### ISSUE TITLE
Possible to limit adult results in search?

### ISSUE THREAD

**Issue by meesterexx** [Tikipeter/repository.tikipeter#1]
The issue occurred when I searched on the anime movie Akira, and multiple hardcore adult titles were returned, some with explicit covers.

I looked through the settings and the only thing I could find was for removing adult results from Easynews, but that doesn't have an affect on the raw search results returned. Did I possibly miss a setting somewhere?

In addition, I have Fen custom search strings integrated into the skin so searches can easily be done from the home screen, and since this is on our main TV, I would like to avoid my pre-teen child being exposed to this accidentally if possible.

I don't see this issue with results from TMDBHelper (also integrated into the skin) so if it isn't possible to add an option to exclude adult results in search, I could remove Fen custom search strings from skin integration and use the TMDBHelper player to launch in Fen as a work around. I prefer not to do this if possible because I sometimes get some extra search results with Fen and it launches faster directly rather than through the player.

Thank you and so glad you're back!

**Comment by Tikipeter** [comment]
That's not a good situation. On the other hand, TMDb classifies movies that aren't really "adult" as adult, so there's a need to have access to them as well.

I'll have a look and see what I can come up with.

**Comment by Tikipeter** [comment]
![screenshot00000](https://user-images.githubusercontent.com/28930002/181863652-e22d360b-e167-4837-a277-31d222fef466.png)

New setting next update. Be sure to turn it ON, as it will be OFF by default.

**Comment by Tikipeter** [comment]
Actually, it will be "Include Adult Content". So you will need to uncheck it. Just to keep things consistent.

**Comment by wormyragtime** [comment]
> ![screenshot00000](https://user-images.githubusercontent.com/28930002/181863652-e22d360b-e167-4837-a277-31d222fef466.png)
> 
> New setting next update. Be sure to turn it ON, as it will be OFF by default.

Which skins is this in the screenshot? I like it.

**Comment by Tikipeter** [comment]
It's just an old skin I made many years ago. It's very ugly and basic by today's standards (trust me), but I keep it around because it's fast and I'm used to it.
