### ISSUE TITLE
Set vieuw (at tools) bug. 

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#10]
I don't know if it is only me (could be), but at tools, set vieuw, the settings do not stick, if that is correct English (or not saved) in Aeon nox silvo mod skin.
On other addons (like Venom as a example) the set vieuw settings are saved, and working. 

If you need more info, or log (I need help with that, on how to do a correct logging) that is no problem also. 

Further I have zero issues, the addon is working fantastic, and the scrape times are fast also (I use the check cached torrents function also, also nice)

**Comment by Tikipeter** [comment]
Hi Tinuz97.

The view set is a little hit and miss on kodi 18, but it does work nearly all the time, and works fairly well for me.

Make sure you click on the 'Set View and then Click Here' list item after you have changed the view to what you want for it to save in the database.

I'll look at the Aeon Nox skin and see if there's anything different going on. Shouldn't be though.

**Comment by Tinuz97** [comment]
Thx for testing, trying a clean install shortly (going to sleep now)

**Comment by edb64** [comment]
I have found that the view settings do not always stick on several addons in 18.3. Makes me think it's more of a Kodi issue than a Fen issue. Have Movies set to Thumbnails and randomly a page will come up in List view. And again I have experienced this in Fen and in other addons. 
 BTW, Mr. Tikipeter... Great job with all of the "enchantments" you have added lately 👍 Seriously bro, love this addon and appreciate all the great work you do!

**Comment by Tikipeter** [comment]
Thanks edb64. :)

I've found the same as you regarding view settings. It always worked in Kodi 17 and earlier, so I agree it's to do with 18.x. Plenty of little things started not quite working right in Kodi 18. It was a big update so it will take them a while to iron the small problems out.

In saying that, the Kodi Team has never wanted add-ons to set their own views, saying that the skin should do that automatically. That has never worked with add-ons.

**Comment by Tinuz97** [comment]
I fixed it by deleting VieuwModes6.db In userdata, database.
Did set it again with Fen, and now the skin does remember the settings I like (shift). 
Maybey the file was corrupt, no idea, but does work fine now. 

Can be closed this ticket.

**Comment by edb64** [comment]
Thanks, I will try that and see if it works for me too. 👍

**Comment by Tinuz97** [comment]
> Thanks, I will try that and see if it works for me too. 👍

I did google the file, and came across this. So i just deleted it (need to set vieuws again in every addon)  

ViewModes#.db

Kodi stores the selected view type for every path in every skin. This enables different view types for different parts of the library. This database contains the last set view and sorting method for each path while navigating Kodi.

The current stable release of Kodi is using the following version of the database:

Kodi v18 - ViewModes6.db

**Comment by Tikipeter** [comment]
Good stuff Tinuz97. I'll close this with the caveat that add-ons setting view types doesn't work as well in Kodi 18 as it did in earlier versions, so you still may have it not switch correctly sometimes. Unfortunately, that is currently the way it is.
