### ISSUE TITLE
After update to 3.0.06, Kodi consistently crashes

### ISSUE THREAD

**Issue by ivarbrandt** [Tikipeter/repository.tikipeter#10]
Hey, welcome back! 

Before I go into it I just want to let you know how HAPPY I am that you and Fen are back! I was crushed when you took it down so I'm elated that you're back. I've said it once and I'll say it again, Fen is single-handedly the BEST Kodi add-on I have ever used! 

So I have one request and one major issue. 

For my request I was wondering if you could please bring back the alphabet sorting to the "Jump To" feature instead of just page numbers. I have a big Trakt collection so I really miss that feature.

And now for the major issue, I updated to version 3.0.06 that was recently released and it instantly showed me an error. Shortly after the error, my Kodi crashed. I tried opening Kodi back up and it crashed again shortly after I opened it. I also tried opening Fen and it loads for awhile and then crashes the Kodi as well. I monitored the memory usage in Kodi and for some reason the memory just keeps falling until it crashes. To make sure it was Fen that was causing this I quickly disabled the add-on after Kodi started up and it didn't crash, memory usage was stable too. I also tried a previous version of Fen (3.0.04) and it ran smoothly. I then performed the update to 3.0.06 and the consistent crashing continued. Idk what's going on but when you get a chance please look at the attached log.

Thanks again and welcome back!

[kodi 2.log](https://github.com/Tikipeter/repository.tikipeter/files/9254474/kodi.2.log)

**Comment by Tikipeter** [comment]
https://github.com/Tikipeter/repository.tikipeter/issues/9
