### ISSUE TITLE
Feature request.

### ISSUE THREAD

**Issue by ricinga666** [Tikipeter/repository.tikipeter#100]
Hi Peter

Further to my suggestion the other week regarding the library update at set time in the night.

Would it also be possible when items are added to the library that they are added with the release date rather than the actual date added.
Regards Richard

**Comment by Tikipeter** [comment]
I've read this a few timee

**Comment by Tikipeter** [comment]
I've read this a few times now, and I'm still not sure what you mean. Do you mean the order in which the new episodes are displayed in a widget?

**Comment by ricinga666** [comment]
No strictly a widget. But had the same principle and yes it's about the ordering of episodes.

Under the current system a series I add to my trakt list will show as the newest episode regardless of how long

**Comment by ricinga666** [comment]
I believe all the old metalliq forks used to offer this as a menu setting to either add to library as release date or date added.

Of you need more info.  I can take some screen shots.tomorrow evening.

**Comment by Tikipeter** [comment]
Please let me know how you are accessing this list of newest episodes.
Is it through Kodi's built-in 'Recently added episodes' or through other means e.g. Fen has a Kodi Library menu for 'Recently Added Episodes'.

I don't think there's anything I can do if you access this list through Kodi's 'Recently added episodes'. That list is formed by accessing a built-in Kodi .xml file that points to 'videodb://recentlyaddedepisodes'. That can't/won't be changed.

**Comment by ricinga666** [comment]
Yes the live background is generated from the recently BV added episodes feature within Kodi.

It must be possible as it's been a feature in the old metalliq forks I think metaliq 4qed and chappaai still have this as an option in the settings.

**Comment by Tikipeter** [comment]
OK. I downloaded an old zip of metalliq forked and I see what they are doing. They are editing the time the OS sets as for when the files are created and modified to the release date of the episode. This is a nice feature which I didn't know the os python module could do, and should be something I can do in Fen. Leave it with me (and by "leave it with me", I don't mean I'll stew over it for a couple of days and then put it in the too hard basket, like I seem to have done with your 'update timer' idea. I'll get back to looking into that, I promise).

**Comment by ricinga666** [comment]
No worries bud.  I'm just throwing stuff out there.  The hard works all on you and I really appreciate your commitment drive and effort to keep making this add-on better and better.

**Comment by Tikipeter** [comment]
This should be done for next update. There'll be a setting in Settings->Subscriptions->Updates->Set Added Time to Release Date to turn this on.

Unfortunately, this setting will only work going forward, so if you want your current library to reflect this setting, you would have to remove and clear the source from Kodi's library,  then remake the strm files through Fen and rescrape into Kodi library.

**Comment by Tikipeter** [comment]
The subscription daily timer has been added for the next update.

**Comment by ricinga666** [comment]
Great stuff bud.  I'll give you some feedback once it's updated.

**Comment by ricinga666** [comment]
Hi Peter 

Seems to be working ok apart from a little glitch.  All the episodes add as per the air date except for the first episode in a series which shows  as the date added to library

**Comment by Tikipeter** [comment]
Interesting. I'll open a new issue myself with this subject and look into it.
