### ISSUE TITLE
Error at discover movies or tv-shows

### ISSUE THREAD

**Issue by chrisnikol** [Tikipeter/repository.tikipeter#100]
After the last updates is not working some options from the discover movies or tv-shows at FEN

Both at movies and tv-shows id you use the option discover recomended return an error.

Error also return at discover tv-shows when you chooce networks. Normaly should load the list with networks but return an error message instead.

Since those errors are easy to reproduce i am not including a log file, but if a log file required i will upload as soon as posible.

Thank you.

**Comment by Tikipeter** [comment]
Appreciate the report. I'd caught the "Recommended" error and it was fixed for next release, but I had missed the "Networks" error in DISCOVER: TV Shows.

All will be fixed for next update.
