### ISSUE TITLE
Can’t update fen or any other addons in kodi 19.4 or 19.5

### ISSUE THREAD

**Issue by Blockr22** [Tikipeter/repository.tikipeter#101]
Hi, didn’t know where to post this issue but i m really sorry if this is not the right place to ask this question but i m really stuck with my parents kodi builds & need answers to resolve it. There setup is kodi 19.5, fen & seren repo’s with addons installed. AH2 for skin & tmdb helper for ratings & stuff on Tcl c725 android tv & connected to jio fibre through wifi connection. Everything installed just fine from repositories a month ago but when i checked for updates yesterday both on there tv & laptop getting errors failed to update. Nothing is updating in kodi. What can be the problem?

**Comment by SJ50** [comment]
@Blockr22 I had a same issue with both Fen and Umbrella, just wait for it to update. In my case it took 10-15 minutes, may be more.

**Comment by Blockr22** [comment]
@SJ50 i have tried manually checking for updates & even force updates from open wizard but it seems like its not even checking for updates for some addons like fen & seren. Only shows available updates from AH2 & tmdb helper but those don’t update even i try manually updating

**Comment by Tikipeter** [comment]
Post a log. Within should show if Kodi can't connect to repos.

As to why, I doubt I'd be able to answer. You need a "clean" Kodi install (no addons like Fen) and then provide a log to the Kodi devs.

**Comment by Blockr22** [comment]
Thnx @Tikipeter i will try that & post a log

**Comment by Blockr22** [comment]
@Tikipeter hi dev can u plz have a look here & let me know what can i do to resolve this 
https://pastebin.ubuntu.com/p/ffZN4qKxqk/
