### ISSUE TITLE
Enhancement (Auto clean settings file, obsolete settings )

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#101]
I did see that The Oath has borrowed that piece of code (with credits for you), but he did a little thing extra:
After a new version of the addon, the obsolete settings are getting automaticly removed (with a nice pop-up that it removed obsolete settings)

Maybey a idea to integrate that nice option in Fen also?

The Oath Github: 

https://github.com/host505/plugin.video.theoath

**Comment by Tikipeter** [comment]
It's not really needed for Fen, Tinuz97. The settings don't change that often. :)
