### ISSUE TITLE
Trakt

### ISSUE THREAD

**Issue by sblair77** [Tikipeter/repository.tikipeter#102]
Constant Trakt load time errors. I contacted trakt but they said "We’re aware of the timeout issues on the website and API. It appears to be related to some apps incorrectly syncing data. 

If you’re an app developer, please ensure your app correctly syncs data and handles error conditions."

Any luck we may get an update for FEN that resolves this?

**Comment by xyzfre** [comment]
Yup I’ve been having the same issue I just literally try re authorizing Trakt but still get a timeout error

**Comment by Tikipeter** [comment]
You want me to update Fen to resolve Trakt's current API issues? I don't know what you're talking about. I can't do anything about Trakt problems with their API. Just be patient until they fix the issues.

**Comment by sblair77** [comment]
Ok. I don't know how FEN syncs with trakt so when they told me to contact the app developer that's what I did. Seems like it's been months that it times out. I'll just hang tight.

**Comment by Tikipeter** [comment]
It's not been months. If it has truly been for you, then something else is going on.
