### ISSUE TITLE
Fen  addon,  Filepursuit. 

### ISSUE THREAD

**Issue by Greg0580** [Tikipeter/repository.tikipeter#102]
Hi.
I have added Filepursuit  api key to the Fen Coco Scrapers Check it and it is Correct it is  enable and I press OK. But unfortunately I can't Find any Filepursuit links at all .   For a Movie or TV show.  But I can try for the same movie or TV show on another Addons and they Show Filepursuit link/s. I have a Feeling that I have missed something or made a mistake somewhere in setting up Fen
Greg.

**Comment by Tikipeter** [comment]
No Filepursuit in Fen.

You must use Umbrella if you want to use Filepursuit.

**Comment by Greg0580** [comment]
OK  did not know that thank you for your Quick Response.
Greg.



Sent from my Galaxy



-------- Original message --------
From: Tikipeter ***@***.***>
Date: 30/12/22 15:27 (GMT+12:00)
To: "Tikipeter/repository.tikipeter" ***@***.***>
Cc: Greg0580 ***@***.***>, Author ***@***.***>
Subject: Re: [Tikipeter/repository.tikipeter] Fen addon, Filepursuit. (Issue #102)


No Filepursuit in Fen.

You must use Umbrella if you want to use Filepursuit.
