### ISSUE TITLE
Premiumize download failure for files. 

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#103]
I did wait a couple of days to report this, because I thought it is maybey a Premiumize issue (maybey it is, no idea, can't find anything helpful in the kodi log). 

if I use Realdebrid, it is downloading fine, without the error in the screenshot, any idea? or a tip how I can log this one so you can have a better look at it? 

Thx and greetings :+1: 

![Screenshot_20200108-020332](https://user-images.githubusercontent.com/47715606/71941840-7cc2ad80-31bb-11ea-9202-a56f980655f0.jpg)

**Comment by Tinuz97** [comment]
Ps, the file that is selected is playing fine, so the file is there (cached) on the server.

**Comment by Tikipeter** [comment]
Hm, I can confirm this. Strange that both RD and AD are working. Give me a few hours and then I can look into this Tinuz97.

**Comment by Tikipeter** [comment]
This is fixed for next update.

**Comment by Tinuz97** [comment]
Nice, thx as usual 👍

**Comment by Tinuz97** [comment]
Fix working, thx.
