### ISSUE TITLE
Feature Request: Sort by seeders

### ISSUE THREAD

**Issue by woxie** [Tikipeter/repository.tikipeter#104]
Greetings, would it be possible to implement sorting streams by amount of seeders? The reason for this petition is that the more seeders a torrent has, the more likely it is to have better subtitle support (due to its popularity). 

Here's an example:
![2022_12_30_15_27_14](https://user-images.githubusercontent.com/33608237/210113412-c9622151-5cfe-417b-9d33-8dcc12cd4699.png) 
![2022_12_30_15_43_23](https://user-images.githubusercontent.com/33608237/210113582-da28ccec-425e-4e87-99f4-7b1e6a589f78.png)<img src="https://user-images.githubusercontent.com/33608237/210113665-6c69e11d-132e-4066-9149-48cf3937706e.JPG" width=39% height=39%>

**Comment by Tikipeter** [comment]
I'm afraid there is a moratorium on requests involving sorting and filtering.

No more sorting can be added until I re-write the entire sorting code.
