### ISSUE TITLE
Feature request - add Show/Movie to Favorites manager faster

### ISSUE THREAD

**Issue by barronen1** [Tikipeter/repository.tikipeter#106]
Hi,
Is it possible to configure Fen to have the "add tv show/movie to fen favorites" button on the first menu, when holding on a TV show/movie?

Instead of clicking on Options --> Favorites Manager
(default Kodi "Add to Favourites" button is confusing)

Bar

**Comment by Tikipeter** [comment]
Not possible, due mainly to a stringent rule of not having any more than Extras and Options in the context menu.

If you're adventurous, you could enable Settings->Navigation->Custom Actions->"Open Fen Options Instead of Kodi Context Menu (for Media)".

That will bypass the context menu altogether and open the Fen options menu when you press the context menu button. Doesn't work well on lesser hardware and is experimental.

**Comment by barronen1** [comment]
Thank you. 

By the way, is it possible to  synchronize “Fen” Favorites (Not Kodi favourites.xml) between devices? based on trakt account or maybe a “Fen” account for this data synchronization?

**Comment by Tikipeter** [comment]
Not really. It is a purely local database.

You could copy the `favourites.db` between installs and then they would match. But there's no way to access the database from one install to another.

**Comment by barronen1** [comment]
Thank you very much,

The reason I’m asking is because I’m creating my Kodi build Using OpenWizard code which mainly based on Fen, so I wanted to exclude Fen favorites between build updates. 


Are the rest of  .db files in userdata directory can be useful for more interesting data keeping between installs, that maybe I’m not aware of?

**Comment by barronen1** [comment]
![D7276890-A660-4E98-B551-C70EB1C1EBFD](https://user-images.githubusercontent.com/29895680/210462218-35888196-eb34-47d8-8c77-a97c29b9d0fb.jpeg)

**Comment by 2kdevs** [comment]
> ![D7276890-A660-4E98-B551-C70EB1C1EBFD](https://user-images.githubusercontent.com/29895680/210462218-35888196-eb34-47d8-8c77-a97c29b9d0fb.jpeg)

I believe views and watched are mostly for local storing of view and watched history (if you're not using trakt) though I might be wrong

**Comment by Tikipeter** [comment]
* `debridcache.db` - Stores the cached status of torrent results for each debrid service.
* `favourites` - Stores your movie/tvshow favorites.
* `maincache.db` - Stores other data not covered by these other db's.
* `metacache2.db` - Stores all the metadata for movies/tvshows accessed through Fen.
* `providerscache.db` - Stores scraper results.
* `traktcache.db` - Stores data relevant to your Trakt account. Watched history/lists etc.
* `views.db` - Stores the "views" you have set for current skin.
* `watched.db` - Stores your watched history if not using Trakt.

The other db that might be useful to share between builds would be the `navigator.db`. This database stores the content and order of the Fen menu system. If you have set up custom items or re-arranged/removed menu items from Fen, that information is stored here.
