### ISSUE TITLE
Feature request and bugs finding

### ISSUE THREAD

**Issue by cabban** [Tikipeter/repository.tikipeter#106]
I have some problem. 
When I search a movie I find no results works in others only to test . The text is correct
Option I search 1st born in fen on result in others addons many result first born 1st born etc. 
Today from discover nothing loads 
It working little slow now unfortunately
Many fake links many not even works or buffering

Request
When auto page have a option to go back to previous page 😀 thank u for all you do.

**Comment by Tikipeter** [comment]
All the things you say are not working are working for me:
* Results for 1st Born: WORKING
* Discover: WORKING
* Speed of add-on: NOT SLOW (What part of the add-on is slow for you?)
* Fake Links: NO MORE THAN NORMAL

Request:
The way Auto Page works makes it not possible to do this.
