### ISSUE TITLE
Feature Request - episodes with no air date

### ISSUE THREAD

**Issue by les017** [Tikipeter/repository.tikipeter#107]
Hi TP, Happy New Year

Would it be possible to add to Navigation Settings - Ignore Episodes with No Air Date?

I use In Progress Shows because we like to see remaining number of episodes of a series/season. We would also normally like to Show Unaired Episodes.  But there are some series that list episodes that have no air date (show up in red) and they really clutter up the series episode list.  As far as I can see they can not be marked off or deleted. 

If I set FEN to not include unaired episodes they are properly hidden in episode list but still count in episode totals on the series poster.  I included pic of poster of a show that is watched complete yet still indicated the 12 unwatched shows with no air date.

Thanks
![PXL_20230102_222757549](https://user-images.githubusercontent.com/236296/210282045-10fd7d67-6322-4cab-90a3-0d021d52dd0a.jpg)
![PXL_20230102_222811732](https://user-images.githubusercontent.com/236296/210282048-3587e6fb-608f-4199-be08-401a3fdec6ef.jpg)

**Comment by Tikipeter** [comment]
I've removed the check on episode dates when marking as watched for next update, which will fix this issue.

This is a prime example of something where the community can give back. There are missing episode dates on TMDb for all of Season 2. TVDb has the airdates for all of the episodes in Season 2. One could copy those airdates into the info within TMDb if one were so inclined, and help to make their data more complete.

**Comment by les017** [comment]
Ah, great point about community. I tunnel-visioned my problem and didn't really assess the root cause. Thanks not only for the great add-on but the reminder that we can all contribute!
