### ISSUE TITLE
ANNOUNCEMENT: Trakt Issues...

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/repository.tikipeter#107]
Currently, there are Trakt API and server issues. If you use Trakt in Fen, then there will be all kinds of erratic behavior to do with watched statuses, loading of Trakt lists, occasional slow loading of ANY lists.

There have been MULTIPLE Issues started within the last couple of days concerning problems related to the Trakt issues despite the OP often knowing about Trakt currently being problematic.

I CANNOT FIX THE TRAKT API/SERVER ISSUES AND I CANNOT REASONABLY INVESTIGATE WHAT MAY BE ANY LEGITIMATE FEN BUGS WHILST TRAKT IS HAVING ISSUES. HOLD OFF ON POSTING ISSUES THAT MAY BE RELATED TO TRAKT'S CURRENT INSTABILITY.

From this point in time, up until Trakt has stabilized, I will be deleting Issues that I deem are related to the Trakt problems WITHOUT commenting in the issue's thread. Please do not take offence to this.

**Comment by techecoyote** [comment]
Thank you for your reply. No offense taken. Again, Great work, thanx for the Hard Work...

**Comment by xyzfre** [comment]
Thank you for your response definitely no offense taken ,,thank you for all your hard work Fen is the best

**Comment by xyzfre** [comment]
Trakt posted on Twitter last night they added more servers to address the issues,, on my end already seeing A big improvement
