### ISSUE TITLE
not issu

### ISSUE THREAD

**Issue by jigoop1** [Tikipeter/repository.tikipeter#108]
hi @ tikipeter
for folder scraper if you can add following it will only scrape the folder which have define paths instead of all 5 folders.
```

	def get_folderscraper_info(self):
		# folder_info = [(get_setting('%s.display_name' % i), i) for i in folder_scrapers]
		if self.media_type == 'movie': source_dir = '%s.movies_directory'
		else:  source_dir = '%s.tv_shows_directory'
		folder_info = [(get_setting('%s.display_name' % i), i) for i in folder_scrapers if not get_setting(source_dir % i) in (None, 'None', '')]
		return [i for i in folder_info if not i[0] in (None, 'None', '')]
```
thanks
btw i have seen you have implemented some ware but i forget where it was.

**Comment by Tikipeter** [comment]
Thanks jigoop1.

There is a check within the folder scraper code to not scrape the directory if it does not match the media_type, but I agree it would be better checked earlier on.

I'll include something next update.
