### ISSUE TITLE
First episode incorrectly tagged when adding to library and using release date as added time

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/repository.tikipeter#109]
Reported by ricinga666...

>Seems to be working ok apart from a little glitch. All the episodes add as per the air date except for the first episode in a series which shows as the date added to library

I'll look to see what is happening here...

**Comment by Tikipeter** [comment]
I cannot replicate this.
Could you browse in a file manager to the actual files and make sure the wrong date is tagged on the first episode file?

**Comment by ricinga666** [comment]
Yes the file information had date added set as as the date it was added and no release date, however I've just removed one of the shows and re added it and it's come back as the release date.  I think it must be something to do with the trakt API problems.  I was getting weird stuff happening all night last night.

**Comment by ricinga666** [comment]
Hi Peter,.  I've just done a complete fresh install and this issue still exists.

The first episode of every show that I add via my trakt list shows as. The date added to the library all other episodes show as the release date as expected.

**Comment by Tikipeter** [comment]
OK. Thanks @ricinga666.
I'll have a much better look at this now. It's obviously failing on that first episode, and falling back to the default. It is strange though that it works on all subsequent episodes.

....Damn. I've just tries this on 3 series and it marked each episode correctly.

I'll include some logging in the next release ricinga666. If you could add any series, and send me the log afterward, that would be great. Just delete the series folder created so it doesn't get added to your Kodi library.

I just thought of something else: is the folder for your TV Shows on another device within your network?

**Comment by ricinga666** [comment]
Hi Peter yes my setup is duplicated on 3 devices on my network.

**Comment by ricinga666** [comment]
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/4091268/kodi.log)

Hi peter added watchment to my list.

**Comment by Tikipeter** [comment]
Thanks a lot @ricinga666

I've made some changes for the next release (v.1.5.89). Let me know if you have anymore success with that release. Fingers crossed.

**Comment by ricinga666** [comment]
I have cleared the subscriptions and readded everything to the library (see my other thread) and everything now appears to have been added at the release date as expected.

**Comment by Tikipeter** [comment]
That's good news ricinga666.
I'll close this issue, as I can continue on with the Subscription problems on the other issue created. :)
