### ISSUE TITLE
[Request] Option to treat Specials Season 0 same as other Seasons

### ISSUE THREAD

**Issue by Ade-AV** [Tikipeter/repository.tikipeter#109]
Hi

When 'Show TV Show Specials When Available' is on and the view is set to Unwatched and there's an unwatched Special then Season 0 will only show if any episode in any of the other Seasons is also unwatched

An example of this is Ghosts (2019), a Christmas Special recently aired but doesn't appear as unwatched as all other Seasons are watched

Thanks

**Comment by Tikipeter** [comment]
>...the view is set to Unwatched...

What does this mean please?

**Comment by Tikipeter** [comment]
I'm steering away from these types of requests that will likely help exactly one person, and to implement it is a lot of work, and it only serves to make things slightly easier for said person.
