### ISSUE TITLE
Add Subcene for subtitles  if you can 

### ISSUE THREAD

**Issue by hishamaltmimy** [Tikipeter/repository.tikipeter#11]
Hello guys, great work, can you add Subcene to subtitles it as a site.  Awesome and has a lot of international subtitles

**Comment by Tikipeter** [comment]
I'll look into this when I can.

I've written it down in the to-do list.

**Comment by hishamaltmimy** [comment]
Thanks man 😊مرسل من هاتف Samsung Galaxy الذكي.
-------- الرسالة الأصلية --------من: Tikipeter ***@***.***> التاريخ: ٤‏/٨‏/٢٠٢٢  ١٠:٠٤ م  (GMT+03:00) إلى: "Tikipeter/repository.tikipeter" ***@***.***> نسخة: hishamaltmimy ***@***.***>, Author ***@***.***> الموضوع: Re: [Tikipeter/repository.tikipeter] Add Subcene for subtitles  if you can  (Issue #11) 
I'll look into this when I can.
I've written it down in the to-do list.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Tikipeter/repository.tikipeter/issues/11#issuecomment-1205662207",
"url": "https://github.com/Tikipeter/repository.tikipeter/issues/11#issuecomment-1205662207",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by tundrablasen** [comment]
Just install the a4k subtitles addon. It has subscene and many others included. And works perfectly with FEN

**Comment by hishamaltmimy** [comment]
مرسل من هاتف Samsung Galaxy الذكي.
-------- الرسالة الأصلية Movies are gone from the collections folder, and it's empty
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Tikipeter/repository.tikipeter/issues/11#event-7158466547",
"url": "https://github.com/Tikipeter/repository.tikipeter/issues/11#event-7158466547",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
