### ISSUE TITLE
fen future request:official addons like netflix

### ISSUE THREAD

**Issue by ananias47** [Tikipeter/repository.tikipeter#110]
thank you for your great work 
i want if it is possible to scrap netflix through fen like "promise" addon it will very usefull

**Comment by Tikipeter** [comment]
I really don't see the benefit of these being included.

Once the novelty's worn off, what do they really provide apart from another source?

Why would you even have subscriptions to these services if you are using an addon like Fen?

**Comment by ananias47** [comment]
hi again my friend i use my brothers netflix because some series and movies from netflix its hard to find it on kodi via rd

the reason i want to include it on fen is because if i open a series from netflix addon throw fen it will be update trakt that i have seen this specific series otherwise if i open directly from netflix addon it doesnt update trakt  ps i also user standalone trakt addon
