### ISSUE TITLE
A New Feature Idea

### ISSUE THREAD

**Issue by flhthemi** [Tikipeter/repository.tikipeter#110]
Was thinking how cool it is to be able to edit menu lists and had an idea. Add an option to create a folder then one could add to it some trakt lists like so...

Main Menu
  Movies from Trakt <User Created Folder
    Now I can add just Trakt Movie Lists allowing me to separate movies from TV Shows!

Just a thought I dunno if it's even possible.

**Comment by Tikipeter** [comment]
I used to have a "Favorites" folder a while ago, where you could put different menu items/lists. Don't know why I got rid of it. Wish I kept the code!
Anyway, this would be similar in structure, so should be do-able. Give me a few days, though.

**Comment by Tikipeter** [comment]
This will be ready for the next update. There will be a Fen Tip for using this feature in Tools->Fen Tips.

**Comment by flhthemi** [comment]
Man!!! I love it!! Seems to be working great!!

I can't say thanks enough!!

I have several installs of Kodi w/Fen on all of them. Can I copy the navigator.db file to all the others now that I have it setup on one install? :) I'm a lazy boy!

**Comment by Tikipeter** [comment]
Yep, the navigator.db will work for each install. Or, at least, I can't think of why not.

**Comment by flhthemi** [comment]
> Yep, the navigator.db will work for each install. Or, at least, I can't think of why not.

Yup that did the trick...so if anyone else wants to know once you have Fen's Menu like you want it just copy **_navigator.db_** to the Kodi\userdata\addon_data\plugin.video.fen folder. Uniformity is actually what I'm after :)

Thanks again!! Fen is great!
