### ISSUE TITLE
Highlight a link

### ISSUE THREAD

**Issue by ilan316** [Tikipeter/repository.tikipeter#111]
Selecting a movie or a series gives big list of links to choose from. 
Once I choose one of them that I like, how can it be saved or somehow highlighted when I will want to use that link again to continue watching the movie if I stopped in the middle.

**Comment by Tikipeter** [comment]
Not possible unless you use RD and turn on cloud scraping and sort the results to top and/or check before full search.

**Comment by ilan316** [comment]
and how i do that ?
