### ISSUE TITLE
Possible bug and feature suggestions

### ISSUE THREAD

**Issue by cabban** [Tikipeter/repository.tikipeter#111]
Hello. I Uninstalled fen then it's working better.
But when I browse for subtitles then it's freeze and crashes 
I tested in exodus it working to browse

Suggestions 
Movie and TV show info and plot option to change language to ex Swedish if it's possible
😀
I hope u can check😀

@Tikipeter

**Comment by Tikipeter** [comment]
Hi cabban.
1. Please tell me what language you have selected for subtitles.
2. To change language navigate to the Settings menu WITHIN Fen, then choose EXTERNAL (META): Tikimeta Settings. Go to Language->Set Language for Metadata and change it to Swedish.

**Comment by cabban** [comment]
> Hi cabban.
> 
> 1. Please tell me what language you have selected for subtitles.
> 2. To change language navigate to the Settings menu WITHIN Fen, then choose EXTERNAL (META): Tikimeta Settings. Go to Language->Set Language for Metadata and change it to Swedish.

Swedish 
English on subtitles 
Ok thank u 😀

**Comment by Tikipeter** [comment]
I've added some brief logging to subtitles for the next release of Fen. Please wait for that release and retest. If you still are experiencing problems, send me a log here and I will look further into this.

In saying that, I think I remember you having troubles with other functionality, and often it led to Kodi freezing and crashing. A failure to download a subtitle should not cause Kodi to crash entirely. I really feel something has gone wrong with your setup cabban, and a log might also help with that..

**Comment by cabban** [comment]
> I've added some brief logging to subtitles for the next release of Fen. Please wait for that release and retest. If you still are experiencing problems, send me a log here and I will look further into this.
> 
> In saying that, I think I remember you having troubles with other functionality, and often it led to Kodi freezing and crashing. A failure to download a subtitle should not cause Kodi to crash entirely. I really feel something has gone wrong with your setup cabban, and a log might also help with that..

No you misunderstood me, not crash only a freeze and windows pop up kodi not answering I need manually end kodi. 
I have a problem  now nothing loads openscrapper is not loading or none source is found 🤨

**Comment by Tikipeter** [comment]
@cabban
Turn off ALLUCXYZ in Openscrapers and then clear the External Provider cache in Fen and that should resolve your new issue.

**Comment by jeanguy2** [comment]
Have the exact same problem. what is the pathway to the "External Provider cache" to clear it. Fen's tool section has "Clean Settings Files" and "Clear list & Data Info".  Can't find "Clear external Provider Cache"?

**Comment by jeanguy2** [comment]
Turned off "ALLUCXYZ" in OpenScrapers/Hosters. Shut down Fen addon and Kodi. Rebooted Kodi 18.5 and Fen addon. Movies now being successfully searched for and suggested links working fine. Thanks for your help and a super add-on.

**Comment by cabban** [comment]
> @cabban
> Turn off ALLUCXYZ in Openscrapers and then clear the External Provider cache in Fen and that should resolve your new issue.

Best are you😀

**Comment by Tikipeter** [comment]
@jeanguy2

For your future reference, if you navigate into that 'Clear list & Data Info' menu item, it will have many items related to clearing Fen data, including the 'External Provider' cache referenced above.

**Comment by jeanguy2** [comment]
> @jeanguy2
> 
> For your future reference, if you navigate into that 'Clear list & Data Info' menu item, it will have many items related to clearing Fen data, including the 'External Provider' cache referenced above.

Thanks a lot for cache clearing info. "Open Scrapers" dev, "addons4kodi" also put out an update yesterday that removed the "ALLUCXYZ" option .  New OpenScrapers version is 0.0.1.102

**Comment by cabban** [comment]
@Tikipeter 
When browse for subs fen and kodi not answering. Not crash only not answering and can't then use it kind regards
