### ISSUE TITLE
Ability to add more debrid services like from resolveurl plugin extension

### ISSUE THREAD

**Issue by ohmichael** [Tikipeter/repository.tikipeter#112]
I thought about buying into linksnappy & others mentioned on resolveurl extension plugin - is there anyway you or possibly umbrella can add it or implement it into the addon fen that way I don’t have to focus just on the main debrid services like RD - I’d like to add all my services to your great pieces of work :)
If you can do linksnappy that’ll help I said the more possibly because I know there’s other people who use different ones that may want the other debrid services on resolveurl added too so I threw it in.
I find the best thing would be to have fun get links from coco & resolveurl & have it listed in settings.
I’m sure it’s possible If not I just threw my two cents in with asking. Hopefully you aren’t mad with my asking :X

**Comment by Tikipeter** [comment]
Nobody uses those services, so it's not worth the considerable effort of implementing them.
