### ISSUE TITLE
Cached torrent problem

### ISSUE THREAD

**Issue by ghost** [Tikipeter/repository.tikipeter#112]
hi i m new fen.i think i made all settings which required for cached torrents.But there is no source finding with rd cached.Is there anything else i can do for?Please help

**Comment by Tinuz97** [comment]
did you authorize ResolveUrl,and FEN? Because for cached torrents FEN needs to have auth also.

**Comment by Tikipeter** [comment]
Hi ghost.
Please check what Tinuz97 has written above and report back if that solved the problem you are having.

Also, if you mean Fen scraping your actual RD Cloud, not just checking torrent results are cached, make sure you have the RD Cache internal scraper enabled in Settings->Internal Scrapers->RD Cloud->Enable RD Cloud Scraper.
