### ISSUE TITLE
Subtitles do not work in Dutch

### ISSUE THREAD

**Issue by peno64** [Tikipeter/repository.tikipeter#113]
When I set the subtitle language in Fen on English, then things work.
If I set the subtitle language on Dutch, I never ever get a subtitle from Fen. I get the popup that it searches for subtitles, then this disapears and I have no subtitle. However if I call the subtitle window from kodi then there is in the list a subtitle from opensubtitles.org with exactly the same name as the filename (except for the extension of course). Even stranger. If I change Download Subtitles Action from Auto to Select then it shows me a couple of subtitles after a couple of seconds after the movie starts, even one with exactly the same name as the movie, but when I choose one, the subtitle is not shown. And if I choose a language for which I know there are no subtitles for, for example Catalanian, I get the message that there were no subtitles found. But for the Dutch language this message is not shown. So from all this I conclude that a subtitle can be found but for some reason it doesn't want to use it.
So what could be wrong here?

**Comment by Tikipeter** [comment]
Hi peno64.
I'll look into this. To help me out, can you give me an example of a Movie/TV Show where there is DEFINITELY a sub available in Dutch. I can then test using that title.

**Comment by peno64** [comment]
Thank you for looking into this.

The TV show "Succession", season 1, episode 1 and 3 for sure.

**Comment by peno64** [comment]
I just discovered something really strange. It is because I use a VPN that I have this issue. I checked this several times and consequently, when I am connected to a Belgian VPN (in Brussels) and I am also living in Belgium, FEN cannot find subtitles. From the moment I disconnect the VPN I get the subtitles. I am very puzzled how this can happen. Note that I do not have a problem when I use the standard subtitle functionality from kodi and select the subtitle from there, also from opensubtitles.org

If you want to investigate this further, I think you could add some extra logging when a subtitle is selected from the popup screen and there log why it is not taken, if that is possible.

**Comment by peno64** [comment]
I use NordVPN on a raspberry pi with the addon VPN Manager for OpenVPN. And I also use Real Debrid to have more and better streams.

**Comment by peno64** [comment]
Another strange this is that when I connect the VPN to The Netherlands then it is working also ok. So not all VPN connections give the problem

**Comment by Tinuz97** [comment]
It's because opensubtitles blocks many vpn's, I had that in the past also with NordVPN (and private internet acces).

**Comment by peno64** [comment]
@Tinuz97 
I could agree with that but then it is still strange that when I open the subtitles dialog from kodi and choose a subtitle from there (from opensubtitles.org) then it does work.
And then also why do I get the list of possible subtitles in FEN. It appears that only getting tthe subtitle file itself is then blocked and then I would also have to conclude that FEN uses another API call to opensubtitles which is blocked because of the VPN.
Strange...

**Comment by Tikipeter** [comment]
Ok, I don't have an absolutely definite answer for you here peno64, but it is likely related to your VPN usage. I could download those subtitles you suggested with and without my VPN, but in saying that my provider does not have a Belgian server, so I could not replicate your issue exactly.

The opensubtitles Kodi add-on most likely uses the old xml api endpoint, which is deprecated. Fen uses the new 'search' endpoint, so there are differences in their interaction with OpenSubtitles that COULD cause one to work and one not work.

For the next release, there will be logging of the response for both searching for and then downloading the chosen subtitle. If you want to replicate the issue and then send me a log here it will show which status code is raised for the failure. I also added headers to the download call. They are not needed for that call, but they don't interfere negatively and it's the only thing I could change to possibly make that call successful. I also removed the try/except code around the calling for subtitles, so if it does fail, you may also see a general Fen script error notification.

Also, if you want to spend a bit of time on this, connect to the Belgian VPN server that is giving you trouble, and navigate to the OpenSubtitles web page. Search for subtitle results, and then try and download a subtitle. If any of that process fails (not likely) then you will know for sure that it's the Belgian server being blocked.

**Comment by peno64** [comment]
@Tikipeter 

Ok, that is fine with me. As I understand you already have that logging code build in. If you point me to the source code I can install that and provide you the log. Even individual .py files I can install. I am a developer myself and know my way quite well in kodi.

**Comment by Tikipeter** [comment]
@peno64

If you reply here with a kodi log now (after v.1.5.88), I will be able to see the response. Alternately, you could have a look and let me know here. The phrase to search for in the log would be "FEN Opensubtitles Download". Let me know what it says after that.

**Comment by peno64** [comment]
###FEN Opensubtitles Search###: <Response [200]>
###FEN Opensubtitles Download###: <Response [429]>

Merk dat het wel degelijk vpn gerelateerd is want als ik naar een ander vpn adres connecteer dan gaat het wel en krijg ik:

###FEN Opensubtitles Search###: <Response [200]>
###FEN Opensubtitles Download###: <Response [200]>

**Comment by peno64** [comment]
response 429 is too many requests. Strange. I would have access denied or something like that expected...

**Comment by peno64** [comment]
Must be related to this: https://forum.opensubtitles.org/viewtopic.php?t=16072

**Comment by Tikipeter** [comment]
@peno64

Yep, almost definitely related to the policy you linked to.

I've re-written the opensubtitles implementation to include a 10 second delay if 429 is in the response. Ideally, I'd like to have info from OSubs about how long before the limit resets, so I could only wait that long, but there is nothing in the headers that gives that info. It only says how many requests are left for that 10 second period.
Anyway, after next update (v.1.5.89) give it a couple of tests with subs on AUTO and let me know if it fixes the problem.
