### ISSUE TITLE
In progress Episodes

### ISSUE THREAD

**Issue by ilan316** [Tikipeter/repository.tikipeter#113]
is the TV shows >>>  progress episodes   working ?

its not working for me , he is not showing any episodes i started to watch and stopped in the middle.
the list is empty.

**Comment by Tikipeter** [comment]
Yes, it is working.

Please read/follow the rules for opening requests.

**Comment by ilan316** [comment]
if you be so kind , can you refer me and to let me know what am i doing wrong
