### ISSUE TITLE
Request: 'Play Next Episode' button in TV Extras screen, and allow customisation of Extras buttons

### ISSUE THREAD

**Issue by iampritesh** [Tikipeter/repository.tikipeter#115]
Hi Tikipeter,

Love the Extras screen, I have it set to open whenever selecting a movie or show; Extras and menu customisation are my favourite parts of Fen.  I have a couple of requests for the Extras screen please, if it's not too much hassle and it's useful for more than just me.

1. Would a 'Play Next Episode' button for TV Shows be possible, to play the episode that is shown at the top of the screen?

2. Is it possible to add a way to customise the buttons that are on the Extras screen?

I'd ideally like the buttons to be as below, but I know everyone uses the Extras screens differently.  I spent a few hours fiddling with the xml and python files before making the request, but I didn't get anywhere.

Movies:

|Play|Trailer|Recommended|Extra Info|
|:--:|:--:|:--:|:--:|
|Trakt Lists Manager|Director|Genres|Options|

TV Shows:

|Play Next Episode|Trailer|Recommended|Extra Info|
|:--:|:--:|:--:|:--:|
|Trakt Lists Manager|Browse Show|Genres|Options|

Either way, thank you so much for the great addon

**Comment by Tikipeter** [comment]
I'm still thinking on this.
My time is limited currently.

**Comment by iampritesh** [comment]
Thanks for considering, much appreciated.

**Comment by Tikipeter** [comment]
1. Done for next update. Swapped "Play Random" button for "Play Next Episode". So at least it's available.

2. I have a good idea of how to implement custom buttons. There wouldn't be an endless amount of function options, but I can add a couple more to what's currently available and then offer the user to place them anywhere within the 8 buttons. I just need to find the time and motivation.

**Comment by Tikipeter** [comment]
OK. The difficult job is finished and all the framework is in place to have custom buttons.

Now just need to write a method to set them. But that won't be half as disruptive.

**Comment by Tikipeter** [comment]
Ready for next update.

Change button actions: `Settings->Features->Extras->"Set Actions for Extras Buttons"`.

You can set the movie and tvshow buttons differently of course.

Reset buttons to default: `Restore Extras Buttons to Default Actions`.

**Comment by Tikipeter** [comment]
A couple of minutes setting up and I got what you wanted above:

MOVIES:
![screenshot00000](https://user-images.githubusercontent.com/28930002/216290873-ecccce47-4287-46f8-a868-140f7a63a51c.png)


TV SHOWS:
![screenshot00001](https://user-images.githubusercontent.com/28930002/216290964-4960849f-6c41-4be4-95e8-dcd1eed357ae.png)

**Comment by iampritesh** [comment]
Wow, thank you so much!  That is absolutely perfect, can't wait for the next update to get it all set up.

Let me know if you have a tip jar or something, would love to throw something your way

**Comment by ReaLx3m** [comment]
@Tikipeter Have one annoyance that is unrelated to this exact issue, but related to extras, so i dont clutter your inbox with issues i figured ill post here. Maybe you can take a look at this too while youre at it with the extras.

https://youtu.be/X0gU6ms1XyU

Video is self explanatory, when youre using a mouse cursor the top menus in extras try to get away from the mouse. How my cursor has wronged them is beyond me :)

P.S.
Btw, .40 works pretty great with EN, and no hangs so far. I assume you rolled the code back to the old way of playback monitoring?

**Comment by Tikipeter** [comment]
Yeah I wouldn't be using a cursor with custom windows.

It's near enough impossible to get a decent user experience with skins and mouses.

There's a reason many skins don't offer mouse support. And they're going to have a better chance than me of implementing it. I'd have to be a skilled skinner to get it right. There's hit areas, and some other stuff I kinda remember from years ago. Many skinners end up throwing their arms up and stating "no mouse support". It's just too hard.

I kept the monitoring code with some more changes, and then offered the ability to disable it. I was hoping some EN users would actually try the new monitoring code, but I understand that most will just want it to work now and turn it off. :) It's been a long running issue.

If the monitoring code is off, then there is absolutely no checking as to whether the file is successful in playback. It handles playback like every other addon, including no ability to retry EN links that fail on the first attempt.

**Comment by ReaLx3m** [comment]
> Yeah I wouldn't be using a cursor with custom windows.

Yeah rarely do use cursor too but thought if its an easy fix why not, since its not an easy fix then good riddance, not a really that big of a deal to begin with.

>I was hoping some EN users would actually try the new monitoring code, but I understand that most will just want it to work now and turn it off. :)

Thats what im saying, been using .40 with monitoring ON for the last few days and havent had a single hang. Hope i dont jinx it :).

**Comment by Tikipeter** [comment]
That's good news, although likely due to EN playing well at the moment.

I'm hoping when it does freeze, and you need to hit back to cancel, then the cancel is registered.

Fingers crossed it will work then.

**Comment by ReaLx3m** [comment]
> That's good news, although likely due to EN playing well at the moment.

We will see. I will continue running .40 for few more days, and if a hang doesnt happen ill go back to .37 to see if it happens there as it used to before with that version.
