### ISSUE TITLE
Library update set time

### ISSUE THREAD

**Issue by ricinga666** [Tikipeter/repository.tikipeter#115]
Hi Peter.

I've noticed a few times lately that if my Kodi crashes and I restart Kodi the subscription update seems to happen.  While this in itself is not a big issue. Once this happens it sets my update schedule from the 0600hrs in settings to the time to 24 hours from the update that just happened.

**Comment by Tikipeter** [comment]
Does it also reset other settings i.e. Does it change the "Update Subscriptions Method" setting back to  "Hourly Intervals"?

**Comment by ricinga666** [comment]
No, the setting remains as 0600hrs.   it just shows the new update time in tools and doesn't change until i reselect the 0600 in the settings.

**Comment by ricinga666** [comment]
Another thing I've noticed is that the fen no longer seems to check the subscription folder with trakt anymore. 

By that I mean if I add a new series to my trakt list I have to clear the subscription list in fen(tools) and then reset the subscription folder witjin settings.  

This is also true of any series I remove from my list.

**Comment by Tikipeter** [comment]
@ricinga666
Man, this Subscriptions code is really kicking my ass!
There were some fundamental issues with the code, I've sorted out as much as I can see, and hopefully it fixes this issue with not accurately reflecting Trakt list changes.
The other issue with the schedule wigging out when Kodi crashes, I'm hoping is fixed but I'm not as confident...
The next update (v.1.5.90) will have these changes. See if it makes a difference.

**Comment by ricinga666** [comment]
The show adding/removing from the list seems to be back working as expected.

So far I've not seen any events that have knocked the update time out of whack.  I have noticed a few random subscription updates that appear to run for no obvious reason. And the update bar looping back to around the 10% mark and then that 10% getting stuck on the display once the update completes.  
I have a suspicion this maybe skin related   though. 

I'll update you as I use the add on more.

**Comment by Tikipeter** [comment]
I appreciate your efforts ricinga666.

**Comment by ricinga666** [comment]
Hi Peter.

My main box doesn't seem to have had any issues ,although weirdly the update time in tools is now showing 2  seconds after 6 as the update time. This box I cleared my fen user data folder.

On my other main main box.  I've had a few issues with fen launching the Library update.  Over the weekend I intend to reinstall Kodi on this box so hopefully this clears any issues and we can close this bug.

**Comment by Tikipeter** [comment]
There are some more small changes to the code for the next update (v.1.5.93). It should fix the '2 seconds' problem, and hopefully make the code a bit more solid. I just feel it's very brittle at the moment, so I'll continue to work on it.
