### ISSUE TITLE
Can there be option to only scrape for Hindi or dual audio prints

### ISSUE THREAD

**Issue by Blockr22** [Tikipeter/repository.tikipeter#116]
Hey Dev, is it possible to scrape for particular audio prints like for Hindi language or only shows prints/files that contains more than 1 audio but specifically have Hindi audio in it.
For example if i look for Venom, there is normal version of this movie that is in English but then there are dubbed prints of almost every movie. I want an option to get only dubbed prints for English movies & shows so that my parents back home can watch these movies/shows aswell. I know there is option in debrid to add torrents but its a pain to look for particular file from torrent & go through so many ads & even if i add it won’t sync with trakt for resume points & also won’t mark as watched when they watch it. I use trakt to add them shows & movies from my ends.

**Comment by Tikipeter** [comment]
There is a moratorium on adding any new sorting or filtering features until I can re-write the code for sorting and filtering. It is not set up at the moment for that sort of filtering.
