### ISSUE TITLE
No Results for TV Shows on Furk

### ISSUE THREAD

**Issue by tekknight** [Tikipeter/repository.tikipeter#116]
I have never gotten any results for TV Shows for Furk. No issues with movies. When I look up for the TV Show on furk’s website, I am able to see it cached.

**Comment by Tikipeter** [comment]
Hi @tekknight 
I am not having this issue. I can't even really think of any reason why you would receive results for movies but not for tv shows. If you provide a log here, after scraping for a tv show, perhaps it will show the reason why...

**Comment by tekknight** [comment]
Hi,
I'm able to get TV Show results with my easy account only, but nothing for furk. For movies, I get results from both. Same issue on another 2 devices. I don't see anything in the logs. Let me know if you see something.

https://pastebin.com/mELWdwXQ

**Comment by tekknight** [comment]
Also, If I go to Premium Services menu in Fen and then search for a video through furk there, it works.

**Comment by Tikipeter** [comment]
I'll include some logging in the next update. Please send through another log then.

**Comment by Tikipeter** [comment]
OK. The next update (v.1.5.90a) will have some logging for the Furk scraper.
Please test with only the Furk scraper active, and send me through the log.

**Comment by tekknight** [comment]
Here is a log with Furk only enabled as the scraper. I searched for a movie first (which gave me a result) and then a TV show (no result).

https://pastebin.com/g6Yzet0f

**Comment by Tikipeter** [comment]
I was quite excited to get home from work, have a look at this log and sort this issue out. Unfortunately, I cannot see anything in the log pertaining to your issue @tekknight. :(
Could you do me a big favor? Could you send me through another log searching for an episode, this time WITHOUT debugging on?

**Comment by tekknight** [comment]
Looks like it's now showing an error in the log with debugging off :)

https://pastebin.com/S9g9rP7n

**Comment by Tikipeter** [comment]
Ahhh!!!! Its an error in the process of trying to GET the error. I'm an idiot.
I'm so sorry tekknight. I'm going to push an update very soon, can you please send me one more log? 
ACTUALLY: It has given me one idea. In the Furk scraper settings (Settings->Internal Scrapers->Furk), turn off 'Include Uncached Results', pick an episode you haven't searched for yet, and see if you get results now. Otherwise, I'll push that update with fixed error reporting...

**Comment by tekknight** [comment]
The 'Include Uncached Results' is already turned off and searching for a new show is still not giving any results.

**Comment by Tikipeter** [comment]
OK. I've pushed v.1.5.90b.
Fingers crossed it shows something. I've got a horrible feeling it's not going to. :(

**Comment by tekknight** [comment]
I don't get anything new in the log after clicking on an episode with debugging off :(
I turned it on and got some stuff but don't think anything is there.
https://pastebin.com/NBBCxqFW (debugging off)
https://pastebin.com/q8NNxfwJ (debugging on)

**Comment by Tikipeter** [comment]
OK. I'm at a loss. Here's what I would do when you have some time to test a few things yourself:

* Clean settings files in Tools.
* Change Results Display to "Dialog".
* In Furk Scraper settings, set "Limit Size of Results" and "Limit Number of Results" to 100 each. Also, set"Search Moderation Level" is set to OFF. Also, change the highlight color of the furk scraper.
* Take notice of the scrape. Does it display FURK as a 'Remaining Provider' on the display whilst you are waiting for a result? Does the scraper take a bit of time before it comes back with no result (over, say, 3 seconds).
* Copy this link and place it in your browser window and hit enter (replace {YOUR API} with your own Furk API key). Does it give a result in the browser?
LINK:
`https://www.furk.net/api/plugins/metasearch?api_key={YOUR_API}&q=@name+The+Witcher+@files+s01e08+|+1x08+|+01x08+|+"season 1 episode 8"+|+"season 01 episode 08"&cached=all&match=extended&moderated=no&sort=relevance&type=video&offset=0&limit=200`
* If you have another add-on that uses Openscrapers, enter your Furk credentials into Openscrapers, turn on the Furk scraper in Openscrapers, and see if that returns TV Show results (although FEN uses Openscrapers, I remove the Furk and Easynews scrapers before scraping with them. So you would need another add-on like Venom or Exodus Redux).

That's about all I can think of....

**Comment by tekknight** [comment]
OMG it works! After some tinkering, I found out I had full moderation search selected on my furk account. After disabling it, it works. Sorry that I had to put you through all that. Thanks for the help.

**Comment by tekknight** [comment]
Quick question, is there a way to sort furk and easy scraper results? I wanted to see all the easy results first.

**Comment by Tikipeter** [comment]
Great that it's working!! The add-on is made for people like you with Furk and/or Easynews accounts. Your issue was really bugging me!

It's my fault it wasn't working, that is a bug in the code to have TV shows not work when moderation is on. I'll fix that for next update.

As for extra sorting, leave it with me. I'll get it done but it'll be harder than it sounds to do. :) :)
