### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by sblair77** [Tikipeter/repository.tikipeter#117]
I can't get the subtitle alert at the top of the screen to go away. I've disabled them and enabled them but it keeps saying "opensubtitles rate limited. retrying in 10 secs..." at the top of the screen every few seconds. Any tips on stopping this?

Thanks! Have an amazing Friday!

**Comment by Tikipeter** [comment]
Close Kodi and restart it. I'll look into why this is happening.

**Comment by sblair77** [comment]
I ent through playback options and turned it off and then cleared lists and settings. It stopped! Of course we can't get the subtitles now but that is ok for now. Thank you!

**Comment by Tikipeter** [comment]
Yeah. Just hold out on using subs until I get this sorted.
Can I ask, are you using a VPN when this is happening?

**Comment by Tikipeter** [comment]
This should be fixed for next update (v.1.5.90a)
