### ISSUE TITLE
Color settings greyed out, bug? 

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#118]
Any idea why these color settings are greyed out?

![Screenshot_20200125-195748](https://user-images.githubusercontent.com/47715606/73125960-3b990e80-3fad-11ea-93b2-3a00e87b1f4a.jpg)

**Comment by Tinuz97** [comment]
Version 1.5.90a, almost did forget that.
Also did the 'clean settings file' option, and did clear all cache in Fen.

**Comment by Tikipeter** [comment]
Hi Tinuz97.
Those settings will become active if you set "Highlight Results Based On..." to "Quality".

**Comment by Tinuz97** [comment]
Oh thx, my bad 😅

**Comment by Tikipeter** [comment]
No worries. :) :)
