### ISSUE TITLE
Request for an old but beloved option (Alphabet sorting)

### ISSUE THREAD

**Issue by ivarbrandt** [Tikipeter/repository.tikipeter#12]
If it's not too much trouble, could you please add back the Alphabet sorting option in the Jump To feature? I find it infinitely more helpful to have the alphabet option vs page numbers. 

Thanks for all you do. Take care.

**Comment by Tikipeter** [comment]
It can't come back working the same way it used to, as the code for it was cumbersome and messy (why I took out the feature).

If I can think of an alternative way to implement this, then I'll put the feature back into Fen as best I can.

**Comment by ivarbrandt** [comment]
Awesome thanks! I look forward to seeing what you come up with.

**Comment by Tikipeter** [comment]
![screenshot00000](https://user-images.githubusercontent.com/28930002/182989039-0a5f2cdf-3616-4c27-a828-c0fbe68167ce.png)

This will be how it needs to work. Still Page based, but you'll have information of the starting and ending alphabetical values for the items within each page.

**Comment by ivarbrandt** [comment]
That looks good! With bigger lists, for example Trakt collections, one whole page might still be on just one letter. So let's say I have a page that starts with the movie "Armageddon" and ends with the movie "The Avengers" So would that show as 
"A - A" or would it have the second or even third letter of the titles, for example "Arm - Ave" ? 

Also could you please add the option to just display the letters and hide the page numbers? I think it would look a lot cleaner that way.
