### ISSUE TITLE
Next Episodes 

### ISSUE THREAD

**Issue by JeanMow** [Tikipeter/repository.tikipeter#121]
"Why doesnt the next episodes  show the airdate when Next Episodes is set as a widget"

**Comment by Tikipeter** [comment]
"Probably the skin doesn't choose to show the `Listitem.Label`".

**Comment by JeanMow** [comment]
This is in Nexus its fine in Matrix

**Comment by Tikipeter** [comment]
OK.

Same answer as above still.

**Comment by Tikipeter** [comment]
But I'll make the title the same as the label for next update so it works for you.

**Comment by JeanMow** [comment]
Thank you much appreciated

**Comment by JeanMow** [comment]
Thank you working great again
