### ISSUE TITLE
Settings - Fen error check log

### ISSUE THREAD

**Issue by JFG1000** [Tikipeter/repository.tikipeter#122]
Hi mate not sure if your aware but if you go into the Fen addon at the bottom and click settings it throws an error message

**Comment by Projectal374** [comment]
### Version 3.0.16 changelog

- Root Menu item "Settings" merged into "Tools" menu.
$\textcolor{red}{\text{The Settings menu item will no longer work, so either remove it from the Root Menu (Edit Menu->Remove Settings from the List),or restore the Root Menu (Edit Menu->Restore Root Menu to Default)}}$

**Comment by Projectal374** [comment]
### version 3.0.16 changelog
- Root Menu item "Settings" merged into "Tools" menu.
The Settings menu item will no longer work, so either remove it from the Root Menu (Edit Menu->Remove Settings from the List), or restore the Root Menu (Edit Menu->Restore Root Menu to Default).
