### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by cabban** [Tikipeter/repository.tikipeter#122]
Remaining sources is there any chanse to add disable  Hosters not working remaining automatically
To speed up scraper searching 😀

**Comment by Tikipeter** [comment]
It's possible. Maybe....

**Comment by cabban** [comment]
> It's possible. Maybe....

Thank u hope and know it's gonna rock 😘😀

**Comment by Tikipeter** [comment]
In the meantime, if you set "**Stop Search Early if Most Sources Finished**" in Settings->External Scrapers->General, then when certain conditions are met the scrape will stop by itself at or after the halfway mark of the search. The formula is: if there are at least 100x the amount of results as sources left, then the scrape will terminate at the halfway mark or any time after the halfway mark, as long as the formula condition is met.

So if there are 500 results at the halfway mark of the scrape, and there are 3 sources, then FEN will stop the scrape (3x100 < 500).

**Comment by cabban** [comment]
> In the meantime, if you set "**Stop Search Early if Most Sources Finished**" in Settings->External Scrapers->General, then when certain conditions are met the scrape will stop by itself at or after the halfway mark of the search. The formula is: if there are at least 100x the amount of results as sources left, then the scrape will terminate at the halfway mark or any time after the halfway mark, as long as the formula condition is met.
> 
> So if there are 500 results at the halfway mark of the scrape, and there are 3 sources, then FEN will stop the scrape (3x100 < 500).

As now I hurry to catch up remaining and disable those but maybe other movies needed that's why I asked the question😀 I have that settings checked already . Kind regards

**Comment by Tikipeter** [comment]
I'm working on this as we speak. I just need to work out the best way to go about it. :)

**Comment by cabban** [comment]
> I'm working on this as we speak. I just need to work out the best way to go about it. :)

Thank u  😀

**Comment by cabban** [comment]
@Tikipeter  i tried it. But remaining providers was the correct name when searching. This is still there and not make the search faster. Am I doing something wrong. Thank u for update. 😀

**Comment by cabban** [comment]
> ![IMG_20200202_095047](https://user-images.githubusercontent.com/19514493/73605675-a21bbf00-45a1-11ea-80cd-066c013ea85a.jpg)
> ![IMG_20200202_095048](https://user-images.githubusercontent.com/19514493/73605676-a2b45580-45a1-11ea-94e9-ae65950ee554.jpg)
> ![IMG_20200202_095051](https://user-images.githubusercontent.com/19514493/73605677-a2b45580-45a1-11ea-87f3-9e2eb6aea94e.jpg)
> ![IMG_20200202_095055](https://user-images.githubusercontent.com/19514493/73605678-a2b45580-45a1-11ea-8a56-b939f66bacf0.jpg)
> ![IMG_20200202_095059](https://user-images.githubusercontent.com/19514493/73605679-a2b45580-45a1-11ea-97b7-323619006379.jpg)
> ![IMG_20200202_095111](https://user-images.githubusercontent.com/19514493/73605680-a34cec00-45a1-11ea-86b3-3827bdf839c8.jpg)
> ![IMG_20200202_095051_1](https://user-images.githubusercontent.com/19514493/73605681-a34cec00-45a1-11ea-85c6-ac1fca416de6.jpg)
> ![IMG_20200202_095057](https://user-images.githubusercontent.com/19514493/73605682-a34cec00-45a1-11ea-9c1f-b5c96f6a625b.jpg)
> 
> @Tikipeter i tried it. But remaining providers was the correct name when searching.. Am I doing something wrong. Thank u for update.  i tried as i say to disable those but maybe they have providers needed next time.

I have end search fast in settings it goes faster, but maybe to remove the remaining is not possible 😁

**Comment by Tikipeter** [comment]
OK. Firstly, change "Sample Size Before Removal" down to 5 (the default is 25). This means once a scraper has been tried 5 times, it will become eligible to be automatically disabled by FEN. The 5 searches have to have been since the last update, because before then nothing was keeping track of the success/failure of the scrapers. So nothing will happen on the first searches after the update.

Once that threshold of 5 searches is reached, FEN will disable the scraper if it has had at least twice as many failures as successes. You can go to Tools->External Scrapers->Disable Failing External Scrapers to see how the scrapers are doing...
![disable_scrapers](https://user-images.githubusercontent.com/28930002/73608327-c1ecca80-4615-11ea-9909-ceb9ad3c15c9.png)

You should see a lot of scrapers be disabled once that 5 searches is reached. Then more will be removed as their failures increase. But there needs to be some amount of results first to base the removal on. If you cut that down to 5, you should see results immediately.

**Comment by Tikipeter** [comment]
As for Pre-emptive Termination, it will stop a search if the two conditions under it in settings are met.

* Pre-emptive Limit is the number of results for a certain quality.
* Pre-emptive Quality is the quality that will be checked.

Examples;
-Set limit to 20 and quality to 720p: Search will stop once 20x720p results are returned.
-Set limit to 300 and quality to All: Search will stop once 300 results in total are returned, of any quality.

**Comment by cabban** [comment]
> As for Pre-emptive Termination, it will stop a search if the two conditions under it in settings are met.
> 
> * Pre-emptive Limit is the number of results for a certain quality.
> * Pre-emptive Quality is the quality that will be checked.
> 
> Examples;
> -Set limit to 20 and quality to 720p: Search will stop once 20x720p results are returned.
> -Set limit to 300 and quality to All: Search will stop once 300 results in total are returned, of any quality.

It's working 😀
