### ISSUE TITLE
Feature Request - Movies by Networks (like in TV Shows)

### ISSUE THREAD

**Issue by barronen1** [Tikipeter/repository.tikipeter#123]
Hi,

is it possible to add networks list in Movies section just like in TV shows?  

(Example: Movies by Netflix/Disney Plus etc..)

Picture from TV Shows - Networks:
![image](https://user-images.githubusercontent.com/29895680/215036812-52794b13-a025-4a62-a955-8a7a5e5383d3.png)

**Comment by Tikipeter** [comment]
There are literally thousands of production companies. So no.

**Comment by barronen1** [comment]
Isn’t It available through TMDV / Trakt?

**Comment by barronen1** [comment]
Updated comment ^
