### ISSUE TITLE
Missing info on OSD screen 

### ISSUE THREAD

**Issue by xyzfre** [Tikipeter/repository.tikipeter#123]
Just noticed with this latest update using AuraMod skin when playing a show or movie The ratings always showed up on OSD screen and the skin also has options to show actors on the OSD screen and now they don’t show up and for actors it says no information ,and prior to this update it always worked with Fen as well been using Fen for a while now and always worked well with the skin Tried with a different addon to make sure it’s not the skin and the ratings and option for the actors works,, sorry to bother and always appreciate all your hard work

**Comment by Tikipeter** [comment]
I changed things in this area last update. I can look at this in a few hours from now. Hang tight until then.

**Comment by xyzfre** [comment]
Much appreciate it and thank you for your response

**Comment by Tikipeter** [comment]
This should be fixed for next update (v.1.5.94)

**Comment by xyzfre** [comment]
Just wanted to say thank you this update definitely fixed the  problem ratings and actors information now show back up👍🏼👏🏼✊🏼
