### ISSUE TITLE
Failed to resolve EasyNews links makes Kodi freeze indefinitely

### ISSUE THREAD

**Issue by Nuklear92** [Tikipeter/repository.tikipeter#124]
Okay, so this doesn't happen all the time but when it does it makes Kodi completely frozen and can't return back to select another source or anything. The only thing to do is to completely quit Kodi from the opened Apps list from the Shield. 

![image](https://user-images.githubusercontent.com/76958541/215193348-9388d52b-7c58-4d0e-9fe2-a22299a843db.jpeg)

This image shows how the spinning wheel becomes frozen after a few seconds pass from resolving a EasyNews link source. It's not like the source is broken, because when I quit Kodi completely and reopen everything and choose the same source link it then plays correctly. 

I'm not getting any error logs or anything it just freeze Kodi completely when FEN fails to resolve the link. Is it possible to make FEN jump back to the menu lists when an easynews source fails to be resolved. Something like a timeout that automatically quits the Source Select/Resolve UI screen so we don't have to quit Kodi completely due to making it completely frozen and even the back button stops working on the Shield TV. 

If there's a timeout implemented for when a source fails to be resolved from EasyNews it seems like it's bugged and it's not returning back to Kodi menu lists, instead just freezing the whole application. When FEN successfully resolves an EN link it does it well, it's only when it fails that it doesn't return back and quit the SS UI screen. 

Here’s a Kodi log, idk if there’s any use for it but just in case. 

[kodi.txt](https://github.com/Tikipeter/repository.tikipeter/files/10523135/kodi.txt)

**Comment by les017** [comment]
@Nuklear92  - are you on latest FEN?  I think .38 had some new code to hopefully try to address this issue. Your issue used to be frequent for me but since .38 I have yet to see the complete hang. So far.....

**Comment by Nuklear92** [comment]
> @Nuklear92  - are you on latest FEN?  I think .38 had some new code to hopefully try to address this issue. Your issue used to be frequent for me but since .38 I have yet to see the complete hang. So far..... 

Yes, I'm on the latest 3.0.39 FEN build.

**Comment by Tikipeter** [comment]
Move to here please:

https://github.com/Tikipeter/repository.tikipeter/issues/118
