### ISSUE TITLE
1.5.94d Broke something...

### ISSUE THREAD

**Issue by JayDee696969** [Tikipeter/repository.tikipeter#124]
Since 1.5.94d, getting No Results in FEN. RD enabled. Quick dirty fix was to delete the FEN userdata. Sot sure exactly what in the update broke the sources. But deleting UD fixes it. Im not the only one, got multiple reports of same issue. Just putting it out there...

**Comment by Tikipeter** [comment]
Unfortunately, since it didn't happen on any of my devices, I have no way of knowing why this happened.....

**Comment by JayDee696969** [comment]
NP, ill see if i can pinpoint the issue and let you know. It shows many sources found while scraping external scrapers, then pops up with No results found.

**Comment by Tikipeter** [comment]
Do you have Settings->Results->Display->Highlight Results Based On set to "Quality"? If so, switch it to "Scrapers" and see if that fixes it. That was the only current bug I could find.

**Comment by JayDee696969** [comment]
> Do you have Settings->Results->Display->Highlight Results Based On set to "Quality"? If so, switch it to "Scrapers" and see if that fixes it. That was the only current bug I could find.

Yes! That was exactly it. After I set it to Scrapers, the source list shows up again.

**Comment by Tikipeter** [comment]
Great! That was all I could find when I went looking. Just hang tight until next update, and I'll have that fixed. It was a little oversight in the code when I was trying to fix something else.
