### ISSUE TITLE
Next episode failed

### ISSUE THREAD

**Issue by Blockr22** [Tikipeter/repository.tikipeter#125]
Hey dev, so this is happening to me for a few days now. Every-time when fen tries to play next episode, doesn’t matter if i clip play in the small window that appears at the top right or i click close & it looks for sources & then it just says playback failed. Not playing anything & this happened in kodi 19.5 aswell. I am now using kodi 20 public build with shield 2017 & artic horizon 2 skin. Also when playback is stopped & it goes to main screen it says fen placeholder & no widgets are displayed for some time, its like widgets relode every time i play something. It didn’t happened before. Is this intended behaviour ?

Thnx for the updates now kodi crashes very few times than earlier.

I hope this is the correct way of posting logs. I got these from open wizard. Thnx

https://pastebin.ubuntu.com/p/hfTFyxXmPD/

**Comment by Tikipeter** [comment]
I cannot read that log as you need to have an account and be signed in.

1. Reproduce the error with Next Episode.
2. In Fen, go to Tools->Log Utils->Upload Kodi Log to Pastebin.
3. Supply here the url returned by Fen.

**Comment by Blockr22** [comment]
https://paste.kodi.tv/iyesuyanuv

Here u go. Sometimes after playing something, it just crashes to main screen aswell without giving any error

**Comment by Blockr22** [comment]
@Tikipeter are u able to open this ?

**Comment by Tikipeter** [comment]
Yes. Thankyou.

**Comment by xyzfre** [comment]
Also when playback is stopped & it goes to main screen it says fen placeholder & no widgets are displayed for some time, its like widgets relode every time i play something. It didn’t happened before. Is this intended behaviour ?
> 
> 
> 
> Thnx for the updates now kodi crashes very few times than earlier.
> 
> 
> 
> I hope this is the correct way of posting logs. I got these from open wizard. Thnx
> 
> 
> 
> https://pastebin.ubuntu.com/p/hfTFyxXmPD/

There's a setting that was added so when playback ends widgets refresh in the background,,settings,Playback,Load Empty Widget Container on Playback Start ,, disable that feature and that should do the trick

**Comment by xyzfre** [comment]
Also when playback is stopped & it goes to main screen it says fen placeholder & no widgets are displayed for some time, its like widgets relode every time i play something. It didn’t happened before. Is this intended behaviour ?
> 
> 
> 

There's a setting that was added so when playback ends widgets refresh in the background,,settings,Playback,Load Empty Widget Container on Playback Start ,, disable that feature and that should do the trick

**Comment by Blockr22** [comment]
@xyzfre thnx for letting me know about this setting, this seems to have fixed that widgets reload every time after playing anything problem. But do u mind telling me what this setting is there for ?
Why reloading whole kodi is necessary if only 1 widget that is played reloads just fine. Whats the point of this setting ?

**Comment by xyzfre** [comment]
> @xyzfre thnx for letting me know about this setting, this seems to have fixed that widgets reload every time after playing anything problem. But do u mind telling me what this setting is there for ?
> 
> Why reloading whole kodi is necessary if only 1 widget that is played reloads just fine. Whats the point of this setting ?

It's explained here #99

**Comment by Blockr22** [comment]
@xyzfre thnx, It makes sense now.

**Comment by Tikipeter** [comment]
Fixed for next update.

**Comment by Blockr22** [comment]
@Tikipeter thnx dev.
