### ISSUE TITLE
Help with cocoscrapers undesirables

### ISSUE THREAD

**Issue by ambulancePilot** [Tikipeter/repository.tikipeter#126]
**Debug Log:** http://paste.kodi.tv/ejozofuniz

Hey there, I am not sure this is the right place for this discussion.

I am the guy having the issue with Fen playing the wrong episode from a season pack when it comes to Friends S05E01. While awaiting a fix for that (no rush) I have been trying my hand at filtering out the problematic result. I absolutely must be doing something wrong because I'm not able to get it working, at all. My googling suggests the feature does in fact work, so I'd appreciate some guidance from anyone at all.

The season pack that creates the issue is "FRIENDS S05 1080P BLURAY REMUX AVC DD5 1 NOGRP" or a variation thereof. Sometimes there is a space between DD and 5.1, sometimes not. Sometimes NOGRP is at the end and sometimes not. Sometimes [RARTV] is at the end, sometimes not. You get the idea.

The part of the torrent that remains the same no matter which tracker it grabs from is "FRIENDS S05 1080P BLURAY REMUX AVC".

Should I not just be able to put "friends.s05.1080p.bluray.remux.avc" in the undesirables list and have it filtered out? I am clearing external scraper cache as well as RD cache before re-scraping and the cursed source is still top of my list as if I have not made any changes at all.

The only thing I can think of is that it doesn't care about the name of the torrent, rather is cares about the filename. If that's the case, I'm in trouble because each filename is named as "Friends S05Exx The Name of The Episode 1080p BLURAY REMUX AVC DD 5 1", which means the only static part of the file name is "1080p.bluray.remux.avc.dd.5.1" and if I filter THAT out, I'm also filtering out thousands of perfectly good torrents unrelated to Friends. It's just too common a naming convention.

Final question: can I just filter out a HASH instead of the name (whether it is torrent name or file name remains unclear to me).

So what am I doing wrong here? Thanks for any and all help. Much appreciated.

**Comment by ambulancePilot** [comment]
Updated with debug log!

http://paste.kodi.tv/ejozofuniz

**Comment by Projectal374** [comment]
Are you though actually clearing or deleting the file from your RD download and/or torrent folders too?

Fen's internal scraper may still be reading the file in your RD cloud while the external scraper filtered it out .  I don't think FEN's internal scraper uses an undesirables list like cocoscrapers do.  It would be nice if it did especially to help filter my easynews links.

**Comment by ambulancePilot** [comment]
I don't have it set to add sources to my cloud once I start playing them, so once I stop playback, it's gone. The problem also occurs independent of playback, for example when just inspecting the source list after a scrape.

I also don't use the internal scraper, it's completely disabled. Thanks for the ideas but I don't think that's it! Something else I'm doing wrong for sure.

**Comment by Projectal374** [comment]
> I don't have it set to add sources to my cloud once I start playing them, so once I stop playback, it's gone.

Nope not really. Check https://real-debrid.com/downloads and you'll see all your resolved shows there preserved on the site for about 7-10days.

`Provider Accounts>>REAL DEBRID>>Search Cloud Storage` if this setting is ON, Fen will search that download/history folder.

**Comment by ambulancePilot** [comment]
I'm not sure Fen searches the history page that way, but maybe you're right. I was under the impression searching cloud storage meant it would search torrents that have been added either manually or by Fen (if the add torrents to cloud setting is on). But you could be right about how that setting works.

Either way, I have always had search cloud storage off, so that's not it unfortunately.

**Comment by Projectal374** [comment]
here's a solution add .remux. (period before and after remux) to your list and it will filter that one out. However of course you will be filtering all remuxes out from all shows and movies too.

**Comment by ambulancePilot** [comment]
That's not really a solution I'm interested in! Remuxes are my favourite.

I'm more looking to figure out how to use the undesirables list properly to filter out the specific sources I'm not interested in for various shows I regularly watch (only in the event that the problematic source appears at the top of the list, and therefore with autoplay enabled, gets selected).

**Comment by Tikipeter** [comment]
If the torrent was named `Friends.S05.1080p.BluRay.REMUX.AVC.DD5.1-NOGRP[rartv]`, then the portion of the torrent name that will be checked for undesirables will be `.1080p.bluray.remux.avc.dd5.1.nogrp.rartv.`. The show name and season (or season/episode) is stripped before the comparison.

With the variations you mentioned in your original post, I don't think it would be possible to use the undesirables to remove this torrent. Maybe if you included ALL the variables i.e. `.1080p.bluray.remux.avc.dd5.1.nogrp.rartv.`, `.1080p.bluray.remux.avc.dd5.1.nogrp.` etc` then you might catch them all.

I am however looking at this issue as we speak, as I have a bit of free time this morning, and it was next in line....

**Comment by Tikipeter** [comment]
The overarching issue has been fixed for next update (soon).
