### ISSUE TITLE
Scraper progress dialog enhancement request

### ISSUE THREAD

**Issue by tekknight** [Tikipeter/repository.tikipeter#126]
Would it be possible to have an option to remove the progress dialog? When using the auto play feature, it would give it a much cleaner look. Maybe use the default skin progress to let you know something is happening.

**Comment by Tikipeter** [comment]
I've implemented a setting in the next update for this. If you select: Settings->Playback->Playback->Autoplay First Relevant Result, there will be a new setting "Use Minimal Notifications".

Fen will then use a background dialog for scrape result progress, and will suppress any notifications after the scrape such as links removed, debrid cache checking and resolve status of the resolving link. It should be an approximate to what you are after.

Be warned, though, you won't be able to cancel a search when the background dialog is displaying, so I would at least set "Stop Search Early if Most Sources Finished" in Settings->External Scrapers->General so Fen doesn't hang on any slow scrapers.
