### ISSUE TITLE
sort order

### ISSUE THREAD

**Issue by djdirty60** [Tikipeter/repository.tikipeter#127]
good day,

is it possible to sort by Size, such as quality? because now everything is mixed up in terms of size 3gb then 0.75gb and then 1gb again but it is easier if the largest file is at the top and then expires. 

Thanks in advance for the top add-on.

**Comment by Tikipeter** [comment]
It's not possible at the moment to sort by size. The size reporting from Openscraper scrapers is not consistent and is not returned as a value easily accessible for sorting (it comes as part of a general 'info' string).

In the future I can get accurate 'size' information for cached torrents from the debrid providers, but I haven't implemented that yet, as it is a decent sized job.

So, possibly in the future, but not at the moment. :( :(
