### ISSUE TITLE
Trakt Collection gets out of sync 

### ISSUE THREAD

**Issue by Mogulman12** [Tikipeter/repository.tikipeter#128]
This has been happening for a while. At least for a few months. Currently on 3.0.39 and Kodi 20, but this happened on previous Feb/Kodi releases.

I noticed that Feb doesn't seem to keep up with new unwatched episodes in my Trakt collection. It could be days later or a week later. I have my Trakt collection filtered by unwatched. So I'm expecting new episodes of tv shows to show up.

If I know there are episodes, I can unfilter and find it.

Or as a workaround, most of the time clearing meta cache works.

Attached is a log where the latest Last of Us episode wasn't showing up as an unwatched episodes from yesterday.   I cleared Meta Cache  and then it showed up.  

Link to log: https://paste.kodi.tv/wipozanolu

**Comment by Tikipeter** [comment]
"Trakt Collection gets out of snc" means you have added items to your trakt collection that are not showing in Fen.

But then your body of text implies you are having a problem with latest episodes not showing up in your Next Episodes menu.

Is your issue the title of your post here, or the body of text?

**Comment by Mogulman12** [comment]
I just go to Trakt Collection and have the list of shows filtered by unwatched episodes so I can see what is there to wartch.  That is how I used to  keep up with new episodes in other plugins.  It works mostly with Fen, but then sometimes Fen doesn't show the latest episodes even though I know it has aired, and is available in Trakt.  

So I can manually find it or clear meta cache in Feb, and then I can see it.   So maybe it isn't a sync issue with Trakt.   Maybe the meta data isn't updating sometimes. Not exactly sure.

**Comment by Tikipeter** [comment]
>.....and have the list of shows filtered by unwatched episodes

How are you doing that?

Why are you not using "Next Episodes" to see a collection of the next unwatched episodes available?

**Comment by Mogulman12** [comment]
Next episodes isn't organized by series, season, etc.  Also it shows things you've watched that aren't in the Trakt Collection.  Trakt Collection for us is more important than random shows we might have watched.  

If I'm in my Trakt Collection list of shows, I can use the left button on my remote to change the filter from All Videos, to Unwatched Videos.   This seems like a global filter too though, so it also filters movies and other things based on all, unwatched ,or watched.

**Comment by Tikipeter** [comment]
In that case, using it as you are using it, then you will sometimes see a difference at the show level of watched status compared to at the episode level. Maybe even quite often. In which case you would have to re-cache at the tvshow level as you are doing now.

It would work a lot better if you set to hidden the shows you don't want to have appear in the Next Episodes, and used that instead.

**Comment by Mogulman12** [comment]
K.  I'll take a look at that thanks.

**Comment by Mogulman12** [comment]
FYI. Not sure if you can see this after the ticket is closed, but Umbrella and Seren both seem to update using the watched/unwatched in Trakt Collection more frequently than Feb.   If you ever want to pursue this as an enhancement.
