### ISSUE TITLE
Potential issue with Reuse Language Invoker using AH2 new stacked widget feature

### ISSUE THREAD

**Issue by iampritesh** [Tikipeter/repository.tikipeter#129]
Hi TikiPeter,

As requested in a recent changelog, I'm reporting a potential issue with Reuse Language Invoker, using Fen 3.0.39.  Probably a very uncommon use-case as I haven't seen it mentioned elsewhere.  This is using Kodi 20 on Windows 11

Arctic Horizon 2 has recently added a new feature called "stacked widgets" in v0.8.2, where you can have a widget row that displays the contents of the highlighted item in the widget row above it.

Kodi crashes to desktop with Reuse Language Invoker switched on if I do the following:
1.  Have a widget row pointing to a custom Fen shortcut folder that contains Trakt lists
2.  Select a TV show from the widget below it, browse to its episodes and play an episode
3.  Stop the episode and go back to the home page

Probably easier to see what I'm describing in the attached video - the end of the video is where Kodi immediately crashed to desktop.

I do not get a crash if I select a movie from a stacked widget, or if I use normal widgets on the same skin.  I also do not get any crashes if Reuse Language Invoker is switched off.

Have attached the video, a debug log, a crashlog and a stacktrace if they're of any help.

I know it took years to get the fix in so I'm not expecting you to spend any time on this.  I doubt many people will have their skin & widgets set up like I do (it's the first wife-approved setup I've found!).  I'll just switch Reuse Language Invoker off until I inevitably move to a different skin as Fen is still super fast either way.

Thanks again for all the effort you put into this add-on and let me know if you'd like any more information.

https://user-images.githubusercontent.com/68284946/215772842-117b8632-3f26-43dc-b295-cbe48441cbdd.mp4

[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/10546771/kodi.log)
[kodi_crashlog-20.0 Git_20230115-389e701cb9-20230131-125429.dmp.zip](https://github.com/Tikipeter/repository.tikipeter/files/10546781/kodi_crashlog-20.0.Git_20230115-389e701cb9-20230131-125429.dmp.zip)
[kodi_stacktrace-20.0 Git_20230115-389e701cb9-20230131-125429.txt](https://github.com/Tikipeter/repository.tikipeter/files/10546774/kodi_stacktrace-20.0.Git_20230115-389e701cb9-20230131-125429.txt)

**Comment by Tikipeter** [comment]
Just getting around to looking into this. I'm wondering if the crash also happens if you don't navigate into the episode list via the Extras menu?

**Comment by iampritesh** [comment]
Yes it does, it still crashes at the same point.

**Comment by ReaLx3m** [comment]
Im also having crashes with invoker enabled on .40, had them on .37 too. Thats with Aeon nox silvo skin, and the crashes happen when going back to the home screen where the widgets are.

[kodi_crashlog-20.0 Git_20230115-389e701cb9-20230204-022603.dmp.zip](https://github.com/Tikipeter/repository.tikipeter/files/10593699/kodi_crashlog-20.0.Git_20230115-389e701cb9-20230204-022603.dmp.zip)
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/10593701/kodi.log)
