### ISSUE TITLE
Trakt TV Show Lists

### ISSUE THREAD

**Issue by flhthemi** [Tikipeter/repository.tikipeter#13]
Just noticed when getting TV show lists from trakt not ALL episodes are being pulled and some seasons are empty. A good test is The Lone Ranger which Season 4 has 52 episodes but Fen shows me none. It's also taking an extremely long time to pull my trakt tv show lists. More than 5 minutes sometimes.  Thought it might be an API issue but the status was at 100% and other addons did fine as well. My lists are here https://trakt.tv/users/flhthemi/lists if you would like to use them feel free.

![screenshot000](https://user-images.githubusercontent.com/8205131/61755813-3bfae780-ad87-11e9-8d11-fb61f3c9e464.png)

![screenshot001](https://user-images.githubusercontent.com/8205131/61755832-546b0200-ad87-11e9-8e9d-67cb9b04acfb.png)

**Comment by Sovilor** [comment]
Yes it takes long time to browse any trakt list because the items number has set to 40, 
so for Tv Box users it's almost impossible to browse trakt lists (every where they say it's because of the processor) and the old devices too. 
All addons have that problem, only Seren has an option (Page Item Limit) but unfortunately it doesn't apply on Trakt lists, and it shows all your items on one page, so it takes like 25 minutes to browse a big list.

@Tikipeter please consider adding an option to set items page number for Trakt lists from 10 to 40, if possible.

Thank you.

**Comment by Tikipeter** [comment]
@Sovilor 

Fen already paginates all Trakt Lists (Collections, Watchlist, other lists) at 40 items per page. There is also a 'Jump To' icon at the top of each page for lists over 2 pages long so you can jump to Page 3 or 5 or whatever. You can also change that Jump To icon to instead jump to a letter of the alphabet, say jump to listings starting with 'R' etc. I can add a setting to lower that 40 items per page to something less, but it shouldn't take more than 20-30 seconds even on a slow device for the first time you enter a list, and should be much quicker on subsequent visits to the list when all the metadata is cached.

I 'liked' flhthemi's 'Trakt-Movies' list, and it took 13 seconds to bring up the first page of 40 items, and less for the second page of 30. Navigating back into the list after exiting it, it took 2 seconds to get back in as all the movies' metadata was cached now, as well as the contents of the Trakt list itself.

@flhthemi 
It should not take anything near 5 mins for a list to load. If it's taking more than say 25 seconds, press back to cancel the navigation and then press the list to try again. Something sounds like it's getting stuck.

As for the seasons missing, unfortunately that is a by-product of using TMDb for TV Show data. They simply don't have the data for that series complete (or even close to complete by the looks of things).

I'm in the process of writing code to use TVDb instead, who has a much more complete database for TV Shows, and was meant to work on it this week. But I kept getting caught up in these issues tabs, and fixing things from here. Hopefully I can be more disciplined, leave any new issues that come up alone for a few days, and knock out this TVDb code, which will help the issue you're having with The Lone Ranger, plus a lot of (mostly older) shows that have incomplete data from TMDb.

**Comment by Tikipeter** [comment]
v.1.5.30 has setting to change list count for Trakt lists from 10-40.
Go to Settings->General and it's under the 'Trakt' section.

**Comment by Sovilor** [comment]
i just tried, changed the number to 10, and Trakt lists loading time is very fast.

Thank you

**Comment by Tikipeter** [comment]
Should be fixed with Fen v.1.5.33 and tikimeta v.1.1.04.
