### ISSUE TITLE
NOTICE: Slow Openscrapers Initialization...

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/repository.tikipeter#130]
Hi anyone reading this.

Lately, Openscrapers has been slow to 'get going', so I thought I would look into it. I have a test module of Openscrapers below, if anyone would like to try it and see if it improves the speed of Openscrapers starting. I will call this 0.0.1.104a.

If some people could test it and report back here if you see an increase in speed or not, it would be much appreciated. There are lots of small changes from the latest Openscrapers, so I'm hoping some people can test it before I make a pull request to Adons4Kodi. 

To get the file, choose "Install from zip file" in Kodi, then choose the tikipeter repo source you added to filemanager when you first installed the tikipeter repo. You could have named it anything. You will see there the repository.tikipeter file and you should see a new file called:
**script.module.openscrapers-0.0.1.104a.zip**
Click on that to install the test update.

OR.... download this zip file and "Install from zip file" in Kodi....
http://s000.tinyupload.com/index.php?file_id=00783190540688406895

**Comment by host505** [comment]
Hey,

It loads way faster!
But I noticed something odd: it throws import error (requests) when you run actions through settings ("Disable all hosters" etc).
Requests are imported from cfscrape module. Now requests isn't imported on addon.xml, but this doesn's seem to be causing problems on upstream openscrapers, but it does on your version.
I guess because init.py is called on settings actions, and now cfscrape is imported there?

**Comment by Tikipeter** [comment]
Interesting. I'm away from the computer now, but maybe wrapping the cfscrape code in the init file in a try/except might be good enough (the import as well).

**Comment by Tikipeter** [comment]
I'd say it works normally because our addons calling sources() has requests in the add-on.xml. I'd say it's an oversight that Openscrapers doesn't have requests in the add-on.xml.

**Comment by host505** [comment]
Yes, it works with the try/except.

**Comment by 99Maxwell99** [comment]
I created an account just to tell you how much faster this is. From 8-10 seconds prior down to 2 seconds on a shield. This works great.

**Comment by Tikipeter** [comment]
Good news so far.

**Comment by cabban** [comment]
i tried it only get a fen error now nothing loads :) hehe

**Comment by Tinuz97** [comment]
Faster as stock openscrapers,tested on my computer :)

**Comment by Tikipeter** [comment]
Cabban, clear your External Scrapers database in Tools.

**Comment by cabban** [comment]
Not working that either 🤐 thank u for tip though

lördag 15 februari 2020 skrev Tikipeter <notifications@github.com>:

**Comment by Tinuz97** [comment]
![Screenshot_20200215-223649](https://user-images.githubusercontent.com/47715606/74595605-cf597a00-5043-11ea-87b8-bf5f39dc5a63.jpg)
I don't wanna spam with a new ticket, so I just use this closed one. 

I LIKE this, this is a feature I wanted a long time ago, love it!

Thx

**Comment by cabban** [comment]
Can't find that clear dataBase only says cache

lördag 15 februari 2020 skrev Tinuz97 <notifications@github.com>:

**Comment by Tikipeter** [comment]
@cabban 
Tools->Clear Databases and Clean Settings Files->Clear External Scrapers Cache.

**Comment by cabban** [comment]
Done this yesterday. But only get now fen error unfortunately

söndag 16 februari 2020 skrev Tikipeter <notifications@github.com>:

**Comment by Tikipeter** [comment]
Send me the log after you get the error.

**Comment by cabban** [comment]
How do a see and send log :-)

söndag 16 februari 2020 skrev Tikipeter <notifications@github.com>:

**Comment by Tikipeter** [comment]
If I remember correctly, you are using Kodi on Windows, so....
1. Restart Kodi so the Log is fresh.
2. Replicate the problem you are having.
3. Navigate to:
`C:\Users\{user_name}\AppData\Roaming\Kodi\kodi.log`
4. Paste the contents of that log to:
[Pastebin.com](https://pastebin.com/)
5. Put the link to the pastebin you created here for me to read.
6. Profit.

**Comment by cabban** [comment]
> If I remember correctly, you are using Kodi on Windows, so....
> 
> 1. Restart Kodi so the Log is fresh.
> 2. Replicate the problem you are having.
> 3. Navigate to:
>    `C:\Users\{user_name}\AppData\Roaming\Kodi\kodi.log`
> 4. Paste the contents of that log to:
>    [Pastebin.com](https://pastebin.com/)
> 5. Put the link to the pastebin you created here for me to read.
> 6. Profit.

file:///C:/Users/Lassegittan/AppData/Roaming/Kodi/kodi.log

**Comment by Tikipeter** [comment]
@cabban 
Turn off animeloads scraper in Openscraper settings. I'm pretty sure it's in the German scrapers.

**Comment by cabban** [comment]
Thank u see it's working again.
And it plenty fast also. 2-3 seconds to load scraper instead of 8-20 😀

söndag 16 februari 2020 skrev Tikipeter <notifications@github.com>:

**Comment by ANHBOB** [comment]
I'd like to try this. I'm using a 4K Firestick. Is there a way for me to use this?

**Comment by Tikipeter** [comment]
@ANHBOB  
Only if you have a way to download the zip in the original post and can then access that zip on the 4K Firestick so that you can "Install from zip".

**Comment by ANHBOB** [comment]
In Kodi there's a File Manager...i can put the http:// address in...the same as I do when installing Repo's..but nothing happens with that address ...http://s000.tinyupload.com/index.php?file_id=56166857904188870702.
I'm guessing it's a like to another web page?

**Comment by Tikipeter** [comment]
Yeah, that won't work. You need to download the zip from that web page somehow.

**Comment by ANHBOB** [comment]
I thought so. Thanks for the reply.   Any idea when Kodi 18.6 will be released?  It's supposed to have improvements.  Usually they release updates every 2 months, it's been almost 3 since the last update.

**Comment by Tikipeter** [comment]
No idea I'm afraid. Kodi devs don't answer any questions on release dates. :)

**Comment by Tikipeter** [comment]
@ANHBOB 
I put the test Openscrapers in with my repo zip so you can install it directly on the 4K stick. Check the edited first post for instructions.....

**Comment by ANHBOB** [comment]
Thank you for all the work you do. It is very much appreciated.

**Comment by Tinuz97** [comment]
I got bored, and did some (copy paste),just as a test.

Used the old tikiscrapers (the version that was released as the last one), modified some things (the new test cfscraper import from you, add the request in the addon.xml), and it is realy much faster as openscrapers, it flies true the scrapers, and zero hanging. 
Also used the latest VeNoMouS cfscrape modules, removed the tiki related cfscrape files. 

Unfortunately I am a python noob, but (no joke) because of my autism I can see some logic in it (the copy paste part), so for me it works great. 

Do you have a clue why the old tikiscrapers (with above described edits) is flying true the scrapers?
It is realy 5 times faster, weird. 

It would be realy cool if a4k would use tikiscrapers as a base, and improve that (just a idea), I don't know the exact difference between both, but tikiscrapers are way faster.

**Comment by Tikipeter** [comment]
Did you get a reasonable amount of results? If more scrapers are dead it would skip through them fast, making the entire scraping faster. That's the only thing I can think of.

Maybe I'll give them a spin and see what happens for me. :) :)

**Comment by Tinuz97** [comment]
Yes, i only tested (comparing) working scrapers.
So I did not use all (just the debrid and torrent ones, tested each scraper if they did give results back). 

Did this on openscrapers and tikiscrapers (so both same amount working scrapers, not dead ones), and it is realy fast with tikiscrapers as base (keep in my I am a python noob, so probably not perfect). 

So I changed the cfscrape import in the scrapers like you did, add the request module in the addon.xml, did take the latest VeNoMouS modules (cfscrape), it is not a little faster, but realy faster (with probably allot of things not 100% with my noob skills). 

Curious if you try the same thing, and experience the same.

**Comment by Tikipeter** [comment]
Gee I miss Tikiscrapers..........

**Comment by Tinuz97** [comment]
> Gee I miss Tikiscrapers..........

![106516664-352-k536187](https://user-images.githubusercontent.com/47715606/75282810-f5d09f80-5811-11ea-84c3-9eb4b35c5522.jpg)


😂😂😂

**Comment by jaysamuel1976** [comment]
Tikiscrapers! Tikiscrapers!

**Comment by Tikipeter** [comment]
Hey @Tinuz97 
Do you still have that test tikiscrapers module you made yourself a couple of days ago?
If so, could you zip it up and post it here for me to play around with?
Thanks if you can. :) :)

**Comment by Tinuz97** [comment]
Dang, don't have it anymore.
But I used the latest tikiscrapers from you 1.1.25,the one before openscrapers switch.

Removed everything related to the cfscrape.py, and the cfscrape.py. 

Placed the files from VeNoMouS (latest) all in one folder, named cfscrape (under modules). 
Did the steps from you (added request in the addon.xml), did add that little line in init.py (sources_tikiscrapers), the cfscrape = cfscrape.create_scraper etc line. 

Did switch 2 files (no idea how I rewrite them, so I did use 2 from openscrapers, I believe it was cleantitle and source_utils), otherwise not all scrapers did give results back. 

And did change all scrapers with the cfscrape import like you did.

**Comment by Tinuz97** [comment]
Oh, and I left the pyaes folder in it, no idea what it is lol (again, noob here), but if I did remove that, it did not work anymore.
So in the modules folder I had all tikiscrapers modules, replaced 2 like I did write in the above message with openscrapers ones, pyaes folder and cfscrape folder, in that folder all the files from VeNoMouS (did not change or renamed the files) 
So structure the same as on his github, only named the folder cfscrape, and not cloudscraper. 
https://github.com/VeNoMouS/cloudscraper

**Comment by rrosajp** [comment]
@Tikipeter 
here is the modified zip  [https://we.tl/t-pb7M3eEQVy](url) as incorporated yr pr to openscraper and implemented  on tikiscraper .

**Comment by Tikipeter** [comment]
Thankyou both. I really appreciate it.

**Comment by Tikipeter** [comment]
@rrosajp 

I edited your post because the link didn't work. It's working now. Thanks again.

**Comment by ANHBOB** [comment]
Not sure what's going on but lately it's been hit or miss with finding playable sources. 4 days ago tried to watch a movie in FEN...The Last Full Measure. Kept getting No Results found after trying 5-6 times. Then I tried the same movie using The Crew...got a lot of results and watched the movie.

Today I tried to watch Chicago PD...same thing...No Results.  Tried with the Crew....it worked.

**Comment by Tinuz97** [comment]
> Not sure what's going on but lately it's been hit or miss with finding playable sources. 4 days ago tried to watch a movie in FEN...The Last Full Measure. Kept getting No Results found after trying 5-6 times. Then I tried the same movie using The Crew...got a lot of results and watched the movie.
> 
> Today I tried to watch Chicago PD...same thing...No Results. Tried with the Crew....it worked.

What season/episode, tryed a few, working fine for me 
![Screenshot_20200227-171047](https://user-images.githubusercontent.com/47715606/75462231-37815780-5984-11ea-8aea-8457e743481e.jpg)

**Comment by ANHBOB** [comment]
It was Season 7, Episode 15 ..the one that aired last night. I tried to watch it about 3 hours ago in FEN...wouldn't work...no results. So I watched it by using The Crew

**Comment by Tinuz97** [comment]
> It was Season 7, Episode 15 ..the one that aired last night. I tried to watch it about 3 hours ago in FEN...wouldn't work...no results. So I watched it by using The Crew

Weird, working fine here (dutch info in screenshot, but it is season 7 episode 15) 
![Screenshot_20200227-172051](https://user-images.githubusercontent.com/47715606/75463148-af9c4d00-5985-11ea-8f25-cdd9494d7026.jpg)

**Comment by 99Maxwell99** [comment]
If I installed the “a” version of openscrapers from your repo will this update on its own or do I need to remove it and reinstall to continue getting updates. Assume it’s fixed by now and the “a” version is no longer needed for fast initialization

**Comment by ANHBOB** [comment]
Yes I'd like to know as well

**Comment by Tikipeter** [comment]
It will update on its own. The pull request for this fix was not accepted, however.

**Comment by caokhai1331999** [comment]
help me i can not open any movies after upgrade disk, Everytime i turn kodi on, there is a pop up appear tell me that openscraping error cleaning setting file...here is the link. https://pastebin.com/iRaRriNb

**Comment by Tikipeter** [comment]
@caokhai1331999 

Most likely not Fen related. Fen does not clean any settings files automatically.

See if you can navigate into the Openscrapers settings file. If not, it has likely become corrupted. Delete it from your addon_data folder and it should remake itself correctly.
