### ISSUE TITLE
Problem with subtitles

### ISSUE THREAD

**Issue by batarela** [Tikipeter/repository.tikipeter#130]
Hi Tikipeter,

In case of adding external subtitles, the download subtitle option works, but the browse option freezes the program.

thanks

**Comment by Tikipeter** [comment]
What do you mean addong external subtitles?

From where?

And where is your log file as per the rules?

**Comment by barronen1** [comment]
> Not Fen exclusive. More of a Kodi problem. Try [this](https://github.com/peno64/service.subtitles.localsubtitle).

Isn’t it pre existing feature in Kodi subtitles settings? (“Choose subtitles”, not download)

**Comment by Tikipeter** [comment]
????

**Comment by Tikipeter** [comment]
> > ????
> 
> ?

I'm just waiting for a reply from batarela.
Then I can close this issue, as it's not Fen related.

Oh who cares. Closed. People wonder why devs get burnt out.

**Comment by batarela** [comment]
Hi,
I meant the local subs that we search with "browse for subtitle" in subtitle setting.
This doesn't work in any fork of FEN, but it does work in Umbrella or similar.
Sorry for not getting in touch sooner.
Regards

**Comment by batarela** [comment]
> > > Not Fen exclusive. More of a Kodi problem. Try [this](https://github.com/peno64/service.subtitles.localsubtitle).
> > 
> > 
> > Isn’t it pre existing feature in Kodi subtitles settings? (“Choose subtitles”, not download)
> 
> Yes. Though apparently the feature doesn't work well with non-local content. Hence the extra addon.

thanks for this tip
