### ISSUE TITLE
Fen playback failed

### ISSUE THREAD

**Issue by Blockr22** [Tikipeter/repository.tikipeter#131]
Hey dev, so its almost the same issue I mentioned earlier but after last update next episodes worked since whole season ended in one of the show my wife watches. Fen does scrape for sources just fine but when its time to play it just says plaback failed. Seren works like normal. Show’s name is Drop dead diva & Season 5 just finished for my wife & season 6 no episode worked yet. Here are my logs. Thnx

https://paste.kodi.tv/umoxebawov

**Comment by Tikipeter** [comment]
![screenshot00000](https://user-images.githubusercontent.com/28930002/216722950-b237ccec-1cce-46dc-a66d-694c4d6b8ed4.png)


I get these results. If you don't have Easynews, ad you don't have Premiumize, then you are out of luck playing the season.

Although the other results say "Season Pack", they are not really season packs, they are just the one file which was shown as E01E02 together.

Might have to use Seren for this one if it has a full season pack.

**Comment by Blockr22** [comment]
![1A1E89F3-A42B-4BAE-8C01-9B95DD72D3AF](https://user-images.githubusercontent.com/96648629/216736302-7d783b84-d03a-4826-b511-e254d5582a75.jpeg)

Then while scraping why is it showing me 11 1080p files & alot of 720p

**Comment by Tikipeter** [comment]
I scraped for S06E01. What episode are you scraping for?

How many results do you get after the debrid services have been checked for cached status?

**Comment by Blockr22** [comment]
I scraped S06E03 and the picture I included is from that. After scraping or that screen fen just says playback failed.

**Comment by Tikipeter** [comment]
Your original comment said playback failed.

Is it playback failed or no results?

I'm struggling to get what the issue is.

**Comment by Blockr22** [comment]
Now it just says no results. Even though while scraping it clearly seems to find links

**Comment by Tikipeter** [comment]
Finding links from online sources and those links being cached on your debrid service are two different things.

An addon could find 1000 links during the scrape, but if none are cached on your debrid service, then none are playable.

That's how these addons work.

**Comment by Blockr22** [comment]
Ohh, kk. Then how is seren able to find links & play those whereas fen find but says no results. I m using real debrid for both fen & seren

**Comment by Tikipeter** [comment]
What would you say the answer is,  based on what I've explained in this thread?

**Comment by Blockr22** [comment]
Maybe use seren since its able to find the links😅. Thats kk, i will close this issue now. I m confused lol. Thnx anyways

**Comment by xyzfre** [comment]
Fen and Seren use different scraper packages so that makes a difference ,,and it's always good to have a couple of Debrid services As a back up for situations like this usually RD/PM never tried EN But thinking of getting it too
