### ISSUE TITLE
feature request disaable inactive not aired and cam links movies and tv

### ISSUE THREAD

**Issue by cabban** [Tikipeter/repository.tikipeter#131]
i hope this is possible it would make this addon an innovation
a filter for new movies
the actually have  an scraper other wise they are not visible in list 
and also only links with actually not cam
i hope this is possible it would make kodi experience fen much easier :) cause many new movies not even aired on cinema and they have no links :) only show movies actually aired.

i hope you understand what im pointing at here :P @Tikipeter

**Comment by Tikipeter** [comment]
I'm afraid it's not possible, cabban. Fen would have to scrape results for every movie before displaying them , meaning it would take 10 minutes for each page to load.

IF YOU HAVE A TRAKT ACCOUNT:
If you just want a list that features only newly released movies, a popular one is: https://trakt.tv/users/giladg/lists/latest-releases

You can go on the Trakt site and 'like' the list, and then add it to a Fen menu, or you can even search for 'latest releases' in Fen's Trakt: Search User Lists, and then bring up the context menu and select 'like this list', then add it to a menu.

Then you will have your own list of newly released movies to use.

Let me know if you need help adding a Trakt list to the Movies section.....
