### ISSUE TITLE
not an issue suggestion for listitems infotags

### ISSUE THREAD

**Issue by jigoop1** [Tikipeter/repository.tikipeter#132]
@Tikipeter
adopted code from script.module.infotagger [https://github.com/xbmc/repo-scripts/pull/2385](url)
here it may be easy to adopt this for `info_tag = listitem.getVideoInfoTag()`

When making your ListItem 

 ```python
 set_info = kodi_utils.set_info
# Make your listitem as normal
listitem = make_listitem()
# Pass listitem and the meta or item
setUniqueIDs = {'imdb': imdb_id, 'tmdb': string(tmdb_id), 'tvdb': string(tvdb_id)}
item = meta = dict
listitem = set_info(listitem, item, setUniqueIDs)


```

following module goes in kodi_utils
```
def metadataClean(metadata):
	if not metadata: return metadata
	allowed = ('genre', 'country', 'year', 'episode', 'season', 'sortepisode', 'sortseason', 'episodeguide', 'showlink',
				'top250', 'setid', 'tracknumber', 'rating', 'userrating', 'watched', 'playcount', 'overlay', 'cast', 'castandrole',
				'director', 'mpaa', 'plot', 'plotoutline', 'title', 'originaltitle', 'sorttitle', 'duration', 'studio', 'tagline', 'writer',
				'tvshowtitle', 'premiered', 'status', 'set', 'setoverview', 'tag', 'imdbnumber', 'code', 'aired', 'credits', 'lastplayed',
				'album', 'artist', 'votes', 'path', 'trailer', 'dateadded', 'mediatype', 'dbid')
	return {k: v for k, v in metadata.items() if k in allowed}

def set_info(item, meta, setUniqueIDs=None, resumetime=''):
	if resumetime: resumetime = float(resumetime)
	if kodi_version >= 20:
		try:
			meta_get = meta.get
			info_tag = item.getVideoInfoTag()
			info_tag.setMediaType(meta_get('mediatype'))
			if setUniqueIDs: info_tag.setUniqueIDs(setUniqueIDs)
			info_tag.setPath(meta_get('path'))
			info_tag.setFilenameAndPath(meta_get('filenameandpath'))
			info_tag.setTitle(item.getLabel() or meta_get('title'))
			info_tag.setSortTitle(meta_get('sorttitle'))
			info_tag.setOriginalTitle(meta_get('originaltitle'))
			info_tag.setPlot(meta_get('plot'))
			info_tag.setPlotOutline(meta_get('plotoutline'))
			info_tag.setDateAdded(meta_get('dateadded'))
			info_tag.setPremiered(meta_get('premiered'))
			info_tag.setYear(convert_type(int, meta_get('year', 0)))
			info_tag.setRating(convert_type(float, meta_get('rating', 0.1)))
			info_tag.setMpaa(meta_get('mpaa'))
			info_tag.setDuration(meta_get('duration', 0))
			info_tag.setPlaycount(convert_type(int , meta_get('playcount', 0)))
			if isinstance(meta_get('votes'), str): meta_votes = str(meta_get('votes')).replace(',', '')
			else: meta_votes = meta_get('votes')
			if meta_votes: info_tag.setVotes(convert_type(int, meta_votes))
			info_tag.setLastPlayed(meta_get('lastplayed'))
			info_tag.setAlbum(meta_get('album'))
			info_tag.setGenres(to_list(meta_get('genre', [])))
			info_tag.setCountries(to_list(meta_get('country', [])))
			info_tag.setTags(meta_get('tag', []))
			info_tag.setTrailer(meta_get('trailer'))
			info_tag.setTagLine(meta_get('tagline'))
			info_tag.setStudios(to_list(meta_get('studio', [])))
			info_tag.setWriters(to_list(meta_get('writer', [])))
			info_tag.setDirectors(to_list(meta_get('director', [])))
			info_tag.setIMDBNumber(meta_get('imdb_id'))
			if resumetime: info_tag.setResumePoint(convert_type(float, resumetime), meta_get('duration', 0))
			if meta_get('mediatype') in ['tvshow', 'season']:
				info_tag.setTvShowTitle(meta_get('tvshowtitle'))
				info_tag.setTvShowStatus(meta_get('status'))
			if meta_get('mediatype') in ['episodes', 'episode']:
				info_tag.setTvShowTitle(meta_get('tvshowtitle'))
				info_tag.setEpisode(convert_type(int, meta_get('episode')))
				info_tag.setSeason(convert_type(int, meta_get('season')))
			info_tag.setCast([xbmc_actor(name=item['name'], role=item['role'], thumbnail=item['thumbnail']) for item in meta_get('cast', [])])
		except: logger(f'set_info meta : {meta} error: {traceback.print_exc()}', '')
	else:
		item.setUniqueIDs(setUniqueIDs)
		item.setCast(meta.get('cast', []) + meta.get('guest_stars', []))
		meta = metadataClean(meta)
		try: meta.pop('cast')
		except: pass
		item.setInfo('video', meta)
		if resumetime: item.setProperties({'ResumeTime': resumetime, 'TotalTime': str(meta.get('duration', 1800))})
	return item

def to_list(item_str):
	if not isinstance(item_str, list): item_str = [item_str]
	return item_str

def convert_type(_type, _value):
	try:
		return _type(_value)
	except Exception as Err:
		logger(f'convert_type error: {Err}', '')

```
@Tikipeter 
this modified code work i have tested on episodes.py , movies.py, seasons.py, tvshows.py and it work. here is those files
[plugin.video.fen.zip](https://github.com/Tikipeter/repository.tikipeter/files/10614081/plugin.video.fen.zip)

**Comment by umbrellaplug** [comment]
Wish you'd make a stop by the Umbrella repo next. Lol.
I'll check this out also.

**Comment by jigoop1** [comment]
@Tikipeter 
@umbrellaplug 
i still testing the meta dictionary value type  conversion but if we make meta dict value for final required value type we can reduce redundant value conversion.
i will post as i find more.

**Comment by umbrellaplug** [comment]
@jigoop1 I was able to get it into my tv shows category successfully removing the warnings that I typically would see in the log. There are a few places in Umbrella where item are being added and uniqueid are not passed so I modified the function a bit. I've linked my branch I'm working on for the test repo [here](https://github.com/umbrellaplug/umbrellatest/tree/infoset_kodi20).

My changes are in control.py, navigator.py, tvshows.py

I will work with this more tomorrow. I've got some other things going on tonight.

**Comment by jigoop1** [comment]
@Tikipeter 
sorry i m posting this since there was no isssue @ [https://github.com/umbrellaplug/umbrellatest/tree/infoset_kodi20](url)

@umbrellaplug 
there is problem with genre / country / studio / writer / director
since it is str it can not convert to list 

```
                        info_tag.setGenres(to_list(meta_get('genre', [])))
			info_tag.setCountries(to_list(meta_get('country', [])))
			info_tag.setTags(meta_get('tag', []))
			info_tag.setTrailer(meta_get('trailer'))
			info_tag.setTagLine(meta_get('tagline'))
			info_tag.setStudios(to_list(meta_get('studio', [])))
			info_tag.setWriters(to_list(meta_get('writer', [])))
			info_tag.setDirectors(to_list(meta_get('director', [])))
```

and we need this func to convert list
```
def to_list(item_str):
	if not isinstance(item_str, list): item_str = [item_str]
	return item_str
```

**Comment by umbrellaplug** [comment]
@jigoop1 Nice catch, I don't know if you noticed my commit on branch, but I was just looking at exactly this problem.
I'll open a feature request on my side and link it here so we can stop annoying Peter.

**Comment by Tikipeter** [comment]
I appreciate the effort a lot @jigoop1 .

I did, however, begin implementing these changes back in Fen version `3.0.38`. And as of the latest release it should have all been finalized.

I'm assuming this code is from Jurial's module he released for converting setInfo to setting tags. There are some checks in there that I felt were not needed specifically for Fen, as I can control what I feed the `set` functions.

I've not been too well for a few days, so spent a couple offline altogether (except whilst at work :) ), so it's good to see umbrella dev taking on this task as well.

My plan, however, is to eventually stop supporting Kodi 19, which will allow me to properly format the metadata at the start of the chain, instead of having to do it on the fly every time a listitem is made. I feel it actually slows down the listitem creation, when the intention of this Kodi change was the opposite.

In saying that, there are definite needs to "tweak" usage of this. Mainly around watched statuses etc.
