### ISSUE TITLE
Enhancement (3D sources) 

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#132]
Is it possible to add a 'filter out 3D sources'?
No idea if it is possible, just a idea (looked in the settings, I think it is not there, or I am overlooking it)

**Comment by Tikipeter** [comment]
Does it have '3D' in the info for the 3D video?

**Comment by Tinuz97** [comment]
In the scraper, like I believe kickass as a example,yes.

**Comment by Tinuz97** [comment]
![Screenshot_20200217-001842](https://user-images.githubusercontent.com/47715606/74614784-2bdb9880-511b-11ea-8de5-1ac5fd2c5cd9.jpg)
A example.

**Comment by Tinuz97** [comment]
Did not check every link (of it is realy 3D)

**Comment by Tikipeter** [comment]
Thanks as always Tinuz97. Will be in next update.
