### ISSUE TITLE
Everything ticked as watched? 

### ISSUE THREAD

**Issue by JFG1000** [Tikipeter/repository.tikipeter#133]
![20230204_205518](https://user-images.githubusercontent.com/76907836/216789324-703b937a-0d7f-4ae2-9d26-fd1690455350.jpg)

Hi mate not really sure what's happening here but for some reason everything is marked as watched with the ticks on every cover art, not sure if this is a skin issue or kodi itself but if i navigate to the same screen using umbrella all seems fine, using mavens nexus 20, I've also tested this on 19.5, both using auramod skin

EDIT : rolled back to 3.0.37 to test and it seems fine on that version

**Comment by Tikipeter** [comment]
Try a different skin to see if the behavior is correct and then report back here.....

**Comment by JFG1000** [comment]
Hi mate tried the default estuary and everything seemed fine, it was auramod that was producing this, unfortunately I don't have AH2 installed or anything but I'm happy to try it if need be

**Comment by JFG1000** [comment]
Just an update on this issue, I've noticed this morning it's just TV shows that display watched ticks on everything

**Comment by Tikipeter** [comment]
What did the Auramod dev say?

**Comment by JFG1000** [comment]
I've messaged you on discord if you could check mate

**Comment by Tikipeter** [comment]
I'm off all social type media. No more a4k, no more Discord, no more Keybase.

Too many assholes.

**Comment by JFG1000** [comment]
That's completely understandable and I agree with you, I did post the issue on the github of auramod but nothing has been said really, I'm happy to get a log for you tomorrow if you would like? It's so confusing as to why it all seemed fine on a previous fen version

**Comment by JFG1000** [comment]
https://paste.kodi.tv/qigitotumu

I've got a log if that's any help mate

**Comment by JFG1000** [comment]
Just a quick update on something else I've no noticed regarding this,  I've noticed its a show that I'm watching it displays all the episodes as unwatched, but all other shows are ticked, this is only with TV shows and nothing else 
![20230227_180915](https://user-images.githubusercontent.com/76907836/221647521-27d973cb-eac3-4f36-8375-34d19d0cbb97.jpg)
