### ISSUE TITLE
Torrent links

### ISSUE THREAD

**Issue by medievil1** [Tikipeter/repository.tikipeter#133]
is it possible to NOT show torrent links?? if not there needs to be
like all things it should be a on/off user setting cause not everyone uses torrents
 there needs to be more view options for the menus as well... I like, for example, to use icons for the various move/tv/etc options, but for the settings I prefer lists...currently you can only have one or the other
 one Last request..
a New episodes tv option...like exodus and the like so it shows the episodes that aired that day with the episode description... currently the airing today just gives the show description and doesn't list the episode number or air date

**Comment by Tikipeter** [comment]
Hi @medievil1 

1. Turn off the torrent scrapers if you don't want torrent results.

2. Fen allows you to set specific views for the following:
* Main Lists
* Movies
* TV Shows
* Seasons
* Episodes
* Episodes List View (i.e. Trakt Calendar or Next Episodes)
* Trakt Lists
* Search Results
* Premium Files (i.e. browsing your cloud files).

The above includes all the differentiation in views that you are requesting (plus more).

3. I won't be including a 'New Episodes' TV option at this time. If you have Trakt, you can use the 'Trakt Calendar' to see recently aired episodes pulled from your viewing habit and Trakt Collection.
