### ISSUE TITLE
Enhancement (Filter minimum size TV shows) 

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#134]
![Screenshot_20200219-011841](https://user-images.githubusercontent.com/47715606/74789799-12228880-52b6-11ea-8b1e-7902d759c34e.jpg)
Just a example, would be cool if you can tweak this feature for TV shows (for movies 1 GB minimum 

is fine for me), but for TV shows (minimum size) MB instead of GB would be nice, so I can set the filter to like 730MB (just a example) to keep the 0,73GB  versions, and filter out the 500MB versions. 

Maximum (GB) also ok for me :)
(Just a idea, not a big issue), like this feature already.

**Comment by Tikipeter** [comment]
I like this idea. I'd just have to find another way to set the setting without using 'sliders' in the settings dialog. Because if I set the 'steps' to, say, every 0.25GB (250MB), then it would take too long to get to a higher number like 5GB.
Leave it with me..

**Comment by Tinuz97** [comment]
Also I did notice (maybey placebo, no idea?) that the links load much faster if i filter out movies, let's say below 3GB (allot of low GB movies that I do not watch).

Realy like the filter options.

**Comment by Tikipeter** [comment]
Yes, they will load a lot faster if many are filtered out.

**Comment by Tikipeter** [comment]
This will be done for next update. You will have to input the value yourself.
If you want 720MB to be the minimum size, you would input "0.72", because the setting is caluclated for GB's.

**Comment by Tinuz97** [comment]
Nice one 👌

**Comment by Tinuz97** [comment]
![Screenshot_20200219-201337](https://user-images.githubusercontent.com/47715606/74867102-611efb00-5354-11ea-9442-9bbbc095d694.jpg)
Works great 🎉👌
