### ISSUE TITLE
Persistent Issues after Nexus Update

### ISSUE THREAD

**Issue by FloridaJC** [Tikipeter/repository.tikipeter#134]
Hi Tikipeter,

**Update:** after more time on the Nvidia Shield forums, someone mentioned turning off IPV6 under internet connection settings. Did that and that stopped the issues I reported. I'll pass that on to others.  Please disregard the issue as posted.
-----------------------------------------------------------------------------------------------------------------------------
Been a while since I have had any issue.  Kodi /Fen on Windows works fine. Been using Fen via Kodi for a while on two Nvidia Shield Pro. Nexus came out then all of a sudden clicking on menu items within Fen resulted in the swirling wheel. Could not get into any Fen list. Tried all the remedies on your tool's menu, to no avail.  Even uninstalled, reinstalled Fen. The uninstalled/reinstalled Kodi.  Any any rate, even though all my other non kodi apps were working fine (Amazon, Netflix, etc...) I factory restored my Shield. Downloaded Kodi Nexus from the Google Play store. Installed Fen. 

Authorizing Trakt and RD took about two minutes for the code to come up and just as long to authorize in Kodi once code was entered at respective websites.   Once that was done, I clicked into my Trakt list and it took a good 5 minutes for list to display.  

I had to use the Kodi log file uploader as the one in the Fen tools menu was taking too long. Here is my log:

https://paste.kodi.tv/kopuyibega

I'd appreciate any insight you can give me.  Thanks for your time.

**Comment by umbrellaplug** [comment]
On Android TV go to Settings -> Apps - Kodi -> Permissions -> Files and Media and select Allow all the time.

Then reopen Kodi.

**Comment by FloridaJC** [comment]
Yes, saw that on reddit and had tried it to no avail before the IPV6 change. For some reason the IPV6 was set to on my two Shields and turning it off took care of it.  Crazy couple of days trying to find a solution. Thank you for your suggestion.
