### ISSUE TITLE
Fen with RD

### ISSUE THREAD

**Issue by batmann111** [Tikipeter/repository.tikipeter#135]
Hi all I have a problem with de add-on FEN after an update real debrid isn't working anymore.
Cleaned all cache and reauthorized RD butt nothing.
Removed the add-on new install stil RD not working other apps it work I have days enough and my IP is not blocked. 
Any one no this problem.

Thnxxx.

**Comment by Tinuz97** [comment]
Do you use a VPN? Because it sounds you have a VPN enabled.

If not, clean function cache in ResolveUrl, Auth ResolveUrl again after that, and if you use the Cached Torrents function in Fen, Auth that one again also.

Zero issues here (using RealDebrid and Premiumize)

**Comment by batmann111** [comment]
I used it butt not anymore I removed it butt the Crew is working fine so that can't be the issue right?

**Comment by Tikipeter** [comment]
Hi batmann111.
You will  have to explain what you mean by "not working".

Does Fen find RD links but they won't play, or does Fen not find any RD links at all?

**Comment by batmann111** [comment]
Fen finds a lot of RD links but if I click on the first 1.its shoots from the first stream.to the 26e and than all down to the normal streams .

**Comment by Tikipeter** [comment]
OK. Everything is working fine for me with RD, both hoster links and Torrents.

Firstly, double check that your RD subscription is active.

Then, as Tinuz97 said, go into ResolveURL settings and Reset the Function Cache.

If that still doesn't work, go back into ResolveURL settings and Re-authorize RD.

Lastly, send me through a log after playback has failed for me to look at.

**Comment by batmann111** [comment]
Tomorrow asap thnx for now👌🔥

**Comment by batmann111** [comment]
RD is active I cleared de resolve cache and authorized RD again still nothing it shows the steams from RD but goes from 1 to 511in a Second

**Comment by batmann111** [comment]
(Lastly, send me through a log after playback has failed for me to look at.)

Where can I find the log u want to see I only found event log and there is nothing to see

**Comment by Tikipeter** [comment]
Drag the picture into the comment box and it should upload, although I'm not sure a picture will do me any good. I'll probably need the whole log as a pastebin file.

**Comment by peno64** [comment]
Maybe an easier alternative is this: https://kodi.wiki/view/Add-on:Kodi_Logfile_Uploader
