### ISSUE TITLE
can't exit resume point

### ISSUE THREAD

**Issue by vip200** [Tikipeter/repository.tikipeter#136]
It is not possible to exit the window, it requires me to choose one of the options.

If I want to close the playback I have to choose one of the options and then make a stop.

It is also better if he asks where to continue playing before he starts the movie.

**Comment by Tikipeter** [comment]
This is the worst Issue I have ever had opened in over 5 years of developing Fen.

Reading it was a total waste of my time.

Thanks for making a strong case for the Issues tab to be closed permanently. Because "issues" like this are what drive devs insane.

**Comment by vip200** [comment]
![image](https://user-images.githubusercontent.com/51438486/216984217-0068bb40-6266-4d4e-8a5a-11bb2ed96e4e.png)
Hello,
I meant you can't exit this window:
