### ISSUE TITLE
Trakt error. 

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#136]
![Screenshot_20200223-024331](https://user-images.githubusercontent.com/47715606/75102097-61362980-55e6-11ea-8b97-bc08e82180d5.jpg)

Temporarily error, or did they change something in the link that pops up?

**Comment by Tikipeter** [comment]
Hopefully temporary error only. Their website is having trouble too.

**Comment by Tinuz97** [comment]
Yeah I noticed it after posting this message, I can't even reach the website, keeps loading 😅

**Comment by Tinuz97** [comment]
500
"Never send a human to do a machine's job."
Something went wrong and we're looking into it. Visit us on Twitter
to get the most up-to-date information about what's going on.
 

So we just sit back and relax 😄

**Comment by Tikipeter** [comment]
......or keep refreshing their website until it loads.
I think I'm going to watch some YouTube instead.
