### ISSUE TITLE
Links won’t show on home screen widgets

### ISSUE THREAD

**Issue by xyzfre** [Tikipeter/repository.tikipeter#137]
Using AuraMod Skin on home screen widgets using Next up from Fen which I’ve been using for a long time now notice after a couple updates when clicking on an episode from home screen widgets it starts to scrape finishes but the links are not being  displayed afterwards I really hope you could sort this out love using Fen specially next up on home screen widgets Has always been perfect

**Comment by xyzfre** [comment]
It only happens on episode on home screen widgets if I use the context  menu browse series and click an episode from there after the scrape The links show up ,so the issue is happening only on episode on home screen widgets

**Comment by xyzfre** [comment]
![58594C4F-25AE-464B-822F-E16BA03C0038](https://user-images.githubusercontent.com/49699869/75112163-0d8c0600-560f-11ea-9ebf-710b7d11ae13.jpeg)

**Comment by xyzfre** [comment]
After Scrape just get this
![D749937C-B3C7-48D5-A99B-0C026CDF0034](https://user-images.githubusercontent.com/49699869/75112175-3d3b0e00-560f-11ea-8c31-fd1741470c60.jpeg)

**Comment by Tikipeter** [comment]
Hi @xyzfre 

Not sure how I didn't notice this. Will be fixed for next update.

**Comment by xyzfre** [comment]
Thank you really appreciated much respect for your amazing work with Fen

**Comment by Tikipeter** [comment]
@xyzfre 
Should be fixed with v.1.5.103b I just uploaded.
Please let me know if the issue persists after that...

**Comment by xyzfre** [comment]
Yep you got it it’s working perfect again,, I’m constantly playing around with AuraMod Skin the BEST ,I use Fen ☝️,, Seren ,,Venom so sometimes I catch glitches and I just like to report them OCD LOL but thanks again my friend really appreciate your response your time and your fix👍🏼
