### ISSUE TITLE
Fen Update to 3.0.41 - Broke subtitles search addons

### ISSUE THREAD

**Issue by TwillightMercy** [Tikipeter/repository.tikipeter#137]
Hi,

Kodi version: 20.0

Since last Fen update to version 3.0.41 - My subtitles addons cannot find properly the correct subtitles for any movie/tv show.

I can confirm this issue affects me and and a lot of Fen users from Israel (We have a big Kodi Israel community using Fen).

**I'm searching for subtitles in two languages: Hebrew and English.** I'm using:

- All Subs Flash (Israeli subtitles addon that searches from: **OpenSubtitles, Ktuvit, Wizdom**. the last two sites are Israeli subtitles sites).

**Reverting to Fen 3.0.40 - everything works perfectly.**

I've noticed a different behavior between these two settings:

1. When Fen Metadata language is configured to **English**: subtitles search still doesn't work like it worked perfectly in 3.0.40, but it works partially and finds only subtitles from OpenSubtitles.
**kodi.log on DEBUG mode on Metadata Language English:** https://paste.kodi.tv/kopetasike
 
2. When Fen Metadata language is configured to **Hebrew**: subtitles search doesn't work at all as doesn't find anything / finds tons of irrelevant subtitles of different stuff.
 **kodi.log on DEBUG mode on Metadata Language Hebrew:** https://paste.kodi.tv/azomasonas

What is weird that on Kodi 19.5, Fen 30.041 this issue doesn't happen. only for Kodi 20.0

Your help will be appreciated, thanks!

**Comment by Tikipeter** [comment]
Fen moved over to using the (soon to be required) `info_tag = listitem.getVideoInfoTag()` and then setting the info tags like so `info_tag.setUniqueIDs({'imdb': imdb_id, 'tmdb': string(tmdb_id)})`. There are many tags to be set for the many listitem properties.

Let me know what properties the subtitle addon uses and I'll check they are being set correctly.

**Comment by TwillightMercy** [comment]
I'm not sure what properties you mean exactly (not the owner of the subtitles addons), I can upload them if it helps.
All Subs Flash 2.5.3d:
[service.subtitles.All_Subs_Flash-2.5.3d.zip](https://github.com/Tikipeter/repository.tikipeter/files/10670318/service.subtitles.All_Subs_Flash-2.5.3d.zip)

All Subs Plus 1.0.1
[service.subtitles.all_subs_plus.zip](https://github.com/Tikipeter/repository.tikipeter/files/10670313/service.subtitles.all_subs_plus.zip)

By the way, how come it did not affect Kodi 19.5 + Fen 3.0.41? it's working perfect there. broke only on Kodi 20.

**Comment by Tikipeter** [comment]
I mean do they need the imdb id, the tmdb id, the tvdb id, and/or the title.

Which of those do they use to look up the subtitles?

**Comment by TwillightMercy** [comment]
I'll try to check and update. By the way,

"Fen moved over to using the (soon to be required)..." - why it's required?

**Comment by ViewAfterReview** [comment]
I have the same issue with a4ksubtitles. The addon requires  imdb id.

**Comment by Tikipeter** [comment]
I have checked and Fen is setting the IMDb property correctly.

**Comment by TwillightMercy** [comment]
Can you identify the reason for the change that no results found in All Subs Flash from this debug log?

https://paste.kodi.tv/azomasonas

**Comment by TwillightMercy** [comment]
I’ve checked with “All Subs Flash” developer and he said it misses “setimdb” in info_tag IDs. 

I can provide log of the add-on works perfect on Fen 3.040, and a log on 3.0.41. Will it help?

**Comment by Tikipeter** [comment]
Ah, well that was included in the latest update `3.0.42` when I was looking into this, so things might be fixed on that version already. Assuming ASF dev is referring to `setIMDBNumber`.

Issue now is the repo doesn't seem to want to display the latest Fen update within Kodi.

**Comment by TwillightMercy** [comment]
Actually the repo updated for me Fen to 3.0.42 automatically,

I can can confirm All Subs Flash works now. thank you.
