### ISSUE TITLE
EN Playback Monitoring Update & EN Retries Request

### ISSUE THREAD

**Issue by ReaLx3m** [Tikipeter/repository.tikipeter#138]
So ive been bed ridden the last three days and using kodi + en practically every waking hour, and i can say with certainty that whatever you did with .40 fixed the hanging issue. And its not related to EN working better last week or so as you suggested in a previous message, as i went back to .37 and got 2 hangs in few hours, while i havent had any with .40 for a week or so including the last 3 days that i was watching stuff probably 10+ hours daily.
.40 does have some short freezes now and then, so in case you decide to address that dont get too crazy with too many changes at once :). Though personally dont really mind those.

On a side note, would it be possible for you to add a setting for how many times it retries a source before going to the next one? As 2 sometimes is not enough, imo somewhere in the range of 3-5 would be perfect. 
Or at least point me to the file where the setting is. It should be a single value change from 2 to whatever, right?

**Comment by Nuklear92** [comment]
In the version 3.0.40 and up. There's a new option found under FEN settings ---> Playback ---> Monitor Playback Success. By default, that option is ON and even trying the build for a short while with the option left ON as Tikipeter suggested since he also made a few minor adjustments to help preventing the Kodi hangs or complete freezes. For me I wasn't enough and I still got my Kodi frozen once or twice. So, what I did is the obvious workaround which is turning OFF Monitor for Playback success. And ever since I turned OFF that option, Kodi never hangs or freezes and almost all the time plays the EN sources I choose. And if it doesn't it doesn't freeze Kodi, you just have to go back to the Source Select screen and select either the same link or another and it will play fine. But, no more Kodi freezes or hangs after turning the Monitor for Playback Sucess option. 👍

**Comment by ReaLx3m** [comment]
Probably related to the power of the device. The experience i got is on a intel 4690K, which in modern affordable mini pc terms would be around Ryzen 3550H-4500U.
Youre probably using yours on an android box?

**Comment by Nuklear92** [comment]
> Probably related to the power of the device. The experience i got is on a intel 4690K, which in modern affordable mini pc terms would be around Ryzen 3550H-4500U.
> 
> Youre probably using yours on an android box?

Yup, Shield TV Pro 2019. Either way, turning that Monitor for Playback Success has been a great workaround so far. At least in my experience.

**Comment by ReaLx3m** [comment]
> Yup, Shield TV Pro 2019

Means Monitoring ON working for you too.... if youre patient enough to wait out those freezes :). Im getting around 2-3 seconds freezes maybe max 5, on the shield that would be much longer.

**Comment by Nuklear92** [comment]
> > Yup, Shield TV Pro 2019
> 
> 
> 
> Means Monitoring ON working for you too.... if youre patient enough to wait out those freezes :). 
> 
> Im getting around 2-3 seconds freezes here and there, maybe max 5 sec, on the shield that would be much longer.

I'll double check by enabling it again, but if they take more than 10 seconds with Kodi frozen something with the monitoring OFF it doesn't. Then I'll just disable it again, but I'll give it another go again and see how it goes. 👍

**Comment by Tikipeter** [comment]
Unfortunately I feel the freeze is inevitable. Whether the monitor is on or not. It's just a case of whether the inputs to cancel the monitor work when coming out of the freeze. Also the monitor will sometimes `stop()` the playback attempt, which will also cause a freeze at least on Android systems.

But I still know we had freezes long before the monitoring code was implemented. It's just a case that back then, you could hit back and eventually Kodi would give up playback. The monitoring code often made that impossible, as the back command wasn't registering.

Offering to turn off the monitoring I think was likely the only reliable way to make sure everyone can get some use out of Easynews links. Whether Andoid, Windows, Linux etc.

Thankyou both for your reports on this. Very much appreciated. One was more successful than the other, but both can now use EN links at least. :)



>So ive been bed ridden the last three days

Most importantly, I hope you are OK?

**Comment by les017** [comment]
@Tikipeter   would logs from a seemingly-fixed implementation be of any benefit to you? I've stated before that, at least for ME on both of my Shields, I have not had a single unrecoverable freeze with EN since the changes in . 38. And since implemented, I've left playback monitor ON. 

The worst I've seen is occasionally maybe a 10 second delay from initial hang to start of a retry. But then 100% it's either played the retry or moved on normally to the next source.

**Comment by Tikipeter** [comment]
>would logs from a seemingly-fixed implementation be of any benefit to you?

Thanks anyway, but not really. I think we're at a point where many will be able to use EN with the monitoring on, and others simply won't be able to. Having the option to turn it off seems like a good enough compromise to me.

**Comment by Tikipeter** [comment]
>You probably missed this part of the message(quoted below), could you address it?

I read it and then forgot about it. I'll sort something out for next update.

>Now i know you care and the least i can expect is in memoriam page in FEN when im gone :p :)

I'll replace the Easynews icon with a picture of your mug. You've earnt it I feel. I'll replace the Furk icon with my ugly mug at the same time, since I think I'm now their only customer.

**Comment by ReaLx3m** [comment]
> I'll replace the Furk icon with my ugly mug at the same time, since I think I'm now their only customer.

Good, now imagine how that single employee they keep feels every morning he gets up for work hoping that will be the day that he gets to finally retire... "Maybe this will be the day - he thought. Nope, that one freak is still on board"... Like a wandering spirit that has unfinished business on earth that prevents him to get his wings... Yore a cruel cruel man @Tikipeter :D

**Comment by Tikipeter** [comment]
Oddly specific scenario............

**Comment by Tikipeter** [comment]
Damn. I forgot to code in the choice for EN retries. Sorry mate.
I'll do it for next update. I won't wait too long for next update. Give me a couple of days.

**Comment by Tikipeter** [comment]
Re-opening so I see this and don't forget again..

**Comment by ReaLx3m** [comment]
> Damn. I forgot to code in the choice for EN retries. Sorry mate.
> I'll do it for next update. I won't wait too long for next update. Give me a couple of days.

Not a problem, have survived through bigger hardships than this :).
Thanks

**Comment by Tikipeter** [comment]
Well, this has triggered another re-write of the monitoring code. So there's that. :)

**Comment by ReaLx3m** [comment]
> Well, this has triggered another re-write of the monitoring code. So there's that. :)

Now that sounds scary, not sure if id be able to go through this unscaved :). Approach it like defusing a bomb, do it slow and steady, and if in doubt... Its the red wire most of the time :).

**Comment by ReaLx3m** [comment]
Installed .43 update, and looks like getting stuck at the resolving screen is back, had it happen once within few hours. Happened on a 4th retry of a link. Will try to get it to happen few more times, so im sure it wasnt a fluke.

**Comment by ReaLx3m** [comment]
Noticed couple more undesirable behaviours with .43
Had an occasion where it only only retried 1 time(2 times in total if counting the initial try) and got to the second source even though i have set 5 retries, playback started after going to the second source, then "FEN playback failed" popped up and playback stopped. Had also an occasion where FEN showed the same error but playback continues normally. Also one occasion with same error, and the playback bar being shown on top giving impression that its playing with white screen next episodes were shown over that white screen, upon pressing tab to get the video full screen playback stopped.
The log provided is from when the first 2 happened.
 
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/10787596/kodi.log)

**Comment by ReaLx3m** [comment]
Problem described is still present in .44, looks like its the same problem as described in [this issue](https://github.com/Tikipeter/repository.tikipeter/issues/155) 

Did the setting for number of retries require the re-write of the monitoring code? Or did you make some additional changes? If the second is true, maybe just roll back to the monitoring code that was in up to .42, as it was working ok in .40-.42.

**Comment by Tikipeter** [comment]
>Did the setting for number of retries require the re-write of the monitoring code?

Yes.

>Or did you make some additional changes?

Yes as well.

>And have the retries setting as the only change.

Not possible.

>looks like its the same/similar problem as described in https://github.com/Tikipeter/repository.tikipeter/issues/155

Do you have "Limit Resolve Attempts to Selected Result Only" set to true in the settings?

Do you have anything other than an EN account to use? If so, does that work properly?

**Comment by ReaLx3m** [comment]
> Do you have "Limit Resolve Attempts to Selected Result Only" set to true in the settings?

Nope, its off.

> Do you have anything other than an EN account to use? If so, does that work properly?

Only EN unfortunately

**Comment by ReaLx3m** [comment]
Noticed a new behavior in .45, not sure if you did any changes or i just havent used .43-.44 long enough for it to happen. If playback starts after 2 tries or more, the file starts playing for few seconds, then "Playback failed" pops up and playback gets stopped, and then it restarts playback and plays normally.
https://youtu.be/YAcrwxICv-E

And heres a video of the other variation where it just stops the video if it needs to retry the source.
https://youtu.be/u8OgJ1hVpbg

This happens pretty consistently. If video starts on the first try, then all works ok.

Could you maybe undo whatever additional changes you made to the monitoring code, and have just the minimum changes required for the "maximum retries", and hope that that will resolve it.   

P.S.
The new scraping screen looks pretty cool, but it looks bit off. Better to use the same font/size/position as the resolving(playback monitoring) screen imo.

**Comment by Tikipeter** [comment]
![screenshot00002](https://user-images.githubusercontent.com/28930002/221290198-ec796282-4376-4606-a101-a440ea1e6799.png)

Change this setting to 5000ms and see if it makes a difference. If it does, set it back 500ms at a time and test until it stops making a difference. Then set it 500ms above that point.

**Comment by ReaLx3m** [comment]
> Change this setting to 5000ms and see if it makes a difference. If it does, set it back 500ms at a time and test until it stops making a difference. Then set it 500ms above that point.

Oh cool, didnt even notice that theres a new setting there. Will give it a go and let you know how it went in a day or few when i have enough data and am certain of the outcome.

**Comment by ReaLx3m** [comment]
Looks like videos dont stop after starting anymore. I set attmpts at 3000ms. Though the "Playback failed" popup is still there.
Had it get stuck and unable to get out of the resolving screen 2 times. 
EN has been working better and getting stuck doesnt happen as often as it used to a month or so ago(with other older versions tnah .40-.42), but if/when that level of EN performance gets back, getting stuck will become more frequent occurence i think. So thats not ideal and a step back compared to .40-.42.
Also noticed that now "FEN Error" pops up for files with no sources, instead of "No sources" popup, which can be misleading and make one think that something else is the problem why a Movie/TV show doesnt play.

**Comment by ReaLx3m** [comment]
@Tikipeter  You mentioned in issue #174 that youre aware of the "playback failed" popup and that youre going to eork on it, which implies that its still present. I think its worth mentioning that for me it was solved with one of the recent bugfix updates, im on .52 atm and dont have that popup anymore even if playback starts after 1 or more retries.

**Comment by Tikipeter** [comment]
That's interesting.

Does that mean playback overall is working correctly for you now, or is it just that particular issue that's been fixed?

**Comment by ReaLx3m** [comment]
That particulal issue with the popup "playback failed" i havent had for few days now, and it did happen pretty consistently. 
As for getting stuck at the resolving screen and unable to get out with back button, but needening to reload skin, not sure, as that one happens less frequently.
Ill stay on .52 for the time being and try to force it to get stuck by trying to play loooots of episodes, and will let you know in few days.

**Comment by ReaLx3m** [comment]
Decided to do a quick test and went back to .51 and got the popup right away on 3 out of 3 shows that played with 1 or more retries. Reinstalled .52 and again dont have them anymore. So looks like whatever you did with .52 is what solved that popup.
Might be worth mentioning that with .45(what i had before .52) i had to set "Pause between playback attempts" to 3000ms so it doesnt stop playback after initially starting it(https://youtu.be/YAcrwxICv-E), and with .52 i have this at the default value of 1500ms and playback doesnt stop.

**Comment by ReaLx3m** [comment]
So i tested probably 70+ episodes from different shows and havent had it stuck once, untill i ran into a show that got it stuck at resolving screen 4 times in a row with different episodes. Episodes would play ok after you try the same episode again after reloading skin to exit from the resolving screen.
Peculiar visual thing i noticed is that the kodi spinning wheel is been shown before it gets stuck, near the end of the video at 31s - https://youtu.be/pap18UbEm3c . Havent noticed this in the other instances where everything was ok. 
And dont judge me on the choice of show :P, i was trying everything in order.

**Comment by ReaLx3m** [comment]
Just an update, while maybe not that big deal at the moment as EN has been working better, but still as of 3.1.08 getting stuck at the resolving(playback monitoring) screen is still an issue. Using 3.0.42 as thats the latest version i know that doesnt exibit this behavior.
That "Real Housewives of Miami" looks like a good benchmark, i could trigger the behaviour straight away with that show on 3.1.08.

**Comment by ReaLx3m** [comment]
So it happened that it got stuck with 3.0.42 too. So as of now last version i dont remember ever having that problem is 3.0.17 which had the old play check. Though not really willing to go back that far and use that one to make 100% sure that it doesnt happen there too.
@Tikipeter Btw am i just writing to myself here? As i havent seen you react in any way for quite some time in this thread.

**Comment by Tikipeter** [comment]
I have notifications off for all issue threads and I've gotten mixed up on what the reply count was for this and likely the other playback thread here.

The next update, `3.1.12' will have some changed code in it regarding playback. I'm hoping it might fix these intermittent issues. Fingers crossed as always.

**Comment by ReaLx3m** [comment]
> I have notifications off for all issue threads and I've gotten mixed up on what the reply count was for this and likely the other playback thread here.

And ive been sitting here heartbroken for more than a month... I dont know, i dont know, i think we should see other people. I was about to create my own addon which would be 1 better than yours in every aspect, it would have been called GFO. Every letter is 1 higher in the alphabet, cant mean anything else but better, thats what ive been taught. I was getting mad and even thinking of HGP, but i guess 2 better would be considered as using excessive force. And ofcourse it would have had built in blackjack and hookers, nobody can beat that...

Joking aside, i did spend lots of hours trying to reproduce the bug, and not getting any response didint look good to me. Ive been doing all that work to help with improving the addon, not out of motivation for personal gain, as i can accept and/or get around any issue in one way or another, like i was doing many years before i started posting on your github.

> The next update, 3.1.12 will have some changed code in it regarding playback. I'm hoping it might fix these intermittent issues. Fingers crossed as always.

Didnt give any updates on the situation since my last post month ago, as i thought you lost interest in this, but since it turns out im wrong, here it is...
This last month, been using  3.1.10(maybe even .09, cant recall) and the 3.1.11 update when it came out, and without trying to force the bug, i havent had a single hang happen. 
With the new progress bar, it will usually retry a link when it gets to around 3/4 to 4/5 of the way, and indication that its about to get stuck was if it goes all the way to the end, and it stays there(this was with version 0.8). With .10 ive had couple close calls with it getting to the end and thinking it got stuck, but after waiting for few seconds(probably 10-15) it did work ok and retry.

So if possible, just in case, keep the code thats in .10 and .11, so you can easily roll back if it turns out that .12 is worse in some aspects. Could happen that the isssue is solved by accident in .10-.11. 
I will try to force the bug in both .11, and .12 when its out and let you know.
