### ISSUE TITLE
[Request] Please add Real-Debrid "History" link

### ISSUE THREAD

**Issue by host505** [Tikipeter/repository.tikipeter#139]
On 'Premium Services/Real-Debrid', it would be nice to have an item for history (recently resolved by r-d items) as well (hxxps://real-debrid.com/downloads).
Only thing keeping me to still use an r-d dedicated add-on ;)
Not sure if the other debrid services offer this as well.

**Comment by Tikipeter** [comment]
Howdy @host505 

Added for next update "**REAL DEBRID:** Download History" in Real Debrid's Premium Services folder.

Cached for 2 hours like the cloud.

Clear both cloud and download history with the Clear Cloud Cache function.

I should really scrape this for RD Cloud results as well.....

**Comment by host505** [comment]
Oooot! Many thanks.
I find it quite useful in cases where I, well, fall asleep while watching something, then when I decide to continue watching it I don't have to browse/scrape/choose link etc, just go to r-d history and the last used link is there.

**Comment by Tikipeter** [comment]
I was going to ask you what you use it for. :)

**Comment by host505** [comment]
Mind you, this list doesn't only contain fully downloaded items, it lists all recently resolved by r-d items, whether cached on r-d or from supported hosts.

**Comment by host505** [comment]
Thank you for implementing it, @Tikipeter and taking it steps further.
One more question/req on this: do you think the server of each file is easily fetchable from this list?

**Comment by Tikipeter** [comment]
Do you mean the original server i.e. "rapidgator", or do you mean the RD server it's now coming from i.e. "rd.syd4"?

**Comment by host505** [comment]
I meant the original server (if it comes from a host, eg rapidgator), but now I realise that when you play it it actually plays from r-d, so not really need to know the original host.
