### ISSUE TITLE
[Feature] Hide items in watchlist if not released yet

### ISSUE THREAD

**Issue by JacopoV** [Tikipeter/repository.tikipeter#14]
Hi there! 

I hope you don't mind this ticket being opened. 
It's not specifically an issue at all in Fen (again, thanks for your work and nice to see you back in the scene), but mainly if it is possible to implement a useful (at least in my opinion) feature : 

- possibility to hide items in Trakt watchlist if the content is not released yet (so if the release date is bigger than the actual current date) and, as soon as it's released, add it to the list again. 

I looked into the API for Trakt and movies/tv shows do have a release date field. Inside FEN source, Trakt handling script has already "current_date" being used around. 
I tried to play with the code a little bit, but i m not familiar with Python or Kodi addons. 

Well, there it is. You can close directly the ticket if you don't like receiving feature suggestions or you think it's nor worth it or too complex. 

Thanks for you time, i really appreciate it.

**Comment by Tikipeter** [comment]
The considerations are mainly built around exactly which lists this should be associated with.

Only the Watchlist? Explain why the Watchlist specifically needs this feature.

Also, it would need to be a setting if implemented, so it could be turned on/off.

**Comment by JacopoV** [comment]
Hi!

Well I would say go any list at this point, just for consistency. So yeah all list would be great.

Regarding the second point, I think that would be best to leave the option open for the user. I the intent is not to broken the behavior among all Fen users.

**Comment by Tikipeter** [comment]
Of course, I've changed my mind. :)
I'm only going to implement this for Trakt Watchlists. Mainly because it would either be that or all Personal Lists. And I can't implement it properly for users with IMDb lists. So it'll just be for Trakt Watchlists only.

I'll write the setting name here once I've set it up.

**Comment by JacopoV** [comment]
Oh I see. Well sounds good for me! 😉

Thanks a lot👌 looking forward for it! 🎉

**Comment by Tikipeter** [comment]
Settings->Navigation->Content->"Include Unaired Media in Trakt Watchlists".

You'll need to turn that OFF. It will be ON by default.

**Comment by JacopoV** [comment]
Ah a thing that I noticed. Some movies or TV shows have no date, they're "planned" or "in production" from what I see, as status in Tmdb.
So in that case the rule will still apply as hide the content 😊🙏

**Comment by Tikipeter** [comment]
As long as it has a release date from Trakt it will be fine. I'll add some code for titles with no release date to exclude them as well (no release date almost always means definitely not released).

I'll try and find a movie with no release date to make sure it works.

**Comment by JacopoV** [comment]
Great!

From what I see (at least from the skin) Deadpool 3, Max Max The Wasteland, Extraction 2 for example, have no date. It that helps!

**Comment by JacopoV** [comment]
It's working great! Thanks so much! 😊
