### ISSUE TITLE
Show changes on startup setting ignored

### ISSUE THREAD

**Issue by BP-onthemove** [Tikipeter/repository.tikipeter#140]
Since a few versions back. I love to see the changes but when fen is started from a widget it prevents it from going further while not seeing the changes too. I hope I explained clear enough.
Love all your work though!🙂

**Comment by Tikipeter** [comment]
Hi BP-onthemove 

I start Fen from a widget and I always get the changelog upon version change.

I'm not entirely clear on what you're saying. I understand the following:
* You start Fen from a widget.
* The changelog is not automatically showing when there's an update, even though you have it set to show.

What I don't understand is:

> ....prevents it from going further while not seeing the changes too.

Do you mean Fen won't even start?

Are you using Kodi 17, because it wasn't working for 17 and under, but I very recently pushed an update to fix that.

**Comment by BP-onthemove** [comment]
Thanks for your reaction :), much appreciated!

About: "....prevents it from going further while not seeing the changes too.":

This part seems to work again. I just tested this. I saw 1.6.200 was there and started a video from a widget. It worked!  I thought that problem was related to showing the changelog on a Fen update. I may have made a wrong assumption there. 

But what I could not test now was if the setting "disable autoview of changelog on Fen updates" worked or not when starting the fen add-on normally from video add-ons. Maybe I can check this on the next uodate. (I use Kodi 18.5)

Thanks a lot for your efforts! Have a great day!

**Comment by Tikipeter** [comment]
Oh, OK. I understand what you mean now. Yes, the results not showing was a different bug that is fixed now.

With regards to the changelog showing/not showing issue, can you go to Tools->Changelogs & Log Viewer and test if you can view the log manually that way? Just to help narrow down the issue.

Also, when you do open Fen from the widget, is it opening to the root menu (the main Fen menu), or do you have it set to open somewhere else within the add-on. The changelog is coded to pop up upon first navigation into the MAIN Fen menu. If you open any other part of Fen, then it will not show until you open the main menu.

**Comment by BP-onthemove** [comment]
Hi, yes I can view the changelog via tools normally. On the next update I will check if the setting  to not see it on startup is working. (When starting Feb normally via add-ons)

The other problem through a widget is solved indeed. But you wanted to know more about the widget. The widget shows a trakt list in Fen with movies (but also happens with another with next episodes) and once chosen it starts to search available sources directly. So not starting from the main view. But this is solved now thanks so much!

**Comment by BP-onthemove** [comment]
Hi! I can confirm the problem is not there anymore. I checked with the last 2 releases. When view changes on startup is disabled, I don't see the changes anymore 🙂. Thanks for your efforts and listening! Have a good weekend!
