### ISSUE TITLE
Feature Request: Autoplay next episode option similar to umbrella.

### ISSUE THREAD

**Issue by Liquidrag** [Tikipeter/repository.tikipeter#140]
H TikiPeter, this isn't an issue but a feature request. Umbrella has this excellent option for the up next window to pop up after the subtitles end or a percentage. Just thought it would be an excellent option.

**Comment by TwillightMercy** [comment]
Fen - settings - playback

**Comment by Tikipeter** [comment]
Percentage: Already exists.
Subtitle: I will not be implementing this.

**Comment by Liquidrag** [comment]
> Percentage: Already exists. Subtitle: I will not be implementing this.

Thank you.
