### ISSUE TITLE
I think you forgot to modify settings_files folder files. (BUG) 

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#142]
Like the txt says.
The settings.xml is edited in the latest version, but not the ones in the settings_files folder. So probably that is going to give issues when switching between basic and advanced 😉

**Comment by Tinuz97** [comment]
or is the settings.xml the advanced version now?

**Comment by Tinuz97** [comment]
Yup,looks like, closing this one.

**Comment by Tikipeter** [comment]
I forgot to switch it back over to basic for the last update.
As a tip, no matter what the settings.xml is on update, as soon as you open the Main menu in Fen, it will replace it with the one you had before the update. I should really make that a service, so users don't have to enter the main menu before their settings.xml file gets put back to right. Too much to do right now, and my work holiday is quickly coming to an end. :( :(
