### ISSUE TITLE
Fen v3.0.42 not appearing in Repo

### ISSUE THREAD

**Issue by ShibajiCh** [Tikipeter/repository.tikipeter#143]
Hi @Tikipeter,

I guess there's some issue with the latest Fen update or the Repo. The latest Fen version 3.0.42 is not appearing in the Repo even after manually checking for updates in Kodi. Also, I tried to install it via the Zip from GitHub but it is showing Invalid structure error. I'm using Kodi Nexus v20 on an Nvidia Shield TV Pro. Please advise.

Here's my Kodi log:

https://paste.kodi.tv/jiwerarosa

Thanks and Regards,
ShibajiCh.

**Comment by Tikipeter** [comment]
Nothing wrong with the update or the repo from what I can see.

It's not showing in the repo for me either though.

Maybe tomorrow it will show.

Nothing really I can do about it. The zip installed fine for me in the meantime.

**Comment by ShibajiCh** [comment]
Fine @Tikipeter. Usually the updates in the repo reflect immediately. Hence, I raised this concern.

I'll extract the Fen zip from the GitHub package and install it manually then. You may close this ticket if you want.

Thank and Regards,
ShibajiCh.

**Comment by xyzfre** [comment]
Same on my end as well usually the update shows up as soon as I start up Kodi 🤔

**Comment by TwillightMercy** [comment]
Same for me

**Comment by ShibajiCh** [comment]
The new Fen version 3.0.42 is still not showing in the repo on Kodi even after checking manually for updates. This never happened before. Fen always automatically updates from the repo as soon as I start Kodi. This time I had to manually download the zip from GitHub and install it on Kodi.

**Comment by xyzfre** [comment]
Update: I tried this earlier but it didn't work, now I tried again check manually for updates and got the new version .42

**Comment by Tikipeter** [comment]
Yeah I changed the md5 value, so Kodi would check again. But I did get the update through on one install before doing that.

I also STILL cannot get the latest version through from the test repo.

Who knows what's going on. All I can do is make sure the zip is OK, and the addons.xml is formatted correctly.

**Comment by Tikipeter** [comment]
`3.0.42` JUST came through on the test repo for me. So everything might be OK now (hopefully).

**Comment by ShibajiCh** [comment]
Hi @Tikipeter,

Is there some ongoing issue with GitHub Repos because yesterday I couldn't see Fen addon version update and today I can't see many other add-on version updates like Otaku, etc. Never faced such issues before. I checked on both my android mobile and on my Nvidia Shield TV Pro. Please advise if you're aware of any ongoing issues.

Thanks and Regards,
ShibajiCh.

**Comment by Goldenfreddy0703** [comment]
Hey @ShibajiCh surprise seeing you here but yeah there is something going on with my repo so im glad im not the only one who was having the issues with my repo.

**Comment by Goldenfreddy0703** [comment]
There is even a reddit post of someone noticing this as well. 
https://www.reddit.com/r/Addons4Kodi/comments/10zpm3u/addons_are_not_updating_to_latest_version_from/

**Comment by ShibajiCh** [comment]
Hi @Goldenfreddy0703,

Yes, glad to see you here too. 🙂 I've been noticing this issue since yesterday and was pulling my hair out thinking it's something to do with my Kodi setup, but then I tested on different devices and found out that it was an ongoing issue everywhere. Hope it gets resolved soon.

By the way that Reddit post was also posted by me only. 🙂

Thanks and Regards,
ShibajiCh.

**Comment by Tikipeter** [comment]
Nothing devs can do about this.

**Comment by Goldenfreddy0703** [comment]
True, we found out that it was a github issue yesterday and we thought something was wrong with our repositories. Hopefully they can fix it soon.

**Comment by AakashC2020** [comment]
Hi @Tikipeter and @Goldenfreddy0703,

Thank you both! 👍🏻
