### ISSUE TITLE
'cosmetic' error (Trakt) 

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#144]
Just a cosmetic error I guess, because auth does work fine after it.
But I am interested why it does show that error, something changed in the url maybey?
But it does work fine the auth. 
![Screenshot_20200226-013954__01](https://user-images.githubusercontent.com/47715606/75300847-6c34c800-5839-11ea-96f0-a8204ab10cef.jpg)

**Comment by Tinuz97** [comment]
(it did notice this earlier, few weeks back, forgot to report it)

**Comment by Tikipeter** [comment]
Yeah I noticed this too a few weeks ago. But the other day I re-authed Trakt and it didn't do it, so I'm not sure of the issue. I'm keeping an eye on it.

**Comment by Tikipeter** [comment]
I just checked, though, and the URL hasn't changed. So it isn't that at least.

**Comment by host505** [comment]
@Tikipeter I think it's the poll for authorization. You have code to check if the user has submitted the auth code every x seconds, right? You must've added infodialog for trakt errors recently, so if the user hasn't applied the code upon the checks it shows the infodialog with the (by-design) error.

**Comment by Tikipeter** [comment]
Ah, of course! I'll have to adjust the error notification to not include this polling. Thanks host505!

**Comment by Tikipeter** [comment]
Fixed for next update. Thanks guys. :)
