### ISSUE TITLE
FEN doesn't find EN link where another add-on does

### ISSUE THREAD

**Issue by les017** [Tikipeter/repository.tikipeter#144]
Hi tikipeter - I had previously raised issue #61 but never got back to you properly with a log. This time I made sure it's an ongoing issue.

Please see [https://paste.kodi.tv/ehizohuhog](https://paste.kodi.tv/ehizohuhog) 

FEN finds no links on the scrape for The New Yankee Workshop for all of season 5.

Asgard add-on does find one EN link and plays it successfully. 

I use FEN directly and do NOT use Kodi library but I do have TMDB helper installed just for the ability to try another add-on via context menu.

I have seen this same thing with a few other shows in the past, but they are lost to antiquity and I did not capture the error.

Thanks for your attention and effort on this great add-on.

**Comment by Tikipeter** [comment]
They're found for me.

**Comment by Tikipeter** [comment]
![screenshot00001](https://user-images.githubusercontent.com/28930002/218306556-2d4a7044-68fd-45d2-a6d8-30fbf4477647.png)

etc.....

**Comment by les017** [comment]
Interesting. I've tried all of the few settings in FEN provider and CoCo scrapers, no change.
 I guess this is a one-off and I'll just use the other add-on for this show. Thanks for checking.

![PXL_20230212_125353417](https://user-images.githubusercontent.com/236296/218312746-82194d48-81cf-4394-abe5-05f07d02320f.jpg)

**Comment by Tikipeter** [comment]
Cocoscrapers will make no difference for Easynews results.

Apart from the specific Easynews settings, check also the general filter settings as well.

Apart from that, I wouldn't really know why. You could pay attention as to whether there's a count registering whilst scraping that then doesn't show. That would signify filtering.

**Comment by les017** [comment]
Ok thanks. I'll keep sniffing around on easynews.

There are no items counted during scrape. I'll close this but maybe resurface it if I see this on more shows in future. I use easynews as my primary source and I watch some pretty obscure stuff so if anyone will have additional issues like this it'll be me 😉

Thanks again
