### ISSUE TITLE
RD Unchecked...

### ISSUE THREAD

**Issue by Converted007** [Tikipeter/repository.tikipeter#145]
Hi,

I noticed this issue:

Some are mark as 'rd unchecked', why's that? Is it funky magnet form and can't get the infohash correctly?

Thanks for solving:)

**Comment by Converted007** [comment]
https://github.com/Tikipeter/repository.tikipeter/issues/62

It was adressed here too. But apparently its back.

**Comment by Tikipeter** [comment]
Hi @Converted007 

When you say "Some are mark as 'rd unchecked'", what do others say? Do you have Settings->Results->Torrents Sorting & Filtering->"Check RD/PM/AD for Cached Torrents" enabled? Have you authorized your RD account in Fen AND ResolveURL? Do you have other debrid accounts authed? I don't have quite enough information to go on here.

More generally, 'unchecked' only shows when the torrent hasn't been checked on that debrid service. If the magnet is funky I throw the result away, as it's of no use.

**Comment by Converted007** [comment]
> Hi @Converted007
> 
> When you say "Some are mark as 'rd unchecked'", what do others say? Do you have Settings->Results->Torrents Sorting & Filtering->"Check RD/PM/AD for Cached Torrents" enabled? Have you authorized your RD account in Fen AND ResolveURL? Do you have other debrid accounts authed? I don't have quite enough information to go on here.
> 
> More generally, 'unchecked' only shows when the torrent hasn't been checked on that debrid service. If the magnet is funky I throw the result away, as it's of no use.

Some say RD. But most of them say RD Unchecked. They do play tho.
The Cached Torrents setting is enabled.

RD account is authorized in both resolveURL and FEN.

And nope, im only using Real Debrid.

**Comment by Tikipeter** [comment]
The torrent links can only display 'RD CACHED', 'RD UNCACHED'  or 'RD UNCHECKED'. It cannot say 'RD' for torrents of any kind.

You may need to post a picture of what you are describing. Something is not right.

**Comment by Converted007** [comment]
> The torrent links can only display 'RD CACHED', 'RD UNCACHED' or 'RD UNCHECKED'. It cannot say 'RD' for torrents of any kind.
> 
> You may need to post a picture of what you are describing. Something is not right.

I will try to make a picture in the next coming hours. The color is green for sure. So thats makes it a torrent right?

**Comment by Tikipeter** [comment]
The default for a torrent is "magenta". It's like a purple/pink. But the colors are changeable in the settiings so it could be anything.

If you get to the results screen with the issue on a computer, you can press ctrl + s and it will take a screenshot. You can then drag that screenshot into one of these comment boxes and it will upload it.

**Comment by Converted007** [comment]
> The default for a torrent is "magenta". It's like a purple/pink. But the colors are changeable in the settiings so it could be anything.
> 
> If you get to the results screen with the issue on a computer, you can press ctrl + s and it will take a screenshot. You can then drag that screenshot into one of these comment boxes and it will upload it.

![screenshot003](https://user-images.githubusercontent.com/36426581/75418392-9ec2eb80-5933-11ea-82e0-c76baf97a79f.png)
![screenshot002](https://user-images.githubusercontent.com/36426581/75418395-a08caf00-5933-11ea-9909-fb061a61621a.png)
![screenshot001](https://user-images.githubusercontent.com/36426581/75418397-a08caf00-5933-11ea-97c5-4d626e3e64fc.png)
![screenshot000](https://user-images.githubusercontent.com/36426581/75418398-a1254580-5933-11ea-800b-daf3c873a4d3.png)


Made a few screenshots. I didnt changed anything about the colors in the app. So all standard. Except the 720 color, thats light green.

**Comment by Tikipeter** [comment]
Thanks Converted007, I appreciate those screenshots. :)

Firstly, you must have 'Highlight Results Based On..." set to Quality. That means there will not be color differences based on scrapers and torrents. So the results which have the "RD UNCHECKED" tag are torrents, and the ones that have the "RD" tag are hoster files (not torrents).

Personally, I would change that setting to "Scraper", so that you see the difference visually between a hoster file and a torrent file. You would change that from Settings->Results->Display->Highlight Results Based On... 

On to your "RD UNCHECKED" issue. It can only be one of 2 things:

1. You don't have RD auth'ed in Fen. Please check by going to Settings->Accounts->Real Debrid. If you don't see your "Real Debrid Username" as the first item under the Real Debrid settings (greyed out but visible), then you are not auth'ed.

2. You don't have Settings->Results->Torrents Sorting & Filtering->"Check RD/PM/AD for Cached Torrents" enabled. If this is not enabled, Fen doesn't check if a torrent is cached or not, and thus returns all torrents as "UNCHECKED".

I know you've already stated that you have both those above conditions met. But barring a fundamental error in the code (which I and others would also be experiencing), then these are the only 2 ways you could be seeing what you are seeing.

In a perfect world, you will realize one of those settings is not set correctly and it will solve all your problems. :) :) :)

**Comment by Converted007** [comment]
> Thanks Converted007, I appreciate those screenshots. :)
> 
> Firstly, you must have 'Highlight Results Based On..." set to Quality. That means there will not be color differences based on scrapers and torrents. So the results which have the "RD UNCHECKED" tag are torrents, and the ones that have the "RD" tag are hoster files (not torrents).
> 
> Personally, I would change that setting to "Scraper", so that you see the difference visually between a hoster file and a torrent file. You would change that from Settings->Results->Display->Highlight Results Based On...
> 
> On to your "RD UNCHECKED" issue. It can only be one of 2 things:
> 
> 1. You don't have RD auth'ed in Fen. Please check by going to Settings->Accounts->Real Debrid. If you don't see your "Real Debrid Username" as the first item under the Real Debrid settings (greyed out but visible), then you are not auth'ed.
> 2. You don't have Settings->Results->Torrents Sorting & Filtering->"Check RD/PM/AD for Cached Torrents" enabled. If this is not enabled, Fen doesn't check if a torrent is cached or not, and thus returns all torrents as "UNCHECKED".
> 
> I know you've already stated that you have both those above conditions met. But barring a fundamental error in the code (which I and others would also be experiencing), then these are the only 2 ways you could be seeing what you are seeing.
> 
> In a perfect world, you will realize one of those settings is not set correctly and it will solve all your problems. :) :) :)

Thanks:) will take a look later and let you know.

**Comment by Converted007** [comment]
> Thanks Converted007, I appreciate those screenshots. :)
> 
> Firstly, you must have 'Highlight Results Based On..." set to Quality. That means there will not be color differences based on scrapers and torrents. So the results which have the "RD UNCHECKED" tag are torrents, and the ones that have the "RD" tag are hoster files (not torrents).
> 
> Personally, I would change that setting to "Scraper", so that you see the difference visually between a hoster file and a torrent file. You would change that from Settings->Results->Display->Highlight Results Based On...
> 
> On to your "RD UNCHECKED" issue. It can only be one of 2 things:
> 
> 1. You don't have RD auth'ed in Fen. Please check by going to Settings->Accounts->Real Debrid. If you don't see your "Real Debrid Username" as the first item under the Real Debrid settings (greyed out but visible), then you are not auth'ed.
> 2. You don't have Settings->Results->Torrents Sorting & Filtering->"Check RD/PM/AD for Cached Torrents" enabled. If this is not enabled, Fen doesn't check if a torrent is cached or not, and thus returns all torrents as "UNCHECKED".
> 
> I know you've already stated that you have both those above conditions met. But barring a fundamental error in the code (which I and others would also be experiencing), then these are the only 2 ways you could be seeing what you are seeing.
> 
> In a perfect world, you will realize one of those settings is not set correctly and it will solve all your problems. :) :) :)

So i checked a few things. I set like you said the "Highlight Results Based On..." on Scraper instead of Quality.
Now it gives that purple color for a torrent and a blue color for an RD stream.

About the RD Unchecked thing: 1) to be sure i re-authenticated RD within FEN again.
2) That checkbox is enabled.

The movies i searched for are Knives Out, Once Upon a Time in Hollywood, Bad Boys for Life and Ford vs Ferrari in the category Popular.
Oh and my kodi-version is 17.6 (don't ask why it's not 18.5 lol)

You are probably right that the torrents aren't cached yet. But i didn't saw any cached torrent yet in FEN...

**Comment by Tikipeter** [comment]
There should be STACKS of cached torrents for those titles. You're probably going to have to get me a log at this point, because yiu should be seeing a lit of cached torrents.

Restart Kodi, run a search, and post the log here.

**Comment by Converted007** [comment]
> There should be STACKS of cached torrents for those titles. You're probably going to have to get me a log at this point, because you should be seeing a lot of cached torrents.
> 
> Restart Kodi, run a search, and post the log here.

Ok will do. Just a normal search for a movie? And a normal log?
Ill try to do it in the next couple of days.

**Comment by Converted007** [comment]
> There should be STACKS of cached torrents for those titles. You're probably going to have to get me a log at this point, because you should be seeing a lot of cached torrents.
> 
> Restart Kodi, run a search, and post the log here.

https://paste.kodi.tv/mizisacopo

This is the log. Is this ok?
