### ISSUE TITLE
Excluding Dolby Vision files doesn't work

### ISSUE THREAD

**Issue by TwilightMercy** [Tikipeter/repository.tikipeter#145]
Hi,

Re-opening the issue, this time on Dolby Vision only. (Your last workaround of Cocoscrapers issue worked for HDR exclusion).

Kodi version: 20.0
Fen version: 3.0.42
Metadata langauge in fen settings: Hebrew

DEBUG kodi.log:
https://paste.kodi.tv/zohucuzedu

Example:

![image](https://user-images.githubusercontent.com/29895680/218320397-c6cf7ef5-888d-465e-aac0-d3bbdba1492c.png)

**Comment by Tikipeter** [comment]
It needs to be fixed by cocoscrapers dev.

Some scrapers are returning wrongly formatted info.

Torrentdownload is one of them.

**Comment by TwilightMercy** [comment]
> It needs to be fixed by cocoscrapers dev.
> 
> Some scrapers are returning wrongly formatted info.
> 
> Torrentdownload is one of them.


I see. How can I contact them for an issue?

And the workaround you did for HDR can’t be applied for DV?

**Comment by Tikipeter** [comment]
You can't contact them. Their issues tab is closed.

>And the workaround you did for HDR can’t be applied for DV?

The workaround for HDR was reversed last update and is staying that way as it caused other issues. So there will be no similar fix for HDR.

The workaround of disabling Torrentdownload can be applied by you though.

**Comment by TwilightMercy** [comment]
I see, Do you know if Cocoscrapers is even getting updates?

And do you mean to disable Torrentdownload here?
And is it the only provider that causes the DV/HDR filtering issues, or there are more?

**Comment by TwilightMercy** [comment]
> You can't contact them. Their issues tab is closed.
> 
> > And the workaround you did for HDR can’t be applied for DV?
> 
> The workaround for HDR was reversed last update and is staying that way as it caused other issues. So there will be no similar fix for HDR.
> 
> The workaround of disabling Torrentdownload can be applied by you though.

I see, Do you know if Cocoscrapers is even getting updates?

And do you mean to disable Torrentdownload here?
![image](https://user-images.githubusercontent.com/29895680/218328403-2345c05f-477a-4b22-b9d6-77b55d711f75.png)


And is it the only provider that causes the DV/HDR filtering issues, or there are more?

**Comment by Tikipeter** [comment]
>And do you mean to disable Torrentdownload here?

Yes.
