### ISSUE TITLE
Feature Request - Connect Real Debrid/Trakt account with QR code Image

### ISSUE THREAD

**Issue by TwilightMercy** [Tikipeter/repository.tikipeter#146]
Hi,

It's a small feature request that will make the authorization process to RD/Trakt, etc.. way easier and faster.

It will be really appreciated if for example, the "Real Debrid" Authorize window will contain QR image to scan from phone, directly to the link:
https://real-debrid.com/device

**For example:**

![image](https://user-images.githubusercontent.com/29895680/218321129-9181d461-0bb5-4896-828e-fb97b0c286e1.png)

**Instead of:**

![image](https://user-images.githubusercontent.com/29895680/218320826-ca98f234-9ff1-4a79-a8d9-110799a4490f.png)

**Comment by Tikipeter** [comment]
Where do I get the QR code from?

**Comment by TwilightMercy** [comment]
> Where do I get the QR code from?

https://www.qr-code-generator.com/

**Comment by Tikipeter** [comment]
RD Auth, PM Auth, AD Auth, Trakt Auth all now have QR Codes. So not so little request, but done anyway.

You will have to test these next update, as I don't have a device that can read QR Codes. They may be too "squashed" in the image.

**Comment by TwilightMercy** [comment]
No problem, I’ll update you!

**Comment by Ade-AV** [comment]
Can you also add it to the Log File Uploader please

**Comment by TwilightMercy** [comment]
QR images works perfectly
