### ISSUE TITLE
Subscription update error

### ISSUE THREAD

**Issue by ricinga666** [Tikipeter/repository.tikipeter#146]
Hi Peter

Since Monday, subscription updates seem to fail.  

I've tried resetting subscriptions but still get the same error.  Not sure if you are aware of the issue.

**Comment by Tikipeter** [comment]
I was not. Thanks ricinga666 for bringing it to my attention. Do you know what the error was?

**Comment by ricinga666** [comment]
Not sure looks like tikimeta related.

[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/4263940/kodi.log)

**Comment by Tikipeter** [comment]
Looks like your metadata file is corrupted. This issue may resolve itself with the latest fen and tikimeta updates pushed today. (v.1.6.003a and 1.1.36).

If not, let me know.

**Comment by ricinga666** [comment]
Hi Peter

I have updated to the new versions and still have the same issues.  I've cleaned a few databases and reset the subscriptions but I keep having the issue.  so far same across three devices.

**Comment by Tikipeter** [comment]
Yeah I think I know the problem, and I'll hopefully have a fix for next update.

You could probably get it working again yourself by navigating to your userdata folder, then script.module.tikimeta and deleting an metacache#.db files in that directory.

Then, browse into ANY movie or TV Show page (e.g. Movies Trending) BEFORE an update is performed, and it should make the database correctly.

Unfortunately, even after the next update, you are going to have to manually delete any metacache#.db files in that folder, unless you do it now. So you may as well give it a shot.

**Comment by ricinga666** [comment]
Right I deleted a the meta databases files then went to trending movies and then I ran an update.  It still fails.  I tried it a few times switch restarts after the different steps.  And the best I can get is clearing my subscription folders and rescanning.  This gives me one correct update but any subsequent ones fail.

**Comment by Tikipeter** [comment]
I'll need another log after replicating your above steps.

**Comment by ricinga666** [comment]
Here you go.  I cleared the metadata database went to movies /trending then came out and then went to tolls and clicked update this is the log.


[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/4313514/kodi.log)

**Comment by Tikipeter** [comment]
Had you added any new shows to Subscriptions around the time this started?

**Comment by ricinga666** [comment]
Probably I do add shows to my list whenever I see something I fancy.

**Comment by Tikipeter** [comment]
There are changes to the subscriptions code for next update (v.1.6.05)
