### ISSUE TITLE
Improve ASF Subtitles add-on auto matching to links from Fen

### ISSUE THREAD

**Issue by TwilightMercy** [Tikipeter/repository.tikipeter#148]
Hi,

As a continuation of my previous subtitles related issue:
https://github.com/Tikipeter/repository.tikipeter/issues/137

Which you fixed perfectly! (In Fen `3.0.42` - the subtitles add-on works perfectly with `setIMDBNumber`)

I have another question/request (if possible).

### subtitle add-on also supports auto matching the best available subtitle according to the torrent name, and it sorts the results by percentage and picks the highest matching subtitle for the Movie/TV show.

Example for the feature - Movie "Black Adam" - played through Fen:
**Link Selected:**
![image](https://user-images.githubusercontent.com/29895680/218832622-c2e94548-3816-466d-bebe-08d54ed2cba6.png)

You can see the ASF add-on finds the best subtitle with **100% matching rate** - because the subtitle file name and torrent file name are the same:
![image](https://user-images.githubusercontent.com/29895680/218832386-2af9e97c-3a72-40d6-ac4a-8aa1d7015932.png)

### **However, not all of links played through Fen are working with this feature, example:**

**Link selected:**
![image](https://user-images.githubusercontent.com/29895680/218833459-e40b9045-88b5-4dd3-b15f-828909b0013a.png)

As you can see, ASF **poorly** matches the subtitle because of weird file name `00018.m2ts`:
![image](https://user-images.githubusercontent.com/29895680/218833266-9cb07d29-72fb-4c92-9754-4cde42602b17.png)

I've asked ASF developer about this and he said:

**> "If Fen could send the magnet link name to the player as tagline, it will work for every link selected, in order to better match the subtitle results."**

### Adding DEBUG kodi.log which I:
1. Play "Black Adam" with the good link example, search for subtitles - ASF matches subtitle with 100% matching percentage.
2. Then play again "Black Adam" but with the bad link example (`00018.m2ts`), search for subtitles - ASF cannot use it to match.
Log: https://paste.kodi.tv/iveluxaziz

Thank you for all of your hard and best work.

**Comment by Tikipeter** [comment]
>send the magnet link name to the player as tagline

If I do that, then skins that display the tagline as part of the OSD when bringing up info during playback will have the title of the torrent file being played instead of the actual tagline of the movie.

Does the dev really mean to set the listitem's tagline as the torrent title? Because if so I won't be doing that.

**Comment by TwilightMercy** [comment]
Do you have any other suggestion where the torrent title can be send to the player?

**Comment by Tikipeter** [comment]
> Isn’t the name appearing only in the subtitles search window?

What do you mean? You said the dev wants me to set the torrent name as the tagline.

> Do you have any other suggestion where the torrent title can be sent to the player?

It can be any property the subtitle addon will look for. But not one that would usually  serve another purpose.

**Comment by TwilightMercy** [comment]
> > Isn’t the name appearing only in the subtitles search window?
> 
> What do you mean? You said the dev wants me to set the torrent name as the tagline.
> 
> > Do you have any other suggestion where the torrent title can be sent to the player?
> 
> It can be any property the subtitle addon will look for. But not one that would usually serve another purpose.

The subtitle addon needs to get the torrent name, the addon can read any info from the player , I don't know of any parameter that is useless, any idea how to do that?

**Comment by Tikipeter** [comment]
The playing file can have any property set. `asf.filename`, `asf.torrent_name`. Anything he wants.

Just not a specifically assigned by Kodi property

**Comment by TwilightMercy** [comment]
> The playing file can have any property set. `asf.filename`, `asf.torrent_name`. Anything he wants.
> 
> Just not a specifically assigned by Kodi property.

`asf.torrent_name`

**Comment by Tikipeter** [comment]
`getProperty` can be used to get any property from the listitem.

**Comment by TwilightMercy** [comment]
> `getProperty` can be used to get any property from the listitem.

I see, `asf.torrent_name` is perfect

**Comment by TwilightMercy** [comment]
> `getProperty` can be used to get any property from the listitem.

ASF dev:

i tried this:
`listItem.setProperty('torrent_filename',torrent_name)`

but how can i get the property from the player?
this code:

```
xbmc.getInfoLabel('ListItem.Property(torrent_filename)') return "",
this:
'
playerid_query = '{"jsonrpc": "2.0", "method": "Player.GetActivePlayers", "id": 1}'
playerid = json.loads(xbmc.executeJSONRPC(playerid_query))['result'][0]['playerid']

torrent_name_property = '{"jsonrpc": "2.0", "method": "Player.GetItem", "params": {"playerid": ' + str(playerid) + ', "properties": ["torrent_filename"]}, "id": 1}'
 torrent_name = json.loads(xbmc.executeJSONRPC (torrent_name_property))
```

returns 'Invalid params.'

and there is no getProperty for videoplayer or xbmc.player(),
any idea?
thanks

**Comment by Tikipeter** [comment]
What about a window property instead?

I can set a window property when starting the video.

Example: `xbmcgui.Window(10000).setProperty('asf.player_filename', file_name)`

fetch it using `xbmcgui.Window(10000).getProperty('asf.player_filename')`

**Comment by TwilightMercy** [comment]
Hi,

ASF dev tested it and it works!
Can you add this as a window property, as your example?

And maybe, if will be used by other subtitles add-ons, it can be a generic name like `torrent.player_filename`

**Comment by Tikipeter** [comment]
I'll add `subs.player_filename`, because `torrent` isn't really generic either. People still play hoster files as well.

**Comment by TwilightMercy** [comment]
Thank you very much. 

Will it be available in 3.0.44, or 3.0.45?

**Comment by Tikipeter** [comment]
`3.0.44`.

Next update.

**Comment by TwilightMercy** [comment]
> What about a window property instead?
> 
> I can set a window property when starting the video.
> 
> Example: `xbmcgui.Window(10000).setProperty('asf.player_filename', file_name)`
> 
> fetch it using `xbmcgui.Window(10000).getProperty('asf.player_filename')`

Hi tiki how are you?

I've downloaded your latest Fen test .zip file (version 3.0.43k), and I've noticed that you added the `subs.player_filename ` paremeter.
ASF dev told me to check with you if it's a window property or not, because it is not the code you've sent here as an example (that he tested and worked for him)

![image](https://user-images.githubusercontent.com/29895680/220668623-24c6b694-8cc9-403c-998d-4ac289725aea.png)

**Comment by Tikipeter** [comment]
Yes, it is a window property. The code I used as an example above will work for him.

**Comment by TwilightMercy** [comment]
Works.
