### ISSUE TITLE
NO event text or plot and missing show name bug maybe set up help

### ISSUE THREAD

**Issue by cabban** [Tikipeter/repository.tikipeter#148]
![image](https://user-images.githubusercontent.com/19514493/75511358-4dc3fd80-59ee-11ea-8490-1cb38e99bc62.png)

![image](https://user-images.githubusercontent.com/19514493/75511344-43a1ff00-59ee-11ea-8fc9-c263cdfa49f4.png)

![image](https://user-images.githubusercontent.com/19514493/75511294-135a6080-59ee-11ea-86bb-f59054888afc.png)
i
![image](https://user-images.githubusercontent.com/19514493/75511269-f7ef5580-59ed-11ea-9dec-9cdeccc61a6b.png)
![image](https://user-images.githubusercontent.com/19514493/75511271-f7ef5580-59ed-11ea-9563-904b6e7fdd78.png)

 try to se plot there is no plot, and its only from tw show, works in venom @Tikipeter dont know why this is blank on some and no plot on almost every show i tried, hope u could helpo :)

**Comment by Tikipeter** [comment]
Clear metacache and restart Kidi.

**Comment by cabban** [comment]
> Clear metacache and restart Kodi.

still no plot of
