### ISSUE TITLE
V1.5.31 Cache Clear Error

### ISSUE THREAD

**Issue by flhthemi** [Tikipeter/repository.tikipeter#15]
Just updated to 1.5.31 getting error when attempting to clear providers cache.

![screenshot000](https://user-images.githubusercontent.com/8205131/61997334-2549de80-b06e-11e9-86b9-a544a3bac9a9.png)

If it helps from the kodi.log

ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named debrid
                                            Traceback (most recent call last):
                                              File "C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.fen\fen.py", line 217, in <module>
                                                clear_cache(params.get('cache'))
                                              File "C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\modules\nav_utils.py", line 242, in clear_cache
                                                from resources.lib.modules.debrid import DebridCache
                                            ImportError: No module named debrid
                                            -->End of Python script error report<--

**Comment by Tikipeter** [comment]
Thanks flhthemi.

I forgot one thing on last update. It broke this and auth'ing debrids. I will be home to fix it in about 5hrs.

**Comment by Tikipeter** [comment]
v.1.5.32 fixes this issue.
