### ISSUE TITLE
Feature Request - Global Context 

### ISSUE THREAD

**Issue by JFG1990** [Tikipeter/repository.tikipeter#150]
Hi there first of all I would like to say thank you for all the hard work that goes into this amazing addon, would it be possible to add things like rescrape, and a trakt manager that allows users to add things to watchlists etc from widgets on our home screens? Currently this can only be done inside the addon. Thankyou!

**Comment by Tikipeter** [comment]
Hi JFG1990.
This is already available.
Go into the tikipeter repository->Context menus and install "Fen Context Menu".

**Comment by JFG1990** [comment]
Oh that's awesome I'll take a look thanks, by the way do you know how i can get rid of these 2 random episodes that have appeared in my next episodes section? They are the 2 bottom ones in the image I'll attach, seven worlds I've never even watched and modern family is an old episode, they do not appear in other addons with progress etc 
![20200228_222509](https://user-images.githubusercontent.com/61604210/75592780-25361500-5a7b-11ea-8975-6d3c29576261.jpg)

**Comment by JFG1990** [comment]
I have just checked out the global context menu which is cool, are we able to add trakt manager and re scrape to it?

**Comment by Tikipeter** [comment]
Yeah, rescrape SHOULD be in the "Fen Settings" menu (which should be called Fen Options), but it doesn't appear for the widget. Hopefully I can add it.

Trakt Manager I can add.

I'll do an update of the context menu add-on today.

As for those shows, I don't know why they're there. Are there 2 shows that should be there that are missing?

**Comment by JFG1990** [comment]
Thanks that's much appreciated if you could also add clear progress that would be awesome. Thanks very much 
I've also noticed that having the length of the episodes in this skin view cuts of the word continuing is there something you could do? I have other addons like venom and seren and they do not include the length on this skin view enabling the word to appear. Many thanks 

![20200228_231007](https://user-images.githubusercontent.com/61604210/75594099-82cc6080-5a7f-11ea-91f7-ef396153727c.jpg)
