### ISSUE TITLE
It can be possible?

### ISSUE THREAD

**Issue by RunAway189** [Tikipeter/repository.tikipeter#150]
I've just discovered Fen and I felt in love with it so, first of all thanks for your amazing work. I'm here just to kindly ask if it would be possible to just add a simple results filtering based on specific language. This feature could help a lot of users that try to find that content in their native language like me. Multi-language filter is already there, I know but it's easy to get frustrated in short time opening the link and check if the desired language is there.

Thank you in advance for your time and your attention.

**Comment by Tikipeter** [comment]
How would I do this?

**Comment by RunAway189** [comment]
Unfortunately I don't have the technical skill to do such thing but I know it would be possible: I've checked the latest version of Gaia and it allows you to show all the results filtering and selecting the language you are searching for. Gaia is good and usable but honestly not even close as good as Fen is. That's why I'm here asking for your help. I'm not sure if this feature is strictly related to a CocoScrapers integration tho. By the way I'll be here for everything you would ever need (testing and experimenting)

**Comment by Tikipeter** [comment]
You've now said, in 2 posts, both that adding this filter would be "simple", and that you "know it would be possible".

So whilst you may not have the ability to write the code, you must know what the code will need to do to achieve language filtering.

Just tell me what information is available that I can use to filter the results. Then I can code it into the addon on your behalf.

How do you currently decide which stream has which language? I can automate that.

**Comment by RunAway189** [comment]
I'm currently looking into the Gaia add-on to find this but as I said, I'm not expert in python language and coding in general. If only I was capable of that I would already contributed on this. I'll let you know as soon as I find the code related to this filtering stuff. The fact is that I don't know if I can post it here or I'm not allowed to. Feel free to get in touch with me wherever you prefer. As I said, I'm genuinely impressed and I'd like to give my contribution. Thanks again

**Comment by Tikipeter** [comment]
Forget about code. How do YOU currently decide what language the results are? What information do YOU currently use to decide which result to play back when you see the list of results?

**Comment by RunAway189** [comment]
I honestly don't know how they do that. The add-on allows you to set an audio primary and secondary language into the add-on settings or, in alternative, once the search is finished you can long press the "enter" button and set a lot of filters such as audio channels, video quality and also the audio language. As I said, I don't know if it's a check of the filename (for example: name.ita.eng) and then it's flagged as italian content. I should check with other languages and see if it's correctly working even if the language it's not displayed into the title. At that point it checkes the metadata? I don't know, I'm just trying to guess.

I'll let you know as soon as I finish to do this check

**Comment by RunAway189** [comment]
I've tested and I'm pretty sure the control and the tag is based on the torrent filename as I said you earlier.

For example
filename.eng.hindi tags the file as English and Hindi audio language and so the user can apply the filter. Hope it helps

**Comment by RunAway189** [comment]
> 

Yeah, but you need to open the link and check. It happens that you even can't read the full name of the file and it's way uncomfortable. Also, excluding undesidered language allows you to load more links for your desired one

**Comment by Tikipeter** [comment]
This is the issue....... you need to open the link and check.

The addon doesn't have any more information available to it than what it is showing the user. That's why I was trying to ask you how you filter the wrong language links currently, when selecting what to play.

The only way to successfully and accurately filter by language is to begin playback of EVERY result returned and check what languages are available for it.

That is wby no addon does it.

**Comment by RunAway189** [comment]
> This is the issue....... you need to open the link and check.
> 
> The addon doesn't have any more information available to it than what it is showing the user. That's why I was trying to ask you how you filter the wrong language links currently, when selecting what to play.
> 
> The only way to successfully and accurately filter by language is to begin playback of EVERY result returned and check what languages are available for it.
> 
> That is why no addon does it.

Yeah but as I said if a torrent has a filename like: torrentname.fr-eng you are sure that the file has surely two languages (france and english). My idea is basically to edit the CocoScrapers add-on adding an "inclusive filter" which is corresponding to the language. So if someone select France it will show only "torrentname.fr-eng" and every other files which has "fr, france" or anything related to that language. If nothing is showed then the add-on may ask you to ignore the filter in order to try with some remuxes or other files which may be multilanguage. That's basically my idea

**Comment by Tikipeter** [comment]
It's not worth the effort.

Usually the file will have nothing in the filename. If a dev offers audio filtering based on language, and then 85% of the results are unable to be filtered, then it is just going to cause a whole line of people whingeing that the filter doesn't work.

All these things have been thought of many times. Unless each file is opened, there is no way to do it.

**Comment by RunAway189** [comment]
Yes, I perfectly understand why you are hesitating doing this. I've just tried to give a look at the code of Coco and it's too advanced for me sadly, I'm not able to add anything of what I had in my mind. Thanks anyway for your kind attention and support. Wish you all the best
