### ISSUE TITLE
Feature Request - Cached Results

### ISSUE THREAD

**Issue by JFG1990** [Tikipeter/repository.tikipeter#151]
Would it be atall possible to add a setting to fen that allows us users to organise our results by debrid service lists for example currently when they are displayed we have PM and RD cached together, would it be possible to have a setting that allows us to have PM cached results first then RD cached results second or vice versa 😁

**Comment by Tikipeter** [comment]
Maybe after I stop using ResolveURL for debrid playback, but  not before then.
