### ISSUE TITLE
Search menus do not play nice with creating paths with builds

### ISSUE THREAD

**Issue by JFG1990** [Tikipeter/repository.tikipeter#152]
Hi there apologies to keep laying these on you, I'm trying to explain this the best i can but currently when trying to set paths when making builds, fens search menus don't play nice, if you set the path to create menu item from here, the search box will pop up, you cancel then click ok to save the path which is fine, but when you then click search on the build you do the search, then when you next go back into search to look up a new movie or show, it won't bring up the search box, it instead brings up the previously searched movie/show, would it be atall possible to have seperate search menus that have a screen saying new movie or show search that us users could save a path to. This is probably a really confusing read so i apologise 😂

**Comment by Tikipeter** [comment]
Fen doesnt support making shortcuts to the search menus. You can add a Kodi variable (system uptime for instance) into the url when making the shortcut. That should work.

**Comment by JFG1990** [comment]
Ok not to worry thanks anyway
