### ISSUE TITLE
Scrape box sources

### ISSUE THREAD

**Issue by JFG1000** [Tikipeter/repository.tikipeter#152]
Hi k
![20230216_221715](https://user-images.githubusercontent.com/76907836/219499670-b3d917c1-187f-44d2-8383-21feff37f8a5.jpg)

Hi mate is it possible to add a setting so we can have the 4k links first to show on this scrape box? It's now SD

**Comment by Tikipeter** [comment]
It won't matter. Next update has a new display.

**Comment by JFG1000** [comment]
Sweet thanks mate

**Comment by Greg0580** [comment]
Thank you.  Looking forward to the New Update.  And thank you for all the Time and Effort you put into Fen and Coco Scrapers.  👍

**Comment by JFG1000** [comment]
@Tikipeter thankyou for this latest update it looks great,  would it be possible to add a setting so we can change the colour? Would be cool to change it to green instead of grey. 
![20230222_182542](https://user-images.githubusercontent.com/76907836/220722094-bbf5ea4d-a0e6-4e31-adb9-7fa1d2a19580.jpg)
