### ISSUE TITLE
Fen isn't working correct for me

### ISSUE THREAD

**Issue by ANHBOB** [Tikipeter/repository.tikipeter#153]
I'm not sure how it happen but when I open Fen (I'm using the 4K Firestick and use the center circular button on the remote) then choose say movies, when I find a movie I'd like to see I press on the center button...nothing happens.  The only way I can watch a movie is to long press the center button...choose Select Source...then it'll start scraping.
ALSO when wanting to watch a TV series....after selecting the show...when pressing the center button..nothing happens (before it would open the seasons).  Now I have to long press the center button..go to explore to see the seasons.
I'd like it to go back to the way it was before...so I don't need to long press the center button. I've gone through all the settings many times to see if something is off. I've even tried reinstalling Fen.

**Comment by Tikipeter** [comment]
I'm away from a computer right now, so i can't give you the correct wording of the setting but....
Its in Settings->Navigation. Something like "Open with Extended Info...". Set that to OFF or NEITHER. I am hink you've got it set  to BOTH currently.

**Comment by ANHBOB** [comment]
Thank you so much. It was driving me crazy for the past 2 days. That was it..set that to Off under Settings>General>Navigation>Open Extended Info when Selecting>Off. Thank you again
