### ISSUE TITLE
Fetch all ratings from IMDB instead of TMDB

### ISSUE THREAD

**Issue by Pharaoh2k** [Tikipeter/repository.tikipeter#153]
Is there any way to fetch all ratings from IMDB instead of TMDB or can this option be implemented, please?

**Comment by Tikipeter** [comment]
Not without significant slowdowns to the addon. So, no.

**Comment by Tikipeter** [comment]
Is it possible you only meant for this from within the Extras window?

Because that wouldn't slow down Fen. But it would require a setting to place an OMDb API key.

**Comment by Pharaoh2k** [comment]
I am not sure what you mean by "extras window". A screenshot would be helpful if you can.
What I meant is, for example, in a list of series season episodes, currently, the rating is by TMDB (many episodes on TMDB don't even have a rating as it's not as popular as IMDB, and their rating is by itself inaccurate in my personal opinion). 
IMDB ratings are much better and have a lot more voters. 
I have made a Greasemonkey userscript for IMDB (https://greasyfork.org/en/scripts/2033-add-movie-ratings-to-imdb-links-by-pharaoh2k) so I realize fetching ratings can be slow, but perhaps this can still be added as a feature with a notice/warning such as (SLOW), or (Much slower than TMDB, etc.) and will be disabled by default and enabled as a user choice/preference.
Btw, it's an amazing add-on, truly appreciate your work and dedication! :)

**Comment by Pharaoh2k** [comment]
Also, after the first listing, caching (with expiry, like 14 days hardcoded, or configurable) can make loading the episodes page instant.

**Comment by Pharaoh2k** [comment]
There are many links you may wanna check out here:
https://github.com/topics/imdb-api

And I know there is also a developer api and other paid APIs that users can use if they have the key, so that can be an option.
Plus, the feature can always be made as opt-in, rather than default, as I pointed out earlier. So and performance hit is up to the user, if they want much better ratings - they may choose to wait a bit and fetch them, or just stick to the default TMDB.
There can be many ways this can be implemented I think.

**Comment by Tikipeter** [comment]
Noted.
