### ISSUE TITLE
feature suggestions discover exclude words in title

### ISSUE THREAD

**Issue by cabban** [Tikipeter/repository.tikipeter#154]
my mom loves the hallmark movies but not want to discover all christmas word titles now
maybe is possible to add a link to all them hallmark movies, or discover with all tvshow romance drama but exclude the world christmas dont show movies with word christmas in title :) until 1 december then she is discover just winter and christmas movies again :) 

@Tikipeter she SAYS THANK U in advanced

**Comment by Tikipeter** [comment]
It's a bit more work than it sounds, but I'll do this for next update. I'll have to add "Companies" and "Keywords" to Discover, but it's doable.

As always though, relying on other services (TMDb in this case) will mean it might not be perfect. You will be able to tell Discover "Hallmark Movies without "Christmas", but if a Christmas movie isn't tagged with "Christmas" in their database it will sneak through. It should be decent enough though.

**Comment by cabban** [comment]
Thank u now it's maybe 120 movies if that value is lowered I'm happy I
belive in you young tiki may the force be with u😀

måndag 2 mars 2020 skrev Tikipeter <notifications@github.com>:

**Comment by Tikipeter** [comment]
This will be ready for next update.
You will need to:
* Go into "Discover: Movies"
* Select "Companies" and type in "Hallmark"
* You can choose multiple companies. I chose "Hallmark Entertainment" and "Hallmark Hall Of Fame Productions"
* Select "Exclude Keywords" and type in "Christmas"
* You can choose multiple excluded keywords. I simply chose "Christmas".

If you are exporting the list to, say, the movies menu, you will want to shorten the title that Fen Discover automatically gives it. i.e. rename it to something like "Movies | Hallmark" and get rid of the rest of the title.

Be warned, though, this did give a lot of results (I stopped looking at 6 pages of 20 results each), but there are not a lot of Christmas titles in there. So I think the keyword filter is doing it's job pretty well. You could add some other filters to get that number down i.e. use Start Year and End Year to limit the number of years of titles.

Also, you probably won't get many/any scraper search results for a lot of these movies, as they will be fairly obscure.

**Comment by cabban** [comment]
Thank u all it needed was to filter off Christmas. I know hallmark is many
movies😀you are best

tisdag 3 mars 2020 skrev Tikipeter <notifications@github.com>:

**Comment by cabban** [comment]
@Tikipeter  i tried , but all christmas movies was in the list anyway, i exclude word in title christmas any ideas :)?

**Comment by Tikipeter** [comment]
Make sure you are entering "Christmas" in the "EXCLUDE Keywords" field and not the "INCLUDE Keywords" field.

If you are sure that is correct, show me a couple of screenshots with what you have entered into the Discover fields.

**Comment by cabban** [comment]
> Make sure you are entering "Christmas" in the "EXCLUDE Keywords" field and not the "INCLUDE Keywords" field.
> 
> If you are sure that is correct, show me a couple of screenshots with what you have entered into the Discover fields.
here is one example that many christmas is here :) 
![image](https://user-images.githubusercontent.com/19514493/75921872-39ef2000-5e62-11ea-9d49-a3d8b5627459.png)

![image](https://user-images.githubusercontent.com/19514493/75921816-16c47080-5e62-11ea-95cd-0da34e02e8a0.png)
cheers @Tikipeter

**Comment by Tikipeter** [comment]
![screenshot000](https://user-images.githubusercontent.com/28930002/76334059-a4163200-6346-11ea-9d4c-4cb8aba733cf.png)

I get a totally different set of results with the same filters...

**Comment by cabban** [comment]
Haha yes it is strange does plot works for you?

tisdag 10 mars 2020 skrev Tikipeter <notifications@github.com>:

**Comment by Tikipeter** [comment]
Yes.

**Comment by cabban** [comment]
Ok still not me no plot no TV shows😂

tisdag 10 mars 2020 skrev Tikipeter <notifications@github.com>:
