### ISSUE TITLE
Trakt Watchlists not loading anything

### ISSUE THREAD

**Issue by KalAvroniev** [Tikipeter/repository.tikipeter#154]
First off, I want to say welcome back, I'm so glad that you resurrected this add-on. It is my favourite and I love how responsive you are to issue resolutions.

Recently I noticed that the watchlists do not load anything. I've tried both Movies and TV Shows nothing.
I cleared all cache and database, but no luck.

I tried SEREN and I can see the watchlists there

I looked at the logs and cannot see any errors but just in case - [https://paste.kodi.tv/supeniyaze](https://paste.kodi.tv/supeniyaze)

**Comment by Tikipeter** [comment]
Try "check for corrupt databases" and then restart Kodi.

The only fail in that log is for Seren navigating to myMovies.

Make sure you've performed the action that's failing within the log you post.

**Comment by KalAvroniev** [comment]
I did that also, no corruption was detected.
Seems like it is just not triggering anything when I go to the watchlist views. That's why I said I could not see anything in the logs with or without debug on. The log above is me going to those views. You can see where I enabled debug and went back to both watchlist views 
`2023-02-21 19:34:31.969 T:2501     INFO <general>: Log level changed to "TRACE"
2023-02-21 19:34:31.969 T:2501     INFO <general>: Enabled debug logging due to GUI setting. Level 2.`

**Comment by Tikipeter** [comment]
Do other Trakt list menus work? Collections?

Do all other Fen menus work except Watchlist?

Did you just install this new version of Fen? Did you previously have a version `2.x.x` version of Fen?

Are you navigating within the addon to open the Watchlists, or are they widgets?

**Comment by KalAvroniev** [comment]
> Do other Trakt list menus work? Collections?

Trakt Collections all work

> Do all other Fen menus work except Watchlist?

- Trakt My Lists, Linked Lists give me nothing
- Trakt Recommended all work
- Trakt Calendar works
- Trakt Trending User Lists, Popular User Lists and Search Lists all work

> Did you just install this new version of Fen? Did you previously have a version 2.x.x version of Fen?

No, I've been on version 3 for months possibly since the resurrection of the addon.
 
> Are you navigating within the addon to open the Watchlists, or are they widgets?

Direct within the addon, no widgets or builds, pure Kodi, only custom is the skin (Confluence). Tried going back to Estuary - same experience doesn't even attempt to load anything.

**Comment by Tikipeter** [comment]
At this point, seeing as there is actually nothing wrong with the Watchlist, My Lists or Linked Lists menus for anyone else, I would probably navigate to your userdata folder and into `addon_data/plugin.video.fen/databases` and delete the `navigator.db` file.

Then restart Kodi. See if that works.

**Comment by KalAvroniev** [comment]
I tried that same, nothing loading

**Comment by KalAvroniev** [comment]
I even tried reauthorizing Trakt and still nothing.
I guess the only solution is to uninstall and reinstall the addon if you have no other ideas.

**Comment by Tikipeter** [comment]
No more ideas I'm afraid.

Make sure to select for Kodi to delete the data when you uninstall. That's really the only important bit of the uninstall/reinstall process.

**Comment by KalAvroniev** [comment]
Sorry to say it, but I did all that and still not working. That is so strange

**Comment by KalAvroniev** [comment]
I think I found the issue.
What I did was start with fresh Kodi, installed Fen only, authorised with Trakt and started making settings changes.
After each change, I went back to check the WATCHLISTS.
I narrowed down the issue to the Navigation settings.

When I change the Sorting for Watchlist to Release Date it stopped loading, reverting back to Title gets it going again. I then checked the other profiles and they have the same setting but are working, which makes me think I have a movie/tv show with some weird release date that breaks the addon.

**Comment by Tikipeter** [comment]
>When I change the Sorting for Watchlist to Release Date it stopped loading, reverting back to Title gets it going again. I then checked the other profiles and they have the same setting but are working, which makes me think I have a movie/tv show with some weird release date that breaks the addon.

Good job. I did test that when I was trying to see what was going rong, but of course it still worked fine for me as well.

I'll have a good look at the code and see why it's failing completely. At worst it should just not show the offending media.

**Comment by Tikipeter** [comment]
![screenshot00001](https://user-images.githubusercontent.com/28930002/221269822-a4ed4fed-776c-494f-adb4-fdd560714d56.png)

What is your setting here?

Try toggling that setting and see if the Watchlist works when sorting is by release date.

**Comment by KalAvroniev** [comment]
I have that on and I can confirm that if I switch it off then the WATCHLISTs work.

I think I had it on so I can see upcoming new shows, which I have added to my watchlist, on the Next Episodes view.

I guess the solution, for now, is to have that On and sort by Title or have that Off and sort by Release Date

Let me know if you are going to look into this so I can have both the soft and hard tacos ;)

**Comment by Tikipeter** [comment]
For sure I am going to look into it.

I have no troublesome data to check with, but I'll fiddle around and hopefully have a fix for next update.

**Comment by KalAvroniev** [comment]
Maybe find a movie or a tv show on trakt that has no release date yet and add them to your watchlist.

Maybe Now You See Me 3 - movie, The Walking Dead: Dead City - show

Here is my trakt watchlist, if that helps - [https://trakt.tv/users/solitarybg/watchlist?sort=released,desc](https://trakt.tv/users/solitarybg/watchlist?sort=released,desc)

**Comment by KalAvroniev** [comment]
Thanks for all your awesome work

**Comment by Tikipeter** [comment]
I appreciate it. But it was mainly you that got it sorted in the end.

The Walking Dead: Dead City was perfect. Let me reproduce the error.

Fixed for next update.

**Comment by KalAvroniev** [comment]
I can confirm issue is fixed for TV Shows but not for Movies, that still breaks
