### ISSUE TITLE
Fen Error playback

### ISSUE THREAD

**Issue by tfouto** [Tikipeter/repository.tikipeter#155]
When the option "Limit Resolve Attempts to Selected Result Only" is enabled, and try to open Real Debrid files most of the time there is a Playback failed. If I disable the option, there is no problem on playback.
 EN files doesn't seem affected by this error, at least not to the same extent. I dont see any relevant in logs.

Https://paste.kodi.tv/omehuhejuz

**Comment by Tikipeter** [comment]
Looks like an issue with RD playback, not to do with the "Limit Resolve Attempts to Selected Result Only" setting.

**Comment by tfouto** [comment]
I can reproduce it over and over just for enabling/disabling the setting. I think it's strange that's a problem with RD, not related at all with the setting, as is always giving error when the setting is On, and vice-versa. 

But of course I can't say for sure, as I don't know the code.

**Comment by tfouto** [comment]
This error remains, the same. I can reproduce exactly all the time, for specific files. For instance. Gunther gunther's millions first real debrid link. Always playback failed when "Limit Resolve Attempts to Selected Result Only" setting is on. Always playback ok when setting off.

Tried with 3 different devices (Nvidia Shield, Windows PC, Android Tablet).
