### ISSUE TITLE
Missing 'Size' info for Debrid hosters. (BUG)

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#155]
I noticed the size info is missing for debrid hosters, as a example Rapidmoviez,that one did show the size of the file before,but others are missing also.

The rapidmoviez.py from openscrapers has the code for it,and i am sure it did work in the past.

Rapidmoviez.py :
				try:
					size = re.findall('((?:\d+\.\d+|\d+\,\d+|\d+)\s*(?:GiB|MiB|GB|MB))', name)[0]
					div = 1 if size.endswith(('GB', 'GiB')) else 1024
					size = float(re.sub('[^0-9|/.|/,]', '', size)) / div
					size = '%.2f GB' % size
					info.insert(0, size)
				except:
					pass

**Comment by Tinuz97** [comment]
(tested with movie Frozen 2, and then scroll down to Rapidmoviez)

**Comment by Tinuz97** [comment]
(Torrents file size working fine,almost forgot that)

**Comment by Tikipeter** [comment]
I'll have this sorted for next update. :)

**Comment by Tinuz97** [comment]
Fixed,thx :)
