### ISSUE TITLE
Auto play TV Episodes

### ISSUE THREAD

**Issue by Randalllind** [Tikipeter/repository.tikipeter#157]
I notice when autoplay is enabled there is a weird bug. The bug is this let's say you have 4 episodes and the 4th one is not release because it comes out next week. You start episode 1 then Fen auto-plays 2, 3 then it will play 4 with the title for 4 but the video is episode 3.

**Comment by Tikipeter** [comment]
Fixed for next update (v.1.6.05)

**Comment by Randalllind** [comment]
Thanks :)
