### ISSUE TITLE
Possible Workaround - EN playback

### ISSUE THREAD

**Issue by tfouto** [Tikipeter/repository.tikipeter#157]
I have noticed that when I am playingback the files on My Services->EN->Search, and then play the files, there is 100% of success in playing the file. No errors. On the other way when trying to open from source select on a movie/series, sometimes it fails.

Is it possible that enabling some new setting that would allow, when choosing some EN source, in the background Fen would search by filename and filesize to catch the exactly file, the same way it searches, via My Services->EN->Search, and then play automatically? Even if it took more 3 seconds to do the Extra Search->Playback, I would prefer that if it would work 100%.

Thanks

**Comment by Tikipeter** [comment]
No. That is not really a solution.

It is purely coincidence that the videos searched through My Services currently play correctly for you. They are the exact same videos with the exact same url being fed to Kodi.
