### ISSUE TITLE
Improvement of Playback resume

### ISSUE THREAD

**Issue by TwilightMercy** [Tikipeter/repository.tikipeter#158]
Hi,

General question/suggestion,

I've noticed that if you want to resume playback, you select the link, and then when player loads it pop ups for "Resume from XXXX / Start Over"
![image](https://user-images.githubusercontent.com/29895680/220663560-96380d61-55d9-4784-a87e-75d3c88bdcb5.png)

And then the player freezes for 1 second, then jumps to the resumed time.

my dev friend suggested that if you display the resume window before you start the video, you can use "InfoTagVideo.setResumePoint() " that will make the jump much faster in Kodi player.

Keep up the amazing work!

**Comment by Tikipeter** [comment]
That will mess with the successful playback check, so it is on the to-do list but has not been done yet.
