### ISSUE TITLE
NOTICE: Tikiscrapers Returns and Debrid Resolving Handled by Fen.

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/repository.tikipeter#159]
Hi anyone who checks these issues.

There are a couple of big changes to Fen with the next update (v.1.6.05).

The first change is Fen will now handle all resolving of debrid services. This is currently limited to Real-Debrid, Premiuimize.me and All-Debrid. No other debrid services are supported at this time. I will attempt to add debrid services if requested.

What does this mean for you?
* Users are no longer required to enter their debrid accounts in ResolveURL for debrid to work in Fen. Fen will no longer use any debrid accounts from ResolveURL.
* This does mean, however, that you MUST have your debrid accounts authorized in Fen for debrid to work going forward.
* At the moment, resolving cached torrents and hoster links are supported. I will soon be writing code to support loading uncached torrents onto your debrid cloud, but it is not currently implemented. If you have not enabled checking if torrents are cached, then you will continue to see 'Unchecked' next to the torrents. Fen will check if they are cached upon selection, and resolve them if that is the case.

The second change is a return to Tikiscrapers instead of Openscrapers. This is due purely to necessity, and hopefully Fen can return to Openscrapers soon. The changes to Fen away from ResolveURL, and a couple of other issues, have made it impossible to currently use Openscrapers as Fen's external scrapers. So I need to re-use Tikiscrapers for a while. I remain committed to helping the devs of Openscrapers when I can, and acknowledge the great work that is done by them. This return to Tikiscrapers is more of a temporary 'fork' of Openscrapers so I can implement the changes to resolving debrid within Fen.

What does this mean for you?
 * Hopefully, there will be a smooth transition on the next update, where Tikiscrapers will be installed on your system if not already. Fen will then use Tikiscrapers for it's external sources.
* Importing other scraper modules (an old Tikiscraper feature), WILL NOT be present in this new iteration of Tikiscrapers. There are currently too many differences between the scraper modules to successfully implement this feature. The code is still there, and perhaps it can be brought back in the future, but not currently.
* There are more scrapers in Tikiscrapers (and more broken), so it would be a good idea to turn on Remove failing scrapers and let Fen remove scrapers that don't return results on time. Also turning on Stop Search Early if Most Sources Finished would be good to turn on as well.

Hopefully everything goes smoothly and there are no interruptions to people's systems. In saying that, it's always a good idea to have another add-on handy in case something goes wrong.

**Comment by xyzfre** [comment]
Is there anything we have to do on our end for the update tried yesterday and today but no update has went through

**Comment by Tinuz97** [comment]
> Is there anything we have to do on our end for the update tried yesterday and today but no update has went through

 Because the update is not there yet, have patience. 
If these zips are getting updated, then it is available... 

https://github.com/Tikipeter/repository.tikipeter/tree/master/zip
