### ISSUE TITLE
New Feature - Audio Flags on Results list.

### ISSUE THREAD

**Issue by tfouto** [Tikipeter/repository.tikipeter#159]
In Results list, if possible it could appear the flags of the audios available in each stream. That would be great for non-native speaking english.
Or at least that info, via text.

I don't know if the audio titles languages are available in the results, if they are it would be a great feature.

Thanks for your awesome addon.

**Comment by Tikipeter** [comment]
It would ruin the aesthetics of the source select screen. So no.

Umbrella addon has flags for this. It may be a better fit for you.

**Comment by tfouto** [comment]
It would be an option. Only those who wanted, would use it. Not on default.
    On Thursday, 23 February 2023 at 11:13:33 WET, Tikipeter ***@***.***> wrote:  
 
 


It would ruin the aesthetics of the source select screen. So no.

Umbrella addon has flags for this. It may be a better fit for you.

**Comment by tfouto** [comment]
Would it be possible to sort by language? To appear in first place a language, like spanish or portuguese?

Also I can't find the flags option on Umbrella.
