### ISSUE TITLE
show account info for RD and PM

### ISSUE THREAD

**Issue by sasagr** [Tikipeter/repository.tikipeter#16]
Hi Tikipeter. Just to keep track of an additional feature we discussed in the past, in case you are still interested.
To add in the root menu and account folder with all the account info (expiry, available gigs,...) for not only furk and EN but also RD and PM.
Feel free to close it if you feel it is not doable (I doubt that knowing you!) or not essential.

**Comment by Tikipeter** [comment]
I'm doing this as we speak sasagr. Read my mind again!
There will be a "Premium Services" root menu which will house the current Furk and Easynews sections as well as sections for RD and PM. RD and PM will have account info, and a menu to browse your cached torrent files for those services. RD is finished at the moment..
As you know I'm slow with things like this as I need to work them out first, but it is coming together now.
Once that's done I can make scrapers to check your RD and PM cloud for relevant files. I'll have to look to Realizer/Premiumizer and Seren (and Gaia) for inspiration for that.
Probably a week plus until it's ready...

**Comment by Tikipeter** [comment]
Implemented in coming update (v.1.5.37)

**Comment by sasagr** [comment]
Great. Thanks. It seems perfect. I think we can close it
