### ISSUE TITLE
Fast forward at end of show cancels next episodes 

### ISSUE THREAD

**Issue by IG2022** [Tikipeter/repository.tikipeter#16]
Hi, I noticed a bug with fast forwarding at the end of a episode. There are some episodes particularly those on Netflix shows that have really long credits. I usually fast forward to get to the next episode pop-up in these situations but I noticed that if I fast forward towards the end of a show it stops the episode and cancels the next episodes in the que and takes me back to episode list, I never fast forward to the complete end of the episode just to the point where I should see the next episode pop-up. This seems to happen right when the pop-up should show but instead cancels and stops the episode. I am using Arctic Horizon 2 for my skin. 

I've attached a log for you to take a look. 
https://paste.kodi.tv/mipakukoya

**Comment by Tikipeter** [comment]
For a test, turn off the still watching check and see if that solves the issue.

Otherwise, tell me your settings (an image of them might be easier) for all the next episode settings and I'll try and replicate this.

**Comment by IG2022** [comment]
> For a test, turn off the still watching check and see if that solves the issue.
> 
> Otherwise, tell me your settings (an image of them might be easier) for all the next episode settings and I'll try and replicate this.

Turning off still watching seems to solve the issue I tested with a couple of episodes and the didn't have that issue. I'll keep still watching off for now.

**Comment by Tikipeter** [comment]
Thanks for reporting back. That gives me the place to look.

I should have it sorted out next update and you can turn still watching back on.

I'll report back here.

**Comment by Tikipeter** [comment]
Should be fixed for next update, but I couldn't replicate the issue so I'm not 100% that it's fixed.

**Comment by IG2022** [comment]
> Should be fixed for next update, but I couldn't replicate the issue so I'm not 100% that it's fixed.

No worries. I'll test it out in the next update and let you know if it's solved.

**Comment by IG2022** [comment]
@Tikipeter I just did some testing and I'm not experiencing the same issue with the new update. Thanks for sorting this out for me.

**Comment by Tikipeter** [comment]
Thanks for reporting back. :)
