### ISSUE TITLE
Internal scraper not working after update from 1.5.103a

### ISSUE THREAD

**Issue by wilsonalmeida** [Tikipeter/repository.tikipeter#161]
Hi,

After upgrading from `1.5.103a`, my internal scraper doesn't work ...I've some episodes on a `smb` server and added the path under `Folder 1`.  It worked fine before the upgrade.. I've one box where I have disabled auto-update and kept the version at `1.5.103a` and the internal scraper works.  But on my `desktop` where I've upgraded, internal scraper does not show the episodes.  I'm not sure what's changed from this version and if it's fen library or some of it's dependencies which are causing this issue.  Btw, on the `1.5.103a` version, the external links don't work now..only the internal scraper links show up.

**Comment by Tikipeter** [comment]
Hi wilsonalmeida.
I will get to this issue after the current problems with the most recent update are resolved.

**Comment by wilsonalmeida** [comment]
Thank you... Thanks for making such awesome plugins.

Cheers

**Comment by Tikipeter** [comment]
@wilsonalmeida 

Please change Settings->Results->Display->Highlight Results Based On... to "SCRAPER" and see if that fixes any problems.

**Comment by wilsonalmeida** [comment]
Thanks !! That worked like a charm.  Cheers :+1:

**Comment by Tikipeter** [comment]
@wilsonalmeida
Fix will be in the next update so you can set that settings again.

**Comment by wilsonalmeida** [comment]
Oh cool.. thanks :+1:
