### ISSUE TITLE
Not showing torrents anymore. 

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#162]
Latest version (1.6.05), not showing torrent results anymore, only debrid hosters.
I checked the log, but I do not see any errors popping up for Fen. 

After the update I did clean all options first (clean all cache option), did authorize Fen again (re) Authorize Realdebrid option in Fen, same result. 
Any idea?

Normally I always post a log file, but the log is not showing any errors related to Fen....

**Comment by Tinuz97** [comment]
Video 

https://tinuz97.stackstorage.com/s/REoWuPKB7gKwIlk

**Comment by Tinuz97** [comment]
Wiped the Fen folder in userdata (The plugin.video.fen folder), wiped Metadata folder.
Did configure Fen again (because all setrings gone that I wanted with wiping both folders), did authorize Realdebrid again for Fen, keep getting this issue on my phone (oneplus 5, Android 9).

A friend of my is not having this issue (raspberry 4 with I think LibreElec) so gonna test on my computer today, let's see if the issue is also on that system.

**Comment by Tinuz97** [comment]
Other buddie has the same issue, nvidia shield tv, I am beginning to think this issue is in combination with Android devices, so I am realy gonna test it on windows 10.

**Comment by Tinuz97** [comment]
As expected.
On my windows 10 computer, I see the cached torrent links, I realy starting to think it is a Android device operating system issue (in combination with Fen), because the Oath works fine, Tempest on the same Android devices. 

On my phone, shield ( both android), no torrent links, only debrid hosters.

**Comment by jaimsitecom** [comment]
Same here. Am using chinese android box MIBOX S. Getting no results after scraping. Even after reauthorizing my debrid accounts. Cleared metadata cache didnt help. 

Had to go back to 1.6.04. Everything back to smooth. :)

**Comment by Tinuz97** [comment]
Thx for verification

**Comment by jaysamuel1976** [comment]
Same here

**Comment by Tikipeter** [comment]
Please refer to the pinned notice for info.
