### ISSUE TITLE
Having problems

### ISSUE THREAD

**Issue by ANHBOB** [Tikipeter/repository.tikipeter#163]
I updated Fen last night, cleared all cache then watched a TV show. It acted like it was working correct. This morning there was an updated for Open Scrapers so I installed that. Went to watch a TV show today and it just kept skipping down the list of links without starting the show. I re-scraped again and it did it again. I'm using the 4K firestick, Kodi 18.6, I have real debrid and Trakt accounts set up within Fen.

Another wierd problem I saw was under my Trakt collection...TV shows...SEAL Team...it shows I've watched a show that hasn't aired yet..the show for March 18.  Before the update that wasn't there.

**Comment by Tinuz97** [comment]
Skipping issues is a Realdebrid issue, they have or had problems with cached torrents (every addon, including tvzion, a apk)

2nd issue, can't answer that.

**Comment by jaimsitecom** [comment]
Had to downgrade back to 1.6.04. Scraping got slow and resulted mostly to ‘no source’ popup. Even after re-authorizing both my realdebrid and alldebrid, most movies resulted to 0 results. Weird. Good thing i had the old version in zip. Now this is scraping fast and getting lots of results.

**Comment by Tikipeter** [comment]
Please refer to the pinned notice for info.

**Comment by ANHBOB** [comment]
Any idea why I'm seeing this....Another wierd problem I saw was under my Trakt collection...TV shows...SEAL Team...it shows I've watched a show that hasn't aired yet..the show for March 18. Before the update that wasn't there.

I've tried to remove from watched and unable to do that.
