### ISSUE TITLE
Proposal: Add Trakt Watchlist View for Seasons

### ISSUE THREAD

**Issue by francis-robert** [Tikipeter/repository.tikipeter#163]
### Background

FEN currently supports both Movies and TV Show watchlists from Trakt. However, there isn't a watchlist view for Seasons, which can be a useful feature for users who want to keep an eye on a particular season of a series.

### Proposal

I suggest adding a new Trakt watchlist view for Seasons in FEN.
The watchlist URL is available at `https://trakt.tv/users/{username}/watchlist?display=season&sort=rank,asc`.
In other words, it uses the same [/watchlist](https://trakt.docs.apiary.io/#reference/users/watchlist) endpoint as TV Shows and Movies. The only difference is the `mediatype` specified as `seasons` and the response payload.

My understanding is that the bulk of the API code would live in `/resources/lib/apis/trakt_api.py` and possibly some of the UI code `/lib/indexers`.

### Some Benefits

- Adding a Seasons watchlist could enhance the user experience for FEN users who want to keep track of their favorite seasons
- This feature doesn't seem to be available in any other add-on making FEN more attractive to prospective users.
- This feature could be also useful for users who have already seen a series up to a certain point and want to catch up on new seasons.
- Likely other uses I haven't thought of.

### Out of Scope

- An `episodes` watchlist and mediatype is also available on Trakt, but it is not within the scope of this proposal.
- Adding and removing to/from the seasons watchlist. I believe this adds unnecessary complexity to the initial proposal

**Comment by xyzfre** [comment]
I like this idea I'm one of those users that deletes everything on Trakt that I've already watched to make things run quicker in the background but sometimes a show comes out with a new season a year or so later, so with this feature I would add just the new season to my watchlist instead of Re-adding the whole show ,, hope this makes sense

**Comment by Tikipeter** [comment]
Since I have zero, and I mean zero, interest in attracting new users, this would all come down to whether it's worth the effort.

If you've watched all of a show and you add the next unreleased season to your watchlist, what happens when the first episode of that season airs? Are you notified in some way? Because Fen wouldn't "notify" you. Would the Trakt website? And if so, why have the list available in Fen?

If it's just to have a list at hand for easy manual checking, why not just go into In Progress TV Shows and see if a show you're watching has moved in there from the Watched menu, which would happen when a new season begins airing.

**Comment by francis-robert** [comment]
It's not so much a matter of notification but a matter of keeping track of particular seasons. Users might have favorite seasons or ones they want to rewatch at some point, etc. It's not necessarily about unreleased seasons. There are many use cases outside of my own.

I've put together some additional info in case you're interested in picking up the feature:

Here's the response body for my seasons watchlist

```json
[
  {
    "rank": 1,
    "id": 797760672,
    "listed_at": "2023-02-23T05:17:17.000Z",
    "notes": null,
    "type": "season",
    "season": {
      "number": 4,
      "ids": {
        "trakt": 317254,
        "tvdb": null,
        "tmdb": 329524,
        "tvrage": null
      }
    },
    "show": {
      "title": "Tournament of Champions",
      "year": 2020,
      "ids": {
        "trakt": 157664,
        "slug": "tournament-of-champions",
        "tvdb": 376197,
        "imdb": "tt11173298",
        "tmdb": 100095,
        "tvrage": null
      }
    }
  },
  {
    "rank": 2,
    "id": 797760692,
    "listed_at": "2023-02-23T05:17:47.000Z",
    "notes": null,
    "type": "season",
    "season": {
      "number": 5,
      "ids": {
        "trakt": 307276,
        "tvdb": 2031336,
        "tmdb": 317592,
        "tvrage": null
      }
    },
    "show": {
      "title": "The Circle",
      "year": 2020,
      "ids": {
        "trakt": 151342,
        "slug": "the-circle-2020",
        "tvdb": 368012,
        "imdb": "tt9581768",
        "tmdb": 97083,
        "tvrage": null
      }
    }
  }
]
```

It seems to return both the TV Show as well as the specific details to the season that is on the watchlist. In this case, I only have 2 seasons for 2 separate shows in my seasons watchlist and neither of the "parent" shows are in another watchlist on my trakt.

Here's a screenshot of how that looks: ![image](https://user-images.githubusercontent.com/87673558/221206487-2f72f547-677f-4562-8b50-8adcf9ebe9f0.png)

Clicking on either of those seasons brings you to the specific season page. For example, in the case of `Tournament of Champions` we can see that the hyperlink is for the specific season:  ![image](https://user-images.githubusercontent.com/87673558/221206797-525f1bd2-5b9e-47f2-bbfb-46fd70ef2385.png)

**Comment by Tikipeter** [comment]
>Users might have favorite seasons or ones they want to rewatch at some point, etc

Is the season removed from the Watchlist if an episode from the season has been watched? Like the behavior when a tvshow is in the watchlist?

>There are many use cases outside of my own.

This is what I'm referring to. To me, this might have some utility when using it through the Trakt website, I just don't see what utility it would have being viewed through Kodi. Why not add those 2 tvshows to the watchlist?

It is not trivial to add this. I cannot rely on code already written in Fen like you think I can, as that code assumes all the seasons in a season container are for the same tvshow. So it's not just a matter of adding a new endpoint from Trakt and away we go.

From what I've read, so far there is ONE usage for this...... I want to add the season to the watchlist and not the tvshow. I don't even know why that is beneficial over adding the tvshow.

**Comment by Tikipeter** [comment]
I'm going to close this.

I appreciate the request, but it's not something I have interest in implementing in Fen.
