### ISSUE TITLE
NOTICE: Issues with latest update.

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/repository.tikipeter#164]
I will be away from home for a few more hours. Please use another addon in the meantime if you are having issues.

**Comment by xyzfre** [comment]
No issues here since yesterday‘s update I actually feel Fen is working a lot faster specially next up widgets on home screen load a lot faster now,,,I followed the instructions after updating clearing the Meta cache etc and everything went smooth thank you for this amazing addon

**Comment by Tikipeter** [comment]
Thanks xyzfre, nice to hear.

Everyone with troubles, I'm about to push an update (v.1.6.05a) that will add a pause between a couple of things Fen is doing new, regarding allocating a couple of settings in ResolveURL, and also a fix for free links not resolving. This is done without testing because i have to leave the house again for probably an hour after just getting home.

I know the fix for free links resolving will work, but the possible fix for other issues is a stab in the dark that i can do quickly now. Most likely, I will need DEBUG LOGS for this issue, as it is probably not a mistake in the code, but a situation where Kodi is simply not happy with the code it's being asked to perform, quite possibly on android.

Anyway, if testing this quick update, clear the external providers cache before testing. No other cache needs to be cleared.

**Comment by Tinuz97** [comment]
Debug logs, like kodi debug logs? (so enable kodi debug log?)
unfortunately A did not solve the torrent links for me, also no need to hurry, just wanted to report the issue (Android only for me). 

So if you can guide me for the best way for logging, I will post a log (tryed the standard kodi log yesterday, could not find any Fen error, so I need something that logs everything).

**Comment by Tinuz97** [comment]
Found it.
Wiped the log first with total commander, started kodi, enabled kodi's debug logging, and did run Fen.

Can I post the full log here, or does it contain personal info, like premiumize or Realdebrid or Trakt api keys/passwords etc?

Normally I check this on my computer, but with the phone that I tested it on (oneplus 5, Android 9), it is hard to read a log, lol.

**Comment by Tinuz97** [comment]
I hope this is the correct one (did the debug log described as above), if not correct, guide me. 

But in a hour I am going to bed, so then I will respond later. 

https://pastebin.com/F8qGwYk3

**Comment by Tikipeter** [comment]
I've had a lot of trouble getting some supplies for the house in case of quarantining, so I was away a lot longer than I expected. Unfortunately these Fen issues are going to have to wait until tomorrow my time. Sorry everyone, I was hoping to have some time after work but things were a bit chaotic with regards to buying some regular shopping items. Half a tank of petrol and nearly 4 hours later I'll have to get some sleep. :(

**Comment by Tikipeter** [comment]
Method for a potentially useful debug log:

1. Go to Kodi settings and turn on debugging.
2. Replicate the issue (searching for sources).
3. Paste log on 'pastebin.com' and post a link here for me to look through.
NOTE: It is always better to restart Kodi after enabling debugging, and then replicating the issue. But this is not essential.

**Comment by jaimsitecom** [comment]
Thanks Tikipeter!  Mine doesnt give any error/s or something. But it just wont scrape anything even if my debrid accounts were re-authorized. Tried the latest one 1.6.05a  but still the same ‘no results’ when scraping.  Good thing is i can always revert to 1.6.04. For now if it aint broke am not fixing it! Hehe. Thanks again for this amazing addon!

**Comment by Tinuz97** [comment]
Did a clean install (renamed kodi folder to backup), so clean install Fen, and nothing else to keep the log clean from other addons etc.

Did enable standard debug log (first switch on top, no idea if I need to enable anything extra, I will post a screenshot after this message of the enabled debug log settings). 

Closed kodi with exit (not a force close). 

Started kodi, opening Fen, did scrape 3 movies, closing kodi again with exit. 

Opened the log, copy paste to paste bin.

Log:

https://pastebin.com/sdefMXam

**Comment by Tinuz97** [comment]
My debug log settings 
![Screenshot_20200317-135352](https://user-images.githubusercontent.com/47715606/76857978-cd5b2480-6856-11ea-93a3-0fa78f172fe8.jpg)

**Comment by Tinuz97** [comment]
I have the idea that nothing is logged for Fen or any other issues in this log, but I am not a pro on reading the debug log.

So waiting for a next step, ot setting.

**Comment by jaimsitecom** [comment]
> My debug log settings
> ![Screenshot_20200317-135352](https://user-images.githubusercontent.com/47715606/76857978-cd5b2480-6856-11ea-93a3-0fa78f172fe8.jpg)

Mine’s exactly the same.

**Comment by Tinuz97** [comment]
![Screenshot_20200317-140505](https://user-images.githubusercontent.com/47715606/76858731-5757bd00-6858-11ea-836a-14cf0be173f6.jpg)
But still no torrents, and only 32 debrid hosters (only debrid enabled in the settings, and cached only, Fen is authorized with Realdebrid)

Did the clean install not only for a clean log, but also to make sure that that is has no conflicts with other Addons, or dependencies, but issue stays unfortunately on Android,only Android, LibreElec, CoreElec, windows 10 tested, all fine.

**Comment by Tikipeter** [comment]
_(NOTE: There are a fair few steps below needed to help me out. There is one quicker way to test, and that is to authorize one debrid account **IN RESOLVEURL**, then clear Fen's External Scrapers Cache and test a Movie for results. Report back if you received torrent and debrid results when a debrid account was active in ResolveURL.)_


OK, for anyone not receiving torrent results and limited debrid results:

Firstly, check some settings (these only need to be set this way for the purpose of finding the problem, they won't need to be kept this way):
* External Scrapers->General->Stop Search Early.. - set to OFF
* External Scrapers->General->Remove Duplicate Links - set to OFF
* External Scrapers->General->Remove Failing Scrapers - set to OFF
* External Scrapers->General->Pre-emptive Termination - set to OFF
* Results->Torrent Sorting & Filtering->Check Debrid Services for Cached Torrents - set to OFF
* Also turn OFF any other scrapers (Internal).

* Go to Tools->External Scrapers Manager->Reset Failing External Scraper Stats and confirm a reset of the stats.

* Stay in External Scrapers Manager and select ALL SCRAPERS: Enable all scrapers. Then make sure all scrapers have been enabled by selecting ALL SCRAPERS Enable/Disable Specific Scrapers and, without changing anything, see that all the scrapers are already selected.

* Then go to Tools->Clear Databases and Clean Settings Files and clear the External Scrapers Cache ONLY. There is no need to clear any other caches.

* Go to Kodi's settings and turn on debug logging.

* Restart your device.

* Upon restart, go directly into Fen and select a movie for it to scrape for results.

* Upon completion of the scrape, if it unsuccessful in display torrent and/or debrid results, upload the log here so I can look at it.

Whilst there may not be anything in the log specifically logged by Fen, it may give me an indication of why Kodi doesn't like what I'm asking it to do.

**Comment by Tinuz97** [comment]
Going to set the adviced settings, reporting back asap (I must say that the settings that I use did work fine in previous version, but I go try the settings, be right back).

**Comment by Tikipeter** [comment]
Sorry @Tinuz97 , I forgot to let you know that 2 logs you have posted were only 1.5 seconds and 2 seconds worth of startup info. Something went wrong.

**Comment by Tinuz97** [comment]
> Sorry @Tinuz97 , I forgot to let you know that 2 logs you have posted were only 1.5 seconds and 2 seconds worth of startup info. Something went wrong.

Is it a idea that I also do a screenrecord, so you can see what I am doing etc etc?

**Comment by Tikipeter** [comment]
No, that's not necessary.
Actually, a screen record including the actual scraping might be handy if you can.

**Comment by Tikipeter** [comment]
I'm going to try and find my old Android device to see if I can replicate this problem in the meantime...

**Comment by Tinuz97** [comment]
I am after the settings now, going to set them exactly like you did write, after that I do a screenrecord, and post video and log afterwards, do take some time, because it is switching between screens on my phone 🤣

**Comment by Tikipeter** [comment]
You're a legend Tinuz. I really appreciate it. I've found my android device and will be testing now. Hopefully it doesn't work so I can find the problem!

**Comment by Tinuz97** [comment]
I have set all settings, last step reboot device, so realy restart my phone, after that launch kodi?
Or close kodi, start it OK also?

**Comment by Tikipeter** [comment]
Just close Kodi and restart it.

**Comment by Tinuz97** [comment]
Funny, after these settings, my log is MUCH  bigger.

Here you go. 
After this message I upload the video (still no torrents) 


https://pastebin.com/XN5vfv8U

**Comment by Tinuz97** [comment]
Video

https://tinuz97.stackstorage.com/s/hmDxIkQJq6IaL4P

**Comment by Tikipeter** [comment]
Well, the good news from that video is that it IS scraping torrent providers and Debrid providers. That is really good news.

* Make sure you turned OFF "Results->Torrent Sorting & Filtering->Check Debrid Services for Cached Torrents". The video shows it still checking for cached torrents.
* Up you scraper timeout to 60 seconds in Settings->Results->Display.

Run another test and see if the torrents appear now...

**Comment by Tinuz97** [comment]
Weird, because I am almost sure I checked every setrings twice.
But I go check again to be sure. Be right back.

**Comment by Tinuz97** [comment]
Aha, that is a issue also.
If I turn that one off, click OK  to save the new setting, go back to check it, it is enabled again. 

Could that be the issue maybey relating to my 'android' issue?

**Comment by Tinuz97** [comment]
Look, realy funny, turns on automatically again.

https://tinuz97.stackstorage.com/s/6A8HSChAImqqWAn

**Comment by Tikipeter** [comment]
That's definitely a problem!
Try entering the settings through fen and see if it stays set properly.

**Comment by Tinuz97** [comment]
> That's definitely a problem!
> Try entering the settings through fen and see if it stays set properly.

That is funny also, now the settings do stick (true Fen, not like I did in the video), something is going on in that section I guess?

Going to scrape again, set to 60 seconds now, and cache check off.

**Comment by Tinuz97** [comment]
If I record on my phone, the scraping does take very long, because that needs cpu power also.
I can post the video, but tryed also without recording (with 60 seconds, cache check realy off), still no torrent results unfortunately (it did reach all scrapers almost after 60 seconds, just 1-2 did remain before the 60 seconds cut did come in)

**Comment by Tikipeter** [comment]
In that first video, the number of results you were getting, the number of scrapers that were initially loaded, and the fact that a cache check was performed through RD shows me that the torrent and debrid scrapers were used. For some reason the results weren't shown. I've looked as best I could, and the debug log doesn't really give me an answer.

You can turn debugging off and restore all the settings you had to change Tinuz. I really appreciate you helping me out with this.

I'm going to concentrate on a different part of the code now that I know it is loading the torrent/debrid scrapers, but not showing the results.

Whilst it seems bad at the moment, it is actually good news so far. Fixing the issue I thought it was might have not been possible with my knowledge of Kodi, but hopefully the real issue will be solvable.

I'll write back here with any new info, and do the '@' thing so that you know I've posted. It could be a while though...

**Comment by Tinuz97** [comment]
No problem, and no need to hurry.
On the shield I did roll back to previous version (working 100%),luckily I was in the Addons download folder from kodi, so reverted for now.

**Comment by Tikipeter** [comment]
@Tinuz97  and others, here is a test zip to try out. If you don't see torrent/debrid results with this test, re-auth your debrid accounts in Fen (I know many have already done this, but it may need to be done one more time).

http://www.filedropper.com/pluginvideofen-1605b

I've also put this in the repository address files (Tikipeter.github.io) that most of you would have added to Kodi's File Manager when installing the Tikipeter repo. You can install it from zip from that location as well.

Let me know of, hopefully, good news....

**Comment by Tinuz97** [comment]
@Tikipeter Unfortunately the same (for me).
Did authorize Realdebrid again, and did clean external scrapers. 

Before this update, could you replicate the issue in the Android box that you did find?

**Comment by Tikipeter** [comment]
Not exactly. I wasn't getting any results at all. They just never showed up. After the changes I made, they now show up (torrents, debrid, regular).

I'll have to make another test with logging to see more info.

**Comment by Tikipeter** [comment]
Do you prefer a link here or in the repository files?

**Comment by Tinuz97** [comment]
Link here, install from zip for the win 😄

**Comment by Tikipeter** [comment]
Thanks Tinuz.

http://www.filedropper.com/pluginvideofen-1605c

**Comment by Tinuz97** [comment]
Do i also need to auth again? (did that in the version you did say auth again), still no torrents :/ (cleaned extarnal scrapers also)

**Comment by Tikipeter** [comment]
No, no need to auth again.

**Comment by Tinuz97** [comment]
is that loging readable true normal kodi log, or the debug log?

**Comment by Tinuz97** [comment]
debug log to big for paste bin..... 512kb  max

**Comment by Tinuz97** [comment]
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/4345741/kodi.log)

**Comment by Tikipeter** [comment]
Thanks Tinuz. Appreciated. I'll only need normal logs from now on (not full debug).

**Comment by Tinuz97** [comment]
Normal log: 
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/4345770/kodi.log)

**Comment by SJ50** [comment]
@Tikipeter I am having same issue, while scraping it shows found 20 torrent and than no result on Nvidia Shield, is it possible to push previous version as update while this issue is being resolved?

**Comment by Tikipeter** [comment]
@SJ50 "No Result" as in no results shown at all, or no torrent results?

**Comment by SJ50** [comment]
I have very specific settings where only 1080P video comes up as a result, window while scraping shows 20, 1080P torrents than for results window it says no result. 
PS - scraping was really fast though

**Comment by Tikipeter** [comment]
Your issue MIGHT be different.
I'll push an 'update' with the code from 1.6.04. That will probably mean this won't get solved, though, as nobody will be using/testing the newer version.

**Comment by SJ50** [comment]
I was searching Old movie, so I guess only torrents were available, it identified different quality but when it comes to show results it failed. So I guess results are not stored or accessible properly.
I can help you with identifying issue with current version but I can do it on weekends only.

**Comment by Tinuz97** [comment]
These are from the normal log,posted above @Tikipeter ,i am interested in what these errors are?

2020-03-17 21:47:46.850 T:17722   ERROR: GetDirectory - Error getting plugin://plugin.video.fen/?content_type=video
2020-03-17 21:47:46.869 T:15161   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.fen/?content_type=video) failed
2020-03-17 21:47:46.872 T:17739   ERROR: Unable to find plugin
2020-03-17 21:47:46.872 T:17739   ERROR: GetDirectory - Error getting plugin://
2020-03-17 21:47:46.875 T:15161   ERROR: CGUIMediaWindow::GetDirectory(plugin://) failed

**Comment by Tikipeter** [comment]
I'm looking in that area now, along with one other area.

So far, I know that Fen is getting plenty of results (including all the torrent and debrid results it should get), and that it is successfully calling RD for info on what hosters are available for resolving, and that it is then processing the list of results (e.g. adding UNCHECKED etc) then it is passing those off for the labels to be constructed.

Somewhere after that things are going wrong. So either at the point the labels are being constructed (very little code was changed here), or the next point where the items get made for Kodi to display the results (no code was changed here). So I'll post one more test file with a few changes made and some logging. Please check with this when you get the chance, and send through the log.

That will have to be it for today, though, as I'm quickly running out of time, :( :(

**Comment by Tikipeter** [comment]
Next test:
http://www.filedropper.com/pluginvideofen-1605d

Good Luck.. :) :)

**Comment by xyzfre** [comment]
I’m Using a Nvidia Shield 2019 just curious I have no issues with 1.6.05 actually with this update I feel like Fen works a lot faster should I still update or stay with this version

**Comment by Tikipeter** [comment]
Stay with the new version that is working. The latest update was just a rebadge of 1.6.04.

**Comment by ANHBOB** [comment]
@Tinuz97  I have 1 question for you. In that video you posted it shows you found 587  total links for the movie...86 4K,  265 1080p, etc.. If  I search the same movie I only get around 20 4K, around 75 1080p links.  I'm using the 4K Firestick, I also have Real Debrid and my internet speed is 35Mbps.
All of my links do show RD CACHED except 2-3 1080's.

**Comment by Tinuz97** [comment]
@Tikipeter  new 'normal' log for version D 

https://pastebin.com/NEYajh2H

**Comment by Tinuz97** [comment]
> @Tinuz97 I have 1 question for you. In that video you posted it shows you found 587 total links for the movie...86 4K, 265 1080p, etc.. If I search the same movie I only get around 20 4K, around 75 1080p links. I'm using the 4K Firestick, I also have Real Debrid and my internet speed is 35Mbps.
> All of my links do show RD CACHED except 2-3 1080's.

My phone is realy fast (faster as my shield), it is going to every scraper in the scrape time, so not any left when it is done,maybey that i why i get more,is the device you are using fast enough to search all scrapers in the time you set, or are there many left?

**Comment by ANHBOB** [comment]
I can't tell how many are left...I had pre-emptive Termination  set to ON and stop search early turned ON....I just went through my settings and turned things off  like Tikipeter said in the earlier post...now I'm going to try scraping the movie again....I still get the same results after the changes

**Comment by ANHBOB** [comment]
@Tikipeter ...so the new update..1.6.06..is the same as 1.6.04?

**Comment by Tikipeter** [comment]
Yes, it is a revert to 1.6.04

**Comment by ANHBOB** [comment]
@Tikipeter  One thing that has been annoying me is after clearing settings and all cache..then restarting Kodi...or not restarting..it doesn't matter>My Track>collection:TV shows OR Trakt>watchlist>movies..that stupid blue wheel spins for about 5 minutes before anything shows.  That had happen before and its back again....its been back for some time now..not just the latest update.

**Comment by ANHBOB** [comment]
Just tried it now..it took about 7 minutes to show the watchlist

**Comment by dm2912** [comment]
Im still on 1.06.4 (or whatever). only issue im having is its asking me to reauthorise trakt about five minutes before the end of every single show i watch.

**Comment by SJ50** [comment]
I have automatic update on so when I turned Kodi on fen updated to 1.6.04, before searching Movies I deleted all db file files from plugin.video.fen folder. Fen showed all the torrent links. 

I updated version 1605d and I guess it retrieved from cached data and displayed all torrent result.

I deleted all db files it scrapped everything while scrapping it showed how many different quality files are available and when it came to display result than No torrent only hosters.

I updated from 1605d to 1.6.04 but no torrent result as fen is using old cached result.

Deleted all db file and searched movie again and 1.6.04 showed torrent result.

I guess torrent results are not getting written in db files properly or not accessible .

Hope this helps to narrow down the issue.

**Comment by SJ50** [comment]
1.6.04 shows only 6 results because of removal of duplicate results, but when I search using 1605d with 1.6.04 cached database result 1605d shows 249 result, it shows notification showing 194 result remove but not removed.
Is duplicate checking script broken and removing all the torrent results?

**Comment by Tikipeter** [comment]
Alright, I've had enough of this update. There were a series of fixes other than changing to Fen for debrid resolving that need to be put back, so I'm going to make a new update with those fixes included and not the changes to resolving that seem to be causing big issues on some devices.

@Tinuz97  has provided plenty of logs of his problem and there is still no answer to the problem of links displaying. Practically all the changes I made in that regard are working on his setup, and returning the correct info at the correct time. So it's now coming down to a section of the code that hasn't had any changes in quite a while. If Tinuz wants to keep the 1.6.04 version on his phone, I would love to work with him more on fixing this issue, but I understand if he doesn't.

There will be an update soon enough that will pull together the other fixes, and leave out the changes to displaying results and resolving so hopefully that will work for everyone.

**Comment by Tinuz97** [comment]
If it helps you, and you like to try some fixes, I have no problems testing, but if it bothers you (programming must be fun I guess), and you also like to search the issue, I am always willing to help, no problem.

Also I have the time for it, I am only outside if I am gonna take a walk with the dog, or in my yard. 
Corona is hitting The Netherlands more and more, we are in lockdown now, not a total lockdown (but could change, it is a option, the president mentioned that yesterday, so like you I did some extra groceries today). 

So it is upon you, if you say I like to find the issue, because I like that, but but please only if you want to do it, like it, ot want to newer changes to work. 

Don't do it otherwise, because it also must be fun for you :)

**Comment by Tikipeter** [comment]
I definitely do want to find the issue. If you could keep 1.6.04 on one of your affected devices it would be great, because I think we need to limit dependency on ResolveURL as much as possible.

I will start a new issue here for us to work in, though, as this one has too much of a generic title, and should not be needed once I push the next update.
