### ISSUE TITLE
Issue 161 

### ISSUE THREAD

**Issue by Raoulduke889** [Tikipeter/repository.tikipeter#164]
**"_There are absolutely no settings in Fen to change the display of episodes "when a season's episode list is displayed".

If you're using Estuary, the episodes' duration is in the bottom right corner of the SKIN.

If you're using Confluence, the Media Info view of the SKIN displays the duration.

As a long time user you should know this_."**

You replied this to my ticket #161 then deleted it. I think there's been a communication issue since you didn't get my request at all. Please take a look at the pictures. I'm talking about switching from those ratings, which I believe Fen pulls directly from the service it gets the metadata from, to the episodes' duration. Skins here are Estouchy and Confluence. 

![Screenshot_20230224-073605~2.png](https://user-images.githubusercontent.com/94480245/221109900-f4998888-7085-403d-a2e8-b05b3bd924dc.png)

![Screenshot_20230224-073727~2.png](https://user-images.githubusercontent.com/94480245/221109899-89a909e3-00d6-4236-9548-7e09ca7a7a65.png)

Cheers.

**Comment by Tikipeter** [comment]
My answer's the same.

I don't know why you continue to think an addon can control what a skin shows and where it shows it.

Addons supply Kodi with the info for the listitems. Skins then use that info from Kodi to populate their listitems.

Fen is not telling any skin where to place any info. Be it duration, rating, whatever.

Please tell me you understand now and are not going to open a third issue for this hokum.

**Comment by Raoulduke889** [comment]
> My answer's the same.
> 
> I don't know why you continue to think an addon can control what a skin shows and where it shows it.
> 
> Addons supply Kodi with the info for the listitems. Skins then use that info from Kodi to populate their listitems.
> 
> Fen is not telling any skin where to place any info. Be it duration, rating, whatever.
> 
> Please tell me you understand now and are not going to open a third issue for this hokum.

![Seren 1.png](https://user-images.githubusercontent.com/94480245/221128900-a9f313e8-d254-41fb-8929-c9e37d443296.png)

This is Seren. Same skin, no changes made to it whatsoever. Definitely not a skin issue.

**Comment by Tikipeter** [comment]
Since I took the time to explain how this works, are you going to read what I explained to you, or are you just going to continue posting pictures?

If you have the knowledge to know I'm wrong in what I wrote above, then supply a counter argument.
