### ISSUE TITLE
2 Incorrect values returned for ListItem when Next Episodes are used for widgets

### ISSUE THREAD

**Issue by meesterexx** [Tikipeter/repository.tikipeter#165]
This was a weird one, but long story short while working on a skin mod, I discovered that in Fen, ListItem.Genre and ListItem.Studio return the wrong values when the widget source is Next Episodes:
 
ListItem.Studio returns TVShowTitle
ListItem.Genre returns Studio

I duplicated this easily in Fenstruary by changing lines 186 & 187 in Includes_Home.xml for the WidgetListEpisodes to the below values:
```
 <param name="main_label">$INFO[ListItem.Genre]</param>
 <param name="sub_label">$INFO[ListItem.Studio]</param> 
```
You can see in the screenshot that Fen has the incorrect values while Umbrella returns the expected values, as well as the studio logo is missing in the footer for Fen (but shows for the episode when the Umbrella widget is focused). In the other skin I was working on, I had Next Episodes widgets for Fen, Umbrella, TMDBHelper and Quicksilver all pulling from my Trakt Progress and only fen displayed the wrong information. 

If I link a widget directly to a season's episodes (say TV Shows > Trending >pick a show > Season 1 > use for widget path) I get the correct values.  
If I go into the addon itself (not homescreen widget) and navigate to TV Shows > Next Episodes none of the Studio logos show in the footer on the bottom right of the addon view which seems to confirm the incorrect values being returned as well inside the addon.

Screenshot of Next Episodes widgets on Fenstruary home pulling from Fen & Umbrella:
![screenshot00001](https://user-images.githubusercontent.com/13154733/221301974-0e505acb-9234-4d32-b78b-07430736fbd0.png)

**Comment by Tikipeter** [comment]
Fixed for next update.

Thanks for taking the time to explain this properly. Made it very easy to spot the issue.

**Comment by Tikipeter** [comment]
If you want to get your hands dirty before then:

`Line 198` of `resources\lib\indexers\episodes.py`:

Change this:
`orig_title, rootname, trailer, genre, studio = meta_get('rootname'), string(meta_get('trailer')), meta_get('genre'), meta_get('studio'), meta_get('original_title')`

to this...
`orig_title, rootname, trailer, genre, studio = meta_get('original_title'), meta_get('rootname'), string(meta_get('trailer')), meta_get('genre'), meta_get('studio')`

**Comment by meesterexx** [comment]
Corrected episodes.py per your instructions and that fixed it. 
Much appreciated and thanks for the fast turn around!
