### ISSUE TITLE
Problems with Fen handling all debrid links.

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/repository.tikipeter#166]
@Tinuz97 

Here is the current status of this issue:
There are two main areas that changed with the 1.6.05 update regarding debrid.

In external.py:
1. Fen now asks the debrid services for which hosters they support (i.e. Rapidgator, Nitroflare etc)
2. Fen now decides whether you have any debrid services active (by looking at only which services are authed in Fen).

Both of these actions were previously handled by ResolveURL (an addon would ask ResolveURL for this info).
**BOTH OF THESE CHANGES ARE WORKING CORRECTLY ACCORDING TO THE LOGS YOU HAVE PROVIDED ME SO FAR.**

In sources.py:
1. Fen now resolves all debrid links instead of passing them to ResolveURL.
**WHILST WE HAVEN'T TESTED THIS, I WILL ASSUME IT WORKS.**

The first problem when moving away from ResolveURL was that each torrent/debrid scraper in Openscrapers uses ResolveURL to check if you have an active debrid account. If you don't have an active debrid account in ResolveURL, then the scraper would return no results without checking. To get around this (because I wanted Fen to work without active accounts in ResolveURL) I use a quirk in the checking which made it return TRUE if a Rapidgator account existed in ResolveURL. So I change that setting (Rapidgator) to active in ResolveURL before the scrape, meaning torrent/debrid scrapers would activate, and then turn the Rapidgator account off again at the end of the scrape.
**Obviously when you weren't getting torrent/debrid results, I believed it was because of a problem with this section of code. Turns out that is not the case.**

The next section I looked at was as to whether or not the new debrid functions were working. Were you getting info from RD about which hosters it currently supported.
**This also showed to be working correctly.**

Next step was to see if some extra threading I had enabled in the external.py file had caused your setup to stop working (this is the issue my old MiBox had. When I removed the threading, it began to give results).
**Unfortunately, this also did not solve your issue.**

Then I uploaded a new file which had logging to show that the correct labels were made and then that the results of the scrape were sent correctly to sources.py to be displayed in Kodi.
**Once again all of those checks came back positive.**

**So, at the moment we can say that your faulty setup DOES scrape torrent/debrid results, DOES process those results correctly and DOES send those results back to the code that will display them in Kodi. Really, there is only one step left, and that is the actual displaying of the results. No code has changed there in a while, but that is the area it seems to be failing.**

There will be a test file for you to try when you get time to come shortly.......

**Comment by Tinuz97** [comment]
My English is not that great, maybey I understand it wrong, but your faulty setup sounds so weird 😅
Or maybey it is not written like that, but that is why I started with a clean kodi ( nothing installed, just a new, clean install of Fen), to be sure that there is nothing faulty, or give issues (like maybey other dependencies, addons). 

Before reporting, I did ask my friends, that use kodi also with a nvidia shield, or other Android devices to take a look also (reporting same issue that I have/had). 

After that I created a ticket here, because I noticed realy fast that is had to be something in combination with Android (tryed same, different setrings on other operating systems, I could not replicate the bug). 

Replicate on Android is very easy (I have 3 android devices, Asus tablet, old one,oneplus 5 phone, nvidia shield pro). 

I have time to test today, watching live TV from the government at the moment, with some important information, so I can a little later today.

**Comment by Tikipeter** [comment]
Ha! Sorry about the 'faulty setup'. It sounds weird to a native English speaker also! I meant your setup with the faulty Fen install.

**Comment by Tikipeter** [comment]
Here is a test file.

Please clear all data first. Please post a log (normal, not debug) after scraping one movie.

Just this first time, could you also restart the device you will be testing on (the entire device, not just Kodi) before testing. Thanks Tinuz.

http://s000.tinyupload.com/index.php?file_id=00345477255127081112

**Comment by Tinuz97** [comment]
Going to test in a minute :)

**Comment by Tinuz97** [comment]
Cleaned all data options (clean all option), rebooted device. 

Normal log https://pastebin.com/BdEnLujp

**Comment by Tikipeter** [comment]
Couple of things you could test before the next test file.
* Settings->Results->Display->Show Filename When Available - Set to OFF
* Settings->Results->Display->Results Display - Set to DIALOG.

No need to clear external providers cache before testing these 2 settings.

I'll have a new test file shortly...

**Comment by Tikipeter** [comment]
New test (for log file):
http://s000.tinyupload.com/index.php?file_id=82894927571752174043
Thanks Tinuz.

**Comment by Tinuz97** [comment]
![Screenshot_20200319-085452](https://user-images.githubusercontent.com/47715606/77044554-ee8b5480-69bf-11ea-9498-b2e6f69e275e.jpg)
New settings screenshot (to verify) new log https://pastebin.com/AapwUjwc

**Comment by Tikipeter** [comment]
OK. That last one gave some info.
In good news, you don't need to clear the External Providers cache anymore when testing.
Something's going on with the filtering of results. Just before end of the log you can see:
` "###results raw (LENGTH)###: 917"`
and then straight after:
`###results after FILTER (LENGTH)###: 85`
So the results went from 917 to 85.
I'll send a test file to confirm this by leaving out the filter.

**Comment by Tikipeter** [comment]
Turn OFF filter torrent size and I bet you'll see all the results.....

**Comment by Tinuz97** [comment]
Now I see them indeed, unchecked torrents.
So now I am curious why it does work on 1.6.04 (torrent size enabled works fine in that one) 
![Screenshot_20200319-161952](https://user-images.githubusercontent.com/47715606/77083341-a12dd800-69fd-11ea-8f36-ff3146f3af6a.jpg)

**Comment by Tikipeter** [comment]
> So now I am curious why it does work on 1.6.04 (torrent size enabled works fine in that one)

An update to Openscrapers meant it was now returning sizes instead of Fen having to fetch it from the extra info of the source.

The returned size by Openscrapers was size in GB, whereas the size Fen was grabbing before the OScrapers update was the size in MB. This meant every torrent was being filtered out. I didn't notice the change because I don't use size filtering.

One more test file to confirm coming up, then I think everything should be OK. Turn all your settings back to how you like them before you test (torrent cache check ON, go back to Directory for displaying results etc), just to be sure everything else is working for you.

**Comment by Tinuz97** [comment]
Ok, test would take a little time, going to take a walk with the dog for like a half hour.
After that eating.

**Comment by Tikipeter** [comment]
No hurry Tinuz, your help has been invaluable to me through this problem.

**Comment by Tinuz97** [comment]
Well, I am just glad that I could give some help back for this great addon :)

**Comment by Tikipeter** [comment]
There's very few willing to do that. And I understand why. It is not easy to give valuable time to testing, and many only have one device that the whole family relies upon for viewing. On some devices a log is hard to extract from the device etc. Even saying 'I need a log file' will turn many off.

I should have caught that bug, but it's hard (impossible?) to test everything before releasing an update. I tested that update for 3 days before releasing, but never saw this problem. I was concentrating on testing the changes I made to torrent and debrid handling away from ResolveURL.

Anyway, here's the final test. Make sure your torrent size filter is turned back ON, along with other settings you had to change for these tests.
You should see everything back to normal with this test, with all torrents showing and all debrid showing. TinyUpload is having troubles again, I'll have to go with File Dropper:

http://www.filedropper.com/pluginvideofen-1604-test5

**Comment by Tinuz97** [comment]
All settings back, the way I like it.
So size filter on, debrid only, stop search early, timer on 30 seconds instead of 60 (enough now, because scraping is also back to normal, so faster, no idea if placebo). 
![Screenshot_20200319-170748](https://user-images.githubusercontent.com/47715606/77088306-8dd23b00-6a04-11ea-89ea-1388f2520f18.jpg)

**Comment by Tinuz97** [comment]
Need a log of this?
Maybey a idea to check?
No idea if you can see my settings that I mentioned above :)

**Comment by Tinuz97** [comment]
Here is a log, all working now I guess, but a log so you can double check

https://pastebin.com/g6h62gnv

**Comment by Tikipeter** [comment]
If it looks good to you then it looks good to me!

Turns out it was 2 lines of code, and not the disaster I thought it was going to be.

Once again, I can't thank you enough for your help!

Great job!!

**Comment by Tinuz97** [comment]
No, thank you, glad I could help 😄

**Comment by Tinuz97** [comment]
Renamed my back up folder again on the phone, so using my personal build again, and all settings/addons back, working great again (1.6.08).

Woohoo! 🥳
![Screenshot_20200319-183252](https://user-images.githubusercontent.com/47715606/77097047-79943b00-6a10-11ea-8228-5f1d52100460.jpg)
