### ISSUE TITLE
Error on loading watchlist (only tv Shows)

### ISSUE THREAD

**Issue by JacopoV** [Tikipeter/repository.tikipeter#166]
Hi @Tikipeter 

Since the last version (with some rework on watchlists) i started getting an error while loading the watchlist for tv shows only.

https://paste.kodi.tv/egajuhorun

Keep in mind the error shows up only with "include unaired media in Trakt Watchlists"  DISABLED .
If i enable it, all works.

I hope it can help narrowing down the issue.
Thanks 🙏

**Comment by KalAvroniev** [comment]
Also, the fix that was applied to the watchlist in issue, [Trakt Watchlists not loading anything #154](https://github.com/Tikipeter/repository.tikipeter/issues/154), only affected the Tv Shows one the Movies remained broken (not loading)

**Comment by JacopoV** [comment]
Thanks a lot as always 😊
