### ISSUE TITLE
request 

### ISSUE THREAD

**Issue by cabban** [Tikipeter/repository.tikipeter#169]
this is a link to the video source on a site 
with sd 720 and hd maybe this can be added to fen, cause it works in to find the source in a log :) 
https://s8.jawcloud.co/hls/baxplp33mvts7n2gmkc6oxhxjbbi7nq3kgdo33363wue6mjctzqw45sd75yq/index-v1-a1.m3u8

**Comment by Tikipeter** [comment]
That webpage won't open for me cabban, it says 403 Forbidden.

**Comment by cabban** [comment]
Ok for me it's a m3u8 downloads and starts play in vlc cheers

Den mån 23 mars 2020 16:07Tikipeter <notifications@github.com> skrev:
