### ISSUE TITLE
uncached furk.net torrents errors?

### ISSUE THREAD

**Issue by vinkop** [Tikipeter/repository.tikipeter#17]
hello, i try to add some uncached files from furk.net but everytime i got error " fail, error adding torrent ".....can you check what could be a problem?

**Comment by Tikipeter** [comment]
From which menu are you trying to add the Uncached Torrent?

**Comment by vinkop** [comment]
i try from tv shows or movies menu.....

**Comment by Tikipeter** [comment]
Can confirm.
Fixed in coming update (v.1.5.37).
Thank you @vinkop

**Comment by vinkop** [comment]
it working now....can confirm...
