### ISSUE TITLE
Clear Art and Disc Art not showing anymore. 

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#170]
Clear Art and Disc Art not showing anymore,did work a while ago, no idea if it has something to do with latest updates, or the website it pulls it from, can you verify / test this @Tikipeter?

**Comment by Tinuz97** [comment]
![Screenshot_20200322-195521__01](https://user-images.githubusercontent.com/47715606/77257876-4d2e2800-6c77-11ea-8566-6d342a78a3e8.jpg)
Normally I get art in these sections.

**Comment by Tikipeter** [comment]
Getting both. I'd say a problem with fanart.tv.
It took a while for the discart to show.
![screenshot000](https://user-images.githubusercontent.com/28930002/77262443-f01f8a00-6ce9-11ea-8372-abb382ed79f8.png)

**Comment by Tinuz97** [comment]
Loading here now also, probably they had issues 4 hours ago, anyways, thx for verification.
