### ISSUE TITLE
trakt_lists.py causing "ListItem.getUniqueID() is deprecated" errors in kodi.log

### ISSUE THREAD

**Issue by meesterexx** [Tikipeter/repository.tikipeter#171]
I noticed the following in my kodi.log:

```
2023-02-27 13:28:36.327 T:15824 warning <general>: ListItem.getUniqueID() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.getUniqueID().
2023-02-27 13:28:36.851 T:16048    info <general>: Skipped 89999 duplicate messages
```

A recursive search of the addon directories for my skin, Fen and Otaku (the only addons involved with my homescreen & widgets) showed the only occurrence of the phrase "getUniqueID" in any of the three addons is in Fen's trakt_lists.py line 158 (in the build_trakt_list code).

So, I disabled the movie widget that was pulling from a trakt liked list and the error went away in the logs. Then I went directly into Fen's My Lists > Trakt Lists > Liked Lists and from there, each liked list I went into caused a recurrence of the errors in kodi.log.

I also tested this in my Arctic Horizon 2 and Fenstruary builds and was able to reproduce the error in the log when going into a liked list in Fen.

I don't know python, but I noticed in the get_trakt_trending_popular_lists above build_trakt_list there are provisions for kodi_version>=20. I don't see anything for kodi 20 in the build_trakt_list code. 

Please let me know if you need anything else from me. Thank you.

**Comment by Tikipeter** [comment]
But please don't tell me you have widgets where the total listitem count for those widgets is `89999`!

That's absurd. :)

**Comment by meesterexx** [comment]
> But please don't tell me you have widgets where the total listitem count for those widgets is `89999`!
> 
> That's absurd. :)

That's what I don't understand, the item count on the liked list is only 300 items:
https://trakt.tv/users/giladg/lists/latest-4k-releases?sort=added,asc

It's like it's multiplying the number of items by itself:  1 original warning + 89,999 duplicates =90,000 = 300*300

**Comment by Tikipeter** [comment]
That's exactly what's happening.

Let me take a good look at the code. I've grown unfamiliar with it.

**Comment by Tikipeter** [comment]
Both issues fixed for next update.
