### ISSUE TITLE
episode title does not show up when using next episode

### ISSUE THREAD

**Issue by xyzfre** [Tikipeter/repository.tikipeter#172]

**Comment by xyzfre** [comment]
Weird just finished watching a TV show and it didn’t happen I was trying to replicate it to show in a video

**Comment by xyzfre** [comment]
I have tried reauthorizing Trakt and played with the settings but still won’t mark as watched,tried with a different addon to make sure it’s not my set up and it works,, Sucks because next up won’t load the next episode if I don’t manually mark as watched appreciate any help with this issue,,love using Fen

**Comment by Tikipeter** [comment]
There were changes to how Next Episode displayed in the last update (showing a cached version of Next Episode). I will be changing this to a setting option in the next update defaulting to OFF.

**Before that next update, after you have watched an episode, back out of Next Episode and navigate back into it and see if the new episode is there. I think it is marking it watched, but it is not visible to you as a cached (by Kodi) list is showing.**

Fen marks the item as watched whilst it is still playing in Kodi, so unless you are seeing an error message whilst the video is still playing, chances are it HAS marked it as watched. Give it a try.

As to the restarting scrape at completion, I will look into that. Any video or log might be handy though.

**Comment by xyzfre** [comment]
> There were changes to how Next Episode displayed in the last update (showing a cached version of Next Episode). I will be changing this to a setting option in the next update defaulting to OFF.
> 
> **Before that next update, after you have watched an episode, back out of Next Episode and navigate back into it and see if the new episode is there. I think it is marking it watched, but it is not visible to you as a cached (by Kodi) list is showing.**
> 
> Fen marks the item as watched whilst it is still playing in Kodi, so unless you are seeing an error message whilst the video is still playing, chances are it HAS marked it as watched. Give it a try.
> 
> As to the restarting scrape at completion, I will look into that. Any video or log might be handy though.

I use Next Episode (Fen) as one of my home screen widgets using AuraMod Skin for a while now ,it always used to refresh pretty well after finishing an episode,, But I have tried what you said backing out and going back into it and still won’t mark as watched,, But for example if I go into Venom it will show as watched ,and if I go to Trakt.tv using Fen it does show me I’m watching the episode ,,trying to explain the best that I can really appreciate your response and your time Fen is amazing

**Comment by Tikipeter** [comment]
Check with the most recent update and see if that has fixed your issue (v.1.6.10)

**Comment by xyzfre** [comment]
Just tried still having the same issue won’t  Mark as watched and the next episode won’t come up but if I go to for example progress in Venom The next episode is there ,, if I exit out of Kodi and go back in the next episode is there so you’re right it is being marked somewhere in the background as watched but not being displayed in Fen , I tried with both cache disc on and off

**Comment by Tikipeter** [comment]
I would first make sure you have 'Cache To Disc' OFF, then go in and remake that widget.

I also have a Next Episodes widget on my setup, and it is working properly, so I'm having trouble replicating your issue.

**Comment by xyzfre** [comment]
Not too sure if it was the update but I just tried next episode and it work instantly refresh showing me the upcoming episode which is one of my favorite features

**Comment by xyzfre** [comment]
Really sorry to bother you but just notice when using next episode it doesn’t show the episode title but if I go into the show itself not using next episode it does show the title for the Episode

**Comment by xyzfre** [comment]
![B8294A87-758D-44BE-B3E0-697D35B95940](https://user-images.githubusercontent.com/49699869/77675117-e9e81280-6f62-11ea-83af-bfb918c69b1f.jpeg)

**Comment by xyzfre** [comment]
![0048BBF5-CFD9-4293-A7C3-50664147CFD9](https://user-images.githubusercontent.com/49699869/77675205-02582d00-6f63-11ea-9f3f-0b347edcd07b.jpeg)

**Comment by xyzfre** [comment]
Really appreciate all the help I just love using Fen it really Is the best out there

**Comment by Tikipeter** [comment]
Fixed for next update.
