### ISSUE TITLE
Auto play next episode - Seconds instead of Percentage

### ISSUE THREAD

**Issue by Swimfan02** [Tikipeter/repository.tikipeter#172]
Is it possible to have an option to specify the number of seconds prior to the end of an episode to display the next episode dialogue rather than it being tied to the percentage of the episode watched?

I've found that shows generally have a 30 to 1 minute outro regardless of the length of the episode so specifying number of seconds vs a percentage will allow for a more consistent user experience.

**Comment by Tikipeter** [comment]
The whole seconds vs percentage was hashed out over a year ago, and the percentage people won.

I'd have preferred seconds till end as well. But an addon can't have everything, so I have to put up with it.

**Comment by Swimfan02** [comment]
Ah ok, yeah seconds till end makes more sense for my use cases but I understand others might not feel that way. I suppose it's not possible/not in the pipeline to have some sort of toggle to allow for using either or?

I don't mean to seem pushy or anything, I don't know the work or messiness that it'd involve. Either way, I appreciate all the hard and FREE work that is done so I don't mean to come across as ungrateful.

**Comment by TwilightMercy** [comment]
Can’t it be optional to chooseb
