### ISSUE TITLE
Birds of Prey issues with Cached sources

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#173]
Birds of Prey issues with sources, is it maybey because the long weird name? (Birds of Prey: And the Fantabulous Emancipation of One Harley Quinn (2020)

Tested Tempest, The Oath, no issues (almost all torrent scrapers are giving cached results back), other movies fine.

In the log i can't see anything relating to Fen (did you disable the logging for this maybey?)

Edit: i see that Tempest also has Plot at link level, is this possible for Fen also (nothing to do with this issue, extra request)

![birds](https://user-images.githubusercontent.com/47715606/77563466-9bcf0280-6ec1-11ea-9f62-26aca96f4abf.jpg)

**Comment by Tinuz97** [comment]
Tempest 197 sources, including cached results.
Realy weird, i only have this issue with Birds of prey (maybey others with maybey weird long names,no idea)
![birds](https://user-images.githubusercontent.com/47715606/77564086-78588780-6ec2-11ea-938a-781b1510148c.jpg)

**Comment by Tikipeter** [comment]
Fixed for next update.
I'll add the plot back in too (it was taken out to speed up results showing, but shouldn't cause much extra time).

**Comment by Tinuz97** [comment]
![9200000073410260](https://user-images.githubusercontent.com/47715606/77582802-422a0080-6ee0-11ea-86ad-cddae0efe3d6.jpg)

**Comment by Tikipeter** [comment]
Ha! Not really, Tinuz!

I forgot to mention, though, clear the External Scrapers before you test the next update for that Birds Of Prey movie.

**Comment by Tinuz97** [comment]
@Tikipeter i forgot almost 1 thing. If not authenticated with trakt (not a issue for me,because i use Trakt,but for people who don't use it) you get a pop-up that Trakt must be authenticated if you let's say browse for movies,so like Trending section. 

I removed my Trakt auth to make a screenshot for it: 
![Fen-Trakt](https://user-images.githubusercontent.com/47715606/77586801-12322b80-6ee7-11ea-915f-6ca99efa4105.jpg)

**Comment by Tinuz97** [comment]
1.6.10 works great (plot at links,and enough sources), only the little Trakt thingy (above this message)

**Comment by Tikipeter** [comment]
I can't replicate that Tinuz97. I know why it might be happening, and that is due to Indicators being set to 'Trakt' when there is no Trakt account active. But I have code to switch Indicators to Fen when Trakt is inactive, and that code is working for me.

I will keep an eye on this, but will close this Issue for tidiness.
