### ISSUE TITLE
Playback failed pop up

### ISSUE THREAD

**Issue by inky-pits** [Tikipeter/repository.tikipeter#174]
I've been receiving a playback failed pop up recently although playback is successful. This happens on stock Kodi and Maven (I had been trying both because of the separate Kodi audio dropout issue which is still happening).

During logging the second episode I tried triggered the pop up https://paste.kodi.tv/afasinoleg

**Comment by Tikipeter** [comment]
Please define "pop up"

Is it a notification or a dialog window where you have to select "OK"?

**Comment by inky-pits** [comment]
Apologies, it is a notification that briefly pops up in the top right hand corner of the screen.
![Uploading PXL_20230303_221118808.MP.jpg…]()

**Comment by Tikipeter** [comment]
That's not as troublesome to me then.

There's a (5th or 6th) rewrite of the playback monitoring code about to happen if I can get started on it.

Will address issues like this.

**Comment by inky-pits** [comment]
Okay, many thanks for your time. Atb

**Comment by Tikipeter** [comment]
No worries.

I'll close this because I am aware of this issue and I'll be reporting on it and any other playback issues after the re-write here:

https://github.com/Tikipeter/repository.tikipeter/issues/138
