### ISSUE TITLE
Enhancement: Cloud File Scraper beyond root level

### ISSUE THREAD

**Issue by akuiraz86** [Tikipeter/repository.tikipeter#174]
Can you make it possible for the premiumize cloud files scraper to scrape beyond the root level?  I have premiumize set up with a showrss feed and it places the downloaded files to this folder:  My Files \ Feed Downloads \ showrss \ TV Show Name \ Torrent filename

It would be nice to have fen check the feed downloads section and use those files if available

**Comment by Tikipeter** [comment]
I'll look into this akuiraz.

I read somewhere that Premiuimize will now let you get a big list of all the files in a user's cloud all at once. Fen currently traverses each folder so there must be some hint of the shows name in the naming of the top folder for it to continue.

If I can see how to get all files returned at once, I should be able to do what you asked. If not, then it is unlikely as each step into folders is a new API call. So if someone has 20 folders going 4 deep into subfolders that would be 80 calls to the API to check them all. I wouldn't in good conscience implement something like that.

Leave it with me..

**Comment by Tikipeter** [comment]
This will be implemented next update.

Please test and report back.
