### ISSUE TITLE
Show more then 20 entries in widget?

### ISSUE THREAD

**Issue by mariofenech** [Tikipeter/repository.tikipeter#175]
Hi,I need some help,not really an issue..
So I set up a "Discover Movies" list and added that to my list shortcuts folder.
I have show next page item in widgets disabled.
So problem is that widget only shows first 20 results.
Skin is arctic horizon 2 and widget limit is set to 50.. but i don t think it makes a difference between skins..
Is there a way to show more items then just the first page in a widget?
Thanks

**Comment by ReaLx3m** [comment]
My way to bypass that limit is to use user maintained lists from trakt.
Just like a list, and you can link the widget through fen trakt liked lists.
Heres few of what im mostly using:
https://trakt.tv/users/jjjonesjr33/lists/trakt-trending?sort=rank,asc
https://trakt.tv/users/beefybanana/lists/tmdb-trending?sort=rank,asc
https://trakt.tv/users/ink79/lists/trending-movies?sort=rank,asc
https://trakt.tv/users/justin/lists/imdb-popular-tv-shows?sort=rank,asc
https://trakt.tv/users/hdlists/lists/latest-tv-shows?sort=rank,asc
https://trakt.tv/users/garycrawfordgc/lists/latest-tv-shows?sort=rank,asc
https://trakt.tv/users/garycrawfordgc/lists/sci-fi-shows?sort=rank,asc

**Comment by Tikipeter** [comment]
Yep. Follow ReaLx3m's advice. TMDb offer 20 items per page, and that's ut. No way ro increase that.

Most lists in Fen come from TMDb.

Trakt lists don't have that restriction.
