### ISSUE TITLE
Fen and Orion Integration

### ISSUE THREAD

**Issue by jjred1977** [Tikipeter/repository.tikipeter#177]
The Orion developer has been great about fixing Orion to work with Fen with each new update. With Fen's latest update Orions scraping popup shows up but no Orion links are shown in Fen.

I was asked to pass this along,
"Please report this to the Fen developer:
In extrernal.py line 375 the function sourcesFilter() causes all the links to be removed.
I'm not really sure what was intended with this. Maybe it has something to do with the Fen debrid cache checking in that function?"

Best to ask the Fen dev to have a look. If you do not want to wait on him you can just comment out line 230 in external.py like this: #self.sourcesFilter()
Then the links should be returned.

Tiki are you able to "fix" this in an update for us Orion users since Orion isn't going to do it for some reason? I think its because they don't know what changing your code would do to your addon.

**Comment by jjred1977** [comment]
The issue is fixed. Which side fixed it I'm not sure but both addons had updates since the error occurred.

**Comment by SJ50** [comment]
@jjred1977 how do you use it? I am getting zero results but seren shows links.
