### ISSUE TITLE
Specific tv show won’t add to subscription/kodi library

### ISSUE THREAD

**Issue by jaimsitecom** [Tikipeter/repository.tikipeter#178]
This has been a headscratcher. I thought it was a tvdb or trakt bug but i guess it isn’t. I tried to add MARVELS Agents of SHIELD show into my FENs subscription list (it said it added) but when i check my subscription list, it isnt there and obviously wont get added on my kodi library. I confirmed this bug by installing a different video addon VENOM and SCRUBS just to test if trakt or tvdb is having problems with this specific TV show. So i tried adding the show via VENOM and it got added. Also the same with SCRUBS.  

So I think there’s a buggy code that prevents the show to be added somewhat.  Or is there a setting i should be turning on/off to fix this?

Thanks

Kodi 18.6. Fen 1.6.11 on Xiaomi Mibox S

**Comment by Tikipeter** [comment]
Working fine here. Is it missing from BOTH the Subscriptions list AND the file directory the .strm files should have been created to?

**Comment by jaimsitecom** [comment]
Thanks for the quick response. 
Yes both subscription list and kodi library even after doing  ‘update library’. Not getting added. It shows ‘adding Marvel agents... 0%’ then stops.

**Comment by jaimsitecom** [comment]
Ok now it got added in FEN Subscription list (by clearing cache and restarting kodi) but still nothing on kodi library.

**Comment by Tikipeter** [comment]
I mean check the folder location where the .strm files are added.

**Comment by jaimsitecom** [comment]
Marvels agents...strm file is inside the TV SHOWS folder together with the other shows i subscribed to. But it wont appear on  Kodi’s TV SHOW list in the main menu together with the others. I wonder why Venom and scrubs got to put it in the library...

**Comment by Tikipeter** [comment]
Update the Kodi library again and see if it appears. If a folder has been made on the disk and there are .strm files inside the folder, than Kodi's library should add them. One thing to check is that there is also a tvshow.nfo file inside the Agents of Shield folder. If not, delete the whole folder and add it again.

If it still doesn't work, you'll need to send me a log of adding the show, and then Kodi doing a library scan.

**Comment by jaimsitecom** [comment]
Deleted/added and then updated. Still nothing.

**Comment by jaimsitecom** [comment]
How do i insert the link for my log here?

**Comment by jaimsitecom** [comment]
Log:

https://mega.nz/#!JZoDHbIa

**Comment by Tikipeter** [comment]
I'll have to think of a way to sort this out.

In the meantime, you can go to your file sources in Kodi, select the folder for this show, and select EDIT SOURCE. Then change the 'Information Provider' to The Movie Database and rescrape and it should work.

**Comment by jaimsitecom** [comment]
Got it. Thanks Tikipeter!
