### ISSUE TITLE
'Next page' item missing in widgets

### ISSUE THREAD

**Issue by ivarbrandt** [Tikipeter/repository.tikipeter#178]
So for some reason, the 'Next Page' item is missing in widgets. It is missing whether the widget is an IMDb list with items capped at 20 or a personal Trakt list with 20+ items. I made sure to check that the widget limit items were above 20 so as to show the 'Next Page' item at the end of the list.

I use the default Estuary skin but this is happening regardless of skin.

I can provide a log if necessary.

EDIT: Nevermind. I had the setting 'Hide Next Page Item in Widgets' toggled on lol.

**Comment by Tikipeter** [comment]
>EDIT: Nevermind. I had the setting 'Hide Next Page Item in Widgets' toggled on lol.

👍 🥇
