### ISSUE TITLE
Fix UTC offset

### ISSUE THREAD

**Issue by djdirty60** [Tikipeter/repository.tikipeter#179]
good day,

 you might look at the UTC offset function which doesn't work quite well. the agenda of trakt indicates an episode a day later than fen, trakt says visible here in the Netherlands on Monday but fen says on Sunday. can you watch that otherwise an episode is already added without it already being broadcast.

**Comment by Tikipeter** [comment]
Hi djdirty60.

> you might look at the UTC offset function.....

What setting do you have for the offset?

> .....an episode is already added

Are you using Subscriptions for library integration? Is this where you say episodes are being added.

**Comment by djdirty60** [comment]
> Hi djdirty60.
> 
> > you might look at the UTC offset function.....
> 
> What setting do you have for the offset? +2
> 
> > .....an episode is already added
> 
> Are you using Subscriptions for library integration? Is this where you say episodes are being added too early? 
no at my trakt lists and then trakt: tv show calendar there are the date of Siren on 02-04-2030 but with the rest of the other add-ons on 03-04-2020 and also on the website of trakt here in the Netherlands

**Comment by Tikipeter** [comment]
I'm still looking into this, and hopefully there will be a 'fix' in the next update.

**Comment by djdirty60** [comment]
> I'm still looking into this, and hopefully there will be a 'fix' in the next update.

Oké thnx
