### ISSUE TITLE
Request ( not a issue, addon works wonderfully) 

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#18]
In the TV Shows section, is it possible to add 'new TV shows' as extra (like Numbers, The Oath as a example), or is it there with a different name, that I am overlooking it? 

Thx :100:

**Comment by Tikipeter** [comment]
'Premieres' shows TV Shows that have started airing in the last month. 'Upcoming' shows TV Shows that will premiere within the next month. 'Anticipated' is a default Trakt API list described as: 'Returns the most anticipated shows based on the number of lists a show appears on.' It mainly features new shows as well.

**Comment by Tikipeter** [comment]
BTW Tinuz97, you can find a user list on Trakt for New Shows and add it to any of the main menus in Fen (Root Menu, Movies, TV Shows), and name it what you want. Then you will have your own specific list in the menu. A popular one is: https://trakt.tv/users/garycrawfordgc/lists/new-shows?sort=added,asc
You can go on the Trakt site and 'like' the list, and then add it to a Fen menu, or you can even search for 'new shows' in Fen's Trakt: Search User Lists, and then bring up the context menu and select 'like this list', then add it to a menu....

**Comment by Tinuz97** [comment]
Great tip, thx 👌
