### ISSUE TITLE
Download pack and Browse pack are not working. FEN

### ISSUE THREAD

**Issue by Faststreamer** [Tikipeter/repository.tikipeter#18]
The download and browse pack feature are not working when i click on a link. I do not know how to post a log of the error (But another users log is attached who had same issue) but I am using kodi 19.4 with the latest Fen Version. I saw a user on reddit had a similar issue and just wanted to ensure it gained the developers attention as I know that FEN had a ressurection recently. On the reddit that user did post a log - the post was made 2 days ago. Thanks and please consider before you remove my post as I know there isnt a log but here is the other users log:
https://paste.kodi.tv/uquwipexoy.kodi
Thank you ;)

**Comment by Tikipeter** [comment]
That reddit user also received a reply saying I would be notified of the error, which I was.

It is already fixed for next update.

**Comment by Faststreamer** [comment]
> That reddit user also received a reply saying I would be notified of the error, which I was.
> 
> It is already fixed for next update.

Thanks so much for this and your commitment to providing the addon
