### ISSUE TITLE
Extras screen fails to auto-close at playback start

### ISSUE THREAD

**Issue by ivarbrandt** [Tikipeter/repository.tikipeter#180]
I noticed this a few versions ago but I kept forgetting to mention it.

I'm not sure if this is abnormal behavior or not. If a movie or show is started from the Extras screen normally the Extras screen would auto-close at the start of playback. For some reason right now that is not happening. When I click back on my remote then it closes. I made a short screenshare to showcase the issue.

https://user-images.githubusercontent.com/54084201/224535861-61091f9f-b2fe-4227-a56c-e24ad6a8582a.mov

**Comment by Tikipeter** [comment]
Fixed for next update.

**Comment by 1N73771G3NC3** [comment]
Awesome! Thank you.
