### ISSUE TITLE
Can't play Easynews links in FEN kodi on linux: HTTP error 401

### ISSUE THREAD

**Issue by jpwonder** [Tikipeter/repository.tikipeter#181]
Whether I use the actual scraped results or look up a source via the services > Easynews search, I'm unable to stream any Easynews files with FEN (they scrape fine, and so clearly there is no issue with my account linking in FEN). Real-Debrid works no problem, and I can also play the (easynews) files of interest outside of kodi via mpv with a link in the form `https://username:password@members.easynews.com/dl/auto/443/blahblah.mkv/blahblah.mkv` . So I suppose the way FEN is passing easynews authentication doesn't work with yt-dlp (I wasn't able to get a file from FEN to play with default kodi player either, still goes through ffmpeg/yt-dlp and 401 errors), or there's some linux/kodi issue going on here?

```
[ffmpeg] https: HTTP error 401 Authorization Required
Failed to open https://members.easynews.com/dl/auto/443/66814f6adbd29b01bddd1488490dbaf00a83e8130.mkv/Gallipoli%201981%201080p%20Blu-ray%20Remux%20AVC%20DTS-HD%20MA%205.1%20-%20KRaLiMaRKo.mkv|Authorization=Basic%20c2FuYW5kcmVhc2tpOl9JaER1LGBZbnhQJ3Q3elZjJTs7N2o0Zip4LTYkXGZt.
[ytdl_hook] ERROR: [generic] None: Unable to download webpage: HTTP Error 401: Authorization Required (caused by <HTTPError 401: 'Authorization Required'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U 
[ytdl_hook] youtube-dl failed: unexpected error occurred 
```

kodi log: https://paste.kodi.tv/saworozopa

**Comment by Tikipeter** [comment]
>or there's some linux/kodi issue going on here?

What Linux flavour are you running? I only have LibreELEC to test on. Whilst that is Linux, it is not the best representation of what might potentially be a problem.

>https://username:password@members.easynews.com/dl/auto/443/blahblah.mkv/blahblah.mkv

I could change the resolve url to this, but I doubt it would work for downloads through Fen. Meaning I would have to provide 2 urls - 1 for playback, one for downloads.

Which might be what I have to do.....

**Comment by jpwonder** [comment]
> What Linux flavour are you running? I only have LibreELEC to test on. Whilst that is Linux, it is not the best representation of what might potentially be a problem.

Using Arch Linux, wish I had my desktop to tell you if it was working on there, I'm on a laptop right now that isn't as well set up as the desktop. Top of that kodi log says a little more about system, but it's 16GB RAM, GTX 960M 4GB VRAM since it doesn't say that in the log.

Yeah, playing with the link is a bit annoying. I don't know enough about how fen/kodi works to help you probably but there's some alternative options (instead of changing link) for passing authentication to yt-dlp if that wouldn't mess something else up: https://github.com/yt-dlp/yt-dlp#authentication-options

Anyhow, appreciate you looking into it. Will let you know if I come across anything else, or if it starts working.

**Comment by Tikipeter** [comment]
Let's back up and just deal with Kodi. No external factors.

Is it correct that you cannot play a source from Easynews through Fen using the Kodi player in the format the url is currently in?

**Comment by jpwonder** [comment]
> Is it correct that you cannot play a source from Easynews through Fen using the Kodi player in the format the url is currently in?

Correct. Although up until this point I realized my playercorefactory was causing extra trouble (when I would tell kodi to use VideoPlayer, it would still use mpv). I fixed that now, confirmed VideoPlayer is working and plays real-debrid results correctly, but no matter how many retries, won't play easynews results. I have included my kodi log, it seems lines 367-383 are the ones of interest, I believe a curl error 22 and http error code 401.
https://paste.kodi.tv/sazikovaza

**Comment by Tikipeter** [comment]
Wow, you got some stuff going on!

With the url that WOULDN'T play, the authorization was this:
`Authorization=Basic%20c2FuYW5kcmVhc2tpOl9JaER1LGBZbnhQJ3Q3elZjJTs7N2o0Zip4LTYkXGZt`

whereas the url that WOULD play, the authorization was this:
`Authorization=Basic%20c2FuYW5kcmVhc2tpOk1Cc05RRHExTmFqVXo5VmdUM3AzNlkwbTFKRTA0c0JT`.

They should be the same, as they are a `base64.b64encode` and `.decode('utf-8')` of your `"username:password"`. Obviously the second one is correct, and the first one is incorrect. Probably the source of your issue.

I'd "Clear Internal Scrapers Cache" in Tools->Clear databases & Clean Settings Files.

Have you recently changed the settings values for your username/password? Because the link for playback is cached and will have the wrong value like above if that were the case. You would have to clear the cache to get correct urls for anything that has been cached already. Which I've never even thought about until now.

**Comment by Tikipeter** [comment]
Latest update is utilizing `https://username:password@members.easynews.com/`.

**Comment by jpwonder** [comment]
> Wow, you got some stuff going on!

Oops sorry if that was misleading, I changed my password as a security measure since I figured that authorization could be reversed. But awesome, it's working no problem now with that change, easynews and debrid, no problems! Appreciate your awesome work!
