### ISSUE TITLE
Settings Backup Failing On Some Devices.

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/repository.tikipeter#182]
Some errors are occurring when performing a Settings Backup on some devices.

Awaiting update with more logging to try to identify the issue...

**Comment by jaimsitecom** [comment]
Hi Tikipeter!  New update is great! Solved the unnecessary ‘adding of undated future shows’.  I now confirm that It doesnt add anymore future episodes. 

Here’s the latest log for the backup error:
https://mega.nz/file/5d4lWAbD#FTJr6RWi9SJuaAoove-a84hQYoi1jnjivvQ23LSfntg

Thanks so much again!

**Comment by Tikipeter** [comment]
Thanks for the log jaimsitecom.

There's probably a problem with using the python module I'm using within android.

The next update will use a custom (not by me) made zfile module that hopefully fixes this (I can't test on android at the moment).

**Comment by jaimsitecom** [comment]
Backup working fine again! Sweet! Ty Tikipeter!
