### ISSUE TITLE
Playback failed when resuming content 

### ISSUE THREAD

**Issue by IG2022** [Tikipeter/repository.tikipeter#182]
Hi there, I just noticed a problem when resuming a tv show using the latest version of fen. 3.1.01

When I try resume a show I'm running into an issue. Here is what happens: When I initiate playback on an episode I want to resume it takes me through the scraping process then asks me if I want to resume when I select "yes" this takes me to the resolving screen. This is where things get a little weird, it looks like everything is going to work and the video plays for a split second then freezes up and goes back to the scraping screen and tries to scrape again. I am then again taken to the screen to resume playback and when I select yes it doesn't go back to the resolving screen I just get a message saying playback failed. 

If I select no in the resume playback screen then the episode plays without issue. I'm also getting the same problem with movies. I use auto play for tv shows and source select for movies. 

I've attached a log for you below. 

 [Log](https://paste.kodi.tv/pisudafumu)

**Comment by ReaLx3m** [comment]
When i had a similar issue, though i dont remember if it was also happening when resuming, as per @Tikipeter advice i increased "pause between playback attempts" setting which is in playback section to 3000ms and that solved it for me. You can start with 5000ms and if it fixes it gradually go down.

Btw @Tikipeter the "playback failed" popup is back for me too in the latest version, though havent had it stop playback after starting even with the default setting of 1500ms

**Comment by Tikipeter** [comment]
Here we go again.

Turn off Settings->Playback->Monitor for Successful Playback until I can sort this out.

Fucking Kodi.

**Comment by IG2022** [comment]
> Here we go again.
> 
> Turn off Settings->Playback->Monitor for Successful Playback until I can sort this out.
> 
> Fucking Kodi.

This sorted the issue. I'm not getting that playback failed message anymore and content is resuming as it should.

Thanks!

**Comment by Tikipeter** [comment]
You should be able to turn that setting back on with the latest `3.1.02` and have it work correctly.

**Comment by xyzfre** [comment]
With this latest update something change automatically resume playback stop working I have a set for always and Limit Resolve Attempts to Selected Results Only disabled

**Comment by xyzfre** [comment]
I reverted back to 3.1.01 it's working perfect on this version specially when resuming a episode or movie it skips straight to the resume point ,prior to this version there would always be a few seconds delay before jumping straight to the resume point

**Comment by IG2022** [comment]
Thanks for sorting this out. I turned monitor successful playback back on and I'm not getting the playback failed issued anymore. I set automatically resume playback to "never" so I'm not having the same issue as @xyzfre  but if I change that setting to "always" then playback is not resumed, the video starts from the beginning.

**Comment by xyzfre** [comment]
Hey IG2022 when you set automatically resume playback to never ,does resume playback work for you

**Comment by xyzfre** [comment]
That's the first thing I noticed with 3.1.01 the resume points starting correctly which was a nice fix but if it can't be done it's alright Thank you @Tikipeter always very grateful for all your hard work my friend

**Comment by IG2022** [comment]
@xyzfre Yes in version 3.1.02 when resume playback is set to never it resumes the content as it should it's only when I set it to always that it does not resume. (Which I only did for testing purposes I usually set it to never)  Maybe you can set it to never for now as a temporary fix as Tikipeter suggested. 

Tikipeter having that option to choose which way Kodi resumes content sounds like a good idea, if the "proper" way works for some people then it would be good for them to have the option.

**Comment by Tikipeter** [comment]
There'll be a setting next update in Settings->Playback->Playback Utilities "Resume Playback Method". Choices will be "Before Playback Starts" and "After Playback Starts".

@IG2022 I would trial the "Before Playback Starts" and see if it works for you now, because of other changes I made regarding your issue. It would be worth checking it out. If it doesn't work, switch that setting to "After Playback Starts" and it will behave as it is currently.

The setting's default will be "Before Playback Starts".

**Comment by IG2022** [comment]
> There'll be a setting next update in Settings->Playback->Playback Utilities "Resume Playback Method". Choices will be "Before Playback Starts" and "After Playback Starts".
> 
> @IG2022 I would trial the "Before Playback Starts" and see if it works for you now, because of other changes I made regarding your issue. It would be worth checking it out. If it doesn't work, switch that setting to "After Playback Starts" and it will behave as it is currently.
> 
> The setting's default will be "Before Playback Starts".

Got it! I'll give it a try and report back  after I try the next update. Fingers crossed it works, but if it doesn't that's okay I am okay with it the way it currently is too.

**Comment by xyzfre** [comment]
> There'll be a setting next update in Settings->Playback->Playback Utilities "Resume Playback Method". Choices will be "Before Playback Starts" and "After Playback Starts".
> 
> 
> 
> This is a GREAT feature I really like the new way resume playback starts looking forward 💯

**Comment by xyzfre** [comment]
> There'll be a setting next update in Settings->Playback->Playback Utilities "Resume Playback Method". Choices will be "Before Playback Starts" and "After Playback Starts".
> 
> 
> 
> @IG2022 I would trial the "Before Playback Starts" and see if it works for you now, because of other changes I made regarding your issue. It would be worth checking it out. If it doesn't work, switch that setting to "After Playback Starts" and it will behave as it is currently.
> 
> This is a GREAT feature I really like the new way resume playback starts looking forward 💯
> 
> The setting's default will be "Before Playback Starts".

**Comment by xyzfre** [comment]
> There'll be a setting next update in Settings->Playback->Playback Utilities "Resume Playback Method". Choices will be "Before Playback Starts" and "After Playback Starts".
> 
> 
> 
> @IG2022 I would trial the "Before Playback Starts" and see if it works for you now, because of other changes I made regarding your issue. It would be worth checking it out. If it doesn't work, switch that setting to "After Playback Starts" and it will behave as it is currently.
> 
> 
> 
> The setting's default will be "Before Playback Starts".

This is a GREAT feature I really like the new way resume playback starts looking forward 💯

**Comment by IG2022** [comment]
Just updated and left new setting as the default resume before playback starts. The issue is now fixed completely for me and is resuming the way it should (before playback starts). Thanks so much for getting this sorted!

**Comment by Tikipeter** [comment]
Good news. I may remove that setting if there are no other issues, as it won't be needed. And the settings category for Playback Utilities is getting a bit out of hand.

**Comment by IG2022** [comment]
Yeah it works for me so I don't see the need to have the other option unless of course someone else has that problem.
