### ISSUE TITLE
Feature Request: Add ability to reset Scrapers Daily

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/repository.tikipeter#183]
From @jaimsitecom

> I hope this doesn’t sound dumb. :)
> 
> Is it even possible to get a feature where removed failing scrapers get reinstated via set time (after 1hr, 12hrs, 24hours and never)? I just find it too meticulous and too deep into the ‘openscraper settings’ to reinstate the disabled scrapers. Cause sometimes the disabled scraper works somedays and fails another time. So it would be nice if everyday/everytime i start my kodi with a complete set of scrapers. Then just let FEN prune it down along the day and just use the ‘working’ ones. Then gets reset to full list again tomorrow.
> 
> I hope my explanation made sense. Hehe
> 
> Thanks!

**Comment by Tikipeter** [comment]
I'm going to think about this.

**In the meantime, you can use Tools->External Scrapers Manager to both "Reset External Scraper Stats" and "Enable all Scrapers". That will be a lot less navigation for you then going into the Openscrapers settings.**

The problem with resetting each day is it takes multiple scrapes to build up info on which scrapers are consistently failing. Because Fen uses Openscrapers, the only real way to gauge success/failure is whether results are returned. A scraper could be functional, but simply not return a result because it does not provide that movie/tv show. So implementing your idea would mean that scrapers need to begin being evaluated and turned off right from the first scrape it does, because someone might only perform 5 scrapes for the whole day.

Anyway, I'm thinking......

**Comment by jigoop1** [comment]
@Tikipeter 
you r right otherwise it kill the purpose of disabling scraper. instead  of resetting if u can check it with db file  for success or not , then if no success for let's say 25 times than disable particular scraper that would be more helpful .
thanks

**Comment by Tikipeter** [comment]
@jigoop1 
That should be what Settings->External Scrapers->"Remove Failing Scrapers" does now. It will keep a track of failing scrapers, and remove them after a certain number of uses. Set "Sample Time Before Removal" to set how many times the scraper is used before it is disabled by Fen. If the scraper fails twice as often as it succeeds (67% fail rate), then it is automatically disabled.

**Comment by jaimsitecom** [comment]
Right. Great points. I guess i only asked this request coz the ‘lazy-me’ came out. Haha i should experiment more on the number of scrapes see if that helps.

**Comment by rrosajp** [comment]
@Tikipeter 
oh ,i thought it disable only based on nos of fail not compering with success ,if it does that then it's the ideal.    
thanks for all yr hard work.

**Comment by Tikipeter** [comment]
This will be implemented next update.

Subsetting of Settings->External Scrapers->General->"Remove Failing Scrapers".

You will have a choice in settings between "Never, Daily, Weekly, AfterScrapersUpdate", as to when you want Fen to clear the scraper stats and re-enable all the scrapers. Default will be "Never".

"AfterScrapersUpdate" will reset scraper stats and re-enable all scrapers after any OpenScrapers update.

If you set it daily, I'd go for a low number for "Sample Size Before Removal". That setting is now a slider so you can choose between 1-50 scrapes before scrapers start getting turned off...

**Comment by jaimsitecom** [comment]
Yay! Thanks again Tikipeter!
