### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#184]
No idea if possible, or asked before, Premiumize newsgroups support, like Gaia (I think that is the only addon supporting it at the moment).
But I don't use Gaia anymore since Seren, and now only using Fen since a long time. 

It is perfect, has anything I like, including advanced tweaks, I only miss newsgroups support for Premiumize.

I have no idea if this is technically possible with Fen, just a idea :)

**Comment by Tikipeter** [comment]
I'll look into it, but I have a feeling Premiumize now no longer supports the lookup of 'cached' .nzb files, and possibly doesn't cache them at all anymore. If they aren't cached, or can't be found, then there will be no way for an add-on to play them. :(

If you still have Gaia on an install somewhere, let me know if it still works. Don't install Gaia if you don't already have it though. Too much trouble.

**Comment by Tinuz97** [comment]
I will look into it tomorrow, I think I have a older (personal) build with Gaia (or maybey I wiped it already, not sure), if I still have it, I have it easily installed.
But now it is bedtime for me :)

**Comment by Tikipeter** [comment]
A reply by Premiumize to a question about the caching status of nzb's:

> nope they used to be cached but because nzbs dont have a hash system like torrents, even though we proposed one to the indexer software github and they eventually were planning to add it but no sites adopted it just yet, then there's not much we can do. Also not to long ago we had to change things due to DMCA so nzb's are no longer cached at all.

Probably not worth checking Gaia....

**Comment by Tinuz97** [comment]
Thx for the info

**Comment by Tikipeter** [comment]
I'll close this Tinuz97. Unfortunately, there is no way to stream an nzb file "on the fly" in Kodi, so since Premiumize no longer cache them, it is impossible.

Sorry mate. :( :(

**Comment by Tinuz97** [comment]
No problem, thx for taking a look at it.
