### ISSUE TITLE
Cursor wrap-around in Fen settings "General" category doesn't work

### ISSUE THREAD

**Issue by OneAngryMan** [Tikipeter/repository.tikipeter#184]
This is a petty bug report, but in the "General" category of Fens settings, the cursor wrap-around (pressing up on topmost item navigates to bottommost item) isn't working due to the large number of hidden settings in that category. Seems like Kodi runs out of eligible control ids there. Splitting the hidden settings across two categories seems to fix this.

**Comment by Tikipeter** [comment]
I'll sort it out for next update. :)
