### ISSUE TITLE
New category values not working for custom Trakt lists

### ISSUE THREAD

**Issue by ivarbrandt** [Tikipeter/repository.tikipeter#185]
Some of the new category values don't seem to be working correctly for Trakt lists. Upon further inspection I saw that any custom Trakt list whether created by the user or other users, is showing the category value/breadcrumbs as "Shows" regardless of the content being movies or shows.

Trakt Collections, Recently added, Watchlist, and Recommended all work fine. 

Btw neat addition of the category values. It looks super clean!

**Comment by Tikipeter** [comment]
These should be assigned correctly next update.
