### ISSUE TITLE
Trakt 

### ISSUE THREAD

**Issue by djdirty60** [Tikipeter/repository.tikipeter#186]
good day, 

trakt does not work properly, liked lists do not load remains empty and the calendar and subsequent episodes do not always load properly.

**Comment by jaimsitecom** [comment]
I think trakt, or tvdb and tmdb had api issues hours ago, i had the same problem. But got to confirm it wasnt FEN when i tested Venom, as it had the same problem when accessing trakt/tvdb or tmdb. 

Right now everything is smooth again. No errors.

**Comment by djdirty60** [comment]
still does not work

**Comment by Tikipeter** [comment]
Hi djdirty60.

I'm afraid I simply don't have enough information to go on with your issue.

As a stab in the dark, I would clear both Trakt and Meta Cache's and see if that fixes the problem.

**Comment by djdirty60** [comment]
found the error, if I turn on kyradb at meta I see nothing and if I turn off kyradb I see everything again
