### ISSUE TITLE
Library

### ISSUE THREAD

**Issue by djdirty60** [Tikipeter/repository.tikipeter#187]
good day, 
is it correct that no specials of series are added to the library?
and is it possible to be able to do that?

**Comment by Tikipeter** [comment]
You cannot add specials to the library.

It is possible to do that, but I won't be adding it.

**Comment by djdirty60** [comment]
🖕🏼🖕🏼🖕🏼

**Comment by Tikipeter** [comment]
> 🖕🏼🖕🏼🖕🏼

My apologies @djdirty60 , I didn't realize this meant so much to you.

Now that you've "given me the finger" x 3, I'll  look into this for you.

Please keep an eye out here for updates....

**Comment by Tinuz97** [comment]
That made me laugh, LOL

**Comment by ANHBOB** [comment]
I thought that was very rude of djdirty60  to do that to you Tikipeter after all you've done for us users. Taking your time to create an awesome addon and always trying to improve it. I think it's the BEST addon out there by far of all the ones I've ever used.

Tikipeter...just remember...“You can please some of the people all of the time, you can please all of the people some of the time, but you can’t please all of the people all of the time”
Keep up the great work and thank you for all you have done.
