### ISSUE TITLE
Filtering of cams and TSs...

### ISSUE THREAD

**Issue by jaimsitecom** [Tikipeter/repository.tikipeter#188]
Hi Tikipeter, is there a better way to filter out the CAMS and TS movies and TV shows?  I only use Debrid sources but Cams and bootlegs still get thru into the list even if i unchecked ‘include pre-release results’ from the SETTINGS/RESULTS/SORTING & FILTERING settings page. 

For example, try scraping for BIRDS OF PREY, and uncheck the include pre release...’. Lotsa CAMS and TS versions will come up. 

I guess when the filename has the word ‘HD’ even if it’s really a ‘BIRDS OF PRET HD CAM’, it wont get filtered out. Just guessing. :)

Anyways, thanks again.

**Comment by Tikipeter** [comment]
Yeah, I noticed the recognition of CAMS etc wasn't too good with the external scraper.

I've added an extra check after Fen gets hold of the results. It isn't perfect (it never will be), but if the cam/ts/tele status is reflected in the filename, it should pick it up now and adjust the quality accordingly.

Will be ready for next update.

**Comment by jaimsitecom** [comment]
Thank you!
