### ISSUE TITLE
Dutch language gone? (need help?)

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#19]
if you want to add it, just tag me, happy to help, if not, also ok, just to let you know i am reading here also.
Welcome back.

**Comment by Tikipeter** [comment]
Firstly, great to see you again. :)

I need to have a good think about what to do with language files moving forward. It was a significant burden coding wise in the past, as even adding a single new setting meant the need for updated files.

The plan was for English only moving forward. But I'll have another think.....
