### ISSUE TITLE
Real debrid not working

### ISSUE THREAD

**Issue by tiagoclc** [Tikipeter/repository.tikipeter#192]
Real debrid not working on fen 3.1.05
Every time i try to play a show episode or a movie there's no results.

I've tried to revoke real debrid authorization and authorize again but it returns a fen error.

**Comment by ivarbrandt** [comment]
Can confirm. Same thing happening here.

https://user-images.githubusercontent.com/54084201/227094388-4e0594ae-f97d-4e52-9e7b-28c4ba9fb106.mp4

**Comment by tiagoclc** [comment]
Real debrid is down. 

Read the comments: https://www.isitdownrightnow.com/real-debrid.com.html

**Comment by ivarbrandt** [comment]
Wow it's down everywhere.

**Comment by tiagoclc** [comment]
![Screenshot_2023-03-23-00-41-23-550_com facebook katana-edit](https://user-images.githubusercontent.com/20015979/227097002-e7278138-f174-45a1-9f15-2d99785f2e24.jpg)

**Comment by tiagoclc** [comment]
Aparently its a real debrid (expired ssl) problem.
