### ISSUE TITLE
Similar/Recommended not loading.

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#192]
If i see a movie i like, in this case : Superman Red Son,choose Similar/Recommended option, after that similar, no results.
If i choose recommended i get recommended movies, is similar broken ?

**Comment by Tikipeter** [comment]
I think it works OK. Other movies worked for me, but not Superman Red Son, like you say. I just think there aren't any "Similar" movies linked to that movie.

Both calls go to TMDb, but Similar is an older method that relies on Genres & Keywords to link similar titles. Superman Red Son doesn't have any keywords associated with it on TMDb, so no results for Similar. A bit of light reading on the subject:
https://www.themoviedb.org/talk/59efc7fcc3a3680682004dba?language=en-US

It might be an idea to switch "Similar" to a Trakt based call. I've got a couple of other things to do first, then I'll look into what they offer.....
