### ISSUE TITLE
Autoscrape next episode text

### ISSUE THREAD

**Issue by JFG1000** [Tikipeter/repository.tikipeter#193]
![20230323_223505](https://user-images.githubusercontent.com/76907836/227379833-12ea6908-983e-40f3-9e9c-efc6000b195c.jpg)
Hey Tiki I've just noticed the text is greyed out "Auto scrape next episode" using AH2, not sure if it's intentional or not

Kind regards

**Comment by Tikipeter** [comment]
That highlight honors Settings->General->General->Custom Windows Highlight Color.

There is a skin pack for AH2 with custom xmls for Fen. Turn on Settings->General->General->Use Custom Skin XMLs When Available to use them with AH2.
![screenshot00000](https://user-images.githubusercontent.com/28930002/227397583-db3c8982-bd6f-43be-ace5-54096bf780c3.png)

**Comment by JFG1000** [comment]
Awesome that's sorted it, many thanks Tiki. Loving this skin
