### ISSUE TITLE
Is there a way to send you a private message?

### ISSUE THREAD

**Issue by ANHBOB** [Tikipeter/repository.tikipeter#194]
Tried to send one in Addons4Kodi but it said your account was deleted.

**Comment by Tikipeter** [comment]
I'm afraid I deleted my Reddit account in protest of their policies so I am no longer contactable on any 'social media' type platforms, and thus by private messaging. Sorry ANHBOB.

**Comment by ANHBOB** [comment]
That's ok. I had a couple of things I wanted to ask but not on an open website as this.
