### ISSUE TITLE
Folder scrapper does not match some Movie and series

### ISSUE THREAD

**Issue by SJ50** [Tikipeter/repository.tikipeter#195]
Today I noticed that WALL-E does not matched by Folder Scrapper.
it is named as following

`/media/storage/Movies/Movies_HD/WALL·E.2008.1080p.BluRay.DTS.6.1ch.x264.[tt0910970]-SbR/WALL·E.2008.1080p.BluRay.DTS.6.1ch.x264-SbR.mkv`

`/media/storage/Movies/Movies_UHD/WALL·E.2008.2160p.BluRay.UHD.Remux.TrueHD.7.1ch.ATEME.[tt0910970]-EPSiLON/WALL·E.2008.2160p.BluRay.UHD.Remux.TrueHD.7.1ch.ATEME-EPSiLON.mkv`

I was trying to folder scrap really old series https://thetvdb.com/series/mahabharat
it is named as 
`/media/storage/TV_Shows/TV_Shows_HD/Mahabharat\ \(1988\)/Season\ 01/Mahabharat.S01E01.Introduction.Of.Kuru.Family.Raja.Bharat.And.Raja.Shantanu.NTSC.DVDRip.AAC2.0.x264-BTN.mkv`

How do I make sure that both gets matched by folder scrapper?

**Comment by Tikipeter** [comment]
For Wall-E, if you remove the strange 'dot' in the filename it should scrape it.

For Mahabharat, I've edited the metadata on TMDb (it was called Mahabharata), so in an hour or so you should be able to refresh the meta cache for that item, and it will find the correct path. To refresh the meta cache, bring up context menu on Mahabharata, and select Add/Remove->Remove From...->Remove From Cache. It should then display the correct name, and be found in your folder.

Moving forward eventually, I would like to implement a system for these folders like I have for the RD and AD Cloud scrapers, where you can 'link' a TV Show (or Movie as well in this case) to a specific movie or series. Then, it doesn't matter the naming of the folders, Fen already has info telling it to link a Movie/Show with that particular folder. It would only be needed when a match doesn't occur, but would have been handy for the two examples you have above.

**Comment by SJ50** [comment]
Thank you for clarification and help
