### ISSUE TITLE
Recently watched episodes stop working with latest version 3.1.05

### ISSUE THREAD

**Issue by xyzfre** [Tikipeter/repository.tikipeter#195]
Hey @Tikipeter noticed this today so I reverted back to the previous version 3.1.04 to test and Recently Watched Episodes is working perfect on .04, K20.1 Windows 11 Pro ,AH2

**Comment by xyzfre** [comment]
Before reverting back to .04 I did try clearing Trakt cache and database from Fen Tools even the addon_data/plugin.video.fen/databases and delete the navigator.db file.

**Comment by Tikipeter** [comment]
Looks like somebody broke it last update.

It's possible it was me.

I'll fix it and upload a fix soon.

**Comment by xyzfre** [comment]
Thank you @Tikipeter looking forward to the update 😁
