### ISSUE TITLE
The because you watched.... is not working at Fen 1.6.16

### ISSUE THREAD

**Issue by chrisnikol** [Tikipeter/repository.tikipeter#196]
After the last update to version 1.6.16 the "Because you watched...." function is not working anymore.
When you are choosing a movie then go to next screen but dosent return any results. Actually dosent seem to search at all.

What i've done so far:

I unistall and install Fen again
I re-authorize the trakt
I clear all cache
I resynced he watched status at trakt.

Here is a short 30 sec video that you can see all the above.
https://youtu.be/oxvZ3OMofG8

Of course that small issue dosent mean that i am not gratefull to you for this amazing addon, with frequently updates and very intresting functions like the Because you watched.... or the discover.

**Comment by Tikipeter** [comment]
Thanks @chrisnikol 

Oversight on my part. Will be fixed next update.
