### ISSUE TITLE
Error when launching media through widget

### ISSUE THREAD

**Issue by WickedT53** [Tikipeter/repository.tikipeter#196]
Hey @Tikipeter 
Fen is displaying error each time I start any media through widget. Happens each time while the file is loading (after scraping) and then it eventually plays.
Using shield, kodi 20.1. Skin is AH2
http://paste.kodi.tv/halamuyuve 
Appreciate any help you might have. Thanks mate

**Comment by Tikipeter** [comment]
Fixed for next update, which should be today.

**Comment by WickedT53** [comment]
You're a legend thanks as always mate 👍
