### ISSUE TITLE
[XBOX] Error trying to watch show I just watched two days ago

### ISSUE THREAD

**Issue by chazbaps** [Tikipeter/repository.tikipeter#197]
Ongoing issue trying to watch a show I just watched recently on Xbox SX. Kodi will not return to previous menu and is stuck in the scraping window upon error notification. I've tried every button on the controller. I've tried fresh, clean installs. This is driving me insane. 

Wrong log? (Can't get to log after error notification):
https://paste.kodi.tv/omacisalit
![20230326_120545](https://user-images.githubusercontent.com/128988574/227789074-1d70ad80-55a0-41c6-83dd-e93206215ca9.jpg)
![20230326_120556](https://user-images.githubusercontent.com/128988574/227789079-a3b50148-94f6-4a95-b514-22ea153f45e2.jpg)
![20230326_120603](https://user-images.githubusercontent.com/128988574/227789077-df2ae149-6b79-4182-8f66-f68ad26139f9.jpg)

**Comment by Tikipeter** [comment]
Restart Kodi after it happens, and then upload `kodi.old.log`.

**Comment by chazbaps** [comment]
Went into CocoScrapers and disabled BitSearch it seems to work now.
