### ISSUE TITLE
Fen error, Playlist ‘cant find next one to play....

### ISSUE THREAD

**Issue by jaimsitecom** [Tikipeter/repository.tikipeter#197]
Hi again Tikipeter. Not really major ‘bug’ but with the latest version 1.6.16, when you click to play a movie on the library, just before scraping, an error will pop up — FEN ERROR, PLAYLIST (cant find next one to play...). But if you click it 2nd or third time, scraping will proceed and play the movie. I just find that error odd, and first time i’ve seen such. 

Should i post the log?

**Comment by Tikipeter** [comment]
I can't make this happen jaimsitecom.

Perhaps you have some other item stuck in your playlist. If you restart your machine perhaps it will solve this problem.

You will see this notice every time you select to play something from the library and then don't select a source, however.

**Comment by jaimsitecom** [comment]
That’s alright, Tikipeter. I don’t have anything in the playlist and this error is not constant. It appears erratically. Sometimes doesn’t at all. It’s very minor for me and can be ignored. 

Thanks anyways!
