### ISSUE TITLE
download question

### ISSUE THREAD

**Issue by ke7doy** [Tikipeter/repository.tikipeter#198]
I changed the default download path to a folder on attached storage because the available space in the default was insufficient to store the intended file.  According to the ending pop-up the download was successful, but despite an extensive search of both the desired location and the native storage of the device I  was unable to find the file.  What did i miss?

**Comment by Tikipeter** [comment]
No log?

**Comment by ke7doy** [comment]
paste.kodi.tv/zewomuxafu

**Comment by Tikipeter** [comment]
Ugh, Amazon.

All I could suggest is make sure you have the write permissions sorted for the hard drive.

**Comment by ke7doy** [comment]
Thanks for the tip!
