### ISSUE TITLE
Episodes keep playing after playback stopped

### ISSUE THREAD

**Issue by ivarbrandt** [Tikipeter/repository.tikipeter#199]
I noticed something strange start happening on v3.1.05. This is the sequence of events:

1. I'm watching an episode and the Next Episode dialog comes up, I click Cancel, then Stop in Kodi.
2. After returning to the homescreen I wait a few seconds. Suddenly the episode I just watched will start playing again automatically.
3. I click Stop. Back to the homescreen. I wait a few seconds then the next episode after that one starts playing automatically.
4. After I click Stop on that one it returns to the homescreen and doesn't play anything else.

This has happened about 4 or 5 times now.

Here is my log: https://paste.kodi.tv/beqiregume.kodi

**Comment by Tikipeter** [comment]
Strange.

**Comment by ivarbrandt** [comment]
Indeed.

**Comment by ivarbrandt** [comment]
I've gathered some more evidence. 

This is happening on any show. This also seems to only be happening when going back to a widget on the home screen. It happens like I described it above but I noticed it also happens when returning to the home screen widgets from any other window. So the thing that I see in common here is the returning to the home screen widgets. The times that it doesn't play the next episode, Fen throws an error, then Kodi crashes. This happened several times. I'm not sure if it is related but I included the log for the crash as well.

This first video shows what happens when clicking Cancel, then Stop.
https://www.dropbox.com/s/tu2y1gqo65bhb41/test3.mp4?dl=0

These two videos shows the same thing after returning to the home screen.

https://user-images.githubusercontent.com/54084201/227820299-bfdee019-8411-4109-aea5-2cd774b53f59.mp4

https://user-images.githubusercontent.com/54084201/227820320-d03024bc-506f-4f14-ba03-ef7a54b2d658.mp4




And here is the log for the crash

https://paste.kodi.tv/difovuvoha.kodi

**Comment by AakashC2020** [comment]
Hi @ivarbrandt and @Tikipeter,

This issue is happening for me as well for both Movies and TV Show Episodes while using widgets, after the latest Fen update. I can also provide a log if needed. Thank you!

**Comment by Tikipeter** [comment]
I'm looking into this....

**Comment by AakashC2020** [comment]
> I'm looking into this....

Thank you @Tikipeter !

**Comment by tundrablasen** [comment]
I noticed in the latest version, that when approaching via a skip to the trigger of the next episodes widget, it gets started automatically without me pressing „play“

**Comment by xyzfre** [comment]
> I noticed in the latest version, that when approaching via a skip to the trigger of the next episodes widget, it gets started automatically without me pressing „play“
> 
> 
> 
> e.g. outer banks episode is finished and the end credits are running. But it’s too much time left for the next episodes widget to pop up. So I skip a few seconds to the front until it’s time for the widget. It comes up and the episodes gets automatically played without hitting „play“
> 
> 
> 
> Gonna provide a log whenever I have the next opportunity 

If you skip to the end of the episode and don't click on close on the next episode dialogue pop up The following episode will start playing, there is a Setting in playback where you can change this behavior

**Comment by tundrablasen** [comment]
> > I noticed in the latest version, that when approaching via a skip to the trigger of the next episodes widget, it gets started automatically without me pressing „play“
> > e.g. outer banks episode is finished and the end credits are running. But it’s too much time left for the next episodes widget to pop up. So I skip a few seconds to the front until it’s time for the widget. It comes up and the episodes gets automatically played without hitting „play“
> > Gonna provide a log whenever I have the next opportunity
> 
> If you skip to the end of the episode and don't click on close on the next episode dialogue pop up The following episode will start playing, there is a Setting in playback where you can change this behavior ,for example I have this setting set to play so if I skip to the end of an episode The next one will start playing automatically without me clicking anything on the dialogue pop up

Define „end of the episode“. I’m not skipping to the end. I’m skipping like where it’s 1-2 minutes left on the episode, so that the next up widget is triggered. The current episode itself has some time left to play

**Comment by xyzfre** [comment]
My Apologies I missed read your post I thought you were referring to the episode widget but I see you're referring to the next episode dialogue pop up ,I'm not experiencing this behavior it's working perfect on my end good luck 👍🏼
