### ISSUE TITLE
Torrent hash check switch.

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#199]
Is it possible (no idea) to make a torrent hash check switch?

So switching between the 'old' cache check before you introduced the 'hash check',a switch that you can choose which you want. 

Why?

Because I noticed this is a aggressive filter, i miss my favorite scrapers since the hash check, like 1337,extratorrent,glodls,limetorrents, torlock, torrentquest, zoogle as a few examples. 

Even with the latest openscrapers from today. 

Or is it already in the settings (I can't find it) to disable the hash check, so it checks the cache like before.

**Comment by Tinuz97** [comment]
In venom as a example, I see 1337x, limetorrents etc. (also using openscrapers)

**Comment by Tinuz97** [comment]
Or maybey it has nothing to do with the hash check, no idea, but those sources are missing in the results 😞

**Comment by Tikipeter** [comment]
I will make a setting to turn off the filter for torrents specifically.

**Comment by Tinuz97** [comment]
@Tikipeter, works great, all favorite torrent scrapers back ❤️
