### ISSUE TITLE
problem with Set Metadate Language

### ISSUE THREAD

**Issue by jshn68** [Tikipeter/repository.tikipeter#2]
hi I have a question if I set the Set Metadate Language to Dutch and I load my
widget in then kodi stops and when I set it back to English it loads the widgets normally.

And that only happens with the movies widgets if I turn it off then kodi doesn't stop?

Thank you and so glad you're back!

**Comment by Tikipeter** [comment]
Reproduce this and post me a log that captures it happening.

**Comment by jshn68** [comment]
i've never done this before i have no idea how to find log.
I'll check tomorrow how this works.

**Comment by jshn68** [comment]
dissolved
