### ISSUE TITLE
not an issue.feature request 

### ISSUE THREAD

**Issue by cabban** [Tikipeter/repository.tikipeter#20]
hello, this addon is greAT ONLY two things i misses :) 
1. search genre by years 
2. subtitles from settings :) i hope this can be added :) now i must go through all genres to search movies to save :) 
i am positive cause first developer, who actually answers users, issue and request and that is rare this days :)

**Comment by Tikipeter** [comment]
Hi cabban.

1. I should be able to do that. Let me think of the best way to implement it.
2. You are the second person to request this. I've resisted it so far, as I have no experience with subtitles at all and Kodi provides ways to download them itself. I'm going to think about this again, with the view to probably doing it if it isn't too hard. I'll have a look at an Exodus fork that has a working example of it to get inspiration from.

**Comment by cabban** [comment]
@Tikipeter thank u so much :=) <3 best

**Comment by cabban** [comment]
@tikipeter thank u for filtering 😀 but, I was trying but couldn't find anything year start how? To add? Year start 1987 year end 2016 comedy 😀 I try to context the tips. Now only subtitles left. Then this is 10 of 10😀

**Comment by cabban** [comment]
> 
> 
> Hi cabban.
> 
>     1. I should be able to do that. Let me think of the best way to implement it.
> 
>     2. You are the second person to request this. I've resisted it so far, as I have no experience with subtitles at all and Kodi provides ways to download them itself. I'm going to think about this again, with the view to probably doing it if it isn't too hard. I'll have a look at an Exodus fork that has a working example of it to get inspiration from.

i was only trying to have filter
1987-2016 
comedy
only english movies not french spanish etc 
not animated 
but i just cant :(

**Comment by Tikipeter** [comment]
What part doesn't work cabban?
I will add a 'without genres'.

**Comment by cabban** [comment]
try this but i cant figured out how to make a filter ::( no genres is
great ,
i only want to make export this
comedy
english movies
1987-2017cbut i cant as i explained figure out how to do this

Den mån 26 aug. 2019 kl 21:22 skrev Tikipeter <notifications@github.com>:

**Comment by cabban** [comment]
can u show me how to make filters in fen. canrt find anything in settings  maybe im stupid im sorry but

**Comment by cabban** [comment]
![Namnlös](https://user-images.githubusercontent.com/19514493/63754914-f9608980-c8b5-11e9-942f-7db845b6e863.jpg)

**Comment by Tikipeter** [comment]
OK. I understand you now. You don't have the new 'Discover' menu activated in Fen yet. :)

In the root menu (the first menu that opens when you open Fen), bring up the context menu on any item. Then select 'Edit Menu'. Then click 'Check if Root Menu has New Menu Items'. Fen should then tell you that a new item, 'Discover' has been found. Select Yes to accept it, and assign it a place within the root menu. If that fails, select 'Restore Root Menu to Default'. That will, however, reset any changes you have made to the root menu.

Once you have the Discover menu available to you, here are some steps/tips to help you...

Browse into 'Discover', select 'Movies' or 'TV Shows', and assign the filters you want to set. Then select 'Save & Browse Results' to see the results of the filtered search, and/or select 'Export Search' to make this filtered search a menu item. You can place it in the Root menu, Movie menu or TV Show menu (Music menu as well, but that's not really relevant to these Discover lists).

If you click on a filter that already has a value set, Fen will ask if you want to change that value or clear it. At the top of the filters is a 'Clear All Filters' item that will clear all the filters at once.

Any filtered list you export or browse into will be saved into history (last 7 days worth are kept). From there you can browse into them again, or export them via the context menu.

**Comment by Tikipeter** [comment]
For your list you are trying to make above, you would do the following....

Set 'Start Year' to 1987
Set 'End Year' to 2016
Set 'Include Genres' to Comedy
Set 'Exclude Genres' to Animation
Set 'Language' to English (EN)

Then you would hit 'Save & Browse Results' to see the results of the filters, and/or select 'Export Search' to make that search a menu item in one of Fen's main menus (Root, Movie TV Show). Fen will automatically assign a name for the new list item, in this example it will be:
'MOVIES | 1987-2016 | EN | Comedy (not Animation)'
When exporting the list, you can edit the name to be whatever you like.

Good luck! Let me know of any issues you might have....

**Comment by cabban** [comment]
> 
> 
> For your list you are trying to make above, you would do the following....
> 
> Set 'Start Year' to 1987
> Set 'End Year' to 2016
> Set 'Include Genres' to Comedy
> Set 'Exclude Genres' to Animation
> Set 'Language' to English (EN)
> 
> Then you would hit 'Save & Browse Results' to see the results of the filters, and/or select 'Export Search' to make that search a menu item in one of Fen's main menus (Root, Movie TV Show). Fen will automatically assign a name for the new list item, in this example it will be:
> 'MOVIES | 1987-2016 | EN | Comedy (not Animation)'
> When exporting the list, you can edit the name to be whatever you like.
> 
> Good luck! Let me know of any issues you might have....

![Namnlös](https://user-images.githubusercontent.com/19514493/63795536-6bf85600-c904-11e9-91b5-44828bbcea52.png)
big thank u :) now :) all comedy from 1987 -2017 :)  best cooperatiove helpful developer in all rtimes ::) <3

**Comment by Tikipeter** [comment]
I am using the TMDb API for this feature. There is a 'region' query that can be used, but I'm not sure how well it works. I have included it (Movies only) in Discover for the next update. Cabban, can you test it and see if you get results that you expect? I've tried testing, but I don't really know what results I should be seeing, and whether it is filtering by region AS WELL AS by original language. My foreign movie knowledge is poor.

Also, if it does seem to work, check if there are any countries that I haven't included in the 'region' section. I had to take out a lot that I didn't think were needed, as the total list is too big to be practical (I think I left 71 countries in the list).

If it doesn't give the results you think it should, I'll remove it in a following update.

**Comment by Tikipeter** [comment]
I don't think this is going to work. If the movie is released AT ALL in the region country chosen, it will show up. So, it isn't specific to the region the movie was ORIGINALLY released in, only if the movie was released in the chosen country AT ALL.

Unfortunately, in the API documentation, I can't see any other query that might achieve the desired results. There needs to be something like a 'country_of_origin' param.  :( :( :(

**Comment by cabban** [comment]
I ment, whole united kingdom all European movies and united states , you have add all that I asked for I am chock and appreciate it😀 region multiselect? Now I can only choose 1 united states is most movies. Region @tikipeter

**Comment by cabban** [comment]
> 
> 
> I don't think this is going to work. If the movie is released AT ALL in the region country chosen, it will show up. So, it isn't specific to the region the movie was ORIGINALLY released in, only if the movie was released in the chosen country AT ALL.
> 
> Unfortunately, in the API documentation, I can't see any other query that might achieve the desired results. There needs to be something like a 'country_of_origin' param. :( :( :(

it works great a few wrong movie in there no bother, french movie inside english list , and hope for the multiselect region, then i can choose , uk ameriica:)

**Comment by Tikipeter** [comment]
Multi-region is not supported by the TMDb API, so I'm afraid you're out of luck with that one cabban. :( :(
