### ISSUE TITLE
[Enhancement] HEVC Files Filter Quality Selection

### ISSUE THREAD

**Issue by ReaLx3m** [Tikipeter/repository.tikipeter#20]
When using old PC or a SBC like Raspberry Pi 3B as HTPC, you cant play 1080p HEVC due to no hardware support and limited CPU power, 720p will play just fine. I assume some older android boxes would run into same limitation. Also some might be able to play 1080p but have problem with 4K HEVC.

With current state of things you can either select to include or exclude HEVC in results, and to avoid issues with autoplay trying to play 1080p HEVC logical thing would be to exclude them, which will limit results. 
So it would be great if an option could be added to select up to what quality HEVC to include SD/720p/1080p/4K 

Not related to the suggestion above, but so i dont start another thread i thought it would be best to ask here. 
So Next Episodes takes very long time(about a minute or so) to load for me using Orange Pi PC2(bit faster that RPi 3B).
Is there a way that im not aware of to speed up that aspect?
I do have a lot of items in the list, more than 200, which i assume is the reason why it takes so long. Paginate helps speed up things considerably with Watchlist, but doesnt work in Next Episodes.

Edit:
In Progress TV Shows, while it does paginate doesnt seem to get any improvement from it, also takes very long time to load a page with even 4 items.

**Comment by CocoJoe2411** [comment]
>When using old PC or a SBC like Raspberry Pi 3B as HTPC, you cant play 1080p HEVC due to no hardware support and limited CPU power, 720p will play just fine. I assume some older android boxes would run into same limitation. Also some might be able to play 1080p but have problem with 4K HEVC.
With current state of things you can either select to include or exclude HEVC in results, and to avoid issues with autoplay trying to play 1080p HEVC logical thing would be to exclude them, which will limit results.
So it would be great if an option could be added to select up to what quality HEVC to include SD/720p/1080p/4K

I'll have a think about this. I can only play 720p HEVC as well, so I limit autoplay results to 720 to get around that.

>Not related to the suggestion above, but so i dont start another thread i thought it would be best to ask here.
So Next Episodes takes very long time(about a minute or so) to load for me using Orange Pi PC2(bit faster that RPi 3B).
Is there a way that im not aware of to speed up that aspect?
I do have a lot of items in the list, more than 200, which i assume is the reason why it takes so long. Paginate helps speed up things considerably with Watchlist, but doesnt work in Next Episodes.
Edit:
In Progress TV Shows, while it does paginate doesnt seem to get any improvement from it, also takes very long time to load a page with even 4 items.

***Short Answer:***
Hide some (a lot) of those 200 shows currently in the progress/next ep lists. Your user case is the exact reason Trakt offers this feature.

***Long Answer:***
This is a hard one. To determine whether or not each show has been only partially watched or fully watched, I need the total episodes info from a TMDb call. In order for there not to be certain pages where only a fraction of the paginate limit is filled, I need to filter out the fully watched shows before paginating the list. Meaning I need to fetch that info on every item in the list before I then paginate it.
The problem with that is that there is almost no benefit, speed wise, to paginating when it comes to the "Watched" and "In Progress" lists. To get around the call for meta for each item in the list before paginating, I could use some extra info that Trakt provides to get the episode count, but then I wouldn't have that info available if the user wasn't using Trakt. Meaning I'd need to maintain 2 methods for both In Progress and Watched, which I am not willing to do.
So, especially on under powered hardware, we return to the short answer. That is about all you can do about the slow loading.

**Comment by Tikipeter** [comment]
>When using old PC or a SBC like Raspberry Pi 3B as HTPC, you cant play 1080p HEVC due to no hardware support and limited CPU power, 720p will play just fine. I assume some older android boxes would run into same limitation. Also some might be able to play 1080p but have problem with 4K HEVC.
With current state of things you can either select to include or exclude HEVC in results, and to avoid issues with autoplay trying to play 1080p HEVC logical thing would be to exclude them, which will limit results.
So it would be great if an option could be added to select up to what quality HEVC to include SD/720p/1080p/4K

I'll have a think about this.
I also have a limitation of only 720p for HEVC. I get around that by setting max resolution to 720p for autoplay.

>Not related to the suggestion above, but so i dont start another thread i thought it would be best to ask here.
So Next Episodes takes very long time(about a minute or so) to load for me using Orange Pi PC2(bit faster that RPi 3B).
Is there a way that im not aware of to speed up that aspect?
I do have a lot of items in the list, more than 200, which i assume is the reason why it takes so long. Paginate helps speed up things considerably with Watchlist, but doesnt work in Next Episodes.
Edit:
In Progress TV Shows, while it does paginate doesnt seem to get any improvement from it, also takes very long time to load a page with even 4 items.

***Short Answer:***
Hide some (a lot) of your in progress shows. Your user case is the exact reason that feature is offered by Trakt.

***Long Answer:***
In order to provide the watched or in progress shows, I need an episode count from TMDb for each item in the list. I also need that information for each item *before* I paginate the list, otherwise there'll be pages that have only a fraction of the number of items specified in settings. Because of this, for watched and in progress shows there is not much speed benefit to paginating.
I could get around this by using info that Trakt supplies, but that would not be available to me if the user is using local indicators and not Trakt indicators. I also don't trust Trakt's data when using it for that type of info. Meaning I would need to maintain 2 separate methods for each function, which I'm not willing to do.
So, unfortunately, we return to the short answer being the only solution for underpowered devices.

**Comment by ReaLx3m** [comment]
> I'll have a think about this.
> I also have a limitation of only 720p for HEVC. I get around that by setting max resolution to 720p for autoplay.
Its an alternative all right, though still will limit available results. I opted for disabling HEVC and upping the file size to compensate a bit. Not that my connection cant handle it but its still a wasteful alternative. Hopefully you can think of something better to implement.  

> _**Short Answer:**_
> Hide some (a lot) of your in progress shows. Your user case is the exact reason that feature is offered by Trakt.

I thought of doing this, and actually started doing it, but it is a problem on its own too. Namely when i remove 1 show from the list i need to wait for a minute till it refreshes the list, and like that for every show you remove. I got anxiety after few :) and gave up. Maybe this list could be done in a way not to refresh every time you remove something, but have an OK button that would commit all the changes at once when youre done with deselecting shows? 

> _**Long Answer:**_
> In order to provide the watched or in progress shows, I need an episode count from TMDb for each item in the list. I also need that information for each item _before_ I paginate the list, otherwise there'll be pages that have only a fraction of the number of items specified in settings. Because of this, for watched and in progress shows there is not much speed benefit to paginating.
> I could get around this by using info that Trakt supplies, but that would not be available to me if the user is using local indicators and not Trakt indicators. I also don't trust Trakt's data when using it for that type of info. Meaning I would need to maintain 2 separate methods for each function, which I'm not willing to do.
> So, unfortunately, we return to the short answer being the only solution for underpowered devices.
I was thinking maybe using FEN as watched indicator would speed up things considerably, but not really clear on how that one works. When i switch to FEN next episodes is empty, is there a way to sync all my current watched/shows in progress/next episodes data from Trakt to FEN indicator?
When FEN is used as watched indicator, does it periodically sync with trakt so in case one needs to reinstall or switch box will still be able to have progress back?

**Comment by Tikipeter** [comment]
>I thought of doing this, and actually started doing it, but it is a problem on its own too. Namely when i remove 1 show from the list i need to wait for a minute till it refreshes the list, and like that for every show you remove. I got anxiety after few :) and gave up.

Best to use the Trakt website when you have multiple to hide. It really is your only answer, as having a list of 200+ on under powered hardware will be slow whether there's a call for meta or not. 

>Maybe this list could be done in a way not to refresh every time you remove something, but have an OK button that would commit all the changes at once when youre done with deselecting shows?

Maybe, but that would require a custom window or using Kodi's dialog window. Both of which are big changes. So not going to happen anytime soon.

>I was thinking maybe using FEN as watched indicator would speed up things considerably.

It won't speed things up at all.

>When i switch to FEN next episodes is empty, is there a way to sync all my current watched/shows in progress/next episodes data from Trakt to FEN indicator?

No. Then it would be using Trakt indicator information anyway. ;)

>When FEN is used as watched indicator, does it periodically sync with trakt so in case one needs to reinstall or switch box will still be able to have progress back?

Same answer as directly above.

Fen indicators are for people without a Trakt account. When something is watched in Fen, Fen will update it's database (locally) for that watched info. It's purely on a per-install basis, and has nothing to do with Trakt.

**Comment by ReaLx3m** [comment]
Oh riiiight, the trakt website :). I keep forgetting that it has more functionality than just activating trakt account in FEN. Will do some cleaning there, thanks for the reminder. And thanks for the clarification on the rest of my questions.

**Comment by Tikipeter** [comment]
Hide 195 of those 200+ and you'll be cooking. :) :)

**Comment by ReaLx3m** [comment]
Hahaha , or get a hobby that takes a minute at a time for those special moments :)

**Comment by ReaLx3m** [comment]
BTW heres an idea, build in some elevator music while that wheel is spinning, should make it more bearable :P :)

**Comment by Tikipeter** [comment]
![screenshot00001](https://user-images.githubusercontent.com/28930002/184247602-d7cfd474-9c80-4f6b-b2a6-72674445a921.png)

I'll limit the Next Episode Manager items to very basic info for next update (above). No metadata at all. Only title and current hidden status. Meaning the list will load quicker.

But you really still do need to go on the Trakt website if you're going to be handling many "hides".

**Comment by ReaLx3m** [comment]
Good to hear, but yes trakt website is the way to do it, and much more convenient. Doing some cleaning right now from there, and it turns out i had 600+ items in the list, poor poor Orange Pi :). Down to 340 now and loading time of Next Episodes of around 30 seconds. Turns out that even ended/cancelled shows that are in the list affect the performance, wast majority of what i removed were shows like that that i watched like 7 years ago.

**Comment by ReaLx3m** [comment]
BTW, riddle me this... What happens if i hide a show which ended for the time being and then new season/episode comes out, will it appear in next episodes on top if i have that option on?
Another scenario that comes to mind... if its hidden from next episodes, and then i access it through say trending and watch an episode, will it reappear in next episodes or remain hidden?

**Comment by xyzfre** [comment]
> Good to hear, but yes trakt website is the way to do it, and much more convenient. Doing some cleaning right now from there, and it turns out i had 600+ items in the list, poor poor Orange Pi :). Down to 340 now and loading time of Next Episodes of around 30 seconds. Turns out that even ended/cancelled shows that are in the list affect the performance, wast majority of what i removed were shows like that that i watched like 7 years ago.

This is interesting info never notice TV shows that have been canceled or ended years ago were ending up as progress,, I myself had a lot from years ago after reading this post I decided to delete or remove a bunch also improve the performance

**Comment by xyzfre** [comment]
Trakt.tv should change that if the TV show has been canceled or ended they should remove it from the progress automatically that would be great

**Comment by Tikipeter** [comment]
>Turns out that even ended/cancelled shows that are in the list affect the performance...

Absolutely they will. Every one of those 600 needed to make a call to TMDb for metadata, then see if there were any new episodes released. Big, big bottleneck.

>What happens if i hide a show which ended for the time being and then new season/episode comes out, will it appear in next episodes on top if i have that option on?

No. Any shows that you definitely want to watch you will need to leave un-hidden, or at least remember to unhide them when they are coming up to premiering again.

> if its hidden from next episodes, and then i access it through say trending and watch an episode, will it reappear in next episodes or remain hidden?

That will remain hidden also. The episode will be marked as watched of course, but the hidden status will remain the same.

>I decided to delete or remove a bunch also improve the performance

It's the best thing you can do to improve the performance of the In Progress TV Shows and Next Episodes. They are the 2 slower menus in Fen due to what you read above. Next update of Fen due for release soon will honor the "hidden" status within the "In Progress TV Shows", which it currently doesn't.

>Trakt.tv should change that if the TV show has been canceled or ended they should remove it from the progress automatically that would be great

Old fellas like myself still watch lots of ended and cancelled shows. :)

**Comment by Tikipeter** [comment]
In general, Trakt info is the biggest cause of slowdowns with Fen. If you have a huge amount of watched movies and episodes, it slows down the displaying of all media menus. I know Fen is pretty fast in general, but that is where the issue will be when people are suffering from a sluggish Movie or Show/Season/Episode menu in Fen.

If you have a largish Trakt watched list (400+ Movies/5000+ Episodes), for an experiment switch the Watched Indicator from "Trakt" to "Fen" and see the difference in opening up regular Trending/Popular etc lists. Even on my PC there is a difference, and that difference increases as the hardware power decreases.

**Comment by ReaLx3m** [comment]
> > Trakt.tv should change that if the TV show has been canceled or ended they should remove it from the progress automatically that would be great
> 
> Old fellas like myself still watch lots of ended and cancelled shows. :)

Add and 100% completed to that sentence.

Heres a thought on improving how FEN handles in progress and next episodes. If it would be possible maybe make it first check the completion status of a TV show before pulling episodes info, and if its at 100% then ignore that entry in the list. Should speed up things for plenty of people, and especially folks that have been using it for very long time with cluttered lists.
Is my logic sound, or am i missing something and a change like that could have some adverse effects?

**Comment by xyzfre** [comment]
> In general, Trakt info is the biggest cause of slowdowns with Fen. If you have a huge amount of watched movies and episodes, it slows down the displaying of all media menus. I know Fen is pretty fast in general, but that is where the issue will be when people are suffering from a sluggish Movie or Show/Season/Episode menu in Fen.
> 
> If you have a largish Trakt watched list (400+ Movies/5000+ Episodes), for an experiment switch the Watched Indicator from "Trakt" to "Fen" and see the difference in opening up regular Trending/Popular etc lists. Even on my PC there is a difference, and that difference increases as the hardware power decreases.

You’re absolutely right I decided to delete movies I watched years ago and keep deleting and speed performance has been getting better not that it was an issue ,,but specially deleting those old TV shows has made a major speed performance on next episodes now it opens in maybe 10 seconds or less using Nvidia Shield 2019 pro ,,really glad I came across this post thank you @Tikipeter and @ReaLx3m

**Comment by ReaLx3m** [comment]
We must not forget to also thank my underpowered Orange Pi :), this would have never come up without it. And to be honest it would never come to my mind that it could be an issue, also i imagine wast majority of kodi users will never think of doing this and silently suffer through the ages :), especially long time trakt users with android boxes or similar underpowered devices. 
On a fairly old i5 4690K its not really a problem. Considering the list filling speed so far, would probably take me another 10 years with my habbits to start noticing slowdowns :). Though improvement can still be noticed, got from about 6-7 seconds to around 3-4.

And as another positive outcome from this, i just learned about minisforum B550 mini PC by looking for some more powerfull htpc options. Now that is a beast that i doubt will need list cleaning anytime soon :).

**Comment by ReaLx3m** [comment]
@Tikipeter Got faced with one more issue with low powered devices and HEVC. If HEVC is excluded and no results are found with pre-set size and filters are ignored then it will sometimes autoplay a HEVC file thats beyond the capabilities of the device. So maybe excluding HEVC setting from "Ignore filters" would be the solution, or maybe when all filters are ignored autoplay gets disabled and takes you to source selection. What do you think?

**Comment by Tikipeter** [comment]
>or maybe when all filters are ignored autoplay gets disabled and takes you to source selection

That sounds like the way to go. Because people will have the same issue with the other specific filters like HDR, DV & AV1.

So if autoplay is enabled and no results are available using the filters, source selection will be returned instead of autoplay.
I'll sort that out for next update.

**Comment by ReaLx3m** [comment]
> So if autoplay is enabled and no results are available using the filters, source selection will be returned instead of autoplay.
> I'll sort that out for next update.

Hopefully it could be added as an additional option "Ignore all filters/ignore all filters and select source". As while for relatively proficient users would be simple to choose what to play, i can see parents/grandparents or friends that have no idea and you set the box for, clicking the first item in the list and trying to play a 4K Remux on a internet connection or hardware that cant support it.

**Comment by Tikipeter** [comment]
Back to the original request (extra HEVC quality filter). Next update you'll be able to select maximum quality for source select & autoplay results. They can be set the same or differently of course. The settings will show up when either "Include" or "Prefer (Autoplay)" are selected as the filter.

Using my own usercase as an example, I will set "Max. HEVC Quality" to 4K and "Max. Autoplay HEVC Quality" to 720p. I want to see ALL the results for source select, but only utilize 720p or less for Autoplay.

I was hesitant to do this because I wanted consistency in the filter settings, and I didn't feel there was any use in this type of setting for any of the HDR, DV or AV1 filters. But I think just having it for HEVC is OK, as there are instances like ours where software decoding can work up to a certain quality. I feel the other 3 filters are more of an all or nothing type proposition.

**Comment by ReaLx3m** [comment]
Yep, probably for the best, as even if there is some color shenanigans with the HDR nad DV on devices with no support for them, its pretty watchable and it gets you more results.
Would be great if you could consider also adding "Scrape with all filters ignored and select source" to the context menu "options>playback options". I feel it would be pretty usefull, as ive tried using it few times but it autoplaying if autoplay is enabled turned me off from it.
