### ISSUE TITLE
Backup Location

### ISSUE THREAD

**Issue by flhthemi** [Tikipeter/repository.tikipeter#200]
Ok you fixed the download locations...now I've discovered the SMB/NFS locations for making a Fen backup don't work. Might be the same issue as downloads.

Also, I tried several times to make Kodi crash while downloading and it appears Fen is solid as a rock in that aspect!! Again, great job, well done!

**Comment by Tikipeter** [comment]
Was there an error when it failed?

**Comment by flhthemi** [comment]
It didn't fail! DAUE (Dumb Ass User Error). If you select a backup folder and then try to do a backup, you get told to select a backup folder. If you select a backup folder and then click the OK button and return to the settings it will work because the setting isn't saved until you click OK. Duh..call me blond!

**Comment by Tikipeter** [comment]
Thank God it works, because I spent a couple of hours on it earlier and couldn't get it to work with a similar fix that I used for the downloads!
