### ISSUE TITLE
Playback failure

### ISSUE THREAD

**Issue by kyub** [Tikipeter/repository.tikipeter#200]
I just started to receive a playback failure (I think after the latest update). 

https://paste.kodi.tv/kinacolalu

**Comment by Tikipeter** [comment]
The log errors relate to a building of the next episode listitems, not a playback error, so you're going to have to explain to me what you are witnessing instead of just dumping a log here.

**Comment by kyub** [comment]
Sure thing. Apologies for not providing additional detail. I'm selecting any episode or any movie, then selecting any result. The 'playback failed' dialog appears.

![2_select_result](https://user-images.githubusercontent.com/3519111/227954800-84c96294-c1a4-412c-9ffc-f6e6df87b099.jpg)
![3_playback_failed](https://user-images.githubusercontent.com/3519111/227954836-5cc70194-64cc-4791-b827-8f93a645ff2b.jpg)

Here's another log https://paste.kodi.tv/sicoricipo

**Comment by xyzfre** [comment]
I had a similar issue yesterday with PM And I change the CDN in my PM account and the Play failed stop popping up

**Comment by kyub** [comment]
Strange but that worked. Thanks for the tip!
