### ISSUE TITLE
Unable to delete downloaded files

### ISSUE THREAD

**Issue by catsmonster** [Tikipeter/repository.tikipeter#201]
I have tried out the option of downloading a video file from the list of video files for a certain TV serie, and I found some major issues with it - which later forced me to have to factory reset my android TV.

So what happened was that I didn't have any file manager installed previous to trying out this feature, and I was unaware that this file would completely fill out my storage.
I was expecting to be shown a dialog message before the download starts to tell me where the file is going to be downloaded to/choose a download location, but only in hindsight found out it is set in the settings.
This is my bad, for not checking better, but could be nice to be told in advanced where it's going to download to, or at least prompt that the download location is set in the settings of fen.

Now the real issue was that after I started downloading, there was no way to cancel the download, and no indication that a download was actually happening in the background - until my TV started showing that it's running out of space, and even worse, there was no way to delete the file from within Fen (at least not an option that I could find).
So now since I didn't have any storage space left, my TV started acting in a weird way, not letting me access the internet anymore, so even if I could free up some space to download a file manager, I couldn't do it anymore, so I couldn't delete the file which was causing all of these issues - finally forcing me to delete Fen, (which didn't seem to solve the internet connectivity problem) and eventually forcing me to perform a complete factory reset and start over (which of course, fixed all the issues).

Now I admit that I was being careless when attempting to download the file without knowing I have enough storage left, but I just assumed when it would find out it doesn't have enough storage space it would just either cancel the download and delete the file, or at the very least that I would have the option to delete the file from within Fen or Kodi. 
As the feature stands now, if you don't have a file manager pre-installed, and if you don't have enough storage, this is a system breaking feature - one which requires a factory reset to fix

**Comment by Tikipeter** [comment]
Stopping Kodi will stop the download.

**Comment by Tikipeter** [comment]
>So what happened was that I didn't have any file manager installed previous to trying out this feature, and I was unaware that this file would completely fill out my storage.

Kodi has a built in File Manager.

>could be nice to be told in advanced where it's going to download to, or at least prompt that the download location is set in the settings of fen.

Every time? People can see that in the settings of Fen.

>no indication that a download was actually happening in the background

There's a notification at every 25% of download. It is assumed people will not forget they just started a download.

>there was no way to delete the file from within Fen

If you have Kodi set to "Allow file renaming and deletion" then you can delete downloaded files within Fen.

>I just assumed when it would find out it doesn't have enough storage space it would just either cancel the download and delete the file...

No

>or at the very least that I would have the option to delete the file from within Fen or Kodi.

Yes, see above.

>As the feature stands now, if you don't have a file manager pre-installed.........

If you have Kodi installed, you have a file manager installed. 

>.......and if you don't have enough storage, this is a system breaking feature - one which requires a factory reset to fix

The entirety of Kodi is a system breaking feature. Care must be taken when using it.
