### ISSUE TITLE
Fen Error can’t play movies or tv shows from library

### ISSUE THREAD

**Issue by jaimsitecom** [Tikipeter/repository.tikipeter#202]
Hi Tikipeter. After updating to latest version 1.6.18, I cannot play anymore any movie or tv show from the library. It’s the same FEN ERROR i reported as before, ‘FEN ERROR: cant play next item in playlist’. 

I dont use playlist queing so it’s a weird error at least for me. 

I had to revert back to 1.6.17 and it was good again. 

Anyways i am sending uyou the kodi log so you can check and verify. Thanks man!

https://mega.nz/file/hRhUUQoB#Wz0wOi0SbfDxxsjvhIwKHkDmY-UsQ1o3bv4tUHWsfeU

**Comment by ricinga666** [comment]
Yes, same here.  They will work through the Add-ons library option but not from within the Kodi library.

**Comment by Tikipeter** [comment]
Sorry all, oversight on my part. Next update will be soon with the fix, just have another issue to fix first...

**Comment by jaimsitecom** [comment]
Thanks Tikipeter! No prob. 1.6.17 works fine.
