### ISSUE TITLE
Auto scrape box video stutter

### ISSUE THREAD

**Issue by JFG1000** [Tikipeter/repository.tikipeter#202]
I've been noticing tonight there have been a slight video stutter when the auto scrape box appears, it could well be my eyes playing tricks but I think I managed to trigger it so grabbed a log

https://paste.kodi.tv/ofepirujuf

Nvidia Shield

Kodi 20.1

AH2 skin

Thanks mate

**Comment by Tikipeter** [comment]
Quite possible, especially if using the AH2 specific custom xmls.
