### ISSUE TITLE
Extra Window

### ISSUE THREAD

**Issue by unlimitedent713** [Tikipeter/repository.tikipeter#203]
Hi loving the addon been using since day 1 just wondering could u make widgets open straight into extras window only. im using a custom aeon nox skin and it dosent have that option ??

**Comment by SoulReaverFan** [comment]
> Hi loving the addon been using since day 1 just wondering could u make widgets open straight into extras window only. im using a custom aeon nox skin and it dosent have that option ??

This is already a feature in Fen Settings —> Features —> Open Fen Extras When Selecting —> Choose Both or TV Shows/Movies.

If you have that activated and click a Fen Widget it opens straight to the Extras window.

**Comment by unlimitedent713** [comment]
I get that but that also opens in all other views as well just asking for widgets only like titan binge mod, it might be just a skin setting and not addon setting

**Comment by unlimitedent713** [comment]
I have a custom window with all info on it but not widgets, would save a couple of clicks lol
![Screenshot_20230331_065831_Kodi](https://user-images.githubusercontent.com/36339060/229115009-a3320ca6-f382-43d2-9d5b-5e4d78ee7f82.jpg)
![Screenshot_20230331_065814_Kodi](https://user-images.githubusercontent.com/36339060/229115014-190c7518-88fb-4d3a-b415-55f004051dd6.jpg)

**Comment by Tikipeter** [comment]
Nah.
