### ISSUE TITLE
Configure Custom "TV Shows - Networks" Menu

### ISSUE THREAD

**Issue by TwilightMercy** [Tikipeter/repository.tikipeter#204]
Hi, is it possible to choose a specific list of Networks inside "TV Shows", as a different custom Fen menu?
I want to choose specific list and to use this list as widget menu for FENtastic skin.

To choose from:

![image](https://user-images.githubusercontent.com/29895680/229214042-3012ef04-4b25-4116-9de6-e5b09a202479.png)

**Comment by Ade-AV** [comment]
Is [this](https://www.reddit.com/r/Addons4Kodi/comments/11dq8ak/pro_tip_add_a_networks_widget_using_fen_and/) what you want?

**Comment by Tikipeter** [comment]
>Is [this](https://www.reddit.com/r/Addons4Kodi/comments/11dq8ak/pro_tip_add_a_networks_widget_using_fen_and/) what you want?

I would say so.

@TwilightMercy use Fen's Shortcut folders to make a directory filled with anything you like. Including only certain Networks.

There's an tip on how to do it in Tools->Fen Tips.

**Comment by TwilightMercy** [comment]
Yes, thanks.
