### ISSUE TITLE
Apple TV

### ISSUE THREAD

**Issue by socyboi** [Tikipeter/repository.tikipeter#205]
I am running Kodi 17.6 on my Apple TV and since the most recent update, nothing seems to be loading. When I open the addon, I just see a blank screen.

**Comment by Tikipeter** [comment]
What version number are you using please? I pushed an update (1.6.18a) that was supposed to fix this problem. BTW, it is a Kodi 17 problem, not an Apple TV problem.

**Comment by socyboi** [comment]
I just installed 1.6.8a and it loads up just fine. You are the best!
