### ISSUE TITLE
Playback Issues

### ISSUE THREAD

**Issue by Slicey750** [Tikipeter/repository.tikipeter#206]
Hey Tikipeter,

Great addon, thanks for all your work as I've really enjoyed it.  The past few days I've had playback issues, choppy videos along with errors when I stop the video.  I've tried a fresh kodi install but I encounter the same issues, my log is below, any ideas.
https://paste.kodi.tv/oduyiyanoq

**Comment by Tikipeter** [comment]
> any ideas.

Not really. I can see for some reason Fen tried to restart the search for sources again after finishing the movie. If there was choppy playback throughout, then it was possibly trying to do that during the movie as well. The reason for that I can't say.

Were you utilizing autoplay when this happened?

**Comment by Slicey750** [comment]
> > any ideas.
> 
> Not really. I can see for some reason Fen tried to restart the search for sources again after finishing the movie. If there was choppy playback throughout, then it was possibly trying to do that during the movie as well. The reason for that I can't say.
> 
> Were you utilizing autoplay when this happened?

Yes I have been using autoplay but when I take it off the same issues occur.  I would suspect its the reason for the choppy playback.

**Comment by Tikipeter** [comment]
How about the Folder Scrapers? Do you use those?

I would suggest as a test, you disable all internal scrapers and only leave the external scrapers, turn off autoplay and see if the issue persists.

If it does, go to Tools->Clear databases & Clean Settings Files and select "Clean Settings Files" and then select "Clear All Cache".

Whilst the log shows what is probably the cause of the problem, it is not showing WHY the problem is happening. If, at the end of playback, there is a notification with a script error notice for Fen, a log including that could be helpful.

**Comment by Slicey750** [comment]
> How about the Folder Scrapers? Do you use those?
> 
> I would suggest as a test, you disable all internal scrapers and only leave the external scrapers, turn off autoplay and see if the issue persists.
> 
> If it does, go to Tools->Clear databases & Clean Settings Files and select "Clean Settings Files" and then select "Clear All Cache".
> 
> Whilst the log shows what is probably the cause of the problem, it is not showing WHY the problem is happening. If, at the end of playback, there is a notification with a script error notice for Fen, a log including that could be helpful.

Ok I'll give this a try, I'm a bit skeptical because I believe I only have external scrapers enabled and I have tried to clear my settings.  I'll try it in this order and let you know if the issue persists.

**Comment by Slicey750** [comment]
> > How about the Folder Scrapers? Do you use those?
> > I would suggest as a test, you disable all internal scrapers and only leave the external scrapers, turn off autoplay and see if the issue persists.
> > If it does, go to Tools->Clear databases & Clean Settings Files and select "Clean Settings Files" and then select "Clear All Cache".
> > Whilst the log shows what is probably the cause of the problem, it is not showing WHY the problem is happening. If, at the end of playback, there is a notification with a script error notice for Fen, a log including that could be helpful.
> 
> Ok I'll give this a try, I'm a bit skeptical because I believe I only have external scrapers enabled and I have tried to clear my settings. I'll try it in this order and let you know if the issue persists.

Looks like the issue still persists.  Here is a log

https://paste.kodi.tv/oxikofidoj

**Comment by Tikipeter** [comment]
Unfortunately, the logs don't really show anything.

I'm going to re-include a couple of "pauses" I had in script at various spots in the code that I took out very recently for the next update (v.1.6.20). Kodi sometimes chokes if you don't put little sleep commands here and there. Hopefully, that is what the problem is.

After the update, please turn **OFF** the following settings and then test playback:

* Settings->Playback->**Autoplay Next Episode**
* Settings->Playback->**Autoplay First Relevant Result**
* Also make sure all **Internal Scrapers** are turned **OFF**.

**Comment by Slicey750** [comment]
> Unfortunately, the logs don't really show anything.
> 
> I'm going to re-include a couple of "pauses" I had in script at various spots in the code that I took out very recently for the next update (v.1.6.20). Kodi sometimes chokes if you don't put little sleep commands here and there. Hopefully, that is what the problem is.
> 
> After the update, please turn **OFF** the following settings and then test playback:
> 
> * Settings->Playback->**Autoplay Next Episode**
> * Settings->Playback->**Autoplay First Relevant Result**
> * Also make sure all **Internal Scrapers** are turned **OFF**.

Thanks will do, it certainly appears to be connected to a recent update as I have a backup with version 17 that runs smoothly without this issue.  Thanks for all your work.

**Comment by Tinuz97** [comment]
> Unfortunately, the logs don't really show anything.
> 
> I'm going to re-include a couple of "pauses" I had in script at various spots in the code that I took out very recently for the next update (v.1.6.20). Kodi sometimes chokes if you don't put little sleep commands here and there. Hopefully, that is what the problem is.
> 
> After the update, please turn **OFF** the following settings and then test playback:
> 
> * Settings->Playback->**Autoplay Next Episode**
> * Settings->Playback->**Autoplay First Relevant Result**
> * Also make sure all **Internal Scrapers** are turned **OFF**.

Is it me, or is scraping faster also (the percentage etc goes faster), i like this update.

**Comment by Slicey750** [comment]
Thanks for the update.  Unfortunately I'm still having the same issue (log below).  I'm using 18.6 via Libreelec, got another setup using OSMC and I'm going to try with that one.

http://ix.io/2lxY

**Comment by Slicey750** [comment]
Works perfectly with my OSMC setup, nothing with the addon, there is something with my libreelec setup, I'll turn it and start from scratch.  Thanks for your help, this is a great addon.

**Comment by Slicey750** [comment]
Just in case someone else come across this.  The issue can be rectified in Kodi settings, in Settings-Media Settings-Videos-Default Select Action if show information is selected this creates the issue where Fen searches for another video to play if you stop the movie or the movie finishes, changing that to play solved the issue.  Choppy playback was rectified by adjusting the player settings.  Thanks again for your help.

**Comment by Tikipeter** [comment]
Good to hear you got it sorted. I would have never thought of that as the reason for the issues.
