### ISSUE TITLE
Fen Translation to Hebrew

### ISSUE THREAD

**Issue by TwilightMercy** [Tikipeter/repository.tikipeter#207]
Hi,

I was wondering if you have the intention to support extra languages/**Hebrew** specifically for Fen? (for Menus mostly, I think Settings should always be English).
I can provide help with menu translations if needed.

For now, as "workaround", I use Shortcuts Menu and manually translate the menu items to Hebrew. **example:**

**Genres - English:**
![image](https://user-images.githubusercontent.com/29895680/229627892-3e78b057-d0ab-4ae7-a665-4acb63709579.png)

**Genres - Hebrew:**
![image](https://user-images.githubusercontent.com/29895680/229627918-32a716a6-46d8-4e9d-b63b-f365b2f75767.png)

Thank you very much for the good work!

**Comment by Tikipeter** [comment]
No plans for translations on this iteration of Fen.
