### ISSUE TITLE
Enhancement: Filter out HEVC

### ISSUE THREAD

**Issue by akuiraz86** [Tikipeter/repository.tikipeter#209]
Could you please implement an option to remove HEVC videos?  I have a Raspberry Pi 3b running OSMC and anytime it tries play a video encoded with HEVC (x265 / h265) the audio plays but the video is a blank black screen.  It looks like Seren, Venom & TheCrew all have this implemented already... I really prefer Fen to any other addon but lately these video types are playing more and more.  Thanks

**Comment by Tikipeter** [comment]
Do you mean for autoplay?
