### ISSUE TITLE
Support for Stremio Addons

### ISSUE THREAD

**Issue by I-Do-Ketamine** [Tikipeter/repository.tikipeter#21]
Would it be possible to add Stremio addons support to Fen? The idea is that a person can add several Stremio addons to use along with Fen.

**Comment by Tikipeter** [comment]
I have absolutely no idea what you are talking about....

**Comment by PodTT** [comment]
Stremio addons are extensions for another app(https://stremio.com). Fen uses torrentio as a source for torrents but stremio addons also support http streams. I was wondering if support for them was possible.

**Comment by I-Do-Ketamine** [comment]
Stremio addons are extensions for another app(https://stremio.com). Fen uses torrentio as a source for torrents but stremio addons also support http streams. I was wondering if support for them was possible.

**Comment by Tikipeter** [comment]
Oh, I see. Cocoscrapers doesn't use the stremio "addon". It just has a scraper that accesses the same data that the stremio extension accesses.

As for whether other data from other Stremio extensions could be accessed? Doubtful for Cocoscrapers as hoster links are generally frowned upon these days.

But you could ask the Cocoscrapers dev and see if he's interested. I have no hand in any external scrapers.
