### ISSUE TITLE
loading when cant open scraper

### ISSUE THREAD

**Issue by cabban** [Tikipeter/repository.tikipeter#21]
i have also one issu, its when tap a scraper to stream, nothing happen is there not working, so only spins the wheel, :) but thats it :) then after that sometimes all kodi crashes, but för now addon 8 of 10 :)

**Comment by Tikipeter** [comment]
I'm keeping an eye on this. I think it's to do with RD's recent issues. Restart Kodi and/or turn off cached torrents only when it happens. That should fix it.

**Comment by cabban** [comment]
> 
> 
> I'm keeping an eye on this. I think it's to do with RD's recent issues. Restart Kodi and/or turn off cached torrents only when it happens. That should fix it.

HOW TO TURN OFF CACHED TORRENTS-- :) ?

**Comment by Tikipeter** [comment]
Settings->Search->Cached Torrents Only (right near bottom of settings), or when browsing media in Fen: context menu->Options->Show Only Cached Torrents - switch to OFF.

**Comment by Tikipeter** [comment]
I haven't seen this happen in a while, so I'm going to close this for now.

I will keep an eye on it, however.
