### ISSUE TITLE
Autoplay Next Episode.

### ISSUE THREAD

**Issue by jigoop1** [Tikipeter/repository.tikipeter#210]
hi @ tikipeter
 since 1.6.21 update Autoplay Next Episode not playing. is that me only or other have same problem too? p

**Comment by Tikipeter** [comment]
There's something going on. Let me look into it.

**Comment by Tikipeter** [comment]
This will be fixed for next update (v.1.6.21c).

**Comment by jigoop1** [comment]
thanks a lot. it working great.
