### ISSUE TITLE
Ratings missing on TV shows season level using AH 2

### ISSUE THREAD

**Issue by xyzfre** [Tikipeter/repository.tikipeter#210]
Ratings show up for TV shows but after clicking on a TV show bringing up season level  Ratings show up blank This happens on home screen widgets and within Fen, episode ratings work perfect, using Trakt I don't use library, Windows 11 Pro K20.1

**Comment by xyzfre** [comment]
https://user-images.githubusercontent.com/49699869/231274921-b7f03e9a-72c3-4c47-8aec-618f478cf5ca.MOV

**Comment by Tikipeter** [comment]
I have no idea what he's doing with his skin at the moment.

If it wants a season specific tmdb id it's not getting one from Fen.

**Comment by umbrellaplug** [comment]
These new requirements are getting old fast.

**Comment by Tikipeter** [comment]
Yep. Real fast.

Haven't touched Fen for a week. Bit over it all at the moment.

Got stacked widgets on Fenstraury though. So that was fun to do. :)

**Comment by adamosborne83** [comment]
Sorry to jump in, but, have you tried different Views? Just as you can see below. All ok with mine, and episodes shows different ratings. 
Again, this just shows its more of a Jurial thing, but, worth a try.

https://imgur.com/a/kZ87nSv

**Comment by xyzfre** [comment]
Interesting with the different views on my end Info screen ,TV show level and episodes, ratings work perfect👌🏼 but on Season level poster view They show up blank with Fen

**Comment by ivarbrandt** [comment]
I'm don't think this behavior is Fen related.

This used to happen all the time to me back when I used AH2. I found that different updates to TMDb Helper sometimes fixed the ratings for some shows at the season and episode levels but it also broke other shows. It was very hit and miss. 

This is why I don't think it has anything to do with Fen.

**Comment by xyzfre** [comment]
I agree I'm sure it's probably a skin behavior was just putting it out there to see if something can be done but if not no worries Fen works AMAZING💯 Been using Fen for about four years,Thank you @Tikipeter I'm always grateful for all the hard work and dedication that goes into Fen

**Comment by xyzfre** [comment]
> I don't think this behavior is Fen related.
> 
> 
> 
> This used to happen all the time to me back when I used AH2. I found that different updates to TMDb Helper sometimes fixed the ratings for some shows at the season and episode levels but it also broke other shows. It was very hit and miss. 
> 
> 
> 
> This is why I don't think it has anything to do with Fen.

I just noticed in your video you're using Umbrella add-on I checked with Umbrella and for some reason on TV show season level ratings do work with Umbrella

**Comment by xyzfre** [comment]
> Sorry to jump in, but, have you tried different Views? Just as you can see below. All ok with mine, and episodes shows different ratings. 
> Again, this just shows its more of a Jurial thing, but, worth a try.
> 
> https://imgur.com/a/kZ87nSv

I just noticed in your video you're using Umbrella add-on I checked with Umbrella and for some reason on TV show season level ratings do work with Umbrella

**Comment by adamosborne83** [comment]
> > Sorry to jump in, but, have you tried different Views? Just as you can see below. All ok with mine, and episodes shows different ratings. 
> > Again, this just shows its more of a Jurial thing, but, worth a try.
> > 
> > https://imgur.com/a/kZ87nSv
> 
> I just noticed in your video you're using Umbrella add-on I checked with Umbrella and for some reason on TV show season level ratings do work with Umbrella 

Tbf mate, I'd stick with Fen....... Umbrella Dev is a bit, well ummmmmmmmm.... haha....
Anyway, at least you know it's AH2 issue anyway, it will be some way Jurial has changed look up etc... I know Umbrella Author and I had a convo months ago about this sort of thing.... for example, unaired episodes (i use red writing) will only show in certain views otherwise the writing stays normal etc etc. More effort for Addon Authors, to keep changing their addons code to match Jurials.

**Comment by xyzfre** [comment]
There's nothing out there that can take me away from using Fen😎

**Comment by Tikipeter** [comment]
Fixed for next update.

**Comment by xyzfre** [comment]
Thank you 💯 @Tikipeter it's working perfect now.
