### ISSUE TITLE
fen stuck on firestick (Multiple devices 4k, firetv, etc)

### ISSUE THREAD

**Issue by medievil1** [Tikipeter/repository.tikipeter#211]
tv/xxx show/xxxx season, select an episode and it goes to working and stays there....like it is hung up tryign to do something in the background....I closed it, switched to a different plug in and 20 min later got the popup, preparing sources...happened since last night cause it was fine yesterday

**Comment by Tikipeter** [comment]
Since the problem you are having is not happening on any device I use, I have absolutely no way of trying to debug what might be happening with your setup.

If you provide a log from when this happened, perhaps there will be something in there that can point me in the right direction.

**Comment by medievil1** [comment]
not sure I have a way to get the log off the firestick...I did look at it and a lot of errors were showing stuff like :
Error retrieving from thetvdb.com : HTTP Error 401:Unauthorized
These 2 are together
>Error: CAddon[plugin.video.fen]: failed to load addon settings from special://profile/addon_data/plugin.video.fen/settings.xml
Error:Previous line repeats 55 times<
Error: Exception thrown (PYthonToCppException) : -->Python callback/script returned the following error<--
Error type <class 'sqlite3.OperationalError'>
Error Contents: database is locked

**Comment by medievil1** [comment]
ahhh found a way to retrieve it 
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/4641830/kodi.log)

**Comment by Tikipeter** [comment]
Good job with getting the log. :)

I don't know why it's happened, but it looks like the "ext_providers3.db" database might be corrupt. In saying that, you also seem to have some troubles with Kodi reading Fen's settings, as well as other problems.

Anyway, hopefully to fix your problem with Fen, it is enough to delete the "ext_providers3.db" from Fen's userdata folder, with an ending location of "userdata/addon_data/plugin.video.fen". You can use Kodi built-in File Manager to navigate there. Delete that file, restart Kodi (I'd restart the whole device) and hopefully those errors will go away.

The generic location for android userdata, according to Kodi Wiki, is:

> Android/data/org.xbmc.kodi/files/.kodi/userdata

Failing that, I'd uninstall Fen altogether, selecting to delete all add-on data when Kodi asks you to, then re-install and see if that fixes your issue.

**Comment by medievil1** [comment]
didn't work(deleting file), Uninstall/reinstall, at least on this one did, though now menu items are no longer there (like search history)
 I can understand it happening to one, but all 3?? and they are all with the last 3 or 4 month installs, we certainly didn't do anything to them...

**Comment by medievil1** [comment]
another update, it did NOT work on the firetv...still spinning after an uninstall, reboot, reinstall....(no search history so I know it did wipe everything) and on the first firestick, though it worked, it is slow... a good 2 min or more to pull up links after it has sourced them... 2 different versions of kodi too... the tv has 18.5 the firestick has 18.6... my next step is to try undating kodi on the tv...

**Comment by Tikipeter** [comment]
I wouldn't worry updating Kodi on the TV just for this problem. It won't be related.

I'll upload a test version for you to try in a few minutes. I will put it in with my repository address as a zip file.

This means, you will need to go to Addons->Install from Zip file within Kodi, and select the Tikipeter Repo address you made when installing my repo originally. The file will be in there along with the repo file. Select the test version of Fen (plugin.video.fen-test01) to install, restart the device, and test if it works.

**Comment by Tikipeter** [comment]
OK. I have uploaded the test file (plugin.video.fen-1.6.21d-test01.zip).

Please test at your convenience and let me know if it fixes the problem.

**Comment by medievil1** [comment]
no change on the firetv, still just spins (About 20-30 min later it will eventually popup preparing sources, or that was the previous behavior)
Firestick was already kinda working still slow to get to preparing sources though

**Comment by Tikipeter** [comment]
OK. Thanks for testing. There's two other things I can change, which I'll do now and upload a new test file. It will have 'test02' at the end of the filename in the Tikipeter Repo source.

**Comment by Tikipeter** [comment]
New version up for testing (plugin.video.fen-1.6.21e-test02).

Please navigate to Fen's userdata folder and delete the "ext_providers3.db" again before testing (as described above).

I'll be away from home for 10 or more hours after I post this, so there is no hurry for testing. Just write back the result and I'll read it when I get a chance. :)

**Comment by medievil1** [comment]
ok, deleted file, rebooted kodi, installed #2 and it is working on the firetv...
So what ever change that was seems to have done the trick...
so much appreciated!!
err.. while I am here.. any chance of search history coming back?? it is the only menu item I miss cause I used it frequently... I looked about adding it (Through the edit thing, but the edit stuff seemed more tailored to just moving stuff around and not adding or removing main menu items  (Gotta bee able to click on  it to remove or add basically

**Comment by Tikipeter** [comment]
Good job medievil1! Glad it's working, and thanks for helping out with the tests. The next 'official' version will have these changes.

As for the Search History, it is now only found in Main Menu (Root)->Search. There's history for Movies, TV Shows and People.

If you mean there isn't history anymore in the particular Movie and TV Show menus, they were removed from there a while ago when installing a new version of Fen. You will need to make a shortcut to the history item now.

So go to Main Menu->Search->HISTORY Movie Search, bring up context menu and select 'Add to a Menu'. Give it the name you want, choose the Movies menu, and choose it's position in the movie menu list. Do the same for the TV Show Search History item, making a shortcut to the TV Show menu.

I'm afraid you have lost your previous search histories though, as we needed to clear your userdata.

Let me know if you have any issues.

**Comment by medievil1** [comment]
>go to Main Menu->Search->HISTORY Movie Search, bring up context menu and select 'Add to a Menu'. Give it the name you want, choose the Movies menu, and choose it's position in the movie menu list. Do the same for the TV Show Search History item, making a shortcut to the TV Show menu< Perfect...exactly what I wanted...
