### ISSUE TITLE
[Enhancement Request] Choose Custom color for RD results, even when based on quality

### ISSUE THREAD

**Issue by TwilightMercy** [Tikipeter/repository.tikipeter#211]
Hi,

**I'm using the current settings for my RD authorization in FEN:**
![image](https://user-images.githubusercontent.com/29895680/231379859-16b4a45c-999f-4a29-a78b-e0e08ba96403.png)

**And for "Results" settings, I like the sort by Quality then size, and different color for each quality:**
![image](https://user-images.githubusercontent.com/29895680/231380143-111cbc93-6951-478c-bf9f-7c56aba4bb0e.png)

**And when a torrent shows up from my RD Cloud, it does always show up on top, but of course stays with the same color of the quality, as configured:**
![image](https://user-images.githubusercontent.com/29895680/231381203-5a2637fa-df40-4102-8456-e68c04145951.png)

Is it possible to add setting to configure different color specific for RD Cloud results, to work even with "Highlight results based on quality"?
So it will be easier to identify RD cloud results.

Thanks for the good work!

**Comment by Tikipeter** [comment]
No
