### ISSUE TITLE
Kodi hangs at shutdown Fen 1.6.22

### ISSUE THREAD

**Issue by flhthemi** [Tikipeter/repository.tikipeter#212]
A. With this update I had to rebuild my Trakt lists I have located on my root menu in Fen. Just info for some that might be having trakt/Fen problem.

B. I noticed that kodi now takes a long....long time to exit on Windows. 

From my log file:
"2020-05-19 16:04:16.126 T:4248   ERROR: CPythonInvoker(6, C:\Users\Steve\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\services.py): script didn't stop in 5 seconds - let's kill it"

Attached kodi.log. If you want a debug log it's no problem.
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/4652876/kodi.log)

**Comment by Tikipeter** [comment]
I'll push a fix for hang on shutdown. Unfortunately, "xbmc.abortRequested" will be deprecated by next update, so I switched Fen to using "xbmc.Monitor().abortRequested()", which doesn't seem to work at all.
