### ISSUE TITLE
[Option Request] AutoHide Screen elements when playing trailers via Extras

### ISSUE THREAD

**Issue by Nuklear92** [Tikipeter/repository.tikipeter#212]
As the title says, an option or perhaps an internal auto hide of the elements shown in the screen during a playback of any trailer via FEN Extras. As you see in the screenshot below, those elements stay persistent on display all the time when a trailer is playing making it a bit distracting, specially when you're watching in a dark room without lights and you want full attention to the trailer itself without any sort of UI elements on screen.

![image](https://user-images.githubusercontent.com/76958541/232539467-04008692-4521-4ad7-bee6-8b6928be8e8c.png)

**Comment by Tikipeter** [comment]
Done.

Display for 2(?) seconds at start of playback or no?

**Comment by Nuklear92** [comment]
> Done.
> 
> 
> 
> Display for 2(?) seconds at start of playback or no?

Awesome, yeah that's fine 2 seconds is good or even 4 secs which is the default Auto Hide OSD setting for Kodi's Estuary skin. Either is good as long as it auto hides, hehe! 😜
