### ISSUE TITLE
[REQUEST] Add landscape artwork from fanart.tv for movie sets

### ISSUE THREAD

**Issue by ivarbrandt** [Tikipeter/repository.tikipeter#214]
Hey man! Hope all is well with you.

I really like the '**TRAKT COLLECTION:** Movie Sets' feature you implemented awhile back and I find myself using it quite a bit.

The default artwork for landscape seems to be pulling backdrops from TMDb. Could you please change it so that the default is pulling the landscape artwork from fanart.tv? They are called 'Movie Thumbs' on the fanart.tv website. Here's an example:

https://fanart.tv/movie/86311/the-avengers-collection/?section=thumb

The reason that I am requesting this is because the landscape artwork from fanart.tv looks like actual artwork vs just fanart from TMDb. Fanart is usually the fallback artwork when the main artwork is missing. Plus, this will breathe new life into the displaying of movie sets as the artwork from fanart.tv is cleeeean.

Let me know what you think. Thanks for your time.

**Comment by Tikipeter** [comment]
Howdy mate
. :)

I see a point where I am not assigning a `thumb` value ( landscape for movies) within Fen's collections code.

If your aim here is to have the collection listitems display exactly as the movie list items currently do, then me adding a landscape value for `thumb` should make that happen.

Then the views `WideWall`, `WideInfoWall` & `WideList` should display the landscape art when available...

![screenshot00002](https://user-images.githubusercontent.com/28930002/233214931-6509b643-db9f-49f6-ab55-d6d6a681b3dd.png)
![screenshot00001](https://user-images.githubusercontent.com/28930002/233214941-ff6b4e38-6dc6-4132-a43f-b13549a50235.png)
![screenshot00000](https://user-images.githubusercontent.com/28930002/233214948-2a1bf224-d504-4c09-8cb7-bf9178574073.png)

**Comment by Tikipeter** [comment]
BTW, always keep an eye on my old Fenstruary skin, I've added some widget making features that I can help you implement if you have any interest.

I've got custom category widgets (so any amount can be placed anywhere in the widget list) as well as implementing a stacked widget option underneath any of the category widgets made.

Our skins have a fair few differences now, so it wouldn't be entirely trivial to port over any changes, but I'd be willing to give it a shot whenever you might see something you like.

Just let me know with a new issue here  if you ever see something you might like to implement in FENtastic, and I'll help out.

**Comment by ivarbrandt** [comment]
> If your aim here is to have the collection listitems display exactly as the movie list items currently do

Yes, this is exactly my aim. Thank you for implementing this. It looks beautiful! 

I just took a look at the changes you've made to your skin and oh wow! The stacked widgets are awesome! And sooo fast! I also love that you kept the option to have normal category widgets. I'm definitely going to have to apply some of these features to my skin. Absolute 🔥 !

> Just let me know with a new issue here if you ever see something you might like to implement in FENtastic, and I'll help out.

Thank you so much for your offer. I'll be taking you up on it soon. I look forward to learning more from you.
