### ISSUE TITLE
Fen Real Debrid streams

### ISSUE THREAD

**Issue by naezzo** [Tikipeter/repository.tikipeter#215]
The addon Fen (only), will pull torrent streams, but not Real Debrid streams. The end result shows no streams. I have revoked Real Debrid authorization, uninstalled Fen, reinstalled, closed the build and reopened,  with the same results. 

![20230420_071053](https://user-images.githubusercontent.com/131394215/233445549-6b8cf4b3-63ba-4ddc-aead-5f91169584df.jpg)
![20230420_071039](https://user-images.githubusercontent.com/131394215/233445554-46a3c4ce-a5a9-4bf1-add3-eafe144b8226.jpg)
![20230420_071024](https://user-images.githubusercontent.com/131394215/233445559-fcce7203-4bc0-455e-98d4-b290d74985f3.jpg)
![20230420_070913](https://user-images.githubusercontent.com/131394215/233445563-b230a84e-2ec5-4eb2-bad1-022feb1290bb.jpg)
![20230419_224641](https://user-images.githubusercontent.com/131394215/233445565-811a37cc-aca0-47ce-9759-07fd5852ff8e.jpg)
![20230419_224632](https://user-images.githubusercontent.com/131394215/233445571-7053587d-23e3-4193-8757-6cf9b952e091.jpg)
![20230419_224601](https://user-images.githubusercontent.com/131394215/233445573-0f0620c9-b752-4feb-81ad-48b91ceea660.jpg)
![20230419_224457](https://user-images.githubusercontent.com/131394215/233445575-7a400b0c-77c7-4ac8-8d28-0fa7e1efbfa1.jpg)
![20230419_224436](https://user-images.githubusercontent.com/131394215/233445578-a07aaaac-2aa3-44bb-82a5-e33378a4aab5.jpg)
![20230419_224320](https://user-images.githubusercontent.com/131394215/233445580-f35a1e4b-3c7c-4db6-8f33-3d02364eae60.jpg)

**Comment by xyzfre** [comment]
What device are you using? What version of Kodi? And which skin and a log would help

**Comment by naezzo** [comment]
> What device are you using? What version of Kodi? And which skin and a log would help

**Comment by naezzo** [comment]
New Firecube, Kodi 19.5, Xenon 1.9

**Comment by xyzfre** [comment]
Unfortunately you're using a build and these are the rules for Fen it's right there on GitHub ![image](https://user-images.githubusercontent.com/49699869/233477072-d833cbc5-e698-4f08-80d6-0ad825d639ac.jpeg)
