### ISSUE TITLE
[Question] Getting video_path parameter - Before Playback

### ISSUE THREAD

**Issue by TwilightMercy** [Tikipeter/repository.tikipeter#216]
Hi Tiki,

I'm workin on implementing into Fen a feature to search for Hebrew subtitles right when picking a movie/episode,
And then displaying if subtitle match found for each source in sources list (`sources_results.xml` window).

In addition, it shows the percentage match between the subtitle name and then source file name. (from external sources e.g. Real Debrid).

Most of my code is ready, adding example screenshot of how it looks like:

**The translation from Hebrew to English is:**
TOP Line:
**`104 Results | 39 Subtitles Found | 20 Sources with 85% and above match to subtitles`**

And in each matching source line the addition is:
**`SUBTITLE: 97% Match To Subtitle [<website_name>]`**

![image](https://user-images.githubusercontent.com/29895680/233774444-a5274cba-3bae-4dc9-8865-1ab6f2c789ee.png)

This is my additional code workflow:

1. **When picking a movie/episode in FEN, the code in `plugin.video.fen/resources/lib/scrapers/external.py`:**

* Sends the metadata parameters `(self.media_type, self.title, self.season, self.episode, self.year, self.tmdb_id)` to extenal function that searches for Hebrew subtitles in Israeli subtitles websites.
* The subtitle names found are written into `userdata/addon_data/plugin.video.fen/databases/subs.db` (Custom .db file I added)
Example screenshot from subs.db for found subtitles: (SQLite Browser)
![image](https://user-images.githubusercontent.com/29895680/233778294-bfe97a20-c0ce-4942-99da-4265bf8661a9.png)

----------------------------------------------------------------------------------------------
2. **Then, the code in `plugin.video.fen/resources/lib/windows/sources.py`:**
* The subtitle are read from subs.db into a list.
* inside `def builder(results)` function, under the for loop: `for count, item in enumerate(results, 1)`:
For each source, I check the if it matches to any of the subtitles in the subtitles list. If so, setting the properties with the "Match found" text + Top line text. (as in the example screenshot)

----------------------------------------------------------------------------------------------
At first, to compare between the found subtitles and the source name in FEN results in `sources.py`, I used the variable:
`name = get('display_name')`

But then I saw the name I get is in UPPERCASE and after some string cleaning, as written here in `external.py`:
`display_name = clean_file_name(normalize(i['name'].replace('html', ' ').replace('+', ' ').replace('-', ' ')))`

So I added the original `i['name']` as a variable called `original_name` into the results, so I can use the original name before cleaning to check subtitle matching. **Example value for original_name:**
`original_name = "Top.Gun.Maverick.2022.2160p.WEB-DL.DDP5.1.Atmos.HDR.HEVC-CMRG[TGx]"`

----------------------------------------------------------------------------------------------
It works perfect on movies! 
But In some old TV shows, the source name is too general and not episode specific which makes the subtitles matching harder.
Example from South Park Season 01 Episode 01:
```
original_name = "South.Park.S01.1080p.Bluray.AV1.Opus.AV1D"
display_name = "SOUTH PARK S01 1080P BLURAY AVI1 OPUS AV1D"
```

When the video itself plays in Kodi, using xbmc.Player().getPlayingFile() the actual file name is:
`xbmc.Player().getPlayingFile() # "South.Park.S01E04.Big.Gay.Al's.Big.Gay.Boat.Ride.1080p.Bluray.AV1.Opus.AV1D"`

----------------------------------------------------------------------------------------------
I saw the code in FEN: `plugin.video.fen/resources/lib/modules/player.py` that sets the two possible names:
1. The `original_name` variable I use:
```
	# Value: "South.Park.S01.1080p.Bluray.AV1.Opus.AV1D"
	def set_playback_properties(self):
			if self.playing_filename: set_property('subs.player_filename', self.playing_filename)
```

2. The actual playing file name:
```
		# Value: "South.Park.S01E04.Big.Gay.Al's.Big.Gay.Boat.Ride.1080p.Bluray.AV1.Opus.AV1D"
		def _searched_subs():
			try: video_path = self.getPlayingFile()
			except: video_path = ''
			if '|' in video_path: video_path = video_path.split('|')[0]
			video_path = os.path.basename(video_path)
```

----------------------------------------------------------------------------------------------
My question, is it possible to access the `video_path` variable (which represents the actual playing file name, which helps in TV shows), from `external.py / sources.py` / any file code BEFORE the playback? Does it exist in the source object in addition to ‘name’?
 to be able to use it in the sources window.

Thanks for everything!

**Comment by Tikipeter** [comment]
No, that episode name info will not be available when you want it to be. That will only become available after you have chosen a source, If the result isa single episode torrent, it would be OK. But if it is a PACK torrent, then the filename of the video file will not be known until the PACK is resolved and the correct episode is chosen for playback.

**Comment by TwilightMercy** [comment]
> No, that episode name info will not be available when you want it to be. That will only become available after you have chosen a source, If the result isa single episode torrent, it would be OK. But if it is a PACK torrent, then the filename of the video file will not be known until the PACK is resolved and the correct episode is chosen for playback.

That's what I thought. that it is available only in playback. dam I guess.. : )
