### ISSUE TITLE
Update Kodi Library after Subscription Update

### ISSUE THREAD

**Issue by jigoop1** [Tikipeter/repository.tikipeter#216]
@Tikipeter 
is that 

> Update Kodi Library after Subscription Update

option in setting suppose to update watch episode in kodi library?. if so then it is not updating in kodi library the same. but in fen with kodi library menu item it updating watch episode.
can u pl look in to this.

**Comment by Tikipeter** [comment]
That setting is not for that. It is to trigger an update (scan) of the Kodi library after Fen updates Subscriptions.

The setting to mark a library item as watched is Settings->General->Watched Indicators->**Set Resumed/Watched in Kodi Library if Watched in Fen**.

I haven't used library integration for a long time, so let me know if that setting doesn't work properly.

**Comment by jigoop1** [comment]
@Tikipeter 
i also just started using library integration to test on network drive for centralized fen "TVShow Subscriptions". 
that setting also true in my setting but still not marking watch. btw does that setting mark watch on other device too? means watch on one device and update all other device with same setup.

**Comment by Tikipeter** [comment]
I just added a show to Kodi library from library integration and it marked as watched when I finished playing it.

Unfortunately, there is no way for Fen to mark an item as watched in any other Kodi library other than the one that played that episode. If you use Trakt, you can get that behavior by using the trakt addon to manage your library items watched status. You would share the subs folder as you are doing now, and install the trakt addon on each machine and tell the trakt addon to sync the watched statuses.

Once you get into sharing a source on multiple machines, you are going to need the "official" trakt addon to handle that sort of thing, or look down the route of setting up and using a mysql database.

Are you sure library integration (Suubscriptions) is your best option? Are you using it mainly to speed up widgets/browsing?

**Comment by jigoop1** [comment]
I was trying to speed up widget/browsing. btw i have set up trakt with fen but not trakt addon. but you are correct i will going to setting up mysql db. that may be the best way. thanks you for your help and superb addon. 
on side note i have notice you [https://github.com/123Venom/plugin.video.venom/issues/58#issuecomment-633929124](url) 
if you need futurize --stage2 code for openscraper. 
i you need the copy of that which i was testing? here is the link [https://github.com/jigoop1/testing/blob/master/script.module.openscrapers-1.0.001.zip?raw=true](url)

**Comment by Tikipeter** [comment]
Thanks for that link jigppo1.

I was thinking it might be best to avoid using futures for the conversion, as it adds more imports. It will be good to check out though.
