### ISSUE TITLE
[Enhancement] Sort DV and HDR links at the top of Source Select list

### ISSUE THREAD

**Issue by ShibajiCh** [Tikipeter/repository.tikipeter#22]
Hi @Tikipeter,

This is an enhancement request for Fen so I'm not including any log. Is it possible to add an option in Fen to sort all DV and HDR links at the top of Source Select list as I use them the most and need to search them through the list when auto play is not on? I know there's already existing options under auto play to prefer them but I want to choose the links myself. Preferably DV links should be at the top followed by HDR links. I guess many others like me will be benefited by this. Kindly let me know if this is possible.

Thanks and Regards,
ShibajiCh.

**Comment by JFG1000** [comment]
This wound actually be a brilliant feature, would it not mess up the file size sorting though?

**Comment by ShibajiCh** [comment]
> This wound actually be a brilliant feature, would it not mess up the file size sorting though?

@JFG1000, I agree with you... The file size and quality sorting needs to be kept along with the DV and HDR sorting. Otherwise it won't be useful. I'm sure @Tikipeter will be able to implement them together.

**Comment by Tikipeter** [comment]
>I'm sure @Tikipeter will be able to implement them together.

Unfortunately to achieve this successfully will require a full re-write of the sorting and filtering code. So at the moment it is not possible to achieve adequately.

You can currently use the "Filter Results" (in the context menu) feature within the Source Select window to filter displayed results after they have been returned. If you filter by "Extra Info" and then select DV and HDR, the window will only display results that match that filter.

Unfortunately that's as good as it's going to get until I have the time to re-write the sort/filter code.

**Comment by ShibajiCh** [comment]
> > I'm sure @Tikipeter will be able to implement them together.
> 
> Unfortunately to achieve this successfully will require a full re-write of the sorting and filtering code. So at the moment it is not possible to achieve adequately.
> 
> You can currently use the "Filter Results" (in the context menu) feature within the Source Select window to filter displayed results after they have been returned. If you filter by "Extra Info" and then select DV and HDR, the window will only display results that match that filter.
> 
> Unfortunately that's as good as it's going to get until I have the time to re-write the sort/filter code.

Fine @Tikipeter. Thank you!

Thanks and Regards,
ShibajiCh.

**Comment by JFG1000** [comment]
No worries @Tikipeter many thanks for your hard work
