### ISSUE TITLE
Movies/tv search doesnt open search box...

### ISSUE THREAD

**Issue by jaimsitecom** [Tikipeter/repository.tikipeter#220]
Instead they open a different page (some kind of list of tv/movies)

**Comment by Tikipeter** [comment]
I did change things in this area last update, but I can't replicate this issue.
Are you selecting search from within Fen, or have you made a 'shortcut' to it somehow with a skin? If you are using a 'shortcut', it will no longer work with the changes made last update.

**Comment by jaimsitecom** [comment]
Not a shortcut.  It is inside FEN-Movies-Search. I even did a restore movies menu to default but still no searchbox. It seem to list down and populate the page from trakt info.... then it list down movies (new movie titles?).

**Comment by Tikipeter** [comment]
Damn. I forgot I left a 'Search' menu item in Movies/TV Shows. I will push an update soon to fix these, as the search function changed.

You will need to bring up context menu on 'Search' and select Edit->Reload 'Search' after the update, and then search will work again. Do this for both the Movie and TV Show menu Search items.

**Comment by jaimsitecom** [comment]
Thanks Tikipeter!

**Comment by Tikipeter** [comment]
I have just pushed an update (v.1.6.25a) to fix this. It may take a bit to come through on Kodi, as I had just pushed an update for tikimeta a half hour earlier.

Apologies for this. I always 'remove' the Search items from Movies/TV Shows for my setup, so really I forgot they were still there and needed editing with the changes to search.

**Comment by jaimsitecom** [comment]
Not a problem at all. Thanks so much again!
