### ISSUE TITLE
Feature Request: Select Source; Default Container Color Change

### ISSUE THREAD

**Issue by Bhav1111** [Tikipeter/repository.tikipeter#220]
Feature Requests:

1. add “select source” to context menu. —Only rescrape & select source is an option. 

2. Change default background from Gray to Black —
In widgets for movies the background becomes fanart. When not clicked or viewing a different widget with Fen settings the default background color is Gray.

**Comment by Tikipeter** [comment]
1. Rescrape & Select Source provides the same function.
2. You have not explained this very well. Unless you mean simply changing Fen's default fanart image to black (not going to happen), then I don't know what you are trying to explain here.

**Comment by Bhav1111** [comment]
> 

1. But it doesn’t do the same function. A source select is half the function and therefore quicker. It was available on other addons so would be nice to have if not too much trouble. 

2. Sorry. maybe it is the default fanart I’m referencing. Is the default color a dull gray? 
It’s just an eye sore on my all black build. 

Otherwise, Fen works flawlessly and I can’t thank you enough for your time and work. Even if you are a little short fused, haha ;)

**Comment by Tikipeter** [comment]
1. Explain the situation where you want to use it.
2. You could replace the addon's fanart with a black image if you wanted.

**Comment by Bhav1111** [comment]
1. I have a newborn so I constantly have to shut down Kodi by asking google assistant to start a YouTube baby sensory video. So I end up constantly having to restart whatever it is I am watching while he’s sleeping. Seeing the whole rescrape screen load every time seems redundant as with a copy of your addon - ezra - it was an available feature. So I have built an experience with source select that even after months of Fen working flawlessly it seems to be lacking and bugging me. 

2. Which setting changes the default fanart for the addon itself? I have a widget if Fem settings for example that defaults gray in the background. The skin doesn’t offer to change the addon background. There’s a fen logo on the gray background so it’s def the addon. 

I don’t want to push this but since you asked me to explain I figured I’d be as frank as can be. I can live with it. Lol.

**Comment by Tikipeter** [comment]
1. Source Select will not change the behavior you think it will change. The scrape screen will still show. Just re-select the movie/episode like you did the first time. The results are cached so the screen will not stay for long. There was no fullscreen scrape progress screen when Ezra was forked, so there's no value in comparing. There was certainly no "Select Source" feature in Ezra as you're claiming though.
2. There is no setting to change the default addon fanart. You would have to change the image within the folder yourself. And also you would have to do that after every update.

**Comment by Bhav1111** [comment]
Got it!
