### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by No-Dot7369** [Tikipeter/repository.tikipeter#222]
My first time posting. I hope I am making this request in the right area.  Tikipeter can you please add  Networks to the Movie section, currently it is only in the TV area.

**Comment by Tikipeter** [comment]
Like TMDbHelper's Movies->"Providers"?

**Comment by No-Dot7369** [comment]
Yes Please

**Comment by TwilightMercy** [comment]
https://github.com/Tikipeter/repository.tikipeter/issues/123

**Comment by Tikipeter** [comment]
Well, kinda. You both asked for the wrong thing really. This Issue and yours were both asking for Movie "Networks". To which I assumed in your case "Production Companies". Of which there are thousands. Of which I could never make a list of for Fen.

The difference here is I had more context about what was actually being asked for from the a4k subreddit, where this info was given:
>The only reason I use it is that one section of my widgets is for streaming movies(Providers) Tmdb has a Provider movie section Fen does not Fen only has Providers(Newtowrks) listed under Tv

So I had a chance to see what was really being asked of from TMDbHelper. Turns out there's around 170 of these, so it can be done.

**Comment by No-Dot7369** [comment]
Thanks, sorry I should have explained it like I did in the  a4k subreddit. I am the one that posted that in the a4k subreddit

**Comment by Tikipeter** [comment]
It's cool. I was just explaining why I didn't entertain the request before, but now am.

**Comment by No-Dot7369** [comment]
Thanks your hard work on the best addon in my opinion is much appreciated

**Comment by TwilightMercy** [comment]
Great to hear thanks for the enhancement!
Will you call in Fen menu - Movies —> Providers, or “Networks”? (I suggest “Networks” to keep same syntax with TV Shows —> Networks menu)

**Comment by xyzfre** [comment]
This is a great enhancement another widget to add to my skin movie networks sounds great💯

**Comment by Tikipeter** [comment]
I didn't say I'd do it. :)

**Comment by No-Dot7369** [comment]
Please :)

**Comment by Tikipeter** [comment]
Done for next update.

You will need to navigate into the Movies menu, then context menu: Edit Menu->Check if Movies Menu has new Menu item. Then add "Networks" where you want it in the list. If that fails, select Restore Movies menu to Default.

**Comment by xyzfre** [comment]
Thank you @Tikipeter❣️

**Comment by No-Dot7369** [comment]
Thank you Tikipeter!!!

**Comment by TwilightMercy** [comment]
Thank you very much for adding movies by networks!

I installed latest test FEN version, and most of the lists working great, but for some of the networks I get the same movie list for all of them:
![image](https://user-images.githubusercontent.com/29895680/236322203-602b3a05-fa3a-434e-a476-07bee0df3a80.jpeg)

**Comment by Tikipeter** [comment]
Bound to happen.

**Comment by No-Dot7369** [comment]
Thanks once again Tikipeter

**Comment by No-Dot7369** [comment]
> Done for next update.
> 
> You will need to navigate into the Movies menu, then context menu: Edit Menu->Check if Movies Menu has new Menu item. Then add "Networks" where you want it in the list. If that fails, select Restore Movies menu to Default.

I navigated to movie menu but it still has the same list. How do I get to the contet menu to edit from movie menu?

**Comment by TwilightMercy** [comment]
> > Done for next update.
> > You will need to navigate into the Movies menu, then context menu: Edit Menu->Check if Movies Menu has new Menu item. Then add "Networks" where you want it in the list. If that fails, select Restore Movies menu to Default.
> 
> I navigated to movie menu but it still has the same list. How do I get to the contet menu to edit from movie menu?

Right/long click

**Comment by No-Dot7369** [comment]
I went to choose widget>addon>videoaddons>Fen>movies>Right/long click and nothing happens..,,Sorry I have never done this before can you give the exact steps

**Comment by xyzfre** [comment]
https://github.com/Tikipeter/repository.tikipeter/assets/49699869/7100bb37-4a50-4455-8211-a75764a6cf05

**Comment by xyzfre** [comment]
My apologies for the crappy video from my phone lol

**Comment by xyzfre** [comment]
![image](https://github.com/Tikipeter/repository.tikipeter/assets/49699869/8a077244-a13a-40c9-af3f-fc93b266ac81)

**Comment by xyzfre** [comment]
![image](https://github.com/Tikipeter/repository.tikipeter/assets/49699869/91c9f8e0-51ff-482d-9f99-c9456ad84d5c)

**Comment by No-Dot7369** [comment]
Thank you very much xyzfire. That made it alot easier for me to understand

**Comment by xyzfre** [comment]
Your welcome @No-Dot7369 enjoy ,love Fen just noticed something myself looking at this picture that I can add a Trakt list to the movie menu
