### ISSUE TITLE
My trait lists

### ISSUE THREAD

**Issue by ricinga666** [Tikipeter/repository.tikipeter#222]
Hi Peter.

Is there an issue with "my trakt lists" at the minute.  Im getting an error everytime.  But I can get to watchlist and subscriptions appear to work.    I can't upload a proper log at the minute but I've tried to take a photo  of the error

#
![15910484974771178298846569533385](https://user-images.githubusercontent.com/58446154/83458793-0456d480-a45b-11ea-8cc8-15107b350a81.jpg)

**Comment by Tikipeter** [comment]
The change to Trakt lists was introduced in Fen version 1.6.19 (Fen is now at 1.6.25). The instructions on making sure this error didn't happen were in the changelog for that update.
I will post them again for you below:

```
[COLOR dodgerblue][B]Version 1.6.19[/B][/COLOR]
- Big change to menus with this update. Main (Root), Movies and TV Shows menus have had their content changed. Because Fen uses dynamic lists that can be changed by the user, these changes will not happen automatically. You will need to reset each of these menus manually. For people who have adjusted their menus to their liking, my apologies as you will have to reset these and make them again. Please see Fen Tips' "Edit Main Menus" for details on how to reset your menus.
- IMDb Watchlist and user lists now supported. Found in new main menu item "My Lists". This is also where Trakt lists will now be found. The lists are broken into movie or tvshow sections, as IMDb does not have an always accurate way of determining media type when fetching the full list without using filters. All Trakt Lists continue to support both movie and tv show items appearing in the same list.
- Enter your IMDb user ID in Settings->Accounts->IMDb. You should enter your ID without the leading "ur". The IMDb lists should, however, still work if you forget to remove the "ur" from the start of your user ID.
- Added extra caching to Folder Scrapers.
- Other code changes.
```
To fix:
* Navigate to the Main Menu (Root)
* Context Menu->Edit
* Select "Restore Root Menu to Default
* "My Trakt Lists" will now be called "My Lists" (4th from bottom). Your Trakt lists are in there.

Unless you want issues with the Movies and TV Shows menus, repeat steps 1-3 for them as well.
