### ISSUE TITLE
[Feature request] Trakt lists as a custom search path

### ISSUE THREAD

**Issue by rizreflects** [Tikipeter/repository.tikipeter#223]
Hey Peter, hope you're doing well. 

I was wondering whether it would be possible to add trakt lists as a custom search patch, similar to how movies and TV shows work. That way for example I could search '90s movies' directly through Arctic horizons search menu. The addon would ideally search through the users personal and liked lists, and then show the relevant list without the need for any additional clicks.

Do you think its possible to implement a feature like this? Thanks a lot for your time.

**Comment by Tikipeter** [comment]
Not really possible. Trakt doesn't have such a feature as far as I know.

You can search all trakt lists with `plugin://plugin.video.fen/?mode=get_search_term&search_type=trakt_lists`. That will return a list of Trakt lists related to your search term, but they won't be only your personal/liked lists, they will be all public lists.

**Comment by rizreflects** [comment]
Ah fair enough, I had a feeling it wouldn't be possible but thought I'd double check with you. Thanks anyway and keep up the good work.
