### ISSUE TITLE
V1.6.26 recurring Search issue

### ISSUE THREAD

**Issue by UPRHome** [Tikipeter/repository.tikipeter#223]
Similar to two versions ago, the Search function is not working within Movies and TV Shows menus. Unable to perform previous fix of accessing context menu at search and reload search (V1.6.25a was working fine)

**Comment by Tikipeter** [comment]
It looks like I do need to fix the 'refresh' function, but there's no reason Search should have broken again.
Try:
* From Movies/TV Shows menus: context menu->"Edit"
* "Restore [Moives/TV Shows] Menu to Default.

That should fix the issue. If not:
* Go to your userdata folder, navigate into plugin.video.fen, delete the "navigator.db".
* Restart Kodi.
