### ISSUE TITLE
Popular People menu item not showing up in root.

### ISSUE THREAD

**Issue by jigoop1** [Tikipeter/repository.tikipeter#224]
@Tikipeter 
hi,
to reproduce this issue you need to reset root menu to default ,then 'Popular People menu item' shows up in root but then get out of fen and then open again fen the item is not visible. i thinks that 
in 'def build_main_list(self, list_items):' 
line # 472
'if self.is_widget and not isFolder: continue' comment out it then items show up.
but i do not know unintended consequence of that. so can you please look in to this.
thanks.

**Comment by Tikipeter** [comment]
Working fine for me.

**Comment by xyzfre** [comment]
https://github.com/Tikipeter/repository.tikipeter/assets/49699869/0e78760e-40f8-44d7-bbe9-336c4a5775d5

**Comment by xyzfre** [comment]
I was reading this post and I checked experiencing the same behavior ,I'm on v21 alpha Omega I didn't notice when this started happening

**Comment by Tikipeter** [comment]
Try entering another addon and then navigate back into Fen. Is it still missing?

**Comment by xyzfre** [comment]
I found a work around ,Edit menu and add Popular People To a Different Menu list ,like TV shows or Movies

**Comment by xyzfre** [comment]
![image](https://github.com/Tikipeter/repository.tikipeter/assets/49699869/6c8c81a8-d2c3-46c5-90f7-9f63813dd757) Movie list

**Comment by Tikipeter** [comment]
Nope. Can't make it happen. Works fine with Popular People always in the Root menu for me.

**Comment by Tikipeter** [comment]
You don't use General->"Use Custom Skin XMLs When Available?

An entire set of xml's are available for AH2.

**Comment by xyzfre** [comment]
> You don't use General->"Use Custom Skin XMLs When Available?
> 
> 
> 
> An entire set of xml's are available for AH2.

Should I be using this feature to correct this issue?

**Comment by Tikipeter** [comment]
Not to fix this issue, no.

I just noticed you're using the AH2 skin. Thought you might use the AH2 themed xmls for Fen. Makes Fen's custom windows look more like AH2 windows.

**Comment by xyzfre** [comment]
I love Fen The way it is and it's custom windows you've done a AMAZING job💯

**Comment by Tikipeter** [comment]
You're always too nice.

They do look good though. Try them out one day if you get bored. :)

**Comment by Tikipeter** [comment]
Someone try using Estuary and see if this happens.  I installed AH2 on Kodi 20 and couldn't get this to happen. I then installed Kodi 21 and could not get this to happen then either.

**Comment by jigoop1** [comment]
@Tikipeter 
hi
sorry for late response, i re installed fen but it still not showing Popular People menu item in root
btw on kodi 20.1, win10 and skin.aeon.nox.silvo , if it help.
and yeah entering another addon and then navigate back into Fen. it is still missing.
i try to log it @ that line actually external_browse() return None instead of plugin.video.fen second time when get back to Fen. i think kodi acting up

**Comment by xyzfre** [comment]
In the current test version v3.1.09d Popular People is working correctly now👍🏼
