### ISSUE TITLE
Meta module

### ISSUE THREAD

**Issue by djdirty60** [Tikipeter/repository.tikipeter#225]
from the last update the meta module is no longer good, if you have it on dutch he will only look for the films that have the dutch information at themoviedb, and no longer with the english what he did before. so I have to switch it back to english to find all the movies. can this be solved? thank you in advance

**Comment by Tikipeter** [comment]
I'll fix it now. Update will be 1.1.47a.

**Comment by djdirty60** [comment]
Thnx 👍👍👍
