### ISSUE TITLE
Trakt Collection no longer in Alphabetical order

### ISSUE THREAD

**Issue by ANHBOB** [Tikipeter/repository.tikipeter#226]
After updating Fen to 1.7.01 it changed the Trakt TV Collection order from Alphabetical to random order. Any way to change it back without going back to previous version?

**Comment by Tinuz97** [comment]
I can confirm this @Tikipeter.

**Comment by Tikipeter** [comment]
There looks to be something going on with the metadata. When I switched languages, I see TV Shows with no title. The other metadata is there, but not the title.

I still had them in alphabetical order, though, so I don't know what's going on with that. I'm hoping the 2 issues are related.

**Comment by Tikipeter** [comment]
Can someone switch to English in tikimeta and see if the collection is alphabetical then?

Also, is Collections Movies still alphabetical?

**Comment by Tinuz97** [comment]
Meta set to English (interface Dutch).
Wiped cache. 

Movies and TV shows still random afterwards.

**Comment by Tikipeter** [comment]
OK. I'm barking up the wrong tree with the metadata for this issue. I'll come back to it later.

I'll have to go searching around the code, because it's not doing it for me...

**Comment by Tikipeter** [comment]
I'm going to leave a test build here. Can someone suffering from this problem please install it and see if it fixes the issue? Thanks if you can.

http://s000.tinyupload.com/index.php?file_id=03119271625817478024

**Comment by djdirty60** [comment]
For me it's fix now

**Comment by Tinuz97** [comment]
I'm not at home now, in a hour, so I report asap.

**Comment by Tinuz97** [comment]
No idea what you did exactly, but it is fixed for me also @Tikipeter 🏆

**Comment by Tikipeter** [comment]
I'll push an update, because that test file had other things broken in it that I was half way through changing.
