### ISSUE TITLE
Haven't been getting Furk results for months, help please

### ISSUE THREAD

**Issue by JBM05** [Tikipeter/repository.tikipeter#226]
Hello all!  Ever since Furk went down months ago, I have not been getting any furk results.  Easynew is working just fine.  I checked the log and I found this error:

2023-05-12 10:22:51.129 T:17900   ERROR <general>: C:\Users\JBM\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.furk.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
                                                     warnings.warn(

But I don't know what is going on.  I have tried TV shows and Movies....Easynews works, furk doesn't.  Any help would be appreciated . Thanks!

[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/11465141/kodi.log)

**Comment by Tikipeter** [comment]
I no longer have a Furk account, so you're going to have to help me help you by providing as much information as you can.

Do any actions within Fen work with Furk? Can you access your Account Info? Your Video Files? Can you make a search of Furk from within the My Services Furk menu?

Install Umbrella and enter your Furk details into Cocoscrapers. Then test that. Does Umbrella (via Cocoscrapers) yield results for Furk?

Can you use Furk through it's website with full utility?

**Comment by JBM05** [comment]
Let see if I can answer some your questions.  I have SALTS as well and easynews works, but not furk.  It is having the same problem.
> Do any actions within Fen work with Furk?
No results at all.  And it times out almost instantly.  Almost like it can't log in
>   Can you access your Account Info?
Yes
> Your Video Files?
I don't have any, I use it exclusively for streaming
>  Can you make a search of Furk from within the My Services Furk menu?
Yes.  I did a search for Deadpool, I got 3 results, 2 were Deadpool 2 and one was untitled.

When I did the same search from the Fen menu, I got all easynews streams, and no furk results.  Time out instantly.
> Install Umbrella and enter your Furk details into Cocoscrapers. Then test that. Does Umbrella (via Cocoscrapers) yield results for Furk?
I tried salts, same results.  I will try umbrella when I get a second
> Can you use Furk through it's website with full utility?
Yes, it seems so.  When I did a search for Deadpool on furks site I got over 8700 results.  Is it possible they changed their API and that is problem?

Thanks for your help.  And let me know if you want a furk account to test things out.

—
Jason B Monette
Owner
JBM Automation, LLC

269.350.4471 (Office)
269.217.4473 (Cell)
***@***.***

https://JBMAutomation.com
On May 14, 2023 at 6:25 PM -0400, Tikipeter ***@***.***>, wrote:
	I no longer have a Furk account, so you're going to have to help me help you by providing as much information as you can.

**Comment by Tikipeter** [comment]
Try to play something after searching for it in the My Services Furk menu. Does it play?

Please provide a log after playback/playback failed.

**Comment by JBM05** [comment]
That is what I am thinking as well.  Furk isn't answering support requests and I'm a reseller for them.  Not sure what other options are out there that were as good as furk used to be.  If you know of any that work with Fen, please let me know!

Tikipeter, let us know if it is a problem server side or hopefully just an API change.  Thanks!

**Comment by Tikipeter** [comment]
Unfortunately it is not an API change. I'm going to run straight http (no s) requests to them with the next update. Apart from that, Furk might be dead. I have seen it come back from the ashes many times before though.

I was a member of Furk for maybe 9 years before giving it up this year. The reason I started using it was because it was the only way to access "packs" of tv shows in those days. Regular scrapers only accessed hoster links.

That has all changed now. With a basic RD subscription, you have access to cached torrent packs, and the addons within Kodi to utilize that.

Also, the need for RSS feeding is pretty much gone too as far as I can see. The debrid services have a vast cache of torrents cached. Way, way more than Furk has. If you want the new episode of a show with certain specific parameters, you're going to likely find it using a debrid service. Particularly RD.

If there's nothing I can do to solve this, and it looks like there isn't, then your hand may be forced anyway.

**Comment by JBM05** [comment]
Does real debrid work with Fen?  I was under the understanding that Fen was designed to use furk and easynews.

Thanks

**Comment by JBM05** [comment]
Ok cool.  Hopefully the furk issues will work themselves out.  But I will get RD set up as a fall back

**Comment by JBM05** [comment]
Ok, I signed up for Real-Debrid.  Got the 6 month premium plan.  Enabled and Authorized it in Fen.  Not getting any results.  Is there something I am missing?

**Comment by JBM05** [comment]
It seems to be only searching furk and easynews, real debrid.  I'm sure I am missing a setting or something.  But for the life of me, I can not find it.

When I click  a show/movie.....I can see it say easynews and furk, but no Real Debrid

**Comment by xyzfre** [comment]
Did you try clearing the scraper cache in tools or all cache

**Comment by JBM05** [comment]
> Did you try clearing the scraper cache in tools or all cache

I did, I will try again....stand by

**Comment by JBM05** [comment]
Cleared all cache....still only easy news results.  Is there another place I have to enable the Real-Debrid scraper?  If I go to the context menu, it only shows furk and easy news as external scrapers.

**Comment by JBM05** [comment]
Ok interesting find.  If I enable the coco scraper option, the real debrid results show up....if I disable it...they go away.

**Comment by adamosborne83** [comment]
> Ok interesting find.  If I enable the coco scraper option, the real debrid results show up....if I disable it...they go away.   

CoCo scrapers is the scraper package so therefore must be enabled.  Fen itself does not scrape these.

**Comment by JBM05** [comment]
> > Ok interesting find.  If I enable the coco scraper option, the real debrid results show up....if I disable it...they go away.
> 
> CoCo scrapers is the scraper package so therefore must be enabled. Fen itself does not scrape these.

Got it.  That should be added to the setup guide if it's not there already.  I'm not the only one who was scratching their head trying to get the RD results to show up.

Thanks everyone for all the help.  I'm hoping Furk will rise from the ashes again.....but RD seems to be a better resource for the time being.
