### ISSUE TITLE
Idea (Improvement)

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#227]
I was curious what section is used to 'finish_early' the scraping (if enabled).

i did found these:

						if finish_early == 'true' and percent >= 50:
							if len(alive_threads) <= 5: close_dialog = False; break
							if len(self.sources) >= 100 * len(alive_threads): close_dialog = False; break

Could you make a section in the settings (under the finish_early switch as a example) with 2 sliders, so people can up or down the percent and the minimum sources?

So a slider for if finish_early and if len(self.sources) .

No idea what alive treads is?

**Comment by Tikipeter** [comment]
Interesting idea. Let me think it over.
Something where you can set the minimum amount of scrapers left and the minimum amount of scraper time left as to when the scrape finishes early. Is that right?

**Comment by Tinuz97** [comment]
Minimum finish early slider (percent), and a minimum found sources slider (so just like it does work in that code, but with sliders).

Now it does standard stop at 50%, if a minimum of 100 sources reaches, correct?

And what does the alive_threads code?

**Comment by Tikipeter** [comment]
> Now it does standard stop at 50%, if a minimum of 100 sources reaches, correct?

Almost. It checks for one of 2 things:
* Stop the search if the scrape is at least 50% and there are 5 or less scrapers remaining.
* Stop the search if the scrape is at least 50% and the amount of results found is at least 100x the amount of scrapers remaining. i.e. if scrape is past 50% and there are 8 scrapers remaining and 910 results already, it will stop. But if there are 8 scrapers remaining and only 300 results it will continue.

The `alive_threads` tells us how many scrapers (they run in threads) are still alive i.e. they haven't returned a result or a 'no result' yest.

**Comment by Tikipeter** [comment]
There's been quite substantial changes to the importing code of the external scrapers lately. Are you having new issues?

**Comment by Tinuz97** [comment]
Nope, working fine at the moment, but I like tweaking lol 😊

**Comment by Tikipeter** [comment]
Ah, I see! It can only be a good thing being interested and looking through code.

I'm thinking about your suggestion. It's not really ideal as it is.

**Comment by xyzfre** [comment]
With this current update Fen is scraping like a beast super fast you have done an amazing job my friend keep up the GREAT work

**Comment by ANHBOB** [comment]
Just wanted to say thank you for all the hard work you have done Tikipeter, and Tinuz for helping out to make Fen the best addon there is.  It is truly unique. 
Usually I get good results after scraping, but some older show I'm trying to watch (NYPD Blue) I get no results found.  When this happens I use Shadow and get results. Not sure how Shadow can find things Fen can not.

**Comment by Tikipeter** [comment]
> ...Not sure how Shadow can find things Fen can not.

Different scrapers. Fen uses Openscrapers, Shadow does not.

**Comment by ANHBOB** [comment]
Thank you for the response, and thanks for fixing Fen so it shows the titles in order now.

**Comment by Tikipeter** [comment]
@Tinuz97 

This will be done next update. You will need to turn on stop search early, and then turn OFF "Use Default Stop Early Settings" to then set your own settings for Percent, Remaining Scrapers, Total Results. You can set each of these individually, or leave them at 0 to turn that filter off.

There are 4 new settings strings if you would like to translate them:
1. Use Default Stop Early Settings
2. Stop Early if Percentage of Scrape Time Equals (0=Off)
3. Stop Early if Remaining Scrapers Equals (0=Off)
4. Stop Early if Total Results Equals (0=Off)

Always appreciated. 🥇

**Comment by Tinuz97** [comment]
1. Gebruik Standaard Instellingen 'Stop Zoeken Vroegtijdig'
2. Stop Vroegtijdig als Percentage van de Scrape Tijd Gelijk is aan (0=Uit)
3. Stop Vroegtijdig als Resterende Scrapers Gelijk Is Aan  (0=Uit)
4.  Stop Vroegtijdig als Totale Resultaat Gelijk Is Aan (0=Uit)

**Comment by Tinuz97** [comment]
no idea if 'Stop Zoeken Vroegtijdig' is a issue, without ' it is weird to read @Tikipeter

**Comment by Tikipeter** [comment]
> no idea if 'Stop Zoeken Vroegtijdig' is a issue, without ' it is weird to read

From past experience, it should be fine. I'll pop them in and see if there's an issue.
Thanks Tinuz. 🙂🙂

**Comment by xyzfre** [comment]
One thing I noticed with the last update not having no issues just curious to know ,,when it is scraping providers I noticed sometimes it blinks for example + 25 but the numbers are colored in red

**Comment by Tinuz97** [comment]
I think, that those are 'failing' scrapers (says my logic, no idea if I am correct).

**Comment by xyzfre** [comment]
Make sense ,so you see them on your end as well? Appreciate any feedback

**Comment by Tinuz97** [comment]
Yes, I see the red ones also sometimes.

**Comment by Tikipeter** [comment]
@xyzfre @Tinuz97 

That is due to the changes in how Fen imports all the scrapers.

Previously (and on all Exodus forks) Fen would import ALL the scrapers before showing the progress dialog and starting the scrape. That is why there was a pause (sometimes a large one on under powered devices) before the dialog would show and scraping would start.

Now Fen imports the scrapers _on the fly_, meaning the dialog will show and scraping will start from the moment the first scrapers are imported. The redness and + are when more scrapers are being imported once the scrape has started.

You won't see it much if your device is fast. Probably only for a few seconds at the start of the scrape. Slower devices can see the total scrapers number going up, and hence the red and +, for sometimes 10 seconds or more during the scrape. But in that time, the already loaded scrapers are looking for results.

Fen then has a formula for adding a little bit of extra time to the scrape whenever scrapers are loaded after the initial batch are loaded.

It's all done so that the dialog and the scraping can start as soon as possible.

**Comment by xyzfre** [comment]
Definitely works GREAT I only see it for maybe 2 or 3 seconds tops ,,using Nvidia Shield  it’s scrapes so fast now 👍🏼👍🏼
