### ISSUE TITLE
Downloading cached packs

### ISSUE THREAD

**Issue by moongato** [Tikipeter/repository.tikipeter#228]
Until recently, when I selected "download Pack" and go to select the files to download, the complete list of files were unchecked for download and I would just choose the ones I needed. Now when I try to do it, ALL the files are checked for download and I have to uncheck the files I don't need. It's not a problem for a single season pack but it is a major problem if it is from a multi season pack when I just need a single or partial season. I literally have to uncheck 100's of files to get 1 season of Burn Notice. Is there a way to change the default back to unchecked? I could not find anything in settings to address this.

**Comment by TwilightMercy** [comment]
https://github.com/Tikipeter/repository.tikipeter/issues/221

**Comment by Tikipeter** [comment]
I'll add a Select All/Deselect All button and leave them deselected by default.
