### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by pcliff069** [Tikipeter/repository.tikipeter#228]
I was wondering where (which menu) I can find sorting.since the last update my TV lists appear in random order.

**Comment by djdirty60** [comment]
Update 1.7.02a fix that

**Comment by pcliff069** [comment]
Is supposed to fix that?
Seeing it's not available yet.

**Comment by djdirty60** [comment]
![15923982153568646092302650396509](https://user-images.githubusercontent.com/13561831/84900089-ea97cd00-b0a9-11ea-9356-f58bf1347438.jpg)

**Comment by Tikipeter** [comment]
Hi @pcliff069  

djdirty60 is right. This was fixed with 1.7.02a. If it is not showing for update through Kodi, you may have to grab the zip file from here and download it. Or wait for it to show in Kodi.

**Comment by pcliff069** [comment]
Thanks for the response.

**Comment by pcliff069** [comment]
Interesting.
I have two versions of Kodi. One on my Google TV - all Fen is up to date, on my Fire Stick 4K it is not and the up to date versions are not in the repository - .01 the latest.
The only difference I can see between the Kodis is on the Google TV it is the .7 version - on the FS4K it is .6
I will try and upgrade the Fire Stick version. (which can be a pain).

**Comment by Tikipeter** [comment]
I'll be away for several hours, but write back here if you don't get the update on the stick and i will add a link on the github.io page.

With that, you can go to Kodi's Install From Zip and select the source you used to install my repo.

**Comment by pcliff069** [comment]
Thanks.
Away a bit myself.
All done now.
All looks good and upgraded.

Thanks for your help and for the fantastic service and app.
