### ISSUE TITLE
Fen missing home screen widget indicators

### ISSUE THREAD

**Issue by JesseNtaylor** [Tikipeter/repository.tikipeter#229]
Hi I'm using Kodi 20.1 on Ubuntu 20.04 with Arctic zephyr reloaded as my skin

I used to use Ezra and my home screen widgets would correctly show the Artic Zepher indicators from trakt such as watched, paused in the top right corner correctly..

Since I switched back to Fen I've noticed the only widget indicators that show correctly are films and TV that are "PAUSED"

I've checked my watched status provider is Trakt inside fen settings and my skin settings are still correct, but my watched films do not show any indicators on the home screen fen widgets.. 

If I go into the menus themselves instead of the widgets and change to any icon view the indicators are there fine, all of them ..

Just the home screen widgets are missing the indicators.. 

Here are my examples of trending movies.. one with the home screen widgets

![IMG_20230518_022019](https://github.com/Tikipeter/repository.tikipeter/assets/101215194/bb18cce7-569e-4f44-935f-e9e94c53c99e)

And one from fen movies trending menu

![IMG_20230518_022043](https://github.com/Tikipeter/repository.tikipeter/assets/101215194/25da833d-26a4-42f7-ad69-46a93e7885c7)

Can this be rectified.. ?

**Comment by Tikipeter** [comment]
>Can this be rectified.. ?

By the skin dev, sure.
