### ISSUE TITLE
not an issue feature request 2

### ISSUE THREAD

**Issue by cabban** [Tikipeter/repository.tikipeter#23]
scenarie we search movies and have 400 pages and goes trough ans save
the request is start the page u last left
i hav egone through approximately 50 pages with comedy movies then kodi chrashes i must enter all pages again :( 
i hope this is somehting is possible best regards:)

**Comment by Tikipeter** [comment]
Hi cabban.
Let me think about it......

**Comment by Tikipeter** [comment]
OK. I should be able to do this. Please test on next update....

**Comment by cabban** [comment]
> 
> 
> OK. I should be able to do this. Please test on next update....
you are the best , page 6 ex, relisted it notifies :) thank thank u :) come to sweden i buy u lunch :)

**Comment by Tikipeter** [comment]
Good stuff. Thanks cabban.
