### ISSUE TITLE
[Question] Movies --> In Progress Results Order

### ISSUE THREAD

**Issue by TwilightMercy** [Tikipeter/repository.tikipeter#230]
Hi,

![image](https://github.com/Tikipeter/repository.tikipeter/assets/29895680/201abe57-30c7-4674-8df3-19daa0c1a81e)

For FEN --> Movies --> Watched, there is also Recently Watched (sorted by time)

For FEN --> Movies --> In Progress - are the results are sorted like recently watched time? (they are still in progress, but sorted from latest watching start time to earliest)
Or is it random?

Same question for FEN --> TV Shows:
In Progress TV Shows / In Progress Episodes / Next Episodes

![image](https://github.com/Tikipeter/repository.tikipeter/assets/29895680/581b3f36-e3b2-4a06-a870-ca58ffafc30c)

Thank you very much

**Comment by Tikipeter** [comment]
Settings->Navigation->Sorting.

**Comment by TwilightMercy** [comment]
Thank you,

Does these two settings related to In Progress + Next Episodes?

![image](https://github.com/Tikipeter/repository.tikipeter/assets/29895680/dff14425-fcb2-4f74-9c62-660cb69c5080)

**Comment by Tikipeter** [comment]
In Progress relates to In Progress. Watched relates to Watched.

Next Episodes sorting is towards the bottom of the Navigation tab settings. Under Next Episodes.

**Comment by TwilightMercy** [comment]
Thanks.
