### ISSUE TITLE
[Issue] Fen "Netflix" Movies Network list shows incorrect movies

### ISSUE THREAD

**Issue by TwilightMercy** [Tikipeter/repository.tikipeter#231]
Hi,

thank you very much for adding Movies --> Networks list, it's awesome.
I'm using the common networks such as:
Disney Plus, Apple TV+, HBO Max, Amazon Prime.

They all work great and shows the relevant movies.

But specific for "Netflix" list (and more others but they are less important imo) - the list seems to show irrelevant movies.

Screenshot:
![image](https://github.com/Tikipeter/repository.tikipeter/assets/29895680/1cd302cc-275c-4e78-a90f-ef758d95c1dc)

You wrote here when I previously wrote about it: https://github.com/Tikipeter/repository.tikipeter/issues/222#issuecomment-1535385837
"Bound to happen" - what do you mean by that?

And is it fixable?

Thanks!

**Comment by Tikipeter** [comment]
"seems to show irrelevant movies" - what do you mean by that?

**Comment by TwilightMercy** [comment]
That the movies in “Netflix” network list - aren’t Netflix related. 

Another example is in my comment here: https://github.com/Tikipeter/repository.tikipeter/issues/222#issuecomment-1535371520

**Comment by Tikipeter** [comment]
"aren’t Netflix related" - what do you mean by that?

**Comment by TwilightMercy** [comment]
> "aren’t Netflix related" - what do you mean by that?

My bad. I mischecked correctly the results. the movies are indeed related and relevant to "Netflix" network. (they are in Netflix platform).

So changing my Issue this comment only:

Most of the lists working great, but for some of the networks I get the **same** movie list for all of them:

![image](https://github.com/Tikipeter/repository.tikipeter/assets/29895680/18f63fe2-27a6-48da-8980-588d136a4ca2)

Examples networks:

Apple TV (not Apple TV Plus)
Google Play Movies
Amazon Videos
YouTube
Microsoft Store

**Comment by Tikipeter** [comment]
"random but same" - what do you mean by that?

**Comment by TwilightMercy** [comment]
> "random but same" - what do you mean by that?

The screenshot I provided in the previous comment, is the same movie list that you get for multiple networks such as:

Apple TV (not Apple TV Plus)
Google Play Movies
Amazon Videos
YouTube
Microsoft Store

**Comment by Tikipeter** [comment]
Are those movies not supposed to be in each of those lists?

**Comment by xyzfre** [comment]
I think because these are most popular movies and they are available in multiple networks🤔

**Comment by Tikipeter** [comment]
I'd say so.

To me these lists are pretty useless. But someone wanted them, so here they are.

**Comment by TwilightMercy** [comment]
Keep it that way it’s good. At least the common networks are working well.
