### ISSUE TITLE
Subscription Update Crashing in 17.0.3

### ISSUE THREAD

**Issue by dm2912** [Tikipeter/repository.tikipeter#231]
Since update to 1.7.0.3 my subscription update is crashing all the time.

(same in 1.7.0.3a, and now reverted to 1.7.0.1 and error there too now)

Standard log from first failure http://paste.kodi.tv/gococucelo

Full debug log from second attempt http://paste.kodi.tv/avakideqan

I have reverted to the next newest zip i had saved on the network, 1.6.0.8 and subscription update working fine there.

**Comment by dm2912** [comment]
Just looking in my library, I think this may have been broken for me since 17.0.x as the last thing showing as added to my library was last Saturday. Was wondering why this weeks shows had not appeared :D

**Comment by Tikipeter** [comment]
Good job with the logs @dm2912 .
I'll look into it and report back...

**Comment by Tikipeter** [comment]
Will be fixed next update. Please report back here if you are still having issues.

**Comment by djdirty60** [comment]
Test2 working for me now

**Comment by dm2912** [comment]
yup, fixed. i only updated today.
