### ISSUE TITLE
No Furk results

### ISSUE THREAD

**Issue by sasagr** [Tikipeter/repository.tikipeter#232]
Hi Tiki. Not sure what is happening but I get no results from Furk. Account info are available as the video files (My Files) but nothing is coming out from scraping, while manual search works. 
In the log an example from Game of Thrones s01e01. Can you please advise?
https://paste.kodi.tv/irivubukol

**Comment by Tikipeter** [comment]
Hey sasagr.

After a long run of about 9 years, I did not renew my Furk subscription in February of this year. So I am no longer able to delve deeply into any Furk issues. I'd been paying for about 4 years without ever really using the service, just so I had an account for dev work. But I couldn't justify that any longer unfortunately.

In saying that, there was a thread here just recently addressing Furk, and the general consensus amongst those users is that it might well be as good as dead. At least from the standpoint of using it with Kodi.

https://github.com/Tikipeter/repository.tikipeter/issues/226

Unfortunately this may be the end of Furk with Kodi.

**Comment by sasagr** [comment]
oh... sorry I did not see the #226 issue before.
Yes I have been seeing Furk not responding at all a couple of months ago but as you said it came back from ashes as it often happened in the past. Generally I have no big issues from the website but I understand very well that since there is no real support and development it is slowly going to be the end of it. Pity for me that I have a lifetime subscription. To be honest if it wasnt for the sake of saving some bucks today I would have gone to RD straight away. 
It was fun!
By the way ... maybe at a certain point you should cut out the F.. from FEN :) or maybe reinvent a new name

**Comment by Tikipeter** [comment]
What if easynews goes down too. Then it'll be called `''`
