### ISSUE TITLE
[Enhancement Request] Debrid Expiration Notification from FEN

### ISSUE THREAD

**Issue by TwilightMercy** [Tikipeter/repository.tikipeter#235]
Hi Tiki,

Im using “Account Info” button from “My Services” Menu, to check my RD status and expiration date, time days in left:
![image](https://github.com/Tikipeter/repository.tikipeter/assets/29895680/8370ff0f-bb2e-4de4-8a97-3def724816ae)

I was wondering if you’ll consider adding some auto notification from FEN inside Kodi, to notify when the account premium status is about to expire,

Like in 7 days or 14 days. 
Of course, optional in settings. 
What do you think?

**Comment by Tikipeter** [comment]
Done for next update.

**Comment by TwilightMercy** [comment]
Thank you very much for adding it!

I installed the latest test FEN version, and as you wrote in the changelog enabled this setting:
![image](https://github.com/Tikipeter/repository.tikipeter/assets/29895680/29fc81e4-b48b-49ef-b6eb-60ec92a3d508)


I have no way to test it now since my account is not the about to expire, 

can you describe how it’s gonna work, or maybe add an example screenshot when the notification pops up?
and for how many days left it’s gonna notify?

**Comment by TwilightMercy** [comment]
I looked in the code, from what I understood it notifies for 7 days and below?

If so, can it be configured in settings? Something like to choose to notify between 1-30 days before

**Comment by TwilightMercy** [comment]
Tiki?
