### ISSUE TITLE
Fen Error ....’when calling a python...’

### ISSUE THREAD

**Issue by jaimsitecom** [Tikipeter/repository.tikipeter#235]
I get this Error ‘...recurrsion depth exceeded...when calling a python...’, whenever i try to add a new TV show into my FEN subscription. 
 Thus the show doesn’t get added into my kodi library.

**Comment by Tikipeter** [comment]
I'll need a log of this happening.

**Comment by jaimsitecom** [comment]
Log:

https://mega.nz/file/MJZVCCxQ#3_Asso1WayVYxVjuo0z_gDKq6NFTWiV0fMneuAnWDVo

**Comment by jaimsitecom** [comment]
Had to downgrade back to 1.6.26 to make the new subscriptions To appear into the kodi library. Every version starting 1.7.... broke that function.

**Comment by Tikipeter** [comment]
There is something very wrong with your installation.

There are multiple sqlite (database) errors, and then the box goes on some sort of error spree, wracking up a near 2000 line python error. I've never seen anything like it..... until less than a minute later when it does the same thing again. And those two ridiculous errors seem to come from trying to mark something as watched or unwatched.

I have absolutely no idea what advice to give you, but if I saw errors like that on my equipment, I would be wiping the whole thing and starting again. Something is rotten in the state of Denmark.

**Comment by jaimsitecom** [comment]
Clean Installed FEN on another box no Error regarding python anymore but same issue adding subscription in kodi library (still not showing up).

**Comment by jaimsitecom** [comment]
I’m not sure if i Solved the ‘Twilight Zone won’t add on Kodi library’ problem by adjusting Trakt setting in Fen- Trakt-Show future days by changing it to 1 from zero. New season added after that. So it’s only Marvels Agents of Shield still that can’t be added. Not really a problem, i just use Venom for it. Thanks Tikipeter!
