### ISSUE TITLE
Can't find shows

### ISSUE THREAD

**Issue by ANHBOB** [Tikipeter/repository.tikipeter#237]
I'm not sure you can help with this or not, but I thought I'd ask.  I'm trying to watch an older show...NYPD Blue from 1993-2005.  There were around 22 episodes per season. I haven't had any luck using Fen to watch the show....just get a message No Links Found. I have been able to watch some using another addon.  I know Fen uses different scrapers. I do have Real Debrid and Trakt authorized in Fen.

**Comment by Tinuz97** [comment]
Ah,i see why (I think). 
Shadow finds 2 complete season 1 packs, and I think Fen etc (like venom, tempest, the oath etc) do not support season packs?

**Comment by Tikipeter** [comment]
Yes, no season packs for Openscrapers at this time (it is being worked on though, so hopefully soon).

**Comment by ANHBOB** [comment]
I have watched all of season 1 and season 2 (around 44 shows) and the links I found were not Season Packs....just individual links. When I wanted to watch S03E01 is when I ran into a problem. Couldn't find any links for that show but was able to watch it on the internet (Daily Motion and Hulu had links)

**Comment by Tikipeter** [comment]
I understand.

There are no links available for at least the episodes you have quoted. Since you use real-debrid, and are wanting to watch a show that debuted nearly 30 years ago, your best bet is to grab a torrent from a torrent site, add it to your RD cloud, and then Fen will find it there and include it as a result.

There are TV Shows newer than NYPD Blue that I have wanted to watch in the past, and there has been no links available for certain episodes. It is just the way it is with older TV Shows, and to a lesser extent, older Movies.

**Comment by ANHBOB** [comment]
Thank you for your advice, but I'm unsure how to grab a torrent from a torrent site. I don't have any torrent program on my computer.
Yesterday and today I have been able to watch a few shows with Fen, but I've had to try scraping about 5 times before I get a result. As it's scraping it'll count down remaining scrapers left....starts around 60ish. After the first scrape it'll show around 35 left..then shows "No results found" so I do it again and its counts down to around 20-18 and again No results found. After the 4th scrape I'll get 2 results...720p from cartoonhd I think is the name.  Funny on the 2nd scrape I'll get around 8 1080 links during the scrape, but then I get No results found.
I do appreciate all the work you do with Fen. I've always thought it is one of the best addons I've ever used and it's truly unique. Also the support you do helping others with their problems is excellent.

**Comment by Tikipeter** [comment]
> Thank you for your advice, but I'm unsure how to grab a torrent from a torrent site. I don't have any torrent program on my computer.

If you go on your computer to Google, type in "Torrent search engines", then pick one that is available to you.

Then search for "NYPD Blue Season2". If there is a result, copy the link to the magnet, and go to the real-debrid site. At the top of the real-debrid site, there is a "Torrents" tab, click that.

Paste the magnet link where it says "Or Paste Your Magnet Link Here", and click "Convert".A popup will ask you what files from the torrent you want RD to download, you deselect all the files that aren't videos (important), and leave the rest ticked.

Click OK and wait for it (RD) to download. If RD has already downloaded that file, then it will be available immediately.

As long as you have the Internal "RD-Cloud" scraper active in Fen, then Fen will now find these files in a search and offer them for playback as with other results.

You never actually 'download' any of the torrent yourself, so there is no need to worry about installing torrent download software.

If you like watching older shows, you will need to become familiar with this method. You are basically adding these files to your RD Cloud, and then Fen is able to search that and make them available for you to play.

Hopefully soon Openscrapers will have season search support, and you will have to do the above less often, but it will still be necessary sometimes with older shows.
