### ISSUE TITLE
Next episode window shows after video stopped 

### ISSUE THREAD

**Issue by IG2022** [Tikipeter/repository.tikipeter#237]
Hey there, I've noticed that the next episode window shows up after I stop the video if I stop the video before the window comes up within the player. 

I have the next episode window to show at 98 percent. I've found that is the best time for most shows for me as it comes up right after the credits start. 

Sometimes I stop the video before the next episode window shows in the player and I've found that the next up window still  comes up outside of the player even after the video is stopped. Clicking the cancel button removes the window but I was wondering if it would be possible to have the window not show up after stopping the video if I stop it before it shows up within the player. 

I'm not sure if I'm making sense here but let me know if you need any further clarification. 

Thanks!

[Log](https://paste.kodi.tv/bacagiyasa)

**Comment by Tikipeter** [comment]
Should be fixed for next update.

**Comment by IG2022** [comment]
> Should be fixed for next update.

Thanks, I appreciate it!
