### ISSUE TITLE
trakt lists

### ISSUE THREAD

**Issue by trkselim** [Tikipeter/repository.tikipeter#238]
Hi tikipeter

Please can you make trakt lists more than 25

Thanks

**Comment by Tikipeter** [comment]
You'll have to explain yourself better....

**Comment by trkselim** [comment]
In Trakt widgets max.items is 25  
Can you make it more than 25

**Comment by Tikipeter** [comment]
What would you like the upper limit to be? Keep in mind the more items, the slower the load time.

**Comment by trkselim** [comment]
50 is ok

**Comment by Tikipeter** [comment]
OK. I'll up it to 50 for next update.

**Comment by trkselim** [comment]
Thanks
