### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by xyzfre** [Tikipeter/repository.tikipeter#238]
- When using context menu Playback options, Scrape with all filters ignored,,are they the Coco Scrapers filters or Fen ,or both I'm asking because when using this feature I get a lot of 4k links for TV Shows without this feature I get 1080 links,, I noticed this recently because I purchased a new 4K TV

**Comment by Tikipeter** [comment]
It should be both.

All filters within Fen should be ignored, and then any undesirables and any foreign audio filters from Cocoscrapers should be ignored as well.

**Comment by xyzfre** [comment]
> It should be both.
> 
> 
> 
> All filters within Fen should be ignored, and then any undesirables and any foreign audio filters from Cocoscrapers should be ignored as well.

Thank you @Tikipeter 💯
