### ISSUE TITLE
[Enhancement Request] Next Up Credits Chapter - also for “Auto Scrape Next Episode”

### ISSUE THREAD

**Issue by TwilightMercy** [Tikipeter/repository.tikipeter#239]
Hi,
The latest feature from here: https://github.com/Tikipeter/repository.tikipeter/issues/236

is great. 
Can the setting be applied also to “Auto Scrape Next Episode”?
(If there is a chapter above 90%), they can act the same imo

Thanks for all the work!

**Comment by Tikipeter** [comment]
Should use the same already.

**Comment by TwilightMercy** [comment]
The setting only shows up when enabling “Auto Play”, and “Auto Play Next Episode”,

not when only “Auto Scrape Next Episode” is enabled, so I thought it doesn’t work for this method. 

![image](https://github.com/Tikipeter/repository.tikipeter/assets/29895680/7b9e856b-7564-464f-841f-e9cdc0da02b3)

**Comment by Tikipeter** [comment]
I'll add specific settings for when Autoscrape is enabled. They can be set the same or different.
