### ISSUE TITLE
context menu external scrapers manager dialog

### ISSUE THREAD

**Issue by jigoop1** [Tikipeter/repository.tikipeter#239]
hi @Tikipeter 
it's not that big deal but in context menu external_scrapers_manager dialog not showing detail of menu item
in file dialogs.py line # 362 
instead of
listitem = xbmcgui.ListItem(line1, line2)
should be:
listitem = xbmcgui.ListItem('%s %s' % (line1, line2))
btw in tool menu option it's display ok.

**Comment by Tikipeter** [comment]
Do you mean this?..
![screenshot000](https://user-images.githubusercontent.com/28930002/86542415-e51afd80-bf58-11ea-8ad3-84da0e11d1fd.png)

Does yours look different to that^^?

> listitem = xbmcgui.ListItem(line1, line2)
> should be:
> listitem = xbmcgui.ListItem('%s %s' % (line1, line2))

These 2 lines of code achieve the same thing as long as `line1` and `line2` are strings (which the are in this case).

**Comment by jigoop1** [comment]
yeah that's the one but some how my does not show 2 line ! i used skin.aeon.nox.silvo.

**Comment by Tikipeter** [comment]
I'll install that skin and have a look.

**Comment by Tikipeter** [comment]
Looks like Nox Silvo doesn't include a line2 for their dialog window. This skin is a giant pain in the ass.

Let me look at what I can do to make the text visible for this skin on one line, without ruining the aesthetic for every other skin (for most skins having it all on one line is too long to fit the window).

If Kodi allows me to check the currently used skin, then I can manipulate the text based on that condition.

**Comment by Tikipeter** [comment]
There will be a "fix" for this in the next update.

**Comment by jigoop1** [comment]
@Tikipeter 
your help is beyond the wards.
 thanks a lot.
