### ISSUE TITLE
Trakt marked played 2x

### ISSUE THREAD

**Issue by warmach1ne23** [Tikipeter/repository.tikipeter#24]
Iv'e noticed whatever I watch in Fen it get marked as watched twice in Trakt.

**Comment by Tikipeter** [comment]
Hi warmach1ne23. Let me look into it...

**Comment by ANHBOB** [comment]
I am having the same problem as well

**Comment by ANHBOB** [comment]
But it's not that big of a problem. FEN is still the best add on I've ever used

**Comment by Tikipeter** [comment]
I don't know what could be causing this, and I'm not having it happen to me.

The only thing I can think it could be is something to do with the official Trakt add-on also marking watched. Do you have the official Trakt add-on installed??

**Comment by ANHBOB** [comment]
Yes I have the official Trakt add-on.  No worries, it's not that big of a deal.

**Comment by warmach1ne23** [comment]
> I don't know what could be causing this, and I'm not having it happen to me.
> 
> The only thing I can think it could be is something to do with the official Trakt add-on also marking watched. Do you have the official Trakt add-on installed??

Yeah I do.

**Comment by ANHBOB** [comment]
Not sure if this makes a difference but for movies I have them in Watchlist so after I watch them they go away under Movies I've watched. For my TV shows I have them in Collections so I can continue to watch the series every week.

**Comment by host505** [comment]
Fwiw Exodus code (hackily) solved this with getTraktAddonMovieInfo/getTraktAddonEpisodeInfo functions on trakt.py, which are then checked on playcount.py and acts accordingly.

**Comment by Tikipeter** [comment]
Hi host505. :)

That was the only thing I could come up with (checking official Trakt add-on settings) but, like you say, it is pretty hacky. Oh well, if better coders than me can't come up with a better solution, then it looks like I'll be doing that too....

Appreciate the help very much. :) :)

**Comment by Tikipeter** [comment]
I can't get the Trakt add-on to scrobble any movie played with FEN.

Can anyone confirm it is only episodes being marked watched twice....

**Comment by host505** [comment]
You're right, movies don't get scrobbled through trakt add-on when played through fen.
They do however get marked as watched if finished, but not scrobbled in-between pauses/skips. And they consequently don't get marked as watched twice on trakt.tv (but I guess they will, if you have added the movie to your Kodi library through fen and play it through library).

Btw I said the way Exodus does it is hacky before, because it sends 'mark watched' call to trakt, then checks trakt add-on settings, and then sends 'mark unwatched' if true. Maybe you could do it differently, ie first check trakt add-on settings, then do (or don't) your stuff.

**Comment by Tikipeter** [comment]
Yeah, I've written the code so it checks the Trakt add-on settings first. Not sure why the Exo forks don't do that, maybe something to do with the clearing of Trakt cached info. Thankfully, I can clear the cache directly, so if the Trakt add-on is going to mark as watched, I can wait a few seconds for that to happen, and then clear FEN's trakt cache.

I still feel it's hacky to access another add-ons settings directly, but it seems the only way.

Looks like I'll only need to do it for episodes, at least until I figure out why the Trakt add-on isn't active for FEN movies (which I'd like to do).

I suppose the Exo forks do it that way so as to refresh the cache

**Comment by Tikipeter** [comment]
I'm hoping this is fixed come last update (v.1.5.55).
