### ISSUE TITLE
[Question] Debrid Expiration Notification from FEN

### ISSUE THREAD

**Issue by TwilightMercy** [Tikipeter/repository.tikipeter#240]
Hi Tiki,

Thank you very much for adding the Account expiration notification from my issue: https://github.com/Tikipeter/repository.tikipeter/issues/235

I wanted to ask 2 question:

1. I looked in the code, from what I understood it notifies for 7 days and below? or only for remaining days 7,5,3,1?

2. Can the remaining days be configured in settings? Something like to choose to notify between 7-30 days remaining? (In addition to enabling "Check Accounts Status on Startup")

Thanks!

**Comment by Tikipeter** [comment]
1. Notification happens at 7 days before expiry. Then every other day leading down to zero.
2. There is no setting to choose the beginning of notifications.
