### ISSUE TITLE
external scraper

### ISSUE THREAD

**Issue by jigoop1** [Tikipeter/repository.tikipeter#240]
@Tikipeter 
hi,
in external scrapers. scraping work in dialog showing total sources, but then dialog appear no result. i did checked in ext_providers3.db there are hosts list populated. but do not play the source.

**Comment by Tikipeter** [comment]
Both Movies and Episodes don't work?

**Comment by jigoop1** [comment]
Both Movies and Episodes don't work.
no do not using debrid.
i try delete external_providers3.db, and rescrape it still same . scrape the source it's there but not playing any link.

**Comment by Tikipeter** [comment]
I'll close this. Let me know if the problem returns...
