### ISSUE TITLE
improvement next episode list.

### ISSUE THREAD

**Issue by jigoop1** [Tikipeter/repository.tikipeter#242]
@Tikipeter 
is there anyway you can add the total nos of episode remaining to watch. can be seen on that list, currently
![screenshot000_LI](https://user-images.githubusercontent.com/60192287/87695864-08fef000-c75e-11ea-86e3-27c98dde6b93.jpg)
 it shows in TV show/In Progress TV show 
but not in  TV show/next episodes

**Comment by Tikipeter** [comment]
@jigoop1 

I finally got around to trying this, and unfortunately the skin does not display that information for the episode views.
