### ISSUE TITLE
ANNOUNCEMENT: Testers needed.

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/repository.tikipeter#243]
The dev of Venom has been working tirelessly for weeks so as to incorporate season and show torrent scrapers into Open Scrapers. I've been helping in a limited way (he is a much better coder than myself) when possible to make this a reality.

I'm hoping some Fen users can help out with testing this important new feature to Open Scrapers.

**The latest Fen (v.1.7.08) has code that will utilize these scraper packs.** Download the Openscrapers zip posted below to test.

I have also included this Openscrapers zip in the repository source for Tikipeter. So if you added that as a source to File Manager when installing Fen, you can choose it as the source for this file when you select "Install from zip file" in Kodi.

To enable pack searches within Fen, you will need to turn on "Enable Season/Show Pack Search" within Settings->External Scrapers->General. This setting will be OFF by default.

After enabling, be aware that Fen will also decide when to use season/show pack searching. If the current episode being searched is within a season that hasn't finished airing, Fen will not allow a season search to happen. Additionally, if the tv show is not finished, and is still airing, then Fen will not allow the show search to happen. This is to make sure to minimize the extra calls to the source websites. There is no point making a call for a season pack if the season in question is still airing. There will be no season packs to return, and it is just a wasted search.

As a result, when testing it is suggested to choose episodes to search within **finished** seasons and/or **finished** tv shows.

There are a few main areas to look out for when testing:

* **Are the results that are returned correct?**
* Will the results returned play successfully?
* **Is the file that is played the correct file? i.e. the correct episode from the correct season.**
* Are the season/show results caching correctly i.e. going from a s02e07 search to a s02e08 search, does the season and/or show pack results appear in the progress counter immediately, implying that they are cached results?
* Does the cached season/show packs survive a restart of Kodi?
* Is Fen choosing correctly when to enable a season/show search?

Some additional info:

* Fen will now cache single episode result for 24 hours.
* Fen will cache season and show pack results for 2 weeks. (Going forward this will be reduced to 1 week, but the test files included here are set at 2 weeks.)
* You can see what files are in the pack, and manually choose one of those files to play by bringing up the context menu on a pack result, and selecting "Browse Debrid Pack".
* **RD results are hit and miss for playback. I know from the RD API that certain packs will not allow a single episode to be played back from within them, and I don't think there's anything that can be done to fix that. It is just how RD works. So expect playback failures from RD. In saying that, if EVERY playback attempt from RD fails, there is a problem.**
* Uncached Packs are not yet handled by Fen, so it would be best to turn them off when testing.

Here is the Openscrapers zip for users who don't have the tikipeter repository as a source in File Manager:
[script.module.openscrapers-0.0.2.007k.zip](https://github.com/Tikipeter/repository.tikipeter/files/4969405/script.module.openscrapers-0.0.2.007k.zip)

Big thanks for anyone willing to test these new features, and of course to the **Venom** dev who is working so hard to bring this to all Open Scrapers users.

**Comment by Tinuz97** [comment]
Gonna test it also, maybey tomorrow 😃

**Comment by Tinuz97** [comment]
At the moment it works great (I think).
But 1 question/idea. 
It is possible to 'download' a complete pack ?
Because the size reported from a pack is (I think) 1 episode.

**Comment by Tikipeter** [comment]
I appreciate you taking the time to do some testing Tinuz! Much appreciated.

I'm hoping to be able to download a full pack in the near future. At this point it will only download the single episode searched for.

You are correct about the file sizes, they are an estimate of how large one episode file would be, not the entire size of the pack.
That is needed for filtering settings and sort settings, otherwise they will always be at the top of results, and will get filtered out if compared to the single file filter if size filtering is enabled.

Venom dev is hoping to have the update to Open Scrapers done and mostly tested by end of month, possibly earlier.

**Comment by Tinuz97** [comment]
I love this,this is realy great for older shows,just a example.
With my settings,without pack support,it would find zero links,now it has a 1080P pack :)

I did not notice any weird bugs at the moment either.

Latest Fen (Release,not the test version),openscrapers (K) beta.

![image](https://user-images.githubusercontent.com/47715606/88439060-6c49eb80-ce0a-11ea-878b-d97b0621f96b.png)

**Comment by Tikipeter** [comment]
That's great Tinuz!
I'm a little worried about RD's style of caching the packs, there will be results that simply cannot be played.
But I've done as much research as I can, and I don't think it is a solvable problem. The go to is to look at what Seren does, and whether there are results displayed there that cannot be played.
The only solution I can think of would be a call to RD for each PACK result to check if it is playable or not before displaying, which would slow down the displaying of results a lot and also be unreasonable to RD's API. So that's out.
