### ISSUE TITLE
HELP NEEDED for Easynews v3 testing

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/repository.tikipeter#245]
I'm trying to get the new v3 website of Easynews woking in Fen.

The problem I have is that I am unable to access this v3 webpage, I am redirected away from it, likely because my account is not new. Therefore, I have no way to test the code that I'm hoping to use.

If @Aguzy  or @omen124 or anyone else would like to test this Fen build, it will hopefully give me enough information to finish writing working code. Nothing is harder than writing code when you cannot even see the results.

If anyone is willing to test this version, please do the following:
* DO NOT turn on debug logging. It is not necessary for me and will clutter the log.
* Turn off ALL scrapers except for Easynews.
* Search only for 1 or 2 movies. I just need some info from the log as to what is returned by the query.
* Upload the log here for me to take a look at.

I don't expect you to actually get results showing on the screen when you do your searches, so don't be discouraged. It may work but probably not. And if it does work, it almost certainly will not play the results returned.

I need help just to collect the data that is returned by the query to Easynews in the code. So the log file is what is of importance at the moment, rather than seeing results.

Much thanks to anyone with v3 Easynews access who can help here.

Below is a zip to the test file (v.1.7.09b). You can download this zip and install it, or go to my repository address you may have in your Kodi File Manager and it will also be there to install over the net.

~~[plugin.video.fen-1.7.09a.zip](https://github.com/Tikipeter/repository.tikipeter/files/4990573/plugin.video.fen-1.7.09a.zip)~~
~~[plugin.video.fen-1.7.09b.zip](https://github.com/Tikipeter/repository.tikipeter/files/4996056/plugin.video.fen-1.7.09b.zip)~~
See latest post for most recent test zip.

**Comment by omen124** [comment]
@Tikipeter Send me an email and I will help you with access to my account

**Comment by Tikipeter** [comment]
Thanks a lot for the offer @omen124 

I have sent you an email, and removed your email from your message afterwards.

**Comment by omen124** [comment]
@Tikipeter thanks for sorting that part, I have sent the email and hopefully it helps out. Keep me in the loop for updates.

**Comment by Tikipeter** [comment]
Great stuff!
It was definitely my email sent, so don't worry.
This should allow this issue to be resolved soon.

**Comment by Tikipeter** [comment]
@omen124 

Already looks promising!

**Comment by Tikipeter** [comment]
![screenshot000](https://user-images.githubusercontent.com/28930002/88826044-a4d33600-d20b-11ea-8b8c-1319cc32cbcc.png)

**Comment by omen124** [comment]
Good to hear.

**Comment by Tikipeter** [comment]
@omen124 

Ok. I'll post below a test zip (v.1.7.09c), and will also post it at my github repo address.

To use this version:
* Go to Settings->Accounts->Easynews and set "API Version" to "Version 3"
* Go to Tools->Clear Database and Clean Settings Files and select "Clear Internal Scrapers Cache".
* Have only the Easynews Scraper enabled.
* Scrape a Movie. You should get results. If you do get results, you should be able to play back the file.

Things that are troubling me, and I am hoping to sort out:
* This v3 is much slower than version 2.
* I can get search results through the "My Services" section, but for some unknown reason I have yet to successfully play back a file through that menu.
* I have had at least one occasion already where the Easynews scraper did not give me results when it should have. I'm hoping it was a glitch, otherwise this v3 method is also not as stable as v2.

Anyway, try it out and let me know if it works. If so, give me a day to try and see what's going on with direct search playback, and the inconsistent results, and then I should be able to give you back your logins.

v.1.7.09c:
[plugin.video.fen-1.7.09c.zip](https://github.com/Tikipeter/repository.tikipeter/files/4998292/plugin.video.fen-1.7.09c.zip)

**Comment by omen124** [comment]
I tried installing the c version from the repo and it wasn't there, just the normal version. 
I use the repo for my installs due to having a firestick and it is a little fiddly to get the zip on there.

**Comment by Tikipeter** [comment]
When you installed the Tikipeter repo, you likely added my repo address as a source in your Kodi File Manager. That is where the file is.

**Comment by omen124** [comment]
I don't quite understand what you mean. 
I added the 0.05 repository as the "install from zip" which added your normal repo to "install from repository" which I download Fen from. When going into the "install from repository" and choosing Fen from video add-ons I only see 1.7.09, and I have scoured the sub categories and can't find the c version.

**Comment by Tikipeter** [comment]
OK.

1. Go to Kodi's File Manager.
2. Select "Add Source"
3. Enter this as the path: 'https://tikipeter.github.io".
4. Choose a name for the source.
5. Back out of File Manager, and into "Install from zip file".
6. Choose the source you just added.
7. Choose the Easynews test file (it's going to be 1.7.10 in a minute when I upload a new test).

That should install the test version.

**Comment by omen124** [comment]
In the meantime I went the long way around and downloaded the zip file.
I tested it and it works, it is streaming a HEVC movie right now from easynews.
No issues so far.

**Comment by omen124** [comment]
When checking install from zip all I see is the repository 0.0.5 zip

**Comment by Tikipeter** [comment]
Latest test:
[plugin.video.fen-1.7.09d.zip](https://github.com/Tikipeter/repository.tikipeter/files/5002530/plugin.video.fen-1.7.09d.zip)

**Comment by Tikipeter** [comment]
Great news that it's working.

I've sorted out playback from the Easynews direct search.

I've also moved away from using cookies like Shadow does, and back to Authing in the params. That should see a speed increase.

The only issue now is cleaning up the code, bcause atm it's a bit of a mess, getting downloading to work from Easynews again, and making sure there's nothing else I can do with regard to resolving success (I am having trouble resolving sources sometimes).

I'm hoping a couple of hours and I can push an official update, which will be easier for you to install, and then this will all be over.

**Comment by omen124** [comment]
Right now I'm just browsing categories eg popular and they do take a little time to load on version d, will report any failures.

**Comment by Tikipeter** [comment]
There will be an official update soon.

* Speed for searching should be the same as v2 now.
* Speed for resolving will be slower, as there is an extra call to Easynews to get more needed information before resolving.
* Downloading, both from a direct search and a regular search, is now working.
* Account info is still working.

I think that's about it. I'm not sure whether the moderation setting is being applied to the v3 API, but it is included in the params so that is up to Easynews.

**Huge thanks to you @omen124 , I realize now I could not have implemented v3 without direct access.**

If I were you, I would wait for the update (v.1.7.10), test it for a while, and when you are confident it is all working correctly **change your password so I no longer have access. I will no longer be using you account login so you can change it as soon as you feel I don't need to fix anything**.

**Comment by Aguzy** [comment]
Sorry pal I just saw this in my emails, have tested 1.7.09d and it's working perfectly for me too. Sorry again that I wasn't around to help you test it or give you use of my account

**Comment by Tikipeter** [comment]
No worries @Aguzy 

The latest official update (v.1.7.10) has the code for working Easynews, so you can migrate to that if you want.
It has a little bit cleaner code.

**Comment by omen124** [comment]
I have installed the latest version after uninstalling both Fen and Kodi completely due to some cache issues and how I can seem to get any Easynews results, are you sure it is fixed? I tried a couple of movies and a few tv shows.
paste.kodi.tv/ahalamegoz

**Comment by Tikipeter** [comment]
Be sure you have it set to version 3 in settings.

**Comment by omen124** [comment]
It is set to version 3, I will try to switch ti to 2 and back to 3 to make sure it is properly set, then report back.

**Comment by Tikipeter** [comment]
You definitely have the correct credentials entered?
If you changed your password, do you have the new one entered correctly?

**Comment by omen124** [comment]
After closer inspection of the username and password, I realized that the username was all lower case and the website login has a capital letter in it. Forgot it was case sensitive, must have missed it as I was rushing through filling in the settings for the 20th time....

**Comment by Tikipeter** [comment]
Great stuff.
Let me know of any issues.
