### ISSUE TITLE
Fen showing watched shows under In Progress

### ISSUE THREAD

**Issue by 42RoiDesRois42** [Tikipeter/repository.tikipeter#246]
First, I truly appreciate all the hard work that’s done.

The new update to Fen now includes all shows in progress even those marked watched with no new episodes.

While this may work for some, it doesn’t for me (not sure if there was a poll or just a couple who wanted this). I only want to see new, unwatched episodes under In Progress (what I really liked about Fen, but it’s gone).

How do I turn it off? Can a feature be added to enable or disable so that we can remove watched (no need to see active seasons since that’s what trakt is for)?

Thanks.

For better explanation (copied from Reddit):

People hold 2 different views on this subject:

Option 1) When all currently available episodes of a show have been watched, then the show should appear in the watched menu, and not the in progress menu. Whether there will be new episodes aired in the future is irrelevant.

Option 2) When all currently available episodes of a show have been watched, then if the show is still airing, meaning there will be new episodes in the future, then that show is not fully watched so should remain in the in progress menu. Only shows where all episodes have been watched, and no new episodes will be aired in the future, should be placed in the watched menu.

My preference is Option 1.

**Comment by les017** [comment]
Echo Option 1

**Comment by Tikipeter** [comment]
Added Settings->Navigation->Content->"Watched (Still Airing) TV Shows Location" setting. Choose between "Watched", "In Progress" or "Both" for next update.

**Comment by 42RoiDesRois42** [comment]
> Added Settings->Navigation->Content->"Watched (Still Airing) TV Shows Location" setting. Choose between "Watched", "In Progress" or "Both" for next update.

Thank you.
