### ISSUE TITLE
Lag/High(er) CPU load on 'Extra's' Menu on Windows 10 PC.

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#247]
if Fen is open (version 1.7.11) the cpu load is normal (like 0-3% on taskmanager).
I i open the 'Extras' menu, just open it,not selecting anything, the CPU goes to 15/20% (i7 3770K), this does not look much,but if i scroll in the extras menu,that scrolling is lagging (lag spikes,CPU spikes also).

I don't have this in other menu's, and i did not have this in the previous version, did you change something in the Extras menu code?

Greetings TInuz.,

**Comment by Tinuz97** [comment]
My android phone (oneplus 5) and nvidia shield tv pro same as above.

**Comment by Tikipeter** [comment]
I'm going to have to look into this, as I did have it happen to me, although not all the time. It was happening randomly.

**Comment by Tikipeter** [comment]
I'll push an update soon with a hopeful fix for this.

I've added something that I think will stop this issue, but i have no idea why it stops this issue. It's a real mystery.

**Comment by Tinuz97** [comment]
On the phone it feels smoother now, did not test my computer and nvidia shield yet.

**Comment by Tinuz97** [comment]
Also I noticed something else, any idea why Fen does not find any cached link for this movie?
Fen also had kickass scraper, so that in theory would not be the issue. 

![Screenshot_20200809-001513](https://user-images.githubusercontent.com/47715606/89720728-ad7af780-d9d5-11ea-8091-084bdea22c50.jpg)

**Comment by Tinuz97** [comment]
Venom addon (same scrapers) 

![Screenshot_20200809-022406](https://user-images.githubusercontent.com/47715606/89722226-73b2ec80-d9e7-11ea-86ea-0597970d6e9d.jpg)

**Comment by Tinuz97** [comment]
Feels smooth on computer again also (the extras menu)

**Comment by Tikipeter** [comment]
The discrepancy in the results would likely be due to Venom and Seren making a call to Trakt before scraping to get aliases for the movie. Fen relies on TMDb's aliases, of which there are none for this movie. This means the scrapers are trying to match the full title, which includes "The Movie" at the end.
