### ISSUE TITLE
Regarding episode runtimes 

### ISSUE THREAD

**Issue by rizreflects** [Tikipeter/repository.tikipeter#249]
Hey Peter, I'm afraid I have to bother you again today. I've come across a problem I was hoping you could help with. 

![20230608_024202.jpg](https://github.com/Tikipeter/repository.tikipeter/assets/76912707/42be49cc-6bc1-4c82-b86f-6ea31cbdb4b0)

The skin I'm using here is Arctic horizon 2. If you take a look at the episode runtime (just below the title), you can see the runtime of 30 minutes. This is actually incorrect, and this issue repeats for quite a lot of shows. If you look on mdblist, you can see the correct runtime which is 42 mins (on the bottom right-hand corner):

![20230608_024416.jpg](https://github.com/Tikipeter/repository.tikipeter/assets/76912707/5d360474-a850-4c72-a268-8e5b49ed7cb6)

Now initially, I assumed this was a skin problem. Reason being, the ratings only work if I put my omdbkey into tmdbhelper. So I assumed the episode runtime was through there aswell. I posted the issue onto Arctic horizons github and the dev said this is a problem with the video addon rather than the skin. Is this a problem we could possibly find solutions for? As usual, thanks for all your work. I really appreciate all that you do.

**Comment by Tikipeter** [comment]
30mins is the fallback value when TMDb doesn't provide any episode duration value at the TV Show level.

I can make `0` the fallback value, which won't fix the problem of TMDb not having episode duration info, but will stop an value appearing in Kodi.

**Comment by rizreflects** [comment]
I think setting it to 0 may be a good solution. With that being said, jurialmunkey responded again to my issue saying this "Also, TMDb website and TMDbHelper are reporting correct times for this show when I looked it up. Which means either the addon you're using is giving the wrong times; or the metadata it provides is wrong/incomplete which is then causing TMDbHelper to lookup the wrong show."

Since he is saying that particular show has episode runtimes, do you think there may be a problem with how fen is looking it up? It's a little strange how mdblist shows the correct runtime, as I was under the impression that website was also getting its metadata through tmdb.

**Comment by Tikipeter** [comment]
>Also, TMDb website and TMDbHelper are reporting correct times for this show when I looked it up

Nowhere on the TMDb website does it show an episode runtime value at the TV Show level. Also, TMDbHelper does not show a value for this at TV Show level for `Love & Death`, and many other TV Shows. I'm not really sure what Jurial is talking about here.

>Which means either the addon you're using is giving the wrong times; or the metadata it provides is wrong/incomplete which is then causing TMDbHelper to lookup the wrong show

This is nonsensical.

>Since he is saying that particular show has episode runtimes, do you think there may be a problem with how fen is looking it up?

No. This is the reply from TMDb when asked for info for this TV Show: `'episode_run_time': []`. There is no value supplied. And TMDbHelper doesn't provide a value within the addon either.


Unless Jurial is getting confused, and is now talking about runtimes for each of the specific episodes (which TMDb DOES provide and Fen displays correctly), then he is wrong.

But it seems like a misunderstanding of which container is being talked about. You're talking about the TV Show container, whereas he now seems to be referring to the episodes container. At the TV Show level, there is no valid runtime to show for Love & Death. At the episodes level, all the episodes have valid runtimes and are set correctly by Fen.

Once again, the only issue is me setting a 30 min default value when there is no value supplied by TMDb. I'll change that to 0 so nothing shows.

>It's a little strange how mdblist shows the correct runtime, as I was under the impression that website was also getting its metadata through tmdb.

MDbList would get it's metadata from Trakt, which indeed gets the bulk of it's metadata from TMDb. But it also adds metadata itself, like airtimes and obviously default semi-correct TV Show level episode runtime. Likely still from TVDb, or they add it manually.

**Comment by Tikipeter** [comment]
>If you look on mdblist, you can see the correct runtime which is 42 mins

This is also not correct, and shows the difference between providing an episode runtime at TV Show level versus what the actual episodes' runtimes are specifically.

The episode runtimes for Love & Death are:
```
Episode 1: 57mins
Episode 2: 55mins
Episode 3: 59mins
Episode 4: 52mins
Episode 5: 53mins
Episode 6: 46mins
Episode 7: 58mins
```

None of the episodes are 42 minutes long.

**Comment by rizreflects** [comment]
I understand. Thanks for explaining that to me. Yes, I think there was definitely a misunderstanding between me and jurial. I should have worded it better. I appreciate you setting it to 0 though. Better to see nothing than an incorrect runtime imo. Thanks a lot!

**Comment by xyzfre** [comment]
My opinion I'd rather see the default runtime which is close enough at least it gives you an idea more or less when browsing then to see nothing there

**Comment by Stelios79** [comment]
> My opinion I'd rather see the default runtime which is close enough at least it gives you an idea more or less when browsing then to see nothing there

Same here

**Comment by rizreflects** [comment]
It is kinda hard to unsee these incorrect episode runtimes though I must admit. The last of us is apparently 30 mins 😭

**Comment by Tikipeter** [comment]
If TMDb provide the value at TV Show level, I will provide it to Kodi. If not, I won't.

That's what I'm going with.
