### ISSUE TITLE
Getting lots of errors lately

### ISSUE THREAD

**Issue by KalAvroniev** [Tikipeter/repository.tikipeter#250]
My most used navigation is TV Shows -> Next Episodes. 
I have also installed FenTastic skin and added that to the widgets.
The problem is I'm getting lots of errors, mostly when I get to the above section. 
Before I could navigate away by going back but not any more. I'm stuck there and I have to force close the Kodi app and try again.
It's been taking multiple retries until I'm able to get into the Next Episodes section.

I tried cleaning the cache, database, checking for corruption. I also changed the Language Invoker to false. No luck with either.

Kodi: 20.1

Example log:
https://paste.kodi.tv/emiwedabal

**Comment by Tikipeter** [comment]
I can't really help with the log provided, as there's no actual error in there.

My only advice, based on what you have already tried, is to delete all the databases in Fen's settings, and restart Kodi.

Apart from that I have no idea what might be going on.

**Comment by KalAvroniev** [comment]
I'll try that. All I can say is that the add on was way more stable on Kodi 19
