### ISSUE TITLE
Trakt rating and Fen

### ISSUE THREAD

**Issue by onlytanmoy** [Tikipeter/repository.tikipeter#250]
Hi, first things first..thank you for the awesome Fen addon 👌 I got a request with respect to Trakt in Fen.
Please see below issue
https://github.com/trakt/script.trakt/issues/507
The developer of the Trakt add-on has indicated that this issue is down to the fact that Fen is not sending the right info as expected by Trakt and therefore it fails to show the rating pop-up at the end. You will find the log files in the issue I referred earlier. I know some people find it silly to rate a movie after watching but I personally enjoy it so will be nice to get it working. Let me know if you need more details. TIA.

**Comment by Tikipeter** [comment]
I've not got the trakt script installed to test, but I have added code to set the window property it wants to use upon completion of playback.
Please test after next Fen update to see if it is working, and let me know.

**Comment by onlytanmoy** [comment]
@Tikipeter I truly appreciate that mate. Will eagerly await for the next Fen update. I will test a movie post that and report back to you, hopefully positive outcome. Thank you.

**Comment by onlytanmoy** [comment]
@Tikipeter just wanted to thank you for fixing this mate..the latest update of Fen 1.7.12 is working like a champ in terms of handling the Trakt rating 👍 Thanks again for the swift turnaround.
