### ISSUE TITLE
[Bug] Excluding Dolby Vision / HDR Sources

### ISSUE THREAD

**Issue by TwilightMercy** [Tikipeter/repository.tikipeter#251]
Hi,

Trying again my luck from this past issue: https://github.com/Tikipeter/repository.tikipeter/issues/145

I know this is not a FEN issue, but Cocoscrapers issue. Just checking if something has changed between then and maybe now something can be a workaround fix through FEN, or maybe there is a way to contact cocoscrapers dev regarding this issue.

Screenshot + log are attached in the past issue.

Thanks!

**Comment by 42RoiDesRois42** [comment]
Scraping is going to be Cocoscrapers Dev.

**Comment by Tikipeter** [comment]
No news.

Your option is to ascertain which scraper(s) is causing the issue, and disable it until an update is provided by the dev. Not all scrapers are providing incorrectly formatted data.

I currently have no contact, and of course no access to the github.
