### ISSUE TITLE
Context menu ‘Fen option’ not working anymore?

### ISSUE THREAD

**Issue by jaimsitecom** [Tikipeter/repository.tikipeter#252]
Hi Tikipeter. Just wanna know if the Fen Option not working anymore?  I used to use this context menu option if i need to change quickly a setting inside Fen and if i get problems with a certain movie or tv show. Do i need to do something to make this work again?  I am currently using the latest version. I couldnt remember anymore which version where it was still useable at least for me tho. 

Thanks man.

**Comment by Tikipeter** [comment]
It is still working for me....
![screenshot000](https://user-images.githubusercontent.com/28930002/90649733-61a23b00-e27e-11ea-8871-51a1199f1e66.png)

Questions....
* Are you trying to access the menu from within the addon or from a widget item?
* Is there a notification script error message when this doesn't work?

Things you can try....
* Clear the Metadata Cache (Tools->Clear Databases & Clean Settings Files->Clear Meta Cache).
* If trying to access via widget, try from within addon and see if it works.

Finally....
* Attempt to access Options Menu, and then provide me with a log after it fails.

**Comment by jaimsitecom** [comment]
I access Fen options from the Kodi Library. I honestly remember doin it there until the last 2 (at least) versions. 

I will send the log in a moment. Ty

**Comment by Tikipeter** [comment]
OK. That's the info I needed.

There's no need to send a log. I can test this now and work out what's going on. 👍

**Comment by jaimsitecom** [comment]
Log:
https://mega.nz/file/pNghmTrZ#EQFqdm6fifPIKu9s_r_lttyylpvx5oSUSe-RwLIPvgQ

**Comment by Tikipeter** [comment]
I'll push an update to fen context menu addon soon with a fix for this.

**Comment by jaimsitecom** [comment]
Thanks

**Comment by Tikipeter** [comment]
Update pushed (v.1.0.09). Please let me know if it fixes the problem.

Here if you want to install manually:
[context.fencontextmenu-1.0.09.zip](https://github.com/Tikipeter/repository.tikipeter/files/5097460/context.fencontextmenu-1.0.09.zip)

**Comment by jaimsitecom** [comment]
Worked! Thanks Tikipeter!!!

**Comment by Tikipeter** [comment]
No worries. :)
