### ISSUE TITLE
Premiumize 'packs' downloading wrong path. 

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#253]
I did set the path correctly (to my server on the local network), same path as I did for my movies, for movies it is working correctly.

But tv shows (packs) won't download to that path, they get stored on my local (windows) machine, not the server on the local network, any idea?

**Comment by Tikipeter** [comment]
Interesting.

Just fwi, PACKS are supposed to download to the `Premium` directory.

I'll look into this.

**Comment by Tinuz97** [comment]
Auto unzip would be awesome also 😜

**Comment by Tikipeter** [comment]
Unfortunately, the downloader re-write has had to be put off for a week. Something else came up with Fen that I will write about shortly, which has taken my time up until now. There is still more to do, so this will have to wait.
My apologies @Tinuz97
