### ISSUE TITLE
Trakt lists taking a lot longer to load at times 

### ISSUE THREAD

**Issue by inky-pits** [Tikipeter/repository.tikipeter#253]
Recently Trakt lists are intermittently talking longer to load. It usually happens to next episodes, but happened to latest TV shows in this log. I've tried clearing all cache in Fen and Kodi app.

Sometimes scrapes produce no results on first pass but will on second, I shall try to get this behavior in a log too.

Nvidia Shield TV Pro, Kodi Version info:
Build: 21.0-ALPHA1 (20.90.101)
Git: 20230506-eebc71466d
Compiled: 2023-05-07

https://paste.kodi.tv/ejowohalos

**Comment by Tikipeter** [comment]
Not much I can do here really. If it's Trakt being Trakt, then their API might be faltering occasionally. If not, I'd delete the `traktcache4.db` in Fen's userdata folder and restart Kodi.

As for results sometimes not showing on first scrape, let me know what debrid service you use.

**Comment by inky-pits** [comment]
Thanks for the reply, I shall look for the suggested db file. I'm using Real Debris.
