### ISSUE TITLE
ANNOUNCEMENT: Testers wanted...

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/repository.tikipeter#254]
Hi to anyone interested.

When Kodi 18 was released, there was a new feature called "reuselanguageinvoker" that caused a lot of discussion on Kodi's Github.

When I stopped monitoring the conversation, this new feature was to be ON by default, and addon dev's could disable it in the addon.xml by including a condition within.

I chose not to include that condition, meaning I believed Fen was using the reuselanguageinvoker feature.

A recent post on reddit by nixgates, ascribing the large speed increases when this feature is ON, got me thinking about whether Fen was actually utilizing it or not. Whilst Fen is fairly speedy now, it has had issues in the past with slower than expected results for certain actions, so I decided to look into the matter more.

Turns out, after much debate, this feature was defaulted to OFF in all Kodi builds, so Fen was in fact NOT using reuselanguageinvoker. When I enabled it, all hell broke loose as Fen was handling args, params and general sys items in a way that would not be compatible with enabling this feature.

So, a lot of work later, there is a Fen build below for anyone who wishes to try this speedy version out. I can't post this on my html github location, as it seems for some reason Kodi will not show the file for ZIP installation. So it's grab it from here or nothing, unfortunately.

There are definitely issues with stability on some users' setups when this feature is set to ON, so there is a menu at the bottom of Tools that will allow you to turn the invoker reuse OFF. Kodi must be restarted if you change this setting. The eventual location of this setting is still being considered.

For these test builds, the reuse invoker will be set to ON (True) by default. In future releases, this will not be the case. It is quite possible I will not be able to honor the users' setting of this between updates, so each update may require you to reset this feature. I'm trying to think of a way to have a persistent setting for this, but it is different from all the other settings, and isn't really a setting at all, so it can't be set and then be honored between updates.

Good things to look for:
* Speed improvement (possibly a large speed increase with certain hardware, less large with more powerful devices that are pretty fast to begin with).

Bad things to look for:
* Menus not loading when selected.
* Kodi crashing.
* Multiple widgets causing Kodi to crash.
* Problems with changes to settings being honored.
* General instability.

In good news, some of the changes I had to make to allow this to work will also provide some speed benefit even if you turn the reuse invoker OFF. So in the end it was worth the effort, even if it is not used.

The file:
~~[plugin.video.fen-1.8.01_testing.zip](https://github.com/Tikipeter/repository.tikipeter/files/5125944/plugin.video.fen-1.8.01_testing.zip)~~

~~[plugin.video.fen-1.8.02a_testing.zip](https://github.com/Tikipeter/repository.tikipeter/files/5131852/plugin.video.fen-1.8.02a_testing.zip)~~

~~[plugin.video.fen-1.8.02c_testing.zip](https://github.com/Tikipeter/repository.tikipeter/files/5135406/plugin.video.fen-1.8.02c_testing.zip)~~

~~[plugin.video.fen-1.8.02d_testing.zip](https://github.com/Tikipeter/repository.tikipeter/files/5139010/plugin.video.fen-1.8.02d_testing.zip)~~

[plugin.video.fen-1.8.02e_testing.zip](https://github.com/Tikipeter/repository.tikipeter/files/5146186/plugin.video.fen-1.8.02e_testing.zip)

**Comment by Tinuz97** [comment]
![bucket](https://user-images.githubusercontent.com/47715606/91224440-648ba880-e722-11ea-9f91-7dcfdca1ba4a.png)

**Comment by Tinuz97** [comment]
If you need translation(s), just drop them here. 

![Screenshot_20200825-223233](https://user-images.githubusercontent.com/47715606/91224773-e7acfe80-e722-11ea-80d5-3d1cb2318ada.jpg)

**Comment by Tikipeter** [comment]
Thanks Tinuz. I'll be home in a couple of hours and I'll post them below for when you get some time. :) :)

**Comment by Tinuz97** [comment]
I have time tomorrow, almost bedtime here 😄

**Comment by Tikipeter** [comment]
Just if you get the chance Tinuz:

```
msgctxt "#33017"
msgid "Set Language Invoker (ADVANCED!!)"
msgstr ""

msgctxt "#33018"
msgid "[B]Reuse Langauage Invoker[/B] is currently set to %s.\n\nDo you wish to change this setting to %s?"
msgstr ""

msgctxt "#33019"
msgid "Changing this setting can create problems within Fen.\n\nContinue?"
msgstr ""

msgctxt "#33020"
msgid "Kodi must close and be restarted for the change to take effect.\nClose Kodi now?"
msgstr ""

```

**Comment by trkselim** [comment]
I tested on beelink gt king pro S922X it’s really fast the movies menu and widget works will
For tv shows if I open trending tv from fen is working but when I make it widget it’s shows empty widget in Home Screen

**Comment by djdirty60** [comment]
msgctxt "#33017"
msgid "Set Language Invoker (ADVANCED!!)"
msgstr "Taalinvoker instellen (GEAVANCEERD !!)"

msgctxt "#33018"
msgid "[B]Reuse Langauage Invoker[/B] is currently set to %s.\n\nDo you wish to change this setting to %s?"
msgstr "[B]Hergebruik taal Invoker[/B] is momenteel ingesteld op %s.\n\ Wilt u deze instelling wijzigen in %s?"

msgctxt "#33019"
msgid "Changing this setting can create problems within Fen.\n\nContinue?"
msgstr "Het wijzigen van deze instelling kan problemen veroorzaken binnen Fen. \n\nDoorgaan?

msgctxt "#33020"
msgid "Kodi must close and be restarted for the change to take effect.\nClose Kodi now?"
msgstr "Kodi moet worden afgesloten en opnieuw worden opgestart om de wijziging door te voeren. \nKodi nu sluiten?"

**Comment by djdirty60** [comment]
Trakt list not working

**Comment by Tinuz97** [comment]
@Tikipeter 


msgctxt "#33017"
msgid "Set Language Invoker (ADVANCED!!)"
msgstr "Taal Invoker Instellen (GEAVANCEERD!!)"


msgctxt "#33018"
msgid "[B]Reuse Langauage Invoker[/B] is currently set to %s.\n\nDo you wish to change this setting to %s?" -->*Language
msgstr "[B]Hergebruik Taal Invoker[[/B] is momenteel ingesteld op %s.\n\nWilt u deze instelling wijzigen in %s?"


msgctxt "#33019"
msgid "Changing this setting can create problems within Fen.\n\nContinue?"
msgstr "Het veranderen van deze instelling kan problemen veroorzaken binnen Fen.\n\nDoorgaan?"


msgctxt "#33020"
msgid "Kodi must close and be restarted for the change to take effect.\nClose Kodi now?"
msgstr "Sluit Kodi af en start opnieuw op om de verandering in werking te laten treden.\nKodi nu sluiten?"

**Comment by Tinuz97** [comment]
> Trakt list not working

Same here on Android. (on Windows 10 it is working fine). 

But on Android (phone, not tested the nvidia shield yet) I can't even authorize Trakt, error immediately. 

No idea if this is the correct section of the log @Tikipeter from my phone.


plugin://plugin.video.fen/?foldername=My%20Lists&iconImage=lists.png&mode=navigator.my_content&name=32454
2020-08-26 12:49:40.682 T:4808   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.fen/?foldername=My%20Lists&iconImage=lists.png&mode=navigator.my_content&name=32454) failed
2020-08-26 12:49:44.349 T:4808   ERROR: Control 4294967216 in window 10140 has been asked to focus, but it can't
2020-08-26 12:50:22.457 T:4808   ERROR: Previous line repeats 1 times.
2020-08-26 12:50:22.457 T:4808  NOTICE: CWinSystemAndroid::DestroyWindow

**Comment by Tikipeter** [comment]
Thanks everyone for reporting your tests.

I'll look into the issues. 👍

**Comment by Tikipeter** [comment]
New file posted in original comment (1.8.02_testing).

This update has a check upon each Kodi start/update to see that the value of reuselanguageinvoker in the addon.xml is the same as the last value set by the user. Since you haven't set a value yet because Fen couldn't do that in 1.8.01, then a pop up will appear letting you know to restart Kodi. Ignore this for just this update, and go into Tools and set the invoker to TRUE yourself (it is ow at the bottom of Tools). After this, each time Fen updates, the auto check will let you know that there is a mismatch in the settings, and to restart Kodi.

Anyone with widget issues, you will likely need to rebuild your widgets after this update to get them working correctly again.
I think all issues brought up here are now fixed.
Let me know.

**Comment by Tinuz97** [comment]
That needs translation also (I did hit yes). 
Testing in a minute. 

![Screenshot_20200826-221907](https://user-images.githubusercontent.com/47715606/91352492-38d3f580-e7ea-11ea-8ed7-a4ecba744662.jpg)

**Comment by Tinuz97** [comment]
And this maybey a mistake by me 😅

![Screenshot_20200826-222146__01](https://user-images.githubusercontent.com/47715606/91352775-9c5e2300-e7ea-11ea-844c-12520da39451.jpg)

**Comment by Tinuz97** [comment]
This one needs translation also. 

![Screenshot_20200826-222411](https://user-images.githubusercontent.com/47715606/91353005-ef37da80-e7ea-11ea-93b2-b3b9f2934850.jpg)

**Comment by Tinuz97** [comment]
Trakt auth is working again on my Android phone with this update 👍

**Comment by trkselim** [comment]
All tv&movies widgets work after update to1.8.02a👍🏻

**Comment by Tikipeter** [comment]
@Tinuz97 
You are right, there's a couple missing and I've now changed a couple a bit as well. Would you mind re-translating them for me?
Thanks buddy if you can. 👍 

```
msgctxt "#33018"
msgid "[B]Reuse Langauage Invoker[/B] is currently set to %s.\n\nDo you wish to change this setting to %s?"
msgstr ""

msgctxt "#33019"
msgid "Changing this setting can create problems within Fen.\n\nContinue?"
msgstr ""

msgctxt "#33020"
msgid "Kodi must close and be restarted for the change to take effect."
msgstr ""

msgctxt "#33021"
msgid "[B]Reuse Language Invoker[/B] SETTING/XML mismatch.\nRestore correct status(RECOMMENDED)?"
msgstr ""

msgctxt "#33022"
msgid "No Trakt or IMDb Account Detected."
msgstr ""
```

**Comment by Tikipeter** [comment]
**Big speed increases** with next version posted above (v.1.8.02c).
Big changes to settings, so this is very much a TEST VERSION.
Settings you change from the settings dialog will not register within Fen. You have to go to Tools->Clear Settings Properties.
This is of course temporary, but I haven't written a settings change monitor yet.
This version is to test if others get a quite large speed increase.

**Comment by djdirty60** [comment]
msgctxt "#33018"
msgid "[B]Reuse Langauage Invoker[/B] is currently set to %s.\n\nDo you wish to change this setting to %s?"
msgstr "[B] Hergebruik taal Invoker [/B] is momenteel ingesteld op%s.\n\nWilt u deze instelling wijzigen in%s?"

msgctxt "#33019"
msgid "Changing this setting can create problems within Fen.\n\nContinue?"
msgstr "Het wijzigen van deze instelling kan problemen veroorzaken binnen Fen.\n\nDoorgaan?"

msgctxt "#33020"
msgid "Kodi must close and be restarted for the change to take effect."
msgstr "Kodi moet worden gesloten en opnieuw worden opgestart om de wijziging door te voeren."

msgctxt "#33021"
msgid "[B]Reuse Language Invoker[/B] SETTING/XML mismatch.\nRestore correct status(RECOMMENDED)?"
msgstr "[B] Hergebruik taal Invoker [/B] INSTELLING/XML komt niet overeen.\nJuiste status herstellen (AANBEVOLEN)?"

msgctxt "#33022"
msgid "No Trakt or IMDb Account Detected."
msgstr "Geen Trakt- of IMDb-account gevonden"

**Comment by Tinuz97** [comment]
Translations are fine above here @Tikipeter

**Comment by Tinuz97** [comment]
Trakt issue, or a bug in the new C test version? @Tikipeter 
![Screenshot_20200827-205749](https://user-images.githubusercontent.com/47715606/91483481-130d2600-e8a8-11ea-9d40-2e0e86870ab8.jpg)

**Comment by Tikipeter** [comment]
@Tinuz97 

Trakt issue. Hopefully fixed soon.

**Comment by Tikipeter** [comment]
Update 1.8.02d_testing posted just now in original comment has a settings monitor so should behave again just as normal. Settings changed in the settings dialog should be honored immediately.

Barring issues this may be the last test file. Some more things have been fixed for this test.

**Make sure you have reuse invoker set to TRUE when testing. You can see it's current status and change it if needed at the bottom of the Tools menu.**

Thanks to anyone testing.

**Comment by Tikipeter** [comment]
Version **1.8.02e**_testing posted in original post. Fair few more problems ironed out, mainly around handling playback issues as Kodi is more fussy with certain values when reusing the invoker.
If using widgets, might be best to restart Kodi before testing.
As always, make sure reuse invoker is set to TRUE.

Thanks to anyone testing.

**Comment by trkselim** [comment]
After update to 1.8.02e on beelink gt king pro with coreelec everything works fine 
And it’s really so fast

**Comment by Tikipeter** [comment]
Great. Thanks for the feedback @trkselim .

**Comment by jigoop1** [comment]
@Tikipeter 
late to the party , is there me only?
issue: 1
 when i try to rec-scrape and select from context menu it not showing selection dialog but start play.
issue:2
every time it resetting scraper stats.

**Comment by Tikipeter** [comment]
Thanks for testing @jigoop1 

I'll look into those issues.

**Comment by jigoop1** [comment]
@Tikipeter 
it's just typo since lot's change u may miss that. 
in file in_progress.py
line# 16 instead of 'special://home/addons/plugin.video.fen'
should be
"special://userdata/addon_data/plugin.video.fen"

**Comment by Tikipeter** [comment]
> in file in_progress.py...
Thanks @jigoop1 .Pasted the wrong thing there!
