### ISSUE TITLE
[QUESTION] Search paths

### ISSUE THREAD

**Issue by ivarbrandt** [Tikipeter/repository.tikipeter#255]
Hey Peter! Hope you're doing well.

I'm working on a new feature for FENtastic and I would like to know some info in order to be able to implement it.
I know this question has been asked before but after the Addons4Kodi subreddit went private, I'm having a hard time finding answers for this. 

What are the search paths for Fen for Movies, TV Shows, Collections (Movie Sets), People, IMDb Keywords (Movies), and IMDb Keywords (Shows)?

I found the paths for Movies and Shows somewhere else but if you can please include the most up to date ones, I would really appreciate it. Thanks man!

**Comment by TwilightMercy** [comment]
If it helps, I think you can add the path you want to Kodi "Favourites" menu (right click --> add to favourites)

And then you can see the path in userdata/favourites.xml

**Comment by ivarbrandt** [comment]
@TwilightMercy 

I appreciate your response. However those aren't exactly the kind of paths that I'm looking for. I'm looking for the ones that typically end in `query=`. For example, this is the path that I have for Movies:

`plugin://plugin.video.fen/?mode=build_movie_list&amp;action=tmdb_movies_search&amp;query=`

These paths allow me to append a string to the end of them in order to bring up the results for Movies for the string that was entered.

**Comment by Tikipeter** [comment]
MOVIES:  `plugin://plugin.video.fen/?mode=build_movie_list&amp;action=tmdb_movies_search&amp;query=`
TV SHOWS: `plugin://plugin.video.fen/?mode=build_tvshow_list&amp;action=tmdb_tv_search&amp;query=`
COLLECTIONS (MOVIE SETS): `plugin://plugin.video.fen/?mode=build_movie_list&amp;action=tmdb_movies_search_sets&amp;query=`
PEOPLE: Not possible
IMDB KEYWORDS (MOVIES): `plugin://plugin.video.fen/?mode=imdb_build_keyword_results&amp;media_type=movie&amp;query=`
IMDB KEYWORDS (SHOWS): `plugin://plugin.video.fen/?mode=imdb_build_keyword_results&amp;media_type=tvshow&amp;query=`

**Comment by ivarbrandt** [comment]
Thanks! I got some cool stuff coming up for FENtastic. It'll be available in the test repo by EOD. It'd be awesome if you could take a look and lemme know your thoughts on the changes.

**Comment by TwilightMercy** [comment]
I’m curious too!

**Comment by ivarbrandt** [comment]
That makes sense. I look forward to using the new path in the future!

For the paths that you gave me for IMDb keywords, they return a list of keywords and then you can click the chosen keyword and it'll load the list of movies/shows. What I want to be able to do is search the keyword directly. So for example, if the string I input is "alien", I want to see all the movies/shows associate with that keyword. Is there a way to do this with a different path?

**Comment by Tikipeter** [comment]
IMDB KEYWORDS (MOVIES): `plugin://plugin.video.fen/?mode=build_movie_list&amp;action=imdb_keywords_list_contents&amp;list_id=`
IMDB KEYWORDS (SHOWS): `plugin://plugin.video.fen/?mode=build_tvshow_list&amp;action=imdb_keywords_list_contents&amp;list_id=`

**Comment by ivarbrandt** [comment]
Awesome! I just added it to the skin 😃

**Comment by TwilightMercy** [comment]
Your collaboration and teamwork is what makes FEN + FENtastic combo the best Kodi experience.

**Comment by Tikipeter** [comment]
`3.1.14` just uploaded. Has the changes needed.

**Comment by ivarbrandt** [comment]
Yessss!

**Comment by ivarbrandt** [comment]
`1.0.12a` is up as well. I'm excited to hear your thoughts it.

**Comment by Tikipeter** [comment]
I spent a few days offline again with the whole Reddit blackout encouraging me to do so, so I'm late once again with replying here. Just like last time. :)

Anyway, I had a couple of things to point out from my initial testing of the changes, but you seem to have fixed them all with `d` versions, so only good things to say really.

I love the changes. There's lots of new python code in there which I'm really impressed with. You've been reading up it seems. :)

Everything works great with that code. The changes to order etc of the widgets work great. There's also a new database you're making storing the search results which is a great thing too.

I had to do an extra update to Fen when this was all happening, as I had left code in the direct person search that opened a new window for while I was testing it. So the first update of Fen broke your search window. Oops. I also added a Known For field in the "plot" of the result, so there was something to show there.

Great job @ivarbrandt 
The skin sure has it's own identity now more than ever.
Question is, what's next?

**Comment by ivarbrandt** [comment]
> There's lots of new python code in there which I'm really impressed with. You've been reading up it seems. :)

Thanks! I decided to stop being afraid of it and finally dove into the Helper. That kind of code is more complex than XML but I was able to learn a lot from your code so thank you! Plus I realized that's where all the cool stuff happens :)

> So the first update of Fen broke your search window. Oops. I also added a Known For field in the "plot" of the result, so there was something to show there.

I saw that the day you released it. I was like "oh boy I'm gonna have to tell Tikipeter tomorrow". But you pushed the fix before I could tell you so thank you. And thanks for adding something to show in the InfoPanel. It would look strange without it.

> The skin sure has it's own identity now more than ever. Question is, what's next?

I'm not entirely sure. I thought of adding ratings but just scheming that out in my head led to a lot of issues. I also thought of making a way to add sections to the home screen dynamically but that is gonna be tough and has quite a few challenges. So for now, I don't know. I'm focused on fixing a few more edge cases that I thought of and making sure everything I added is working correctly for the next release. What do you think? I'm all ears to any suggestions.

That being said, I did want to get your thoughts on some of the behavior from the code I've added. I will raise that soon in the previous "Supercharging FENtastic" thread. I hope you don't mind me reopening it.
