### ISSUE TITLE
shows list not in alphabetical order

### ISSUE THREAD

**Issue by ANHBOB** [Tikipeter/repository.tikipeter#255]
Hi Tikipeter.  Everything was working fine with Fen until last night Shadow had an update. After updating Shadow first I tried using Shadow and I was getting an Error, so I went back to Fen to watch some shows.  Now all my lists are not in alphabetical order.  In Fen settings I have Ignore Articles When Sorting Lists turned on and the lists still aren't in alphabetical order.  I even tried turning it off, backing out of Kodi, clearing cache, going back into kodi> re-enable the setting but it still doesn't work.  I'm not sure why updating Shadow would change Fen settings?

**Comment by Tikipeter** [comment]
Changes due to a Shadow update are conincidental.
Trakt are having issues with their API, causing issues such as yours.
We have to wait it out.

**Comment by ANHBOB** [comment]
Hi and thanks for the reply.  After I wrote this I saw Trakt were having issues and had updated their services. I thought that may have been the problem.  Keep up the great work. It's very much appreciated.

**Comment by Tikipeter** [comment]
I'll leave this here until (hopefully) Trakt shows itself as the culprit.

**Comment by SJ50** [comment]
my trakt list order is date added  but FEN shows all list (even liked and lists shown by FEN) by rank. Is this related?

**Comment by ANHBOB** [comment]
I checked other addons I have installed and it seems like the only addon affected is Fen with not showing things in alphabetical order. Besides Fen I also have the Crew and Shadow installed. I have the 4K Firestick running latest Kodi 18.8 .  I tried turning off Ignore Articles When Sorting Lists, then backing out of Kodi, clearing cache open again and tried to enable it but it didn't help.  

 When I go into my Trakt>wishlist>movies...that is in alphabetical order, but I have a couple of lists I created for TV shows.  So it's a custom list....DB's TV list.....that is the one NOT in alphabetical order.  It's strange 1 is fine and the other isn't.  AND before I updated Shadow everything was fine. Just saying.

**Comment by Tikipeter** [comment]
Perhaps the other addons have an older cache, from before this happened.

Here is the header information sent by Trakt to Fen for an MCU list I have which is sorted by Release Date and always has been.

```
{'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'X-Request-Id': 'a4c3a6f9-080d-4df3-864d-06e0b27dcf0d', 'CF-Cache-Status': 'DYNAMIC', 'Content-Length': '7594', 'Etag': 'W/"3d18dd54217b95fd315468bd0bb890cd"', 'X-Permitted-Cross-Domain-Policies': 'none', 'X-Pagination-Item-Count': '24', 'X-Frame-Options': 'SAMEORIGIN', 'X-Download-Options': 'noopen', 'X-Sort-How': 'asc', 'cf-request-id': '04e2cbe3fc0000fd2e01860200000001', 'X-Runtime': '0.029882', 'X-Sort-By': 'rank', 'X-Pagination-Page-Count': '1', 'Date': 'Sun, 30 Aug 2020 21:08:02 GMT', 'CF-RAY': '5cb17c19995cfd2e-SYD', 'Cf-Railgun': '09bbfd5276 0.14 0.048252 0030 57da', 'X-Applied-Sort-How': 'asc', 'X-Xss-Protection': '1; mode=block', 'Set-Cookie': '__cfduid=d83c5a434aac2599730277e94e459de561598821682; expires=Tue, 29-Sep-20 21:08:02 GMT; path=/; domain=.trakt.tv; HttpOnly; SameSite=Lax', 'Server': 'cloudflare', 'Connection': 'keep-alive', 'X-Applied-Sort-By': 'rank', 'X-Pagination-Page': '1', 'X-Content-Type-Options': 'nosniff', 'Content-Encoding': 'gzip', 'X-Private-User': 'false', 'Vary': 'Accept-Encoding', 'Cache-Control': 'max-age=0, private, must-revalidate', 'Referrer-Policy': 'strict-origin-when-cross-origin', 'Content-Type': 'application/json; charset=utf-8'}
```

The `X-Sort-How` is being returned as `rank`, even though I have it set to `release date` on the Trakt website.

The API is returning the wrong information. There is nothing I can do until they fix it.

**Comment by ANHBOB** [comment]
Ok thanks for letting me know. It's not that big a deal if the order is wrong.  I just thought it was a bug

**Comment by Tikipeter** [comment]
I'm keeping an eye on this, but that header info is what we have to use to determine the users sort type and order.

The Watchlist and Collection are sorted by Fen always alphabetically. Atleast I think that's the case. I haven't been into that code in a while and I'm not at the computer atm.

Even though it doesn't make sense to me, users often have success with fixing Trakt "glitches" by reauthing their account. Perhaps thats worth a try here too.

**Comment by Tikipeter** [comment]
@ANHBOB @SJ50 

Trakt have indicated the sorting issues with their API should be fixed within the next 24 hours.

I would wait that long, and then clear the Trakt cache in Fen and hopefully it will then be working correctly.

**Comment by SJ50** [comment]
@Tikipeter Thank you for update.

**Comment by ANHBOB** [comment]
@Tikipeter   I wanted to thank you for the update. The trakt issue has been fixed. Everything is working as it should be and faster.
