### ISSUE TITLE
No Issue :)

### ISSUE THREAD

**Issue by flhthemi** [Tikipeter/repository.tikipeter#258]
I just wanted to say since the addition of the invoker, man talk about fast! Windows and Android installs here work much faster! I cleared all the caches and then pulled a list from trakt of about 200 movies and it was like 3 seconds!

The only issue I had was a fen error when I tried to bring up the tool menu item for the invoker. I would toss an error. A restart of Kodi seems to stop that.

Thanks boss! It was a great improvement, at least for me!

**Comment by Tikipeter** [comment]
Glad somebody's happy!
Thanks for the report @flhthemi . Appreciated.

**Comment by xyzfre** [comment]
Definitely agree it is working much FASTER!! on my end as well using a Nvidia Shield Pro ,,I appreciate all the hard work my friend,I got a similar error but after clearing the Settings cache And a reboot everything is working perfect

**Comment by Tikipeter** [comment]
Thanks as well @xyzfre . Appreciated.
