### ISSUE TITLE
telegram server

### ISSUE THREAD

**Issue by The-cpu-max** [Tikipeter/repository.tikipeter#259]
There is a lot of content that is in Telegram and can enrich FEN and improve it significantly
There is an ADD-ON called telemedia
Is it possible to add it to the host? As an additional server search?
Also does not require REAL DEBRID

**Comment by Tikipeter** [comment]
Too much work for me I'm afraid.

I'm semi-retired from Fen at the moment.

**Comment by The-cpu-max** [comment]
> Too much work for me I'm afraid.
> 
> I'm semi-retired from Fen at the moment.

I added the source to cocoscrapers
It displayed all the results from Telegram - but when I try to play a movie it just doesn't play them
what could be the problem ?

# -*- coding: utf-8 -*-
'''
    cocoscrapers Project
'''

import re,xbmc

from cocoscrapers.modules import cfscrape
from cocoscrapers.modules import client
from cocoscrapers.modules import source_utils
import random
import logging
import requests
import urllib,logging,base64,json

try:
    import xbmcaddon
    resuaddon=xbmcaddon.Addon('plugin.video.telemedia')
    listen_port=resuaddon.getSetting('port')
except:
    pass
class source:
    priority = 26
    pack_capable = False
    hasMovies = True
    hasEpisodes = True
    def __init__(self):
        self.language = ['en']
        self.base_link = "https://rlsbb.cc/"
#		self.base_new = "http://proxybb.com/"
#		self.base_old = "http://old3.proxybb.com/"
        self.search_link = "https://search.rlsbb.cc/?s=%s" #may use in future but adds a request to do so.
        

    def res_q(self,quality):
        f_q=' '
        if '4k' in quality.lower():
            quality='2160'
        if '2160' in quality:
          f_q='2160'
        elif '1080' in quality:
          f_q='1080'
        elif '720' in quality:
          f_q='720'
        elif '480' in quality:
          f_q='480'
       
        elif '360' in quality or 'sd' in quality.lower():
          f_q='360'
        elif '240' in quality:
          f_q='240'
        elif 'hd' in quality.lower() or 'hq' in quality.lower():
          f_q='480'
        return f_q
    
    def fix_q_links(self,quality):
        f_q=100
        if '4k' in quality.lower():
            quality='2160'
        if '2160' in quality:
          f_q=1
        if '1080' in quality:
          f_q=2
        elif '720' in quality:
          f_q=3
        elif '480' in quality:
          f_q=4
        
        elif '360' in quality or 'sd' in quality.lower():
          f_q=6
        elif '240' in quality:
          f_q=7
        elif 'hd' in quality.lower() or 'hq' in quality.lower():
          f_q=8
        return f_q
    def get_q(self,name):
        q=self.res_q(name)
        loc=self.fix_q_links(q)

        return q,loc
    def search(self,tmdb,type,last_id_pre,search_entered_pre,icon_pre,fan_pre,season,episode,no_subs=0,original_title='',heb_name='',dont_return=True,manual=True):
        
        last_id=last_id_pre.split('$$$')[0]
        last_id_msg=last_id_pre.split('$$$')[1]
      
        query=search_entered_pre

        query=query.replace('%20',' ').replace('%27',"'").replace('%3a',":")
        
        
        num=random.randint(1,10001)
        all_links=[]
        if type=='all':
            data={'type':'td_send',
                 'info':json.dumps({'@type': 'searchMessages', 'query': query,'offset_message_id':last_id,'offset_chat_id':last_id_msg,'limit':100, '@extra': num})
                 }
        
            event=requests.post('http://127.0.0.1:%s/'%listen_port,json=data).json()
            
            if 'messages' not in event:
                time.sleep(0.1)
                num=random.randint(1,10001)
                
                data={'type':'td_send',
                 'info':json.dumps({'@type': 'searchMessages', 'query': query,'offset_message_id':last_id,'offset_chat_id':last_id_msg,'limit':100, '@extra': num})
                 }

                event=requests.post('http://127.0.0.1:%s/'%listen_port,json=data).json()
            counter_ph=0
            for items in event['messages']:  
                # logging.warning('433333333 '+str(items))
                
                if 'document' in items['content']:
                    name=items['content']['document']['file_name']
                    if '.mkv' not in name and '.mp4' not in name and '.avi' not in name:
                        continue
                    size=items['content']['document']['document']['size']
                    f_size2=str(round(float(size)/(1024*1024*1024), 2))+' GB'
                    q,loc=self.get_q(name)
                    link_data={}
                    link_data['id']=str(items['content']['document']['document']['remote']['id'])
                    link_data['m_id']=items['id']
                    link_data['c_id']=items['chat_id']
                    f_lk=json.dumps(link_data)
                    all_links.append((name, f_lk,3,q,loc, icon_pre,fan_pre,f_size2,no_subs,tmdb,season,episode,original_title))
                    #addLink( name, str(items['content']['document']['document']['id']),3,False, icon_pre,fan_pre,f_size2,data=data,no_subs=no_subs,tmdb=tmdb,season=season,episode=episode,original_title=original_title)
                    
                if 'video' in items['content']:
                        
                        name=items['content']['video']['file_name']
                        
                        size=items['content']['video']['video']['size']
                        f_size2=str(round(float(size)/(1024*1024*1024), 2))+' GB'
                        
                        q,loc=self.get_q(name)
                        link_data={}
                        link_data['id']=str(items['content']['video']['video']['remote']['id'])
                        link_data['m_id']=items['id']
                        link_data['c_id']=items['chat_id']
                        f_lk=json.dumps(link_data)
                        all_links.append(( name, f_lk,3,q,loc, icon_pre,fan_pre,f_size2,no_subs,tmdb,season,episode,original_title))
                        #addLink( name, str(items['content']['video']['video']['id']),3,False, icon_pre,fan_pre,f_size2,tmdb=tmdb,season=season,episode=episode,original_title=original_title)
                
                if 'caption' in items['content']:
                        txt_lines=items['content']['caption']['text'].split('\n')
                        all_l=[]
                        name=txt_lines[0]
                        rem_lines=[]
                        for lines in txt_lines:
                            if 'upfile' not in lines and 'drive.google' not in lines:
                              rem_lines.append(lines)
                              continue
                            
                                
                            all_l.append(lines)
                        if len(all_l)==0:
                            continue
                        icon=icon_pre
                        fan=fan_pre
                        
                               
                        q,loc=self.get_q(name)
                        all_links.append(('[COLOR lightgreen]'+ txt_lines[0]+'[/COLOR]' , '$$$'.join(all_l),9,q,loc, icon,fan,('\n'.join(rem_lines)).replace('\n\n','\n'),no_subs,tmdb,season,episode,original_title))
                        #addLink( '[COLOR lightgreen]'+ txt_lines[0]+'[/COLOR]' , '$$$'.join(all_l),9,False, icon,fan,('\n'.join(rem_lines)).replace('\n\n','\n'),no_subs=no_subs,tmdb=tmdb,season=season,episode=episode,original_title=original_title)
                        
                elif 'web_page' in items['content']:
                    name=items['content']['web_page']['title']
                    link=items['content']['web_page']['url']
                    plot=items['content']['web_page']['description']['text']
       
                    if 'upfile' not in link and 'drive.google' not in link:
                          
                          continue
                    icon=icon_pre
                    fan=fan_pre
                    
                
                    q,loc=self.get_q(name)
                    
                    all_links.append(('[COLOR lightgreen]'+ name+'[/COLOR]', link,9,q,loc, icon,fan,plot.replace('\n\n','\n'),no_subs,tmdb,season,episode,original_title))
                    #addLink( '[COLOR lightgreen]'+ name+'[/COLOR]', link,9,False, icon,fan,plot.replace('\n\n','\n'),no_subs=no_subs,tmdb=tmdb,season=season,episode=episode,original_title=original_title)
                f_id=items['chat_id']
        
        return all_links
    def sources(self, data, hostDict):
        sources = []
        if not data: return sources
        append = sources.append

        title = data['tvshowtitle'] if 'tvshowtitle' in data else data['title']
        title = title.replace('&', 'and').replace('Special Victims Unit', 'SVU').replace('/', ' ')
        aliases = data['aliases']
        episode_title = data['title'] if 'tvshowtitle' in data else None
        year = data['year']
        hdlr = 'S%02dE%02d' % (int(data['season']), int(data['episode'])) if 'tvshowtitle' in data else year
        logging.warning('DSDSDdataASSSSS '+str(data))
        

        tmdbKey='653bb8af90162bd98fc7ee32bcbbfb3d'

        if 'tvshowtitle' in data:
           imdb=data['imdb']
           
           url1='https://'+'api.themoviedb.org/3/find/%s?api_key=34142515d9d23817496eeb4ff1d223d0&external_source=imdb_id&language=%s'%(imdb,'he')
           t1=requests.get(url1,timeout=10).json()
           id=str(t1['tv_results'][0]['id'])
           url2='http://api.themoviedb.org/3/tv/%s?api_key=%s&append_to_response=external_ids&language=he'%(id,tmdbKey)
           n_value='name'
        else:
           imdb=data['imdb']
           url2='http://api.themoviedb.org/3/movie/%s?api_key=%s&append_to_response=external_ids&language=he'%(imdb,tmdbKey)
           n_value='title'

        try:
            name=requests.get(url2,timeout=10).json()[n_value]
        except:
            name=title

        original_title=title
        heb_name=name
        
        o_name=name
        f_all_links=[]
        all_names=[]
        tv_movie='movie'
        id=''
        type='all'
        last_id_pre='0$$$0'
        count = 0
        if 'tvshowtitle' in data:
            season=data['season']
            episode=data['episode']
            season_n=data['season']
            episode_n=data['episode']
            c_original=original_title.replace('%20','.').replace(' ','.').replace('%27',"'").replace("'","").replace('%3a',":")
            options=[heb_name+' ע%s פ%s'%(season,episode),heb_name+' ע%sפ%s'%(season,episode),heb_name+' עונה %s פרק %s'%(season,episode),c_original+'.S%sE%s'%(season_n,episode_n),c_original+'.S%sE%s'%(season,episode),c_original.replace('&','and')+'.S%sE%s'%(season,episode),c_original.replace('&','and')+'.S%sE%s'%(season_n,episode_n)]
            #if 'the' in original_title.lower():
            #    options.append(c_original.replace('The','').replace('the','')+'.S%sE%s'%(season_n,episode_n))
            options2=[' ע%s פ%s'%(season,episode),'ע%s.פ%s'%(season,episode),' ע%sפ%s'%(season,episode),' עונה %s פרק %s'%(season,episode),'.S%sE%s'%(season_n,episode_n),'.S%sE%s'%(season,episode)]
            all_links=[]
   
            try:
                for items in options:
                    # log.warning('Searching:'+items)
                    all_links=all_links+self.search(id,'all','0$$$0',items,'','',season,episode,no_subs=1,original_title=original_title,heb_name=name,dont_return=False,manual=False)
            except Exception as e:

                pass
            
            exclude=[]
     
            for  name, link,mode,q,loc, icon,fan,plot,no_subs,tmdb,season,episode,original_title in all_links:
                ok=False

 
                if base64.b64encode(name.encode("utf-8")).decode("utf-8") in all_names:
                    continue
                
                all_names.append(base64.b64encode(name.encode("utf-8")).decode("utf-8"))
                for items in options2:
                    t_items=items.replace(' ','.').replace(':','').replace("'","").replace('-','.').replace('[','').replace(']','').replace('..','.').lower()
                    t_name=name.replace('"',"").replace('  ',' ').lower().replace('-','.').replace(' ','.').replace('[','').replace(']','').replace('_','.').replace(':','').replace("'","").replace('..','.')
                    t_items2=c_original.replace(' ','.').replace(':','').replace("'","").replace('-','.').replace('[','').replace(']','').replace('..','.').lower()
         
                    if (t_items+'.'  in t_name+'.') or (t_items+' '  in t_name+' ') or (t_items+'_'  in t_name+'_') or (t_items.replace('.','_')+'_'  in t_name.replace('.','_')+'_') or (t_items.replace('.','-')+'_'  in t_name.replace('.','-')+'_'):
                       if (o_name in name) or (t_items2 in t_name):
                        ok=True
                        break

                if not ok:
                    color='red'
                    exclude.append((name, link,mode,q,loc, icon,fan,plot,no_subs,tmdb,season,episode,original_title))
                else:
                     color='white'
                if 'upfile' not in link and 'drive.google' not in link:
                
                    plot=plot
                else:
                    plot=plot
                try:
                     o_size=plot
                     
                     plot=float(o_size.replace('GB','').replace('MB','').replace(",",'').strip())
                     if 'MB' in o_size:
                       plot=plot/1000
                except Exception as e:
                    
                    plot=0
        
                name=name.replace('_','.')
                host='rapidgator.net'
                name_info=name.replace('_','.')
                info=plot
                quality=q+'p'
                url=link
                
                append({'provider': 'telemedia', 'source': host, 'name': name, 'name_info': name_info, 'quality': quality, 'language': 'en', 'url': url,
                                'info': info, 'direct': False, 'debridonly': True, 'size': plot})
                count += 1
                
        else:
       
       
            all_links=[]
            season=''
            episode=''
            all_links=self.search(id,type,last_id_pre,name,'','',season,episode,no_subs=0,original_title=original_title,dont_return=False,manual=False)
            

            all_links=all_links+self.search(id,'all','0$$$0',original_title,'','',season,episode,original_title=original_title,dont_return=False,manual=False)
            
            all_links=sorted(all_links, key=lambda x: x[4], reverse=False)
            
            for  name, link,mode,q,loc, icon,fan,plot,no_subs,tmdb,season,episode,original_title in all_links:
                if base64.b64encode(name.encode("utf-8")).decode("utf-8") in all_names:
                    continue
                all_names.append(base64.b64encode(name.encode("utf-8")).decode("utf-8"))
                if 'upfile' not in link and 'drive.google' not in link:
                    plot=plot
                else:
                    plot=plot
                try:
                     o_size=plot
                     plot=float(o_size.replace('GB','').replace('MB','').replace(",",'').strip())
                     if 'MB' in o_size:
                       plot=plot/1000
                except Exception as e:
                    
                    plot=0
                name=name.replace('_','.')
                host='rapidgator.net'
                name_info=name.replace('_','.')
                info=plot
                quality=q+'p'
                url=link
                
                append({'provider': 'telemedia', 'source': host, 'name': name, 'name_info': name_info, 'quality': quality, 'language': 'en', 'url': url,
                                'info': info, 'direct': False, 'debridonly': True, 'size': plot})
                count += 1

        return sources

**Comment by umbrellaplug** [comment]
I'm interested in this one. I don't have any telegram "sources" though.

**Comment by TwilightMercy** [comment]
I'm against using Telemdia as FEN source - it will stray the addon from being dedicated to premium services.

**Comment by umbrellaplug** [comment]
> I'm against using Telemdia as FEN source - it will stray the addon from being dedicated to premium services.

Understand, but cocoscrapers is used in more than one project. I already support Plex and others that are outside of the "premium" services bucket, so adding to the scrapers is something that could potentially be done then each addon developer can decide if they choose to support that or not. Same way Plex and GDrive are being done now. 

Why would you ever be against more sources though?

**Comment by The-cpu-max** [comment]
> I'm against using Telemdia as FEN source - it will stray the addon from being dedicated to premium services.

On the contrary, there are exclusive things that are available on Telegram, for example dubbed content, movies with built-in subtitles that are only available on Telegram
Sometimes there is a chapter that hasn't been translated yet and that's where it is
There is nothing wrong with that if it is
And it will be possible to have two separate lines for Premium and Telegram
I'm not talking about junk servers - this is a good product

**Comment by ReaLx3m** [comment]
> I'm against using Telemdia as FEN source - it will stray the addon from being dedicated to premium services.

I would understand being against if it would only get low quality sources. So is that the case with pulling stuff from telegram, have you tried that telemedia thing?

**Comment by The-cpu-max** [comment]
> > I'm against using Telemdia as FEN source - it will stray the addon from being dedicated to premium services.
> 
> Understand, but cocoscrapers is used in more than one project. I already support Plex and others that are outside of the "premium" services bucket, so adding to the scrapers is something that could potentially be done then each addon developer can decide if they choose to support that or not. Same way Plex and GDrive are being done now.
> 
> Why would you ever be against more sources though?

Do you have any idea about the code?
Why doesn't he turn on the player?
It shows the sources but does not activate
