### ISSUE TITLE
Announcement: Support for Free Hosters Most Likely to be Dropped from Fen.

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/repository.tikipeter#259]
With the recent big changes to Fen's handling of settings and enabling of the languageinvoker looking to be stabilized, the next step I'm likely undertaking is a removal of ResolveURL dependency within Fen. This has been a long time coming, but has been put off repeatedly until now.

For people with a Furk, Easynews or debrid (RD/PM/AD) account, there will still be cached and uncached torrent results, and hoster results for hosts that are supported by your debrid account. I will be adding support for hopefully a couple of other debrid services in the near future.

For current users without any premium account of any sort, I'm afraid Fen will soon no longer be of use to you. Development/maintenance of free hoster scrapers in Openscrapers is non existent, and even if the free scrapers were being maintained, the state of free hoster services is dire since Openload was shut down.

Each week free sites scraped by Openscrapers are moving behind the new cloudflare challenge that has not been cracked, making scraping of those sites practically impossible. The days of free, decent quality and speed links is all but over.

**This announcement is to give any users who don't have a premium account some time to find and begin using an alternative add-on. Whilst it's normally no trouble switching to a different add-on, there may be users who have made a Kodi library from Fen strm files. These will soon no longer be of use if you rely only on free streams.**

Anyone with knowledge of decent add-ons that support the scraping of free links is encouraged to write any recommendations below for anyone looking for an alternative.

Of course, anyone with an opinion on the matter is also encouraged to write below.

**Comment by ANHBOB** [comment]
I think it's a good idea to remove the free scrapers. It will probably improve Fen.  I only used free scarpers when I first started with Kodi before I found out about Real Debrid.  I've been using RD for a few years now and it's well worth the small fee they charge.

**Comment by bjgood** [comment]
I wish you'd reconsider this decision. Some people/families simply can't afford the additional monthly expense of a debrid account.

I will say that Fen was a breathe of fresh air when I tried it a few months ago. Very original.

**Comment by ANHBOB** [comment]
@bjgood   The cost is less than $1 per week USD.  I pay around $20 USD for 6 months of service which is only about $3.33 a month. If you can't afford that, there are plenty of other addons that can be used.

**Comment by Junkdewd** [comment]
I agree.  Screw free hosters.  They are useless and unreliable now, due to all the changes in the technology.  Use any of the 3 dozen add-ons that will still support the few free hosters left.   I'm glad to see a developer make a change for the better.

**Comment by pcliff069** [comment]
I am more of a Torrent person than a debrid one - if that makes any sense. The reason I didn't use Debrid was that the free scrapers were basically useless. Since discovering Real Debrid I have cerainly changed my outlook. Fen is one fantastic addon with an excellent developer. Real Debrid is not expensive and works well. The free scrapers seem to me to be more of a hindrance than a help. I fully support the action.

**Comment by jigoop1** [comment]
@Tikipeter 
I wish also you would reconsider this decision. i understand there is very fewer free hosters available now a day.
i started to learning python. as per my limited knowledge addon have separate modules for external_source_utils and external scrapers. some of module interact with other obviously but if u can keep option open it would be great in my humble opinion. 
But hey you can do as you feel easiest to maintain the addon. I really appreciate your hard work no matter which way you decide.
