### ISSUE TITLE
No module named settings_reader

### ISSUE THREAD

**Issue by SJ50** [Tikipeter/repository.tikipeter#260]
I tried to installed addon on my friends Android TV after installation I got error saying “no module named settings_reader”. 
Kodi 18.8 fresh install. 
https://paste.kodi.tv/vabicuwuvi

Edit - even I deleted org.xbmc.kodi folder and tried again.

**Comment by Tikipeter** [comment]
Stupid mistake. The module is setting_reader.

Ill be home in a couple of hours and will push a fix for this.

**Comment by Tikipeter** [comment]
1.8.07a should fix this error.
