### ISSUE TITLE
Could you please explain what you meant   Question

### ISSUE THREAD

**Issue by ANHBOB** [Tikipeter/repository.tikipeter#261]
In Version 1.8.07 you say  "Converted pre-scrape results to a directory when directory display set. You must click START FULL SCRAPE  to decline the pre-scraped results.

In my settings>Results>Results Display  is set to Directory,  BUT I do not see how to START FULL SCRAPE?

Thank you for your time in making Fen the best addon out there.

**Comment by Tinuz97** [comment]
Good question, I did not understand this one either. 😅

**Comment by ANHBOB** [comment]
I checked the Tips for Fen use and didn't see anything in there

**Comment by Tikipeter** [comment]
With Fen's internal scrapers, some you are able to enable a setting "Check Before Search". The scrapers that have this option are all scrapers that return physical media that you have ripped/downloaded. The scrapers are "Local Library, Downloads and Folders 1-5".

If you have this set, then Fen will check these scrapers first, before performing a full scrape using all the enabled scrapers. It allows you to check if you have a local copy of a movie/episode before using the "online" scrapers to get sources.

In the past, Fen would display any results from this "Pre-Scrape" as a dialog, where you could either select the result/s found, or press back and then Fen would perform a full search.

With the update, Fen now displays the pre-scrape results as a directory, just like the full scrape results, and you need to select START FULL SCRAPE to reject the found local result and instead search using all scrapers.

e.g.

I have a copy of Avengers: Endgame on my NAS. I've told Fen to perform a pre-scrape, so it will first check the folders I assigned. It finds Avengers Endgame and displays this locally found result:
![screenshot000](https://user-images.githubusercontent.com/28930002/92338334-177cde80-f0f3-11ea-9016-819bad4cce41.png)

I would then select START FULL SCRAPE to reject the result and perform a scrape using all scrapers:
![screenshot001](https://user-images.githubusercontent.com/28930002/92338366-41360580-f0f3-11ea-9d9d-dbcec9c922a9.png)

Which would then search using all scrapers and return the result:
![screenshot002](https://user-images.githubusercontent.com/28930002/92338394-6fb3e080-f0f3-11ea-8064-eb0d6404d2a2.png)


I hope that explains it.

**Comment by Tinuz97** [comment]
Nice, thx for the explanation.

**Comment by ANHBOB** [comment]
Thank you for explaining this.
