### ISSUE TITLE
Fen does not diplay the correct video.

### ISSUE THREAD

**Issue by OmerB89** [Tikipeter/repository.tikipeter#263]
When searching for X-Men First Class the real debrid 1080p, x265,  6.58gb from tigole shows a 24 minutes video instead of the movie.
On stremio it shows the correct video.
4 others video from real debrid from The Lord of the Rings The Fellowship of the Rings do the same thing and shows a 1 hour movie instead of the full movie:
 1. 4k 26.45gb 
 2. 4k 23.98gb 
 3. 1080p 17.35gb 
 4. 1080p x265 16.7gb
 
are also problematic.

Some of the movies are being shown properly on stremio when there is a similar result from stremio using torrentio.
Also happen in several videos in Lord of the Rings The Two Towers.

I am not sure if fen choosing the wrong video from the torrent or is it the scraper.
I will look for more problematic editions in lord of the rings and x-men and update the post.

2 examples of problematic videos:
![fdsfsd](https://github.com/Tikipeter/repository.tikipeter/assets/78074702/069d0f20-404f-4509-8a12-b9adcf4ed035)

**Comment by adamosborne83** [comment]
This has nothing to do with Fen, it is to do with the scraping and the file.

**Comment by Tikipeter** [comment]
That doesn't look like Fen to me.

**Comment by OmerB89** [comment]
![abc](https://github.com/Tikipeter/repository.tikipeter/assets/78074702/a4fa22b8-d6d1-4028-8d1a-13151d8ad67d)

Fen with fentastic skin using real debrid.
If it is the scraper who sould I contact?

**Comment by OmerB89** [comment]
> That doesn't look like Fen to me.

It is Fen. I just upload an image.

**Comment by OmerB89** [comment]
> This has nothing to do with Fen, it is to do with the scraping and the file.

Than who sould I contact? Can you give please a github link?

**Comment by Tikipeter** [comment]
This is not any version of Fen that I've ever released.

Where did you get it and who supplied it to you?

**Comment by OmerB89** [comment]
I will upload the version number from the addons.... one minute

**Comment by OmerB89** [comment]
> This is not any version of Fen that I've ever released.
> 
> Where did you get it and who supplied it to you?

![תמונה](https://github.com/Tikipeter/repository.tikipeter/assets/78074702/569ebb7b-4bb3-42c7-8b88-0d9fce36a48b)

![תמונה](https://github.com/Tikipeter/repository.tikipeter/assets/78074702/43cefade-0a30-4f08-b884-c9ed99861140)

**Comment by OmerB89** [comment]
> This is not any version of Fen that I've ever released.
> 
> Where did you get it and who supplied it to you?

I took a couple of pictures from my addons build. It is free and just add subtitle in my language and some translation.

**Comment by TwilightMercy** [comment]
> > This is not any version of Fen that I've ever released.
> > Where did you get it and who supplied it to you?
> 
> I took a couple of pictures from my addons build. It is free and just add subtitle in my language and some translation.

Please read my Telegram message, you're missing the point

**Comment by Tikipeter** [comment]
Where have the posts gone that were here?

Where did you get this version of Fen, and from whom did you get it from?

**Comment by OmerB89** [comment]
It is from a public forum from my country. It is giving extra detail on subtitle. I will install the original. I did not know there are changes.
A moment I will install the original and disable the subtitle addon and give you pictures from the original build.

**Comment by OmerB89** [comment]
The movies are still has problem after I reinstall your addon without subtitles 2nd and 3rd result for example :

![תמונה](https://github.com/Tikipeter/repository.tikipeter/assets/78074702/d48b2555-6441-4eb5-b99b-48e73c7d5816)

**Comment by Tikipeter** [comment]
I don't care about that.

I want to know the web address of where you downloaded/installed the build containing the modified  version of Fen.

**Comment by Tikipeter** [comment]
Silence. That's what I thought.

**Comment by OmerB89** [comment]
> Silence. That's what I thought.

Although I am only using Kodi to watch Linux installation guides and only downloading to my computer linux distributions and sharing it with others not everyone are like me.
Those groups sometimes would prefer to remain anonymous. It is not my work and I need to ask permission to share it.
Anyway I really appreciate your work and that you are keeping it open source and wish you a happy weekend.
Thank you for your hard work.
Spending so many hours to help others and keeping it open source is really kind from you.
So thank you again and have a nice weekend.

**Comment by OmerB89** [comment]
> Silence. That's what I thought.

Although I am only using Kodi to watch Linux installation guides and only downloading to my computer linux distributions and sharing it with others not everyone are like me.
Anyway I really appreciate your work and that you are keeping it open source and wish you a happy weekend.
Thank you for your hard work.
Spending so many hours to help others and keeping it open source is really kind from you.
So thank you again and have a nice weekend.
