### ISSUE TITLE
Colors and labels according to versions in fen

### ISSUE THREAD

**Issue by The-cpu-max** [Tikipeter/repository.tikipeter#264]
![image](https://github.com/Tikipeter/repository.tikipeter/assets/102416233/4f80c4f5-2a60-4105-851c-ca61ddb6d77f)
Hi there are movies that contain different options such as IMAX
Dolby Vision
HDR
Extended version
and give the user a different viewing experience. The problem is that you always have to look for the movie among the multitude of movies that exist here
I would appreciate it if you could make a label above everything
For example versions with IMAX will be together and a different color,
After it is an extended version if there is one - a different color as well
This means that the results will not be together, and in the same color because it is very difficult to find the version that I would like to choose if I watch one of the movies

**Comment by Tikipeter** [comment]
Why is the screen so dark?

**Comment by The-cpu-max** [comment]
> Why is the screen so dark?

Wrong screenshot 
![screenshot00000](https://github.com/Tikipeter/repository.tikipeter/assets/102416233/82c21282-e6d2-4c98-befd-d3f5c5b6ed5c)

**Comment by Tikipeter** [comment]
That's better.

Looks fine how it is s.
