### ISSUE TITLE
Internal scrappers

### ISSUE THREAD

**Issue by pcliff069** [Tikipeter/repository.tikipeter#265]
More a question of how / when than a major (or even minor) issue.

Added a couple of shows today that should show up on two directories (folders) I have set up for internal scrappers (one windows, the other synology).
For some reason these shows are not showing up - older shows in the same directories show up no problem.
Is there anyway I can force a refresh?
I'm in Asia\Bangkok timezone - not sure if that has any relationship to when they show up - using Trakt also.

**Comment by Tikipeter** [comment]
If you write the structure of the folders (i.e. the full path) that should show me why they aren't showing.

**Comment by pcliff069** [comment]
Worked it out. Sonarr was selocating to folders labelled "n" (eg 1,2 etc) - moved them to Season n and all are now being picked up.
Plex was picking them up and Fen wasn't .
Can close off -
