### ISSUE TITLE
all addon stopped working

### ISSUE THREAD

**Issue by cabban** [Tikipeter/repository.tikipeter#266]
dont know  whats happened  nothing loads, it goes fast without no sources:/ or scrapers , is it a setting i missed etc ? please help @Tikipeter :)

**Comment by Tikipeter** [comment]
I don't know what it could be cabban.

**Comment by boftain** [comment]
only on apple tv with last update its search local & download only no source

1.7.12a work fine

**Comment by cabban** [comment]
still i tap a show it loads then none all is blank :(  @Tikipeter
