### ISSUE TITLE
FENtastic being used as default skin for build

### ISSUE THREAD

**Issue by ivarbrandt** [Tikipeter/repository.tikipeter#267]
Hey Peter,

I've been following what's happening regarding FEN being used as the default addon in a build and I have some questions as I'm pretty sure FENtastic is being used as the default skin for that build as well. 

If a lot of individual people are using FENtastic (that is people that aren't using a build), I generally don't mind. However, there are 5K+ plus users in that build and since my name is tied to my skin, I want to know what do think would be the best course of action? 

Because if that build is targeted in the future, I don't want my name anywhere near it. 

Also, please let me know if there is any way I can help.

**Comment by Tikipeter** [comment]
You are fine. There is absolutely nothing wrong with providing a Kodi skin. There can be no consequences for you in this. You could ask for your name to be changed for your skin within the build, but it's not necessary. TeamKodi members past and present have their skins used in builds with their names front and centre.

I'll work with TwilightMercy to fix what I need to have fixed, and then there'll be no issues. :)
And you can chill and follow along. :) :)

>Also, please let me know if there is any way I can help.

Appreciate it, but it should be fine. Your skin calls plugin.video.fen for certain things, so I've got that in my head when helping to sort this out. The addon name can change from Fen to Twilight without the addon's id changing. That'll mean your skin can stay as it is.

**Comment by ivarbrandt** [comment]
Ok good to know. Thank you. I'm chillin now :)

I appreciate you Peter.
