### ISSUE TITLE
[Bug] Download function renames files in the wrong way

### ISSUE THREAD

**Issue by tundrablasen** [Tikipeter/repository.tikipeter#268]
If you use FEN‘s build in download function (pack download etc) some files are wrongly renamed. It includes the previous (season) folder in the Filename.

`VideoPlayer::OpenFile: /storage/6499-7427/media/tv/The Newsroom (2012)/Season 03/Season 3The.Newsroom.S03E06.What.Kind.of.Day.Has.It.Been.1080p.10bit.BluRay.AAC5.1.HEVC-Vyndros.mkv `

Original torrent file structure:
![IMG_0469](https://github.com/Tikipeter/repository.tikipeter/assets/46343142/2066173b-f3eb-4bbf-b35a-5669666256c3)
![IMG_0470](https://github.com/Tikipeter/repository.tikipeter/assets/46343142/3a778125-2e8b-4ea1-9bc7-f9136a50b3ce)

It happens for example on this torrent:
https://www.1337x.to/torrent/2696174/The-Newsroom-2012-Seasons-1-3-S01-S03-Complete-Series-1080p-BluRay-x265-HEVC-10bit-AAC-5-1-Vyndros-UTR/

`magnet:?xt=urn:btih:2357C8AD8AEA00438421929BD6C8475F0117E378&dn=The+Newsroom+%282012%29+Seasons+1-3++S01-S03+Complete+Series+%281080p+BluRay+x265+HEVC+10bit+AAC+5.1+Vyndros%29+%5BUTR%5D&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Ftracker.ilibr.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fp4p.arenabg.com%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=http%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Fopentracker.i2p.rocks%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce `

https://paste.kodi.tv/gucatoqude

**Comment by Tikipeter** [comment]
Fen doesn't do any renaming of the files for download.

What did Premiumize say when you took this to them?

**Comment by tundrablasen** [comment]
I did not speak with premiumize about that, because on the web GUI of PM the files are named correctly. 

Just after download via FEN the name changed. I will trigger download via FEN again through RD and PM and see if the filename stays the same. 

But right now I’m on holiday so will take a few days for my feedback

**Comment by Tikipeter** [comment]
I no longer have a Premiumize account, so I can't see what's going on.

You could instead open "Browse Pack" in Fen and see exactly what each file is named by Premiumize...

**Comment by tundrablasen** [comment]
> I no longer have a Premiumize account, so I can't see what's going on.
> 
> You could instead open "Browse Pack" in Fen and see exactly what each file is named by Premiumize...

Download happened via RD. I just used PM Screenshots because of the better web UI.

I’m right now not at home but added the same torrent to my RD as well. Both PM and RD have the names correctly and the strange name is just visible in Kodi after the download via FEN
