### ISSUE TITLE
[BUG] Metadata Artwork Quality option

### ISSUE THREAD

**Issue by Nuklear92** [Tikipeter/repository.tikipeter#269]
Okay, so I've personally done a couple of fresh install of FEN since I've been doing some Omega tests then switching back to Matrix, etc. 

And I had found that the option of Artwork quality within the Metadata setting from FEN by Default is on **Medium**. However, if I want to change it to **High** it doesn't change unless I first change it to **Original** restart Kodi and then go back to the setting and change it to **High** that's the only way you can choose this option and even then idk if it's really in High or the quality of Artwork stays in Original. 

Seems like a minor bug/glitch, hopefully you can check it out and see if it can be fixed so that way people can switch from default Medium to High in one shot without having to work around by changing first to Original quality then restart Kodi and then switch to High. 

Other than that, everything works well as far as I know. If I find any other minor bugs I'll let you know!🙂

**Comment by tundrablasen** [comment]
Yes I can reproduce this bug.

**Comment by ivarbrandt** [comment]
Have you tried clearing the metacache right after you change the artwork quality?

**Comment by Nuklear92** [comment]
Yes, but it's the option itself that seems to be bugged/glitched. Specially when you're changing from the Default setting **Medium** to **High** NOT **Original**. From medium to original it changes fine, however from Medium to High, you need to switch to Original first then to High in order to set that option. 

When it the right way would be switching from Medium to High in one shot. When whenever you do that in a fresh install of FEN nothing happens and it remains in Medium. Even if you hit the High option, then restart Kodi the Medium option remain unchanged.

**Comment by Tikipeter** [comment]
This will be changed to a regular Kodi spinner setting next update, meaning a manual clearance of cache will be needed after this setting has changed.
