### ISSUE TITLE
Unable to open my Trakt list 

### ISSUE THREAD

**Issue by rogermae** [Tikipeter/repository.tikipeter#27]
I've waited a week since this first happened. When I click on my TV Show list, it is empty, however I'm able to open my other lists including my movies, DC Universe,  watchlist and collection. Here is the log. https://paste.kodi.tv/mamazatala

**Comment by Tikipeter** [comment]
A couple of questions.....

* Is your `TV Show list` a personal list made by yourself, or is it your TV Show Collection or TV Show Watchlist?
* If it's not the Collection or Watchlist, does the TV Show sections of both of those work correctly?
* Do you have other personal lists that contain TV Shows and do they work? Is it only this one particular list that fails?

**Comment by Tikipeter** [comment]
And perhaps most importantly...

* Are you using a pre-made build?

**Comment by rogermae** [comment]
Yes personal list
Both watchlist and collections work perfectly
This is the only TV list that I have in trakt
Yes this is a pre-made build

Kind Regards
Roz Artis

________________________________

**Comment by Tikipeter** [comment]
First step would be to clear the Trakt cache in Tools->Clear Databases & Clean Settings Files.

Well really, first step would be to not use a build, as I cannot (not will not, cannot) really offer support. Who knows what they've fiddled with. But.... I didn't have that in the Issues rules so we'll continue.

If clearing the cache doesn't work, install this test version, navigate into the the list that's not working, and hopefully an error will pop up. Post me the log after navigating into the troublesome list and hopefully there's something in it to help me see the issue.
[plugin.video.fen-3.0.09o.zip](https://github.com/Tikipeter/repository.tikipeter/files/9500502/plugin.video.fen-3.0.09o.zip)

**Comment by rogermae** [comment]
Nevermind....I figured it out.

Kind Regards
Roz Artis
________________________________

**Comment by rogermae** [comment]
I get an UNABLE TO CONNECT error message when trying type in the url in file manager. Tried with http, https and as is and get the same msg.

Kind Regards
Roz Artis
________________________________
