### ISSUE TITLE
Video not loading via TMDb player

### ISSUE THREAD

**Issue by onlytanmoy** [Tikipeter/repository.tikipeter#270]
Hi @Tikipeter hope you are doing fine mate.
Please refer this video.
https://imgur.com/a/n2XS3V7
I am using Arctic Horizon Skin and the widgets are pointed to TMDbHelper video addon. As you can see it cannot load the video, so either issue with TMDb player or Fen, not sure.
However, this works fine for a movie, only issue is with TV episodes.

**Comment by Tikipeter** [comment]
You may need to update you rplayers. This issue was addressed here hopefully:
https://github.com/Tikipeter/repository.tikipeter/issues/263

**Comment by onlytanmoy** [comment]
Ok, thanks...I will refer that issue and cross check the players URL in TMDbHelper settings.

**Comment by onlytanmoy** [comment]
So I deleted my existing players URL in TMDb Helper and used the players URL from the issue you referred, that seems to have fixed my issue 🙂 Thanks Peter.
