### ISSUE TITLE
[Bug] insecure HTTPS request EN

### ISSUE THREAD

**Issue by Nemes15** [Tikipeter/repository.tikipeter#271]
Hi Tikipeter,

First of all, thank you so much for this addon, it's a godsent for kodi 20, especially since seren is riddled with bugs and errors.

My issue is that I very often (I think every episode) get an error in the log after I either click "yes" or "now" on the auto-scraper saying there was an insecure HTTPS request to easynews and shows a link to documentation on how to fix it. I think it doesn't check the certificate.

I have settings such as "check year before search", "filter results by name" "filter languages" and "check before full search" off. That slightly increases the Anime matches with dubs. I don't know if this helps create the problem because if you search something generic like "from" you get hundreds of invalid hits.

I also have one more issue that doesn't give a log entry. I use AH2 and your menu skin for it but when I go into a menu (like fen) or browse a season and return to the home page with my widgers it crashes to desktop 9 out of 10 tikes without any mention why in the log.

Platform is windows 11 x64 with the latest kodi 20.
Other addons are Seren, and WatchNixToons2. Kodi log viewer and open wizard (no build, only used it to easilly change buffer settings).

Services RD and EN.

**Comment by Tikipeter** [comment]
If there is an `http` request going out from Fen to Easynews, then it will be because the `https` request has failed.

A log would show what request is being made, but either way that is the reason to see an `http` request rather than an `https` request.

As for the issue of crashing when returning to the AH2 homescreen, I don't have any input into how the AH2 skin is coded.

**Comment by Nemes15** [comment]
Does it downgrade to HTTP by default if HTTPS fails to connect on auto-scrape searches? Because this only happens on auto-scrape. If I say no to auto-scrape I never get a log entry for it.
I left all EN server settings to default but if I missed a setting I would rather not have it resolve at all instead of downgrading to HTTP.

I will keep monitoring it and when I have a log with a good list of examples I will upload the log. I'm scared to select auto-scrape Now or Yes, knowing that it is a HTTP connection. What I understood from the log entry was that it did use HTTPS but did not verify the certificate. 

I understand that you have no input in the AH2 code but do you recognize the bug in Windows 11 Kodi 20 setups?

If you had to suggest a skin for FEN that would avoid these crashes which one would that be? AH2 is great with all the options but it is annoying to know you have to turn Kodi on again if you go into any show or season menu.

**Comment by Tikipeter** [comment]
>Does it downgrade to HTTP by default if HTTPS fails to connect on auto-scrape searches? Because this only happens on auto-scrape. If I say no to auto-scrape I never get a log entry for it.

It will issue a request asking `requests` not to verify the security certificate if the first request fails. This is not determined on whether auto scrape is being used or not.

>What I understood from the log entry was that it did use HTTPS but did not verify the certificate.

That's correct. I was trying to simplify my reply, but really what I wrote was incorrect.

>I understand that you have no input in the AH2 code but do you recognize the bug in Windows 11 Kodi 20 setups?

I have heard of it happening to some users, yes.

>If you had to suggest a skin for FEN that would avoid these crashes which one would that be? AH2 is great with all the options but it is annoying to know you have to turn Kodi on again if you go into any show or season menu.

I would remove your widgets and see what happens then first. Then start adding them back and see at what point the issue starts occurring again. As for which skin to use, it's possible no other skin will exhibit this behavior.
