### ISSUE TITLE
Firestick KODI FEN not returning internal providers

### ISSUE THREAD

**Issue by dodtt0301** [Tikipeter/repository.tikipeter#271]
After the recent update of FEN, no Internal scrapers are searched and returned. External scrapers are working, however, I cannot view either of the providers

**Comment by Tikipeter** [comment]
Android device?

**Comment by Tinuz97** [comment]
> Android device?

I think the same, because I noticed it also on my phone. 
Just turned off my computer (bed time), so I did not check that. 🙃

**Comment by dodtt0301** [comment]
![Uploading 604B7A2F-A7B5-4EFD-A05D-0FD0487B633B.jpeg…]()

**Comment by dodtt0301** [comment]
![A4F69627-3DEC-4749-BAD4-CA4B4933928A](https://user-images.githubusercontent.com/72050297/94501757-3806f880-01c8-11eb-9ee4-b5c399b1ba3e.jpeg)
![Uploading 1E045E12-6C6A-4FEC-9F29-1DF701FD2176.jpeg…]()

**Comment by dodtt0301** [comment]
![B1627E75-036D-4770-9495-BE645F45A95C](https://user-images.githubusercontent.com/72050297/94501866-67b60080-01c8-11eb-87ba-8de9d9a40c21.jpeg)

**Comment by dodtt0301** [comment]
![D3BF37D3-78CF-4A49-99A1-8AE5095EECA5](https://user-images.githubusercontent.com/72050297/94502100-ff1b5380-01c8-11eb-81ea-ee728def36c0.jpeg)

**Comment by dodtt0301** [comment]
> ~Android device?~
> Sorry, just read the title again, Firestick.
> Hang tight @dodtt0301 , I'm hoping this is fixed.

I just wanted to clarify the issue I’m experiencing to make sure I make sense. I’m using the Firestick to run KODE 18.8. After I updated FEN on September 28, 2020, any movie I attempted to watch would not work. I would receive a blank screen with no links. It would say “No Results” I noticed no Internal links would be searched nor found, but external links would be found, but those also would not display on the screen.

![0EECE5E6-4336-4D0D-B3CA-28AB29761BE9](https://user-images.githubusercontent.com/72050297/94527394-8504c200-01fc-11eb-946c-e2b297df2ba6.jpeg)
![DC3C95D6-FEA4-4C71-89F7-2E7AE0C40267](https://user-images.githubusercontent.com/72050297/94527425-9352de00-01fc-11eb-8c26-7b0b5a139524.jpeg)

**Comment by 99Maxwell99** [comment]
> > ~Android device?~
> > Sorry, just read the title again, Firestick.
> > Hang tight @dodtt0301 , I'm hoping this is fixed.
> 
> I just wanted to clarify the issue I’m experiencing to make sure I make sense. I’m using the Firestick to run KODI 18.8. After I updated FEN on September 28, 2020, any movie I attempted to watch would not work. I would receive a blank screen with no links. It would say “No Results” I noticed no Internal links would be searched nor found, but external links would be found, but those also would not display on the screen.
> 
> ![0EECE5E6-4336-4D0D-B3CA-28AB29761BE9](https://user-images.githubusercontent.com/72050297/94527394-8504c200-01fc-11eb-946c-e2b297df2ba6.jpeg)
> ![DC3C95D6-FEA4-4C71-89F7-2E7AE0C40267](https://user-images.githubusercontent.com/72050297/94527425-9352de00-01fc-11eb-8c26-7b0b5a139524.jpeg)

You need to go into fenom scrapers in addons and enable all providers. Save and reboot and then it will work. First might be slow but after that will be fine

**Comment by dodtt0301** [comment]
> > > ~Android device?~
> > > Sorry, just read the title again, Firestick.
> > > Hang tight @dodtt0301 , I'm hoping this is fixed.
> > 
> > 
> > I just wanted to clarify the issue I’m experiencing to make sure I make sense. I’m using the Firestick to run KODI 18.8. After I updated FEN on September 28, 2020, any movie I attempted to watch would not work. I would receive a blank screen with no links. It would say “No Results” I noticed no Internal links would be searched nor found, but external links would be found, but those also would not display on the screen.
> > ![0EECE5E6-4336-4D0D-B3CA-28AB29761BE9](https://user-images.githubusercontent.com/72050297/94527394-8504c200-01fc-11eb-946c-e2b297df2ba6.jpeg)
> > ![DC3C95D6-FEA4-4C71-89F7-2E7AE0C40267](https://user-images.githubusercontent.com/72050297/94527425-9352de00-01fc-11eb-8c26-7b0b5a139524.jpeg)
> 
> You need to go into fenom scrapers in addons and enable all providers. Save and reboot and then it will work. First might be slow but after that will be fine

I followed your instructions, but I’m still experiencing the same issue. I made sure I hit “Ok” and rebooted several times. I verified the changes were applied. I went thru each option on the side column and made sure everything was Enabled. Myself and other FEN users I know are all experiencing this issue after updating the addon.

![07CB8310-660B-4FFF-9EC3-B2C588CD1C3B](https://user-images.githubusercontent.com/72050297/94714313-9986ae80-0311-11eb-9b9a-ffb35ad7e0fc.jpeg)
![D99C55A1-D798-497E-931E-A74F824164B4](https://user-images.githubusercontent.com/72050297/94714362-a7d4ca80-0311-11eb-85d5-220d32730726.jpeg)
![EADF1430-E6CC-472D-A60D-3C684A464418](https://user-images.githubusercontent.com/72050297/94714415-bae79a80-0311-11eb-9ab9-ab275ad46b57.jpeg)
![48682008-F142-44A2-A684-1B2212EC21FA](https://user-images.githubusercontent.com/72050297/94714478-cdfa6a80-0311-11eb-9d87-88a5070e7402.jpeg)

**Comment by Tikipeter** [comment]
Have you entered your credentials and authorized you accounts in `My Accounts`?

**Comment by dodtt0301** [comment]
> Have you entered your credentials and authorized you accounts in `My Accounts`?

I have never entered any credentials Or authorized any accounts using FEN. I installed KODl and FEN on several other Firesticks. Everything was working properly without having to enter any credentials or authorizing any accounts prior to the update. Once I and the other users performed the update on our Firesticks, no links would return for either of us.

**Comment by Tikipeter** [comment]
Do you have any debrid account memberships, or memberships to Furk or Easynews?
If you were previously using Fen with only free links, you will have to find another addon to use. Fen does not provide free links anymore.

**Comment by dodtt0301** [comment]
> Do you have any debrid account memberships, or memberships to Furk or Easynews?
> If you were previously using Fen with only free links, you will have to find another addon to use. Fen does not provide free links anymore.

So here’s what I did. I reset two Firesticks connected to two different Wi-Fi connections back to their origins factory settings as if they were brand new. I installed KODI on both. After the install, FEN worked on both. I was able to get a ton of links and able to start up movies in 1080p with no issues. I restarted KODI, which then triggered the FEN update. After the update, I was unable to get links, which was my original issue. I then uninstalled KODI on both Firesticks. This time, prior to installing any addons, I went to the addon settings in KODI and selected “Notify, but do not automatically update” addons. I then installed addons on both Firesticks. FEN worked perfectly again and haven’t had any issues on either Firestick after multiple restarts and reboots of KODI. I was able to view links and movies again. The root cause is the FEN update. See the screenshots below.

![583B6B75-A12C-4C0C-B328-826FBD693339](https://user-images.githubusercontent.com/72050297/94937063-b5668d80-0494-11eb-8392-8e2bf887a05f.jpeg)
![A59C74F4-E628-443F-B18A-5454B6E71771](https://user-images.githubusercontent.com/72050297/94937075-b8fa1480-0494-11eb-829c-34ed99e513ef.jpeg)
![226DB05D-1789-4A75-8856-47B1D71AA06D](https://user-images.githubusercontent.com/72050297/94937121-c7e0c700-0494-11eb-988b-d03b135adcce.jpeg)
![38F7C193-969A-4A11-8BDA-142293F3665D](https://user-images.githubusercontent.com/72050297/94937133-cadbb780-0494-11eb-84fd-8018af552881.jpeg)
![6C2F3C47-8CCB-4EA1-8853-3EFCD9F19281](https://user-images.githubusercontent.com/72050297/94937170-d62ee300-0494-11eb-92ce-e0732b6258d7.jpeg)
![5BA01AF1-1AE6-45AC-9FA4-9B5097329FA4](https://user-images.githubusercontent.com/72050297/94937178-d8913d00-0494-11eb-96f4-551a79b127ef.jpeg)
![938A7E23-E78A-4017-90D8-3DBAEA89FD64](https://user-images.githubusercontent.com/72050297/94937181-da5b0080-0494-11eb-838b-c44eeb28d0cb.jpeg)
![78CC3338-E659-4B05-807B-F6B8BB09C2A7](https://user-images.githubusercontent.com/72050297/94937189-dcbd5a80-0494-11eb-9368-ff0e7c1e1ed5.jpeg)
![9B69942B-4285-4EBE-8843-DE7AA6820A56](https://user-images.githubusercontent.com/72050297/94937255-f78fcf00-0494-11eb-86e6-96c1abd34895.jpeg)

**Comment by Tikipeter** [comment]
Please, please, PLEASE reread my last comment above.
Fen does not provide free links anymore.

**Comment by dodtt0301** [comment]
Thank you for your help
