### ISSUE TITLE
New update does not pull any int or Ext scrappers

### ISSUE THREAD

**Issue by DoBucki** [Tikipeter/repository.tikipeter#273]
Rolled back to 1.8.07c and that does work,  before roll back I activated all scrappers and reboot kodi, no results, Uninstalled fen reinstalled, still not working.  Cleared all cache and  not working.  Definitely an update issue

**Comment by Tikipeter** [comment]
Did you authorize your debrid account/s in My Accounts?

**Comment by DoBucki** [comment]
Not using debrid or torrents,

**Comment by Tikipeter** [comment]
Fen only supports debrid services.

**Comment by DoBucki** [comment]
It wasn't that way before the update,  watching die hard 2 on fen right now with gvideo.  After I downgraded back

**Comment by Tikipeter** [comment]
Are you asking me or telling me?

**Comment by DoBucki** [comment]
I'm stating a fact

**Comment by Tikipeter** [comment]
Me too.

**Comment by DoBucki** [comment]
So you saying with the new update it uses debrid only and before the new update you could use either

**Comment by DoBucki** [comment]
I'm stating that non debrid sources worked great before 9/28

**Comment by Tikipeter** [comment]
Yes. Fen only supports debrid services.
It was written in the changelog that appeared on you screen when Fen updated.
Since you said you don't use a debrid service, unfortunately Fen is no longer of use to you.
Your only options are to subscribe to a debrid service, or switch to an addon that still provides free links.
Personally I would grab a debrid account, but of course you do what is best for you.

**Comment by DoBucki** [comment]
Why did fen stop using free scrappers

**Comment by Tikipeter** [comment]
I don't use them. I needed to keep a dependency on ResolveURL while they were supported. I needed to support code in Fen while they were supported. I needed to try and help keep the free scrapers working while they were supported. Fen was originally written only for Furk, and then Easynews subscribers; never for free link users. Plus other reasons.

**Comment by DoBucki** [comment]
Well I'm sorry to see you don't support them anymore I do have to say your add-on was great it had a lot of features that salts used to have and you did a really great job on it good luck to you in the future

**Comment by Tikipeter** [comment]
I hope you find another addon that you enjoy and has free links. And don't dismiss entirely the option of using a debrid service.

I didn't write another reason for the move away from free scrapers - it's a losing battle. The sites scraped to provide free links are moving at a rapid pace to utilizing Cloudflare v2 protection. These protections are not passable using code. Each time a scraper's site moves to Cloudflare v2, it is lost as a scraper. I think more than half the sites scraped had already moved to Cv2. It truly is a losing battle.

The time to relent and strongly consider a debrid service is here I'm afraid.

**Comment by DoBucki** [comment]
Appreciate the info, thanks
