### ISSUE TITLE
Settings not "sticking" for My Accounts and Fen (test build inside...)

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/repository.tikipeter#274]
I will post below a test build for Fen and My Accounts (MA) that users having this issue can test.
Things to note for these tests:
* When authorizing Trakt or your debrid account/s, MA's settings window will close and will not reopen when auth is complete.
* The settings changed in MA will not automatically sync to Fen. You will need to go to Fen's settings and select "(Re)Sync Fen Settings with My Accounts".

The main thing I'm looking at here is that the settings are saved successfully to MA, rather than worrying about the sync to Fen, so I have left the sync to Fen as normal.

If you are accessing MA's settings through Addon Info dialog, you MUST fully exit that info dialog before re-entering MA's settings to check if the settings stuck. To be honest, for this testing it would be better if you accessed MA's settings through Fen's settings.

Please report your results from testing with these two files. Thanks anyone who can. 👍 

~~[plugin.video.fen-1.8.11a.zip](https://github.com/Tikipeter/repository.tikipeter/files/5314766/plugin.video.fen-1.8.11a.zip)~~
~~[script.module.myaccounts-1.0.2a.zip](https://github.com/Tikipeter/repository.tikipeter/files/5314767/script.module.myaccounts-1.0.2a.zip)~~

FINAL TEST VERSIONS:
[plugin.video.fen-1.8.11b.zip](https://github.com/Tikipeter/repository.tikipeter/files/5321063/plugin.video.fen-1.8.11b.zip)
[script.module.myaccounts-1.0.2b.zip](https://github.com/Tikipeter/repository.tikipeter/files/5321064/script.module.myaccounts-1.0.2b.zip)

**Comment by Tinuz97** [comment]
No idea what you changed, but voila, Premiumize instantly sticks after Fen and My Accounts update. (I wiped my premiumize ID a little) 
![Screenshot_20201001-234954__01](https://user-images.githubusercontent.com/47715606/94867219-1795a300-0441-11eb-97c3-84c918a075dd.jpg)

**Comment by Tinuz97** [comment]
Both also survived a kodi reboot, both are sticking now. (ps, I always did hit the OK button, and always close kodi how it should, to save settings, I never hit the back key, or force closing, otherwise settings won't save) 


![Screenshot_20201001-235331](https://user-images.githubusercontent.com/47715606/94867361-6b07f100-0441-11eb-902d-f6fdc2c655e4.jpg)

**Comment by Tinuz97** [comment]
🎉

![Screenshot_20201002-000014](https://user-images.githubusercontent.com/47715606/94867856-4f511a80-0442-11eb-83ae-041130d98ae1.jpg)

**Comment by mrchen911** [comment]
I was just about to text it and the trakt website is returning 521 error code. I'll keep trying.

**Comment by mrchen911** [comment]
Ok, trakt back up. Once I authorized, MA closed on its own and the authorization stuck.

**Comment by Tonkapug** [comment]
This has fixed the issue for me as well. The directory is created as soon as you click authorize and the token is saved in the settings.xml.

**Comment by Tikipeter** [comment]
This is mostly great news and a little bit of bad news all in one.
Firstly, it's what I thought it was causing this issue. Secondly, the process temporarily adopted here to auth the accounts cannot be the final way in which it is done i.e. settings closing and not re-opening & needing to resync to bring the settings into Fen. But the way we have it at the moment in the release versions are obviously not working in all situations.

Those test builds are stable so you can keep using those until we come up with a solution that will work.

**Comment by Tinuz97** [comment]
I noticed download packs is gone  with premiumize, just temporarily? Did it mess up something also? (did work great for me, I just unzipped the pack manually, and moved it manually).

**Comment by Tikipeter** [comment]
Yeah temporarily (I thought) disabled whilst trying to write a new downloader module.
Was hoping to get back on it this week, but then this thing happened....
Hopefully next week I can bring it back.

**Comment by Tikipeter** [comment]
If anyone is willing to return to the release version of My Accounts, perform an auth for Trakt or a debrid, and then send through a log after it fails, it could be really helpful.

We need to keep the current functionality of the release version of MA (returning to original addon settings etc) and that would be much easier if we could work out exactly **WHY** MA is failing in the current release version. Even though my hunch for a fix was correct, I still don't know why it's failing doing things the other way.

I understand this has been an issue for the best part of a week now, so I don't want anyone to reinstall the release version if that's the only machine they use Kodi on. Just if someone has a machine they can afford to "test" on.

Thanks all.

**Comment by mrchen911** [comment]
I can help but I need details. 

Do I need to enable additional logging, if so, where?

Where are the logs located on Android? 

Where do I submit the logs to?

I am a software developer, but I do not develop on this platform, language, or device.

**Comment by ramoun** [comment]
Loaded the 2 test files.

Trakt and Rd both accept and store auth details.

RD presents results when searching for moview etc.

Trakt does not show any results for anything but the details are there.

This was after Kodi restart.

Hope it helps

**Comment by Tikipeter** [comment]
@mrchen911 
Thanks a lot for the offer. Here's what's needed if you can.
**Before starting, install the "Kodi Logfile Uploader" from the official Kodi repository.**
1. Turn ON debugging in My Accounts (MA) (Under "Options"). Choose "Kodi Log" for logging location.
2. Clear a couple of auth services in MA (revoke auth).
3. Re-install last release version of MA (1.0.2).
3. Restart Kodi.
4. Attempt to auth either a debrid or Trakt account. If you have a couple you can do that would be great.
5. Navigate in Kodi to Programs->Kodi Logfile Uploader. Run the program. Follow the prompts to "upload" the log.
6 Paste the link to the log here for inspection.

If you can help that is much appreciated. 👍

**Comment by Tikipeter** [comment]
@ramoun 
There are issues with trakt that might be the cause.
Running a resync of My Accounts settings with Fen, or reauthorizing Trakt in My Accounts are the only actions you can really take yourself, but I think it is trakt playing up at the moment on and off.

**Comment by ramoun** [comment]
Trakt does play up some times, FYI tested just now RD & Trakt both show correct details under details, tried FEN account sync no joy. revoked Trakt and re auth'd, data saved and can be seen in details, also did a fen acc sync but displays not results.  I'll try later today.

**Comment by mrchen911** [comment]
Ok, I successfully followed all setup steps outlined in your post.

Log file: https://paste.kodi.tv/uxeliwufaw

Here's my testing steps working directly in MA.
1. Authorize trakt, it did not stick.
2. Authorize RD, it did not stick.
3. Authorize trakt, authorize RD, there was a slight delay of the pop-up notification and I hit ok before it appeared, only RD auth saved.

**Comment by Tikipeter** [comment]
Thanks so much @mrchen911 
Your help is very much appreciated.

**Comment by Tonkapug** [comment]
@Tikipeter Here's my log for an attempt at authorizing Premiumize

https://paste.kodi.tv/imilusajug.kodi

**Comment by Tikipeter** [comment]
@Tonkapug 
That's fantastic, thankyou as well!

I think that's all that's needed folks. Hopefully an official release will be coming soon to fix this issue and get it working for everybody.

Great job all. I'll close this issue so more people don't go to the bother of grabbing logs.

**Comment by Tikipeter** [comment]
New release of MA hopefully in around 24 hours.

**Comment by Tikipeter** [comment]
If anyone wants to test out the likely release for tomorrow, I will post it in the original post.

**Comment by Tinuz97** [comment]
> If anyone wants to test out the likely release for tomorrow, I will post it in the original post.

I removed the complete My Accounts folder, including the XML file as a test, to make sure everything is created again (folder and XML file in userdata). 

Did auth Realdebrid, then, Premiumize, then Trakt. 
All are 'sticking' and working on my Android phone now, without any issues. 
This is great @Tikipeter 😀

**Comment by Tonkapug** [comment]
@Tikipeter Authorization works via the Fen addon>Accounts>Open My Accounts section. Data is saved with no issue. However, if i try to run the My Account addon from the programs menu it gives an error. If i choose settings from the context menu, it will open. Besides that all is good. Log below!

https://paste.kodi.tv/puqajotehe.kodi

**Comment by mrchen911** [comment]
Kodi crash closed on me twice. Auth appears to be sticking but the user experience isn't clean. After each auth it kicks you out before you can complete all authorizations. One time it glitched my screen, see screenshot. Also can't go directly into MA.

Logs https://paste.kodi.tv/hobujowadu

![Screenshot_20201003-104100](https://user-images.githubusercontent.com/907838/94994439-94ba3880-0565-11eb-8d5d-a7d086bc849b.png)

**Comment by Tikipeter** [comment]
The testing was only meant to be through Fen for MA. My fault, I didn't stipulate that. FenomScrapers will need an update too to work correctly.

The direct access to MA will be fixed. I know the problem, and I'll increase some sleep times for a couple of loops to hopefully stop any crashing/glitchiness.
