### ISSUE TITLE
[Enhancement Request] Make "Next Episodes" list honor item limit settings

### ISSUE THREAD

**Issue by TwilightMercy** [Tikipeter/repository.tikipeter#274]
Hi Peter,

I was wondering if it is possible to make **`TV Shows --> Next Episodes`** work with **`Navigation --> Addon/Widgets Item Limit`** setting. Example of current state: (FEN `3.1.17`)

**FEN settings - limit is set to 7 for both:**
![image](https://github.com/Tikipeter/repository.tikipeter/assets/29895680/62431902-6e7f-47d3-a6d5-888b61677b63)

-------------------------------------------------------------------------------------------------------------------------------------

**FEN - TV Shows - Watched (Works, also for widgets):**
![image](https://github.com/Tikipeter/repository.tikipeter/assets/29895680/d6f2c4cb-1cf0-4cc7-b63d-79157e4f2b09)

-------------------------------------------------------------------------------------------------------------------------------------

**FEN - TV Shows - In Progress (Works, also for widgets):**
![image](https://github.com/Tikipeter/repository.tikipeter/assets/29895680/4761804e-08b6-406f-b0fd-019ad28e336c)

-------------------------------------------------------------------------------------------------------------------------------------

**FEN - TV Shows - Next Episodes: (No 7 items limit and next page at the end of the list for both addon/widget)**
![image](https://github.com/Tikipeter/repository.tikipeter/assets/29895680/3b2d4f92-cbf5-42d2-8ca1-5ea24548f455)

-------------------------------------------------------------------------------------------------------------------------------------

I know that TMDb lists are limited to 20 per page. From my understanding, **`Next Episodes`** is taken from local FEN `watched.db` / Trakt data, so I hope it's possible to make this list work with the limit setting.

Thank you very much!

**Comment by Tikipeter** [comment]
It's not really possible without a decent sized re-write of the current code.

Which I would be willing to do if paginating this list would have any effect on performance. Unfortunately it wouldn't, as metadata for ALL the episodes needs to be fetched BEFORE any sorting is done. And sorting needs to be done before any pagination takes place.

**Comment by TwilightMercy** [comment]
> Unfortunately it wouldn't, as metadata for ALL the episodes needs to be fetched BEFORE any sorting is done.

Also for episodes thumbnails and metadata for widgets in Fenstuary/FENtastic?
Or paginating the list will make widgets load only the first page?
