### ISSUE TITLE
Trakt not updating shows as watched

### ISSUE THREAD

**Issue by sblair77** [Tikipeter/repository.tikipeter#275]
After I watch a show it still shows in next episodes and in my trakt widget and lists. I clear cache and restart but I have to manually mark as watched in trakt and then shut down and restart for the next episode to appear in teh list. It used to work seamlessly. Is there a setting that has changed?

**Comment by Tikipeter** [comment]
No settings changed. Trakt has been having issues the last few days. Maybe a reauth will help.

**Comment by sblair77** [comment]
Ahhh stinking trakt. Thank you
