### ISSUE TITLE
Thank you Tikipeter

### ISSUE THREAD

**Issue by xyzfre** [Tikipeter/repository.tikipeter#276]
No issues just wanted to say thank you for Fen (LEGEND)💯💯 3.1.18 is the FASTEST I ever seen on any addon,, your work is AMAZING❣️ as a end user of Fen 4 years now BIG THANK YOU  @Tikipeter

**Comment by Tikipeter** [comment]
Thanks for the kind words @xyzfre 

I'm glad everything is working OK after the latest update.
