### ISSUE TITLE
tapping movie or tv tap show search section loads pre searched polish names 

### ISSUE THREAD

**Issue by cabban** [Tikipeter/repository.tikipeter#276]
should be tapping search should take me to search box ? to search my movie or film, i think this is a bug cheers, search regular is give choise to search with name tv etc, but nothing happend when im inside correct section

**Comment by Tikipeter** [comment]
Hi @cabban 
Bring up the context menu on the "search" item, select "Edit Menu" then select "Reload Search".
Do this for any search items giving you this trouble.
