### ISSUE TITLE
Auto scrape (request) 

### ISSUE THREAD

**Issue by JFG1000** [Tikipeter/repository.tikipeter#277]
Hi Tiki first of all I'd just like to say thankyou so much for all your hard work, the latest update is amazing and it's in my opinion the best it's ever been and so fast 👌🏻

I would just like to ask if i could kindly request something, the autoscrape box that pops up when it asks if we want to scrape currently has a picture of the poster art of the show, would it be possible to change that picture to the episodes screenshot that it's about to scrape instead? 😎

Regards

**Comment by Tikipeter** [comment]
>currently has a picture of the poster art of the show

I hope you mean the fanart. :)

I can do that (surprisingly with more effort than you would think). The issue is the fanart is currently quite dimmed, so I'm not sure the episode thumbnail would be visible enough to discern what is happening.

Thoughts?

**Comment by JFG1000** [comment]
Yes that's correct 😁 i reckon it would be ok, maybe if you was to add it as a setting that way we could switch it back if it didn't seem ok, but i honestly think it would be fine, thankyou so much for this Tiki, fen is by far the best thing to happen to Kodi in years, respect to you

**Comment by Tikipeter** [comment]
Done for next update. I lowered the "dimming" amount of the image so it should look OK.

**Comment by JFG1000** [comment]
Thanks buddy looking forward to trying it, your the best tiki 👍🏻

**Comment by ivarbrandt** [comment]
> Fen is by far the best thing to happen to Kodi in years

This statement is BIG facts 💯
