### ISSUE TITLE
No result on fresh install

### ISSUE THREAD

**Issue by dvdbouns** [Tikipeter/repository.tikipeter#277]
Hi,

- MacOS (Catalina)
- Fresh install
- repository.tikipeter-0.0.6
- My accounts : Alldebrid added

I have no result, for resolve this : 
- launch "sync(re) with My Accounts" in FenomScrapers settings
- close kodi
- open kodi
And it's OK, i have result with all scrapers

Other observation : When i launch Fen at first execution, the changelog is not displayed

**Comment by ANHBOB** [comment]
Many times when I first start up Kodi>Fen I get no results for whatever I scrape.  What I do is go to Tools>Clean settings and all cache. After I clean everything THEN I get the results.  I know why the changes took place with the addon...I just wish it worked as fast and as good as it did when Fen was using openscrapers and Resolveurl.
Another issue I'm having....when I set pre empitive termanation  and I set how many (50)....the old Fen used to stop when it reached 50 results....now it doesn't. It just keeps going until it finishes scraping.
I'm using the 4K Firestick,  Latest version of Kodi.

**Comment by Tikipeter** [comment]
NEVER clear all cache as a troubleshooting measure.  Information is cached for a reason, namely to decrease the load on resources like TMDb, TVDb and Trakt.
Looks like I'll have to remove the Clear All Cache listitem if it's being used in this manner.
@dvdbouns If you accessed My Accounts through Programs, then yes you will need to sync those settings to Fen, through Fen.
I dont understand why you synced them to Fenscrapers?
If you got results after syncing, then there shouldn't be an issue.
@ANHBOB please start a new issue so as to keep this Issue thread organized.

**Comment by dvdbouns** [comment]
Thank for your reply @Tikipeter 
I use Fen plugin (for me the best :)

On fresh install 
I install your repo
I install video plugin fen
I open fen
(The changelog not displayed, I think he launched but he closed directly)
I add my account debrid 
The information of my account is ok
I launch one movie 
No result... (no one scrapper active on dialogue)(in fenomscraper settings all default scrapers are active)
Close/open Kodi : always no result
launch "sync(re) with My Accounts" in FenomScrapers settings
always no result 
Close/open Kodi : it’s ok I have many results

**Comment by mariofenech** [comment]
Having similar issue..on tv shows....click on episode can see the links increasing on search window ..then ehen finish searching I get no links/results...then click back and clickon same episode and links come straight away..looks like they are already cached from previous search attempt..

**Comment by dvdbouns** [comment]
Identical situation with 
LibreELEC (9.2.4)

**Comment by mariofenech** [comment]
> Identical situation with
> LibreELEC (9.2.4)

Here also on LE 9.2.4

**Comment by Tikipeter** [comment]
Does the problem present itself ONLY on the first scrape after a fresh install, or the first scrape each time Kodi is started?

**Comment by dvdbouns** [comment]
> Does the problem present itself ONLY on the first scrape after a fresh install, or the first scrape each time Kodi is started?

If I don't run one of the two options, the problem is persistent

**Comment by Tikipeter** [comment]
> If I don't run one of the two options, the problem is persistent

**Every** new scrape for sources it happens?

**Comment by mariofenech** [comment]
> > If I don't run one of the two options, the problem is persistent
> 
> **Every** new scrape for sources it happens?

Every new scrape for an episode in tvshows...
First run no results but results are cached and come straight away after re clicking episode

**Comment by dvdbouns** [comment]
> **Every** new scrape for sources it happens?

Yes, I have activated the debug of kodi & fenomscrapers & myaccounts
I unfortunately have no error

**Comment by Tikipeter** [comment]
OK. Let me look into it. It's certainly not happening for me at the moment. My main machine also uses LibreELEC 9.2.4 with no issue.

**Comment by mariofenech** [comment]
> OK. Let me look into it. It's certainly not happening for me at the moment. My main machine also uses LibreELEC 9.2.4 with no issue.

Thanks

**Comment by Tikipeter** [comment]
Just testing now. There should be a possible fix for this in the next Fen release.

**Comment by mariofenech** [comment]
> Just testing now. There should be a possible fix for this in the next Fen release.

Great...could you replicate the problem on your setup?

**Comment by dvdbouns** [comment]
Great, thank you for your job !

**Comment by Tikipeter** [comment]
> ...could you replicate the problem on your setup?

I replicated almost the same.

With a new install, there is no `settings.xml` for the Fenomscrapers.
Fen needs that `settings.xml` to exist to get the active scrapers. Normally you don't need it to physically exist, but Fen does because of the way it accesses Fenom's settings. Normally Kodi will return the set default values if it hasn't made a `settings.xml` yet. Fen parses the actual `settings.xml` file to get the settings because it's quicker. But it fails of course when the file doesn't exist.

What gives me pause is I was not able to get the results to appear on a "rescrape" after the initial failure, which is different from your results in testing. I can't explain why that is the case. So there might be another issue going on, but I'm hoping not.

**Comment by Tikipeter** [comment]
I'll push an update shortly for the fix I've done because I'll need to leave the house for a few hours soon.
Let me know if it sorts out the issue or not.
v.1.8.12a will be the release.

**Comment by dvdbouns** [comment]
> I'll push an update shortly for the fix I've done because I'll need to leave the house for a few hours soon.
> Let me know if it sorts out the issue or not.
> v.1.8.12a will be the release.

Unfortunately still no result

**Comment by Tikipeter** [comment]
Do you get consistent results **after** you close Kodi and re-open?

**Comment by dvdbouns** [comment]
> Do you get consistent results **after** you close Kodi and re-open?

No problem on this side, all links are good

**Comment by mariofenech** [comment]
Something changed since the update but still having the no results on first scrape...Now on the second time I click on the same episode it will start the scrape from the beginning instead of showing the cached results from first scrape...it does show the results on second scrape tough..

**Comment by Tikipeter** [comment]
OK. Go to Tools->Clear Databases And Clean Settings Files and select "Clear External Scrapers Cache".
Then try and see if it works then.
Even better, if you know how to access the addon_data folder in Kodi, go in there and delete the `ext_providers3.db` file from Fen's data folder. If you can't do this, do the "Clear" written above instead.

**Comment by mariofenech** [comment]
> OK. Go to Tools->Clear Databases And Clean Settings Files and select "Clear External Scrapers Cache".
> Then try and see if it works then.
> Even better, if you know how to access the addon_data folder in Kodi, go in there and delete the `ext_providers3.db` file from Fen's data folder. If you can't do this, do the "Clear" written above instead.

Done that many times...even started from scratch by deleting all addondata folder of fen/fenomscrapers/my accounts but still got this issue...it only happens on my RPI with LE...kodi on windows with Fen is fine

**Comment by mariofenech** [comment]
Solved?

**Comment by dvdbouns** [comment]
Hi @Tikipeter

I found these differences between before and after close/open kodi
Would it have a debug mode in your addon ?
I have loglevel 2 in advancedsettings.xml but how to use # from modules.utils import logger ? 
Thank you
I hope this will help you

Before (No result) :
```
RunScriptWithParams - calling plugin Fen('plugin://plugin.video.fen/','-1','?mode=container_update&final_params=
GetLanguageInvoker - Reusing LanguageInvokerThread 7 for script
----------
StartScript - calling plugin Fen('plugin://plugin.video.fen/','2','?vid_type=movie&query=
GetLanguageInvoker - Reusing LanguageInvokerThread 7 for script

```

After (Results OK):
```
RunScriptWithParams - calling plugin Fen('plugin://plugin.video.fen/','-1','?mode=container_update&final_params=
GetLanguageInvoker - Reusing LanguageInvokerThread 5 for script
----------
StartScript - calling plugin Fen('plugin://plugin.video.fen/','1','?vid_type=movie&query=
GetLanguageInvoker - Reusing LanguageInvokerThread 5 for script
```
