### ISSUE TITLE
"Add Resolved Torrents to Cloud" Option is Gone! 

### ISSUE THREAD

**Issue by rezpower** [Tikipeter/repository.tikipeter#278]
Hello Tikipeter,
I realize that after the last changes and update the option to save cached torrents to cloud (on premiumize) is gone :( 
The setting was under accounts :  "Add Resolved Torrents to Cloud". I hope that it's me doing something wrong or that
the setting can be found somewhere else in the addon!
Please, Please add this back if possible :)

**Comment by Tikipeter** [comment]
That is unfortunately a `visibilty` error with the settings file. The option for Add Resolved Torrents to Cloud still exists and is still functional.

Next update will include a fix for the settings file so it appears again.

**Comment by rezpower** [comment]
Good news :) Will wait for the next release.

**Comment by rezpower** [comment]
I can confirm that it's fixed now 👍 Thanks a lot :)
