### ISSUE TITLE
Easynews got worse ...

### ISSUE THREAD

**Issue by znilo** [Tikipeter/repository.tikipeter#278]
Hi, 
I just tried to play something from EN after not using Kodi for a while.
While I had some problems with playing something from EN in the past, now it doesn't seem to work at all for me.
Tried to tweak with the playback settings but nothing worked.(Playback Attempts to 5000ms and Retries to 5)
So i looked into the changelog where it says for version 3.1.17
"New resolving code for Easynews. Give it a decent try to see if things improve. If things get worse, open an issue on my github and I will make a setting to choose between old and new method."
Would appreciate having the old method back :)

**Comment by ReaLx3m** [comment]
Dont see anything working worse with EN here. Though there were some slowdowns and buffering today, resolved that by switching server. Problem for me was with US East 443. Switched to Europe 443 and all started working great again, and is generally better since im in europe, but guess was playing around and forgot it set at US. 

You can test what server works best for you here - https://members.easynews.com/route/

**Comment by znilo** [comment]
Thanks for your reply, but I don't think that's the cause of the problem. I just tried different locations and ports and it didn't help.
While using Ezra and Umbrella I have no issues with EN(at least with the more recent stuff), regardless of location and port.
I even tried it on different Platforms. One AndroidTV10 with Kodi 20.2 and the other a Raspi with LibreELEC 11.0.1. But no luck ...

**Comment by ReaLx3m** [comment]
Describe your problem with more detail instead of just "doesnt work at all", and also include a log if you want to get help. 
No log is why the ticket was closed.

**Comment by znilo** [comment]
Ok looking into the log did it for me...(reminder to self always look into the log first :)
In the Log it said it couldn't resolve host name. So I played around with the network settings until I realized that the curl request didn't contain my whole password. I recently changed my password with a password manager generated one, that contained the special character /. I guess that's what f*cked up my password string, because the curl request only contained the characters after the occurance of /. So I changed my password, which now only contains numbers and "normal" characters and.....it works :):):)
Thanks @ReaLx3m, for tanking the time and giving me a hint
