### ISSUE TITLE
Trakt watched setting to choose between Fen/Trakt greyed out

### ISSUE THREAD

**Issue by mariofenech** [Tikipeter/repository.tikipeter#279]
Issue is there is no way I can make this to work from addon..
In My Accounts addon trakt is authorized...in Fen addon settings I can see my trakt is enabled in the accounts section and shows my trakt username....Fen addon loads my trakt lists just fine..
Issue is just with choosing watched mark..

I fixed it by changing the 2 associated lines in settings.xml from a working Fen on windows...but my LE is still the same

**Comment by Tikipeter** [comment]
Resync Fen settings with My Accounts settings and see if that fixes the issue.

**Comment by Tikipeter** [comment]
This will be fixed next update. Run a Sync from Fen settings and the Indicators choice should be available again.

**Comment by mariofenech** [comment]
> This will be fixed next update. Run a Sync from Fen settings and the Indicators choice should be available again.

I tried to do that but never worked...
I got it to work by changing manually..

line 223 to     <setting id="trakt_indicators_active">true</setting>
line 237 to     <setting id="watched_indicators">1</setting>
in settings.xml and been working fine since..

Again this works fine on Fen on windows but not on LibreElec..

**Comment by Tikipeter** [comment]
I meant run a sync once the new update is released.
