### ISSUE TITLE
Install on Apple TV

### ISSUE THREAD

**Issue by Alex20090313** [Tikipeter/repository.tikipeter#279]
Hi Tiki, first I wanna start off with thank you for all your hard work and dedication to the build, I really appreciate it, Fen has grew to be my favourite addon and the add on I apply to all my devices, that being said 

I have kodi installed on my Apple TV 4K and since there is no browser to download the .zip on Apple TV how could I get this installed, I've been searching but have not found a way to install, could you please give me some advice or a way to do this without going to android

**Comment by ke7doy** [comment]
first: settings/system/add-ons/unknown sources/ on
second: file manager/add sources  click none then type
https//:tikipeter.github.io click ok then type fen in the box that asks a name and click ok again.
third: hit back button. click addons then choose install from zip choose fen wait a few seconds for the finished notics to appear then click install from repository choose tikipeters repository then choose video addons.

**Comment by Tikipeter** [comment]
You can't transfer a file over to the Apple? If not, then I don't see how you can install Fen onto it.

**Comment by Alex20090313** [comment]
> first: settings/system/add-ons/unknown sources/ on
> 
> second: file manager/add sources  click none then type
> 
> https//:tikipeter.github.io click ok then type fen in the box that asks a name and click ok again.
> 
> third: hit back button. click addons then choose install from zip choose fen wait a few seconds for the finished notics to appear then click install from repository choose tikipeters repository then choose video addons.

When I do this it now comes up empty the .zip no longer appears, the folder comes blank

**Comment by SoulReaverFan** [comment]
> Hi Tiki, first I wanna start off with thank you for all your hard work and dedication to the build, I really appreciate it, Fen has grew to be my favourite addon and the add on I apply to all my devices, that being said
> 
> I have kodi installed on my Apple TV 4K and since there is no browser to download the .zip on Apple TV how could I get this installed, I've been searching but have not found a way to install, could you please give me some advice or a way to do this without going to android

Have you tried just putting the zip on Dropbox or other cloud storage and use the Dropbox Kodi addon as a source to install the repository zip using the file manager?
