### ISSUE TITLE
Show on Trakt List not showing up in Fen

### ISSUE THREAD

**Issue by Sassafrassa** [Tikipeter/repository.tikipeter#28]
I went to watch a show - Milk Street - on Fen.  It's been on one of my Trakt lists for a year or so and it's up to season 3.  The show is no where to be found in Fen.  When I go to the trakt list page in Fen, it is missing.  When I searched for "Milk Street"  "Christopher Kimball's Milk Street" or even just Christopher Kimballs name, it doesn't show up.  When I pull up OpenMeta, it shows up on my trakt list there, but when I try to search it with Fen, I get an error (attached file)
[fen.txt](https://github.com/Tikipeter/repository.tikipeter/files/3614462/fen.txt)

Link to Trakt page for show https://trakt.tv/shows/christopher-kimball-s-milk-street-television

**Comment by Sassafrassa** [comment]
After a little digging, the show is on TVDB and Trakt but not TMDB, that might be the issue

**Comment by Tikipeter** [comment]
I can't open that file you attached Sassafrassa, but you are most likely correct as to the reason it did not show. You did a good thing adding it to TMDb, as it now shows for me when I searched for it. :)

Whilst Fen will use TVDb for more accurate episode and season info, it does still need info from TMDb initially. So your reasoning was sound and you fixed the problem as well.

Now, getting sources for the show might be a whole other issue....
