### ISSUE TITLE
Some shows and movies fail to load until I clear the meta cache (+ workaround)

### ISSUE THREAD

**Issue by dsemy** [Tikipeter/repository.tikipeter#28]
When loading large lists of movies or shows (usually, sometimes this happens with very short lists too), some items fail to load (I noticed it first since items from my Trakt watchlist and up next were missing, but it seems to happen with lists from any source).
This issue persists - the shows and movies that failed to load can't be accessed through Fen in any way (whether by searching for them, reloading the lists, etc.).
The only way to make the missing items appear is to clear the meta cache - but there are always at least a few shows/movies missing (seemingly randomly).
I'm not very experienced with writing Python, and I have virtually no experience in developing Kodi plugins or interacting with TMBD's API, but I managed to figure out a workaround - as you can see in the log (attached at the end) the following error seems to reappear a few times:
```
ERROR <general>: /home/daniel/.var/app/tv.kodi.Kodi/data/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.themoviedb.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
                                                     warnings.warn(
```
I realized after a while that this issue always appears when Fen fails to load an item; this eventually led me to the ```get_tmdb``` function (which appears almost identically in both ```resources/lib/apis/tmdb_api.py``` and ```resources/lib/metadata/tmdb.py```) which can make an unverified request if the first (verified) attempt failed.
The original function looks like this:
``` python3
def get_tmdb(url):
	try: response = session.get(url, timeout=20.0) # timeout instead of 20.0 in tmdb_api.py
	except: response = session.get(url, verify=False, timeout=20.0)
	return response
```
I figured out a (naive) way to fix this, by redefining the function as:
``` python3
def get_tmdb(url):
	success = False
	while not success:
		try:
			response = session.get(url, timeout=20.0)
			success = True
		except: success = False
	return response
```
(I'm using my own TMDB API key just in case BTW, not sure if repeated requests like this might get the default one blocked).
So far, this seems to be working fine - no shows or movies are missing anymore.

[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/9500882/kodi.log)

**Comment by Tikipeter** [comment]
I appreciate the post very much.

I've implemented something in the next update that should help to cover this, but I'm only willing to retry TMDb once.

**Comment by dsemy** [comment]
Are you not willing to retry TMDb more than once to avoid having the default key blocked?
If so, would it be possible to optionally allow this when supplying your own key?
Thanks for your work BTW, Fen is seriously the best addon out there right now, I’m looking forward to trying out the next version.

**Comment by Tikipeter** [comment]
It's more out of respect for TMDb's service. Some users have lists with 100's of items, and if they don't paginate that list in the settings then not limiting the calls to TMDb could be troublesome.

To be honest what I've implemented for next update is a bit of a quick fix. And the overlying issue of why you've been getting no response from TMDb is a bit of a worry. Their API is rock solid normally and can handle a lot of requests at once.

Also what I do when there's an issue with movie/show meta should be looked at as well. As you encountered, at the moment I simply make some dummy meta and tell the list builder to ignore it. It is then cached that way for 2 days. I took this approach originally because of TMDb's very reliable API. If no meta was returned, it was always because they didn't have meta for that item usually because it was from a Trakt list and Trakt had assigned it an incorrect tmdb id.

**Comment by Tikipeter** [comment]
Anyway, I need to push an update now, and will look into this issue more after that and hopefully come to a better conclusion with more time on my hands.

**Comment by dsemy** [comment]
The new update unfortunately did not seem to make any difference for me (except for changing the order of the "Next Episodes" list for some reason).
I think the only way to "fix" this issue without retrying TMDb indefinitely is to mark items for which there was an issue getting metadata, and then trying to get metadata for them again whenever a list they are in is (re)loaded.
This is basically the same as my workaround, just manual - which should also limit the rate at which a user could potentially make requests to TMDb.

**Comment by Tikipeter** [comment]
>I need to push an update now, and will look into this issue more after that

Next update will make dummy metadata (6 hours life) if the movie/show is not found by TMDb, or no dummy metadata (so will check for meta each list load) if any other error from TMDb.
