### ISSUE TITLE
Fen forces you to scrape twice before it shows results?

### ISSUE THREAD

**Issue by Johnyleo16** [Tikipeter/repository.tikipeter#280]
First off,  thank you Tikipeter for the amazing work you've put into this add on.  Nobody has better speed and customization for a kodi add on then you. 

Now the issue at end...

It seems this issue starting happened directly after the update that added My Accounts/Fenom scrapers 

I got real debrid and everything enabled. I'm definitely getting results and for the most part Fen works. However, 75% of the time I click a movie or a tv episode to autoplay a video , Fen will display the number of 4k, 1080, 720p links etc while it's scrapping, finish it's scrapping, then it'll tell me "no results". If I click it again and wait like 5-10 seconds, the display will come up again but this time it'll actually auto play one of those 4k/1080 results I saw from the first time I scrapped.

Why is it that Fen is bugging out 75% when you click a movie or tv show episode ? Normal behavior should be, it scraps, finishes scrapping, then autoplays the link which is 25% of the time. But most of the time it'll scrap, finish scrapping, then say "no results", forcing you to click the movie/tv show again, scrap, and then suddenly there's results and it autoplays the episode.

**Comment by Tikipeter** [comment]
I'll leave Reddit to answer your question as you decided to post this message there as well.

**Comment by Johnyleo16** [comment]
Reddit seems unable to solve this problem. Other people are experiencing this issue as well. I believe it's a bug that cannot be fixed by any tinkering client side, hence why I posted here first.

**Comment by Tikipeter** [comment]
Reddit is unable to solve any problem. It's NEVER worth posting these kinds of issues there.
If you turn off autoplay does everything work as expected?

**Comment by Tikipeter** [comment]
I won't be able to check in here for a while from now, so the one suggestion I have would be to turn OFF "Reuse Language Invoker". You can find that at the bottom of the Tools menu. Then restart Kodi and try again.

**Comment by Johnyleo16** [comment]
Yes I can confirm this issue is present even when turning off autoplay. Turned off auto play, click a movie, it scraps, and then it'll tell me there was links : 3-- 4k links, 10 ---1080p links etc and then despite that, it will say "no results" forcing me to click the movie again and actually get results 5-10 seconds later.

I noticed additional glitches as well. Sometimes the scraper loading panel will fail to update how many 4k, 1080p, 720p, sd links there was and remain at 0 but it'll still load all the links at the end of the scraping result. Other times it'll hang at scraping from 21 providers to 20 providers until it time's out but usually a rescraping will fix that and it'll work properly again.

I'm using the new Google TV chromecast by the way, and the same issue persists on my Mi Box S as well. Both only have Fen and Rising Tides (sports addon) installed but besides that the Kodi build is vanilla for both clients. No bloat, builds or slow downs so rest assured nothing is interfering with Fen. 

I should still note again this issue seemed to start occuring after the the Accounts and Fenom scrappers update.

I will try to turn off "Reuse Language Invoker" and see if the issue persists

**Comment by ANHBOB** [comment]
I too have this problem. Using the 4K Firestick.

**Comment by Johnyleo16** [comment]
I can confirm, turning Reuse Language Invoker off /false does not fix the issue. It still persists even after turning that option off, restarting kodi, and restarting the chromecast itself.
