### ISSUE TITLE
[Enhancement Request] Auto copy to clipboard Debrid/Trakt code on authorize window

### ISSUE THREAD

**Issue by TwilightMercy** [Tikipeter/repository.tikipeter#280]
Hi Peter,

Congratz on releasing `FEN 3.1.18`, with `reuselanguageinvoker` on it's faster than ever, and window transitions are very smooth.

My question/request is, to save some extra seconds manually typing the code in a Debrid provider website / Trakt - 
Is it possible so the code will be auto copied to clipboard (Windows PC in my example) when the window pop ups?

![image](https://github.com/Tikipeter/repository.tikipeter/assets/29895680/850ed8f4-a4cf-449f-9a25-998aba172b63)

Thanks for everything.

**Comment by Tikipeter** [comment]
Done.

**Comment by TwilightMercy** [comment]
Thank you KING!

I've tested on Windows PC and all Debrid providers + log uploads URLs copied!
Except for Trakt authorization, can it be added as well?

![image](https://github.com/Tikipeter/repository.tikipeter/assets/29895680/aa5b2b14-b576-404b-92d1-6549fa3e60c6)

**Comment by Tikipeter** [comment]
Trakt: Done for next update.

**Comment by TwilightMercy** [comment]
Thanks, works well
