### ISSUE TITLE
Autoscrape episode episode thumb not displaying 

### ISSUE THREAD

**Issue by JFG1000** [Tikipeter/repository.tikipeter#281]
![20230722_084515](https://github.com/Tikipeter/repository.tikipeter/assets/76907836/9d32e87b-225a-4830-9c3f-268633c68e01)

Hey tiki thankyou for update, unfortunately the episode thumbnail is not displaying this is with the setting turned off to that you made to avoid spoilers

**Comment by IG2022** [comment]
> ![20230722_084515](https://user-images.githubusercontent.com/76907836/255318259-9d32e87b-225a-4830-9c3f-268633c68e01.jpg)
> 
> Hey tiki thankyou for update, unfortunately the episode thumbnail is not displaying this is with the setting turned off to that you made to avoid spoilers

It looks like the problem could be with the custom skin xmls. Go to Settings. General. Use custom xmls when available and set that to False. I've done that and the next episode thumbnail is displayed. Maybe give that a try and see if it works.

**Comment by JFG1000** [comment]
That done it many thanks also looks alot better now with it set to false i think

**Comment by IG2022** [comment]
> That done it many thanks also looks alot better now with it set to false i think

Glad it's working for you now. I agree, I think fens next up window looks much better than the custom one for AH2.

**Comment by Tikipeter** [comment]
This solution is fine, but I'll update the xustom skin files when I get home from work.

**Comment by Tikipeter** [comment]
Should be fixed with custom skins version 1.4.3
