### ISSUE TITLE
Lost authorization

### ISSUE THREAD

**Issue by ANHBOB** [Tikipeter/repository.tikipeter#281]
Last night after work I saw there was an update for Fen. I updated and everything was fine. This morning there was an update for Fenom Scrapers so I updated that. After updating the scrapers, I went into My Accounts and checked.  My Trakt account was still in there, BUT my Real Debrid account was not..completely gone. I had to log back in to Real Debrid and re-authorize My accounts.

There have been so many issues with things not working correct ever since the newer version (Fen, My Accounts, Fenom Scrapers). I wish things could work as well as before.  Fen has always been my number 1 addon and I appreciate all the work you have done.

**Comment by Tikipeter** [comment]
You're right. I will shutdown Fen tomorrow. My apologies.

**Comment by 123Venom** [comment]
> 
> but before major changes it should be tested extensively on all platforms (Android, PC, etc)
> 
> This is kinda like what I'm going through with my Iphone. They test the beta for about 3 months...do a public release, then all the problems pop up. 2 weeks later release a fix....more problems..release another fix...more problems again, again,again for about 10 months until they finally get it right. 2 months later release ANOTHER new Ios and the problem cycle starts all over again.

Look at this asshat thinking he's got all the answers....then do it yourself and lets marvel at your brilliance!  Also since you believe devs should invest their free time in testing ALL platforms like a paid business then why don't you purchase the hardware and mail it to him?  Dick!!

**Comment by ANHBOB** [comment]
> 
>  asshat  Dick!!

Very mature of you Venom

**Comment by ANHBOB** [comment]
> 
> 
> You're right. I will shutdown Fen tomorrow. My apologies.

My Apologies Tikipeter. I have always said how much I appreciate all you do and how I've said you addon is truly unique. Please don't shut Fen down because of my comment. I will never post on here again if you keep Fen going. I'll keep the problems I'm having to myself.
