### ISSUE TITLE
ANNOUNCEMENT: Github Repository Web Source Closed.

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/repository.tikipeter#282]
The github web source **Tikipeter.github.io** is now closed. Anyone with the Repo installed this will not affect. Hopefully it should stop new user installs for now.

If you need to install the repo, download the zip from here and install from zip.

**Comment by Johnyleo16** [comment]
May I ask why you are closing this option for new users?

**Comment by Tikipeter** [comment]
I am likely discontinuing Fen and removing the repo so I don't want new users adding the repo and addon. This will stop the vast majority of new users from installing what will likely be an abandoned addon.

**Comment by Tinuz97** [comment]
😕😢😭
I have no words for it, but I am sad now. 
The only addon that I use, and I loved to help in translation as a gift for your efforts, to do something back. 

But I understand it, I did see that 1 ticket today, and I was also like Wtf. And I did feel this coming afterwards. 
I'm realy sad at the moment 😟

**Comment by Johnyleo16** [comment]
I don't understand. Why is this addon suddenly being abandoned? Are you just tired of working on it? Are you making a new addon?  

I'm not hating or shaming. I'm just curious is all.

**Comment by Tikipeter** [comment]
Im hoping to sort something out, but it must involve significantly lowering

**Comment by Tikipeter** [comment]
I'm hoping to sort something out, but it needs to include a significant decrease in user numbers. There will be fair warning here before my next step.
@Tinuz97 I wont forget about the effort you have given Fen. I consider you a friend. I just need to "cull the herd". Don't worry.

**Comment by dvdbouns** [comment]
Please don't stop your addon!

I've been using it for several years and I've never opened a ticket, that shows the quality of your addon!
I would like to help you but I think my knowledge is too limited...
Personally, I think it's the reuselanguageinvoker option that is the problem. Because since 1.7->1.8 I have some bugs. This does not prevent the use of your addon which is really great !

Thanks again for your work !

**Comment by Johnyleo16** [comment]
I agree with Dvd, you're addon is phenomenal and it'd be a shame to see it close! I really hope you'll reconsider or find a solution to whatever problem has caused you to consider closing it.

**Comment by Tikipeter** [comment]
I've re-added the 1.7.12a Fen zip to the zip folder.
This is the last version before the big changes to Fen that have caused issues for some.
I deleted this as I always do when updating, as I like to keep only 2 or 3 versions in the git folder.
Anyone with troubles with the current version can install this and use. You will need to install Openscrapers and ResolveURL first though manually if you want to use this version and don't have those 2 installed on your system.

As far as I'm aware Fen is Kodi 19 ready. It won't work for external scrapers at the moment because the conversion of them to Kodi 19 is not complete. But, Fen itself is ready for Kodi 19 and will hopefully continue to work if development stops.

**Comment by Johnyleo16** [comment]
Alright. Well thanks for everything I guess. If you really are done with the addon, may I ask why? Are you tired of developing for it? Or is attracting too much attention?

**Comment by Tikipeter** [comment]
@Johnyleo16 

I'm not done with development of Fen. I still love my **HOBBY** of coding for it, learning as I go. I have simply grown weary of certain entitled users that have been growing and reached a crescendo this morning with ANHOB's Issues post.

I never released Fen for use. It was made for me to use. But some stupid website put out the github address and that was that. I'm not a professional coder, I don't have huge amounts of time for "product support", and I don't have hardware for 10 different Kodi platforms to test on. I am unable to provide that level of support, and it is unfortunately true that that is expected by some when using another's addon.

I can speak for certain that **EVERY** developer of Kodi addons over the many years I have been around the scene has a similar story to that. Nobody does this for money, notoriety, or anything else. It's a love of the coding; seeing if you can get Kodi to do something you want it to do. There is a level of satisfaction when others say they enjoy using something you have created, but that is tempered by the constant aggressive assertions and demands put on you by a certain type of person.

I found myself developing a short fuse with regard to handling those people, and that's not something I want to have manifest itself within me. I'm normally quite a well mannered individual. That silly woke term "toxic" comes to mind when dealing with Fen issues these past few weeks.

At the moment the only thing that has changed is I have made it much harder for new users to install Fen. I don't want new users installing Fen right now. I'm hoping I can come to a decision of what to do soon, but as I said it needs to involve severely diminishing the active user base. If you **love** Fen and it's all you want to use, or you have a Furk or Easynews account and rely on Fen for that, then I want the addon available to you. If not, I would rather you use something else that serves practically the same purpose. By saying "you" I don't mean you in particular.

**Comment by jfudger** [comment]
Im setting up my new home theatre pc and the source address didn't work so I  came here to see what was up.    I felt nauseous when i read that ticket. Thank you for everything. Most of us do appreciate all of your hard work. What a jerk.

**Comment by Tikipeter** [comment]
@jfudger  Grab the repository zip from here and install using that. It will work the same.

**Comment by pcliff069** [comment]
I too will add that I will be very sorry if you abandon a great addon.
If it is so it is so - but thank you for a great Kodi addon and all the best for your future.
Cheers from Down Under (via Thailand)

**Comment by jfudger** [comment]
Thanks. I got it. I'm not the kind of user you have to worry about.  I read logs and generally figure it out myself. With Kodi, its almost always a dependency.  Just wanted to leave a thank you.  Ir seemed like you were having a crappy day

**Comment by Johnyleo16** [comment]
@Tikipeter I appreciate the explanation. It's clear you've felt this way for awhile. I'm sorry a few rotten apples have soured your experience for a project you very much enjoyed developing for. Whatever you do, I hope it satisfies you. I'm sure me and many other Fen users greatly appreciate your work. It's truly a master piece of a kodi project and to have it available for free was a real treat.

I hope we'll see your work continue to be worked on in Kodi in the future. But for now, I'll hope Fen will last the test of time , atleast for a little while. Thanks for reuploading Fen 17.1.2. It seemed pretty stable last time I checked so I'll downgrade if I got any major issues with the latest version.

**Comment by xyzfre** [comment]
I have to say I’ve been using Fen since it came out your work is amazing a very unique addon I really appreciate all the hard work you put into this project I have had no issues since the major update,, and as a end-user I always look forward to updates and changes it’s part of the Kodi world Plus it’s great to see a addon evolve to something better and better and for that to happen there Has to be constant changes and updates some people just don’t understand that part nothing in life is ever perfect unfortunately but we always try our best to make it work I have to say I was speechless when I read your post I downloaded the zip just to have it as a back up I really hope in the future you continue to develop Fen thank you again for all your hard work my friend
