### ISSUE TITLE
Github Repository Web Source Re-Opened.

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/repository.tikipeter#285]
The address `https://tikipeter.github.io` is once again working as a Kodi source for the Tikipeter Repository.

**Comment by Junkdewd** [comment]
👍👍👍👍🖖🤜🤛

**Comment by Carl535** [comment]
Thanks my friend 👍

**Comment by pcliff069** [comment]
thanks - best wishes for a continued fantastic development
