### ISSUE TITLE
ANNOUNCEMENT: Next version of Fen (3.2.01) will drop support for Kodi 19.

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/repository.tikipeter#286]
Unfortunately this is the end of the road for Kodi 19 support. Often an addon will continue working with multiple past versions of Kodi, but the change in list item building between Kodi 19 and Kodi 20 has meant that 2 sets of code for some functions have needed to be maintained.

This is now the end of the road for the support of the Kodi 19 code.

If you are still on Kodi 19, my suggestions are to upgrade to Kodi 20, or use a different addon moving forward.

**Comment by casedup** [comment]
oh just seeing this, didn't realize you were dropping support, thanks!
