### ISSUE TITLE
Fen returning no results on multiple devices

### ISSUE THREAD

**Issue by test10keystep** [Tikipeter/repository.tikipeter#288]
A fresh install of fen on multiple devices returning no results when searching for any tv show or movie.

Installed on:
Android
Mac OS
Windows 10log shows
- Control 500 in window 10025 has been asked to focus, but it can't
- ignoring action because topmost modal dialog closing animation is running

Any ideas as to what it could be, or should I simply give up on fen and move on?

**Comment by Tikipeter** [comment]
Give up on Fen and move on please.
