### ISSUE TITLE
Possible custom actions bug

### ISSUE THREAD

**Issue by ivarbrandt** [Tikipeter/repository.tikipeter#289]
For some reason "Open Fen Options Instead of Kodi Context Menu (for Media)" toggle isn't working for widgets. It is working inside the addon though. 

I'm not sure which version this started on but it couldn't have been more than 2 versions ago as I constantly use this feature.

Let me know if you need anything else.

**Comment by Tikipeter** [comment]
Already found and fixed for next update.

I won't wait too long to push it out.

**Comment by ivarbrandt** [comment]
Awesome. Thank you!

Of course I use your test repo lol. I'm on the bleeding edge.

**Comment by ivarbrandt** [comment]
Working perfectly now. Thanks again.
