### ISSUE TITLE
Downloading not working (bug?)

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#29]
I tryed to set different directory's ,also the stock settings.
It downloads ,shows % how far the download is, and if it is ready it shows complete, but the file is not in the folder that is set.
Is it just me, or a bug? (no idea how to log it )

Edit: I use realdebrid (links also) for it.
Edit 2: I did scan my hdd for the file, not on my hdd anywhere .

**Comment by Tikipeter** [comment]
Was it a Movie/TV Show with a special character in it (:, ', ~ etc)?

**Comment by Tinuz97** [comment]
Ah, yes.
Spider-Man: Far from home.

**Comment by Tikipeter** [comment]
Thanks Tinuz. I will have a look now....

**Comment by Tikipeter** [comment]
Fix will be in next update. May be a day away from uploading, so probably best to download the movie from another add-on Tinuz97. :) :)

**Comment by Tinuz97** [comment]
I am not in a hurry, normally I just stream, but I wanted to test it for fun :)

**Comment by Tinuz97** [comment]
Found another bug I think, or maybey it is just a limit? No idea.
I did like allot of Trakt user lists, but I only can see 10 as a max (limited, or bug?)

**Comment by Tinuz97** [comment]
Checked the 'liked lists' in Seren, shows all 39. So I guess 10 max in Fen is a bug.

**Comment by Tikipeter** [comment]
Interesting. Let me check....

**Comment by Tikipeter** [comment]
Yep, Trakt puts an automatic limit of 10 items unless you override that within the API call. Nothing said about it in the docs. They do this with hidden items too, and it took me ages to figure out why that wasn't working properly. I'll assume the same is true for Personal lists, so I'll test the limit param for that call as well.

Unfortunately I just pushed an update, so I'll fix this, see if there's anything else I can do quickly, and release 1.5.50a.

Thanks as always Tinnuz97. :)

**Comment by Tinuz97** [comment]
No problem, I like to test and find/report things 😄
(my favorite addon, I only use Fen and Seren).

**Comment by Tikipeter** [comment]
Looks like regular user lists is OK without the 'limit' param, but it doesn't hurt to leave it there. Who knows with the Trakt API....

**Comment by Tinuz97** [comment]
I am so fast with pressing 'check updates', the new fix shows all my 39 liked lists now, thank you 🎉
