### ISSUE TITLE
Trakt Next Episodes out of order after update to 3.0.10

### ISSUE THREAD

**Issue by meesterexx** [Tikipeter/repository.tikipeter#29]
After update from 3.0.09 to 3.0.10, Next Episodes is out of order, showing things I haven't watched in years at / near the top. Also, clearing Fen cache results in a different order of next episodes, so it's not even sorting the same each time. I noticed this on my main build which uses Arctic Horizon 2, so the screenshots and log below are from a portable build using the default Estuary skin to eliminate any skin/view type/widget issues. I also tried it with and without Paginate Lists enabled to see if it made any difference, which it didn't :

Log attached:
[next.episodes.issue.log](https://github.com/Tikipeter/repository.tikipeter/files/9536086/next.episodes.issue.log)

I have the next episodes settings set to recently watched/descending:
![screenshot00006](https://user-images.githubusercontent.com/13154733/189373845-5d383a49-9db4-469d-b408-c1377af4f8f4.png)

Correct watched recently order from 3.0.09:
![screenshot00000](https://user-images.githubusercontent.com/13154733/189370183-2c954636-3758-4453-a421-b813557df668.png)

I updated 3.0.09 to 3.0.10, cleared all Fen cache then went back to Next Episodes. Incorrect 3.0.10 #1:
![screenshot00002](https://user-images.githubusercontent.com/13154733/189370394-c3532b59-d09c-4c28-8951-c3dde2759a76.png)

Cleared all Fen cache again. Incorrect 3.0.10 #2:
![screenshot00004](https://user-images.githubusercontent.com/13154733/189370512-dfc3e03f-0104-4b51-b03d-4024ed0a4d72.png)

For comparison, TMDBHelper still has correct order (Fen is set to show episodes airing today at top so show 1 & 2 are switched in this pic):
![screenshot00005](https://user-images.githubusercontent.com/13154733/189372722-17ad8f1c-53b1-4b10-a32b-206e3808567a.png)

**Comment by Tikipeter** [comment]
Home from work.... I'll check out what's going on....

**Comment by Tikipeter** [comment]
Fixed for next update, which will be soon as this needs to be working correctly. Good job on this Issue, I had a lot of info to go on. 🥇 

In the meantime, if you turn off sorting episodes airing today to top you should get the correct sort ordering.

Also, since it was brought up, it would likely benefit you to hide from Trakt progress some of the shows that you haven't watched for years. It will make the list load quicker. Also any finished shows can be hidden.

**Comment by meesterexx** [comment]
Turning off sorting episodes airing today to top resolved it. I'll set it back after the next update. 
Thank you very much for the quick fix and the Trakt tip, much appreciated!
