### ISSUE TITLE
Artwork Issues

### ISSUE THREAD

**Issue by JayDee696969** [Tikipeter/repository.tikipeter#290]
Hello, ive been having issues with the artwork showing up, all artwork. Posters, fanart, etc. Ive done some troubleshooting and determined its only an issue on Android devices. Windows seems fine. I have tested with a fresh install on both Os's with only installing the repo and FEN. I believe this started with the previous update 1.8.13, or maybe a few days after.  Again, this issue seems to be only on Android.  What is this decoderfilter.xml that FEN seems to write to userdata??
ERROR: CCurlFile::Stat - Failed: Failure when receiving data from the peer(56) for http://image.tmdb.org/t/p/w780/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg

[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/5387581/kodi.log)

**Comment by Tinuz97** [comment]
I have this issue also on Android. (but weird, did not had this before), Windows 10 no issues. 

Password to view logfile: CWyxfJ3A6C

Log:
 
https://pastebin.com/afPjSDkb
https://pastebin.com/afPjSDkb

**Comment by xyzfre** [comment]
I’m having the same issue with poster images started today yesterday everything was fine

**Comment by xyzfre** [comment]
Using a Nvidia Shield

**Comment by Tinuz97** [comment]
Just checked my shield (log above from my phone), worked yesterday without issues, but also missing artwork, only see the ones in cache from yesterday. I guess the log will say the same, not checked it (bedtime for me now).

**Comment by xyzfre** [comment]
I did have some poster images this morning but I decided to clear thumbnails which I rarely ever do and now I get none ,but wanted to give it a shot first because you never know

**Comment by xyzfre** [comment]
And on my end it started before today’s update really appreciate all your hard work my friend

**Comment by Tikipeter** [comment]
Unfortunately it's a combination of TMDb/Cloudflare and Kodi issues.
Kodi's TMDb scraper broke for a lot of users, and this was the reason.
Hopefully I can change the calls to TMDb artwork to `https` instead of `http` and fix this issue, but I need to test it on another machine, because my main coding machine is windows which is not suffering from this issue.

**Comment by Tikipeter** [comment]
Looks like switching to `https` fixes the issue.
I'll push an update now for `script.module.tikimeta` which will fix the poster/fanart/cast images.
I'll also need to push an update for Fen when I get the chance to fix other artwork used within Fen that relies on TMDb.

**Comment by JayDee696969** [comment]
Thanks Tikipeter!!

**Comment by Tikipeter** [comment]
There weren't many instances to change in Fen, so I've done that too.
Both tikimeta and Fen will be updated in a second.

When that happens, if you only have a few not showing posters, it would be better to reload the metadata for each instance by pressing context menu on the item not showing a poster, then Add/Remove->Remove From...->Remove From Cache. This will remake the metadata for that item.

If you have this problem with a lot of titles, then go to Tools->Clear Databases and Clean Settings Files->Clear Meta Cache and that will clear the meta for all items.

**Comment by JayDee696969** [comment]
Thanks, after the update, I needed to go to Tikimeta Settings and clear cache. All artwork is back up. THANK YOU!!

**Comment by Tinuz97** [comment]
Https fixed it for me also 🎉

![Screenshot_20201016-055747](https://user-images.githubusercontent.com/47715606/96211398-89f3a080-0f74-11eb-840f-a2e4c28cf6c4.jpg)

**Comment by xyzfre** [comment]
Thank you Tikipeter Everything is working perfect again thank you for all your hard work my friend
