### ISSUE TITLE
ANNOUNCEMENT: Repository Updates

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/repository.tikipeter#290]
Please make sure the Tikipeter Repository is on version 1.0.2.

There was a minor change to this repo's structure, meaning if the repository was not updated to 1.0.2 when it was released, you will not receive any updates moving forward.

If you are on a lower version of the repo, install it again from the github.io address.

Kodi 19 and below has been disabled for this and future repo updates.

**Comment by xyzfre** [comment]
I updated the repo yesterday when it was released 1.0.2 but today with the new release of Fen 3.1.21 it did not auto update it still shows the previous version of Fen 3.2.01

**Comment by Tikipeter** [comment]
That's OK xyzfre.

That 3.0.21 is there so I can point people to it who a accidently screwed up with the recent pulling of Kodi 19 support.

The 3.2.01 you have installed is the latest version of Fen.
