### ISSUE TITLE
Playback from information view

### ISSUE THREAD

**Issue by Megazildjian** [Tikipeter/repository.tikipeter#292]
When pressing play button from information view, it scrapes links but then just displays spinner indefinitely with results in the background until you hit escape or back button, which then gives playback failed message. This is with results display set to directory and auto play disabled. Works fine when auto play is enabled.

[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/5389295/kodi.log)

**Comment by Tikipeter** [comment]
It won't work from the Info screen through Fen.

**Comment by Megazildjian** [comment]
Correct. This works properly with other similar add-ons, just not with my favorite add-on, which is Fen. Really hoping you can fix it.

**Comment by Tikipeter** [comment]
There's nothing to fix. What I was saying above is it will not work through Fen. It is not offered as a feature.

**Comment by Megazildjian** [comment]
To make something work properly is not a feature, it's baseline standard functionality. This is a bug and can be fixed if you choose to do it.  If not, well then it just will not be fixed. Either way a great add-on with just that one little problem. Thank you for your time.
