### ISSUE TITLE
Link Media to Debrid Cloud not working

### ISSUE THREAD

**Issue by znre** [Tikipeter/repository.tikipeter#293]
Maybe I'm missing a step

So I have this torrent cached in my Real-debrid cloud: "Reply.1994.2013.2160p.WEB-DL.x265.10bit.AAC-Deresisi" 

![image](https://github.com/Tikipeter/repository.tikipeter/assets/70197545/ba30dbb7-b03c-4012-9b98-f8b7f5298f56)

I have successfully linked it in Fen using "Link Movie/TV" option.

![photo_2023-08-02_17-14-10](https://github.com/Tikipeter/repository.tikipeter/assets/70197545/aee17574-a0e1-48c6-aa48-732f8f6626c1)

When I try to scrape the show for sources, no results can be found:

![Fen Scraper Results](https://github.com/Tikipeter/repository.tikipeter/assets/70197545/cab10356-3e9d-4cd9-a6ac-fb6bc01e31d7)

I have double checked that the "Search Cloud Storage" option is enabled and I also tried clearing all cache.

![Scrape RD Cloud Storage](https://github.com/Tikipeter/repository.tikipeter/assets/70197545/c5a28ee8-ffaa-4056-a710-6a05ca65689d)

Any feedback will be appreciated. Thanks!

**Comment by Tikipeter** [comment]
What happens when you select to access the filtered results? Does it show then?

**Comment by znre** [comment]
Nope, it just shows an uncached torrent

![photo_2023-08-02_18-31-19](https://github.com/Tikipeter/repository.tikipeter/assets/70197545/853b2a46-d623-436d-9186-4bf9059f8f62)

Does the version of Kodi possibly affect this? I'm running a nightly version of Kodi 21.

**Comment by Tikipeter** [comment]
>Does the version of Kodi possibly affect this? I'm running a nightly version of Kodi 21.

Shouldn't do.

I can see from the file naming of the files in that torrent that they won't be picked up by the scraper, whether there is a link or not. There is still incorrect naming at the file level.

You will need to play those files through Services.

**Comment by znre** [comment]
I see. Is it expecting a different file name? I know the alternative title is "Answer Me 1994"

**Comment by Tikipeter** [comment]
Not that. It's expecting some correct variation of SxxExx as is the convention. So even though the name of the TV Show is irrelevant once "linking" has occured, Fen still needs to pick the correct file from the list of files. To do that it needs one of 9 variations of SxxExx conventions to be met.

Simply tagging the files as "E01, E02" etc will not be good enough, as is the case with the contents of this torrent.

**Comment by znre** [comment]
Ahh I see. That’s unfortunate. Thanks for looking into it!
