### ISSUE TITLE
Cannot find cached results for some content

### ISSUE THREAD

**Issue by 666jones** [Tikipeter/repository.tikipeter#294]
I am using fen and another addon. Both use Coco scrapers so all settings there match.

However I am often getting different results. Fen struggles to find the cached results. 

Just wondering if there is a setting I can change. I have looked in the settings and tried playing around before making this post so if it is a simple setting I am sorry for wasting your time.

I have included a log and some photos. The photos are of the same episode.

Kodi 20.2
Firecube 3rd gen
https://paste.kodi.tv/ocabejovak

![20230803_122501](https://github.com/Tikipeter/repository.tikipeter/assets/121204283/55c91d94-10a6-45e3-aafd-d6bac35a3030)
![20230803_122034](https://github.com/Tikipeter/repository.tikipeter/assets/121204283/f1b812bd-670e-4336-9dd9-4768fdc3c63c)

**Comment by Tikipeter** [comment]
That's the beauty of using multiple addons I suppose.

**Comment by 666jones** [comment]
> That's the beauty of using multiple addons I suppose.

I cleared scrapper cache and I managed to get the cached results so all good
