### ISSUE TITLE
Packs using wrong language

### ISSUE THREAD

**Issue by Junkdewd** [Tikipeter/repository.tikipeter#294]
I've been running into a few instances of a language other than my default of english when finding packs, and also individual sources with multiple language tracks. 

Is this a Kodi issue or something the add-on can do?   As an example, season 2 of paradise pd loaded the french track for all episodes. 

Not a major issue, but my technically inclined gf has needed assistance afew times.

**Comment by Tikipeter** [comment]
Unfortunately nothing can be done for this, other than making sure in Kodi's settings you have Player->Language->Preffered Audio Language set to English.

I think the trouble happens when the english audio track is not correctly named/tagged, so Kodi doesn't know what it is to switch to it.

**Comment by Junkdewd** [comment]
Understand, minor annoyance compared to the benefits.  Appreciated
