### ISSUE TITLE
Filter out HEVC links from searches..

### ISSUE THREAD

**Issue by mariofenech** [Tikipeter/repository.tikipeter#295]
Hi...first of all thanks for all your time and effort to make this addon one of a kind..we really appreciate that..

I hope I m not breaking any of the new rules by asking here..

I m using a RPi 2 for my setup and these are known to have issues and are not compatible or powerful enough to play HEVC h265 etc..
Is there a way that you can add an option to filter out HEVC from search results..

Thanks for any help..

**Comment by Tikipeter** [comment]
At the moment you can exclude HEVC from playing when using autoplay.
Do you mean you don't even want to see them when selecting a source?

**Comment by mariofenech** [comment]
> At the moment you can exclude HEVC from playing when using autoplay.
> Do you mean you don't even want to see them when selecting a source?

I dont normally use autoplay...after a search the first few links are normally all hevc..would be much easier if there will be an option also for no autoplay..thanks

**Comment by Tikipeter** [comment]
I'll have this done for next update.

The old Autoplay HEVC setting I'll move to Results->Sorting & Filtering. The options will be "Include/Exclude/Prefer (Autoplay)"
"Prefer" will be for Autoplay only. So the ones relevant for you would be Include/Exclude.

**Comment by mariofenech** [comment]
That would be perfect thanks..

**Comment by Tikipeter** [comment]
Should be working with the last update (v.1.8.16)

**Comment by ricinga666** [comment]
Hi Peter  this option does not appear on the latest update.   I have looked on windows 10 and on firestick hd and the option is not visible.

**Comment by Tinuz97** [comment]
I can't find it either,maybe overlooking it, no idea.

**Comment by mariofenech** [comment]
You will have to activate the show cam,sd stream for it to appear. .it s clashing for some reason with that setting...

**Comment by Tikipeter** [comment]
I'll sort this out for next update.

**Comment by Tikipeter** [comment]
Fixed in 1.8.17
