### ISSUE TITLE
Feature: playnext / autoplay (still watching promt)

### ISSUE THREAD

**Issue by 666jones** [Tikipeter/repository.tikipeter#296]
Would it be possible to implement a are you still watching after X amount of episodes are playef? Also if there's no action after the are you still watching promt it could pause? This is a really cool feature and it would be wonderful to see it on fen

**Comment by Tikipeter** [comment]
I removed this feature a while ago and it will not be returning.

**Comment by 666jones** [comment]
> I removed this feature a while ago and it will not be returning.

Oh that's a shame. Is it possible to install a old version of fen so I could try it out?

**Comment by Tikipeter** [comment]
Let me think it over....

**Comment by 666jones** [comment]
> Let me think it over....

Thank you very much for considering it.

**Comment by Tikipeter** [comment]
I can implement a "Pause" type setting, but it's not really a good idea to allow the stream connection to remain open indefinitely.

There needs to be a point of time when Fen decides the user is not going to interact with the next episode window and stop the stream and close the window.

**Comment by 666jones** [comment]
> I can implement a "Pause" type setting, but it's not really a good idea to allow the stream connection to remain open indefinitely.
> 
> There needs to be a point of time when Fen decides the user is not going to interact with the next episode window and stop the stream and close the window.

That sounds good to me mate and you know what's best. I don't think it's a issue if it closes due to no interaction within X amount of time. I think it's still a ideal feature. May I ask how long the user would have to make some interaction. Also thanks very much for looking into this. It is highly appreciated

**Comment by Tikipeter** [comment]
What's your input on a timeout value?

**Comment by 666jones** [comment]
> What's your input on a timeout value?

I think something like 10 minutes would be ok. But I'm not sure if that's to long and would cause problems I suppose the longer the better though

**Comment by Tikipeter** [comment]
I'll give ya 30mins.

Setting will be "Pause and Wait".

**Comment by 666jones** [comment]
> I'll give ya 30mins.
> 
> Setting will be "Pause and Wait".

Ahh that would be Very lovely. Thanks so much for implementing this your a legend and genius :)
