### ISSUE TITLE
Need Multiple Scrape to Get Results 

### ISSUE THREAD

**Issue by dazazbab** [Tikipeter/repository.tikipeter#297]
I’ve been getting No Results after first (or sometimes up to third) scrape for multiple shows and movies. There are always numbers of links shown during scrape but it always ended in No Results.

If I keep re-scraping, results would finally show up and the playback will start (playback is set to Auto Play).

I’m on Android 11 running Kodi 20.2.0 with Fen v3.2.01 and Alldebrid services.

Please see the debug log [here](https://paste.kodi.tv/iyaziwuwaz).

**Comment by Tikipeter** [comment]
Alldebrid is the issue. It is timing out on the query for whether a torrent is cached or not.

Might be worth investing in Real Debrid or Premiumize for the time being.

**Comment by AakashC2020** [comment]
Hi @Tikipeter,

I'm also facing a similar issue like @dazazbab. See screenshots below:

After first scraping:
![IMG20230805093042](https://github.com/Tikipeter/repository.tikipeter/assets/65297828/906b8f66-66f2-4eda-8b09-93b9669f95f9)

After 4th scraping:
![IMG20230805093239](https://github.com/Tikipeter/repository.tikipeter/assets/65297828/9c15fd21-ca4b-4438-9846-48e5eef81863)

As you can see in the screenshots above the DV MP4 result came after 1st scraping but the DV MKV result came after 4th scraping. This causes an issue as DV MP4 files get stuck while playing on Kodi and currently there is no way to exclude DV MP4 files in Fen under autoplay. I can exclude all MP4 files but that will exclude many other results as well. Kindly check and advise.

**Comment by Tikipeter** [comment]
Your issue is completely different to the issue opened by dazazbab. And "me too" posts are against the rules if it was the same issue.

Open a new issue with a log if you require assistance.

**Comment by AakashC2020** [comment]
> Your issue is completely different to the issue opened by dazazbab. And "me too" posts are against the rules if it was the same issue.
> 
> Open a new issue with a log if you require assistance.

Hi @Tikipeter,

Apologies! I thought my issue might be similar to this so I wrote here, and I was also not aware of the "Me too" rules. I've now opened a new ticket #298 regarding my issues.
