### ISSUE TITLE
Ability To Do Autoplay Next Episode With Autoplay option disabled

### ISSUE THREAD

**Issue by LN13uLL** [Tikipeter/repository.tikipeter#297]
Currently, you have to have autoplay enabled to do autoplay next episode.  Is it possible to split out these two options so that you can do autoplay next episode without having autoplay enabled?

**Comment by Tikipeter** [comment]
It's hard to understand what you want to have happen here.
Are you wishing to have autoplay enabled for episodes but not movies?
That's the only reason I can think of.

**Comment by LN13uLL** [comment]
I would like to be able to do auto next episode but select my own source links but currently unable to because autoplay next episode falls under autoplay.

**Comment by Tikipeter** [comment]
Ok, I think I'm with you. You want to keep the part where Fen Pre-scrapes the next episode, but have it show those next episode sources when playback ends, instead of playing automatically.

I'll need to think this over. It would be harder than it sounds,  but is interesting.

**Comment by LN13uLL** [comment]
Yep, that’s exactly it. Yea I currently have that working on another add-on where it pre-scrapes prior to the next scrapping of the next episode happens.

**Comment by Tikipeter** [comment]
Added for 1.8.17.
Please read change log.

**Comment by LN13uLL** [comment]
I’m testing out this new update but for some reason I’m not able to scrape links logged in with real debrid. I’ve tried to reauthenticate and it didn’t seem to help. I see links for PM.

**Comment by LN13uLL** [comment]
Okay looks like it’s working now. Not sure what happened earlier.

**Comment by xyzfre** [comment]
This new feature is amazing and great when your bench watching a show ,,and love the new notifications of how many episodes are left Fen Just keeps getting better and better thank you for all your hard work my friend
