### ISSUE TITLE
Reg. Scraping issues and add DV MP4 file exclusion filter for autoplay request

### ISSUE THREAD

**Issue by AakashC2020** [Tikipeter/repository.tikipeter#298]
Hi @Tikipeter,

I'm getting limited results after first scraping and the results increase after a few scrapes. For example, please see the screenshots below:

After 1st scraping:
![IMG20230805093042](https://github.com/Tikipeter/repository.tikipeter/assets/65297828/2fb77a08-facc-4d10-b205-21d25677526a)

After several times scraping:
![IMG20230805093239](https://github.com/Tikipeter/repository.tikipeter/assets/65297828/e0f46670-4aa6-4f6b-b3e6-ac75cda38ce9)

As you can see in the screenshots for Marvel's What If Season 1 Episode 7 above, the DV MP4 result came after 1st scraping but the DV MKV result came after scraping several times. This causes an issue as DV MP4 files get stuck while playing on Kodi and currently there is no way to exclude DV MP4 files in Fen under autoplay. I can exclude all MP4 files in Coco Scrapers but that will exclude many other results as well. Kindly check and advise.

It'll be really great if you can try to resolve this scraping issue, and also kindly include a file filter to exclude DV MP4 files under autoplay. Thank you!

Also, what I noticed is Scrape with All external scrapers show all results correctly after first scrape only, but Rescrape and select source or Autoplay scraping only shows limited number of results even after several scrapes, though all torrent providers are enabled in Coco Scrapers for me. Will it be helpful if Scrape with all external scrapers is somehow made default under autoplay as that option shows better results? I've also tried using VPN but the same scraping issue happened. Please advise.

After 1st scrape with All external scrapers:

![IMG20230805110314](https://github.com/Tikipeter/repository.tikipeter/assets/65297828/264fe30d-5697-4259-9a6d-eb1c9f3c55aa)

Here's my log file:

https://paste.kodi.tv/equbunocup

**Comment by Tikipeter** [comment]
It's all dependent on what the scrapers return.

Cocoscrapers is scraping torrent sites for these results. They aren't all curated somewhere ready to load up. There will be inconsistencies. That's just the way it is.

You shouldn't be doing several scrapes, you are putting undue load on the sites that supply these results. Take the first scrape and use what's returned.

**Comment by AakashC2020** [comment]
> It's all dependent on what the scrapers return.
> 
> Cocoscrapers is scraping torrent sites for these results. They aren't all curated somewhere ready to load up. There will be inconsistencies. That's just the way it is.
> 
> You shouldn't be doing several scrapes, you are putting undue load on the sites that supply these results. Take the first scrape and use what's returned.

Fine @Tikipeter. Thank you! Is there any way to implement the DV MP4 file exclusion filter in Fen? I tried adding the following exclusions in Coco Scrapers but it didn't work:

.*[.]DV[.].*[.]mp4|.*\sDV\s.*[.]mp4|.*[.]Dv[.].*[.]mp4|.*\sDv\s.*[.]mp4|.*[.]dv[.].*[.]mp4|.*\sdv\s.*[.]mp4|.*D[/]VISION.*[.]mp4|.*\sDOVI\s.*[.]mp4|.*[.]DOVI[.].*[.]mp4|.*\sDoVi\s.*[.]mp4|.*[.]DoVi[.].*[.]mp4|.*\sDovi\s.*[.]mp4|.*[.]Dovi[.].*[.]mp4|.*\sdovi\s.*[.]mp4|.*[.]dovi[.].*[.]mp4|.*\sDOVi\s.*[.]mp4|.*[.]DOVi[.].*[.]mp4|.*[.]DV[.].*[.]MP4|.*\sDV\s.*[.]MP4|.*[.]Dv[.].*[.]MP4|.*\sDv\s.*[.]MP4|.*[.]dv[.].*[.]MP4|.*\sdv\s.*[.]MP4|.*D[/]VISION.*[.]MP4|.*\sDOVI\s.*[.]MP4|.*[.]DOVI[.].*[.]MP4|.*\sDoVi\s.*[.]MP4|.*[.]DoVi[.].*[.]MP4|.*\sDovi\s.*[.]MP4|.*[.]Dovi[.].*[.]MP4|.*\sdovi\s.*[.]MP4|.*[.]dovi[.].*[.]MP4|.*\sDOVi\s.*[.]MP4|.*[.]DOVi[.].*[.]MP4

This used to work in the "playercorefactory.xml" file in Kodi. Please advise.

**Comment by AakashC2020** [comment]
Hi @Tikipeter,

Any suggestions regarding the above? I'll be rea

**Comment by AakashC2020** [comment]
Hi @Tikipeter,

I didn't understand how to implement the Undesirables filter for DV with MP4 in the Latest Fen update. Could you please suggest how to do this? Thank you!

**Comment by AakashC2020** [comment]
Hi @Tikipeter,

I'm not sure if I've annoyed you. Apologies if I did so! I just wanted your expert advise regarding my query above. However, since you've closed this ticket I guess that you don't want to reply. Nevertheless, thank you for all the hard work and thanks for the amazing add-on "Fen"!
