### ISSUE TITLE
[Question] General --> Trakt Cache --> Attempt to Reload Widgets After Refresh setting

### ISSUE THREAD

**Issue by TwilightMercy** [Tikipeter/repository.tikipeter#299]
Hi,

I've noticed this setting (disabled by default and always been for me), I was wondering what it does.
Skin used is `FENtastic` (Also with "Next Episode + "In Progress Movies" widgets used, with TRAKT account connected, if that's relevant).

![image](https://github.com/Tikipeter/repository.tikipeter/assets/29895680/9e5f3e94-c276-4e60-bb0d-fa7304a653da)

Thank you!

**Comment by Tikipeter** [comment]
Take a guess....

**Comment by TwilightMercy** [comment]
> Take a guess....

after doing SkinReload() a new episode that should appear, appears anyway in "Next Episode" widget (connected to TRAKT), with the setting disabled. So I don't know : )

**Comment by Tikipeter** [comment]
You are invoking a reload of the skin yourself? In that case the setting means nothing.

The setting is meant to reload the widgets after a Trakt resync. So that any new info from the Trakt sync is represented in the widgets.

**Comment by TwilightMercy** [comment]
> You are invoking a reload of the skin yourself? In that case the setting means nothing.
Yes, but now I know that it is not needed.

> The setting is meant to reload the widgets after a Trakt resync. So that any new info from the Trakt sync is represented in the widgets.

Great, thank you
