### ISSUE TITLE
Dialog display result

### ISSUE THREAD

**Issue by deyooluv** [Tikipeter/repository.tikipeter#299]
Fen apparently removed dialog display result after scraping and only have directory and small simple directory as the two options for display result.
This change is affecting my aura skin. Please can you bring back this option in result setting. Thanks for everything you do

**Comment by Tikipeter** [comment]
Unfortunately I cannot bring it back. There are changes in Fen that make it no longer work correctly.

If you explain the trouble with Aura, or include some screengrabs of the issue (or both), maybe I can steer you to a solution.

**Comment by deyooluv** [comment]
This happens with all skins. There is no way to pick streams after fen has finish scraping because the result is only displayed in directory in fen settings. The display result in dialog option was recently removed by you. 

With displayed results as dialog, when tmdb helper use fen player for scraping, result previously pops up after scraping is done. This was only the work around using fen with tmdb helper.

The only way to use  fen add-on is to goto the fen add-on itself and use it for scraping. Even at that one has to back out after scraping to see the result that has been diaplayed in directory format

**Comment by Tikipeter** [comment]
> .....back out after scraping...

Back out of what? I don't understand you at all.

**Comment by Tikipeter** [comment]
Fen is supposed to still display the dialog results when using TMDbHelper, or a library item, or a widget. The dialog results are still used then, I just can't have it as an option WITHIN Fen.

I'll need to see a video of what it's doing if not working in that way.

**Comment by DoBucki** [comment]
I think what he's saying is if you click a source and that Source doesn't play you can't go back and all the sources are still there you have to re scrape again, before you could just hit the back button and pick a different Source without having to rescrap
