### ISSUE TITLE
Logos are not changing when using "Set Artwork" through FEN options

### ISSUE THREAD

**Issue by Logs22** [Tikipeter/repository.tikipeter#30]
Log - https://paste.kodi.tv/nelijakubi

I've tried a couple of different shows/media to make sure it wasn't just one singular item that wasn't changing, and it seems like the logo just doesn't want to change. Very minor, but just wanted you to be aware. Keep up the great work!

**Comment by Tikipeter** [comment]
Definitely working for me. Let me know of one of the media items where it's definitely not working for you and I'll try it out.

**Comment by Wilson-Fisk** [comment]
Interesting, a couple I specifically tried, Suits logo number 2 (the red one) the office, and ted lasso. Could maybe be the skin I'm using to, I didn't think about that

**Comment by Logs22** [comment]
I used suits, ted lasso, and the office, none of them stuck but it could be because of the skin potentially, didn't think about that.

**Comment by Tikipeter** [comment]
Do you have extra fanart enabled (fanart.tv)?

**Comment by Logs22** [comment]
Yes

**Comment by Tikipeter** [comment]
I'd say that's the issue. I only really coded it to work when users were using only the default TMDb artwork.

**Comment by Tikipeter** [comment]
Let me see what I can do for next update.

**Comment by Logs22** [comment]
> I'd say that's the issue. I only really coded it to work when users were using only the default TMDb artwork.

Ah ok, will test to confirm it for you real quick

**Comment by Tikipeter** [comment]
I'll tag this as "enhancement" since at the moment it kinda works the way I wanted it to originally. But I'll try and incorporate it with fanart.tv as well.

**Comment by Logs22** [comment]
Yup disabling it shows all the logos now

**Comment by Logs22** [comment]
> I'll tag this as "enhancement" since at the moment it kinda works the way I wanted it to originally. But I'll try and incorporate it with fanart.tv as well.

Sounds good, I didn't even think that would have an effect on it, pretty simple diagnosis lol

**Comment by Tikipeter** [comment]
Cool. I'll (hopefully) get it sorted for next update. Bit more logic involved.
