### ISSUE TITLE
Fen Extras throwing error

### ISSUE THREAD

**Issue by ivarbrandt** [Tikipeter/repository.tikipeter#300]
Hey man I just thought I'd let you know of an error that is occurring on the latest test version of Fen (3.2.01h). I noticed it about two test versions ago.

For some reason when I click a movie or a tvshow it shows the `BusyDialog.xml` spinning wheel then throws an error. I tried to going back to the latest stable version on the official repo and everything works fine there.

Here is the log I was able to get but I don't see a clear error like normal: https://hastebin.com/share/ohisocicaf.yaml

**Comment by Tikipeter** [comment]
Reset the password Extras buttons.

**Comment by ivarbrandt** [comment]
That fixed it. Thank you!
