### ISSUE TITLE
Prescrape library items.

### ISSUE THREAD

**Issue by ricinga666** [Tikipeter/repository.tikipeter#300]
Hi Peter, hope you are well

I'm loving the new pre-scrape feature but I've noticed some strange behaviour.

It scrapes everything no problem and goes straight to the dialog once the current episode finishes but when you select a link it fails to play and just drops back to the library. 
Then I can click the episode again and it goes straight to the dialog and when I select a link it plays first time no problem. 

I won't be able to provide a log until tomorrow.  I just thought you would like to know. 

Regards Richard

**Comment by Tikipeter** [comment]
I'll have a look and see what's happening.

**Comment by Tikipeter** [comment]
I might have a fix for this.
Please test this next update (v.1.8.19).

**Comment by mathu204** [comment]
For the next episodes progress? Man you are a legend! Do u have. A donations box set up anywhere??
