### ISSUE TITLE
Fen not playing anything

### ISSUE THREAD

**Issue by Regaena** [Tikipeter/repository.tikipeter#301]
Last few days fen hasn't played anything, when I play something it scrapes and finds the file then never actually resolves. I checked my real debrid, and it's still got days on it, I even re authorised.

So then I decided to clear the cache of both fen and kodi, which I did - but now fen won't play anything at all with 'Fen Error - Check Logs'.

https://paste.kodi.tv/gubewopovo

After checking the logs I see something about a Python error (Error Contents: 'NoneType' object has no attribute 'update') but I don't know what this really means or how to solve it, so was hoping I could find some answers here.

**Comment by Tikipeter** [comment]
Unfortunately there's not much good news I can tell you here.

There is a Fen error in the log, but it's not anything I can fix. Kodi is the problem.

There's multiple instances of Kodi's addon manager running, almost like it's stuck in a loop, then there's instances of Kodi being unable to read some settings that Fen needs to operate.

Couple that with the fact it's taking Kodi a full 20 seconds before it even starts the services for the addons you have installed, and it looks like you've got yourself a dog of a Kodi install.

I can't even offer any useful advice other than get a better piece of hardware to run Kodi on, or fully uninstall and re-install Kodi and hope it performs better after that.

Good luck. :-)
