### ISSUE TITLE
[Enhancement] Option to use In Progress TV Shows and Movies for Subscriptions Trakt List Sync

### ISSUE THREAD

**Issue by mathu204** [Tikipeter/repository.tikipeter#302]
In Fens subscriptions there is an option to sync a trakt list of your choice which is a great feature, on top of which unlike other addons you can sync your watchlist which is great! However what I would really like to sync but is missing from this and every other addon, is my currently watching/in progress shows and movies. This would be such a great feature if it’s possible to implement.

A little background on why I want this; I’m using Titan bingie mod and to have resume points, and all seasons available in one screen like Netflix, and other features you need to have library content. So honestly the only library stuff I need/want is my in progress shows and movies to have the resume points working properly, other than that I have no problem setting paths and widgets to addon/plugin content.

 I added all my shows manually and used trakt to sync the playback/watched progress, so to be able to sync fen to put my in progress shows and movies to my library, then trakt mark the watched statuses and resume points would be dope, save time and also be very automated as trakt and fen list syncing are automatic.

**Comment by Tikipeter** [comment]
No to this one I'm afraid.

**Comment by mathu204** [comment]
> No to this one I'm afraid.

That’s a shame. Alright; may I know the reason why? Is it due to some limitation In some form?
