### ISSUE TITLE
[Enhancement] add more content to subscriptions/library outside of synced list

### ISSUE THREAD

**Issue by mathu204** [Tikipeter/repository.tikipeter#303]
I made a Reddit post and someme explained it to me so I understand if you don’t want to/it’s not possible. But the idea would be that your synced list would auto update as it does, but you’d still be able to add other shows and movies to your library through the context menu that are unaffected by the subscriptions sync.

Maybe a better idea would be to have the options to have both; you have the 2 synced lists for movies and tv that stay in their own designate folder so as they are not interfered with by the syncing. Then you’d be able to add shows and movies to library through the context menu which would be added to secondary folders for movies and tv.

So example:

### Fen subscriptions synced list settings:

**Synced list for movies:** Watchlist
**Syncler list for shows:** Collection

### Library path for synced lists
**Movies**
Desktop/Library/FenSynced/Movies
**Shows**
Desktop/Library/FenSynced/Shows

### Library path for context menu add to library
**Movies**
Desktop/Library/FenImports/Movies
**Shows**
Desktop/Library/FenImports/Shows

### My synced lists include
**My movie watchlist is:** 
John Wick, and Avatar
**Tv collection is:**
The simpsons

### And I added These to my library through fen context menu (add to library)
**movies**
Cars 3
**shows**
Dragon Ball Z.

**Ideally what would happen is my Kodi library after all this should show something like this**
### Library
**Movies**
Avatar, John Wick, Cars 3
**Shows**
DBZ, Simpson’s.

This way auto updates from syncing with the lists don’t affect the seperate Imports, so if I delete John Wick from my watchlist, it would delete from the library as it syncs, but would not attempt to delete Cars 3 bc of how it tries to sync the library to a list because cars 3 is in its own folder. The same way how if I delete John wick from the library not the watchlist, when I update library or next sync, John Wick would get imported again due to the sync.

Sorry for long post this is sent from my phone too and I tried to make it as clear as possible

**Comment by Tikipeter** [comment]
I could open up the "Add" for when you have a trakt subscription list. I'd need a setting to opt into that though, as normally the subscription update will remove anything not in the list.
Let me think it over.

**Comment by Tikipeter** [comment]
Added for next update (v.1.8.18).
You will need to set "Keep Library Items Removed from Trakt Subscription Lists" in the Trakt section of the Subscriptions settings.
Enabling this setting will also keep the "Add to Subscriptions" option available.

**Comment by mathu204** [comment]
Thank u so much bro!
