### ISSUE TITLE
[Enhancement] option to stop scrape on cloud files

### ISSUE THREAD

**Issue by mathu204** [Tikipeter/repository.tikipeter#304]
Or add it to the pre scrape option, so a setting where enabled, whenever fen scrapes/detects a cloud file it stops rhe search and begins to play that cloud file.

Cloud being debrid service

**Comment by Tikipeter** [comment]
I will need to think about this.

**Comment by Tikipeter** [comment]
This will be included in the next update (v.1.8.18).

**Comment by mathu204** [comment]
Thank you!
