### ISSUE TITLE
v3.2.0.2 Skin fonts toggle removal broke text in Extras

### ISSUE THREAD

**Issue by meesterexx** [Tikipeter/repository.tikipeter#305]
Previously, I had the setting "Attempt to use Skin Fonts in Fen Windows" toggled off because it broke the font rendering of the text right under the clear logo in Extras and the clock text. After update the text is broken again. I see the option is gone from the settings gui and it's ignoring the option that was already there in my settings.xml file `<setting id="use_skin_fonts" default="true">false</setting>`

My Extras Window now looks like this. Any way to get this option back?:
![screenshot00002](https://github.com/Tikipeter/repository.tikipeter/assets/13154733/de019c21-9bd4-4697-915a-435f746976d3)

**Comment by Tikipeter** [comment]
What skin is that?

**Comment by meesterexx** [comment]
> What skin is that?

It's my own mod of the DStealthTV skin, which itself is an Estuary mod. Aside from some formatting changes, I added some features I felt were missing like episode thumbnails on the home screen, OSD autoclose, and a whole new addon view type:
 
![screenshot00007](https://github.com/Tikipeter/repository.tikipeter/assets/13154733/80ea4e85-6244-46a2-a433-cfddcf4f034e)


![screenshot00009](https://github.com/Tikipeter/repository.tikipeter/assets/13154733/cb87b063-c4a5-47ba-aa9a-bdec29e9e5fd)


![screenshot00004](https://github.com/Tikipeter/repository.tikipeter/assets/13154733/c108dd13-6b7e-46ea-95b8-04a7ccc7a9bd)


![screenshot00005](https://github.com/Tikipeter/repository.tikipeter/assets/13154733/006340cd-bf15-4ee6-9b90-73c0915f3fec)

**Comment by meesterexx** [comment]
Ok, I found the culprit. There's an icon font used in the skin's font.xml called MaterialIcons-Regular. For some reason, Fen Extras is picking that up instead of the normal text font. I've commented it out in the font.xml  and the issue resolved. Why it's picking that font, I don't know, but I will go through the skin code and see where it's even used and see if I can get around the issue that way.
Thank you!

**Comment by Tikipeter** [comment]
Can you send me the font.xml file?

There might be an easier way of solving this than commenting out and going through the whole skin looking for uses of it.

**Comment by Tikipeter** [comment]
I can add a check to try and make sure the font selected is the `Default` font.

Before next update, if you move the `Default` fontset to the top of the list of fonts, it should be picked by Fen.

**Comment by Tikipeter** [comment]
This will be fixed next update. I'll push it shortly.

Restart Kodi after the update and it should be sorted out.

**Comment by Tikipeter** [comment]
Cool skin by the way.

Good job. :-)

**Comment by meesterexx** [comment]
> Before next update, if you move the `Default` fontset to the top of the list of fonts, it should be picked by Fen.

So, the MaterialIcons-Regular font was in the default font set, but it was at the top of the default set, I moved it to the bottom of the default set hoping it wouldn't pick it up, but it still did, even though all the other text fonts are above it. 

I checked the skin code, and the only place it's being used is in the script-skinshortcuts.xml and it's only used for the navigation icons in Skin Settings > Edit Main Menu for editing the menu and widget items (icons for up, down, delete, restore, add).
So for now I commented that font out in the font.xml and changed the script-skinshortcuts.xml file to use the standard font characters (^vXR+) from the text font for the navigation icons until I can find a different font or declare a font set for just the icons and figure out how to call that for the navigation icons.

I will test your changes when they are pushed, but since the the icon font is in the default set, I wouldn't expect that to fix it. Thank you so much for taking the time to look at this.

>Cool skin by the way.
>Good job. :-)

Thank you! Coming from you that means a lot to me!

**Comment by Tikipeter** [comment]
Oh that's a shame. Yeah the code fix was to try and get the default font. Won't fix your problem now we know.

I'll add that setting back as well to help you out. Then you won't have to worry about finding something else to use.

Give me a bit more time and I'll push the update.

**Comment by meesterexx** [comment]
That is a huge help, thank you again! 

After the push, I will also try digging around in the skin code some more and see if I can find a better way to implement the icons. Having the setting back in Fen will allow me to easily test it and if I can't figure it out (and it's quite probable I won't) it will allow the skin to work normally with the Extras window.
