### ISSUE TITLE
Tv show specials to library

### ISSUE THREAD

**Issue by djdirty60** [Tikipeter/repository.tikipeter#305]
Good evening Peter,

Is it possible that the specials of the series can also be added to the library?  That will be great.

Thanks in advance for all the work

**Comment by Tikipeter** [comment]
I will need to think about this.

**Comment by Tikipeter** [comment]
Added for next update (v.1.8.18).
You will need to got to Subscriptions settings and enable "Include TV Show Specials".

**Comment by djdirty60** [comment]
Thnx you are a hero
