### ISSUE TITLE
[Possible Bug or Enhancement] Sync to/or resume points from Trakt or Library.

### ISSUE THREAD

**Issue by mathu204** [Tikipeter/repository.tikipeter#306]
I’ll try my best to explain this, so I use Kodi on different devices and builds and I love using Fen. But here is an issue I’m facing.

I use library integration with Fen and TMDBHelper and the issue is that while I use trakt addon to mark resume points in movies and episodes (they show up as you’d expect). Picking up on another device or addon using library does not make Fen continue where I left off even though the library content shows the resume point.

So my questions or possible ideas are:

Can you make Fen read library resume points and pick up where it says? 

Or

Can Fen sync resume points across devices whether it’s through Fen, or Trakt?

Basically I would like to be able to pick up where I left off on another device using Fen; preferably if it reads the library content mark point but i don’t think this is necessary because I’ve noticed that when I play said movie or episode on the next device, skip through and back out it saves the resume point and I can resume through library again. I just have to skip to it once to register it.

I’m not sure exactly how this can be achieved but if Fen could resume where i left off on another a Kodi setup in any means it would be great. Even if it doesn’t read the library point and still resumes it would be great bc at the very least I see the “in progress” thing and fen still resumes.

PS: Apparently venom does this I’m not sure about with library but someone said it syncs trakt resume points; I much prefer Fen though, and also thank you so much for making this great addon and being as responsive as you are!

**Comment by Tikipeter** [comment]
> PS: Apparently venom does this I’m not sure about with library but someone said it syncs trakt resume points

Venom uses Trakt info to honor your resume points. Fen doesn't do that (yet at least).

Fen does SET resume points in Kodi library when you play a library item.
Let me see if I can also honor resuming from that resume point. Should be possible.

**Comment by mathu204** [comment]
> > PS: Apparently venom does this I’m not sure about with library but someone said it syncs trakt resume points
> 
> Venom uses Trakt info to honor your resume points. Fen doesn't do that (yet at least).
> 
> Fen does SET resume points in Kodi library when you play a library item.
> Let me see if I can also honor resuming from that resume point. Should be possible.

Dope! Yes honouring resume point would be wonderful as I tested that fen set the library point, which updated in my other Kodi build using trakt addon to sync. But then Fen would not resume on the next one. Would love to see this, thanks again as always!

**Comment by Tikipeter** [comment]
Honoring resume point from library playback will be supported in next release (v.1.8.19).
This is NOT honoring trakt resume points, only kodi library resume points.
So to have it consistent across different devices, you will need to sync your Kodi libraries using the official Trakt addon. That way your Kodi library items' resume points will match across devices, and then Fen will use the Kodi library resume point set by either itself or the Trakt addon.
At the moment this is the best I can do, as coding in honoring of trakt resume points is going to need to include a lot of refactoring of current trakt code.

**Comment by mathu204** [comment]
This is good enough man thank you so much! I use trakt addon already to sync library points!

I also have a secondary issue using library integration with Fen, I can’t get next up to work unless I set up in player settings in Kodi to play next episode, this is fine but the problem is whenever the next episode plays and I back out. The episode I clicked on (first episodr) marks as watched like I want it to, but it doesn’t mark my resume point in the library for the next episode.

Do you know or have an idea why this is? When I click the episode it resumes in Fen fine

**Comment by Tikipeter** [comment]
Do you have autoplay on in Fen's settings?

**Comment by mathu204** [comment]
> Do you have autoplay on in Fen's settings?
> 
> EDIT:
> Doesn't matter about answering. It's another Invalid Handle error.

I see, I do have auto play, I turned off mark watched in library and tried swapping different settings to no avail.

What does the invalid handle error mean? Is it hard to fix?

**Comment by Tikipeter** [comment]
> Is it hard to fix?

Extremely in some circumstances where code is shared between actions used within Fen and actions used without. Like this.

>What does the invalid handle error mean?

I seriously doubt half the Kodi devs could answer this! Basically (very) it's an error raised when you use an old `sys.argv[1]` value from the previous action in the new action. Or window. Or container. Or whatever else. It's a right mess. And extremely frustrating to fix (if it even can be fixed). What works to fix it in one instance doesn't work in the next instance.

**Comment by mathu204** [comment]
> > Is it hard to fix?
> 
> Extremely in some circumstances where code is shared between actions used within Fen and actions used without. Like this.
> 
> > What does the invalid handle error mean?
> 
> I seriously doubt half the Kodi devs could answer this! Basically (very) it's an error raised when you use an old `sys.argv[1]` value from the previous action in the new action. Or window. Or container. Or whatever else. It's a right mess. And extremely frustrating to fix (if it even can be fixed). What works to fix it in one instance doesn't work in the next instance.

I see, sorry am just a noob here haha admiring the work you and everyone puts. 

So does this mean it’s likely that it won’t be fixed? Maybe can any workarounds be done? 

I think maybe if u work on getting Fen to sync playback progress to Trakt when watching, if I back out it should update on trakt, then when I update library and use trakt addon to scrobble and sync, it should show up correctly.

Maybe just working on adding this feature would be easier than trying to fix a invalid handle error as you say it seems to be very hard to deal with

**Comment by Tikipeter** [comment]
I might have a fix.
Please test this next update (v.1.8.19).

**Comment by mathu204** [comment]
> I might have a fix.
> Please test this next update (v.1.8.19).

For the next episodes progress? Man you are a legend! Do u have. A donations box set up anywhere??
