### ISSUE TITLE
[Enhancements] Add whole sections of movies/shows or more than one.

### ISSUE THREAD

**Issue by mathu204** [Tikipeter/repository.tikipeter#307]
So I’ve been doing this with library integration tool but making custom .strms outside of the Fen addon doesn’t seem to play well for me.

I think it would be nice for a option in the context menu aside from add to library to be add this directory to library so for edample I click on popular movies or shows context, and add this directory to library.

It would add all the shows/movies in that directory. Granted these sections run on and on, so just the current page, say I had a widget limit of 10-15 it wouldn’t try to add hundreds of shows, just the 10-15 that would first show up when u open the directory above “Next page”.

Alternatively maybe it could open up a window where you could click each show/movie u want to add from the page.

Maybe even syncing directories would be dope if it is possible

**Comment by Tikipeter** [comment]
No to this one I'm afraid.
