### ISSUE TITLE
ANNOUNCEMENT: No Requests

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/repository.tikipeter#307]
For a little while, please no requests in the Issues section.

There's a large settings re-write underway, so I can't entertain any requests.

Also, as always, a couple of people have been annoying me with requests. So best for me to stop them for a bit.

**Comment by AakashC2020** [comment]
Hi @Tikipeter,

May be I'm one of the person who annoyed you with new feature requests. Apologies for that! I won't bother you anymore with new requests. Will only report if I notice any errors or bugs. Thank you for all the hard work that you put into this amazing add-on "Fen". Keep up the good work! Thanks again!

**Comment by 15123073** [comment]
Thank you. Appreciate you

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by xyzfre** [comment]
> Rock on Tikipeter! Don't let the whiners distract you. been with you since day one and not once have I pestered you about your great work and awesome efforts allowing us to use FEN. Thank you bud. (B B Fenny <Grin>). Has "always" worked just fine for me. My best to you and yours.

Same here. Been using Fen for 4 years now always works flawlessly thank you @Tikipeter for all your amazing work and dedication
