### ISSUE TITLE
Not an issue but a request

### ISSUE THREAD

**Issue by ozooha** [Tikipeter/repository.tikipeter#308]
Hey Tikipeter,
I know you mentioned no request but rather asking if you can just put this in your code:
~/.kodi/addons/plugin.video.fen/resources/lib/modules/kodi_utils.py

line 14
from
fen_addon_object = xbmcaddon.Addon()
to 
fen_addon_object = xbmcaddon.Addon('plugin.video.fen')

I call your code from another addon and I run into this error every time there is an update from you:
_TypeError: not all arguments converted during string formatting_

Sorry for the bother.
OZooHA

**Comment by Tikipeter** [comment]
What does that typeerror relate to?

**Comment by ozooha** [comment]
Pardon my tardiness. 
Thank you for your attention.
Here is the following error from the Kodi log when _fen_addon_object = xbmcaddon.Addon()_ (however it disappears when I replace it with _fen_addon_object = xbmcaddon.Addon('plugin.video.fen')_):
>
error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                  - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                 Error Type: <class 'TypeError'>
                 Error Contents: not all arguments converted during string formatting
                 Traceback (most recent call last):
                   File "/home/username/.kodi/addons/plugin.video.myplugin/default.py", line 485, in <module>
                     ToAddonFen(mode)
                   File "/home/username/.kodi/addons/plugin.video.myplugin/default.py", line 372, in ToAddonFen
                     routing(sys)
                   File "/home/username/.kodi/addons/plugin.video.fen/resources/lib/modules/router.py", line 30, in routing
                     from indexers.navigator import Navigator
                   File "/home/username/.kodi/addons/plugin.video.fen/resources/lib/indexers/navigator.py", line 25, in <module>
                     clear_all_str, clear_meta_str, clear_list_str, clear_trakt_str = clca_str % all_str, clca_str % ls(32527), clca_str % ls_str, clca_str % trakt_str
                                                                                      ~~~~~~~~~^~~~~~~~~
                 TypeError: not all arguments converted during string formatting
                 -->End of Python script error report<--    

> 

Also if this helps:
When I have  _fen_addon_object = xbmcaddon.Addon()_ then I get blanks for these following strings numbers and needless to add when I have _fen_addon_object = xbmcaddon.Addon('plugin.video.fen')_ then the error goes away:

`32028,32029,32036,32037,32054,32061,32063,32064,32065,32069,32070,32081,32092,32107,32118,32129,32196,32247,32450,32451,32453,32454,32456,32457,32484,32486,32487,32491,32493,32494,32496,32497,32498,32499,32500,32501,32502,32503,32504,32505,32506,32507,32508,32509,32510,32512,32514,32515,32518,32522,32524,32526,32537,32538,32546,32548,32549,32550,32551,32552,32553,32554,32555,32556,32557,32558,32559,32560,32561,32562,32563,32564,32565,32566,32567,32568,32569,32570,32572,32599,32642,32643,32702,32703,32705,32730,32731,32777,32789,32798,32805,32847,32853,32857,32858,32861,32862,32863,32864,32865,32866,32867,32868,32869,32870,32871,32872,32873,32874,32875,32876,32877,32878,32879,32880,32881,32882,32883,32884,32885,32886,32887,32888,32889,32890,32891,32892,32893,32894,32895,32896,32897,32898,32899,32900,32901,32902,32903,32904,32905,32906,32907,32908,32909,32910,32911,32912,32913,32914,32915,32916,32917,32918,32919,32920,32921,32922,32923,32924,32925,32926,32927,32928,32929,32930,32931,32932,32933,32934,32935,32936,32937,32938,32939,32940,32941,32942,32943,32944,32945,32946,32947,32948,32949,32950,32951,32952,32953,32954,32955,32956,32957,32958,32959,32960,32961,32962,32963,33017,33057,33080,33104,33107,33140
`
I hope this helps.
OZooHA

**Comment by Tikipeter** [comment]
Done for next update.

**Comment by ozooha** [comment]
Thank you.
