### ISSUE TITLE
Create Overide Option to Disable All Filters for Local Sources

### ISSUE THREAD

**Issue by bd94** [Tikipeter/repository.tikipeter#31]
Would be a nice feature to have an option to disable all filtering for local media sources aka "Folders 1-5". This would enable to have autoplay for media set to 720p and lower media, if media is found locally within "Folders 1-5" that is 1080p or up Fen would still play the local media file. Same with any other filters currently configured.

Much thanks!

**Comment by Tikipeter** [comment]
Big(ish) job that. Let me think on it....

**Comment by Tikipeter** [comment]
I can meet you half way and provide `Ignore Quality and Size Filters` for the folder scrapers. OFF by default.
![screenshot00000](https://user-images.githubusercontent.com/28930002/190276218-21b97599-473e-499c-a113-ba24b1a25587.png)

**Comment by bd94** [comment]
That will do just fine and fits my use case perfectly :+1: 

Much thanks!

**Comment by Tikipeter** [comment]
>and fits my use case perfectly

Mine too. :)
I'm sure I used to have a setting like this. Can't remember why I removed it to be honest.
