### ISSUE TITLE
[Possible Bug] TMDB Helper FallbackPlayer freezing and crashing Kodi.

### ISSUE THREAD

**Issue by mathu204** [Tikipeter/repository.tikipeter#311]
Attached a log at the bottom. Im not sure if this is a problem on TMDBHelpers end or with Fen so im posting here too but i am getting help on the TMDBH github too.

I configured Fen Player settings in TMDBH, and set Shadow (movies) as a fallback and Seren (episodes). Testing a movie out (Kung Fu Mulan; random movie that i knew wouldnt pull any links) starts scraping in Fen and about halfway through the progress window with one source remaining Kodi freezes, and eventually gives the Not Responding message on windows leading to a crash or me force quitting.

Could you take a look and let me know your thoughts?

[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/5540275/kodi.log)

**Comment by Tikipeter** [comment]
Does it ever scrape with Fen successfully?

**Comment by mathu204** [comment]
From the 6-8 times I tested it, no it froze/crashed every time. I can test later but pretty sure if I scraped without fallback it would have finished just with 0 links. Using it the other way with Seren makes Seren finish scrape with 0 links but doesn’t activate the Fen search/scrape

**Comment by Tikipeter** [comment]
From what I understand the fallback won't work that way. The fallback wont work with Seren, Fen or any Exodus fork.

You need to disable fallback and test Fen normally and let me know what happens.

**Comment by mathu204** [comment]
Closing for now as you and tmdb dev have explained why this won’t work. I’m hoping maybe it can be possible one day. Thank u
