### ISSUE TITLE
Everything is added to debrid cloud even though show packs only is selected 

### ISSUE THREAD

**Issue by ZEPLUMBER1** [Tikipeter/repository.tikipeter#311]
Basically the title.

If you select add to debrid cloud > show packs only, everything gets added to your cloud, individual episodes movies etc

Nvidia Shield and PC (Windows 11)

Kodi 20.2

**Comment by ZEPLUMBER1** [comment]
This was a misunderstanding on my part.

**Comment by Tikipeter** [comment]
Do you need assistance?

**Comment by ZEPLUMBER1** [comment]
> Do you need assistance?

No it's fine. It's you you label some links that are resolved so resuming is possible automatically that had me confused

I'm an idiot and you can shut this ticket down :)
