### ISSUE TITLE
Gretel & Hansel, no results.

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#313]
Some movies, like Gretel & Hansel, are not giving results.
The scraping goes fast like 2 seconds, immediately after that : geen resultaten (no results in English).
Tryed to change the meta language in tiki meta to English, instead of Dutch as a test, but same result. 

Tryed to take a look in the log, but there are no errors (other movies scraping and playing fine), but there are titles (released) that are giving this issue to me, can you test/replicate it?

Unfortunately I forgot which other movies are having this issue (for me), but I think it are movies that are also available in Dutch language at (IMDB I guess that Fen is using?)

The Dutch name for Gretel & Hansel is Hans & Grietje.
I think the other movies that I had issues with, are also available in a Dutch name on IMDB, but switching the Meta language in Tiki Meta did not fix it for me as a test (it did switch fine between the both names, so the English name for this movie, and the Dutch name.)

Could that be the issue? (just a theory I have).

I have no idea how to log this one, because I can't see any errors in the kodi log, is there a other way to log this?

**Comment by Tinuz97** [comment]
No idea if you fixed it, or placebo, but in 1.8.1.9 it is working again. 
![Screenshot_20201119-101800](https://user-images.githubusercontent.com/47715606/99646341-a5a90580-2a50-11eb-8731-47adbb6a6516.jpg)

**Comment by Tikipeter** [comment]
I'm keeping an eye on this as I think it is related to another current issue here.
Even though it is now working for you, there could still be a problem when using languages other than English as default.
