### ISSUE TITLE
FEN Crashing with widgets

### ISSUE THREAD

**Issue by JayDee696969** [Tikipeter/repository.tikipeter#314]
Ok, so since the last version I am getting crashing when using FEN as a widget. Before posting this issue I did the following... I wiped Kodi folder completely. Only installed Xonfluence Skin, Fen Repo and adoon. Didnt change any FEN settings, only Authorized Debrid. 
I created a widget to Movies/Latest releases. FEN plays the link fine. The crashes happen when I hit Stop to stop the movie.  I see nothing conclusive in the Kodi.log, but it is attached. No crashes if i open FEN and navigate to the same Latest releases and play from there, seems only to be an issue when played from a widget. I havent had this issue in the past, so was hoping you might have some insight. I use FEN primarily and would hate to not be able to use FEN widgets. Appreciate if you can take a look Thank you Tikipeter. 
Link to Xonfluence skin: https://github.com/Helly1206/skin.xonfluence
To create a widget using Xonfluence, add Fen latest releases to Kodi favorites, and choose the favorite as a widget to replicate the issue. 
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/5563284/kodi.log)

Kodi 18.9, Windows 10.

**Comment by Tikipeter** [comment]
@JayDee696969 

Go into Fen->Tools, and at the bottom is "Set Language Invoker". Turn that OFF, restart Kodi after Fen reloads your profile, and see if that fixes the issue.

**Comment by JayDee696969** [comment]
> @JayDee696969
> 
> Go into Fen->Tools, and at the bottom is "Set Language Invoker". Turn that OFF, restart Kodi after Fen reloads your profile, and see if that fixes the issue.

Nailed it!! That fixed it! Although it did hang Kodi after reloading profile. After a force stop, the widgets are working correctly again. THANK-YOU!!!

**Comment by JayDee696969** [comment]
Ok, now curious. What is language invoker for?

**Comment by JayDee696969** [comment]
> Ok, now curious. What is language invoker for?

Ok, I see it in the addon.xml Kodi Wiki. Kind of a speed booster I think.

**Comment by Tikipeter** [comment]
Big speed booster, but known to cause a whole range of issues at the moment unfortunately.
Fen now ships with it ON, but cases like yours it needs to be turned OFF because of your widget issue. Must be to do with how Xonfluence handles widgets by taking the uri directly from favorites like that. It seems most other skins don't have this issue.
