### ISSUE TITLE
Fen error after 3.2.04 release

### ISSUE THREAD

**Issue by Alex20090313** [Tikipeter/repository.tikipeter#315]
I have updated to the latest fen release and have followed the steps to add coco scrapers to fen but every time I try to load a movie or tv show I get fen error check change log and then my Apple TV freezes, hopefully the issue is in this log 

https://paste.kodi.tv/ahecukuqim

I also tried to clear all cache and I uninstalled fen and reinstalled with with the coco scrapers as external, I added back rd, all debrid and Trakt and I tried to search a movie again and it froze and gave me a fen error check change log again 

Here is the next log 

https://paste.kodi.tv/irezeracoh

**Comment by eengert** [comment]
I'm experiencing the same error on all of my Apple TV devices (total of 4).  No errors when I try Fen after updating on other devices such as a Mac computer or Nvidia Shield Pro.

**Comment by Tikipeter** [comment]
Ugh. Apple TV again.

Give me a minute...

**Comment by Madddcow** [comment]
I'm experiencing the same problem on my Nvidia Shield Pro running Kodi 20.2.  I downgraded to Fen v3.2.03 and all works well.

**Comment by Tikipeter** [comment]
Log or it didn't happen.

**Comment by fosgate85** [comment]
Hello guys 
Is there any way to roll back until fixed?
Thanks in advance

**Comment by Tikipeter** [comment]
Inetall and test latest version from test repo.

**Comment by Alex20090313** [comment]
I will only be able to test it around 10pm this evening, may you give me the test repo please

**Comment by Tikipeter** [comment]
Im on mobile so can't link.

It's in my test repo in this github.

**Comment by Alex20090313** [comment]
No worries I'll take a look, on mobile it works perfect, I had no issue with kodi on my 14 pro max with the add on will test it later tonight and send you feedback I may still have it on my Apple TV the test repo

**Comment by Alex20090313** [comment]
I don't seem to have the test url no more, when you have a chance may you please post it

**Comment by TwilightMercy** [comment]
https://github.com/Tikipeter/repository.tikipeter.test/blob/main/zips/repository.tikipeter.test/repository.tikipeter.test-1.0.3.zip

**Comment by Alex20090313** [comment]
Is that what I enter into kodi? Cuz I tried and it did not work

**Comment by SoulReaverFan** [comment]
> Is that what I enter into kodi? Cuz I tried and it did not work
> 
> I'm talking about this url but for the test
> 
> https://tikipeter.github.io

That doesn’t exist for the test repo. I think one of the only free cloud storage addons working for Kodi on the Apple TV as a source in the Kodi File Manager is the OneDrive addon. Correct me if I am wrong about that, but anyway you can download the zip [here](https://github.com/Tikipeter/repository.tikipeter.test/raw/main/zips/repository.tikipeter.test/repository.tikipeter.test-1.0.3.zip) and put it on your OneDrive using your phone if you want and then install from zip and choose OneDrive as the source and install.

Hope this helps.

**Comment by Alex20090313** [comment]
Perfect I'll try that but a url does exist I had it a while ago but removed it off of my apple tv

**Comment by eengert** [comment]
The test version works on my Apple TV now.  Thanks.

**Comment by Alex20090313** [comment]
Just tested the test file can confirm it works

**Comment by Tikipeter** [comment]
> ....a url does exist I had it a while ago but removed it off of my apple tv

There's never been a github.io url for the test repo.

**Comment by Alex20090313** [comment]
My bad I may be thinking of umbrella I had issues a while back and I think I had the test repo for that

**Comment by Tikipeter** [comment]
There's a kodi repo, there's just not a github.io url.

**Comment by Alex20090313** [comment]
Oh okay so I might have gotten mixed up my bad

**Comment by 15123073** [comment]
I don't really know how github works, but Fen...tells me re no external scrapers. I recently to configure & put in FEN in the top box ...tells me FEN Incompatible module. Tried each 1 on the list n none were compatible as per FEN...I love FEN n want to use it always but I noticed up there some1 say re cocoscrapers, but I've hunted FEN for nr 2 hrs now n can't find coco or any other external or internal scrapers...stuck now I can't use FEN.the release b4 worked...help please.thanks

**Comment by Omarscomin** [comment]
> I don't really know how github works, but Fen...tells me re no external scrapers. I recently to configure & put in FEN in the top box ...tells me FEN Incompatible module. Tried each 1 on the list n none were compatible as per FEN...I love FEN n want to use it always but I noticed up there some1 say re cocoscrapers, but I've hunted FEN for nr 2 hrs now n can't find coco or any other external or internal scrapers...stuck now I can't use FEN.the release b4 worked...help please.thanks 

You may want to familiarize yourself with GitHub if you plan to keep using Kodi, as this is where add on developers prefer to communicate and post important announcements. 

This Reddit post should get you back up and running:

https://www.reddit.com/r/Addons4Kodi/comments/1607smu/new_umbrella_and_fen_update/?utm_source=share&utm_medium=ios_app&utm_name=ioscss&utm_content=2&utm_term=1

**Comment by 15123073** [comment]
Thank you very much ... very kind of you! I appreciate any help!

Take care

Maddie


Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by 15123073** [comment]
Thank you. Appreciate you!

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by casedup** [comment]
i keep getting a can not connect to repo error

**Comment by SoulReaverFan** [comment]
> i keep getting a can not connect to repo error

You are probably running Kodi 19 Matrix which does support has ended for. Update to Kodi Nexus and it should work fine.
