### ISSUE TITLE
[Possible bug] Fen not marking resume points in library correctly after .19 update

### ISSUE THREAD

**Issue by mathu204** [Tikipeter/repository.tikipeter#315]
Thank you for the work you did! So picking up resume points now works great; however ive run into a new issue. I tested with episodes 1 and 2 of Archer that i integrated from library and what happens is; 1- I watch episode 1, using the player setting to play next episodes, and next uncategorized videos, it autoplays episode 2 next (i dont have autoplay in Fen enabled), after skipping halfway through and exiting. Episode 1 shows as watched and the resume point shows up in episode 2 only for a SPLIT second. After this it disappears and episode 1 is left as unwatched and so is 2, however if i click episode 2 in the library it resumes; normally if i resume again and exit (Before the resume library point update), it would then show up. 

So now, Fen does not mark single episodes as watched in library unless i watch it twice, and if i go to the next episode none of the episodes are marked as watched;nor the resume points. I can provide a log if needed but not sure if it would help let me know if i should

**Comment by mathu204** [comment]
Resume points do not set in singular episodes either now actually but still resume on clicking it

**Comment by Tikipeter** [comment]
I need a log to keep this issue open. ALL issues opened must now include a log.

**Comment by mathu204** [comment]
> I need a log to keep this issue open. ALL issues opened must now include a log.

I’ll post one tonight ; thanks for letting me know

**Comment by mathu204** [comment]
[Episode 1 resume in Fen but not mark in library, skipping to end of episode then exiting marks as watched but not when autoplaying next episode (through player settings autoplay next in Fen is not enabled).log](https://github.com/Tikipeter/repository.tikipeter/files/5578773/Episode.1.resume.in.Fen.but.not.mark.in.library.skipping.to.end.of.episode.then.exiting.marks.as.watched.but.not.when.autoplaying.next.episode.through.player.settings.autoplay.next.in.Fen.is.not.enabled.log)
[Autoplay episode 2 after finishing 1 does not mark 1 as watched nor resume point in 2, playing it in library does resume in Fen though.log](https://github.com/Tikipeter/repository.tikipeter/files/5578774/Autoplay.episode.2.after.finishing.1.does.not.mark.1.as.watched.nor.resume.point.in.2.playing.it.in.library.does.resume.in.Fen.though.log)

**Comment by Tikipeter** [comment]
Firstly, I've tested resume with both library movies and episodes, and it works for me for both correctly.
I definitely need clarification on what you have written in your original post:

>..using the player setting to play next episodes..

Which setting and from where?

>..and next uncategorized videos..

I don't know what this means.

> ..i dont have autoplay in Fen enabled..

You can't autoplay the next episode if you don't have autoplay enabled.

> ..however if i click episode 2 in the library it resumes..

That means Fen has both set the resume point AND is honoring it upon playback start.

You need to make sure if you back out of the window showing the episodes and navigate back into it that the correct watched markers and resume markers don't appear directly. Even in my confusion as to what you wrote above, it sounds more like a container refresh issue.
