### ISSUE TITLE
My accounts losing debrid account still

### ISSUE THREAD

**Issue by 99Maxwell99** [Tikipeter/repository.tikipeter#316]
I’m still randomly getting this issue on a fire tv 2 and once on a shield. The fire tv 2 loses the debrid setting a few times a week for no reason

**Comment by Tikipeter** [comment]
I need a log to keep this issue open. ALL issues opened must now include a log.

**Comment by 99Maxwell99** [comment]
I'm going to get the box now. I'll see if there's a log
