### ISSUE TITLE
Cloud Scraper for RD not working on my end

### ISSUE THREAD

**Issue by xyzfre** [Tikipeter/repository.tikipeter#318]
Noticed today The cloud scraper doesn't seem to pick up RD links in my cloud, it's working for AD and PM Was wondering if anyone is having the same issue,, using Omega,Windows 11 Pro,AH2

**Comment by les017** [comment]
All good here this morning


Thanks,
Evan

**Comment by xyzfre** [comment]
I went into tools and clean Database that seem to fix the issue on my end. My apologies I should've try to troubleshoot first.
