### ISSUE TITLE
Results only show up after the third try

### ISSUE THREAD

**Issue by eitchtee** [Tikipeter/repository.tikipeter#319]
EDITED: Please no mention of external scraper modules.

Any movie or TV Show I try to watch only shows results after exactly the third time clicking on it, before that it seems to scrap results correctly, but Real-debrid is shown with 0 results.

Log: https://paste.kodi.tv/axodibojed

Example: https://imgur.com/a/w4UkWMj

---

Not sure if related, but after doing the whole 3-tries thing and selecting a file from the results, playback gets stuck on the loading screen (see https://imgur.com/a/qTiYi3F)

Refreshing real-debrid's torrents page shows this screen
![image](https://github.com/Tikipeter/repository.tikipeter/assets/10510126/7601b375-8f4d-4ffb-a84d-ddcecf2af269)

After clicking **Start my torrent**, playback finally starts loading and after a while playing.

**Comment by Tikipeter** [comment]
Real debrid is timing out.

**Comment by eitchtee** [comment]
Yes, but is there any reason why?

Note that Stremio and Seren works fine with RD in the same computer and network.

**Comment by Tikipeter** [comment]
I'm afraid I don't have inside knowlesge as to the current status of RDs servers.

I'm sure they posted something on their X account a couple of days ago.

**Comment by Tikipeter** [comment]
As a general rule, following "hiccups" by RD like this, clear any unfinished torrent imports from your RD torrents page. Things should then return to normal usage in Fen.

Also make sure you don't have too many active torrents on that page.
