### ISSUE TITLE
Fen wont play tv shows straight from homepage

### ISSUE THREAD

**Issue by jaimsitecom** [Tikipeter/repository.tikipeter#320]
The latest update took away the function of playing tv shows straight from the kodi homepage. There wasnt any problem before this version 1820. Do i nneed to do any setting manipulation to enable this again?

Playing movies from the homepage works still tho. Only tv shows have the problem. 

Thanks!

Log:
https://mega.nz/file/5cBniSqJ#62zB-jDkw8NXqW68Ges_BQbjT3p06XS4SDjUr02ux9Q

**Comment by Tikipeter** [comment]
Do you mean "episodes". I made a widget for recently added and managed to play a .strm file using it from the homescreen.

You will have to go into more detail about your setup so I can replicate.

**Comment by jaimsitecom** [comment]
Yes Tikipeter. If i click on an episode from the homepage, it wont play straight anymore. Now it just does nothing if i click. I also have ‘subscriptions’ from Venom, and if i click the episode straight from the homepage, it plays. 

![9D46C3DA-2838-4D4C-AA40-4C470AA0A9D3](https://user-images.githubusercontent.com/58242813/100255866-066b9d00-2f7f-11eb-9288-3c89f595eb14.jpeg)

**Comment by jaimsitecom** [comment]
Just to add, i tried goin back one version down, 1819, this version also wont play episodes straight from homepage.

**Comment by Tikipeter** [comment]
It's working for me. I picked the same skin, and the same widget "Recently Added" as in your picture to play back from, and I got this:

![screenshot000](https://user-images.githubusercontent.com/28930002/100258083-bc90b000-2f9a-11eb-9ead-d2b657824a36.png)

which then played when I selected a source.

Does the episode play back from within Kodi's Library?

To troubleshoot, I would pick one show from subscription, delete all the .strm files for that one show, then run a subscription update and then attempt to play an episode from the show once Fen has remade the strm file.

Alternately, you could test playback of the strm file through Kodi's File Manager. Navigate to where the files are on your device through File Manager, and click on one of the strm files within. See if it plays back from there.

**Comment by jaimsitecom** [comment]
It wont play if i click on the episode from the homepage. But if i navigate thru the tv shows list inside kodi’s library, and pick a specific episode, it would play right. 

I will try deleting the .strm files and let it repopulate and will let you know how it went. 

Thanks a lot.

**Comment by jaimsitecom** [comment]
Well deleting and re-adding dis the trick. Thanks for the tip. Just a little hassle now to delete most of ths subscriptions and readding them. What caused this?

**Comment by jaimsitecom** [comment]
Thanks again Tikipeter for the help. You can close this topic now.

**Comment by Tikipeter** [comment]
I'm hoping you don't have to delete and re-add the subscriptions as library items in Kodi. They should still point to the same filepath as before, just the contents of the file (strm) is different. This means they should still play.

As for what happened, I'm not really sure, but the contents of the strm files obviously didn't have the correct url within them to play properly.

Glad it's sorted, and thanks for posting a log in your opening post.
