### ISSUE TITLE
Fen Update Crash

### ISSUE THREAD

**Issue by casedup** [Tikipeter/repository.tikipeter#320]
Hey guys, I have rpi4, librelec, kodi matrix... tried updating to the latest 1.0.3 repo but getting could not connect to repo error. When I try using 1.0.2 repo for some reason there is no Video Addons only Coco is there. Also tried installing the app directly version 3.2.05 immediately throws Fen error when installing and won't open. However when I install version 3.2.04 everything seems to work perfectly, I get the initial pop up about the changes but when I go into the app itself its the empty kodi screen with "..." file directory. Totally confused here. Had to do similar update for Umbrella and was perfect.

**Comment by Tikipeter** [comment]
Fen only works on Kodi Nexus.
