### ISSUE TITLE
[Request] Add "Hide" Option to Tv Show context menu in the In Progress TV Show

### ISSUE THREAD

**Issue by DevGeniusCode** [Tikipeter/repository.tikipeter#323]
Thanks for all the latest updates, they greatly improve charging and I enjoy using it every day.

I'd like to request the addition of a "Hide" option [see below Trakt API [1]] to the context menu for TV series in the "In Progress" list. Currently, this option is available for movies but not for TV series, know as "Clear Progress",  which allows users to remove a movie from the "In Progress" list if they don't intend to continue watching it.

The "Hide" option would serve a similar purpose but for TV series. When selected, it would remove the series from the "In Progress TV Show" list, indicating that the user no longer intends to continue watching it. This feature would streamline the management of TV series in the watchlist.

Currently, the only option available for TV series is to mark them as "Not Watched," which doesn't accurately reflect the user's intention, especially when they have already watched part of the series, and will not want to delete the viewing history.

Additional Information:
I discovered that the trakt.tv website offers a "Hide" option for TV series, and there is an API available to activate this functionality externally.
I made sure that there was a connection between the things, after I hid a series on the Trakt website, and it did disappear from the In Progress list.

![image](https://github.com/Tikipeter/repository.tikipeter/assets/136935333/bd0da11e-4df2-4f13-9490-cfe3830e9c84)

[1] Link to API documentation:
https://trakt.docs.apiary.io/#reference/users/add-hidden-items/add-hidden-items

![image](https://github.com/Tikipeter/repository.tikipeter/assets/136935333/48b867d2-061e-48ef-80c6-7afb8141595a)

**Comment by ivarbrandt** [comment]
This feature is already available in Fen.

Tools > TV Show Progress Manager.

Then click a show to hide/unhide it from progress.

**Comment by DevGeniusCode** [comment]
> This feature is already available in Fen.
> 
> Tools > TV Show Progress Manager.
> 
> Then click a show to hide/unhide it from progress.

Thank you for your response and for pointing out the existing "TV Show Progress Manager" feature in FEN. I appreciate that this functionality is already available.

However, if it's possible, I would be delighted to see the "Hide" option for TV series added to the context menu in a similar way to movies. Having this option readily accessible from the options menu, alongside other actions, would enhance the user experience and provide a more convenient and consistent way to manage both movies and TV series.

I believe this addition would further improve the usability of FEN for users who enjoy organizing their watchlist efficiently. If this feature enhancement aligns with the project's direction, I hope it can be considered for implementation in a future update.
