### ISSUE TITLE
(question) Sorting order premium accounts. 

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#323]
Maybey I am overlooking it, but I can't find a way to sort the premium accounts sorting order.
I have premiumize and Realdebrid, and want to change the order, so that I can see premiumize first at the results. 
Before I changed that in the ResolveUrl, but Fen is resolving links within the Addon now (if that is correct English). 

Am I overlooking this maybey?

Thx, and greetings, tinuz.

**Comment by Tikipeter** [comment]
I'll need to add a "Priority" setting like ResolveURL used to have. Can you translate "Priority" for me and I'll add them in next update.

**Comment by Tinuz97** [comment]
Prioriteit in Dutch language (priority)

**Comment by Tikipeter** [comment]
Sorry Tinuz, but since I'll do the same type of setting as ResolveURL used to have, can you translate this too: "Lower Number Equals Higher Priority". Thanks mate. 👍

**Comment by Tinuz97** [comment]
Lower Number Equals Higher Priority:

Een Lager Getal Is Gelijk Aan Een Hogere Prioriteit

**Comment by Tikipeter** [comment]
This is done for next update.
