### ISSUE TITLE
Library files 

### ISSUE THREAD

**Issue by ricinga666** [Tikipeter/repository.tikipeter#324]
Hi Peter,  there definitely seems to be a bug in the add to library function.

I had new episodes get added but when I click on them nothing happens.

So I removed one of the shows and readded it to the library.  This time it updated no problem.   So I thought if I remove all shows and add them back enmasse I would be good to go.  

Nope all shows are back to doing nothing when clicked again.

I'm struggling to get logs off of my firestick at the minute since I updated my phone to android 11.  But here is a couple of photos one showing the strm file after the batch update and one when I add and remove it one at a time.  

![PXL_20201130_211356768.jpg](https://user-images.githubusercontent.com/58446154/100667355-51582c80-3352-11eb-896d-5e9218b7a009.jpg)![PXL_20201130_211908498.jpg](https://user-images.githubusercontent.com/58446154/100667370-54531d00-3352-11eb-9162-21982be91ef9.jpg)

**Comment by ricinga666** [comment]
I think I've managed to sort them. Not sure what you'll find as I've been playing around for a bit trying to see if I could get it sorted.

[kodi.old.log](https://github.com/Tikipeter/repository.tikipeter/files/5618879/kodi.old.log)
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/5618881/kodi.log)

**Comment by Tikipeter** [comment]
Hold tight because I'm currently coding Fen to use it's own window for source results. It's a lot of work but it should see any playback issues dissapear.
