### ISSUE TITLE
[Request] Stop option instead of Cancel for Next Up

### ISSUE THREAD

**Issue by Jcloak** [Tikipeter/repository.tikipeter#325]
Currently the Next Up window gives 3 options: Play, Close, Cancel

I would like to request for "Cancel" to be replaced with "Stop" or to give an option to choose between "Cancel" or "Stop" in the settings.

**Comment by Tikipeter** [comment]
Why?

**Comment by Jcloak** [comment]
Because when I'm done watching something I just want to Stop with 1 click instead of doing "Cancel" and then bring up OSD and then navigate to the stop button. It is a big process with a TV remote.

**Comment by les017** [comment]
I was curious why as well. Now I understand due to the TV remote. Yet I'd think CANCEL and then skip-to-end should work. 

If I had a vote, I'd vote against CANCEL being hard replaced with STOP.  Stopping early could leave episodes in-progress, especially for Trakt users.

**Comment by Jcloak** [comment]
That is why I also suggested maybe an option to let users choose between "Cancel" or "Stop"

Maybe "Show Stop button instead of Close" would be a better setting though. I believe that's how the Up Next addon implements it.

**Comment by Tikipeter** [comment]
I don't agree it is a "big process" with a TV remote.

That's how I do it currently.
