### ISSUE TITLE
Easynews no search results found 

### ISSUE THREAD

**Issue by Ad10025490** [Tikipeter/repository.tikipeter#326]
Hi all,
This is my log info 
http://paste.kodi.tv/buxopavavo

I just subscribed to EasyNews. Entered my information in  account, everything seems ok
But no search result from easynews. I tried many  popular movies but zero found

I have tried from setting to but version 3.0 and 2.0 same. No search results found 

Any suggestions

**Comment by Tikipeter** [comment]
No suggestions really. It's working for everyone else atm. There seemed to be some "downtime" with easynews the last couple of days, but i was getting results earlier.

I'd try Shadow or Gaia addons and see if you get results and report back here. Venom will also show Easynews results through Fenomscrapers if you have entered your info.

Also, triple check you have the correct credentials entered in the My Accounts addon, and that they have successfully synced into Fen.

**Comment by Ad10025490** [comment]
I did all steps as should be and still not getting anything, i tried to disabled RD and PM and allow only easynews but same, no results found, and its active from my service, everything seems Ok. Tried shadow and venom same result.

Maybe easynews black Friday  disabled that code to work with tj kodi, i dont know man
https://signup.easynews.com/black-friday-exclusive-special-2020/

**Comment by Ad10025490** [comment]
I just record this
https://youtu.be/PgomKuTJYO0

**Comment by Tikipeter** [comment]
It's not that.

I think they are just having issues. My Easynews results are either timing out or not coming through at the moment. This is quite rare, but I think you need to just monitor it for a few days and see if it comes good. This has been happening on and off for a few days now.

**Comment by Ad10025490** [comment]
Will do
Thanks 👍

**Comment by omen124** [comment]
When I was testing regarding 3.0 and 2.0, I found the most frequent cause (if the service was working fine, which is checkable via the website) was that I would either mistype my password username and not include capitalisation.
