### ISSUE TITLE
Information for Next Update (v.1.8.21)

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/repository.tikipeter#327]
The next update for Fen will be REMOVING features rather than adding them (just like the previous update). If you do not want these features removed, please turn OFF Auto Updates and stay with the version of Fen you are happy with. Below is a list of settings (and subsequently the feature associated with that setting) that will be removed next update:
```
- Removed Random Play.
- Removed action choice when selecting Movie/TV Show.
- Removed Parental Controls check before playback. You can still check the Parental Controls ratings in the Extras menu before playback, but the autocheck is removed.
- Removed setting to show/hide Furk uncached items in results. Uncached items will not be shown.
- Removed check if Furk result is currently downloading.
- Removed Max. Results setting for Furk and Easynews.
- Removed Minimal Notifications setting when using autoplay.
```
I may add to this list before the update. Check back here to see.

Along with this there is a new feature for Fen; it will be incorporating it's own window to display results. This has been coming for a while, as it simplifies playback commands. 
Below is an image of the new window. It is nothing fancy, but will make coding easier going forward. The highlight changes color to match the scraper type color. It will be possible to choose different window styles in the future, so you can request certain things (be mindful my skinning skills are limited). Certain notifications in Fen will soon have their own dialogs also.

![screenshot000](https://user-images.githubusercontent.com/28930002/100931997-5928f400-353f-11eb-93cc-cd7bbdd6c12f.png)

**Comment by Tinuz97** [comment]
Wow, that results screen!
Love it!
![images](https://user-images.githubusercontent.com/47715606/100932983-f575db00-34ec-11eb-8319-cf27a14300f7.jpeg)

**Comment by Tinuz97** [comment]
This wil solve the 'aeon nox silvo mod skin' limitation, that is the only annoying thing on aeon nox, the HUGE font, so is does not fit on the screen. (but for the rest I love aeon nox silvo mod skin).

Like this :
![Screenshot_20201202-222914](https://user-images.githubusercontent.com/47715606/100933586-db88c800-34ed-11eb-8ba8-044cb2df3693.jpg)

**Comment by Tikipeter** [comment]
It will, yeah. Plus it displays A LOT FASTER, because we don't have to pass the list items to Kodi to make. We can make them ourselves. The results show almost instantaneously, regardless of how many items there are.

**Comment by Tinuz97** [comment]
So you have a idea how it works/looks in Aeon nox silvo mod skin. 

![tenor](https://user-images.githubusercontent.com/47715606/101073957-7d68ed00-35a0-11eb-9653-9a65eaa2db66.gif)



![Screenshot_20201203-194254](https://user-images.githubusercontent.com/47715606/101073691-206d3700-35a0-11eb-94e4-13a3b6546e8b.jpg)

**Comment by Tinuz97** [comment]
Only weird thing I noticed, that i if I click a movie (link in the results after scraping) does not seems to work with touchscreen on my phone.

If I long press the link, I get the download option (that does work fine, I get the pop-up if I am realy sure if I want to download it, with filename and how big the file etc is). 

Is this jus me, or has it something to do with Aeon nox silvo mod skin maybey?
Can you try a touchscreen maybey (phone, tablet or something).

**Comment by Tikipeter** [comment]
It will be to do with the touch aspect of it. I'll have to see if that registers a different action to selecting generally.

**Comment by Tikipeter** [comment]
I'll push a hopeful fix for this in a minute.
Let me know if it solves the problem.

**Comment by Tinuz97** [comment]
Working 200% with the fix on the phone now with touchscreen 💯🎉👌

**Comment by Tikipeter** [comment]
Awesome. 👍
