### ISSUE TITLE
[Possible Bug] Fen not marking single episode progress in Library.

### ISSUE THREAD

**Issue by mathu204** [Tikipeter/repository.tikipeter#328]
Hey TikiPeter, once again thank you for the great work on FEN it's as fast as it's ever been to the point I don't even need shadow anymore (which is a great addon no hate), anyways Im somewhat continuing off this issue here https://github.com/Tikipeter/repository.tikipeter/issues/315

So to answer your question in that, and how i fixed the problem of when I went to the next episode first one wouldnt be marked as watched, and next ones progress wouldn't be set. The setting I had was in Kodi Settings - Player Settings - Videos - Play next video automatically. I had to disable auto next episode in Fen, and set it up here to make the next episode play BEFORE you fixed the whole problem. My mistake was not turning this off and then using Fens in built autonext which now works with your fix. 

I know currently face a new issue I just tested watching Ep 1 of Seinfeld, going to 2 and quitting halfway and the first episode is marked watched, and the progress for 2 is set! Great. However, I cannot get progress to be STAY set for watching a single episode (just quitting halfway through Fen). So right when I back out it shows the correct resume, if i press back it loses that. It still says resume but at 0%, it does resume correctly on playback so this is just a small nitpick that kinda annoys me lol. (This is from the main widget view)

Upon further testing if i actually go into the addon season view and play it there and back out it shows the correct progress for a split second then goes away. I know you mentioned on that post about something of a container refresh issue, is that something on my end? Or the skin im using? (Titan Bingie Mod) Is there something I can do on my end to address this?

https://imgur.com/a/HKXQ4mj

[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/5637860/kodi.log)

**Comment by mathu204** [comment]
Upon exiting Kodi and coming back a few hours later my single episode progress is lost too, upon clicking it it doesnt even resume normally either.
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/5640008/kodi.log)

This is the log from playing an episode i had progress in earlier

**Comment by Tikipeter** [comment]
Subscriptions will be removed next update. My best suggestion is to use TMDBHelper moving forward.

**Comment by mathu204** [comment]
> Subscriptions will be removed next update. My best suggestion is to use TMDBHelper moving forward.

Okay, is there a reason you would mind explaining? And does that mean there is no hope for addressing any of these problems?

**Comment by mathu204** [comment]
Oh actually I was using tmdb helper for some of these shows, is this still an issue u won’t/can’t fix?
