### ISSUE TITLE
Sources don't stay when I back out. 

### ISSUE THREAD

**Issue by DoBucki** [Tikipeter/repository.tikipeter#329]
Used to be able to pick a source and if it didn't play I could just back out and pick a different one.  Now the sources don't stay and I have to rescrape.

**Comment by Tikipeter** [comment]
I know.

**Comment by DoBucki** [comment]
Did you do this for a purpose

**Comment by Tikipeter** [comment]
Not really. It just kinda had to happen.

**Comment by xyzfre** [comment]
On my end if I back out to pick a different link the re-scrape is blazing fast 2 seconds max love this new look you have done an amazing job with Fen thank you for all your hard work my friend
