### ISSUE TITLE
Search results missing VS Sonarr+Downloader

### ISSUE THREAD

**Issue by omen124** [Tikipeter/repository.tikipeter#331]
I have seen lately that I will get no results searching for an episode via FEN or the website, yet I will still be able to find a download when using NZBGet (with Easynews as a source) and Radarr (with DOGnab as an indexer) meaning that the file exists on the EasyNews server but is slightly difficult to find.

My question is: 
Can an indexer service for Usenet be implemented to improve the search results with FEN?

**Comment by Tikipeter** [comment]
No.
