### ISSUE TITLE
User interface improvements

### ISSUE THREAD

**Issue by omen124** [Tikipeter/repository.tikipeter#332]
After doing testing for the latest 3.0 issues and seeing the layout of other Kodi addons and their flexibility to be able to rearrange the menu, I would like to make some suggestions for improvements with FEN.
Firstly I love the colour scheme of the search results/to be released/etc. I do have some issues with the order of the menu.

There are way too many options and it makes it hard to find what I'm looking for.
The interface could use some folders such as TRAKT/IMDb integration options being grouped.
Being able to move frequently used options to the top via customisation or a favourites section would help.
Things like Genres, Networks, Years, etc can be in a subcategory folder for when people want to dive deeper via a particular type of search.
The search function needs to be more accessible rather than hidden towards the bottom as this is the more frequently used (alongside the popular/new releases) way to find something rather than browsing by categorisations.

My suggestion is to allow people to rearrange the menu the way they like and put stuff into folders. Otherwise, a bit of tidying up is needed to make it way more efficient.

**Comment by Tikipeter** [comment]
All of those things can currently be done in Fen by the user. No other addon has the level of menu customization as Fen.
Read the FenTips on editing menus. In fact, you should read all the Fen Tips. No good using an addon if you don't know how it works.
