### ISSUE TITLE
ANNOUNCEMENT: One more update to Fen.

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/repository.tikipeter#332]
There's a breaking little bug in the TV Show Years menu which makes it inoperable. Since the plan was to get Fen in a state where it was free from any obvious bugs and then retire it, I will do another update to fix this.

Bring on the pathetic little losers on addons4kodi saying I'm going back on my word again. You're the reason no addon devs post on reddit anymore.

**Comment by ivarbrandt** [comment]
Sweet! Thanks man!

I know this is off topic but I gotta ask, what is Fen Light? You tryna make it super light and nimble like FENtastic? 😉

**Comment by Tikipeter** [comment]
>super light and nimble like FENtastic?

It'll never get to that level. :)

>what is Fen Light?

In the past, every 6 months or so I've gone through Fen's settings and removed a bunch I didn't really want anymore. Just to help keep everything snappy. Invariably that would make some users unhappy.

This time, I really wanted to remove a lot of settings as well as some core functionality like Furk support, subtitles support, fanart.tv support, external scrapers' hoster support etc. I knew that would cause A LOT of issues for users, so I figured I would fork Fen and continue on with the fork.

Then users could keep using Fen as is and hopefully largely bug free, or try out Fen Light and see if it would do for them. It's possible only I will want to use Fen Light.

I've already removed about 30 settings and some functionality.

There's one big change that needs to happen (cutting Kodi out of handling addon settings entirely) and then I'll see how it runs.

May move away from Kodi handling updates to the addon as well.

I certainly can't release it right now, even though it is fully functional, mainly because of the changes still to do, which will definitely break any installs up until that point.

**Comment by ivarbrandt** [comment]
That makes perfect sense. Thanks for the explanation! And thank you for giving everyone a choice by leaving Fen up.

I have a neat little update to FENtastic in the works so I'll have it keep using Fen for now.

Btw, I will be reaching out to you soon about a feature I want to implement. This will likely be the last big thing I'll add to FENtastic as it's just about finished.

**Comment by JFG1000** [comment]
@Tikipeter thankyou for all your work on Fen as its by far my favourite addon, can I ask just ask something that I'm sure alot of us are also wondering, if something like trakt API changes etc, will you be willing to fix it with an update so we can continue to use it going forward? I really want to continue using fen going forward if possible

Many thanks again

**Comment by Cloudman999** [comment]
Hi @Tikipeter 
I know this may sound a dumb question, but how do I actually install your Fen Light add-on?

I am trying to add the link to the repository in File Manager in Kodi, but can't seem to get it to work.

I am typing: https://github.com/Tikipeter/repository.tikipeter.test

Can you tell me if that is correct?

Kind regards
@Cloudman

**Comment by Polgara01** [comment]
I'll try to keep this brief.  I've had some pleasant communications with both you and ivarbrandt in the past, and I want to start by reiterating my comment that Fen, in my opinion, is by far the most elegant Kodi addon created to date.  As a developer, both professionally and as a hobbiest, I also understand that projects can become bloated and unwieldy to maintain.  I appreciate that you both want to keep things light and quick.

It's always a challenge to take features away from a program/product.  We witnessed this with the recent update to Fentastic and the reaction to the removal of themes.   I developed and maintain an addon for a popular game and I've always made it clear that this is my personal addon which I choose to share.  I take some requests from time to time, but only if it is for something I want to use.  

I believe you are making the right decision in splitting off Fen Light, and that this is a kindness to users that they might not realize and appreciate.  You could have easily just gone ahead and removed functionality from Fen.  Instead, you chose to think about the community, and your users, and sunset Fen gracefully with full functionality.

> It's possible only I will want to use Fen Light.

I've installed Fen Light from the test repo.  I use RD, PM and EN and also use subtitles heavily.  Thus far, I am able to do 100% of what I do with with Fen using Fen Light.  

No, you won't be the only one using this new, improved, fast and lean version of Fen.

If you need some people to use/test/try-to-break Fen Light, I'm sure there are a bunch of us who can pitch in.

I'm also looking forward to ivarbrandt adding a toggle to Fentastic for Fen/Fen Light integration! 😉

**Comment by xyzfre** [comment]
@Tikipeter just for testing purposes is it OK to have both installed?

**Comment by No-Dot7369** [comment]
Thanks for all your hard work Tikipeter, Fen is an exceptional addon and is always first on my list, looking forward to Fen light

**Comment by rmdcf1967** [comment]
Tikipeter, I must thanks for the Best ever addon ive used in kodi for years. I do want to help and try the fen Light. Can anyone provide the path for the test repository to put on kodi file Manager, please?

**Comment by Tikipeter** [comment]
>...if something like trakt API changes etc, will you be willing to fix it with an update so we can continue to use it going forward?

Likely yes. I more meant development of Fen will finish.

>...how do I actually install your Fen Light add-on?

You have to download the zip file from here and install from that like normal.

>...I will be reaching out to you soon about a feature I want to implement

Can't wait. :) Love seeing what's coming next.

>..If you need some people to use/test/try-to-break Fen Light, I'm sure there are a bunch of us who can pitch in.

I appreciate the offer. Maybe once some "breaking" features are added. I don't want people having to put their settings in over and over. I'll have to do that bit. And I appreciate the kind words. :)

>just for testing purposes is it OK to have both installed?

Yes, they will not interfere with each other. But be aware Fen Light will break at least twice in the near future.

>Can anyone provide the path for the test repository to put on kodi file Manager

There is no path for the file manager. I think Github only allows you one such io address to use. I could well be wrong though.

**Comment by Cloudman999** [comment]
Hi @Tikipeter 
Thank you for responding to my question about the File manager path.

It would be great if Github allows more than one io address, as installing your Fen add-on was so simple.

I've tried downloading the Fen Light .zip file, but Kodi can't seem to find it in the download folder on my Chromecast with Google TV...

**Comment by SoulReaverFan** [comment]
> I've tried downloading the Fen Light .zip file, but Kodi can't seem to find it in the download folder on my Chromecast with Google TV...

Don’t forget to download the test repository zip file and install from there to get updates and not just the Fen Light plugin zip file.

To fix your issue with finding the zip file try this:

Inside the android settings on Google TV > apps > app permissions > files and media > Kodi > allow all the time. That should make the zip files appear now when browsing to their location on local storage.

**Comment by tundrablasen** [comment]
> > super light and nimble like FENtastic?
> 
> It'll never get to that level. :)
> 
> > what is Fen Light?
> 
> In the past, every 6 months or so I've gone through Fen's settings and removed a bunch I didn't really want anymore. Just to help keep everything snappy. Invariably that would make some users unhappy.
> 
> This time, I really wanted to remove a lot of settings as well as some core functionality like Furk support, subtitles support, fanart.tv support, external scrapers' hoster support etc. I knew that would cause A LOT of issues for users, so I figured I would fork Fen and continue on with the fork.
> 
> Then users could keep using Fen as is and hopefully largely bug free, or try out Fen Light and see if it would do for them. It's possible only I will want to use Fen Light.
> 
> I've already removed about 30 settings and some functionality.
> 
> There's one big change that needs to happen (cutting Kodi out of handling addon settings entirely) and then I'll see how it runs.
> 
> May move away from Kodi handling updates to the addon as well.
> 
> I certainly can't release it right now, even though it is fully functional, mainly because of the changes still to do, which will definitely break any installs up until that point.

this sounds super promising. Cant wait to try it out. will wait until you push it to the normal repo. i trust you. 

> Hi @Tikipeter Thank you for responding to my question about the File manager path.
> 
> It would be great if Github allows more than one io address, as installing your Fen add-on was so simple.
> 
> I've tried downloading the Fen Light .zip file, but Kodi can't seem to find it in the download folder on my Chromecast with Google TV...

you need to go to the kodi app settings on android tv and make kodi able to see all files. then the zip appears within kodi. had the same issue on shield tv

**Comment by Cloudman999** [comment]
Thank you for the tips @tundrablasen, and can now see the downloaded .zip files from within Kodi. However when I try to install from within Kodi using...

Addons > Install from zip file> download

Clicking on either of these files

plugin.video.fenlight-1.0.02.zip
repository.tikipeter.test-1.0.3.zip

... just causes Kodi to close

Any ideas?

@Cloudman999

**Comment by tundrablasen** [comment]
> Thank you for the tips @tundrablasen, and can now see the downloaded .zip files from within Kodi using the following...
> 
> Inside the android settings on Google TV > apps > app permissions > files and media > Kodi > allow all the time. That made the zip files appear now when browsing to their location on local storage.
> 
> However when I try to install from within Kodi using...
> 
> Addons > Install from zip file> download
> 
> Clicking on either of these files
> 
> plugin.video.fenlight-1.0.02.zip repository.tikipeter.test-1.0.3.zip
> 
> ... just causes Kodi to close
> 
> Any ideas?
> 
> @Cloudman999

Did you allow zip install (unknown sources) within Kodi settings? It’s somewhere there

**Comment by Cloudman999** [comment]
> > Thank you for the tips @tundrablasen, and can now see the downloaded .zip files from within Kodi using the following...
> > Inside the android settings on Google TV > apps > app permissions > files and media > Kodi > allow all the time. That made the zip files appear now when browsing to their location on local storage.
> > However when I try to install from within Kodi using...
> > Addons > Install from zip file> download
> > Clicking on either of these files
> > plugin.video.fenlight-1.0.02.zip repository.tikipeter.test-1.0.3.zip
> > ... just causes Kodi to close
> > Any ideas?
> > @Cloudman999
> 
> Did you allow zip install (unknown sources) within Kodi settings? It’s somewhere there

Yes @tundrablasen I did this

**Comment by DaleAlan** [comment]
Just a quick thank you for all the work you do @Tikipeter its hugely appreciated. Downloaded the fenlight just to have a play and it’s working nigh on flawlessly especially seeing as it’s not the official release and is a WiP. So much more concise settings and the only couple of things I’ll miss are purely aesthetic like the ability to disable the high contrast results and being able to select the tmdb image quality so more than worth it for the increased ease of use. Think the only thing I’ve spotted is there might be a very slight bug in the results if you’re going back into the scraper for something which you’d already started watching the “start over” button has no text and is just a blank (the resume button is fine) but that may be down to my skin setting.  Right back to my old faithful Fen the OG. Once again huge thanks you’re a superstar.

**Comment by meesterexx** [comment]
@Tikipeter Just tried FenLight here, and so far so good. Haven't missed anything you've removed yet. Thank you once again for all your hard work and continuous innovation, and looking forward to an even lighter, faster version of Fen moving forward!

**Comment by CircaOwl** [comment]
> > > Thank you for the tips @tundrablasen, and can now see the downloaded .zip files from within Kodi using the following...
> > > Inside the android settings on Google TV > apps > app permissions > files and media > Kodi > allow all the time. That made the zip files appear now when browsing to their location on local storage.
> > > However when I try to install from within Kodi using...
> > > Addons > Install from zip file> download
> > > Clicking on either of these files
> > > plugin.video.fenlight-1.0.02.zip repository.tikipeter.test-1.0.3.zip
> > > ... just causes Kodi to close
> > > Any ideas?
> > > @Cloudman999
> > 
> > 
> > Did you allow zip install (unknown sources) within Kodi settings? It’s somewhere there
> 
> Yes @tundrablasen I did this, but Kodi just closes itself if I click on either of the downloaded .zips. I'm just stumped what to do!
> 
> @Cloudman999

I am getting the exact same issue. You are not alone.

**Comment by xyzfre** [comment]
> > > > Thank you for the tips @tundrablasen, and can now see the downloaded .zip files from within Kodi using the following...
> 
> > > > Inside the android settings on Google TV > apps > app permissions > files and media > Kodi > allow all the time. That made the zip files appear now when browsing to their location on local storage.
> 
> > > > However when I try to install from within Kodi using...
> 
> > > > Addons > Install from zip file> download
> 
> > > > Clicking on either of these files
> 
> > > > plugin.video.fenlight-1.0.02.zip repository.tikipeter.test-1.0.3.zip
> 
> > > > ... just causes Kodi to close
> 
> > > > Any ideas?
> 
> > > > @Cloudman999
> 
> > > 
> 
> > > 
> 
> > > Did you allow zip install (unknown sources) within Kodi settings? It’s somewhere there
> 
> > 
> 
> > Yes @tundrablasen I did this, but Kodi just closes itself if I click on either of the downloaded .zips. I'm just stumped what to do!
> 
> > 
> 
> > @Cloudman999
> 
> 
> 
> I am getting the exact same issue. You are not alone.

After downloading the zip file did you extract the file afterwards

**Comment by TwilightMercy** [comment]
Hello Tikipeter,

I wish you good luck with your new lighter Fen adventure, I will be onboard to follow everything you do. 
For my “Twil(L)ight” (pun intended) fork - I will update it to your latest version 3.2.10 and run with it for a good while until things will be clearer with Fen light, to see what your next plans with your amazing addon. 


> There's one big change that needs to happen (cutting Kodi out of handling addon settings entirely) and then I'll see how it runs.
> 
> May move away from Kodi handling updates to the addon as well.

Can you detail on these statements a bit? They are interesting but I couldn’t understand what do you mean by cutting Kodi out of handling addon settings/updates :)

**Comment by Cloudman999** [comment]
I cannot unzip the file, nor get it to install from within Kodi. Wish it was in its own repository like Fen is. Can this be possible @Tikipeter ?

**Comment by No-Dot7369** [comment]
It is in its own repository I downloaded  1.0. 3 test repository on my laptop, then sent it to my shield then went to install zip found the zip install from the repository then video and fen light.

**Comment by tundrablasen** [comment]
> I cannot unzip the file, nor get it to install from within Kodi. Wish it was in its own repository like Fen is. Can this be possible @Tikipeter ?

it is exactly the same. just make sure you have the latest 1.0.3 test repository zip installed

**Comment by Cloudman999** [comment]
@tundrablasen 

Well that is the problem - I have downloaded the repository.tikipeter.test-1.0.3.zip

It is sitting in my Download folder on my Chromecast with Google TV.

I have uninstalled Fen add-on in Kodi (in case the Fen Light add-on doesn't like it being installed).

I closed Kodi

I then Open Kodi
Access Addons
Install from zip
Select repository.tikipeter.test-1.0.3.zip (from the Download folder)

... and Kodi just closes

If anyone here has a Chromecast with Google TV (CGTV device) and can install this Fen Light version, please type the EXACT steps they did to install it, please!

I am using Kodi 20.2 on this device.

Thank you - it is driving me nuts!

**Comment by tundrablasen** [comment]
> CGTV device

yes sounds like a CGTV device related issue. on my shield tv no problem

**Comment by Cloudman999** [comment]
@tundrablasen 
Thank you for your support. I appreciate it.

Fen has been my go to add-on forever, and I have always tried to provide helpful feedback to @Tikipeter on anything that wasn't working.

@Tikipeter has been amazing at helping me fix any reported issues.

I just feel so stupid that I cannot get Fen Light installed on my CGTV device.

Surely others here on Github use this device - can they get Fen Light working??

@Tikipeter do you have any help you can provide, please?

@Cloudman999

**Comment by SoulReaverFan** [comment]
@Cloudman999 

A debuglog would be helpful as this is not normal behavior for Kodi to crash/close in this case.

**Comment by No-Dot7369** [comment]
@Cloudman999I know this is a last-effort thing but maybe back up your current kodi then do a fresh start then install the kodi test repository set it up and then restore your backup?

**Comment by Tikipeter** [comment]
I bought a Chromecast the other day and installed the test repo and then Fen Light onto it as others have laid out here.

No-Dot7369 is correct, you will need to post a log file if it's not working. That should give a good clue as to why.

**Comment by Cloudman999** [comment]
Thanks for the help and suggestions @tundrablasen @Tikipeter @ivarbrandt @No-Dot7369 

Unfortunately, I can't try anything for the next 5 days, as my setup will be unavailable. We are having repairs and flooring fitted to our property, so no internet or TV or CGTV will be connected.

I do appreciate the helpful suggestions, and will report back when I can next get to try these out.

Cheers,

@Cloudman999

**Comment by derrgoo** [comment]
> @Cloudman999 
> 
> 
> 
> Two other things you could try:
> 
> 
> 
> 1. Move the zips to another folder, preferably a custom one. Then try to install from there.
> 
> 2. Download the zip of the earliest version of the test repo (`1.0.0`). If it installs then you can check for updates to update it to `1.0.3`.
> 
> 
> 
> [repository.tikipeter.test-1.0.0.zip](https://github.com/Tikipeter/repository.tikipeter/files/12831154/repository.tikipeter.test-1.0.0.zip)

#1 works but would like to get repo so it updates when a new version is out. Does anyone have the link to new test repo?

**Comment by Cloudman999** [comment]
> I bought a Chromecast the other day and installed the test repo and then Fen Light onto it as others have laid out here.
> 
> No-Dot7369 is correct, you will need to post a log file if it's not working. That should give a good clue as to why.

Thanks @Tikipeter for your reply. I don't have access to my CGTV device for about 5 days ( see my other comments as to why).

Will get back to you once I am back online.

Cheers
@Cloudman999

**Comment by rmdcf1967** [comment]
Im o a Nvidia Shield pro 19 and on a fresh instala of kodinerds 21. Successfulky on instslling both the test repo and fenlight. Im wirh Artic Fuse skin, where all wigmdgets are from Fenlight. Only issue is that in some cases the ckearlogis arent avsiabke from Tmdb(I guss). Besudes this issue everything gies smoothly. One requer could Popular People be avsiable to make widget from it(even with Shortcut Manager i create the widget but inside of it o must open the folder of popular People)?
Gkad to be of assisti. Many thanks Tikipeter

**Comment by ivarbrandt** [comment]
> > @Cloudman999
> > Two other things you could try:
> > 
> > 1. Move the zips to another folder, preferably a custom one. Then try to install from there.
> > 2. Download the zip of the earliest version of the test repo (`1.0.0`). If it installs then you can check for updates to update it to `1.0.3`.
> > 
> > [repository.tikipeter.test-1.0.0.zip](https://github.com/Tikipeter/repository.tikipeter/files/12831154/repository.tikipeter.test-1.0.0.zip)
> 
> #1 works but would like to get repo so it updates when a new version is out. Does anyone have the link to new test repo?

The zip for the repo is attached. After it installs check for updates and it'll update to the latest version of the test repo.

**Comment by derrgoo** [comment]
> The zip for the repo is attached. After it installs check for updates and it'll update to the latest version of the test repo.

I installed the 1.0.0 but it won't update to 1.0.3 just says "no update available"

**Comment by les017** [comment]
> > The zip for the repo is attached. After it installs check for updates and it'll update to the latest version of the test repo.
> 
> I installed the 1.0.0 but it won't update to 1.0.3 just says "no update available"

Same here

**Comment by Cloudman999** [comment]
Hi @Tikipeter @SoulReaverFan @tundrablasen 

I have finally been able to install Fen Light on my Chromecast with Google TV (CGTV).

Note: Kodi 20.2 is installed

Here are the exact steps I took.

1. Open Kodi
2. Access the Cog
3. Select: System > Add-ons > Unknown addons (enable)
4. Update official addons from (any repository)
5. Inside the android settings on Google TV > apps > app permissions > files and media > Kodi > allow all the time. That makes the zip files appear now when browsing to their location on local storage.

6. On my smart phone I downloaded the file repository.tikipeter.test-1.0.3.zip 

Using the android app "Send files to"

7. Sent the file repository.tikipeter.test-1.0.3.zip to my CGTV

8. On my CGTV Opened Kodi
9. Accessed the Cog
10. Addons > Install from zip > External storage > Downloads > repository.tikipeter.test-1.0.3.zip 
11. Addons > Install from repository > Tikipeter's Test Repository > Video Add-ons > Fen Light

It worked!

Cheers

@Cloudman999

**Comment by derrgoo** [comment]
> repository.tikipeter.test-1.0.3.zip

Can you post a link where to get repository.tikipeter.test-1.0.3.zip

**Comment by SoulReaverFan** [comment]
> > repository.tikipeter.test-1.0.3.zip
> 
> Can you post a link where to get repository.tikipeter.test-1.0.3.zip

[Here.](https://github.com/Tikipeter/repository.tikipeter.test/raw/main/zips/repository.tikipeter.test/repository.tikipeter.test-1.0.3.zip)

**Comment by derrgoo** [comment]
> > > repository.tikipeter.test-1.0.3.zip
> > 
> > 
> > Can you post a link where to get repository.tikipeter.test-1.0.3.zip
> 
> [Here.](https://github.com/Tikipeter/repository.tikipeter.test/raw/main/zips/repository.tikipeter.test/repository.tikipeter.test-1.0.3.zip)

Cheers @SoulReaverFan  I am sure many will benefit from this.

**Comment by Cloudman999** [comment]
> > > repository.tikipeter.test-1.0.3.zip
> > 
> > 
> > Can you post a link where to get repository.tikipeter.test-1.0.3.zip
> 
> [Here.](https://github.com/Tikipeter/repository.tikipeter.test/raw/main/zips/repository.tikipeter.test/repository.tikipeter.test-1.0.3.zip)

Thank you for posting the link to the Fen Light repository. I missed that step from my list of instructions @SoulReaverFan

**Comment by Cloudman999** [comment]
I hope you get it installed OK @derrgoo

**Comment by derrgoo** [comment]
> I hope you get it installed OK @derrgoo

Thanks all good now!

**Comment by Cloudman999** [comment]
https://github.com/Tikipeter/repository.tikipeter.test/raw/main/zips/repository.tikipeter.test/repository.tikipeter.test-1.0.3.zip

Is the place I installed the repository from

**Comment by Cloudman999** [comment]
Hi @Tikipeter 
Is it possible to open a place where we can add comments to anything we find out when testing Fen Light?
