### ISSUE TITLE
It Bugs me

### ISSUE THREAD

**Issue by MrC001** [Tikipeter/repository.tikipeter#333]
Thanks for all the years on this.  The only bug left is views are not remembered per skin anymore. if i change to a skin I set views to, It is back to the default views.  It did used to keep these didn't it?  You don't have to fix it.  Just thought that you used to be able to change skins then back and it would remember the set views per skin.

**Comment by MrC001** [comment]
Never mind iI found where they are kept in settings:
    <setting id="view.main" default="true">55</setting>
    <setting id="view.movies">57</setting>
    <setting id="view.tvshows" default="true">500</setting>
    <setting id="view.seasons" default="true">55</setting>
    <setting id="view.episodes" default="true">55</setting>
    <setting id="view.episodes_single" default="true">55</setting>
    <setting id="view.premium" default="true">55</setting>

I can write a little script to set them if/when skin is changed.  Ignore.

Thanks for everything on this and I see FEN light looks just fine to me as well. LONG LIVE FEN and the haters can suck my ****.

**Comment by Tikipeter** [comment]
Fen has never remembered views per skin.
