### ISSUE TITLE
Information For Next Update  (v.1.8.22)

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/repository.tikipeter#333]
After the last couple of updates, there will be less feature removal for the next. So far, only one iitem has been dealt with.

```
- Removed Library Integration (Fen Subscriptions). Please use another addon for library items moving forward.
- Removed Library Scraper.
- Removed Downloads Folder Scraper.
- Removed Kodi Library specific features.
```

More may be added here before next update.

**Comment by SJ50** [comment]
Any recommended  addon for library integration which can play via FEN?

**Comment by Tikipeter** [comment]
TMDbHelper

**Comment by ricinga666** [comment]
Oh man that was a great feature far superior to what tmdb helper has.  

Any chance you might bring it back in the future

**Comment by Tikipeter** [comment]
No idea. Post the player here and I'll have a look.

**Comment by ricinga666** [comment]
>

**Comment by ricinga666** [comment]
> No idea. Post the player here and I'll have a look.

Tinuz has uploaded it here.
 https://github.com/Tikipeter/repository.tikipeter/issues/336#issuecomment-739325076

Hope that helps.  

I'm currently getting loads of folder creation errors adding my list to the library in tmdb.  Currently pulling my hair out. Lol

**Comment by Tikipeter** [comment]
I dont use tmdbh, but there's a setting I'm sure to turn off folder check or something similar. Do that and it should fix the issue.

**Comment by ricinga666** [comment]
Yeah saw that, it stopped the error but not the actual problem with creating the files.😭

**Comment by Tikipeter** [comment]
Re: Fen player:
The player looks fine. There's some parameters that are not needed anymore, but the ones that are needed are correct. Switch the player action in TMBdH for Fen and that should sort it out.

You'll need to get a log capturing the failing creation of files.

**Comment by SJ50** [comment]
What is the reason behind all these feature removal?

I see that you are going to remove "Downloads Folder Scraper", please do not remove "Folder Scraper" FEN is the only addon which provides "Folder Scraper".

**Comment by Tikipeter** [comment]
"Folder Scraper" is staying definitely. I may add a couple more (6 and 7) because of the "download" and "kodi library" scraper removals.

The features removed are to help me moving forward in maintaining the addon.

**Comment by mathu204** [comment]
> "Folder Scraper" is definitely staying. I may add a couple more (6 and 7) because of the "download" and "kodi library" scraper removals.
> 
> The features removed are to help me moving forward in maintaining the addon. It's been a solid 2 years of only adding features. The addon is huge as a result, and I was beginning to notice changes to code occasionally would affect entirely different code. That should not really happen, as it then becomes a nightmare to maintain. Hopefully doing this will largely fix that situation.
> 
> Apart from "Library Integration", I don't think many people were using the things I've removed so far anyway, as a couple of things were broken and no one even noticed (myself included).

Yup i get that, sorry to bother by asking since I could care less about the different features that were removing, everything else I use this addon for is still here and the addon is working great as always. As someone else asked, do you think you would be open to adding subscriptions back anytime down the road or is it off the table moving forward?

**Comment by Tikipeter** [comment]
Off the table now. Anything removed won't be coming back in.

**Comment by mathu204** [comment]
> Off the table now. Anything removed won't be coming back in.

That is unfortunate, thank you for letting me know anyhow.

**Comment by Tikipeter** [comment]
I'll release v.1.8.21b in a second which should fix this issue.

Aside from that, you also have a malformed meta database that is meaning you are likely needing to call TVDb every time for season/episode info instead of the info being cached. To sort this out you will need to go into your `userdata/addon_data` folder, then `script.module.tikimeta` and delete the `metacache6.db` file. Restart Kodi and that should fix that as well.
