### ISSUE TITLE
Add the ability to modify which file extensions to scrape from sources

### ISSUE THREAD

**Issue by obfuscated-loop** [Tikipeter/repository.tikipeter#334]
Hello,

After looking at the code, I realise that there is a list of file extensions currently defined within the codebase, to my knowledge one pulling from the Kodi API and the other being custom for Fen (and various sources). While I think can edit this manually, I think the functionality to modify (whitelist/blacklist) certain extensions would be great. Currently, my sources seem to be inclined to use MKV results; with this suggested change, it would allow one to say _only_ scrape sources that return an MP4 extension.

I will look more into myself and try to understand the codebase a bit better in the meantime, but I think this would be an extremely useful feature.

EDIT: For a reason as to why I would personally use this feature is specific metadata that is integrated into the MPEG-4 container, and something you can not get from MKV and or other file formats. I also understand some people run into trouble using MKV on Kodi. 

Thanks for your hard work, I look forward to your response.

**Comment by obfuscated-loop** [comment]
After some reconnaissance, I think one way of achieving this would be modifying the `supported_video_extensions()` function within `source_utils.py` to check whether an extension is whitelisted/blacklisted, presumably checking `settings.xml`.

**Comment by ivarbrandt** [comment]
Did you see the pinned post where he said there won't be any more development of Fen?

https://github.com/Tikipeter/repository.tikipeter/issues/331#issue-1925130680

**Comment by obfuscated-loop** [comment]
> Did you see the pinned post where he said there won't be any more development of Fen?
> 
> [#331 (comment)](https://github.com/Tikipeter/repository.tikipeter/issues/331#issue-1925130680)

I did not! That's a shame! I might have to fork it then.

**Comment by obfuscated-loop** [comment]
I have started work on a fork here: https://github.com/obfuscated-loop/plugin.video.fenda - hoping to have a repo up by the end of next week.

**Comment by Tikipeter** [comment]
Take over Fen if you want..

**Comment by obfuscated-loop** [comment]
> Take over Fen if you want..

I really appreciate you saying such a thing, but I think it would be better for my own mental health if I keep it separate from your own project. I noticed the Addons4Kodi lot were giving you some problems (don't know the ins and outs of it) but I'd rather have them approach me and start issues rather than them piggyback on past stuff etc. I will make sure to keep you credited throughout though.

Hope you're doing well.

**Comment by obfuscated-loop** [comment]
One thing I will ask: do you know if there is anyway to use IDs instead of integers for the translations files (`strings.po`)?

Example: `usernamePlaceholder` instead of `32755`

Cheers.

**Comment by Tikipeter** [comment]
Integers only I'm afraid, unless there's another method apart from getlocalizedstring to access the translation files.

I don't think so though.

**Comment by obfuscated-loop** [comment]
That really sucks! Seems like a feature that should've been implemented into xbmc from the get-go. I might define my own custom dictionary then that has individual strings/IDs point to the specific integers. Thanks for the reply.
