### ISSUE TITLE
Need help adding feature to FENtastic

### ISSUE THREAD

**Issue by ivarbrandt** [Tikipeter/repository.tikipeter#335]
Hey man! Hope you're having a chill weekend.

The feature that I need help implementing is auto trailers. Before reaching out to you for help, I got as far as I can.

In the latest versions of the skin and helper in the test repo (`1.0.20h` and `0.6.17e`), I added a key to the ratings dictionary to store the trailer url extracted from the API response (I switched to MDbList instead of OMDb).

Then I added the checking of trailers in the service. The flow goes like this: window property > database > api. I also added some checks to make sure everything runs smoothly when starting and ending trailers. 

Even after all of this it is still pretty janky. Sometimes the trailers play other times they start and immediately stop. I don't know why this is happening as I implemented checks and wait times throughout the logic to prevent this.

Could you please take a look when you get a chance? I feel like I'm almost there. I've thought of moving the logic for the trailers somewhere else but I don't want to move it outside of the `listitem_monitor` function in the service. This may be what is necessary though as I'm experiencing weird behavior in the skin such as juddering during the scrolling of the plot when an item is focused.

Looking forward to your expert opinion :)

**Comment by Tikipeter** [comment]
Really hoping to have some time to look into this today or tomorrow buddy.

**Comment by Tikipeter** [comment]
Have you got an old copy of the helper?

From the first time extra ratings were supported?

**Comment by ivarbrandt** [comment]
Sure do. This is where I added IMDb Popular ratings.

[script.fentastic.helper-0.6.17d.zip](https://github.com/Tikipeter/repository.tikipeter/files/12851154/script.fentastic.helper-0.6.17d.zip)

**Comment by Tikipeter** [comment]
This will likely need a re-write...

**Comment by ivarbrandt** [comment]
Aww man. Which part?

**Comment by Tikipeter** [comment]
This is a crude attempt, but give it a go and see if it works for you. Some logging included.

Take what you need. :)

It feels fragile though.

Only `services.py` was changed, but Github doesn't allow a single file like that to be uploaded.

[script.fentastic.helper.zip](https://github.com/Tikipeter/repository.tikipeter/files/12873382/script.fentastic.helper.zip)

**Comment by ivarbrandt** [comment]
Awesome thank you!

Can't wait to take a peek 😄

**Comment by ivarbrandt** [comment]
I probably won't be able to check it out until the weekend but I'll be sure to let you know when I do.

**Comment by ivarbrandt** [comment]
Alrighty I've now had a chance to look at and test out the code. Firstly, thanks so much for your input!

Secondly, you're totally right. It is fragile. I ran into some of the same issues with your version as I did with mine. Sometimes the trailers would play. Other times they'd start for one second and then stop. Sometimes they would work correctly on my PC and not on my Shield. I tried many things like increasing/adding different wait times throughout different points in the logic, refactoring the logic with smaller helper methods, and separating the trailer logic into it's own class and running two services. None of it helped. Plus, for my version of the code it completely killed the speed when processing ratings. Your version didn't so that was cool :)

I was about to completely scrap the auto-trailers, then I sat back and thought: "How would this actually be used?" I came to the conclusion that the way I've been trying to implement this, even if successful, would be somewhat intrusive to the user experience. Imagine scrolling onto an item and reading the first sentence of the plot, then BOOM you're hit with the trailer lol. Or you're checking out the ratings and then BOOM, trailer. With this in mind, I decided to go another route instead.

Instead of autoplaying trailers, I've added the option for one-click trailers. Since the trailer is stored with the ratings as a window property, all I did was access the window property and then use that to play the trailer. This way, the user will be able to choose WHEN to play the trailer with one-click.

I think that this will be a better option, not to mention much more straightforward to code. I'm still working on the code to modify the keymap file. Right now it only works for a long press of the play/pause button on remotes. I'm going to make it work the same way on a computer with the press of the "t" key. I'll let you know when it's done and ready for testing so you can take it for a spin. 

Thanks again for all of your help!

**Comment by Omarscomin** [comment]
> Alrighty I've now had a chance to look at and test out the code. Firstly, thanks so much for your input!
> 
> Secondly, you're totally right. It is fragile. I ran into some of the same issues with your version as I did with mine. Sometimes the trailers would play. Other times they'd start for one second and then stop. Sometimes they would work correctly on my PC and not on my Shield. I tried many things like increasing/adding different wait times throughout different points in the logic, refactoring the logic with smaller helper methods, and separating the trailer logic into it's own class and running two services. None of it helped. Plus, for my version of the code it completely killed the speed when processing ratings. Your version didn't so that was cool :)
> 
> I was about to completely scrap the auto-trailers, then I sat back and thought: "How would this actually be used?" I came to the conclusion that the way I've been trying to implement this, even if successful, would be somewhat intrusive to the user experience. Imagine scrolling onto an item and reading the first sentence of the plot, then BOOM you're hit with the trailer. Or you're checking out the ratings and then BOOM, trailer. Or let's saying you're scrolling and you feel a sneeze coming on so you stop scrolling. By the time you sneeze, BOOM, the trailer would already be playing on some random item lol. With this in mind, I decided to go another route instead.
> 
> Instead of autoplaying trailers, I've added the option for one-click trailers. Since the trailer is stored with the ratings as a window property, all I did was access the window property and then use that to play the trailer. This way, the user will be able to choose WHEN to play the trailer with one-click.
> 
> I think that this will be a better option, not to mention much more straightforward to code. I'm still working on the code to modify the keymap file. Right now it only works for a long press of the play/pause button on remotes. I'm going to make it work the same way on a computer with the press of the "t" key. I'll let you know when it's done and ready for testing so you can take it for a spin. 
> 
> Thanks again for all of your help!
> 
> 

Sorry to butt in here, but I just wanted to say that I LOVE this idea! I was a little scared when I saw your original post/comments about the idea of implementing auto play for trailers, and deep down I was hoping that it was going to be an _optional_ feature for users. 

Love watching your brain work through the hiccups :)

**Comment by ivarbrandt** [comment]
> I just wanted to say that I LOVE this idea!

So glad to hear that! I didn't know how this would be received so your response is encouraging :)

> I was hoping that it was going to be an optional feature for users

It would have definitely been optional. Even the 1 click setup is going to be optional.

> Love watching your brain work through the hiccups

❤️

**Comment by ivarbrandt** [comment]
@Tikipeter 

The latest test versions of the skin and helper are now up.

Please test it out and lemme know how it works for you.

**Comment by Tikipeter** [comment]
I see that you're using mdblist now for all the ratings. They seem to give more info for TV Shows. Is it worth me switching to them do you think? Do they have any limits?

I had a look at the rating service code, and I wanted to let you know that this code is running constantly whilst staying on the same list item:
```
            if cached_ratings:
                result = json.loads(cached_ratings)
                for k, v in result.items():
                    set_property("fentastic.%s" % k, v)
                self.waitForAbort(0.2)
                continue
```
If you keep track of the last `imdb_id` processed for info, you could stop the code from a `json.loads` and assigning a whole bunch of `set_property` values every 0.2 seconds. Plus the code directly above it too.

Something to think about. :)

**Comment by ivarbrandt** [comment]
> They seem to give more info for TV Shows. Is it worth me switching to them do you think? Do they have any limits?

Yes, in my experience there's much more info such as Metacritic, and RottenTomatoes ratings for TV Shows. They don't have any ratings available on a per episode basis, but then again to get this with OMDb you'd need an extra API call every single time. The daily limit for the free tier is 1000 requests per day. I think that might be the same as OMDb.

> Something to think about. :)

Nice spot. I noticed it was spamming the logs whenever I was testing this because of the constant setting of properties but I couldn't think of a solution. I'll def try to implement this sometime soon. Thanks man! 😄
