### ISSUE TITLE
[Possible Bug] Fen error when playing library files (tmdb)

### ISSUE THREAD

**Issue by mathu204** [Tikipeter/repository.tikipeter#336]
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/5647499/kodi.log)

**Comment by mathu204** [comment]
I tried to play an episode of seinfeld that is a .strm for tmdb which sends to Fen automatically as my default player. So could be something to do with the player, or the library files which I know u said u wont really support library stuff moving forward so if it is, then so be it ill just downgrade bc this just happened after the 1.8.19a, or 18a was it update.

**Comment by Tikipeter** [comment]
If you post here TMDbHelper's Fen player I can see what the issue is. It likely needs re-writing.

**Comment by mathu204** [comment]
Its not letting me post the .json so ill just post the code

`{
    "priority": 100, 
    "play_episode": "plugin://plugin.video.fen/?mode=play_media&vid_type=episode&library=True&query={showname}&year={year}&season={season}&episode={episode}&ep_name={title}&tmdb_id={tmdb}&premiered={firstaired}", 
    "name": "Fen", 
    "plugin": "plugin.video.fen", 
    "is_resolvable": "true", 
    "play_movie": "plugin://plugin.video.fen/?mode=play_media&vid_type=movie&library=True&query={name}&year={year}&poster={poster}&title={title}&tmdb_id={id}"
}`

**Comment by Tinuz97** [comment]
[direct.fen.json.zip](https://github.com/Tikipeter/repository.tikipeter/files/5647550/direct.fen.json.zip)

**Comment by Tikipeter** [comment]
The player looks fine. There's some parameters that are not needed anymore, but the ones that are needed are correct. Switch the player action in TMBdH for Fen and that should sort it out.

**Comment by mathu204** [comment]
Sorry Im a noob where is that? &tmdb_id={tmdb} are u saying to change it to &fen_id={tmdb}, or tmdb_id={fen}?

**Comment by Tikipeter** [comment]
In the settings of TMDbHelper there should be an option to change the playback method TMDbH uses with it's players. Change that and see if it works.

**Comment by mathu204** [comment]
> In the settings of TMDbHelper there should be an option to change the playback method TMDbH uses with it's players. Change that and see if it works.

Oh Like from setresolved_url to Playmedia? I think that’s what you’re talking about let me know if I’m wrong, I will change this in the meantime and come back

**Comment by mathu204** [comment]
Changed from resolvedurl to playmedia still get an error, here is the log 
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/5648240/kodi.log)

**Comment by Tikipeter** [comment]
There's an issue with Fen with this one. I'll be able to fix it tomorrow.

**Comment by mathu204** [comment]
> There's an issue with Fen with this one. I'll be able to fix it tomorrow.

Dope you’re the best man thank you.

**Comment by Tikipeter** [comment]
The power of the log. ☺

**Comment by Tikipeter** [comment]
I'll release v.1.8.21b in a second which should fix this issue.

Aside from that, you also have a malformed meta database that is meaning you are likely needing to call TVDb every time for season/episode info (when navigating within Fen) instead of the info being cached. To sort this out you will need to go into your userdata/addon_data folder, then script.module.tikimeta and delete the metacache6.db file. Restart Kodi and that should fix that as well.

**Comment by mathu204** [comment]
> I'll release v.1.8.21b in a second which should fix this issue.
> 
> Aside from that, you also have a malformed meta database that is meaning you are likely needing to call TVDb every time for season/episode info (when navigating within Fen) instead of the info being cached. To sort this out you will need to go into your userdata/addon_data folder, then script.module.tikimeta and delete the metacache6.db file. Restart Kodi and that should fix that as well.

thank u i will do this and update and get back to u

**Comment by mathu204** [comment]
Now I get the scraping  dialog but it doesnt play ill add a log soon

**Comment by mathu204** [comment]
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/5649617/kodi.log)
