### ISSUE TITLE
[Feature Request] Ignore or Option to Ignore Quality for Cloud sources.

### ISSUE THREAD

**Issue by mathu204** [Tikipeter/repository.tikipeter#338]
Continuing from here, sorry I did not attach a log bc I did not think I would need one for a Feature Request as theres nothing in the log that would pertain to it but im just copy pasting a random log. 

"Trying to watch an episode of Jujutsu Kaisen and I have autoplay set to only 720 and 1080p, but for some reason my cloud files show up as SD even though theyre not. May be a naming error [on my end] or whatever but would you consider ignoring quality for cloud sources so they still autoplay regardless of quality as long as its a cloud file? Or maybe an option to enable this so it doesnt screw over other people who don't want it to work like that."

[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/5648213/kodi.log)

**Comment by Tikipeter** [comment]
I can add this for next update.

The requirement of a log with ALL Issues opened is an attempt to temper spamming of the issues section. I don't like having lots of issues open at the same time. It makes me anxious.

**Comment by mathu204** [comment]
> I can add this for next update.
> 
> The requirement of a log with ALL Issues opened is an attempt to temper spamming of the issues section. I don't like having lots of issues open at the same time. It makes me anxious.

Ah I see then I will do that moving forward I can understand. Thank you again :D

**Comment by Tikipeter** [comment]
No worries.

I didn't answer your question about why the quality was wrong. It all comes down to the name of the file. If 2160, 1080, 720 (or different variations of these) are not in the filename, then the default of SD will be assigned. The quality tag comes directly from inspecting the filename.

**Comment by Tikipeter** [comment]
This will be in the next update (v.1.8.22).
