### ISSUE TITLE
[Feature Request] (May already be done) Add Nyaa as source

### ISSUE THREAD

**Issue by mathu204** [Tikipeter/repository.tikipeter#339]
https://github.com/Tikipeter/repository.tikipeter/issues/334

(again, didnt think i needed a log for a feature request, attaching one now)

"I was trying to watch episodes of Jujustu Kaisen and on wako i get multiple sources for the same episode from Nyaa, but on Fen i only get like 2 from Lime. So is it possible to add Nyaa as a source for scraping if its not added already? In which case it may be a bug that its not showing up."

[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/5648214/kodi.log)

**Comment by Tikipeter** [comment]
This is one for Mr Kodi who maintains FenomScrapers which Fen and Venom use.

Only Furk, Easynews, Debrid Cloud and File Folder Scrapers are a part of Fen.
