### ISSUE TITLE
Is Fen Light now ok to use?

### ISSUE THREAD

**Issue by Cloudman999** [Tikipeter/repository.tikipeter#339]
Hi @Tikipeter 
In a previous comment you made about Fen Light, you mentioned it would break twice, if we were to use it before you officially released it.

My question is ...

Is it still OK to use the current version of Fen Light, and have you made the necessary changes yet so it will not break?

Thank you very much - hope you can answer my questions.

@Cloudman999

**Comment by Tikipeter** [comment]
Not really. I have plans for it to break at least once more. I just don't know if the plan is possible.

So I can't give any guarantees as of yet. It's possible it won't break again, and it's possible it will.

**Comment by Cloudman999** [comment]
> Not really. I have plans for it to break at least once more. I just don't know if the plan is possible.
> 
> So I can't give any guarantees as of yet. It's possible it won't break again, and it's possible it will.

Thank you for replying to my question about Fen Light, @Tikipeter .

I guess based on this, I should probably keep using Fen, until you have made the second change to Fen Light.

Cheers
@Cloudman999

**Comment by TwilightMercy** [comment]
@Cloudman999 wait for Fen Light to be available on Tikipeter’s official repository, and not test repository.

**Comment by Cloudman999** [comment]
> @Cloudman999 wait for Fen Light to be available on Tikipeter’s official repository, and not test repository.

OK, no worries. I will do that @Tikipeter 

Thank you
@Cloudman999
