### ISSUE TITLE
[Bug] Progress indicators (Kodi 21)

### ISSUE THREAD

**Issue by rizreflects** [Tikipeter/repository.tikipeter#340]
Hey Peter, I hope you're doing well. I'm unsure as to whether you're accepting bug reports for Fen, so if you're not I apologise in advance and feel free to close this issue. The problem I've run into only applies to kodi 21 Omega, and works fine on 20. As you can see from the image below, the progress indicators no longer appear to be working:

![20231028_131117.jpg](https://github.com/Tikipeter/repository.tikipeter/assets/76912707/794a4c1a-fd21-4563-9e1d-35cac5d1ddc4)

I've tested this with tmdbhelper and that seems to be displaying the indicators just fine:

![20231028_131129.jpg](https://github.com/Tikipeter/repository.tikipeter/assets/76912707/bc737d3c-2d1e-43a1-96a7-0b9baec750a5)

Could you maybe look into this given you have some free time? I admit it's not a huge bug, but it's one of those small annoying bugs that you can't really unsee. Thank you for all of your work on Fen, it's very much appreciated.

**Comment by xyzfre** [comment]
@Tikipeter  I'm experiencing the same issue on Omega Beta 1, I'm on Windows 11

**Comment by xyzfre** [comment]
When I was using Alpha 1 The progress icons were displaying correctly
