### ISSUE TITLE
Calendar crashes when trying to load

### ISSUE THREAD

**Issue by zosoleary** [Tikipeter/repository.tikipeter#342]
Ever since the .12 update, I'm getting an error when the Trakt Calendar widget tries to load or when I manually go to Fen > My Lists > Trakt Calendar. Here is a log:

https://paste.kodi.tv/zowiviyefu

**Comment by Tikipeter** [comment]
Does it "crash" or does it fail to load?

I don't understand what you mean by "crashes".

**Comment by zosoleary** [comment]
I apologize, crash was bad wording. It fails to load and I get a Fen error notification.

**Comment by Tikipeter** [comment]
I'll upload a workaround for when a show in collection/watchlist had no first aired data.

I can't test so hopefully it will work.

**Comment by zosoleary** [comment]
Sounds great. I'll comment after downloading and will let you know

**Comment by zosoleary** [comment]
Working great now, all fixed! Thanks, TP!!
