### ISSUE TITLE
Scrape fails without starting one show

### ISSUE THREAD

**Issue by 99Maxwell99** [Tikipeter/repository.tikipeter#342]
EDIT: Huge spam log removed.

**Comment by Tikipeter** [comment]
You need to upload your log to a pastebin site and post the link here. This is unreadable unfortunately. Also describe your issue clearly.

**Comment by 99Maxwell99** [comment]
I think I narrowed it down. It seems anything that was saved as a favorite fails to work and I have to remove it search and readd as favorite for scrape to work
