### ISSUE TITLE
[Request] UpNext addon integration?

### ISSUE THREAD

**Issue by mathu204** [Tikipeter/repository.tikipeter#343]
Using library files i have an addon called up next that shows a netflix style notification with art for the next episode with a watch now or close button to play the next episode towards the end. However using Fens autoplay next (to prescrape episodes and make the process faster), when clicking play next on UpNext addon it interferes with Fens autoplay next and by doing so it skips an extra episode. So example
Watching 1x01, Next Up says play 1x02, Fen says Next 1x02, I press play on Up Next notification to go into 1x02, Fen ends up playing 1x03 next.

Integrating UpNext (it shows on the addon wiki, I think Seren has integrated it already) would solve this problem as I wouldnt even need the addon at that point and I think UpNext integration is sleeker anyway.

or Maybe would you consider adding an alternative option to Autoplay next called Prescrape next? Basically it would just prescrape the next episode and have the links cached (maybe for a set amount of time or something so it doesnt stay too long and build up), so that when you press the next episode within Fen it would almost instantly play. This wont be much help inside Fen itself, but outside in the library it  would make it so that when I press play Next using the Up Next addon and it sends to Fen to play next episode the link would already be scraped making it play almost just as fast as with Autoplay Next enabled in Fen. It would be helpful if using playlists or play from here as well if one doesnt use up Next addon, or made a playlist within Fen (but again its just extra steps for inside of Fen, but much more useful outside)

[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/5684013/kodi.log)

**Comment by Tikipeter** [comment]
Next Episode is a garbage piece of code that needs an old version to run because the dev stopped it working with addons a while ago.

I hate both it and Kodi Library integration with a passion that defies logic. There will likely be a time very soon when Fen will not even play an item not sourced from within the addon, such is my dislike.

I shall let you infer the answer to your request based on what I've written above.

Hint: It's a no.

**Comment by mathu204** [comment]
> Next Episode is a garbage piece of code that needs an old version to run because the dev stopped it working with addons a while ago.
> 
> I hate both it and Kodi Library integration with a passion that defies logic. There will likely be a time very soon when Fen will not even play an item not sourced from within the addon, such is my dislike.
> 
> I shall let you infer the answer to your request based on what I've written above.
> 
> Hint: It's a no.

Haha When Hell Freezes Over, alright man I understand. But I hope u keep  the letting Fen play content from outside I truly do bc Fen is the best addon for me and it works so great with my library and everything. Please fingers crossed let that be the only addon left
