### ISSUE TITLE
Extras menu - details toggling on/off when mousing over menu buttons

### ISSUE THREAD

**Issue by billm23** [Tikipeter/repository.tikipeter#344]
While in the Extras menu when trying to click on one of the menu buttons, the video details are displayed pushing the buttons down, then when I move the moues it continually toggles on/off making it very difficult to click a button.

**Comment by Tikipeter** [comment]
There's no mouse support in any custom Fen window.

**Comment by billm23** [comment]
> There's no mouse support in any custom Fen window.

Okay, Thanks.
