### ISSUE TITLE
[Bug/Possible Bug] Resume points not setting in NEXT episode using Fen Autoplay Next

### ISSUE THREAD

**Issue by mathu204** [Tikipeter/repository.tikipeter#345]
Hi Tiki, Im using library content through TMDB Helper and this is a little back to that post earlier I made about UpNext, dont worry im not asking u to integrate or even touch it haha. But I was using it to play my next episodes however sometimes the pop up just doesnt show up so I decided to switch back to using Fen's Autoplay next feature. The reason I didnt use it before was cause the next episodes progress point does not get set. 

I enabled it and again I tested this with Promised Neverland Ep 3, going into 4 where 3 was marked as watched but 4's progress was not set. 

1. Would you mind telling me your settings for when you said you tested with a show (Kill La Kill i think) and the resume point was set for the next episode in Autoplay? Maybe I have something set up wrong.
2. 
2. Alternatively (unlikely but maybe Ill ask lol), would u consider adding an option to pre scrape and kinda cache the search results of next episode instead of playing it alongside autoplay next episode so you can back out of an episode or something but come back after play next and it would play fast (This is a scenario im thinking of to use in the addon, cause for me im trying to use it with upNext addon lol but I dont want to wait for hell to freeze over, but honestly there isnt much use for this feature in the addon itself ill admit so i know this one is probably unlikely. I also know that you are not fond of library stuff either now so I know you are probably not fond of trying to fix my errors with library content when it isnt of too much concern to you)

3.Alternatively Do you think you could take a look at the log (i play the episodes at the end) and maybe see if there is something that shows why it is not working? Also, I enabled set Marked in Library when watched in Fen for a bit, I didnt test next episode, but when I play a single episode the episode progress is marked, but after i back out and go back the progress is visaully and numerically set back to 0% (it resumes correctly but it just goes down to 0% after I back out the show, it shows the correct percent when I back out from the video first, but pressing back another time to go back to seasons, or the home screen then returning resets it; I know you mentioned another time it may have been a refresh container issue but disabling this makes it work perfectly for single episode progress, and next episode. The only thing is Upnext as u said is ****, but the only thing I can use to play next consistently and have resume points always work. if only I could get the next episode to play consistently I would be set for life :D )

This is a long post Im sorry, also again I know you are not fond of library content/external content being played through Fen so if this is something you dont want to bother with I completely understand but I have my hopes up. My one request would be is that if you dont want to/cant fix this, please just leave the feature to play external content bc Fen is god tier man and the resume points/read from library point is something only Fen can do, along with how great it is.  Thanks again for making this great addon.

[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/5722119/kodi.log)

**Comment by Tikipeter** [comment]
I've not time just at the moment, but I'll make this the first thing I look at.

I'll be looking to fix subsequent episodes of Next Episode not setting resume point.

I'll have to install TMDbHelper to test, as last time I tested I was just using Fen playback from library I think.

**Comment by Tikipeter** [comment]
Next update (v.1.8.24) will hopefully fix progress not being set on subsequent Next Episode items.
Make sure you have "Set Watched In Kodi Library When Watched in Fen" set to ON (Settings->General->Watched Indicators).
Let me know if it works after the update.

**Comment by mathu204** [comment]
> Next update (v.1.8.24) will hopefully fix progress not being set on subsequent Next Episode items.
> Make sure you have "Set Watched In Kodi Library When Watched in Fen" set to ON (Settings->General->Watched Indicators).
> Let me know if it works after the update.

Thank you! I am using Titan Bingie Mod, however I’m afraid using set watched in Kodi library setting gives me another error/bug I’ll quote what it said “ I enabled set Marked in Library when watched in Fen for a bit, I didnt test next episode, but when I play a single episode the episode progress is marked, but after i back out and go back the progress is visaully and numerically set back to 0% (it resumes correctly but it just goes down to 0% after I back out the show, it shows the correct percent when I back out from the video first, but pressing back another time to go back to seasons, or the home screen then returning resets it; I know you mentioned another time it may have been a refresh container issue but disabling this makes it work perfectly for single episode progress, and next episode.”

the only issue is up next addon doesn’t consistently show up so I switch to Fens Up next, which then brought me to make this post

**Comment by mathu204** [comment]
Btw, if u get Titan bingie mod to test, can u check something out? I’ve had an error happen now whenever I run a trakt sync all my episode progress is reset and I lose the progress even tho I still have it on my trakt account. 

I would have made another feature request about something like asking if you’re still working on Trakt resume, and or adding an option something like to use Fens resume point priority over library, or use Fens resume if there is one but not in library, or use Fens if it is higher than the library one. 

But 1. I know u said Trakt is a difficult one to rewrite but u would do it on your own time so I would just wait and 2. Again I know u aren’t fond of external/library stuff so I didn’t want to trouble you with making a completely new feature only for library stuff again.  

So for now I’ve just disabled trakt episode playback scrobbling And just use episode watched statuses, and made an issue open on the Trakt GitHub. But if u could test if this happens for you too when on Titan bingie mod it would be helpful info!

**Comment by Tikipeter** [comment]
Unfortunately for you all resume points and watched checkmarks stayed visible to me after backing out and re-entering library episodes when using Titan Bingie Mod. I tested 10 different resume points of diferent seasons of a couple of different shows. Always worked.

Even if it did not stay visible, it's not something an addon can fix as you are in Kodi's own library. It is making the list items for display by the skin.

**Comment by mathu204** [comment]
> Unfortunately for you all resume points and watched checkmarks stayed visible to me after backing out and re-entering library episodes when using Titan Bingie Mod. I tested 10 different resume points of diferent seasons of a couple of different shows. Always worked.
> 
> Even if it did not stay visible, it's not something an addon can fix as you are in Kodi's own library. It is making the list items for display by the skin.
> 
> I can't really even suggest a fix, other than nuking your install entirely and trying again.

In this situation are you talking about resume points still being there after running a trakt sync or after backing out to home and re entering the show?

It’s weird bc that one setting makes or breaks it for me what kind of problem do u think it is if u have any idea? I guess the next step for me is to figure out what the problem is on the Kodi library side and get some help on another forum thank you for testing it out for me, maybe it is the container refresh issue u mentioned? 

Also this is me thinking more idealistically, maybe the progress bug fix for next episode fixed the current episode progress too. Which I hope might be the case

**Comment by Tikipeter** [comment]
After backing out and re-entering is what I tested.

The problem for me is all Fen does is set a resume point for that library item when needed. That is done immediately when playback is stopped. That is then the end of Fen's involvement. If that item then resumes at the correct point upon next playback, then Fen's code is correct.

When kodi is making the list of episodes, Fen is not involved at all. It's all Kodi passing info to your skin to display.

So if the episode offers the correct resume point when you go to finish watching (even if the resume indicator is missing), then the Fen code has worked correctly in setting that resume point. My little part in the cog has worked.

Aside from nuking your install completely, it might be worth trying your luck for a day using the default skin. See if it solves this particular issue. If so, you'll know where to look for answers.

Also, you're right about waiting for the next Fen update before doing too much mire troubleshooting. Things may miraculously sort themselves out. A day or two for the next update.

**Comment by mathu204** [comment]
For whatever reason even after .24 update single episode progress is not shown visually even tho it can resume, I do not know why this is the case and same thing does happen in base skin as u reccomended. So I know you said this probably isnt a Fen issue but no matter what I attempt the mark in library when watched in Fen is the make or break setting. Could you send me a screenshot of your settings? maybe just maybe I am missing something to mess it up. I dont think its skin related either, and for some reason while it worked for you I met someone in the TBM forum who had the exact same issue and disabling this setting fixed it. But maybe it could be something in Titan Bingie Mod that even when I switch skins to default it still affects something? Idk but to be fair the guy that had the same problem was also using this skin. 

So i think maybe either 1. Im missing a setting
or 2. I can try to hope that the fix u made for next episode progress, will work even without mark in library enabled (I hope 2 can be the case so i dont have to worry either way)

**Comment by mathu204** [comment]
So on a first test, it does seem to mark episode progress in next episode even without Mark in Library enabled, I do admit that there were like a handful of rare cases when the episode progress was marked sometimes even before this v24 fix. But the fact that it worked on the first attempt is very good news. Thank you as always Tiki and Ill keep you posted, let me know if I should close this or you can close it :D

**Comment by mathu204** [comment]
> So on a first test, it does seem to mark episode progress in next episode even without Mark in Library enabled, I do admit that there were like a handful of rare cases when the episode progress was marked sometimes even before this v24 fix. But the fact that it worked on the first attempt is very good news. Thank you as always Tiki and Ill keep you posted, let me know if I should close this or you can close it :D

hey tiki so on further testing it doesnt always record progress in the next episode, granted I am not using enable watched in Library when watched in Fen bc no matter what I do that is the one setting that seems to wipe episode progress back to 1% for me not sure why. I know that u said that Fen doesnt handle library progress but do u think 1-maybe just maybe there is something being overlooked like when Fen sends a playback progress signal back to kodi, or 2- do u think there could be a workaround to get this playback fix u made to work without the setting in question??

**Comment by mathu204** [comment]
> > So on a first test, it does seem to mark episode progress in next episode even without Mark in Library enabled, I do admit that there were like a handful of rare cases when the episode progress was marked sometimes even before this v24 fix. But the fact that it worked on the first attempt is very good news. Thank you as always Tiki and Ill keep you posted, let me know if I should close this or you can close it :D
> 
> hey tiki so on further testing it doesnt always record progress in the next episode, granted I am not using enable watched in Library when watched in Fen bc no matter what I do that is the one setting that seems to wipe episode progress back to 1% for me not sure why. I know that u said that Fen doesnt handle library progress but do u think 1-maybe just maybe there is something being overlooked like when Fen sends a playback progress signal back to kodi, or 2- do u think there could be a workaround to get this playback fix u made to work without the setting in question??

After doing a bit of research I saw someone on Emby have a similar problem and he noticed that if you waited about 20 seconds before backing out rather than seeking and backing out the resume point would actually stick and this just happened for me now. Do you know or have an idea why this is? Without the mark watched in Library setting, Kodi will set resume points fine even right after seeking and backing out. Though now that I know I just have to wait a bit it is not a problem I am just wondering what this setting could have to do with this if anything at all

**Comment by mathu204** [comment]
> > > So on a first test, it does seem to mark episode progress in next episode even without Mark in Library enabled, I do admit that there were like a handful of rare cases when the episode progress was marked sometimes even before this v24 fix. But the fact that it worked on the first attempt is very good news. Thank you as always Tiki and Ill keep you posted, let me know if I should close this or you can close it :D
> > 
> > 
> > hey tiki so on further testing it doesnt always record progress in the next episode, granted I am not using enable watched in Library when watched in Fen bc no matter what I do that is the one setting that seems to wipe episode progress back to 1% for me not sure why. I know that u said that Fen doesnt handle library progress but do u think 1-maybe just maybe there is something being overlooked like when Fen sends a playback progress signal back to kodi, or 2- do u think there could be a workaround to get this playback fix u made to work without the setting in question??
> 
> After doing a bit of research I saw someone on Emby have a similar problem and he noticed that if you waited about 20 seconds before backing out rather than seeking and backing out the resume point would actually stick and this just happened for me now. Do you know or have an idea why this is? Without the mark watched in Library setting, Kodi will set resume points fine even right after seeking and backing out. Though now that I know I just have to wait a bit it is not a problem I am just wondering what this setting could have to do with this if anything at all.
> 
> EDIT: Actually I turned Mark watched in Lirbary back off lmao let me actually test now oops, yea nvm even after waiting and backing out single episode progress is still wiped :/
