### ISSUE TITLE
Thank you ❤️ 

### ISSUE THREAD

**Issue by ivarbrandt** [Tikipeter/repository.tikipeter#345]
Hey man! How's it going?

I just wanted to drop by and say thank you for everything.

Thank you for the countless times you've helped me. Thank you for all the knowledge you have imparted to me. Thank you for your time. Thank you for always being you. You're fucking awesome man.

Have a Happy Thanksgiving! Take care.

**Comment by Tikipeter** [comment]
Thanks @ivarbrandt 

I really appreciate those words.

I don't celebrate thanksgiving in Australia, but I appreciate the Holiday if this is what it's about. :)
