### ISSUE TITLE
.24 update throws error with Filter Results by Size enabled 

### ISSUE THREAD

**Issue by ReaLx3m** [Tikipeter/repository.tikipeter#347]
Wont play file with autoplay enabled, nor show sources with it disabled, just an error window pops up.

Log attached
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/5753270/kodi.log)

**Comment by jaimsitecom** [comment]
I can confirm this too. Wont autoplay via tmdb helper. Pops up an error exactly like thread starter. 

https://mega.nz/file/5YxkkBzR#Sw4PbWW2_KeOVTLs5gWTUE_4TwFHSP3mQLkFELRPPFc

**Comment by ReaLx3m** [comment]
Looks like some sort of python script error by looking at the log. For the time being you can have FEN working by disabling "Filter Results by Size"

**Comment by jaimsitecom** [comment]
Thanks for the tip. I just downgraded back to .23, everything fine again.

**Comment by ReaLx3m** [comment]
Now your turn for a tip :), how do i downgrade fen?

**Comment by Tikipeter** [comment]
Let me have a look. Hopefully an easy fix and you won't have to.

**Comment by Tikipeter** [comment]
Easy fix. Update in a second.....

**Comment by Tikipeter** [comment]
Should be fixed with v.1.8.24a just uploaded.

For the future, if you want to go back to a previous version, navigate within this repository to `zip/plugin.video.fen` and choose the previous version from there to download. I always keep one previous version in the folder.

**Comment by jaimsitecom** [comment]
> Now your turn for a tip :), how do i downgrade fen?

TikiPete beat me to it^^^

I always download zips here in his gitHub repo just in case i need to go back. 

And Thanks Tikipeter for the quick fix!

**Comment by ReaLx3m** [comment]
Thanks for the help, and for the quick fix. Just tested the update, and it works ok.
