### ISSUE TITLE
FEN Light Search Paths

### ISSUE THREAD

**Issue by ivarbrandt** [Tikipeter/repository.tikipeter#348]
Hey man! Hope you're having a good week so far.

I have begun implementation of FEN Light search functionality into FENtastic. I also looked at the implementation you did in Fenstruary for FEN and FEN Light. However, because I am also implementing in search functionality for Umbrella, I decided to go the route of the direct search paths.

These are the search paths I'm using for FEN Light:

MOVIES
plugin://plugin.video.fenlight/?mode=build_movie_list&amp;action=tmdb_movies_search&amp;query=

TV SHOWS
plugin://plugin.video.fenlight/?mode=build_tvshow_list&amp;action=tmdb_tv_search&amp;query=

COLLECTIONS
plugin://plugin.video.fenlight/?mode=build_movie_list&amp;action=tmdb_movies_search_sets&amp;query=

PEOPLE
plugin://plugin.video.fenlight/?mode=person_direct.search&amp;query=

KEYWORDS (MOVIES)
plugin://plugin.video.fen/?mode=build_movie_list&amp;action=imdb_keywords_list_contents&amp;list_id=

KEYWORDS (TV SHOWS)
plugin://plugin.video.fenlight/?mode=build_tvshow_list&amp;action=imdb_keywords_list_contents&amp;list_id=

TRAKT LISTS
plugin://plugin.video.fenlight/?mode=trakt.list.search_trakt_lists&amp;query=

Movies, TV Shows, and TRAKT Lists all work fine. Collections, People, and Keywords for Movies and TV Shows are not working. Sometimes I'll get `TypeError: argument of NoneType is not iterable` from the People search path.

Could you provide me with the correct search paths to query? If some of them aren't available in FEN Light please let me know so I can structure my code accordingly.

Thanks man!

**Comment by Tikipeter** [comment]
Hi mate. :)

COLLECTIONS:
Gone in Fen Light.

PEOPLE:
`plugin://plugin.video.fenlight/?mode=person_direct.search&key_id=`

KEYWORDS (BOTH):
Give me a day or two, as I'm using TMDb for keyword results now which will need a special function to work for what you need it

**Comment by ivarbrandt** [comment]
Awesome thank you!

> Give me a day or two

Take your time. Whenever you can. I appreciate you.

**Comment by Tikipeter** [comment]
Now my keyboard keeps breaking communication with my computer. Which makes coding, well, let's say difficult. :)

I'll grab a new one tomorrow and get onto this.

**Comment by ivarbrandt** [comment]
That used to happen to me all the time so I just decided to go wired again. 

Old school ftw 🙌🏽

**Comment by Tikipeter** [comment]
`1.0.03` has the changes and is live.

**Comment by ivarbrandt** [comment]
I added the Keyword search paths for FEN Light and they work flawlessly. Thank you.

I am getting a constant error though from FEN Light that seems to be related to the People search path. It happens whenever you switch the search provider to FEN Light. The path is working as it provides results but the error happens whether or not a search query has been made.

You can test it out on `v1.0.22a` in my test repo. Set the search provider to FEN Light either through Skin settings or using the new icon in the search window.

Here's the error I'm getting. Let me know if you would like a more detailed log.

 ```
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: argument of type 'NoneType' is not iterable
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.fenlight/resources/lib/fenlight.py", line 6, in <module>
                                                       routing(sys)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.fenlight/resources/lib/modules/router.py", line 190, in routing
                                                       return person_direct_search(_get('key_id') or _get('query'))
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.fenlight/resources/lib/indexers/people.py", line 49, in person_direct_search
                                                       key_id = unquote(key_id)
                                                                ^^^^^^^^^^^^^^^
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/urllib/parse.py", line 645, in unquote
                                                       if '%' not in string:
                                                          ^^^^^^^^^^^^^^^^^
                                                   TypeError: argument of type 'NoneType' is not iterable
                                                   -->End of Python script error report<--
```

Also, I noticed this other error right below the Type Error:

`2023-12-05 04:53:49.632 T:30287   error <general>: GetDirectory - Error getting plugin://plugin.video.fenlight/?mode=person_direct.search&key_id=
`

**Comment by Tikipeter** [comment]
I'll fix that so the error is silent.

I think the underlying issue is those calls to the addons are called every time that window is opened/refreshed. So they just usually come back as an error, but I hide most errors.

**Comment by ivarbrandt** [comment]
> I'll fix that so the error is silent.

Awesome thank you.

Btw, I finally had a chance recently to take FEN Light for a spin and whoaaaa it is FAST. To the naked eye it probably appears only slightly faster. This is because it was already fast to begin with. But percent wise it's about 50 percent faster. Absolutely marvelous job. Its got a few things missing that idk if I can live without. But the speed alone is making me seriously contemplate switching.

I'm so glad you made it just for you and with just the things you wanted/found useful. That's so great to see!

**Comment by Tikipeter** [comment]
Thanks man, I appreciate that.

I found around the same as you, 30% to 50% faster usually on certain actions I found important to speed up. Mostly due to simple things that took a lot of work to implement throughout the addon.

I figured you might stick to Fen. I went back through my old issues and realized it was you who asked for Movie Collections support, which I gutted. :(

The main one I remember you and I going back and forth on different features for the "Jump To" navigation. The thing is with this feature, it was something I used all the time as well. The really unfortunate issue is it was the main thing slowing Trakt lists down when they were paginated. Now there's only a small difference between paginated Trakt lists and normal, already paginated lists. When I wanted to get that sorted once and for all, I tracked it down to the Jump To feature, or at least the way I had it implemented.

I was really disappointed to have to ditch that. I'm hoping when I have more time I can at least bring that back.

**Comment by Tikipeter** [comment]
Damn. I'll have to do a quick update to Fen Light with this change, as there is another issue with the trakt db on start up that I'll need to hunt down, and I just don't have time now. It will have to wait.

**Comment by ivarbrandt** [comment]
> I found around the same as you, 30% to 50% faster usually on certain actions I found important to speed up.

Sooo much faster. It's actually insane lol. I didn't think Fen could get any faster.

> it was you who asked for Movie Collections support

Sure was lol. Sad to see it go. But, I completely understand :)

> The really unfortunate issue is it was the main thing slowing Trakt lists down when they were paginated.

That makes sense. That was a suuuper useful feature but I'm really glad you got rid of it since it was slowing things down. If one day you can bring it back without sacrificing speed then that'd be dope.

I just loaded my whole movie collection (bout 1000 movies) in Fen Light and on the very first load it took about 18 seconds. On Fen it takes about a minute. Then I reloaded again and this time it was 5 seconds. On Fen it's about 10-15. Maybe with the crazy speed gains, pagination won't be needed much anyways :)

The one thing that hurt me was the removal of fanart.tv artwork. You know how much I love my beautiful artwork. But then I was quickly reminded that artwork from TMDb is stupid fast compared to fanart.tv lol.

**Comment by ivarbrandt** [comment]
> Damn. I'll have to do a quick update to Fen Light with this change, as there is another issue with the trakt db on start up

I didn't see this until now. I just released `1.0.23`. Is this issue you found likely to affect the multi-addon search functionailty of FENtastic?

**Comment by Tikipeter** [comment]
No, no. It's a separate issue.

**Comment by ivarbrandt** [comment]
Ok. Whew. Had me worried for a sec there.

**Comment by ambulancePilot** [comment]
Would someone be able to provide me with the search path for people but for Fen?

**Comment by ivarbrandt** [comment]
That looks correct. Lemme double check my code real quick and tell you for certain.
