### ISSUE TITLE
Next Episode bug? 

### ISSUE THREAD

**Issue by JFG1000** [Tikipeter/repository.tikipeter#35]
![20220913_182556](https://user-images.githubusercontent.com/76907836/189968962-2bdf6f6d-dbeb-42c2-abef-15f650586429.jpg)
Hi there I'm just wondering why the next episode of the boys is showing for the next season that is due to return in a year or so I believe, this has never happened before

Many thanks

**Comment by Tikipeter** [comment]
You must have "Include Unaired Episodes When Available" enabled in the Next Episodes settings....

**Comment by JFG1000** [comment]
Can you check your Keybase mate many thanks

**Comment by Tikipeter** [comment]
Haven't been on there for a while. :)

**Comment by Tikipeter** [comment]
Fixed for next update.
