### ISSUE TITLE
remove Fen subscription entry from Manage Sources -> Videos..

### ISSUE THREAD

**Issue by SJ50** [Tikipeter/repository.tikipeter#350]
I just reinstalled Kodi again today, I found relics of Fen Subscription entry in Manage Souces -> Videos. 
Please remove these relics.

**Comment by Tikipeter** [comment]
Where is "Manage Sources"?

**Comment by SJ50** [comment]
full path as follows 
"Kodi settings" > "media settings" >Library > Manage Sources > Videos

**Comment by Tikipeter** [comment]
That is Kodi related, not Fen related. These are paths that were still in your Kodi settings, that you had set at some point in the past. The settings aren't automatically removed when you uninstall Kodi.

Just bring up context menu on them and select "Remove Source".

**Comment by SJ50** [comment]
Ok, Thank you.

**Comment by SJ50** [comment]
I had removed .kodi folder, it might have came back when I restore FEN settings.

**Comment by Tikipeter** [comment]
Nope. Fen has never set those folders automatically.

Did you restore any other settings?

**Comment by SJ50** [comment]
found the culprit, I also restored ".kodi/userdata/sources.xml" file which contains video sources as well.

**Comment by Tikipeter** [comment]
Ah, that's it.
Good job.
