### ISSUE TITLE
Request for the custom search paths (Movies & TV Shows) for the "Fen" add-on

### ISSUE THREAD

**Issue by ShibajiCh** [Tikipeter/repository.tikipeter#351]
H Tikipeter,
Could you please provide the custom search paths (Movies & TV Shows) for the "Fen" add-on similar to the below page?

https://github.com/jurialmunkey/skin.arctic.zephyr.2/issues/36

I'd like to implement them in the default search for the Arctic Zephyr 2 skin.
Thanks in advance!

**Comment by Tikipeter** [comment]
@ShibajiCh 
MOVIES:
`plugin://plugin.video.fen/?mode=build_movie_list&action=tmdb_movies_search&query=`

EPISODES:
`plugin://plugin.video.fen/?mode=build_tvshow_list&action=tmdb_tv_search&query=`

I had to close the issue due to no log being provided, which is a hard rule, but above is what you asked for. Good luck.

**Comment by ShibajiCh** [comment]
Hi Tikipeter,

Thanks a lot! You're are a life saver.
Thanks for the great Fen addon.
I really love it.
Keep up the good work!

**Comment by Liquidrag** [comment]
> @ShibajiCh
> MOVIES:
> `plugin://plugin.video.fen/?mode=build_movie_list&action=tmdb_movies_search&query=`
> 
> EPISODES:
> `plugin://plugin.video.fen/?mode=build_tvshow_list&action=tmdb_tv_search&query=`
> 
> I had to close the issue due to no log being provided, which is a hard rule, but above is what you asked for. Good luck.

I know this is closed but can you give us the search for people?

**Comment by ShibajiCh** [comment]
> > @ShibajiCh
> > MOVIES:
> > `plugin://plugin.video.fen/?mode=build_movie_list&action=tmdb_movies_search&query=`
> > EPISODES:
> > `plugin://plugin.video.fen/?mode=build_tvshow_list&action=tmdb_tv_search&query=`
> > I had to close the issue due to no log being provided, which is a hard rule, but above is what you asked for. Good luck.
> 
> I know this is closed but can you give us the search for people?

Hi @Liquidrag, 

Here's the Fen search path for people as provided to me by @Tikipeter sometime back:

plugin://plugin.video.fen/?mode=people_search.search&actor_name=

Regards,
ShibajiCh.

**Comment by Liquidrag** [comment]
> > > @ShibajiCh
> > > MOVIES:
> > > `plugin://plugin.video.fen/?mode=build_movie_list&action=tmdb_movies_search&query=`
> > > EPISODES:
> > > `plugin://plugin.video.fen/?mode=build_tvshow_list&action=tmdb_tv_search&query=`
> > > I had to close the issue due to no log being provided, which is a hard rule, but above is what you asked for. Good luck.
> > 
> > 
> > I know this is closed but can you give us the search for people?
> 
> Hi @Liquidrag,
> 
> Here's the Fen search path for people as provided to me by @Tikipeter sometime back:
> 
> plugin://plugin.video.fen/?mode=people_search.search&actor_name=
> 
> Regards,
> ShibajiCh.

Thank you! I must have missed this.

**Comment by ShibajiCh** [comment]
> > > > @ShibajiCh
> > > > MOVIES:
> > > > `plugin://plugin.video.fen/?mode=build_movie_list&action=tmdb_movies_search&query=`
> > > > EPISODES:
> > > > `plugin://plugin.video.fen/?mode=build_tvshow_list&action=tmdb_tv_search&query=`
> > > > I had to close the issue due to no log being provided, which is a hard rule, but above is what you asked for. Good luck.
> > > 
> > > 
> > > I know this is closed but can you give us the search for people?
> > 
> > 
> > Hi @Liquidrag,
> > Here's the Fen search path for people as provided to me by @Tikipeter sometime back:
> > plugin://plugin.video.fen/?mode=people_search.search&actor_name=
> > Regards,
> > ShibajiCh.
> 
> Thank you! I must have missed this.

Hi @Liquidrag,

You're welcome! 🙂 👍

Regards,
ShibajiCh.
