### ISSUE TITLE
Question about specials in TV shows

### ISSUE THREAD

**Issue by ambulancePilot** [Tikipeter/repository.tikipeter#352]
Hi there,

Currently using Fen and I was wondering if you would be willing to provide the option to sort the specials folder to the end so the seasons show first.

I have succeeded by modifying the season sort key to the following:

`season_data.sort(key=lambda k: (k['season_number'] == 0, k['season_number']))`

Wondering if this will cause any issues in the future or if I  may be inadvertently breaking something by doing this. Also wondering if this is the most efficient and proper way to accomplish what I'm looking for.

Thanks for everything and any help you might provide.

**Comment by Tikipeter** [comment]
I can sneak a change like this into the next Fen bug update. I won't have a setting though, I'll just sort the specials folder to the bottom.

What you've got there is fine in the meantime.

**Comment by Tikipeter** [comment]
Hm, let me double check what happens to the watched counts at the season level with this change.

I'll sort that out if needed.

**Comment by ambulancePilot** [comment]
Ha you see that's exactly the kind of thing I wouldn't think of. Thanks so much man!

**Comment by ambulancePilot** [comment]
Thanks! Excellent news. Great work as always.
