### ISSUE TITLE
[Request] Show First episode in-progress in Next Episodes (or option to enable this)

### ISSUE THREAD

**Issue by mathu204** [Tikipeter/repository.tikipeter#352]
I'd like to make a single widget for my Next Up/Continue watching for my family members build, but the thing is when you are in progress for the first episode of a show (with no previous marked as watched, so 19x01 of Family Guy being the first ep i watch on trakt/fen falls under this too) it will show in "in-progress" but not Next Up. As u can see in these images below, 
Fire Force 1x01, Family Guy 19x01 (the first episode of the show im watching in Fen or in Trakt), and Real H.o.H, 1x01 are all in the in progress widget but dont show up in the Next Up. Seinfeld 3x04 will show up in both because Ive watched episodes before that. 

My request is to make it so the Fire Force, Family Guy, and R H.o.h, episodes and any other in progress first episodes will show up in the Next Episodes as well. Or an option to enable it if some people prefer it this way, but I would prefer just one path/one widget. Or maybe even just an addition to In Progress and Next Up, called Continue Watching that merges both.

![screenshot001](https://user-images.githubusercontent.com/52363082/104124186-5cbd5100-531d-11eb-8849-6eeb03e51f63.png)
![screenshot000](https://user-images.githubusercontent.com/52363082/104124187-5d55e780-531d-11eb-94e3-48f7297a7889.png)

[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/5792639/kodi.log)

**Comment by Tikipeter** [comment]
What if you have 2 (or more) in progress episodes of a single show that you haven't watched a full episode of? Do you want them both to appear in Next Episodes? i.e. You've STARTED watching s01e03 and s02e04 of the show Supernatural. Would you want next episodes to include both of these episodes in it's list?

**Comment by mathu204** [comment]
Um generally I don’t watch 2 episodes at a time to leave progress so for me it wouldn’t make a difference however I would like one show to appear at a time so I would say either the further episode, or the most recently watched in Fen to appear in place. For others that would want both to appear maybe an option? Or would that be more hassle to code in, in which case I would just want the most recent one to populate

**Comment by Tikipeter** [comment]
The problem is I don't keep track of when an in progress episode was watched. That is why they are not ordered a certain way in the In Progress menu.

I can do what you want here, but the issue is going to be I can only place the appropriate "In Progress" episodes at the start or the end of the Next Episodes list. I cannot include them in the sorting order of the Next Episodes list because they lack the required info to sort correctly.

Let me know if that is good enough, and if so, where you would want them (beginning or end).

**Comment by mathu204** [comment]
> The problem is I don't keep track of when an in progress episode was watched. That is why they are not ordered a certain way in the In Progress menu.
> 
> I can do what you want here, but the issue is going to be I can only place the appropriate "In Progress" episodes at the start or the end of the Next Episodes list. I cannot include them in the sorting order of the Next Episodes list because they lack the required info to sort correctly.
> 
> Let me know if that is good enough, and if so, where you would want them (beginning or end).

Beginning then :D

**Comment by Tikipeter** [comment]
OK.
This will be done for next update (v.1.8.25).
I can honor sort order for airdate and title. If Recently Watched is chosen as sort type, then they will be placed at the top of the list.

**Comment by mathu204** [comment]
> This will be done for next update (v.1.8.25).
> 
> I can honor sort type for "Airdate" and "Title". If "Recently Watched" is chosen as sort type, then in progress episodes will be placed at the top of the list.
> 
> All In Progress Episodes from a show with no fully watched episodes will be included.
> 
> The setting: Settings->Next Episodes->Content and Sorting->"Include In Progress First Episodes". Default will be OFF.

Thank you as always Tiki keep up the greatness!
