### ISSUE TITLE
Trakt Scrobbling

### ISSUE THREAD

**Issue by derrgoo** [Tikipeter/repository.tikipeter#353]
This question may be a skin issue but I remember using fen full version vs fen light when I opened another box my trakt list would update as soon as it was opened vs having to click on widget refresh. Not a big issue but been wondering about this since using fen light. 🙏

**Comment by Tikipeter** [comment]
Yes, here's the issue.

Kodi does not wait for an addon to perform it's "services" before it interacts with that addon. So in this case, Kodi is making your widgets BEFORE Fen Light has a chance to run it's trakt sync code and get the new information from Trakt.

In the past, I have run a refresh of widgets AFTER the Trakt sync service has run. This is why in Fen you would see up to date information in Fen when opened. The downside to that is that on first load, thew widgets would need to be loaded twice: once by Kodi, and then again manually by Fen once the updated information had been synced.

I decided in Fen Light to not have that happen on initial startup of Kodi, as I didn't like the double load of the widgets. But, I think that was likely a mistake.

So I will add that back in from next update.

If it's unbearable until then, use Fen and keep an eye on when Fen Light next updates.
