### ISSUE TITLE
[Continuation of previous Error/Bug] Next Episode progress bug.

### ISSUE THREAD

**Issue by mathu204** [Tikipeter/repository.tikipeter#354]
I understand if this one will be closed due to 1- the fact that I am not using Mark watched in Library when marked in Fen, and 2- u said that Fen is likely not the cause of the visual bug with progress being lost. but again this setting is literally the make or break for me and other people as well. (well just 1 other person Ik of actually, and me telling him to disable mark watched in library fixed the issue for him instantly as well/he was also from the Titan Bingie Mod Forum too, but this still happens on a base kodi skin too as youll see in the video)

Previous issue: https://github.com/Tikipeter/repository.tikipeter/issues/345

> "hey tiki so on further testing it doesnt always record progress in the next episode, granted I am not using enable watched in Library when watched in Fen bc no matter what I do that is the one setting that seems to wipe episode progress back to 1% for me not sure why. I know that u said that Fen doesnt handle library progress but do u think 1-maybe just maybe there is something being overlooked like when Fen sends a playback progress signal back to kodi, or 2- do u think there could be a workaround or another fix u can try to get this playback fix u made to work without the setting in question??"

Here is a video and a debug log showcasing how this setting breaks it for me, I am really hoping we can figure out whats causing this/ or maybe another work around for the next episode progress fix that doesnt use mark in library when watched in Fen. 

https://streamable.com/tyy20b

[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/5793487/kodi.log)

**Comment by Tikipeter** [comment]
That video helped me to understand what the possible issue might be.

I have made some code changes for the next update (v.1.8.25). Please test **WITH "SET WATCHED IN KODI LIBRARY WHEN WATCHED IN FEN" SET TO ON**.

Hopefully the changes will fix this issue.

The next release will be within the next day hopefully. Just a few things to test out first.

**Comment by Tikipeter** [comment]
Check next update (v.1.8.25) for a possible resolution to this issue.

That video helped me to see what you were meaning with regards to this issue.

**Comment by Tikipeter** [comment]
Update should be available in a day or two.

**Comment by mathu204** [comment]
> Update should be available in a day or two.

Thank you so much!

**Comment by mathu204** [comment]
1.25.a fixed this thank you so much Tiki as always!
