### ISSUE TITLE
put.io support

### ISSUE THREAD

**Issue by PileofBoxes** [Tikipeter/repository.tikipeter#355]
could you add put.io support :) thanks

they have a api https://app.swaggerhub.com/apis-docs/putio/putio

**Comment by Tikipeter** [comment]
I'll have a look at it, but no promises. :)

Also, for future reference, you MUST provide a Kodi log when opening an issue, even if a log is not needed. Unfortunately, they are the rules I need to have in place in order to keep the Issues section open.

**Comment by mathu204** [comment]
> could you add put.io support :) thanks
> 
> they have a api https://app.swaggerhub.com/apis-docs/putio/putio

what is put.io?

**Comment by PileofBoxes** [comment]
put.io is like a BitTorrent client in the cloud, but whats awesome is they cache torrents and they also will convent them to mp4 so they are compatible with most devices aka apple tv and ruko 
so kinda like real debrid and premiumize
but wish put.io was lil more popular so they get more cached torrents but they do a pretty good job
Thanks for giving it a look Tikipeter if you need account to see if you can get it working let me know 
sorry about the no log
