### ISSUE TITLE
Fen light - Play next / Next up episode - focused button

### ISSUE THREAD

**Issue by SJ1O** [Tikipeter/repository.tikipeter#355]
Hello Peter,

Just wondering if it would be possible to make play the focused button rather than close on the play next / next up window that appears at the end of a episode. This way it works with voice assistant when the play next option appears. You just just ask your voice assistant to select and it will play. Just a thought.

Cheers 
SJ

**Comment by Tikipeter** [comment]
Is the previous episode fully finished when the Next Ep display shows though? If not, then you would have to leave it on the screen until the episode is fully finished.

**Comment by SJ1O** [comment]
No it displays next ep at around 95% complete or last chapter. I use the pause and wait setting so even when it's fully complete I need to hit play or wait for the show to fully complete. However if I ask my voice assistant to select it will close the window and then continue to play the next episode after being fully complete. Some episodes have really long credits tho so I give up and look for the remote just thought id see if this was something that could be implemented. I feel abit daft for asking this request just trying to get the most out of my voice assistant.

**Comment by Tikipeter** [comment]
I'll change the focus to Play for next ep dialog.

But I'm not sure you're going to like it.

**Comment by SJ1O** [comment]
Ohh thanks man I've been meaning to ask for this for a long time now really glad I finally did. I sure I will love it. Thanks again very much appreciated.

**Comment by SJ1O** [comment]
Just got home and tested it. Works lovely can now use my voice command to select play when I get the play next pop up. Achieved exactly what I was after. Thanks so much for doing this. Very very much appreciated.

Kind regards
SJ
