### ISSUE TITLE
FEN and TMDB Helper option?

### ISSUE THREAD

**Issue by jaimsitecom** [Tikipeter/repository.tikipeter#356]
Hi Tikipeter. 

Is there a way to add a FEN (source select option) when using TMDB Helpers choose player setting?  Venom has Autoplay, Source Select, Clear Providers, Trakt manager all integrated in TMDB options. FEN only has Autoplay. While i have FEN defaulted to autoplay, sometimes some sources have bad files being autoplayed, so instead i want to choose a different source thru context menu and not go deep into FEN settings just to disable autoplay. 

Just want to know if it’s possible or if there’s a setting i have to enable to see those choices?

thanks!

**Comment by Tikipeter** [comment]
Try this file below and tell me if it works. I don't have TMDbHelper installed (unzip the file and then add the player inside to the players in TMDbHelper):

[direct.fen.select.json.zip](https://github.com/Tikipeter/repository.tikipeter/files/5796175/direct.fen.select.json.zip)

Also, for future reference, you MUST provide a Kodi log when opening an issue, even if a log is not needed. Unfortunately, they are the rules I need to have in place in order to keep the Issues section open.

**Comment by jaimsitecom** [comment]
Thanks Tikipeter!  Will try it now.

Regarding log, am so sorry. I’ll take note on this for next time.



On Jan 11, 2021, at 10:13 PM, Tikipeter <notifications@github.com> wrote:

﻿

Try this file below and tell me if it works. I don't have TMDbHelper installed (unzip the file and then add the player inside to the players in TMDbHelper):

direct.fen.select.json.zip<https://github.com/Tikipeter/repository.tikipeter/files/5796175/direct.fen.select.json.zip>

Also, for future reference, you MUST provide a Kodi log when opening an issue, even if a log is not needed. Unfortunately, they are the rules I need to have in place in order to keep the Issues section open.

**Comment by jaimsitecom** [comment]
it worked!!! thanks so much again!

**Comment by Tikipeter** [comment]
No worries.

**Comment by mathu204** [comment]
> No worries.

Ohh wow I was actually thinking how’s this would be so dope but never made an issue on it I’ll be sure to add it!

**Comment by xyzfre** [comment]
> Try this file below and tell me if it works (unzip the file and then add the player inside to the players in TMDbHelper). I don't have TMDbHelper installed:
> 
> 
> 
> [direct.fen.select.json.zip](https://github.com/Tikipeter/repository.tikipeter/files/5796175/direct.fen.select.json.zip)
> 
> 
> 
> Also, for future reference, you MUST provide a Kodi log when opening an issue, even if a log is not needed. Unfortunately, they are the rules I need to have in place in order to keep the Issues section open.
> 
> 

Thank you very much for this file added to players Definitely working like a charm￼￼ 👍🏼
