### ISSUE TITLE
Resume playback

### ISSUE THREAD

**Issue by xyzfre** [Tikipeter/repository.tikipeter#357]
Hey Tikipeter thank you for Fenlight It's working flawlessly, and really fast performance,, I noticed two days ago when you resume playback you can see the scraping screen for about 3 seconds before it resumes progress,with Fen it resumes progress almost instant,K20.2,Windows 11,AH2,Trakt

**Comment by xyzfre** [comment]
My apologies for comparing I know Fenlight is different wasn't too sure if that's the way it is now or something that you can look into

**Comment by Tikipeter** [comment]
Could you get a video of this happening? I've seen this mentioned before (perhaps by yourself), but I am not experiencing the same issue.

**Comment by xyzfre** [comment]
https://github.com/Tikipeter/repository.tikipeter/assets/49699869/7b3f9c4d-b1af-4edc-98ea-468fab105a32

**Comment by xyzfre** [comment]
Fenlight
