### ISSUE TITLE
Progress indicators not showing properly in Fen

### ISSUE THREAD

**Issue by JFG1000** [Tikipeter/repository.tikipeter#359]
![20231210_145236](https://github.com/Tikipeter/repository.tikipeter/assets/76907836/4386ed25-c961-4424-8d91-9e0724a5b95a)
![20231210_145344](https://github.com/Tikipeter/repository.tikipeter/assets/76907836/84962ace-db22-427a-9b17-21b7d748cc52)

Hey Tiki would it be atall possible to take a look and try find the cause of the progress indicator not displaying as it should within fen using Arctic horizon 2? I updated to omega beta 2 for testing purposes and it displays as it should within umbrella but not within fen or fen light, I've attached to photos if you could take a look it would be greatly appreciated, this was displaying fine on nexus just not since testing Omega. 

Kind regards

**Comment by xyzfre** [comment]
It also happens when using Arctic Fuse,on my end this issue started after Omega Alpha 3

**Comment by JFG1000** [comment]
Fingers crossed Tiki can look into it and hopefully identify the cause, going to stay on beta 2 now as besides that it's running smoothly so it may be something we have to just get used to.
