### ISSUE TITLE
Clear Art missing and information (TV Shows only) 

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#36]
I noticed that Clear Art is missing, and show information (when playing a episode, and pressing information, I use the Aeon nox silvo mod skin, worked before latest update).

Forgot to mention it earlier. 
![Screenshot_20191007-002148](https://user-images.githubusercontent.com/47715606/66277040-203cb300-e899-11e9-913b-276b37918625.jpg)

**Comment by Tinuz97** [comment]
Normally it looks like this (movie screenshot), but without the disc art (I know that does not work with TV shows).

Also I noticed that some studio icons are missing (see top left, txt instead of a studio icon, some do work fine). 
Just fyi 😉

https://imgur.com/a/aCInzls

**Comment by Tinuz97** [comment]
And here a screenshot for comparison with a working studio icon (top left)

Screenshot:

https://imgur.com/a/ohWGx87

**Comment by Tikipeter** [comment]
First, the easy one. The studio icon not showing is because the production is from multiple studios, so the skin only shows the label because it can't parse which studio icon to use.

As for the other issues, I don't know what is causing this. It works OK for other skins, just not this one. I will have to poke around and see what' happening. Leave it with me for a bit....

Thanks Tinuz97.

**Comment by Tikipeter** [comment]
OK. All these issues should be fixed in the next update. :)

**Comment by Tinuz97** [comment]
Woohoo! 🎉

**Comment by Tinuz97** [comment]
Information for TV shows working again, also the clear art, thank you.

Screenshot:
https://imgur.com/a/RauxihP

**Comment by Tinuz97** [comment]
(testing download later, watching a TV show now)

**Comment by Tinuz97** [comment]
Downloading and keep the original name works flawless also (tested torrents), AWESOME! ,sorry for caps, but it is realy awesome (tested in the latest A version)

Thank you :)

**Comment by Tikipeter** [comment]
No worries. Thanks for reporting back. :)

Remember, if the download defaults to the generic name, it's because it couldn't find the title in the filename.

I'll close this and the other issue. :)
