### ISSUE TITLE
Just a Thank You

### ISSUE THREAD

**Issue by kodiadon** [Tikipeter/repository.tikipeter#361]
Just wanted to say thank you for all your hard work.  I'm glad you also gave a link for the last version  (1.7.12a) before the big change. I tried many times to get the newest one to work. It would work for maybe 2 days then stop. I had to re-authorize everything again. After going back to the 1.7.12a version I can enjoy using Fen again without errors and it works flawlessly, very fast and the best addon out there. It's better than Seren in my opinion.

**Comment by yam4me** [comment]
many thanks for the best addon all arround. I was worried with the the "disapeared" sources but the workarround is working good. Once again, thank you.

**Comment by Tikipeter** [comment]
Much appreciated. Thanks to you both :)

**Comment by xyzfre** [comment]
> many thanks for the best addon all arround. I was worried with the the "disapeared" sources but the workarround is working good. Once again, thank you.

Definitely agree been using Fen for almost 2years now and and watched it evolved into a very unique addon ￼￼ with everything you basically need ,lots of respect for your work @tikipeter and really appreciate all the hard work you do for the community￼￼￼ definitely number ☝️ ￼

**Comment by mathu204** [comment]
Thank you so much!!!!
