### ISSUE TITLE
metacache.db not cacheing data

### ISSUE THREAD

**Issue by jigoop1** [Tikipeter/repository.tikipeter#362]
hi @Tikipeter 

log msg is:
NOTICE: ###trouble with get###: <class 'sqlite3.OperationalError'>
NOTICE: Previous line repeats 19 times.
NOTICE: ###trouble with set###: no such table: metadata
NOTICE: Previous line repeats 19 times.

btw there is not tables in db file

**Comment by Tikipeter** [comment]
Try deleting the database file altogether. Restart Kodi and see if it starts writing correctly.

**Comment by jigoop1** [comment]
hi,
 thanks it work now by deleting db file , quick responce and your work, i highly appreciate.
