### ISSUE TITLE
Easynews results

### ISSUE THREAD

**Issue by rishisss23** [Tikipeter/repository.tikipeter#363]
![Screenshot_2021-01-18-11-29-51-740_org xbmc kodi](https://user-images.githubusercontent.com/76693986/104879232-75fc7800-5983-11eb-9a5e-50f6a3ad8b92.jpg)
hi

Thanks for this wonderful addon tikipeter. 

I have a small problem;most of my easynews(only on easynews scraping)results i am getting wrong title results with similar names .. Can anything be done about this in my settings;or should I remove autoplay and select accordingly which I am happy to do if no other option. 

For example:if i search for 'house' series episodes i am getting 'house of saddam' or other title s with house names in it;so not possible for autoplay.;but using other sources from fenom scrapers it is screening correctly. 

Sorry to bug you with some trivial doubt;but would be grateful if I can get a solution. 

Thanks

[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/5828181/kodi.log)

**Comment by Tikipeter** [comment]
Is that Kodi 17?

**Comment by rishisss23** [comment]
no.. 18.9

**Comment by rishisss23** [comment]
I am using fen addon in latest kodi in shield. I tried the same in my Android mobile and got the log; and then also same problem..

**Comment by Tikipeter** [comment]
OK. 2 things.....

I can fix this extra results problem....sort of. Picking a show like you have (House) will show a lot of false results, so I can add a setting for the internal sources to filter out nearly all of the false results. The trouble with easynews is releases there sometimes have aliased names, so as to avoid getting taken down by copywrite. An aggressive filter will remove these aliased releases as they will not match. So the best bet is to have it as an option to turn on or off for each internal scraper (the external scrapers, Fenomscrapers, already filter aggressively).

The second thing is your results screen doesn't look right in the picture you provided. There is a "working" graphic in the middle of the list that should become invisible once the list loads, and the focussed highlight should be the same color as the highlighted scraper source (green in this case). It should look like this:
![screenshot000](https://user-images.githubusercontent.com/28930002/104898610-f6e06180-59cd-11eb-989a-82cee5e1e1c7.png)

P.S. Notice there's only 8 results for me. That's after adding the filter I made to test your request. It works pretty well.

**Comment by rishisss23** [comment]
yeah.. you are right;dont know what happened with the first screen shot.. 
on trying again i too got green highlight
![Screenshot_2021-01-18-15-22-59-192_org xbmc kodi](https://user-images.githubusercontent.com/76693986/104899786-4c524980-59a1-11eb-9a2f-82569f4b7b96.jpg)

**Comment by rishisss23** [comment]
Thank you Tikipeter..option for filtering out internal scraper will solve my problem.. waiting for the update!!! 🌹

Best addon as always!!!

**Comment by Tikipeter** [comment]
No worries. Just be mindful you will lose some correct results.

As an example, when testing, I saw House of Cards s02e01 labelled as HOC s02e01.  The filter will remove that, unless TMDb add "HOC" as an alias for House Of Cards, as the filter will check available aliases. But at this time, it was removed. But I can see for a show like House, a filter would be much more useful than not.

**Comment by rishisss23** [comment]
Thank you.. understood..made my day!!!

**Comment by Tikipeter** [comment]
Done for next update (v.1.8.26).
Settings->Internal Scrapers->Easynews->Filter Results by Name.
Default will be OFF.

**Comment by rishisss23** [comment]
thank you
