### ISSUE TITLE
[Request] Resume from Trakt still on your list of things to do in the future?

### ISSUE THREAD

**Issue by mathu204** [Tikipeter/repository.tikipeter#364]
Hey Tiki, not really asking or pressuring you for this at the moment since I know you said Trakt resuming would take a lot of rewrite of code just making this to ask your thoughts on it and if it is still something you are considering to do in the future. You can close it after if you dont want it to clog up your issues. Basically I am introducing and making a build for my friend rn on Kodi, and I want to make it revolve around Fen and Seren, he prefers Fen to Seren atm like me so I want to make Fen the main addon.

However the one issue I am facing at the moment is that since I am goign to set him up on two different TVs meaning he wont be able to resume on another device with Fen. Now I could go the library route and use the Trakt addon since u made the resume from library point, which I appreciate you so much for and I still use on my personal build which enables me to use Fen anywhere, it will be too much of a hassle for him to learn and maintain. On top of the fact when new episodes come out for shows, unlike Addons when they get details updated they will refresh instantly Id have to teach him to do it manually for his library shows that just aired, hence why I'm making his build just revolve around addons (Fen, TMDBH, and Seren as a backup is/was my plan).

Seren on the other hand can now resume from Trakt resume points on any device so I may have to make the build revolve around Seren for shows now, or atleast for the "Next Up" widget. Hence me making this post to see if you still plan on doing Trakt resume points and/or if it is something coming kinda soon. (but uk I hear asking developers when something is coming out is not a good idea so u dont gotta answer since u probably have a lot on your plate).

If Trakt resuming is added tho, it does _kind of_ make the library resuming point less useful or not needed, but even if u removed it in favour or Trakt resuming I'd still be using my library with the Trakt addon to get the visual progress bar, even if Fen is not physically resuming from the library if it resumed from Trakt behind the scenes as logn as I had the visual progress bar, and it resumes, im good. (I think u shouldnt tho bc Trakt does go down often so this is where library resuming would be useful: Trakt goes down, Fen cant get any Trakt resume points, in which it either uses the addon resume point saved like it does now, or Library resume point when available, or an option in settings what you want to take priority when resuming, Trakt or Library, or library resuming would be useful for people who dont use Trakt at all, not me tho).

Sorry for the long post.
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/5831888/kodi.log)

**Comment by Tikipeter** [comment]
I wouldn't go the library route like you say you don't want to; too many potential issues.

Unfortunately, my time is limited with work commitments at the moment, so whilst trakt progress integration is on the agenda, it is a fairly involved job, so I simply won't have the time needed for a while. I'm basically doing small things that aren't too much change atm.

Your best bet would be to base the build on Seren (assuming synced progress points are as important to him as they are to you). At least for a while.

**Comment by mathu204** [comment]
> I wouldn't go the library route like you say you don't want to; too many potential issues.
> 
> Unfortunately, my time is limited with work commitments at the moment, so whilst trakt progress integration is on the agenda, it is a fairly involved job, so I simply won't have the time needed for a while. I'm basically doing small things that aren't too much change atm.
> 
> Your best bet would be to base the build on Seren (assuming synced progress points are as important to him as they are to you). At least for a while.

Thanks for letting me know, and by all means it is no rush I am appreciative of all the work you put into Fen I will simply wait for when it does happen and make the switch, prioritize yourself.
