### ISSUE TITLE
Fen error

### ISSUE THREAD

**Issue by pcliff069** [Tikipeter/repository.tikipeter#365]
Log file is at

https://paste.ubuntu.com/p/8pg5fHM97z/

[Log File](https://paste.ubuntu.com/p/8pg5fHM97z/)

Error is coming after I select episode to watch.

Using Amazon Firestick

Regards

**Comment by Tikipeter** [comment]
Please read this:
https://github.com/Tikipeter/repository.tikipeter/issues/358#issuecomment-761556328

**Comment by pcliff069** [comment]
Thanks.
I am not sure what I am supposed to ger out of that.
It seems like a video doing something on a skin I do not use.
It's not important.
Thanks for your great work.
Regards

**Comment by Tikipeter** [comment]
The doing of the something is what you're supposed to get out of it.

Just wait a couple of hours instead and I will push an update. There's been trouble with the repository meaning an update isn't being applied to Fen's 2 tiki dependencies. That video showed how to update them manually.

**Comment by pcliff069** [comment]
Hi and thanks.
It was more the what I was supposed to be doing that was the issue. With the computer and TV in different parts of the house I was missing some part of the process.
95% of my watching is in my own library so for me not a big issue - I am just so super impressed with this addon.
I will give it another go and if it works great - if not I can wait for an update.

All the best

**Comment by Tikipeter** [comment]
New update should be online which will fix these issues.

**Comment by pcliff069** [comment]
all working now

thanks again for a fantastic addon
