### ISSUE TITLE
ANNOUNCEMENT: Fen version 3.2.16 includes self updating code.

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/repository.tikipeter#365]
Hi again.

There's been some upheavals in the last couple of weeks, as the plan to move from Github was semi-enacted and then, unfortunately, gutted.

In saying that, the latest repository version of Fen, `3.2.16`, includes internal updating code. This means that once that version has been installed, it will no longer be tied to the tikipeter repository. It will instead check online itself for updates, and perform them on itself when they are available. Fen Light has been doing that for a few versions now without issue, so it's time for Fen to follow the same path.

As a user, there will be nothing you will have to do, apart from maybe changing the default update action from "Notification" to another of the options if you prefer. Read the changelog for knowledge of your choices.

There is a dummy update to `3.2.17` that will happen after you have updated to `3.2.16`, just to make sure everything is working smoothly.

After this update, you can uninstall the tikipeter repository. After about a week, I will remove it from this github.

Moving forward, when you need to install Fen or Fen Light, you simply use the Kodi File Manager address `http://tikipeter.github.io/packages`. Then choose the fen zip or the Fen Light zip to install. Easy.

**Comment by DaleAlan** [comment]
Cheers Tiki. I like the new update system as it seems fast and functional so nice to see it integrated into the full fat. Have a cracking Christmas.

**Comment by xyzfre** [comment]
@Tikipeter this new way of updating is brilliant GREAT work

**Comment by Guguloi** [comment]
Great stuff man. Works as intended.
Thank you for all your work and Merry Christmas.

**Comment by JFG1000** [comment]
Thankyou so much Tiki, all the best and I hope you and your family have the best Christmas, did you manage to reach out to Jurial regarding progress indicators by am chance?

All the best

**Comment by Tikipeter** [comment]
No. Rizreflects said he was going to do it.

Jurial is not going to want to deal with a 3rd party addon dev.

You guys that are actually using the skin are going to have to get the info.

**Comment by ivarbrandt** [comment]
Sick dude! I just updated to `3.2.17` without an issues at all. 

Thank you for all you do Peter.

I wish you Happy Holidays my friend. I hope they are filled with love and magic 🪄 🎅🏽
