### ISSUE TITLE
[Potential Bug] Lag on certain areas when using Arctic Horizon skin.

### ISSUE THREAD

**Issue by streamindemons** [Tikipeter/repository.tikipeter#368]
https://paste.kodi.tv/guzovejise

Hello, I am facing a bug that is rather weird. When scrolling between the back button, the first episode, and the second episode of a show there is very big lag, that is visibly seen. 

https://imgur.com/a/Izuh2a9

There is a video that can see the issue.

I thought this was a full skin issue but I tested a different addon (Seren) and it does not do the same thing, which is really confusing me. I looked through settings for anything that would make sense of causing this but nothing I could find

**Comment by Tikipeter** [comment]
I have absolutely no idea why it would be doing that.
Try turning off "Show parent folder items" in Kodi's settings.

**Comment by streamindemons** [comment]
> I have absolutely no idea why it would be doing that.
> Try turning off "Show parent folder items" in Kodi's settings.

That seems to have fixed it!
