### ISSUE TITLE
Bug? Discovery

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#37]
Could be me, could you also try to check/replicate this?

Discover TV Shows. 
Year start 2015.
Year end 2019.
Include genres : action, adventure, science fiction.
Language: English. 
Minimum rating 6.
Minimum number of votes: 350.
Sort by release date (desc). 

The ones that I did not write down are stock/empty. 

After I hit the save and browse, I get movie results (not tv shows), Is this just me maybey?

Thx 😊

**Comment by Tikipeter** [comment]
Nope, not just you. It's a typo from a couple of updates ago! I suppose no one's using Discover much (me included)!!

Fixed for next update.

Thanks Tinuz97. :)

**Comment by Tinuz97** [comment]
I like discover.
Now I get another idea, but no idea if it is possible code wise. 

If you,let's say are in movie's. 

You see a movie you like, and gold the OK button. 
You get options like similar/related. 
It then shows almost every movie I like (from let's say marvel movies). 

It would be awesome if you can save that as a filter, or attach it to the movie menu (the simalar/related results).

**Comment by Tikipeter** [comment]
Interesting idea. I may be able to do something like that. Let me see what's possible...

**Comment by Tikipeter** [comment]
For next update (v.1.5.57) a few hours away:

2 options for making similar/related lists:

* Select Similar or Related from context menu of Movie/Show, then when that list loads you can bring up context menu and select either "Export Similar List" or "Export Related List". Then follow the usual steps for adding a list to another menu.

* Alternately, Discover now has a "Discover Similar" item at the top of the filters. Select that, type a Movie/Show name, then type the year if you know it, then choose the correct Movie/Show from the list of results. Discover will then make that Similar list available for Browsing or Export, like normal. If you fill the "Discover Similar" filter, all the other filters will disappear as they can't be used together with the similar filter. Clear the similar filter to bring back the other filters.

**Comment by Tinuz97** [comment]
Wow, awesome, thx 🎉

**Comment by Tinuz97** [comment]
Works wonderfully the export similar/related list, love it! 👌👍🎉

**Comment by edb64** [comment]
This keeps getting better and better, thank you!

Ed Bohan

**Comment by Tinuz97** [comment]
Found a little typo.
It should be 'please choose Movie search option', this is the movie screen (avengers endgame) 

https://imgur.com/a/X1MGzuf

**Comment by Tinuz97** [comment]
Forgot, the typo is in the new similar/related, after you press that the typo is in that screen.

**Comment by Tinuz97** [comment]
Typo fixed in the latest release, thx 👍
