### ISSUE TITLE
FPS Jump To item issue persists

### ISSUE THREAD

**Issue by ivarbrandt** [Tikipeter/repository.tikipeter#37]
Thank you so much for trying to fix the FPS Jump To issue that ambulancePilot mentioned. Unfortunately, the issue persists after the update to 3.0.12. It is mostly noticeable in the Trakt TV Shows Collection. When hovering over the Jump To item in that list, FEN becomes almost non-responsive. I thought it could be because I'm running Nexus but I checked and the behavior is the same on Matrix. Could you please take a look at this and let me know if you are seeing the same thing?

Also, let me know if providing a log would be useful.

**Comment by Tikipeter** [comment]
Damn. I'll give it another look.

Since you can notice it a lot, can you try in a Trakt list other than Collection or Watchlist and let me know if it does it there as well? Something like a Liked list or one of your Personal lists.

**Comment by ivarbrandt** [comment]
I tried a few movie lists outside of Collection and Watchlist and I had zero problems there. I also did the same for shows and funny enough, it is way less noticeable on show lists other than the Collection. But it is still there.

Interestingly enough, I have a Personal list of shows that I use as a sort of backup of my main collection. That list contains a lot of the same items as my TV Shows Collection yet the issue is pretty much non existent in that list.

**Comment by Tikipeter** [comment]
Thanks for reporting back. 🥇 

I'm going to go through every module that might need the fix and sort it all out.

There should be another update in half an hour or so that hopefully will fix this once and for all.

**Comment by ivarbrandt** [comment]
You’re welcome. 

And thank you so much! I appreciate you 💯

I’ll give you an update after you drop the fix. 

Thanks again.

**Comment by Tikipeter** [comment]
`3.0.14` just uploaded.
Fingers crossed.

**Comment by ivarbrandt** [comment]
I can confirm that it is fixed! You're a wizard! Thanks again.

One last thing, and this is minor but I thought I'd point it out anyway.

In the description of the Jump To item, it says "Noop". Not a big deal but if there was a way to hide it, I would really appreciate it.

Here's a screenshot of it.

![Screenshot_20220914-222628](https://user-images.githubusercontent.com/54084201/190314915-112ed1ed-f714-4a75-9587-bf93f83b805d.png)

**Comment by Tikipeter** [comment]
I'll fix the Noop out for next update. :)

**Comment by ivarbrandt** [comment]
Thaaank you so much!

**Comment by xyzfre** [comment]
Way off topic but really is GREAT to have Fen back in the community always Thankful for all your hard work and dedication @Tikipeter
