### ISSUE TITLE
[BUG] Watched episodes/movies not getting marked as watched in Trakt

### ISSUE THREAD

**Issue by ShibajiCh** [Tikipeter/repository.tikipeter#371]
Hi @Tikipeter,
I'm using Nvidia shield tv pro with Kodi 18.9 and Fen latest version. I noticed that while watching an episode or a movie in Fen even though Trakt is scrobbling it correctly, but after the video ends it doesn't get marked as watched in Trakt. So the Next Episode list also doesn't get updated. This mainly happens if I watch a video from first to last without forwarding or rewinding. I also have the Trakt addon installed separately. I have observed that this issue is also happening in Seren but after a time delay of 15 mins it gets marked as watched in Trakt. Venom is working fine though. Could you please try to replicate the problem at your end and kindly advise?

**Comment by Gaddinator90** [comment]
I am also experiencing this, wasn't sure if it was a trakt response issue though, either way I mentioned it to Tiki last night

**Comment by Tikipeter** [comment]
Items are being set as watched immediately in my setup. My setup DOES NOT include the trakt addon though (what's the point?) so there is likely some conflict going on there.

Has the Trakt addon had any updates recently?
Could you post a screenshot of your Trakt addon settings?

Fen checks certain settings from the Trakt addon to determine whether to mark items watched itself. For example, if you have the Trakt addon marking http streams as watched, then Fen won't do it or else they will be marked watched twice in Trakt.
So, either there's been an update and setting id's have changed in the Trakt addon, or you have a setting set which conflicts with Fen marking the item as watched. It should be one or the other.


You MUST provide a debug log with each Issue opened.

**Comment by ShibajiCh** [comment]
Hi @Tikipeter,
I actually need the Trakt addon for scrobbling my local videos, and till date I didn't have any conflicting issues with any addons.

I checked and can confirm that the Trakt addon was not updated recently.

Here are some screenshots of the Trakt addon settings:

![IMG_20210124_222423](https://user-images.githubusercontent.com/65297828/105638927-7fae4000-5e9b-11eb-890c-770cd1ab3077.jpg)

![IMG_20210124_222431](https://user-images.githubusercontent.com/65297828/105638930-82109a00-5e9b-11eb-820b-64e4410bfac7.jpg)

![IMG_20210124_222448](https://user-images.githubusercontent.com/65297828/105638933-82a93080-5e9b-11eb-885b-759a235f4237.jpg)

![IMG_20210124_222453](https://user-images.githubusercontent.com/65297828/105638936-8341c700-5e9b-11eb-9de6-39280b23f151.jpg)

![IMG_20210124_222457](https://user-images.githubusercontent.com/65297828/105638937-83da5d80-5e9b-11eb-9c9a-dbcf9e4e3310.jpg)

I checked by running a video in Fen with both the Trakt addon enabled and disabled.

Here are the Kodi logs:

**Fen with Trakt addon disabled:** https://paste.kodi.tv/tijupumiji.kodi

**Fen with Trakt addon enabled:** https://paste.kodi.tv/oyokufihux.kodi

**Fen with Trakt addon enabled and HTTP Sources Excluded:** https://paste.kodi.tv/jiladanete.kodi

I noticed that with the Trakt addon enabled Fen scrobbled correctly in Trakt but didn't mark the video as watched after the video playback ended, whereas with the Trakt addon disabled I noticed that Fen didn't scrobble at all in Trakt but marked the video as watched after the video playback ended. However, as soon as the video playback ended, Kodi crashed.

**I then tested by Excluding HTTP Sources in the Trakt addon. This time though Fen didn't scrobble at all in Trakt but it marked the video as watched after the video playback ended. Also, this time Kodi didn't crash after the video playback ended. So I guess that it was an one time issue.**

I also noticed another thing. In the screenshot below, the first source link was skipped by Fen and it automatically jumped to the second source link and played it.

![IMG_20210124_215013](https://user-images.githubusercontent.com/65297828/105638949-948ad380-5e9b-11eb-8d63-b90f04b1f777.jpg)

Why did this happen?

I'm not facing this issue with the Venom addon, it runs together with the Trakt addon (with HTTP Sources enabled) and marks videos as watched in Trakt immediately as the playback ends. The issue is happening only with Fen and Seren 2.0.x addons. In Seren 2.0.x the video is not getting marked as watched even with HTTP Sources disabled. I've informed it's developer Nixgates about this issue and he said that he's looking into it.

Kindly let me know your feedback.

**Comment by Tikipeter** [comment]
Fen does not support setting resume points to Trakt. So do not expect Fen to do this at all, it's not coded.
Any setting of resume points to trakt that you notice happening when playing within Fen is from the Trakt addon, not Fen.

Fen checks the following trakt addon settings, and decides whether to mark the item as watched in Trakt based on the setting value:
```
User (authorization): IF NO USER THEN MARK WATCHED IN TRAKT
Exclude HTTP sources: IF TUNRED ON THEN MARK WATCHED IN TRAKT
Scrobble TV show episodes/Scrobble Movies: IF TUNRED OFF THEN MARK WATCHED IN TRAKT
```
This is how Fen works, otherwise items will be marked twice if these checks aren't performed.
If you need Trakt to set resume points/mark as watched for local items, then turn ON the setting `Exclude HTTP sources` and it will solve your issues.


As to skipping of an RD link (this is only applicable to RD):
1. The specific episode needed was not included in the upload to RD by the RD user who uploaded the torrent (this can't be known until playback is attempted).
2. The user who uploaded the torrent to RD did not exclude non-video files (.txt etc), making the whole cached torrent useless in regard to parsing out a single episode (this also can't be known until playback is attempted).

These two conditions for successful playback are completely unavoidable for RD, based on how they cache a torrent and the information they provide through their API. Premiumize and All-Debrid do not have these issues. Every cached link found for them SHOULD play.

**Comment by Tikipeter** [comment]
I'll edit out your settings screenshots now, so that not everybody who reads this thread sees them (Especially your user name in Trakt).

**Comment by ShibajiCh** [comment]
Hi @Tikipeter,
Thanks for the very helpful detailed explanation and for the great work that you're doing. I just have a small doubt. The first source link of The Simpsons Season 1 Episode 4 that I mentioned above was from a torrent which I uploaded in my Real-Debrid cloud and I uploaded it correctly without any text file, etc. However, the torrent was already cached in Real-Debrid when I uploaded it. That particular source link works fine in other video addons like Venom, etc. So my doubt is why is it particularly not playing in Fen? What might be the issue. Kindly advise.

**Comment by Tikipeter** [comment]
I'll have a look and see what the problem is.

**Comment by ShibajiCh** [comment]
Hi @Tikipeter,
Thank you! I shall wait for your update.

**Comment by Tikipeter** [comment]
I don't get that result, so unfortunately I cannot test it.

Kepp an eye on this and open a new Issue if you see it happening again.

**Comment by ShibajiCh** [comment]
Hi @Tikipeter,
Thank you! More or less everything is working fine now.
The only issue is why the first time scraping of a video in Fen fetches less source results compared to when I scrape the video for a second time? In Venom I'm getting almost all sources I scrape the first time within 20 seconds duration. Could you please check about this issue in your free time? Thanks again for the great work!
