### ISSUE TITLE
[BUG] In progress list of movies empty

### ISSUE THREAD

**Issue by ShibajiCh** [Tikipeter/repository.tikipeter#372]
Hi @Tikipeter,
I noticed that even though I've In Progress movies in Trakt, still they don't show up in the In Progress movies list in Fen. The list is totally empty in Fen. Could you please check and advise?

**Comment by Tikipeter** [comment]
The `In Progress` movie list is not from Trakt, it is from movies you are watching within Fen.


You MUST provide a debug log with each Issue opened.

**Comment by ShibajiCh** [comment]
Hi @Tikipeter,
Fine. Thanks for the update!
