### ISSUE TITLE
Announcement: Fen Existence Moving Forward....

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/repository.tikipeter#373]
**UPDATE: A preliminary release of Fen supporting only TMDb has been coded. I will include a zip file below for anyone who wants to give it a try/test. Report any issues at all in the new pinned Announcement I have opened for this release. I'm testing it myself at the moment, and it seems to be running OK. Not a huge slowdown. But there will be issues with any large change like this. Install zip here:
[plugin.video.fen-1.8.31e.zip](https://github.com/Tikipeter/repository.tikipeter/files/5876808/plugin.video.fen-1.8.31e.zip)
RESTART KODI AFTER INSTALLING.
Moving forward, TVDb will most likely NOT be considered as a viable option in Fen for metadata, unless there are serious issues with this TMDb test install. It is much too impractical to support both, and relieves me of my moral dilemma in considering TVDb as an option.**

There is currently a lot of conjecture surrounding the future of addons, both due to Kodi 19 and also the expected change to TVDB's access and implementation. I will try and lay out the future roadmap for Fen development going forward.

**Kodi 19/Python 3 compatibility:**
Fen is currently ~100% Python 3 compatible and ~90% Kodi 19 compatible (very little testing has been done).
The 2 external modules Fen relies upon (FenomScrapers and My Accounts) are ~85% Python 3 compatible and ~50% Kodi 19 compatible.

There is NOT a mountain of work left to be done for Fen and the 2 external modules to become 100% compatible for Python 3/Kodi 19.
So, things are looking good in this regard.

**TVDB and their upcoming changes (early March):**
This is more difficult.

Whilst Fen is in a stronger position than Exodus forks, there will still be a considerable amount of work needed to ensure Fen remains workable after March.

Movies are unaffected and therefore nothing needs to be done in this regard.

For TV Shows, currently Fen uses a "mix" of tmdb and tvdb for metadata in regards to TV Shows (plus fanart.tv if enabled). This is to ensure the most data with the least amount of api calls. This works well currently and is fast, but will unfortunately definitely not work in the same way moving forward for many users.

Thus the plan is as follows:
* ~If a user wishes to buy a $12US/year subscription to TVDB, then Fen will continue to utilize the "mixed" method of TMDb + TVDb for metadata. Slight re-writes may be needed for some methods, but nothing drastic.~
* ~Otherwise,~ All TV Show metadata will come from TMDb, with a slight decrease in performance speed (there will need to be an extra API call when moving from Season-->Episode lists). A larger re-write is needed to support this model, but most of the needed calls have been made by Fen in the past, and are still already there as backups when TVDb fails.

~Because I have not yet decided whether to purchase a TVDb API key for myself, I am unable to re-code the "mixed" approach. If I decide NOT to purchase a personal API key from TVDb, then this approach will be abandoned, as I cannot produce code for it if I cannot test it.~

**The ethics of TVDB's actions**
Many in the Kodi addon "community" (if there is such a thing) are voicing strong objections to TVDb's move to a subscription based service, and are hoping for addons not to adopt the v4 API and let TVDb die a slow death. I do share these objections, and it is currently what is stopping me from purchasing an API from them for testing.

~However, I really enjoy the speed at which I can grab metadata from both TMDb and TVDb quickly, and minimise API calls in the process (remember, I use Fen daily myself, so want to keep features of the addon which I enjoy). I am still up in the air on what to do, so at this moment only count on Fen supporting purely TMDb metadata for TV Shows.~

**Immediate actions to be taken**
There is an update waiting to be released after a few more changes to functions which will be released in the coming days.
After the next update, the priority of coding the changes above will be as follows:
1. Code the changes necessary to support TMDB metadata only for TV Shows (large changes needed).
2. ~Code the necessary changes needed to continue to support TMDb/TVDb mixed metadata (small changes needed).~
3. Finish Py3/Kodi 19 changes for Fen. Help with these changes for FenomScrapers and My Accounts (many small changes needed).

If not for the TVDb changes, then Py3/Kodi 19 would be first on the list. But the TVDb changes are completely breaking to Fen, and the Py3/Kodi 19 changes can be put off simply by users not updating Kodi to version 19.

**Any questions please ask them below, and I will do my best to answer, even though I haven't completely decided the full way forward at this point.**

**Comment by darkmantom** [comment]
That's good news that fen is going forward!
Keep up the good work. I myself wouldnt mind to pay 12€

**Comment by ShibajiCh** [comment]
Hi @Tikipeter,
It's really a great news! I was really upset after the developer of Venom addon decided not to move forward with its development after March 2021. 12 USD is not a big amount and I'm ready to pay it or move forward without TVDB whatever you decide.

**Comment by meesterexx** [comment]
With the Venom developer not moving forward after March, will there be any impact on the FenomScrapers module? That is, are you left to maintain it by yourself since previously it was shared?

Really great news that you are moving forward with Fen during all this. Thank you!!

**Comment by Tikipeter** [comment]
There will be no impact to FenomScrapers. 123Venom will still maintain the scrapers for the foreseeable future..

Really, FenomScrapers is his baby, as I cannot code scrapers. So aside from help coding the addon in general, all the scrapers and maintenance of them is his doing. He is the reason for all the great sources we can have for watching.

Plus, I haven't quite given up on him keeping Venom around. I know he said he's done, but I'm hopeful he may change his mind. He didn't give a 100% definite statement, more of a "here's what I'm thinking at the moment, so I thought I best tell my users". All conjecture on my part, of course.

**Comment by FloridaJC** [comment]
Thank you for all you do. Been a long-time Venom user. Will be trying FEN I support whatever decision you make. Although, my preference is to  support TMDB as solution going forward.

**Comment by xyzfre** [comment]
Really great news to see Fen still moving forward I wouldn't mind paying the $12 a year which is nothing for all the content that we get and thank you for your amazing work Fen only gets better and better￼￼￼￼

**Comment by freaktabnl** [comment]
Great news to see Fen still moving forward I wouldn't mind paying the $12

**Comment by streamindemons** [comment]
I like this announcement! I mainly use Seren, but have been playing around with fen and am very impressed. Personally, I cannot see myself paying the $12 or whatever the conversion ends up being, but I am just one person. Thanks for all the work you do!

**Comment by HypoLuxa** [comment]
Well I’ll purchase your TVDB key that you need for testing, as long as you need it.  Contact me and we can get that taken care of. I would buy one for myself as well as I don’t mind paying the $12 for it to be faster.

**Comment by ronfrankhill** [comment]
> There is currently a lot of conjecture surrounding the future of addons, both due to Kodi 19 and also the expected change to TVDB's access and implementation. I will try and lay out the future roadmap for Fen development going forward.
> 
> **Kodi 19/Python 3 compatibility:**
> Fen is currently ~100% Python 3 compatible and ~90% Kodi 19 compatible (very little testing has been done).
> The 2 external modules Fen relies upon (FenomScrapers and My Accounts) are ~85% Python 3 compatible and ~50% Kodi 19 compatible.
> 
> There is NOT a mountain of work left to be done for Fen and the 2 external modules to become 100% compatible for Python 3/Kodi 19.
> So, things are looking good in this regard.
> 
> **TVDB and their upcoming changes (early March):**
> This is more difficult.
> 
> Whilst Fen is in a stronger position than Exodus forks, there will still be a considerable amount of work needed to ensure Fen remains workable after March.
> 
> Movies are unaffected and therefore nothing needs to be done in this regard.
> 
> For TV Shows, currently Fen uses a "mix" of tmdb and tvdb for metadata in regards to TV Shows (plus fanart.tv if enabled). This is to ensure the most data with the least amount of api calls. This works well currently and is fast, but will unfortunately definitely not work in the same way moving forward for many users.
> 
> Thus the plan is as follows:
> 
> * If a user wishes to buy a $12US/year subscription to TVDB, then Fen will continue to utilize the "mixed" method of TMDb + TVDb for metadata. Slight re-writes may be needed for some methods, but nothing drastic.
> * Otherwise, all TV Show metadata will come from TMDb, with a slight decrease in performance speed (there will need to be an extra API call when moving from Season-->Episode lists). A larger re-write is needed to support this model, but most of the needed calls have been made by Fen in the past, and are still already there as backups when TVDb fails.
> 
> Because I have not yet decided whether to purchase a TVDb API key for myself, I am unable to re-code the "mixed" approach. If I decide NOT to purchase a personal API key from TVDb, then this approach will be abandoned, as I cannot produce code for it if I cannot test it.
> 
> **The ethics of TVDB's actions**
> Many in the Kodi addon "community" (if there is such a thing) are voicing strong objections to TVDb's move to a subscription based service, and are hoping for addons not to adopt the v4 API and let TVDb die a slow death. I do share these objections, and it is currently what is stopping me from purchasing an API from them for testing.
> 
> However, I really enjoy the speed at which I can grab metadata from both TMDb and TVDb quickly, and minimise API calls in the process (remember, I use Fen daily myself, so want to keep features of the addon which I enjoy). I am still up in the air on what to do, so at this moment only count on Fen supporting purely TMDb metadata for TV Shows.
> 
> **Immediate actions to be taken**
> There is an update waiting to be released after a few more changes to functions which will be released in the coming days.
> After the next update, the priority of coding the changes above will be as follows:
> 
> 1. Code the changes necessary to support TMDB metadata only for TV Shows (large changes needed).
> 2. Code the necessary changes needed to continue to support TMDb/TVDb mixed metadata (small changes needed).
> 3. Finish Py3/Kodi 19 changes for Fen. Help with these changes for FenomScrapers and My Accounts (many small changes needed).
> 
> If not for the TVDb changes, then Py3/Kodi 19 would be first on the list. But the TVDb changes are completely breaking to Fen, and the Py3/Kodi 19 changes can be put off simply by users not updating Kodi to version 19.
> 
> **Any questions please ask them below, and I will do my best to answer, even though I haven't completely decided the full way forward at this point.**

I understand where you are coming from concerning TheTVDB issue as most developers are facing. Even trakt.tv had decided to move away from TheTVDB and work alongside TheMovieDB instead. The only thing that might replace TheTVDB is TVmaze ( https://www.tvmaze.com ) which you can investigate. What ever you decide. I thank you so do many others for the hard work behind Fen.

**Comment by Wafflestyx** [comment]
To the people saying they wouldn't mind paying the $12/year.  

If you didn't know content was user created and now they turn around and want to charge people to access the information they created, screw that.

**Comment by Tikipeter** [comment]
I think everyone knows.

**Comment by dm2912** [comment]
Personally I would ditch TVDB, but not for the reason most would imagine.

Yes, I have a massive issue with what they are doing. I have contributed a handful of edits over the years, artwork etc, and the fact they are now paywalling that is nothing short of outrageous, and I have not made an edit since, nor will I..

But there is prospectively a bigger issue with TVDB going forward. Many editors have upped sticks and left there now. Some moving their efforts to TMDB, some TVMaze and some just doing nothing. Trakt are ditching TVDB and moving over to TMDB which will undoubtedly lead to TMDB getting increase focus from editors, and being kept more up to date. It is very likely, in fact its probable that TVDB data is going to suffer. They dont have the volume of editors they had before. People relying on Trakt etc will make any additions, edits and changes on TMDB before anything else, and going forward, I think the quality of data on TVDB is going to nosedive. 

I think there is every chance that the quality of data on TVDB is going to head steadily downhill over the next couple of years.

**Comment by playmorebocce** [comment]
I would rather give $12/MONTH to Charity than give these TVDB guys $12/yr.  I don't like rewarding underhanded and nefarious behavior.  
I certainly wouldn't be upset over having a few additional seconds delay if you went strictly the TMDB route. Its obviously your choice and I suspect most of the people utilizing FEN right now will stay loyal whatever you decide. You've built a great Addon. Thanks

**Comment by cgcgcgcgcg** [comment]
> To the people saying they wouldn't mind paying the $12/year.
> 
> If you didn't know content was user created and now they turn around and want to charge people to access the information they created, screw tvdb.

I couldn't have said it better. 👍

**Comment by Tikipeter** [comment]
OP updated with test zip for TMDb only support.
I'll start a new pinned Issue with this test file as well.

**Comment by pewkodi** [comment]
I have integrated the movie db helper as the searcher for my exodus fork as a backup when tvdb broke in 2019.
 I then had to add the zipped config file to movie db helper via my github link for searching tv shows and movies to work.

 i believe there is a link to add all the other supported forks:

https://github.com/a4k-openproject/json.openplayers

The moviedbhelper just puts the json info into what the provider info is looking for ie: movie or tvshow id.

**Comment by Tikipeter** [comment]
@pewkodi 

I'm struggling to understand the relevance of your post. Is this related to Fen's future plans with regard to TVDb?
You are mentioning TMDbHelper and it's players.

**Comment by pewkodi** [comment]
@Tikipeter I was mentioning it as a backup to get metadata for searching for tv shows/movies if you are using an exodus based fork. Fen could be used with TMDBHelper but i guess this will not matter since it is going to use it in this build.

I use multiple addons and test the results. Right now, fen gives the best results. I was just letting other try different avenues on getting results.

**Comment by Tikipeter** [comment]
I suppose that would work if all you wanted was to use Fen for results. But you won't be able to browse TV Shows at all in Fen or any Exodus forks once this change happens unless they are updated to either using v4 TMDb API or an alternative. TMDb Helper would only help in that regard if you used it to make Kodi library items and played back from there, or browse show lists through TMDbHelper, in which case you aren't really using Fen.

**Comment by pewkodi** [comment]
Yes. I figured based on the current changes with fen and the json file in json.players for fen being 2yrs old(not updated). 

Exodus forks may have better success with TMDBHelper maybe not once TMDB goes subscription based.

**Comment by Tikipeter** [comment]
Why would TMDb go subscription based?

**Comment by pewkodi** [comment]
I meant TVDB not TMDB. TMDBhelper does not appear to be using TVDB.

https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki

**Comment by dm2912** [comment]
> Yes. I figured based on the current changes with fen and the json file in json.players for fen being 2yrs old(not updated).
> 
> Exodus forks may have better success with TMDBHelper maybe not once TVDB goes subscription based.

The Fen player file was literally updated two months ago. I know that because I found the issue, a solution was found and the player was updated the next morning.

**Comment by dm2912** [comment]
> I meant TVDB not TMDB. TMDBhelper does not appear to be using TVDB.
> 
> https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki

"TMDB"helper

the clue is literally in the name :')

**Comment by pewkodi** [comment]
I had to edit my comment: it was originally TMDB(TMDBHelper maybe not once **TVDB** goes subscription based.) i then changed it. I never used TMDBhelper with Fen.
