### ISSUE TITLE
Announcement: Test Install Available for TMDb only TV Show Metadata Support...

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/repository.tikipeter#374]
A preliminary release of Fen supporting only TMDb has been coded. I will include a zip file below for anyone who wants to give it a try/test. Report any issues at all below in this thread, including observed impact on navigation speed, any issues. I'm testing it myself at the moment, and it seems to be running OK. Not a huge slowdown. But there will be issues with any large change like this. Install zip here:
[plugin.video.fen-1.8.31e.zip](https://github.com/Tikipeter/repository.tikipeter/files/5876808/plugin.video.fen-1.8.31e.zip)

RESTART KODI AFTER INSTALLING.

Moving forward, TVDb will most likely **NOT** be considered as a viable option in Fen for metadata, unless there are serious issues with this TMDb test install. It is much too impractical to support both, and relieves me of my moral dilemma in considering TVDb as an option.

**Comment by xyzfre** [comment]
Thank you for sharing this definitely going to give it a try and afterwords we can just revert back if we have to without a fresh install￼

**Comment by cgcgcgcgcg** [comment]
Uninstalled old Fen, installed the TMDB one.
From the moment I clicked on TRAKT COLLECTION: TV Shows, old Fen took 17 seconds to show me my library thumbs (see pic), new Fen took 5 seconds after doing a Total Clean Up. Maybe the Clean Up made thumbs appear faster with TMDB or I should clean up earlier to compare?
Anyway TMDB seems faster to me.
Using Kodi v18.9 in Arch Linux.
![ksnip_20210127-025742](https://user-images.githubusercontent.com/38960370/105927116-ff7b0c80-604b-11eb-97e9-063cb50a60bf.png)

**Comment by cgcgcgcgcg** [comment]
Support on the title on top needs one less "p" BTW. :D

**Comment by Tikipeter** [comment]
Ugh, I hate people who don't check their titles before posting. That's embarrassing.

**Comment by Tikipeter** [comment]
Good news on the speed though.

**Comment by streamindemons** [comment]
> Good news on the speed though.

can also confirm, mine feel about just as fast. can't be 100% sure cause that would be way too nitpicky at that point

**Comment by rishisss23** [comment]
I also installed and found no issues;didn't feel any difference in navigation speed .. 

Thanks!!!

**Comment by freaktabnl** [comment]
Installed test version, restarted Kodi and see no issues. I did not do a fresh install but just installed the zip over "old" one.

**Comment by meesterexx** [comment]
I can second the "so far no issues" on updating 1.8.31e directly over 1.8.31b. Subjectively (I didn't time it) I notice no speed difference running on kodi 18.9/linux/arctic horizon. Tested multiple categories (trending, popular, premieres, watched, because you watched, in progress shows) and multiple scrapes/test plays of next episodes. 
Thank you again for all your amazing work.

**Comment by unkn0wn234** [comment]
> Uninstalled old Fen, installed the TMDB one.
> Did a Total Clean Up before running both Fen versions.
> From the moment I clicked on TRAKT COLLECTION: TV Shows, old Fen took 24 seconds to show me my library thumbs (see pic), new Fen took 19 seconds.
> Anyway TMDB seems faster to me.
> Using Kodi v18.9 in Arch Linux.
> ![ksnip_20210127-025742](https://user-images.githubusercontent.com/38960370/105927116-ff7b0c80-604b-11eb-97e9-063cb50a60bf.png)

What skin is that you’re using?

**Comment by unkn0wn234** [comment]
Tested now feels perfectly fine!

**Comment by Tikipeter** [comment]
Many thanks to all who tested. I may as well go all in and push an update for this in the coming days.

**Comment by Tinuz97** [comment]
Just installed the test version (on my oneplus 5 phone), and the art is loading much faster in TV shows, as previously with tvdb.
Going to test a little further, but I noticed that immediately.

**Comment by cgcgcgcgcg** [comment]
> > Uninstalled old Fen, installed the TMDB one.
> > Did a Total Clean Up before running both Fen versions.
> > From the moment I clicked on TRAKT COLLECTION: TV Shows, old Fen took 24 seconds to show me my library thumbs (see pic), new Fen took 19 seconds.
> > Anyway TMDB seems faster to me.
> > Using Kodi v18.9 in Arch Linux.
> > ![ksnip_20210127-025742](https://user-images.githubusercontent.com/38960370/105927116-ff7b0c80-604b-11eb-97e9-063cb50a60bf.png)
> 
> What skin is that you’re using?

It's from my favorite multi skin build -which I won't mention. The skin is Titan MOD.  
https://forum.kodi.tv/showthread.php?tid=330749
