### ISSUE TITLE
Latest FEN broke Auto-play

### ISSUE THREAD

**Issue by MrC001** [Tikipeter/repository.tikipeter#376]
I will add the log shortly but on 3 different setups I have none will auto-play.  Have to turn off and select source.
Fen 1.8.35

**Comment by MrC001** [comment]
]
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/5910788/kodi.log)

**Comment by Tikipeter** [comment]
Fixed with 1.8.35a about to be released.

**Comment by MrC001** [comment]
Man your awesome ... Thanx
