### ISSUE TITLE
Autoplay next episode

### ISSUE THREAD

**Issue by rishisss23** [Tikipeter/repository.tikipeter#377]
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/5915975/kodi.log)

hi;

Thanks for the latest update;but after update autoplay next episode seems to be not working. Please have a look whether it is my settings or generalised.

Thanks!

**Comment by Junkdewd** [comment]
It's not just you.

**Comment by Tikipeter** [comment]
Fixed for next update (v.1.8.35c)

**Comment by rishisss23** [comment]
Thank you Tikipeter.. lots of appreciation for your work..
