### ISSUE TITLE
[Request] Option to disable or put Jump to option at end of page alongside Next Page

### ISSUE THREAD

**Issue by unkn0wn234** [Tikipeter/repository.tikipeter#379]
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/5929245/kodi.log)

Id like to make some widgets out of the Trakt lists and noticed when paginating where i can in Fen, the Jump to is always at the front with no option to move or disable it without turning off pagination which would make widget load time slower as it tries to pull from a widget of a 200+ long list. 

Can you consider adding an option to disable Jump To (although I love the idea, it just kinda bugs me as the first thing you see in the widget), or move it to the end? Would be much better imo.

Alternatively dont know if this is possible but would be the best solution, merge them both so instead of a next page option where there is a Jump TO available, clicking Jump To at the end replacing Next page would function how Jump To normally works with saying Jump to 1, 2, 3, etc. But at the top and first focused option would be next page.

**Comment by Tikipeter** [comment]
It should not be showing on widgets at all. It's coded to only show within the addon.
