### ISSUE TITLE
A request

### ISSUE THREAD

**Issue by rishisss23** [Tikipeter/repository.tikipeter#38]
Hi
Really grateful for bringing back this wonderful addon;always an ardent fan.. 

I have a request..There was an option previously in fen where we can link to movies/tv show the files (torrents) in real debrid;so it plays the files correctly after adding in real debrid. 

Is it possible to bring back the feature? For watching regional language movies;that feature was really beneficial after adding the torrent;scraping immediately used to detect the link now it doesn't.. Please consider if not that troublesome.. 

https://paste.kodi.tv/ihoyujocot

**Comment by Tikipeter** [comment]
That's a tough one. I got rid of that feature because I didn't like the way I implemented it.

Let me think about a better way to do it. If I can come up with something I'll include it moving forward.

**Comment by rishisss23** [comment]
Thank you🌹

**Comment by Tikipeter** [comment]
Will be back for next update.

**Comment by rishisss23** [comment]
Thank you so much

**Comment by rishisss23** [comment]
Super!!! Really thanks🌹🌹
