### ISSUE TITLE
Option for Source Select

### ISSUE THREAD

**Issue by soto9d** [Tikipeter/repository.tikipeter#380]
I have auto play on but I was wondering if you can add a "Source Select" option in the Context Menu (hard press). This option would be good for Movies.

Only way I know how to do it now is going to the 
context menu, fen menu, fen option then "Rescrape and Select Source"

Just hoping to get to it faster. 

Fen is amazing btw great job

**Comment by unkn0wn234** [comment]
> I have auto play on but I was wondering if you can add a "Source Select" option in the Context Menu (hard press). This option would be good for Movies.
> 
> Only way I know how to do it now is going to the
> context menu, fen menu, fen option then "Rescrape and Select Source"
> 
> Just hoping to get to it faster.
> 
> Fen is amazing btw great job

Im not the dev, but
That option is literally what it is no? Or are u asking for an option for source select to just open the sources menu from an item that has already been scraped? in which case i see what ur asking for but wouldnt u agree that Fen already scrapes so fast its really not much difference?

**Comment by soto9d** [comment]
Yea I guess I'm asking to move the source select to the main context menu instead of clicking fen menu, etc, etc.
I like having auto play for tv shows so you can binge watch shows without having to select the next episode every time. 
I like selecting the Source for movies.

I guess another way of this would add an "auto play for tv shows" function

**Comment by unkn0wn234** [comment]
> Yea I guess I'm asking to move the source select to the main context menu instead of clicking fen menu, etc, etc.
> I like having auto play for tv shows so you can binge watch shows without having to select the next episode every time.
> I like selecting the Source for movies.
> 
> I guess another way of this would add an "auto play for tv shows" function

Ohh so you’re using a widget so u have to click the fen context menu To then open the settings I think I get what you mean then, moving it would be nice I guess. 

But based on your use case u just explained I think a better request would be incorporating a playback setting like Seren would be better where u could choose between auto play and source select for both movies and shows. That way u could have it the way u want where it autoplays shows and source selects movies

**Comment by soto9d** [comment]
Yea I'm using a widget. I didn't notice there was different options between widgets and non widget. 

But yea after our discussion I think that would be the better option all around

**Comment by Tikipeter** [comment]
I'll get rid of "Fen Menu" and have the options on the main context menu instead for widgets. This will be one less click at least.

That is the best I can do, as I am keeping "Rescrape and Select Source" within Options.
