### ISSUE TITLE
[2 Requests] Movie Studios and Sets/Collections

### ISSUE THREAD

**Issue by unkn0wn234** [Tikipeter/repository.tikipeter#381]
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/5940011/kodi.log)

Would be cool to have a subsection in Movies for Studios similar to how there is one for Networks in TV Shows. 

Second request is for Movie Sets/Collections such as Star Wars collection, Jurassic Park, and 

MCU (or Avengers collection cause I believe TMDB seperates the MCU into individual collections such as Ant Man Collection, Cap America Collection, etc.) (If you would use TMDB for the sets info or whatnot)

**Comment by Tikipeter** [comment]
These are curated type lists, which I steer clear of with Fen.

You can make "folders" and personal lists within Fen that would achieve what you want.

You could make a Fen folder called "Movie Sets/Collections" and add Trakt lists for the movie collections you want in there.

You could also do similar for "Studios".

You need to read up on features in "Fen Tips" within the Tools menu to see how to do things like this. You can have the Fen menus be practically anything you want.
