### ISSUE TITLE
My latest problems/errors

### ISSUE THREAD

**Issue by kodiadon** [Tikipeter/repository.tikipeter#382]
1st. I know I'm supposed to include a log file, but I've never made one or know how to so if I can have help with that, I will load it.

This is what happened over the weekend.  I opened up Kodi>opened Accounts just to check all my info was there>opened Fenom scrapers>sync info>opened Fen>accounts>sync info just to be sure all was good. Backed out of settings>movies>my Trakt list>scraped for a movie 3 different times because it only gave me Hosters>not any Cached Torrents at all. My settings are correct for Cached torrents enabled and hosters. So after no results I backed out of Fen, opened TheOath, scraped for the same movie which gave me a lot of cached torrents.  I started watching the movie with TheOath addon, and after about 45 minutes into the movie a box popped up with no text and only had OK. After clicking OK many times (because it kept popping up) I got out of the movie and backed out of Kodi. Did a force close to Kodi, then re-opened it.  After opening it up again all my Real Debrid info was gone from My Accounts and Fen.

I don't know why Fen wouldn't show any cached torrents, and in the past when what seems Fen errors out because that box pops up...I loose my RD info.  Funny my Trakt info is still in My Accounts, just not my RD.

I'm using the 2019 Shield pro, up to date.  My Kodi is 18.9.  Only using the vanilla Kodi...no skins.  I have Fen, the Oath, Shadow,and the Crew installed and whatever came with those few.

I have always used Fen as my number 1 because I think it's the best.  If only I can get over this problem of continuing to loose my RD info.  

Thanks for all the work you've put in to making this a great addon.

**Comment by unkn0wn234** [comment]
> 1st. I know I'm supposed to include a log file, but I've never made one or know how to so if I can have help with that, I will load it.
> 
> This is what happened over the weekend. I opened up Kodi>opened Accounts just to check all my info was there>opened Fenom scrapers>sync info>opened Fen>accounts>sync info just to be sure all was good. Backed out of settings>movies>my Trakt list>scraped for a movie 3 different times because it only gave me Hosters>not any Cached Torrents at all. My settings are correct for Cached torrents enabled and hosters. So after no results I backed out of Fen, opened TheOath, scraped for the same movie which gave me a lot of cached torrents. I started watching the movie with TheOath addon, and after about 45 minutes into the movie a box popped up with no text and only had OK. After clicking OK many times (because it kept popping up) I got out of the movie and backed out of Kodi. Did a force close to Kodi, then re-opened it. After opening it up again all my Real Debrid info was gone from My Accounts and Fen.
> 
> I don't know why Fen wouldn't show any cached torrents, and in the past when what seems Fen errors out because that box pops up...I loose my RD info. Funny my Trakt info is still in My Accounts, just not my RD.
> 
> I'm using the 2019 Shield pro, up to date. My Kodi is 18.9. Only using the vanilla Kodi...no skins. I have Fen, the Oath, Shadow,and the Crew installed and whatever came with those few.
> 
> I have always used Fen as my number 1 because I think it's the best. If only I can get over this problem of continuing to loose my RD info.
> 
> Thanks for all the work you've put in to making this a great addon.

Depending on the device youre on, go to the kodi home folder and there is a .log file in there, or you can use openwizard and it will give u a qr code or link that u can just copy and paste here easily

**Comment by kodiadon** [comment]
I'm using the 2019 Shield pro

**Comment by Tikipeter** [comment]
I've got no idea.

Perhaps a log would help..

The easiest way to provide a log is using the Kodi Logfile Uploader. Install it from the official repository.

**Comment by Tikipeter** [comment]
Doesn't matter. I know who you are.....
