### ISSUE TITLE
Error when the user is trying to change the Result display at settings.

### ISSUE THREAD

**Issue by chrisnikol** [Tikipeter/repository.tikipeter#387]
After the last update 1.8.36 when the user go at settings ->Results and try to change the Results display option the Fen throw an error message

Here is the sreenshoot of the error message.
![screenshot199](https://user-images.githubusercontent.com/18036001/108098076-9b1bfd80-708b-11eb-93c0-b2acdf61c6b3.png)

At the kodi log file at normal not debug mode i found those relevant records.

-----------------
 Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: XML File for Window is missing
                                            Traceback (most recent call last):
                                              File "C:\Users\chris\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\fen.py", line 5, in <module>
                                                routing(argv[2])
                                              File "C:\Users\chris\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\modules\router.py", line 121, in routing
                                                dialogs.results_choice()
                                              File "C:\Users\chris\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\indexers\dialogs.py", line 249, in results_choice
                                                window = SettingsResultsChooserXML('settings.source_results_chooser.xml', skin_location(), xml_choices=xml_choices)
                                            RuntimeError: XML File for Window is missing
--------------------------

Beside this minor issue that i am sure it would be corrected at the near future, if i may a small request.

Is it posible to consider to add an option to let the user choose how many movies or tv-shows can see at one page when is browsing at movies or tv-shows catalogue?

In any case i am gratefull to you for all your hard work and this amazing addon.
Thank you.

**Comment by Tinuz97** [comment]
Getting this error also (PC and Phone)

Log: https://pastebin.com/ZXs0AHYp

**Comment by naudski** [comment]
I can confirm this issue. Also after scraping a movie or episode, the results won't show.

**Comment by Mahava** [comment]
Can confirm the same issue on Win10 right after the latest update to 1.8.36 and with source select enabled, busy indicator kept rolling at empty sources window.  Link did play when I changed to autoplay.  I have language invoker enabled, btw.  Haven't tested with it disabled.

**Comment by Tikipeter** [comment]
Woops! I was meant to include an update for tikiskins as well.
Sorry all, I'll have this sorted soon.
You will need to be on version 1.1.04 of tikiskins for this to be fixed.

>Is it posible to consider to add an option to let the user choose how many movies or tv-shows can see at one page when is browsing at movies or tv-shows catalogue?

There is already an option in General->Navigation to "Paginate Lists When Possible". This will work on all "personal" type lists (trakt lists, Fen Favorites etc). That is the best I can do. It cannot work for "general" lists like Trending, Popular etc. The sources for those lists only return 20 at a time.

**Comment by Tikipeter** [comment]
Anyone who cannot get results to display after the update, please go into settings and re-set your preferred window style.

**Comment by JBM05** [comment]
> Anyone who cannot get results to display after the update, please go into settings and re-set your preferred window style.

Sorry, but where in settings is this setting?  Thanks

**Comment by Tikipeter** [comment]
Results->Display->Results Display.

**Comment by JBM05** [comment]
> > Anyone who cannot get results to display after the update, please go into settings and re-set your preferred window style.
> 
> Sorry, but where in settings is this setting? Thanks

Thanks.....but as soon as click on it I get that fen error, just like the author of this post described....unless I am not understanding what you are meaning for me to do.

**Comment by JBM05** [comment]
> > > Anyone who cannot get results to display after the update, please go into settings and re-set your preferred window style.
> > 
> > 
> > Sorry, but where in settings is this setting? Thanks
> 
> Thanks.....but as soon as click on it I get that fen error, just like the author of this post described....unless I am not understanding what you are meaning for me to do.

I updated again, and it worked.....thanks for your help.   Furk streams aren't playing now...but that is a different issue and I will post a log.
