### ISSUE TITLE
Fen Error when finding streams

### ISSUE THREAD

**Issue by JBM05** [Tikipeter/repository.tikipeter#388]
Let me say you have an awesome add on here. I have both Furk and Easynews.  They are the only 2 scrapers I have enabled.  When I click a title, it shows the number of links found, but before it can list them, I get a Fen Error, Check log.

[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/5992030/kodi.log)

**Comment by Tikipeter** [comment]
https://github.com/Tikipeter/repository.tikipeter/issues/387
