### ISSUE TITLE
Furk Streams Not Playing

### ISSUE THREAD

**Issue by JBM05** [Tikipeter/repository.tikipeter#389]
Is anyone else having issues with furk?  I haven't been able to play any streams for about a week.  The links come up after a search, but when I click on one, or any, none of them play.  Easynews is playing just fine.

I logged in to furk, verified everything was correct.  I also opened a ticket with furk because I think it is on their end, but no one has gotten back to me. 

Please let me know if you are experiencing issues with furk as well, and if you have any ideas on how to eliminate them.

Thanks!

[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/6000008/kodi.log)

**Comment by Tikipeter** [comment]
I'm afraid there's definitely something wrong with Furk at the moment.

To confirm it for yourself, try and download something from the site. The search works fine, but they've goofed up something with their download servers.

They're never quick to fix things, so I'm afraid it's a waiting game.

**Comment by JBM05** [comment]
> I'm afraid there's definitely something wrong with Furk at the moment.
> 
> To confirm it for yourself, try and download something from the site. The search works fine, but they've goofed up something with their download servers.
> 
> They're never quick to fix things, so I'm afraid it's a waiting game.

Thanks for confirming this.  I'll keep you posted on my end....

**Comment by JBM05** [comment]
Furk seems to be back up.

**Comment by Tikipeter** [comment]
Thanks @JBM05 

I'll give it a try now..

**Comment by JBM05** [comment]
Cool! Quick question.  I am coming from SALTS to FEN.   With salts, I could watch a show in any addon and as long as Trakt was working, My Next Episodes updated instantly.

I am noticing this isn't the case in FEN.  I watch a show in salts on another box, my next episodes updated on that box.  But on the Fen box it didn't.   I tried to refresh and clear cache.  Only way I could get it to up date is to mark it as watched in fen.

Am I missing a setting or something?  Thanks

**Comment by JBM05** [comment]
Just watched a show in fen, and next episodes didn't update.   And it shows as watched in Trakt......if you want me to open a different ticket, just let me know
