### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#39]
Is it possible to get a notification of how many duplicates (links) are removed, like The Oath addon?
I have enabled remove duplicates, and it works great, but a notification would be awesome also, and maybey a switch for it in the settings, to enable, or disable the notification (maybey some people don't like it). 

Just a idea :)

**Comment by Tinuz97** [comment]
* a notification of how many duplicate links are removed.

**Comment by Tikipeter** [comment]
Should be doable, but I'm very busy with Python 3 compatibility, so make sure to remind me of this if it's not in the next update.

**Comment by Tinuz97** [comment]
Just do your thing, no hurry for it.
Did you also read about the new tvdb api on October 30th? (in beta now).

**Comment by Tinuz97** [comment]
https://forums.thetvdb.com/viewtopic.php?f=17&t=59456

**Comment by Tikipeter** [comment]
This should be included in the latest update....

**Comment by Tinuz97** [comment]
It does work beautifully 🎉
Thx 🍻

**Comment by Tinuz97** [comment]
I tested allot, like this new version.
It is much and much faster on my phone (oneplus 5 with snapdragon 835, 8gb ram), nvidia shield tv pro, and my pc.

The trakt collection list etc are loading realy fast now (using kodi 18.4 on every device). 
Every time I think : this addon is the best, what could he change to make it even better, because it is already great, but you keep surprising me 😃

**Comment by Tikipeter** [comment]
I'm glad it sped things up! And thanks for the kind words Tinuz97.

**Comment by Tinuz97** [comment]
The last update (today), is even faster, or placebo, no idea.
I cleaned all cache as a test, hit my trakt collection, and all data (art like poster, fanart) is loading almost instantly, wow. 
Love this update 🎉
