### ISSUE TITLE
Next episodes not working rp4

### ISSUE THREAD

**Issue by unicornsandcandies** [Tikipeter/repository.tikipeter#39]
On my raspberry pi 4 Next Episodes is not working. On my other devices everything works perfectly since a couples days (there was an issue about this here). On raspberry only things that show there are shows in my watchlist, nothing more. I've tried disabling an option to show them and it resulted in showing nothing. I've also tried workaround from before - disabling showing airing today on top, didn't help either. I've also tried installing addon again, authorizing trakt again and updating manually to newest version. I'm clueless. I'm also sending a log from my device here
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/9586526/kodi.log)

**Comment by Tikipeter** [comment]
For the entire 3 minutes of that log, Kodi was trying (and failing) to parse a whole bunch of settings from a whole bunch of addons. There seems to be some underlying issue with this particular install.

My advice would be to completely wipe this install of Kodi, and start again from scratch. If you don't want to do that, really the only idea I have that might make a difference is to clear the trakt cache in Fen. That might help, but if Fen and the other addons installed can't access settings that they need to, which it looks like they can't, then there's going to be all types of issues.

Are all addons behaving normally except for this Next Episodes issue?
