### ISSUE TITLE
[Feature Request] Set minimum file size

### ISSUE THREAD

**Issue by mrXoo** [Tikipeter/repository.tikipeter#390]
Hi there, I was wondering if its possible to set a minimum and maximum file size for streams?

Thanks a lot for this great addon

[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/6017072/kodi.log)

**Comment by Tikipeter** [comment]
Settings->Results->Filter Results by Size.

**Comment by kodilogs** [comment]
Thanks issue closed :)
