### ISSUE TITLE
Kodi 19.0

### ISSUE THREAD

**Issue by sblair77** [Tikipeter/repository.tikipeter#391]
I love love love FEN. Tonight while i was out Kodi updated to build 19.0.0 and it won't allow me to active script.module.myaccounts or script.module.fenomscrapers

I tried to scroll through tickets to see if there was already a fix or if you already know about it but I didn't find anything. I hope you'll be able to fix it. Either way I'm reverting back to an older version of KODI for now.

Thank you!

**Comment by Tikipeter** [comment]
Fen's dependencies  (MA & FS) are not compatible with Kodi 19.

Nobody should update to Kodi 19 if they wish to continue using Fen.

**Comment by pcliff069** [comment]
just saw a YouTube on Kodi 19 - many addons are not compatible. Python 3 to 2 issue I believe. It is recommended that auto update in Google Play be turned off.

**Comment by sasagr** [comment]
> Fen's dependencies (MA & FS) are not compatible with Kodi 19.
> 
> Nobody should update to Kodi 19 if they wish to continue using Fen.

Hi Tiki,
are u planning to make a separate repo/build for Kodi to test and having a smooth transition from Leila to Matrix for all ur users or just making a switch from Leila to Matrix?
In case u need an hand for Matrix test you know you can count on me

**Comment by Tikipeter** [comment]
Hi sasagr!

The plan is for MA and FS to be like Fen; compatible with both py2 and py3.
There is a necessary and important pause in getting that finalized at the moment, but when that happens there will still be the one repository (the current) for both versions of Kodi (18 & 19). There won't be separate repositories.

**Comment by sblair77** [comment]
> Fen's dependencies (MA & FS) are not compatible with Kodi 19.
> 
> Nobody should update to Kodi 19 if they wish to continue using Fen.

Thank you!

**Comment by sasagr** [comment]
> Hi sasagr!
> 
> The plan is for MA and FS to be like Fen; compatible with both py2 and py3.
> There is a necessary and important pause in getting that finalized at the moment, but when that happens there will still be the one repository (the current) for both versions of Kodi (18 & 19). There won't be separate repositories.

Take all the necessary time. I know it will be well spent! but be aware I m checking this repo every day, looking forward to use Fen again after a year break! and feed you with new ideas :)

**Comment by jaimsitecom** [comment]
Good thing i didn’t update yet. Phew!  Thanks for the warning. 

But am hoping you’d have FEN be compatible and installable in Matrix in the future. 

Thanks Tikipeter!

**Comment by Tikipeter** [comment]
Change of plans likely. It's very possible there will be 2 branches of Fen and it's dependencies. One for 18 (that will not receive updates), and one for Matrix (where development will happen going forward).
