### ISSUE TITLE
Ordering results

### ISSUE THREAD

**Issue by Minefield247** [Tikipeter/repository.tikipeter#394]
![IMG_20210222_154856](https://user-images.githubusercontent.com/34307802/108738946-07837a80-752c-11eb-8928-99e79fe3d4a3.jpg)

Is it possible to order all my results into quality then filesize order? It seems to always show easynews at the top regardless of the filesize then RD and PM (I can get those in filesize order). I'd like easynews results intermingled with RD and PM. I've been through all the results options but there doesn't appear to be one. Here is a photo of the results with 'quality, size, provider' in the settings. The quality is all the same, 4K, but it hasn't ordered the list into size order. The easynews 3.97 GB is above the RD 34.4 GB. It's prioritising easynews. Is this intended behaviour? I would have though that as the 'quality' is all the same (4K) it would then move onto the next sort parameter 'size', and would put them in size order which would intermingled the easynews, RD and PM sources? Thanks in advance.

**Comment by Minefield247** [comment]
![Uploading IMG_20210222_154856.jpg…]()

**Comment by Tikipeter** [comment]
This is the expected behavior at the moment.
I'll leave this issue here as a feature request, and I'll likely get to it when I have some time.

**Comment by Minefield247** [comment]
Thanks.

**Comment by Tikipeter** [comment]
This has been implemented for the coming update.
