### ISSUE TITLE
Russian clear logo

### ISSUE THREAD

**Issue by djdirty60** [Tikipeter/repository.tikipeter#395]
hey tikipeter, 
maybe you can solve the problem that I get a russian logo instead of the english one on some movies and series.
it is only when the Dutch metadata is selected, with an English it is in English
will be completely top.  

thank you in advance

Fen
![16140210195497331739541913963125](https://user-images.githubusercontent.com/13561831/108757358-07927300-754a-11eb-9996-057598bb0184.jpg)

Seren
![16140210861046661473871278121441](https://user-images.githubusercontent.com/13561831/108757472-2bee4f80-754a-11eb-8c57-8ce0412a1ed9.jpg)

**Comment by Tikipeter** [comment]
This will be sorted when i find the time..

**Comment by Tikipeter** [comment]
Hopefully fixed for next update.

**Comment by djdirty60** [comment]
![16152250719255891641221955603631](https://user-images.githubusercontent.com/13561831/110359177-76d59000-803d-11eb-91c4-8d6a36a8c601.jpg)

sorry it is unfortunately not yet fixed

**Comment by Tikipeter** [comment]
Ok I'll have another look.

**Comment by Tikipeter** [comment]
The next update hopefully fixes this.

Keep in mind, when there is no Dutch extra art, AND no English extra art, Fen will still grab whatever it can from the highest rated remaining art. So there may still be occasions where there is art in another language, but it should be much more rare now than before.

**Comment by djdirty60** [comment]
Its working thnx
