### ISSUE TITLE
Nothing scraped for TV Shows

### ISSUE THREAD

**Issue by daking1512** [Tikipeter/repository.tikipeter#397]
I'm currently using GDrive scrapping (all properly setup on fenom scrappers/My Accounts), Movies scrap fine and I can get files to stream, but nothing shows up when I try to stream any TV Show, every time I try to scrap an episode I dont get any results back

Your help is appreciated

Here is the log, I scrapped and played a movie and it worked, but the moment I try to scrap an episode of a TV Show i get an error (I think its skin related maybe, I tried to change the view and the error didnt happen again) but nothing scrapes and it says "No Results"
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/6024679/kodi.log)
[kodi.old.log](https://github.com/Tikipeter/repository.tikipeter/files/6024680/kodi.old.log)

Sorry I have responded to the closed issue, please ignore it

Thanks

**Comment by daking1512** [comment]
Hi, I just want to make an update to the issue, I have added my FilePursuit API in the my accounts addon, and enabled it in Fenom Settings, I noticed that Fen completely ignores GDrive when scrapping for TV Show Episodes and go directly to scrapping from File Pursuit (I have picked a couple of popular tv shows just to be sure, Wanda Vision, Vikings, GoT, etc) . 

I have tested the same thing with movies but this time both scrape properly, the progress bar goes through file pursuit first then GDrive then gives me a list of all files from both providers to select from

Thanks

**Comment by Tikipeter** [comment]
I'm going to need to close this as it's likely a gdrive scraper issue and I cannot test that.

**Comment by daking1512** [comment]
Hi

GDrive works fine scraping movies in FEN, its just with TV shows that's having issues, the GDrive scraper is being skipped immediately by FEN and goes directly to the next enabled scraper (in my case its FilePursuit), yet when I try to scrape movies with the same setup I get results from both GDrive and FilePursuit (GDrive is not being skipped by FEN when I scrape movies). the only other addon that uses FenomScrapers is Venom but GDrive scraper works fine with TV Shows, the thing is that FEN is a much better addon in my opinion, I just hope that one issue gets fixed

Thanks
