### ISSUE TITLE
Possibility of excluding punctuation from titles when querying movies/episodes?

### ISSUE THREAD

**Issue by daking1512** [Tikipeter/repository.tikipeter#398]
Im not sure how to provide a log for this one, I dont get errors when I search for a movie with punctuation or special symbols in the title, but it severely reduces the number of results shown after scrapping the item

for example, the movie "I, Tonya" (thats the correct title) can be found as "I. Tonya", "I Tonya" or "I_Tonya" or other varieties, another is the movie "Scoob!" since most files are uploaded without the "!" Fen is unable to fetch them, another is the movie "Malcolm & Marie", most of the files uploaded for this movie dont use the symbol "&" instead they replace it with "and" 

would it be possible to only include words in the query when an item is scrapped?

**Comment by daking1512** [comment]
Hi, How would I get a log for this one? I dont get an error or anything

Please advise

Thanks

**Comment by Tikipeter** [comment]
I'll re-open this manually. For future, I just need a log posted. Error or not.

Check below for rules in regards to posting issues...
https://github.com/Tikipeter/repository.tikipeter#rules-for-posting-issues

**Comment by daking1512** [comment]
Thank you, here is a log when I query "I, Tonya"
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/6025675/kodi.log)

the results are inconsistent, some include files with punctuations in them, some dont (one file has "I,.Tonya" and it doesnt show up for some reason), I can see that the reults removed all "." from the file name, but it didnt do it for all files in the drive

Thanks

**Comment by Tikipeter** [comment]
This needs to be looked into when i have time...

**Comment by Tikipeter** [comment]
I'm closing this as I tested `Scoob!` and `I, Tonya` and got the same results whether the search name was cleared of `!` and `,` or not.
