### ISSUE TITLE
Language Invoker error since latest update...

### ISSUE THREAD

**Issue by Converted007** [Tikipeter/repository.tikipeter#399]
![asset](https://user-images.githubusercontent.com/36426581/108782772-7e406800-756c-11eb-969d-c06c48830738.JPG)

Im getting this error on all my devices (windows and pi4) since the latest update.
Kodi language is dutch.

Second error: Cant play streams: http://paste.kodi.tv/ofoduzezug
Giving a few errors...

Can you take a look at it? Thanks

**Comment by Tikipeter** [comment]
The first issue (in your picture) is not an error. Just select OK and let Fen re-load your profile.

The second issue is from about 4 updates ago. You need to go into Settings->Results, and re-choose a "Results Style" from the settings.

**Comment by Converted007** [comment]
> The first issue (in your picture) is not an error. Just select OK and let Fen re-load your profile.
> 
> The second issue is from about 4 updates ago. You need to go into Settings->Results, and re-choose a "Results Style" from the settings.

My bad:-) All working again.
