### ISSUE TITLE
scrape error

### ISSUE THREAD

**Issue by kodifitzwell** [Tikipeter/repository.tikipeter#4]
Hello,

I have this bug in my addon where a random scrape will return "remaining providers: +0" and few results, but a subsequent scrape will return full results.  I was checking if I could reproduce in Fen and this different error presented itself with 3.0.04:

[kodi.log](https://paste.kodi.tv/javiroxuda.kodi)

at first, thought it was a pattern, but other titles fail too:

    avengers: infinity war
    spiderman: no way home
    captian america: civil war
    transformers: dark of moon
    transformers: age of extinction
    star wars: rise of skywalker
    the fate of the furious
    aquaman
    the dark knight rises
    joker

but with continued trail, other titles succeed:

    star wars: the force awakens
    star wars: the last jedi
    avengers: age of ultron
    jurassic world: fallen kingdom
    etc.

Hope this helps.

**Comment by Tikipeter** [comment]
Appreciate the report. :)

TMDb had a hiccup earlier where they weren't returning all the `append_to_response` items that Fen requests.
There was some code in metadata where I was setting alternative titles to `None` if it wasn't present in the data. That
s where this error is then coming from down the line. alternative_titles should be set to `[]` if not present, to fix this (as rare as it will be).

If you re-cache the meta for those titles, they should now scrape correctly.

As for your problem.... I'll see if I've made any code changes in that area and get back to you here. Because it's something that I've looked into before. I think I did change something to fix it (or hope to).

**Comment by Tikipeter** [comment]
I can't see any differences in code that would affect the issue you're having unfortunately. Keep an eye on whether Fen does this as well, and as soon as you see it happen, shoot me a message and I'll try and reproduce and get it sorted.

It looks like any code I changed for the +0 bug is already in POV. :(

**Comment by kodifitzwell** [comment]
close this as tmdb seems to have fixed their issue?  thanks

here is what I was able to determine.  I'm still a dummy with this, so you can tell me if the change I made is just masking the issue or makes no sense.

the only way I was able to consistently produce the issue was to delete the cache and reduce number of scrapers.  then start at the top of blockbusters so I know there will be plenty of results, scrape, back out and scrape the next.  eventually a few in the list will randomly show "remaining providers: +0" or return "no results."  realistically this is not normal use I know, but I tried Fen with Cocoscrapers and could reproduce it.

in any case, from ```external.py``` I found *len_alive_threads*, *self.threads_completed*, *process_movie_threads*, *process_episode_threads*.  I changed **get_sources** in both my addon and Fen, and the issue is not reproduceable.  so ultimately, maybe there is a better solution in *process_\*_thread* functions, but that it still beyond my remedial knowledge.

added *sleep(100)* after *self.threads_append = threads.append*
 

    def get_sources(self):
        ... code snipped ...
        threads = []
        self.threads_append = threads.append
        sleep(100) # NEW
        if self.media_type == 'movie': Thread(target=self.process_movie_threads, args=(self.source_dict,)).start()
        else:
            self.season_packs, self.show_packs = pack_enable_check(self.meta, self.season, self.episode)
            if self.season_packs:
                self.source_dict = [(i[0], i[1], '') for i in self.source_dict]
                pack_capable = [i for i in self.source_dict if i[1].pack_capable]
                if pack_capable:
                    self.source_dict.extend([(i[0], i[1], ls(32537)) for i in pack_capable])
                    if self.show_packs: self.source_dict.extend([(i[0], i[1], ls(32089)) for i in pack_capable])
                    shuffle(self.source_dict)
            Thread(target=self.process_episode_threads, args=(self.source_dict,)).start()
        if self.background: _background()
        else: _scraperDialog()
        sleep(200) # WAS 500
        self.final_sources.extend(self.sources)
        self.process_duplicates()
        self.process_filters()
        return self.final_sources

**Comment by Tikipeter** [comment]
You've had no issue since doing that?

Adding a sleep is perfectly acceptable coding practice when dealing with Kodi. You'd be amazed the things it fixes lol.

I'll plug it into Fen and see how we go.

Thanks mate. Appreciate it. 💯 )

**Comment by kodifitzwell** [comment]
yeah, kodi seems to be weird that way. lol

well from **_scraperDialog** I started logging *len_alive_threads = len(info)* and normally it counts down from however many sources enabled.  during my rapid scrape test it would randomly just start at 0 and thus "remaining providers: +0."  so I followed it upwards to *info = [x.getName() for x in threads if x.is_alive()].*  then obviously the following chunk:

    threads = []
    self.threads_append = threads.append
    sleep(100) # NEW
    if self.media_type == 'movie': Thread(target=self.process_movie_threads, args=(self.source_dict,)).start()
    else:
        self.season_packs, self.show_packs = pack_enable_check(self.meta, self.season, self.episode)
        if self.season_packs:
            self.source_dict = [(i[0], i[1], '') for i in self.source_dict]
            pack_capable = [i for i in self.source_dict if i[1].pack_capable]
            if pack_capable:
                self.source_dict.extend([(i[0], i[1], ls(32537)) for i in pack_capable])
                if self.show_packs: self.source_dict.extend([(i[0], i[1], ls(32089)) for i in pack_capable])
                shuffle(self.source_dict)
        Thread(target=self.process_episode_threads, args=(self.source_dict,)).start()
    if self.background: _background()
    else: _scraperDialog()
    sleep(200) # WAS 500
    self.final_sources.extend(self.sources)
    self.process_duplicates()
    self.process_filters()
    clear_property('fs_filterless_search')
    return self.final_sources

ultimately idk if that is **the** fix.  I also see the threading down in the *process_\*_threads* functions.  adding the *sleep(100)* eliminates the start at zero, but sometimes the log shows *len_alive_theads* countdown from "1, 2, 1, 0" when normal countdown should be "2, 1, 0."  seems like a threading/timing issue, but my python/kodi knowledge is remedial.

**Comment by Tikipeter** [comment]
Ah, the len of alive threads will quite often go down, then up again.

The scrapers will start one by one, so usually you would do something like this:
```
for i in source_dict:
	provider, module = i[0], i[1]
	self.threads_append(Thread(target=self.get_movie_source, args=(provider, module), name=provider))
[i.start() for i in self.threads]
```
But..... it takes time for those scrapers to all be added to `self.threads` and then after that all be started. So instead, we do:
```
for i in source_dict:
	provider, module = i[0], i[1]
	threaded_object = Thread(target=self.get_movie_source, args=(provider, module), name=provider)
	threaded_object.start()
	self.threads_append(threaded_object)
```
That will start each scraper immediately after it is added to the `self.threads` list. No wait for them all to be added, and then starting them all at once.

This means the active scraper count will go both up and down near the beginning of a scrape, as some scrapers take longer to instantiate.

It's done this way to speed up the start of the scrape, instead of instantiating each scraper at the same time after appending them all to the threads list, and waiting until that happens to start scraping.

**Comment by kodifitzwell** [comment]
cool, so maybe that sleep after *self.threads_append = threads.append* is the fix then.  as soon as I comment it out (mine and Fen) I start randomly getting the "remaining: +0" AND *len_alive_threads* starts at 0 and never logs again for that scrape.

thanks again!
