### ISSUE TITLE
Not an issue it's a Request

### ISSUE THREAD

**Issue by Sovilor** [Tikipeter/repository.tikipeter#4]
Hello, i like your addon its the most solid and fastest Exodus fork.

My problem is: I'm using (Aeon Nox: Silvo) skin, the text in search results list is huge, 
for example one line is showing only (External | 1080 | RD | GLODLS), it would be way better if we can see the whole info line.
So please give us an option to change the text size or the search results list style.

One more thing, would you please contact Wako dev to have Fen added to the (open on kodi) list.
Thank you.

**Comment by edb64** [comment]
There is a view type setting for the results list. I have mine set to Big List on xonfluence skin and looks good. Maybe External/Internal could be abbreviated to Ext/Int?

**Comment by Sovilor** [comment]
Honestly i don't know how the search results list looks on other skins because i only use Aeon Nox: Silvo, and it's really huge with the view type setting set as list.
I hope you consider adding an option to change the text size, no Exodus forks has that option,
And yes of course, External/Internal to be abbreviated to Ext/Int is better.

Thanks for your efforts.

**Comment by flhthemi** [comment]
> Honestly i don't know how the search results list looks on other skins because i only use Aeon Nox: Silvo, and it's really huge with the view type setting set as list.
> I hope you consider adding an option to change the text size, there is no Exodus fork has that option,
> And yes of course, External/Internal to be abbreviated to Ext/Int is better.
> 
> Thanks for your efforts.

You can get a "Slim List" view in the Silvo mod. Open skin settings go to Advanced then click on "List View Layout" select Slim List.

**Comment by Tikipeter** [comment]
Hi Sovilor (and others).

Thanks for the kind words about Fen. I should point out it is not an Exodus fork though, but that seems to be the description going around so fair enough. :) :) I originally made it as a Furk add-on, then added Easynews and finally the external Exodus type scrapers.

Unfortunately I cannot help you with your problem. An add-on has no control over text size or anything else to do with the way a skin displays the information it is sent from an add-on. The only way to control that is to code entire windows and dialogs with all the .xml files and graphics needed and then include that with the add-on (Seren does this, as does Gaia).

That is a lot of work, and it's been in my too hard basket for a long time. I doubt it will come out of that basket any time soon.

Aeon Nox: Silvo uses MASSIVE fonts. I just installed it to see what you are talking about.  As flhthemi stated, your best bet is to change the List view layout to 'Slim List'.

Sorry. :( :(

**Comment by flhthemi** [comment]
This has become a favorite addon for me. I like that I can change/hide menu items! Such a great option!

I had to roll back to 1.5.20 as .21 would scarpe, find links but when selecting a link to play didn't seem to be handing it off to the player. It just would stay busy until I hit the back button then would return me to the found list. Going back to .20 allowed things to work again.

But man, great work! Just hope you can stay out of the way of....you know what.

**Comment by Sovilor** [comment]
First: your efforts are really appreciated and with your skills Fen looks promising.
Second: thanks for the info, i just thought about asking you to consider that option so Fen will have it's own search result list view like Seren and Gaia.
Last: sorry for typing (Exodus fork) but as you said it's in the description of Fen every where :)

Thank you.

**Comment by Tinuz97** [comment]
A great way for Aeon nox is 'multi line' for the sources links,like Venom addon has.
With multi line you get 2 lines instead of one, so you can read everything at the sources results, without scrolling. 

Maybey you could add that @Tikipeter ?
