### ISSUE TITLE
Debrid Colour setting

### ISSUE THREAD

**Issue by JFG1000** [Tikipeter/repository.tikipeter#400]
Hey would it be atall possible to implement a setting to fen that allows us users to change the colour of each debrid service when viewing results, for an example in the results window we could set real debrid to say a blue and premiumize to a yellow so it's abit of a clearer indication 🙌🏻 many thanks for all your work mate

**Comment by Tikipeter** [comment]
I'll have a think about this, but a similar feature  (highlight based on quality) was recently removed.

**Comment by Tikipeter** [comment]
![screenshot00000](https://user-images.githubusercontent.com/28930002/110815508-9ccd8f80-82de-11eb-804f-463f77019934.png)

It would look like this above. What do you think? I'm still trying to decide. It looks too "busy" I think for me, but I could just set all the debrids to the same color and that would be OK for my setup.

**Comment by JFG1000** [comment]
I think it looks great mate

**Comment by Tikipeter** [comment]
Done for next update.

Default highlight colors will be as in picture below.
Change highlights in Settings->External Scrapers->Color Highlights.
There is a setting to toggle between highlighting based on Scraper (Hoster/Torrent) or Provider (RD/PM/AD). Scraper is default so it will need to be changed.
![screenshot00000](https://user-images.githubusercontent.com/28930002/110834547-c6dc7d00-82f1-11eb-9072-1201730d468a.png)

**Comment by JFG1000** [comment]
This is brilliant mate thankyou!
