### ISSUE TITLE
Setting to ignore Dolby Vision

### ISSUE THREAD

**Issue by Minefield247** [Tikipeter/repository.tikipeter#401]
I was wandering if it would be possible to add a setting to allow users to ignore Dolby Vision encoded files (they appear to have DV in the title). There appears to be no fallback so if you don't have DV compatible gear you just get the audio. For test purposes most/all of the WanderVision series has DV files. Thanks for the awesome add-on.

**Comment by Tikipeter** [comment]
Too specific a setting I'm afraid.
