### ISSUE TITLE
Fen has stopped displaying results

### ISSUE THREAD

**Issue by sklop** [Tikipeter/repository.tikipeter#402]
Hi, 
After an update fen has stopped showing results for me.  Its like the window is there, but I can't see it.  II can click up and down and I hear the select sound change happening. Sometimes, if I get luck I can select it and the video will play.  I'm running on an Nvidia shield pro.   This happens if I navigate to a TV show through one of the TV show menus (like Next Episodes).  If I access a show via the services menu everything works fine.  What is the best way for me to troubleshoot?

Thanks!

**Comment by Tikipeter** [comment]
Go to settings->Results and re-select a setting for "Results Display".
