### ISSUE TITLE
takes a few tries before a movie plays [Easynews]

### ISSUE THREAD

**Issue by crowruin** [Tikipeter/repository.tikipeter#403]
Im not sure if this issue is on Easynews but Ive been running into this where it takes a good amount of tries before the file finally plays. I tried clearing cache + restarting Kodi but it still happens.

this happens on my Shield and PC (not a big deal on the PC since I barely use Kodi on it)

https://paste.kodi.tv/otujatapif here is the log for my Shield TV

**Comment by Tikipeter** [comment]
Unfortunately it's an Easynews issue, and it's been getting worse for a while now.

**Comment by crowruin** [comment]
damn I had a feeling it was EN well thanks for getting back to me.......loving FEN!
