### ISSUE TITLE
Bug? - Fast forwarding to end doesnt mark item as watched

### ISSUE THREAD

**Issue by ReaLx3m** [Tikipeter/repository.tikipeter#41]
Some movies/shows have very long credits and i fast forward(using up arrow for big jumps) to the end in hopes it will be marked as watched but no luck there, it gets flagged with the "in progress" icon.
There used to be an option to set the percentage of length of movie/tv show passed that would mark the item as watched, and because of the reason mentioned above i would have that set to 75-80% and it worked perfectly. Cant seem to find that option anymore.
Any chance of returning it to FEN ? Or maybe if possible make it when fast forwarding to the end it would be detected as 100% of the length so it correctly marks items as watched.

**Comment by Tikipeter** [comment]
If you skip right to the very end i.e. there's no playback left after finishing the skip, then the player can't register a new point of playback. Skip to nearly the end instead.

**Comment by ReaLx3m** [comment]
Thats basically what im doing for the time being , bit it can be a hit or miss, especially with short shows 10/20 minutes its easy to overshoot. Other option is to do it in small increments like 1-2 clicks, which needs to be done multiple times not to overshoot and gets pretty annoying.
Is it out of the question for you returning the option of  % selection?

**Comment by Tikipeter** [comment]
![screenshot00000](https://user-images.githubusercontent.com/28930002/192071611-f0aea1e9-5d96-41bb-a6ee-a8bdbaa6bdb6.png)


Next update.
Set Watched range: 65 - 95 %
Set Resume Point range: 1 - 35 %

**Comment by Tikipeter** [comment]
I don't think it will mess with Autoplay Next Episode, but if it does I will have to remove it. Pretty confident it will be fine though from looking at the code.

**Comment by ReaLx3m** [comment]
Awesome to hear, hopefully they get along :).

Thanks
