### ISSUE TITLE
TikiScrapers 

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#41]
i noticed that hoster 300mbfilms stopped working with the latest update.
And Torrents scrapers: Glodls, Limetorr,Torrdown.

Are those not compatible after the latest update? (did something changed?),because before the update they did work, could you take at look at it if you have some time?

Thx again :)

**Comment by Tikipeter** [comment]
I'll have a look.........

**Comment by Tikipeter** [comment]
I'll push an update soon to fix this.

**Comment by Tinuz97** [comment]
Thx 🍻

**Comment by Tinuz97** [comment]
I am fast with checking, lol.
They work again, thx 👍

**Comment by Tikipeter** [comment]
You are fast!!!
