### ISSUE TITLE
No Results

### ISSUE THREAD

**Issue by XAT93** [Tikipeter/repository.tikipeter#410]
Scraping shows and movies ends with no results.

Log: https://paste.kodi.tv/royuzewije

Fen 1.36c on Kodi Matrix on a Mi TV Stick

Edit: errors on GetDirectory and CGUIMediaWindow

**Comment by Tikipeter** [comment]
Probably best to hold off posting issues until I have released a tested K19/Py3 version of Fen (which will happen if I can ever get home from work today). Hint: the vetsion you are using is not it.

**Comment by XAT93** [comment]
Understood. Thank you for your work. I will try to help on creating a spanish language pack probably this week.
