### ISSUE TITLE
Easynews account info error

### ISSUE THREAD

**Issue by sasagr** [Tikipeter/repository.tikipeter#413]
The latest version (1.8.37) is finally out and supporting Matrix. Thanks Tiki.
I found only one issue so far... it does not read my EN account info, though it scrapes it.
Here the log 
http://paste.kodi.tv/exasegipap 
though I did not find a clear error, but it comes on the screen as " Error cannot unpack non-iterable NoneType object".
My account type is 
Account Type | $6.99 July 4th 2020 Exclusive Upgrade
Maybe the Api does not recognize this special offer?

**Comment by Tikipeter** [comment]
Fixed for next update. :) :)
