### ISSUE TITLE
Movie collections [REQUEST]

### ISSUE THREAD

**Issue by ivarbrandt** [Tikipeter/repository.tikipeter#42]
I'm not too sure how to word this so please bear with me.

I have a lot of movies that belong to movie collections within my Trakt Movie Collection. For example the Harry Potter movies, Fast and the Furious movies, Alien movies, Mission Impossible movies etc. 

I was wondering if you could please add a menu item within the root Movies menu for only movie collections. This would show movie collections that exist in my Trakt Movie Collection whether or not I have collected all of the movies in the movie collection. So let's say I have only one Harry Potter movie in my Trakt Movie Collection. In the menu item that I'm proposing, the Harry Potter collection would show up as one item and if I clicked on it, it would show all the movies in the collection (the same way when using the SEARCH: Movie Collection (TMDb) function in the root Search menu). 

This new menu item would follow the view type set for Movies in the Tools - Set views setting.

Also when searching through SEARCH: Movie Collection (TMDb), please add the ability to add entire collections to the Trakt Movie Collection and Trakt Watchlist. This is more of a bonus so I'm completely fine if this is not possible.

**Comment by xyzfre** [comment]
In Fen there’s a settings called Extras if you enable this you can choose by default for Movies so when you click on it ,,it will show you the plot (Collections)  recommendations etc… just a little work around and sometimes I find things didn’t even know existed lol GREAT feature ,, Fen is AMAZING thank you @Tikipeter for all your great work

**Comment by ivarbrandt** [comment]
Yes I am aware of Fen Extras. It’s one of the many features that makes Fen the best. 

What I’m proposing expands on that functionality. It would ALL of the movie collections in one list that every single movie in your Trakt Movie Collection may belong to 😃

**Comment by ivarbrandt** [comment]
EDIT: I've been thinking about this and I noticed that TMDb has movie collections with just one movie in them. So this proposed menu item should only show movie collections that have more than 1 movie in them.

**Comment by Tikipeter** [comment]
Let me say firstly that I do like this idea.

Without looking into it yet, I'm pretty sure the main issue will be that Trakt does not provide info on whether a movie is part of a Collection. If I'm right, that will make doing this that much harder. It would also make the list of available Collections load much slower, especially on the first instance if none of the movies have cached metadata from TMDb.

In saying that, I have a fair idea what would be needed to get this up and running, and I'll start having a good look at it tomorrow, time willing.

If I can get it working OK, and it's not TOO slow, then I'll include it in the update after the next one, which is due tomorrow.

**Comment by ivarbrandt** [comment]
I'm glad you like the idea!

I may be out of my depth here so please let me know if what I'm about to say is wrong.

You're right that Trakt doesn't provide whether or not a movie is part of a Collection. TMDb does though. And since most Trakt metadata for movies comes from TMDb, and I'm pretty sure Trakt stores the TMDb ID, couldn't you use the ID from Trakt and cross reference it to the TMDb database to determine whether or not the movie belongs to a Collection?

Thanks for giving this a shot. I appreciate you.

**Comment by Tikipeter** [comment]
Yep, that would be how the process starts....

**Comment by ivarbrandt** [comment]
...so how does the process end? I'm asking because I know a tiny bit about coding and I'm curious about your approach.

That and I really want this to work.

**Comment by Tikipeter** [comment]
* Get the list of movies in your collection from Trakt.
* Get the metadata from TMDb for each movie using the tmdb ID number provided by Trakt.
* From the metadata, check every movie and if it's a part of a collection, add the collection ID to a list, checking first to make sure that collection id is not already in the list.
* Get the metadata for each Collection from TMDb using the collection ID's in the list.
* Display the Collections.

That's without looking at this, which I'm about to do now I'm home from work. But that should be what's needed.

**Comment by Tikipeter** [comment]
If Trakt provided even basic info as to whether each movie was part of a Collection, then I could get away with only getting metadata for those specific movies, instead of having to get metadata for EVERY movie right at the start. But you have to work with what you've got.

**Comment by ivarbrandt** [comment]
Thanks for sharing your thought process.

I was looking at the Trakt API docs and I was hoping that you could use `?extended={level}`: `full` or `metadata` but none of those contain any movie collection information. Trakt does have official lists that they use for movie collections but I don't see how to call them anywhere in the docs.

I now understand where you're coming from. I just hope it's not too slow.

**Comment by Tikipeter** [comment]
Firstly a needed compromise:
* This new menu needs to be within the My Lists->TRAKT: Collection path. It needs to be there so as to maintain consistency, as all the other collection related menus are in there as well. Fen's arranged this way so you can grab something from there for example, and place it inside your root Movies menu yourself. If the menus are customizable then they need to be organized more in groups, and then the user can pick and choose what they want where they want it.


Some important points:

* Menu name for the list? Issue is it's a Collections menu of your Trakt Collection. i.e. TRAKT COLLECTION: Movie Collections. Any idea how it can be named to make sense and not sound ridiculous? Maybe TRAKT COLLECTION: Movie Collections is good enough.
* Should the list of Collections be available to be paginated? Unfortunately pagination won't help with speed of loading, so the only consideration would be whether it's worth paginating or not for usefulness.
* Sorting of the Collections pretty well needs to be alphabetical. Nothing else will really work.
* Collections with only 1 RELEASED movie will be ignored. For example if the Collection has 2 or more movies, but only 1 is released, then it won't be shown.

Good news it is up and running, and on my PC it wasn't too slow to be handy. Of the 438 movies in my Trakt Collection, I had 93 movies that were part of a "Collection", and after filtering out the instances of only 1 released title, there were 78 final collection items.

![screenshot00000](https://user-images.githubusercontent.com/28930002/192403878-48313aca-579e-49c9-ace2-8b03b7e3f82d.png)

**Comment by ivarbrandt** [comment]
My goodness that looks beautiful!

In regards to the compromise:

- I build my own Movie and TV sections comprised of different parts of Fen so putting this new menu in the TRAKT: Collection path makes sense and is cool with me.

As for the points you raised:

- I was thinking of a name for the new menu as well as to not cause confusion. The best I can come up without sounding too ridiculous is TRAKT Collection: Movie Sets. What do you think?
- As for pagination, if it doesn't speed anything up, I don't really see the point. I'm not really sure how paginating would make it more useful. Can you please provide an example here?
- Agreed, sorting should be alphabetical.
- That's perfect, single movie sets aren't really sets lol.

I have one question and one request:

- Do the movie sets shown in the new menu item contain ALL of the movies in that set? Or does it show just the movies you have in your TRAKT: Collection that belong to a movie set? I ask because I hope that they contain all of the movies in the collection, whether or not all of them are in the TRAKT Collection.
- Also please let all artwork be available like everywhere else in Fen. (Clearlogo, ClearArt, Landscape).

Again thanks so much! Thank you for asking for my input. It looks the exact way I envisioned it! Thanks so much for adding this in! I'm super excited to test drive this new feature.

**Comment by Tikipeter** [comment]
>TRAKT Collection: Movie Sets. What do you think?

Yep. I like that best.

>As for pagination, if it doesn't speed anything up, I don't really see the point. I'm not really sure how paginating would make it more useful. Can you please provide an example here?

No, I can't provide a good example for using it to be honest. I thought maybe you might want it. 

>Do the movie sets shown in the new menu item contain ALL of the movies in that set?

Yes, once clicked on ALL the movies for that set will load, whether currently in your collection or not.

>Also please let all artwork be available like everywhere else in Fen. (Clearlogo, ClearArt, Landscape).

There's no Clearlogo, Clearart or Landscape for the collection items. TMDb doesn't provide them. :(

>can I add the WHOLE movie set to my TRAKT: Collection through the context menu

I've not done that yet, but I saw it in your original post so hopefully I can get that done.

**Comment by ivarbrandt** [comment]
> Yep. I like that best.

Cool. Me too!

> I thought maybe you might want it.

I appreciate that. No need though if it doesn't speed things up. That's the only reason I use pagination.

> TMDb doesn't provide them. :(

Nooo what a bummer. I think Fanart.TV does. Could you please implement that?

> ALL the movies for that set will load, whether currently in your collection or not.
I saw it in your original post so hopefully I can get that done.

Perfect. Thank you.

**Comment by Tikipeter** [comment]
>I think Fanart.TV does.

For Collections? Are you sure?

**Comment by ivarbrandt** [comment]
Yes I'm sure. I don't know if you can access them through the API but I have definitely seen Clearlogo, ClearArt, and Landscape for collections.

Here's an example for the Avengers Collection and Harry Potter Collection:

https://fanart.tv/movie/86311/the-avengers-collection/

https://fanart.tv/movie/1241/harry-potter-collection/

Also, Landscape = Movie thumbs in Fanart.TV
