### ISSUE TITLE
Enhancement : API language switch. 

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#42]
No idea if it is asked before, but is it possible (in the future) to add some sort of API language switch?
So that in my situation I can switch it to Dutch language?
No idea if API language is the correct term, it is the Information for TV Shows, Movies, it is English now that information. 
Dutch (or maybey other languages) would be nice also. 

Thx 🙂

**Comment by Tikipeter** [comment]
I'm going to look into this for you Tinuz97. No eta though as It could be a big job or an easy job. :)

**Comment by Tikipeter** [comment]
This should be in latest update. I've only included languages supported by TVDb API v2 (TMDb support a lot more), if there's a language needed that's missing I can add it and hope for the best from TVDb.

Any issues let me know (there may well be some).

**Comment by Tinuz97** [comment]
Wow, just wow.
It works wonderfully 😍.
Thx!

**Comment by Tinuz97** [comment]
Hmz, i tested and compared a little further, it looks the fallback (if that is the correct english term) does not work 100%.
You can test it as a example with movie Holiday in the wild (2019).
API set to Dutch , but no information available (stays empty).
Also tested it Tempest as a example,if no Dutch information available, it returns English API info for this movie.

Could you test it also? (don't forget to switch the API to Dutch).

Thx :)

**Comment by Tinuz97** [comment]
PS:
If i set the API bij to English, the information is visible.
So it looks if it can't find Dutch language,it does not switch to English (as fallback)

**Comment by Tinuz97** [comment]
Also seeing some errors with the new log viewer (api on English for now).

https://tinuz97.stackstorage.com/s/LYnlTZltcHxnRtw

**Comment by Tinuz97** [comment]
I think you fixed it in the meta module today?
Could not see the changelog (changelog is version before this one), but it seems that it does fallback to English now, if it can't find Dutch language (description for movies) . 

So for movies it does work 100% now, only TV shows still shows empty information (of dutch is not available), but movies are great now 👌

**Comment by Tikipeter** [comment]
I'm sorry Tinuz97, I didn't even see your comment from 7 days ago. I haven't looked into this issue, so I shall have a good look tomorrow and sort out what is going on with it. I will reopen this issue to keep track of it. ;)

**Comment by Tinuz97** [comment]
No problem, but for movies it does work after the latest update (no idea if you changed something, but 1 version before the latest it did not work either, the fallback to English).

Only TV shows the (I just call it fallback, no idea if it is the correct term) is not working, it shows Dutch if available, if Dutch is not available, the info stays empty. 

Thx as always :1st_place_medal:

**Comment by Tikipeter** [comment]
Hi Tinuz97.

Can you give me one example TV Show where this is happening. I cannot get it to not work. For me, there is always an English fallback.

**Comment by Tinuz97** [comment]
Here are a few for testing:

Last week tonight with john oliver
Madam Secretary
God friended me
Bob's Burgers
Legacies
90 Day fiance
The real housewives of atlanta
Black Lightning
Ancient Aliens
Keeping up with the Kardashians.


Just a few in exact order with the scrolling i do in TV Shows, and then Trending menu,.

**Comment by Tikipeter** [comment]
Yep, definitely all of them are affected! Leave it with me. 👍

**Comment by Tinuz97** [comment]
So these are in exact scrolling order in TV Shows, Trending menu.
So the last i did scroll to is Keeping up with the Kardashians.

All others do fallback to English in that row.

**Comment by Tinuz97** [comment]
`yes, info tv show level. 
For movies it does work perfectly `

**Comment by Tikipeter** [comment]
Hopefully there will be some improvement with this issue in the next update (Tikimeta v.1.1.22).

There's also some good news with regard to TVDb now providing fallback to ENG for plot info automatically. The v2 API that Fen uses didn't do this before, so I had to make double the calls to the TVDB API to also fetch ENG metadata when another language was set, and then plug any holes in the foreign language data with the ENG data. Hopefully I won't have to do this anymore.

The bad news is that the TVDb API seems MUCH slower when querying for a language other than ENG. It seems they don't have it cached as well. This makes first time browsing into seasons slower (sometimes MUCH slower if the TV Show has over 100 episodes), and will also make first time browsing into themed episode lists (Next Episodes etc) slower. I originally thought this was due to all the extra calls I had to make, but even now that I don't need to make those extra calls, it is still much slower than when I have language set to ENG. It seems there's nothing I can do about this; it looks like it's purely an API performance issue. The TVDb v1 API doesn't seem to suffer from the same problem. :(

**Comment by Tinuz97** [comment]
I quickly tested above TV Shows, and it looks that it is working fine now, some in Dutch that where empty before, and others that where empty are showing English now, and the ones that are available in Dutch, are showing Dutch language properly.

Thx for the fix (you must think, how is he so fast every time, lol)

**Comment by Tinuz97** [comment]
Also it is fast enough, I don't realy notice that many difference, or did you tweak the performance (because you did say it is slower before), for me it is not realy noticeable, love the fix. ❤️

**Comment by Tinuz97** [comment]
Hmz @Tikipeter 

TV Shows like i told before working great now, but i tested movies a little better (latest version Fen from a few minutes ago) ,and has the same issue as TV Shows before (at movie level).

There is zero fallback to English if Dutch is not avaiable (exact same issue as TV Shows had before)

Here are a few to test:

Doctor Sleep.
Noelle.
Danger Close: The battle of Long Tan.
Primal.
The death and return of Superman.

**Comment by Tinuz97** [comment]
This is weird, now it is loading again 😅

**Comment by Tinuz97** [comment]
Nope (I checked wrong movie), so bug (for me) still available for movies unfortunately (see message above for the movies I tested)

**Comment by Tikipeter** [comment]
Hopefully fixed with tikimeta v.1.1.23.

Clear Meta Cache to test. :)

**Comment by Tinuz97** [comment]
i am sitting ready,F5 finger lol.

**Comment by Tikipeter** [comment]
Ha! Probably a couple of hours away.....

**Comment by Tinuz97** [comment]
Got Fen 1.5.7.1(update successfully), but meta does not want to update, keeps saying 1.1.22 while 23 is available (I see the module in updates).

On my computer I have this issue, and my android phone. 
Downloaded zip manually from github, install from zip, also does not want to update, any idea? (never experienced something like this).

**Comment by Tinuz97** [comment]
(I can't find a error in the log for that)

**Comment by Tinuz97** [comment]
Disabled Fen, removed meta module, installed the zip (23 version) manually, enabled fen, and again a pop-up for a update (1.1.23), weird 😅

**Comment by Tinuz97** [comment]
But it does work, maybey something in the numbering is wrong, it still says 1.1.22, but the fallback is working for as a example Noelle movie (that was broken before). It does fallback to English fine.

So my guess something with version numbering is not ok?

**Comment by Tinuz97** [comment]
Find the 'issue'.

The addon.xml for tikimeta says id="script.module.tikimeta" version="1.1.22"
So if you make it id="script.module.tikimeta" version="1.1.23" it should update for other users.

**Comment by Tikipeter** [comment]
Should be sorted now (1.1.24 pushed).

**Comment by Tinuz97** [comment]
Yes, sorted.
Tested both TV shows and Movies, both are working fine now with fallback to English, if Dutch language is not available, thx 🍺
