### ISSUE TITLE
Scraping box comes up very briefly thern sas no results

### ISSUE THREAD

**Issue by mrXoo** [Tikipeter/repository.tikipeter#422]
Hi there,
I am having an issue where the scraping box comes up for like 0.5 of a second and it returns no results for everything. My RD account is good. It did actaully play Raya and the last dragon but nothing else after that.
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/6123755/kodi.log)

**Comment by Tikipeter** [comment]
Are you trying to play the media directly through Fen, or using TMDbHelper?

**Comment by mrXoo** [comment]
Hi there, Thanks for the speedy reply. I was trying through the addon directly. 
Resetting the scrapers seems to have fixed it. Not sure what i clicked though

**Comment by Tikipeter** [comment]
Possibly. I can't know without seeing what was happening (the log showed nothing).
Glad it's sorted now though.
Open a new Issue if it happens again.

**Comment by mrXoo** [comment]
Hi again,
Same issue again this time I couldnt fix it until I copied over my settings.xml file from another machine.
Could it have something to do with the "Reuse language invoker" or something like that. Was working fine until that bax came up and I selected YES. It came up again and I selected NO and it still seemed good. Why does that box come up anyway?
