### ISSUE TITLE
Kodi 19 Fen through tmdbplayers not working

### ISSUE THREAD

**Issue by deyooluv** [Tikipeter/repository.tikipeter#424]
Fen scrapes through tmdb helper player fine. However there is no playback after selecting any of links from the displayed result window. Fen works fine without going through tmdb helper.
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/6126738/kodi.log)

**Comment by Tikipeter** [comment]
I'm afraid I'm not the dev of TMDbHelper.

**Comment by deyooluv** [comment]
Thank you.
