### ISSUE TITLE
Easynews playback not stable

### ISSUE THREAD

**Issue by naudski** [Tikipeter/repository.tikipeter#425]
I'm having problems with playback from Easynews. Sometimes it works but often it doesn't. I'm using the v2 API in FEN because I only get results using the v2 API. Strangely enough playback works better with the v3 API?! But switching back and forth is not ideal ;-)
In the kodi log I can see the error: ERROR <general>: CCurlFile::FillBuffer - Failed: Timeout was reached(28)

Here you can find the total log: https://paste.kodi.tv/yonapoqake.kodi

Is this a FEN issue? Is this an Easynews issue or do I need to tweak my advanced settings xml?

By the way, I love your addon and thanks for your great work on it!

**Comment by Tikipeter** [comment]
Unfortunately it is an Easynews issue.

I found switching to a US server on Easynew's website dettings helped with this issue. It might be worth a try for you too.

As for Fen; leave EN at v2.

**Comment by naudski** [comment]
Thanks for the tip! I will try that.

**Comment by naudski** [comment]
Setting it to US servers didn't fix it but setting it from Automatic to Europe did.

Thanks!
