### ISSUE TITLE
Request for the custom search paths (People: Movies, TV Shows, Movies Directed) for the "Fen" add-on

### ISSUE THREAD

**Issue by ShibajiCh** [Tikipeter/repository.tikipeter#426]
Hi @Tikipeter,
Could you please provide the custom search paths for:

People: Movies
People: TV Shows
People: Movies Directed

for the "Fen" add-on similar to the below pages?

#351 
jurialmunkey/skin.arctic.zephyr.2#36

I'd like to implement them in the default search for the Arctic Horizon skin.
Thanks in advance!

**Comment by Tikipeter** [comment]
I'll have to wait until I'm home to get these for you. I can't quote them from memory. About 5 hours I'll be.

**Comment by ShibajiCh** [comment]
> I'll have to wait until I'm home to get these for you. I can't quote them from memory. About 5 hours I'll be.

Fine @Tikipeter. No problem. I'll wait for your update. Thanks!

**Comment by Tikipeter** [comment]
I've got bad news I'm afraid. You cannot use the three paths you want to use for Jurial's search feature, because the paths require the actor's tmdb_id and the skin would be looking to receive the actors name.

**Comment by ShibajiCh** [comment]
> I've got bad news I'm afraid. You cannot use the three paths you want to use for Jurial's search feature, because the paths require the actor's tmdb_id and the skin would be looking to receive the actors name.

Hi @Tikipeter,
Oh okay. So just entering the actor's name in the search won't work? In that case I guess I have to search from within the Fen add-on only, right? Fine. If that is the only solution then I can live with it. Earlier you provided me with custom search paths for both movies and TV shows in Fen which I've been using successfully in the Arctic Horizon skin search, so I thought the People search also might be similar to those. However, if there's no solution then you can close this issue ticket. Thanks a lot for the great work!

**Comment by Tikipeter** [comment]
You can use a url string to land ON this page:
![screenshot00000](https://user-images.githubusercontent.com/28930002/111089071-49796c80-857e-11eb-8227-50b8a64f0381.png)

If that's good enough, the url would be:
```
plugin://plugin.video.fen/?mode=people_search.search&actor_name=
```

That is the url for SEARCH: People.

Give it a try and see if it will do.

**Comment by ShibajiCh** [comment]
> @ShibajiCh
> 
> You can use a url string to land ON this page:
> ![screenshot00000](https://user-images.githubusercontent.com/28930002/111089071-49796c80-857e-11eb-8227-50b8a64f0381.png)
> 
> If that's good enough, the url would be:
> 
> ```
> plugin://plugin.video.fen/?mode=people_search.search&actor_name=
> ```
> 
> That is the url for SEARCH: People.
> 
> Give it a try and see if it will do.

Hi @Tikipeter,
It's not exactly what I wanted, but still it is quite helpful and will do the work. At least something is better than nothing. Thanks for all your help! You can close this issue ticket.
