### ISSUE TITLE
Trakt Sync Settings

### ISSUE THREAD

**Issue by ronfrankhill** [Tikipeter/repository.tikipeter#427]
Is it possible in the section call My TV progress episode to have in Fen settings for trakt the option to remove a episode or episodes already watched automatically in progress list. Instead of constantly going into tools to clear trakt cache to update trakt to remove seasons or episodes already watched in Fen. Just asking.

**Comment by Tikipeter** [comment]
Are you sure you have the correct add-on?
Fen does not have a `My TV progress episode` menu item.
Please re-check which menu item and/or add-on you are referencing.

**Comment by ronfrankhill** [comment]
TV Shows>In Progress TV Shows

**Comment by ronfrankhill** [comment]
If it could have in Fen add-on a settings to automatically delete episodes already watched in trakt.

**Comment by Tikipeter** [comment]
That menu item shows TV Shows, not episodes. I think there is a missunderstanding here.

It sounds as if you want a list of next episodes to watch. That menu item is `Next Episodes`.

**Comment by ronfrankhill** [comment]
My mistake . Sorry. If you click on the section call TV Shows. After you click it. Look for the section call In Progress TV Shows. It will bring up all the episodes that the user is watching from trakt.tv

**Comment by Tikipeter** [comment]
I'm saying it doesn't do that. It brings up a list of TV Shows where you have watched at least one episode, but have not watched all episodes.

Please click on "Next Episodes" and see if that is what you want.

**Comment by ronfrankhill** [comment]
Okay. Thanks. I will do that. Thank again for your assistance but also pointing me to the right section to use.

**Comment by Tikipeter** [comment]
I think it's what you are after. Let me know if it's not.

**Comment by ronfrankhill** [comment]
Okay. Thanks. I will.

**Comment by ronfrankhill** [comment]
Yes. You are right. Next Episode is what l should be using. Thanks. Another question. Is there a option to have the progress dialog in the background instead of foreground in add-on settings.

**Comment by Tikipeter** [comment]
Unfortunately not. There are plans to "fancy up" the progress, at which time I should add an option for a more circumspect  dialog. But there's no setting currently.

**Comment by ronfrankhill** [comment]
Okay. Thanks. Looking forward to that option whenever it comes available in the future.

**Comment by ronfrankhill** [comment]
I see the My Account program add-on don't have the option to install API key for OMDB http://www.omdbapi.com which might not be important.

**Comment by Tikipeter** [comment]
Nope. Not needed.

**Comment by ronfrankhill** [comment]
Okay. Thanks for providing Fen to users to use but also maintaining it daily. Base on my observation once users can get a add-on that can get links over 3 years or more. They are happy.
