### ISSUE TITLE
"NO RESULTS" On first run

### ISSUE THREAD

**Issue by mariofenech** [Tikipeter/repository.tikipeter#429]
Been having this issue for a while now..
When I first search for sources for a movie or tvshow I always get no results on the first run..even that links are found.
Then if I click again results are shown..

[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/6175170/kodi.log)

**Comment by Tikipeter** [comment]
My guess is this would be a Real-Debrid issue. Every 30 minutes RD needs a token refresh. I have no idea why they have decided to do this, but that's the way it is.

There's not much in your log, but there is a troubling error from python when Fen tries to start a new thread for the checking of cached torrents. This shouldn't be happening.

I've "tweaked" this area of code anyway for next update, and I think it may help to fix your issue.

**Comment by mariofenech** [comment]
The search does populate the numbers of links found i.e 4k,1080 etc on the search window..then after that I get the 'no results' notification and obviously no results window..then if I click same movie/episode again it even find lots more results and show results window as expected..
If I clear cache or restart same issue will happen for the same movie or episode.

**Comment by Tikipeter** [comment]
Yeah, after the progress dialog for searching is over, you are meant to then see a dialog showing the progress for Fen checking any debrid accounts you have enabled for cached status of the results. If you don't see that, then that is why it is failing on the first run. When you click the movie/episode again, that cache check has completed in the background and now the results will be shown.

If you clear the cache, then Fen needs to call that cache check again, and it will fail on first try again as a result.

Hopefully fixed next update. But it's possible from that error in your log that something else is going on (which I didn't like the sound of when I read it). Hopefully it'll be fixed.

**Comment by mariofenech** [comment]
Something else that might help...if it's a series ; only the first time I click on an episode the issue happens..the rest of episodes then work fine..
quote;  (which I didn't like the sound of when I read it) you mean is that something from my side of setup? I m running LibreElec on RPi2 with Leia 18.9

**Comment by Tikipeter** [comment]
There's an error from python's threading module `error: can't start new thread` when Fen wants to check for cached torrents on RD.
That's when Fen tries to open 1 or more threads to check RD's servers for the cached status of torrent results. I've not seen that error before, and it MIGHT be hardware related. Perhaps the Pi is hitting some kind of thread limit for some reason. Seems strange is all.
