### ISSUE TITLE
Watched option

### ISSUE THREAD

**Issue by rishisss23** [Tikipeter/repository.tikipeter#43]
Hi
After yesterday s update my tv show episodes (previous watched ones) are not getting watched 'tick' after stopping on the next episode middle. Both episodes (previous n present) showing as resume;and the previous episode still on the next episode widget;each time has to manually mark as 'watched on trakt' on next episodes widget for it to update to the new episode resume point. 

I tried multiple options on % watched;still the same.. Any suggestions?? Log is after stopping playback on the middle of new episode. Please help

https://paste.kodi.tv/uxacaqufuj

**Comment by rishisss23** [comment]
Update:My set resume point after playback%was 2..on changing it to 3;now it is working

**Comment by Tikipeter** [comment]
I'll have a look and see what's happening here.

**Comment by rishisss23** [comment]
Okk thanks

**Comment by rishisss23** [comment]
Update:Does it have anything to do with 'set resume point after playback%' because mine was at 2; when increasing that value to '5' episodes are getting watched tick. Please have a look

**Comment by rishisss23** [comment]
An update:reducing the value of 'Mark watched after (Playback%) below 90;episodes are getting ticked.
Maybe next episodes searching and marking as watched might be conflicting..

**Comment by Tikipeter** [comment]
I couldn't replicate this issue so I've made a couple of little changes that will hopefully make a difference next update.

**Comment by rishisss23** [comment]
Thank you

**Comment by rishisss23** [comment]
Hi
Eager to know when will be the next update?? I understand you are busy;thanks.

**Comment by Tikipeter** [comment]
Who said I was busy?

**Comment by rishisss23** [comment]
Update:Its working fine now;thanks

**Comment by Tikipeter** [comment]
Good to hear.

I didn't think it would make a difference honestly.

**Comment by rishisss23** [comment]
Yaa.. After update it is working fine on my side. Maybe some internal problem on my kodi
