### ISSUE TITLE
Results display 

### ISSUE THREAD

**Issue by edb64** [Tikipeter/repository.tikipeter#43]
I have started seeing the color code text in my search results instead of the results listed in the specified color. I'm sure I must have missed something as I haven't been keeping up on the issue thread. I'm using an xonfluence skin on Kodi 18.4.
![20191029_163035](https://user-images.githubusercontent.com/36031635/67807057-6f29d280-fa6a-11e9-9d04-89f5f0faa689.jpg)

**Comment by Tinuz97** [comment]
Skin issue maybey? (OK with Aeon Nox Silvo Mod).

**Comment by edb64** [comment]
It was working fine until one of the recent updates. It's been displaying like this for a little while now and I am just getting around to posting the issue.

**Comment by edb64** [comment]
Kodi 18.4 actually. No hurry, I will be grateful if you can find out what's causing this. It's really just a cosmetic issue, everything else is working great. Thanks!

**Comment by Tikipeter** [comment]
I do have an idea what is causing the problem...

**Comment by Tikipeter** [comment]
Well, it isn't what I thought it was. :(

I installed Xonfluence on Kodi 18.4, ran a search and got this...

![screenshot001](https://user-images.githubusercontent.com/28930002/67903190-10c23880-fbbf-11e9-9873-f460d93014e4.png)

It also works correctly with Multiline.

As a first step for fixing, I would clear the Internal Providers cache (Tools-->Clear List % Data Info-->Clear Internal Providers Cache). It shouldn't make a difference, but who knows.

Next, I would check the skin, and see if there are any color specific settings to do with labels. Set them to default if there are (I couldn't find any, but this skin has a lot of settings).

Lastly, I would re-set the settings for the color highlights within Fen, making sure to save settings before exiting.

If you have the time to try those things and let me know the result, I can proceed further after that.

**Comment by Tikipeter** [comment]
I found color settings for font colors in Xonfluence, but changing them didn't make Fen results stop working properly for me. I'm still at a loss, but will keep trying to make it malfunction.

**Comment by edb64** [comment]
OK, thanks for looking into it. I will see if I can find a way to fix it, while you try to find a way to break it 😂

**Comment by edb64** [comment]
It's actually doing the same thing on Kodi 18.4 and a Kodi 18.4 fork. Using 2 different builds, same result. I will continue to look for a way around this and may just try to uninstall/reinstall. 
![20191030_185042](https://user-images.githubusercontent.com/36031635/67905081-b1c0dd00-fb46-11e9-889f-63dfc64c2e5e.jpg)

**Comment by edb64** [comment]
Went for the full uninstall of addon and dependancies followed by clear addon data for uninstalled addons. Rebooted Kodi, reinstalled and setup Fen from scratch...same result. Has to be something in the skin settings that I need to change. I will continue to look and let you know if I find any success.

**Comment by Tikipeter** [comment]
OK. I am still trying to make it stuff up...

**Comment by edb64** [comment]
Reset external providers settings to default magenta / dodger blue and still no luck.

**Comment by Tikipeter** [comment]
Do other labels that are meant to be a different color, i.e. unaired episodes, show correctly?

**Comment by edb64** [comment]
Yes, they are. Will attach pic. Also attached is a pic of the results in another addon. 
![20191030_194045](https://user-images.githubusercontent.com/36031635/67907140-56461d80-fb4d-11e9-95d9-1b333d7a9367.jpg)
![20191030_193738](https://user-images.githubusercontent.com/36031635/67907144-6100b280-fb4d-11e9-8d04-7c1016c7cd4b.jpg)

**Comment by edb64** [comment]
I have results view set to Big List if that is any help. I did toggle through all of the views from within the results page but they all showed the same [color XXX] 🤷‍♂️
I hate to bother you with this... Am I the only one using xonfluence and having issues, lol.

**Comment by Mahava** [comment]
I have the same issue in 18.4 with Estuary Mod V2 skin.  I happens whenever I set a specific colour for external scrapers; but, it displays correctly when I set the colour to "No Color".  I think it broke with a recent update, but I can't be certain.

with colour set:
![image](https://user-images.githubusercontent.com/32604452/67969228-39f2c100-fbdf-11e9-90ed-388de9b9c963.png)

with colour set to 'no color':
![image](https://user-images.githubusercontent.com/32604452/67969346-7aead580-fbdf-11e9-8f39-60e9c4db77de.png)

**Comment by Tikipeter** [comment]
I'm afraid we're at a point now where I need you to try with the base Estuary skin and report back if possible.

This, to me, is a breaking error, and would stop me using the add-on, so I really appreciate your patience with trying to get it fixed. I'm just having trouble as I cannot replicate what's happening.

I'll push an update soon which has a couple of changes that hopefully will help, but I'm shooting in the dark as to what to do to fix the problem. Logically, it can only be a couple of things. But logically, it shouldn't be happening at all. So I'm a little lost. :)

**Comment by edb64** [comment]
Well, on one hand it's good to know that I am not the only one experiencing this issue 😂 Sanity restored, thanks Mahava. On the other hand I am sorry that it is making a difficult issue for Tikipeter 🤔  It's functionally still sound, but the appearance is certainly not what anyone hoped for. I have been enjoying Fen for a good while now, so I have plenty of patience to see this through. Best of luck figuring out this issue and I wish I had the skills required to help 🤷‍♂️ If there's anything that I can do to test or experiment please let me know!

**Comment by therealatreides** [comment]
Look in your external.py under lib\sources, starting around line 463+. You are closing the COLOR tag for multiline but not single line. Add in the proper if/else code to add it for single line on down through there and you got it fixed.

**Comment by therealatreides** [comment]
To help point it out a bit more, look at the section for premium highlight.

In the Else where you add [COLOR=%s], you only add the [/COLOR] to premiumClosing if multiLineHighlight is empty. If you add it, you always have to close it.

**Comment by edb64** [comment]
Thank you Mr. therealatreides! Very kind of you to help out 👍

**Comment by Tikipeter** [comment]
First of all, a huge thank you to @the realatreides !

Because my (and others) results were showing correctly, I took only a cursory glance at that section of the code, and to be honest the logic gave me a headache when I wrote it and absence had not made the heart grow fonder!!!

Because I was still not experiencing the problem, I re-wrote that section of code, hopefully making it easier for me to follow when I need to come back to it, but more importantly hopefully making it work correctly now.

I will release an update soon (v.1.5.62a) that will only have this fix.

Please someone report back if it is working after you get that update.

Thanks again to realatreides.

**Comment by therealatreides** [comment]
Just switched back to single and looking good on mine. Would wait for a few others to test and be sure.

**Comment by Mahava** [comment]
Working for me.  Thanks.

**Comment by edb64** [comment]
Just got a chance to try out the new update and happy to say that the issue has been resolved! Thanks Tikipeter and Mr. Atreides for your awesomeness 👍👍

**Comment by edb64** [comment]
Thank you!

**Comment by Tinuz97** [comment]
And still working fine for me also (aeon nox silvo mod), so the fix does not interfere with my skin :)

**Comment by Tikipeter** [comment]
Great job everyone! Thanks for reporting back.
