### ISSUE TITLE
Results discrepancies with Easynews

### ISSUE THREAD

**Issue by ReaLx3m** [Tikipeter/repository.tikipeter#430]
Not sure if its fen issue or something on the side of Easynews itself, but some movies/tv shows that are available when using the easynews search, return no results with fen.
As an example movie Dogwashers, or TV Show Soulmates. Maybe youll figure out whats actually going on.
Using V2 both on website and in fen settings, if that makes any difference.

**Comment by Tikipeter** [comment]
I see those discrepancies also. No idea why. I'll have to look into it.

**Comment by ReaLx3m** [comment]
Same with the new Tom and Jerry movie, and from around 100 documentaries i checked, around 5-10 had the issue. If you need the exact examples, i can recheck them and give you exact names if that would help you narrow it down.

**Comment by ReaLx3m** [comment]
Btw with the documentaries adding the year after the name in cases when they were actually available, returned correct result. Without the year sometimes top results were unrelated, or no results in 1-2 occasions.

**Comment by ReaLx3m** [comment]
Not related to the possible search bug, but since were here maybe you can point me in the right direction without me opening a new issue with a question.
Is there any way of masking the password for Easynews in fen myaccounts and fenomscrapers modules?

**Comment by Tikipeter** [comment]
>Is there any way of masking the password for Easynews in fen myaccounts and fenomscrapers modules?

There is not. Well, there is, but it is not coded into Fen or MyAccounts.

**Comment by ReaLx3m** [comment]
Thanks, good to know. Hopefully youll consider implementing it if not that big task, kind of bad that anyone with access to your device can see your full account info.
Should i open an issue with a request, or mentioning it here is enough for you to consider implementing it?

**Comment by Tikipeter** [comment]
The obfuscation of settings won't happen I'm afraid. Enabling that also means the input of the setting values is also obfuscated. Whilst i would also rather these values hidden, a majority would prefer to see the values they are entering to ensure accuracy when remotes are being used etc.

**Comment by ReaLx3m** [comment]
Yep, i can see now why some pople would prefer it that way.
Maybe some sort of parental control feature? Like having an option if one wants to set master password to access my settings and fenomscrapers

**Comment by Tikipeter** [comment]
Whilst I can control the access to settings for My Accounts (MA) and FenomScrapers (FS) for 2 of the access points in Kodi (via Fen's settings and via clicking on MA or FS directly), I cannot control the third way of accessing the settings (via "Information" when MA or FS is highlighted and then selecting "Configure"). So it would be a case of a false sense of security. You could still navigate to the settings via Kodi's menus.

The good news is if you are worried about someone having access to the settings, you can have Kodi itself limit access.
If you go to Settings (Kodi's settings)-->Interface-->Master Lock, you can set up Kodi to prompt for a password when entering any window to do with the "Add-on Manager" (last option in list). This will stop anyone being able to get to the settings of add-ons.

Note that it will be in effect for ALL addons, not just MA and FS. And will also affect any other interactions related to Kodi's Settings-->Add-ons menu.

Might be worth a look.

**Comment by ReaLx3m** [comment]
On first look master lock fits my bill perfectly. Thanks for the great tip.

**Comment by ReaLx3m** [comment]
Just noticed that Soulmates started appearing in the results, tested Soulmates S01E01 and S01E03. There were some new uploads of the show made 26-28 of March , and judging by the sizes its what appears in results. Though one older one uploaded 11 of February also started appearing for Soulmates S01E01, which as far as i recall correctly it didnt before. 
Not sure if it might be connected to the recent changes you made to metadata retrieval.
Maybe comparing the older to newer files uploaded might give you an idea whats going on.
Dogwashers still not available.

**Comment by ReaLx3m** [comment]
Ive had some back and forth about this with a user on reddit and did few more tests, and it became apparent that materials with flags different than US/UK are the ones not being displayed in results. In this case with Dogwashers has the Spanish flag. Does fen send the search to specifically disregard other flags to avoid possible cluttering of the results with bunch of dubs? If thats the case, maybe there could be an option under search what flags/languages to include in the results. Might be something similar to what KalAvroniev asked for [here](https://github.com/Tikipeter/repository.tikipeter/issues/445) in point 1.

As for Tom & Jerry not finding any results, it was suggested that fen has some trouble with special symbols in movie names. Is it the case? 
When searching the movie above with & in the query, i see easynews will find results with "and" in the name instead of the special character. So if above statement is true about having problems with special symbols, maybe have fen replace "&" with "and" when sending the search? Or disregard it completely as it already does for :, at least thats what it looks like its doing to me from some test searches i did, correct me if im wrong. 
Unless this is something you already know and considered, and it will open a whole new can of worms that im not aware of.

**Comment by Tikipeter** [comment]
I'll push a new update soon (1.8.46) which will include a fair few adjustments to how Fen interacts with Easynews, be it the url used for the search or the checking of relevant results after the returned data is received.

Please check if it has improved things for you (make sure both "Filter Results by Name" and "Exclude Adult Results" are OFF when testing).

I have loosened what is allowed through as a relevant/safe result by Fen, whilst still weeding out files flagged by Easynews as containing a virus or containing a password.

Fen will still remove a result from display if:
1. Easynews flags there is a virus present.
2. Easynews flags the file is password protected.
3. The file isn't a video file.
4. The file is less than 5 minutes long.

There might be a bit more to do with regards to the video files I allow in the search. Currently it is the following only:
`mkv, mp4, avi, mpg, webm`
I may need to add more to this.

If you notice discrepancies with result numbers between Fen and Easynews website, you can check the Kodi log now and see what Fen has logged as the reason for discarding a result. It will have the reason logged alongside the item that was dropped.

**Comment by ReaLx3m** [comment]
Thats great to hear, i really was right when i said that youre on fire today hehe.

I will make a list of 20 or so tv/movie that are available on easynews web search but are not displaying in fen, and retest after the update. Will let you know how it looks like.

**Comment by ReaLx3m** [comment]
So heres what i tested, first with "filter results by name" enabled then disabled.

- Tom & Jerry (2021) - no results Fen, 12 EZN.  After update 10 in Fen. With "filter results by name" disabled 10.
- Dogwashers (2020) - no results Fen, 3 EZN. After update 3 in Fen. With "filter results by name" disabled 5(2 of the added results have a different year)
- Money heist: the phenomenon (2020) - no results Fen, 2 EZN. After update 2 in Fen. 
- Marvel's behind the mask (2021) - 1 result Fen, 1 EZN. when searching without ' it becomes 5 results on ezn. After update 4 in Fen. With "filter results by name" disabled 4.
- Our Towns (2021) - 2 results Fen, 6 EZN. After update 6 in Fen. 
- Game of Thrones: The Last Watch (2019) - 1 result Fen, 2 EZN. After update 2 in Fen. 
- Metamorphosis (2018) - 1 result in Fen with year 2019 in filename, no results in EZN. Changing year to 2019 in ezn nets 11 results. After update no results in Fen. With "filter results by name" disabled 11(all have year 2019)
- Crack: Cocaine, Corruption & Conspiracy (2021) - no results Fen, 8(1 correct) EZN. With removed :, 1 result on EZN. After update 1 in Fen. With "filter results by name" disabled 1.
- Operation Varsity Blues: The College Admissions Scandal (2021) - 2 results Fen, 6 EZN. After update 6 in Fen. 
- Marvel Studios: Assembling a Universe (2014) - no results Fen,  no results EZN, removing the year nets 3 results in EZN. After update no results in Fen. With "filter results by name" disabled no results.

- Soulmates s01e01 - 4 results Fen, 9(8 correct) in EZN. After update 7 in Fen. With "filter results by name" disabled 9(8 correct)
- Soulmates s01e02 - 5 results Fen, 11(7 correct) results EZN. After update 6 in Fen. With "filter results by name" disabled 10(7 correct)
- Soulmates s01e03 - 3 results Fen, 9(7 correct) in EZN. After update 5 in Fen. With "filter results by name" disabled 8(6 correct)
- Ragnarok s01e01 - no results Fen, 6(3 correct) EZN. After update 2 in Fen. With "filter results by name" disabled 5(3 correct)

For Metamorphosis (2018) and Dogwashers (2020) it seems "filter results by name" disabled ignores the year, but then it looks like it doesnt for Marvel Studios: Assembling a Universe (2014) as there still is no results.

All in all, on first look with the titles i tested id say its a big improvement from what it was before. And even with filter by name enabled does a good job.
Will share my thoughts additionally after ive used it for some time.

**Comment by Tikipeter** [comment]
For the results that did not match:

* Tom & Jerry (2021): 2 of EZN results are password/virus files.
* Dogwashers (2020): 2 extra results for Fen as I include year-1, year and year+1 in the search string to cover this exact situation.
* Marvel's Behind The Mask: 1 less result in Fen (Fen not picking up the result with `'` in the title).
* Marvel Studios: Assembling a Universe (2014): No year present in any result is the reason why Fen has 0 results.
* Soulmates s01e02: Fen dropped 2 (one was flagged with a virus, one was a sample file).
* Soulmates s01e03: Fen dropped 2 (one was flagged with a virus, one was a sample file).

To me looks like the 2 Marvel examples are the only ones I might be able to do something about. I'll see if I can tweak the query string somehow. It's looking like the only way to solve these issues completely is to perform multiple queries on certain occasions, which is not something I'm willing to do.

**Comment by ReaLx3m** [comment]
Maybe discard ' in all searches? As with multiple searches ive done on easynews it seems results are always better without it. 
As for multiple queries... might be a good idea to have kind of last resort manual option in context menu.
