### ISSUE TITLE
Fen player for TMDbH is showing "busy" instead of sources list

### ISSUE THREAD

**Issue by cgcgcgcgcg** [Tikipeter/repository.tikipeter#431]
Not sure if a Fen or a TMDbH issue, so I opened it on TMDbH's GitHub too.
Log:
[Fen.kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/6193383/Fen.kodi.log)

**Comment by cgcgcgcgcg** [comment]
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/465

**Comment by Tikipeter** [comment]
Try to play the title within the Fen addon. If it plays within Fen, then it is not a Fen issue. If it fails to play within Fen, then it is a Fen issue.

**Comment by cgcgcgcgcg** [comment]
You're 100% right.
Whoever made that Fen player for TMDbH, he should fix it.
The dev of TMDbH has a wiki about this.

**Comment by Tikipeter** [comment]
I downloaded the Fen player and it looks correct. Im not sure the player is to blame to be honest.

**Comment by xyzfre** [comment]
My apologies for commenting on this close issue but on my end when using TMDB helper ￼it shows me the source list but when I click on a link I just get the loading circle and I have to press back to get out of it￼,,using K.19 on Nvidia shield￼

**Comment by xyzfre** [comment]
Came across this problem and I saw this issue closed so before opening a new one decided to comment on here no disrespect,, and always appreciate all your hard work Fen is amazing￼￼￼

￼

**Comment by Tikipeter** [comment]
What version of TMDbH is being used by you both?

**Comment by Tikipeter** [comment]
Doesn't matter. Try this player file (you will need to unzip of course):

[direct.fen.json.zip](https://github.com/Tikipeter/repository.tikipeter/files/6233137/direct.fen.json.zip)

**Comment by Logs22** [comment]
wanted to comment to say the one thats in the normal player package for tmdbhelper has always/continues to work for me. I think it would be really cool if there could be a "Fen Source Select" one though that always does source select, while the normal one can be dependent on the addon settings. Just an idea!

**Comment by cgcgcgcgcg** [comment]
> Doesn't matter. Try this player file (you will need to unzip of course):
> 
> [direct.fen.json.zip](https://github.com/Tikipeter/repository.tikipeter/files/6233137/direct.fen.json.zip)

That player works fine.
If that player is uploaded here:
https://github.com/a4k-openproject/json.openplayers/tree/tmdbhelper
TheMovieDb Helper will be able to auto update it instead of deleting it when the Players URL is used in TMDb Helper settings:
https://github.com/a4k-openproject/json.openplayers/archive/tmdbhelper.zip
