### ISSUE TITLE
Next Episode not showing

### ISSUE THREAD

**Issue by sasagr** [Tikipeter/repository.tikipeter#432]
Hi Tiki, I m going crazy to understand why a specific TV Shows is not showing the next episode in Next Episode tab.
It is "This is Us"
I checked and it is INCLUDED in the episode manager but It does not show in the next episode.
Others are working fine.
I also checked if it shows in the Next Up of Seren and there it shows.
I did not attach a log, just in case you want me to enable something before.
Please advise how to troubleshooting it.
Thanks

![image](https://user-images.githubusercontent.com/3427877/112439666-14290780-8d52-11eb-9f28-4dadfb9c3ec0.png)

**Comment by Tikipeter** [comment]
It's because TMDb is reporting the total number of episodes for season 5 as 10. Fen isn't even looking for the 11th episode because of that. It is a bug with TMDb I'm afraid. It should sort itself out.

**Comment by sasagr** [comment]
Clear. Thanks

**Comment by sasagr** [comment]
Sorry but I just noticed this. 
![4E58A151-CE39-4DD1-9744-8836BE8705A1](https://user-images.githubusercontent.com/3427877/112540352-bd0b4d00-8dba-11eb-8a25-185b5b0f757f.jpeg)

It seems that there is an episode 11 but I still don’t see it in fen next episode

**Comment by Tikipeter** [comment]
The issue is tmdb's season summary data.
If you navigate to this show within Fen it will also show episode 11, but the data that Next Episode uses from tmdb is out of alignment with that and reports number of episodes in season as 10.
