### ISSUE TITLE
Low Quality Fanart/Artwork

### ISSUE THREAD

**Issue by ivarbrandt** [Tikipeter/repository.tikipeter#433]
The resolution for the fanart and artwork isn't changing when I change it in the settings. This is happening for movies and shows but it appears to be even lower quality on shows.

In Settings > Metadata, I have include extra art on and resolution set to original.

**Comment by Tikipeter** [comment]
Clear the metadata after changing.

**Comment by ivarbrandt** [comment]
Worked like a charm! Thank you.
