### ISSUE TITLE
Date format not displaying correctly when setting applied.

### ISSUE THREAD

**Issue by JFG1000** [Tikipeter/repository.tikipeter#435]
![20210328_210126](https://user-images.githubusercontent.com/76907836/112766327-2ed8d600-9009-11eb-9f7e-57300c3cfd75.jpg)

Hi there when I select date format in Feb to Day, month,year it does not display as I've set it, it displays month, day, year. Would it he possible to take a look? Thankyou

**Comment by Tikipeter** [comment]
That setting is for single episode lists, like Next Episodes or Trakt Calendar within Fen. With labels made by Fen.
It is not to change how a SKIN displays the date. To change that, you need to change the settings in Kodi, not Fen.
`Settings->Interface->Regional`.

**Comment by JFG1000** [comment]
Ok cheers buddy my apologies, I've sorted it

**Comment by Tikipeter** [comment]
No worries.
