### ISSUE TITLE
Fen Error while trying to open some seasons of certain TV shows

### ISSUE THREAD

**Issue by ReaLx3m** [Tikipeter/repository.tikipeter#436]
Having some errors thrown and unable to enter the season of a show. As example tv show Frasier, clicking on seasons 1,2,5,9,11 throws an error and doesnt enter episode select menu, the rest of the seasons work ok.
Line 424 and below in the log.

[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/6227849/kodi.log)

**Comment by Tikipeter** [comment]
Malformed/Incomplete TMDb data. Not seen that before.
Fixed for next update.

**Comment by ReaLx3m** [comment]
Will this be a general fix? As ive seen it before on some other show, just cant recall which atm. Or show would need to be reported and addressed case by case?

**Comment by Tikipeter** [comment]
This will be a general fix, hopefully.

**Comment by ReaLx3m** [comment]
Good to know, and hopefully it will be general :). Thanks

**Comment by Tikipeter** [comment]
Hopefully fixed with latest version.
