### ISSUE TITLE
1337x scraper fixed

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#44]
I am a code noob, but i compared it to other scrapers you have in Fen, and managed to get it to work.
The base is not mine, credits to original dev ( i have no idea who) and modified things to get it to work in Fen (the one included does not work for me in my country).

Maybey you can add this one (revieuw the code first if it is OK, or maybey things in it that are not needed, but it works).
I just wanted to do somethinng back for all the work you do,annd 1337x has great results.

I have no idea how to add a file in here, so here a copy/paste from notepad++:

# -*- coding: utf-8 -*-

import re
import traceback
import urllib
import urlparse

from tikiscrapers.modules import cache, cfscrape, cleantitle, client, debrid, log_utils, source_utils, workers
from tikiscrapers.modules import dom_parser2 as dom

class source:
    def __init__(self):
        self.priority = 1
        self.language = ['en']
        self.domains = ['1337x.to', '1337x.is', '1337x.st', '1337x.ws', '1337x.eu', '1337x.se']
        self._base_link = None
        self.scraper = cfscrape.create_scraper()
        self.tvsearch = '%s/sort-category-search/%s/TV/seeders/desc/1/' % (self.base_link, '%s')
        self.moviesearch = '%s/sort-category-search/%s/Movies/size/desc/1/' % (self.base_link, '%s')

    @property
    def base_link(self):
        if self._base_link is None:
            self._base_link = cache.get(self.__get_base_url, 120, 'https://%s' % self.domains[0])
        return self._base_link

    def movie(self, imdb, title, localtitle, aliases, year):
        if debrid.status() is False:
            return

        try:
            url = {'imdb': imdb, 'title': title, 'year': year}
            url = urllib.urlencode(url)
            return url
        except Exception:
            failure = traceback.format_exc()
            log_utils.log('1337x - Exception: \n' + str(failure))
            return

    def tvshow(self, imdb, tvdb, tvshowtitle, localtvshowtitle, aliases, year):
        if debrid.status() is False:
            return

        try:
            url = {'imdb': imdb, 'tvdb': tvdb, 'tvshowtitle': tvshowtitle, 'year': year}
            url = urllib.urlencode(url)
            return url
        except Exception:
            failure = traceback.format_exc()
            log_utils.log('1337x - Exception: \n' + str(failure))
            return

    def episode(self, url, imdb, tvdb, title, premiered, season, episode):
        if debrid.status() is False:
            return

        try:
            if url is None:
                return

            url = urlparse.parse_qs(url)
            url = dict([(i, url[i][0]) if url[i] else (i, '') for i in url])
            url['title'], url['premiered'], url['season'], url['episode'] = title, premiered, season, episode
            url = urllib.urlencode(url)
            return url
        except Exception:
            failure = traceback.format_exc()
            log_utils.log('1337x - Exception: \n' + str(failure))
            return

    def sources(self, url, hostDict, hostprDict):
        try:
            self._sources = []
            self.items = []
            if url is None:
                return self._sources

            if debrid.status() is False:
                raise Exception()

            data = urlparse.parse_qs(url)
            data = dict([(i, data[i][0]) if data[i] else (i, '') for i in data])

            self.title = data['tvshowtitle'] if 'tvshowtitle' in data else data['title']
            self.hdlr = 'S%02dE%02d' % (int(data['season']), int(data['episode'])
                                        ) if 'tvshowtitle' in data else data['year']

            query = '%s S%02dE%02d' % (
                data['tvshowtitle'],
                int(data['season']),
                int(data['episode'])) if 'tvshowtitle' in data else '%s %s' % (
                data['title'],
                data['year'])
            query = re.sub('(\\\|/| -|:|;|\*|\?|"|\'|<|>|\|)', ' ', query)
            urls = []
            if 'tvshowtitle' in data:
                urls.append(self.tvsearch % (urllib.quote(query)))
                '''
                Why spam for multiple pages, since it gives plenty on each page?

                urls.append(self.tvsearch.format(urllib.quote(query), '2'))
                urls.append(self.tvsearch.format(urllib.quote(query), '3'))
                '''
            else:
                urls.append(self.moviesearch % (urllib.quote(query)))
                '''
                Why spam for multiple pages, since it gives plenty on each page?

                urls.append(self.moviesearch.format(urllib.quote(query), '2'))
                urls.append(self.moviesearch.format(urllib.quote(query), '3'))
                '''
            threads = []
            for url in urls:
                threads.append(workers.Thread(self._get_items, url))
            [i.start() for i in threads]
            [i.join() for i in threads]

            self.hostDict = hostDict + hostprDict
            threads2 = []
            for i in self.items:
                threads2.append(workers.Thread(self._get_sources, i))
            [i.start() for i in threads2]
            [i.join() for i in threads2]

            return self._sources
        except BaseException:
            return self._sources

    def _get_items(self, url):
        try:
            r = self.scraper.get(url).content
            posts = client.parseDOM(r, 'tbody')[0]
            posts = client.parseDOM(posts, 'tr')
            for post in posts:
                data = dom.parse_dom(post, 'a', req='href')[1]
                link = urlparse.urljoin(self.base_link, data.attrs['href'])
                name = data.content
                t = name.split(self.hdlr)[0]

                if not cleantitle.get(re.sub('(|)', '', t)) == cleantitle.get(self.title):
                    continue

                try:
                    y = re.findall('[\.|\(|\[|\s|\_|\-](S\d+E\d+|S\d+)[\.|\)|\]|\s|\_|\-]', name, re.I)[-1].upper()
                except BaseException:
                    y = re.findall('[\.|\(|\[|\s\_|\-](\d{4})[\.|\)|\]|\s\_|\-]', name, re.I)[-1].upper()
                if not y == self.hdlr:
                    continue

                try:
                    size = re.findall('((?:\d+\,\d+\.\d+|\d+\.\d+|\d+\,\d+|\d+)\s*(?:GiB|MiB|GB|MB))', post)[0]
                    div = 1 if size.endswith('GB') else 1024
                    size = float(re.sub('[^0-9|/.|/,]', '', size.replace(',', '.'))) / div
                    size = '[B]%.2f GB[/B]' % size
                except BaseException:
                    size = '0'

                self.items.append((name, link, size))
            return self.items
        except BaseException:
            return self.items

    def _get_sources(self, item):
        try:
            name = item[0]
            quality, info = source_utils.get_release_quality(item[1], name)
            info.append(item[2])
            info = ' | '.join(info)
            data = self.scraper.get(item[1]).content
            data = client.parseDOM(data, 'a', ret='href')
            url = [i for i in data if 'magnet:' in i][0]
            url = url.split('&tr')[0]

            self._sources.append(
                {'source': 'Torrent', 'quality': quality, 'language': 'en', 'url': url, 'info': info, 'direct': False,
                 'debridonly': True})
        except BaseException:
            pass

    def __get_base_url(self, fallback):
        try:
            for domain in self.domains:
                try:
                    url = 'https://%s' % domain
                    result = client.request(url, timeout='10')
                    search_n = re.findall('<input type="submit" title="(.+?)"', result, re.DOTALL)[0]
                    if search_n and 'Pirate Search' in search_n:
                        return url
                except Exception:
                    pass
        except Exception:
            pass

        return fallback

    def resolve(self, url):
        return url

**Comment by Tinuz97** [comment]
PS:
i made the filesize Bolt,you can remove that.

**Comment by Tikipeter** [comment]
That's great Tinuz97! Thanks for this. I shall do an update of tikiscrapers tomorrow and include this. :) :)

**Comment by edb64** [comment]
Wow, nice job Tinuz97! Great to see people contribute to this awesome addon/project!

**Comment by Tikipeter** [comment]
Hey Tinuz97, I'm going to do an update soon with these two scrapers you so graciously fixed. :)

Please test if you can, as I needed to make some slight changes to the code that checks for a working domain. It was broken in both the scrapers, which made it return the default domain (which worked for you each time). My country blocks different urls, so I was able to see the problem. :) :) :) :)

I also moved checking the domains into the main body of the code (sources()), as it does sometimes cause a hang with displaying the progress dialog when enacted from init().

**Comment by Tinuz97** [comment]
Nice, I wish I could fully understand how they work, and fix, or create them.
I only changed this 2, but more do not work (for me). 

As a example, torrentquest and ddlspot block the netherlands,Germany, and Belgium. 

If I use a vpn (I don't want to use that, just for testing), and I set it on America, or the UK, both work. 
I googled my ass off, searching for a proxy (link), but I could not find it (maybey wrong search term).

**Comment by Tinuz97** [comment]
I almost forgot, because those 2 are blocking the netherlands, tiki scrapers keeps loading longer if it reaches those 2 to find links.

**Comment by Tikipeter** [comment]
I know very little myself when it comes to scraping websites, but I got my head around that domain checking code. Leave me a list of not working torrent scrapers here if you wish, and I'll do my best to get them going over the next couple of days.

All the scrapers Fen uses are written (and fixed) by others, which I'm not comfortable with, but I don't have the skills to do it myself. I'm hoping on my next holiday I can jump into trying to learn what I need to do myself.

In the meantime, best to turn off any individual scrapers that hang when searching.

I really need to try and get this result labels issue sorted as well.

**Comment by Tinuz97** [comment]
I think exenbetgiris, wrzcraft are also broken (or blocked like torrentquest and ddlspot, not sure), doublr (needs update, working in tempest as a example), mkvcage and mkvhub (both working in openscrapers, but only in the dev branch release, not the public one).

**Comment by Tinuz97** [comment]
1337x and Magnetdl are working now 👍

**Comment by Tinuz97** [comment]
Almost forgot torrentapi,  does not give results back (for me) either.

**Comment by Tinuz97** [comment]
Nevermind, torrentapi working, forgot my glasses 😂
