### ISSUE TITLE
request enhancement

### ISSUE THREAD

**Issue by jigoop1** [Tikipeter/repository.tikipeter#440]
hi @Tikipeter 
I found this old addon  "[script.tvskipintro](https://github.com/aenemapy/aenemapyrepo/tree/master/script.tvskipintro)" I thinks is not maintain by creator, but it nice useful service addon. 
it skip Intro for tv show. but in binge watching next episode it do not showing skip option.
so I try to add in fen player with intro in start and exit intro before end of episode.

btw I tested it work.
hope I'm not imposing more work on you.
would you pl look in and add this feature that would be nice addition with is great addon.
thanks for yr all hard work I appreciate you.
ps. pardon my code style I'm learning to py coding.

[plugin.video.fen-1.8.43.zip](https://github.com/Tikipeter/repository.tikipeter/files/6289947/plugin.video.fen-1.8.43.zip)
[script.tikiskins-1.1.06.zip](https://github.com/Tikipeter/repository.tikipeter/files/6289948/script.tikiskins-1.1.06.zip)

![screenshot000](https://user-images.githubusercontent.com/60192287/114181061-086f4080-990f-11eb-8b18-6923e89b7088.png)

**Comment by unkn0wn234** [comment]
I think the problem w this and skip intro addons is that the intro time amongst shows are so different and even within the shows sometimes the intros are placed mid episode too instead of the beginning so its just a whole other can of worms.

**Comment by Tikipeter** [comment]
I will look at this after I push the next update (soon), but in reality it would be much better to get the stand alone plugin working again properly, rather than implementing it in Fen, as I can see that it would cause issues for many users who would not be aware of it's obvious limitations.

Really, a database of correct skipping times for each episode of each show is needed for something like this to work effectively, and I doubt that has been created.

**Comment by jigoop1** [comment]
@Tikipeter 
thanks for considering,
I have update the zip file also attached screenshot.
yeah I know it's "poor man skip option" it do not have database of correct skipping times for each episode, but it start with standard value with option to change for each show and stored in json file in user data folder of fen
since stand alone plugin work for 1st time but not work in subsequent episode so I try to add to player.
I respect yr decision either way to add or not.
thanks
ps. tested on win10 and firestick 4k more testing needed.

**Comment by jigoop1** [comment]
thanks you @Tikipeter 
it work without problem.
