### ISSUE TITLE
Enhancement - Size limits fallback

### ISSUE THREAD

**Issue by ReaLx3m** [Tikipeter/repository.tikipeter#442]
When you set maximum file size limit to some reasonable size for autoplay(for me this is 4GB movies and 2GB TV), it sometimes happens that the material isnt available with set size but might be available with larger size. This stands true especially for easynews, as there is less variety in files with smaller sizes compared to RD.
So when this happens you wont get any result to play, and you might get the impression that Movie/TV show isnt available at all.
Suggestion is to make sort of fallback option that could be enabled via settings. If no result available with set max size, it would autoplay smallest available , or show it in results if autoplay isnt enabled.

**Comment by Tikipeter** [comment]
This should be in the next update. All filters will be ignored when no results with filters, though. Not just size filters.
Setting will be in Settings->Results->Sorting & Filtering - "Ignore All Filters When No Results Available".

**Comment by ReaLx3m** [comment]
Maybe it should also be set to disable autoplay if no results, and show list, so it doesnt play some 20gb file needlesly.
Or is autoplay also already affected by the setting youre planning implementing

**Comment by ReaLx3m** [comment]
Btw, while youre at it, would be great if you could also bake in reverse quality sorting(smallest first). I can see this complementing perfectly the ignore filters option.

**Comment by ReaLx3m** [comment]
Another good idea that comes to mind for size conscious users, would also be having an option to have hevc on top. Hope im not asking too much, from 1 enhancement request it already became a 3 part one :).
