### ISSUE TITLE
Enhancement - Next Episodes Sorting

### ISSUE THREAD

**Issue by ReaLx3m** [Tikipeter/repository.tikipeter#443]
Sorting by recently watched imo is kind of best as it can place what youre currently watching on top. Though there is one area which can be improved. 
Namely if there is some show that you finished watching all available episodes, and new season or overdue episode gets released, it can be placed at very low position and often you can miss the new release, especially if you have lots of shows in the list and watching other older shows that have plenty episodes left and are placed on top. 
If possible i think it would be great to have a sub-setting  under "Recently Watched" that would enable episodes with date/flag "Today" to be displayed on top of the list or just below "in progress first episodes" if one has that enabled.

**Comment by Tikipeter** [comment]
I'll have to think on this. We're getting into some very specific user preference type settings now with this type of thing.

**Comment by ReaLx3m** [comment]
I dont think its that rare occurrence, as old good shows that you havent watched can pile up pretty fast if youre not binging just one show but want variety and have opened few episodes of mutiple sows. So the top of the list will always be populated by them, and newly released episodes/seasons from shows that you want to be up to speed with, can be missed.
Up to you in the end, youre the boss :). Thank you for considering it.

**Comment by Tikipeter** [comment]
Done for next update.

Settings->Next Episodes->Content & Sorting: "Sort Episodes Airing Today to Top"

Default is OFF.

**Comment by ReaLx3m** [comment]
Great to hear, thanks again.
