### ISSUE TITLE
Movie titles to show the release year

### ISSUE THREAD

**Issue by KalAvroniev** [Tikipeter/repository.tikipeter#444]
Is it possible to add an option to customize how movie titles are displayed, similar to episodes/shows?
I can see that the release year shows on the scrape screen but not on any of the lists. 
Sometimes movies have the same names but are released different yars and it would be nice to be able to display that.

Thank you.

**Comment by ReaLx3m** [comment]
Movie year is displayed on the bottom right, easy to miss.

**Comment by KalAvroniev** [comment]
It depends on the skin used. On my phone I use Estouchy and I do not see the year. On my PC I use Confluence and that does not show them in all views only some. Hence the option to be able to add them next to the movie titles in the list.

**Comment by Tikipeter** [comment]
You are both right, which highlights my reluctance to do this. It should really be up to the skin for what is displayed as the main label for movie listings. Fen sends Kodi all the information it needs for the skin to choose what it displays.

I know other addons offer the year after the movie title for displaying, but that doesn't mean they are supposed to, or should.

I will think on this though. I suppose an option to enable this wouldn't hurt for those who want to have it.

**Comment by KalAvroniev** [comment]
Only reason I was asking was because I recently transitioned from Gaia addon (no longer actively supported) to Fen and first thing my wife asked was where is the movie year in the list? 

I love this addon it has everything I use and need and it's much faster than Gaia. I've also been chasing up Orion to get the integration into FenomScrapers, which they have done. Making Fen, wife ready ;)

Thanks for considering this in future builds.

**Comment by Tikipeter** [comment]
Done for next update.

Settings->General->Appearance: "Show Release Year in Listings".

Options: Off/Movies/TV Shows/Both.

**Comment by ReaLx3m** [comment]
> 
> 
> It depends on the skin used. On my phone I use Estouchy and I do not see the year. On my PC I use Confluence and that does not show them in all views only some. Hence the option to be able to add them next to the movie titles in the list.

By bottom right i meant on the default skin which is estuary, not sure about estouchy or confluence. Either way its done, Tikipeter is on fire today :).
