### ISSUE TITLE
Movies and TV Shows audio language

### ISSUE THREAD

**Issue by KalAvroniev** [Tikipeter/repository.tikipeter#445]
Lately I've noticed a slight annoyance, but I'm not sure if there is a solution. A lot of videos have multiple language sources and they start playing in whatever the first one is. 

Option 1: Ability to choose audio language, or use system, and filter streams based on that. And maybe when playing select the chosen language audio source.
Option 2: Ability to choose audio language, or use system, and switch to that source when video starts playing.

**Comment by ReaLx3m** [comment]
2. You can set this in kodi. Settings>Player>Language>Preffered Audio Language. Though if audio tracks in the file are not labeled it wont work correctly and will play the first track.
Unless i misunderstood what you actually mean/need by this.

**Comment by Tikipeter** [comment]
1. Almost always no way to filter streams based on audio before starting playback. This would need to be done based on filename, which very rarely has the audio language included in it. If a file has multiple languages, usually the file will have `MULTI AUDIO` in the name, but not which languages are included. So filtering is not possible.
2. Fen has no way to do this any better than Kodi itself, so make sure you have set your preferred audio track language in Kodi as explained by Realx3m above. If the audio tracks are tagged correctly, Kodi will automatically switch to the correct language if it is available on playback start.

**Comment by KalAvroniev** [comment]
Thanks for that. I will test it.
