### ISSUE TITLE
Auto play and trakt Calendar

### ISSUE THREAD

**Issue by djdirty60** [Tikipeter/repository.tikipeter#446]
Good day,

Is it possible that automatic playback only applies to the series and that you can choose the films yourself in the result?

And that more future days can be chosen in the tract calendar?  Max is now 10. 50 which, I have already tested easily.

thanks in advance

**Comment by Tikipeter** [comment]
I've started a large re-write of some core code of Fen that needs to be completed before anything else changes. When that gets done I'll look to implementing these enhancements.

**Comment by Tikipeter** [comment]
Both enhancements done for next update (1.8.47).

**Comment by djdirty60** [comment]
It works perfectly, thank you.
You are a hero

**Comment by djdirty60** [comment]
One more little question😁😁😁
Is it possible with the calendar that the episodes that come first are at the top of the list?  Because they are now at the very bottom.  thanks in advance

**Comment by Tikipeter** [comment]
You mean swap the sort order entirely? Opposite of what it is now?

**Comment by djdirty60** [comment]
It is now the furthest date first, and the earliest date last

**Comment by Tikipeter** [comment]
Done for next update.
