### ISSUE TITLE
TV shows - Premiers 

### ISSUE THREAD

**Issue by JFG1000** [Tikipeter/repository.tikipeter#447]
Hey Peter would it be possible to have this list revisted and maybe changed? I've noticed most of these shows are anime Japanese titles it seems.

**Comment by ReaLx3m** [comment]
As a workaround you can make a shortcut of a trakt user list which has results more to your liking. 
Im using "Latest TV Shows - garycrawfordgc". Its in My Lists>Trakt Lists>Trending User Lists. 
Select the list, right click or long press enter so you get the context menu,  choose "add to menu" and choose the name and to what menu you want the shortcut attached to.

**Comment by JFG1000** [comment]
Yes I currently use trakt list just hoping Peter can take a look as using the addon directly is quicker for loading widgets. Thanks for the advice though

**Comment by ReaLx3m** [comment]
On aeon nox, when using trakt list for a widget it does load bit slower, but it might do with the trakt list displaying much higher number of shows, like 200 in the example i gave, while lists from the addon are limited to 20. You can limit displayed number of shows in the widget to say 15 or maybe 30, it will load much faster that way.

**Comment by Tikipeter** [comment]
No, it's what TMDb provides. I don't use Trakt user lists or IMDb lists for default menu items.
