### ISSUE TITLE
Issue with Fen + TBDbHelper playback

### ISSUE THREAD

**Issue by Logs22** [Tikipeter/repository.tikipeter#449]
Playback Failed - One or more items failed to play. Check the log for more information about this message. I get this error every time exiting a show or movie that has played from TMDbHelper. On the TV Shows, when I click ok I do not get a crash. This log can be seen here - https://paste.kodi.tv/resisodene 

On Movies however, when I click ok i always get a crash. That log can be seen here - https://paste.kodi.tv/futakajeve 

I have reason to believe this is a fen issue due to not getting these errors with other addons through TMDbHelper. However this doesn't happen when playing directly through the FEN addon. If you need debug logs or anything else please let me know and I will be happy to provide them.

**Comment by Tikipeter** [comment]
Try changing the settings for the player type in TMDbHelper. I'm not entirely sure what the setting name is as I won't install that garbage on my system.

If that doesn't fix it, can you post here the current player for Fen please.

I'm not dealing with TMDbHelper anymore, so if I can't change up the player to make it work, then this will be the end of using Fen with TMDbHelper. Venom uses the same scrapers as Fen, and 123Venom seems more inclined to waste his time with this buggy addon than I am. Having to continually adjust my addon to work with someone else's is **really** annoying.

Please don't read the above as me being annoyed with you. I am annoyed with TMDbHelper.

**Comment by Logs22** [comment]
I completely understand that haha, I wouldn't use it if it weren't for the library integration that works well with Titan Bingie Mod and speeds up the system for me, but it is pretty buggy and finicky. Changing to "PlayMedia" From "setResolveURL" did fix the errors, Sorry about that!

**Comment by SJ50** [comment]
Hi I am facing combination of both issue posted here https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/465 and here https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/455 

It is recommended by jurialmunkey to use escape character for "space" key.
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/455#issuecomment-805447989

So which white-space escape method will you recommend `{KEY_+}, {KEY_-}, {KEY_url}, {KEY_url+}, {KEY_escaped} or {KEY_escaped+}`  to use with FEN.

**Comment by SJ50** [comment]
@Tikipeter any recommendation for above question?
