### ISSUE TITLE
*.mp4 filter

### ISSUE THREAD

**Issue by borygo77** [Tikipeter/repository.tikipeter#45]
Hi Peter! Is there any chance you could implement mp4 files filter?
Some android devices does not handle mp4 with dolbyvision which makes things complicated for autoplay function.
Appreciate any help! 😊

Thank you for your hard work buddy!

**Comment by pyro12** [comment]
Not sure if this will work, but I _ think_ the purpose of "Define Extra Undesirables" in CocoScrapers/Torrents/ is to allow you to add your own filters for things like this.

If I understand you correctly and "Define Extra Undesirables" works the way I think it does, you could add '.mp4' to the list and it would filter out all mp4's .

If that is too aggressive and you don't get search results, you could just turn off 'dolby vison' (exclude) in Fen/Settings/Results.  I have it set to exclude and still get plenty of results.

**Comment by borygo77** [comment]
Ah never tought of that. Will try right now 😊
Thank you!
