### ISSUE TITLE
Clear Art

### ISSUE THREAD

**Issue by derrgoo** [Tikipeter/repository.tikipeter#451]
First a big thanks this is my favorite add on. 

Everything working great but just noticed It seems clear art is missing from latest update 1.8.47. 

Thank you

**Comment by Tikipeter** [comment]
Working fine for me.
Please outline the troubleshooting steps you have done.

**Comment by derrgoo** [comment]
I have made sure my fanart api is active. 

I choose In Progress TV Shows as my widget and choose thumbnail with clear logo. Before the thumbnail would show with the clear art title of the movie also when osd menu was activated. 

Since updating I don't see it but still see if I use Seren. I am not sure what to troubleshoot. 
![image](https://user-images.githubusercontent.com/63697905/117562167-160f1600-b0c7-11eb-8f79-8e7a5da3cb44.jpeg)

**Comment by derrgoo** [comment]
👍 extra art was not checked. I must have missed this when I updated. 🙏 thank you!
