### ISSUE TITLE
Question Next Up

### ISSUE THREAD

**Issue by derrgoo** [Tikipeter/repository.tikipeter#452]
I just have a clarification or question on why does episodes show up quicker on next episodes vs in progress episodes? It seems as if In Progress TV shows pops up a day later than next episodes. Is there a settings feature here?

**Comment by derrgoo** [comment]
All ask in a different way. I have two widgets pulled from "In Progress TV Shows" and a widget pulled from "Next Episodes". 

TV Series from "Next Episodes" always show a day earlier than "In Progress Episodes". Just was wondering if this is correct or should they show at the same time when episode is released? I hope this is more clear. 😅

**Comment by Tikipeter** [comment]
Changed to displaying fully watched, continuing tv shows in the In Progress menu for next update.

**Comment by derrgoo** [comment]
Thanks for the update. One request. Is it possible, to hide watched tv shows? In progress tv shows is showing all past "watched" series. This list is big filling mostly my widget with shows that I have watched.

**Comment by ReaLx3m** [comment]
While inside the list, move with arrow keys either left or up(depending on the skin and view youre using) so the side menu pops up. There youll have toggle option for what to display,  "all videos/watched/unwatched"

**Comment by derrgoo** [comment]
Thank you 👍. It worked for the list menu now working with the skin dev to also fix the widgets.  Appreciate your help.

**Comment by ReaLx3m** [comment]
No problem, glad i could help.

**Comment by Tikipeter** [comment]
I'm going to revert back to the way "In Progress TV Shows" is handled to not include fully watched but still airing tv shows. The change was only done because of this issue you opened, and now you want a setting to hide the change that was enacted to fix this exact issue.

Best just to go back to the way things were if you're going to hide the change anyway.

**Comment by derrgoo** [comment]
Sorry I made needless work for you.

**Comment by Tikipeter** [comment]
It wasn't needless.

You didn't specifically ask to see watched but continuing shows in you "In Progress TV Show" list, it's just that that was the fix. It's not your fault.

Re-reading my comment above, it came off as snarky. It wasn't intended. I was more trying to map the events so I know why this was reverted.

Anyway, I'll sort this out for next update, which is hopefully soon. 👍

**Comment by derrgoo** [comment]
Your comment was fine. Understood. Appreciate all you do. Looking forward to the update when you have time. Have a great day ahead!
