### ISSUE TITLE
Fen error when trying to mark episode "Watched in Trakt"

### ISSUE THREAD

**Issue by ReaLx3m** [Tikipeter/repository.tikipeter#453]
Not sure if its something isolated just to that one episode(as i tried with one episode from 2 other shows and it worked) or it will happen with others too. Heres the log to check, line 507.

[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/6451273/kodi.log)

**Comment by Tikipeter** [comment]
I'll fix this for next update. It's happened to me a couple of times too.

**Comment by ReaLx3m** [comment]
Awesome.
Good to know the reason, information is power :).

Btw, after upgrading to kodi 19.1, i started getting freezes when trying to play a show(with EasyNews). Could it be some Fen incompatibility? Dont have any logs as didnt get much into it, just rolled back to 19.
Do you by any chance have some issues with Kodi 19.1 if you already installed it?

**Comment by Tikipeter** [comment]
RD giving me trouble as well.
Something's going on.

**Comment by ReaLx3m** [comment]
Also running on Win 10, and same, it starts playback after about 2 minutes.
It was supposed to be just a bugfix release, so kind of strange. 
Had the same freezes about a week ago when i tried the 20 alpha from the nightlies master, though i attributed it to being alpha. Seems they have something in common with 19.1 .
Also the 2 available 19.1 matrix nightlies exhibit the same behavior.

In changelog, i saw something about - Updated: enable filecaching by default for network filesystems, maybe thats messing with it? Kodi does have incoming traffic while its frozen for the first 20-30 seconds, after that sporadic transfer bursts for the remaining 90 seconds before it starts.

**Comment by ReaLx3m** [comment]
Also checked the log, similar behavior. Though with 2 files i tested for me it opens on the 6-th attempt.
Well alas, back to 19 also for the time being. Thanks for saving me the time to test a clean build.

**Comment by ReaLx3m** [comment]
Just noticed another possible bug. I had "Auto Resume Playback" set to  "Never" but it was still asking. Changing to "Always" does nothing and dialogue still pops up. Tested in next episodes. See if you can reproduce it.

Btw, is it ok me throwing in unrelated issues like this, or you prefer i get into the habit of opening a new issue for each possible bug i find?

**Comment by ReaLx3m** [comment]
> It is supposed to ask if you have it set to "Never".
I think its more logical for "Never" to not ask you, just start from the begining, as "ask" already does that. This way youll actually have 3 options instead of 2.

> This is where you aren't getting the expected behavior, but it is working correctly for me. Note there are now separate Playback settings for Movies and TV Shows which is a recent addition in the last update.

Yep, thats what was up :), i missed thaat one i suppose, was setting it for movies but testing on episodes. All works as intended after retesting.

**Comment by Tikipeter** [comment]
>I think its more logical for "Never" to not ask you...

Perhaps if the setting was not labelled "Auto Resume Playback", but instead labelled "Ask For Resume Playback".

But, because it is "Auto Resume Playback", this makes sense to me:

* NEVER: Never automatically resume playback.
* ALWAYS: Always automatically resume playback.
* AUTOPLAY ONLY: Only automatically resume playback when autoplay is on.

**Comment by Tikipeter** [comment]
I THINK that PR is related to browsing local filesystems.

**Comment by ReaLx3m** [comment]
Not my forte, im just guessing. As from few of those i checked it was the only one i could see timings in the settings.

**Comment by Tikipeter** [comment]
>MAybe increasing theese values would work:
if (m_seekEvent.WaitMSec(5000))
if (m_seekEvent.WaitMSec(2000))

Not something an addon can do unfortunately. That's all Kodi core.
