### ISSUE TITLE
Duplicates when adding resolved torrents to RD cloud

### ISSUE THREAD

**Issue by ivarbrandt** [Tikipeter/repository.tikipeter#454]
I noticed that duplicate torrents are added to my Real Debrid cloud every time I watch the same movie or show more than once.

So for example, in Settings > Provider accounts, under Real Debrid, check Add Resolved Torrents to Cloud. Also enable Search RD cloud and Check before full search

Now go and click any episode or episode with a season pack. After watching it, go and find the same episode and you'll see that the pre-scrape process where it searches your RD cloud will turn up 2 links rather than one in the cloud. They are the exact same links.

Idk if this will happen with movies as I haven't tested that yet.

**Comment by Tikipeter** [comment]
Are there duplicate torrents in the RD Cloud, or are there just duplicate torrents in the results list in Fen?

**Comment by ivarbrandt** [comment]
Another way to possible go about it is instead of figuring out a way to detect duplicates, maybe you could make it so it only adds resolved torrents that are not in the RD cloud. So if the torrent is in the RD Cloud, then it would skip it, if not, it would add it.

**Comment by Tikipeter** [comment]
But are there duplicates in the cloud when you go on the RD website and check?

**Comment by ivarbrandt** [comment]
No, there aren't. And there aren't any duplicates in the cloud storage on Fen either. There are only duplicates in the pre-scrape Fen results. Very strange.

**Comment by ivarbrandt** [comment]
Even weirder, I went to the RD website and deleted some torrents yet they still show up in Fen pre-scrape results and they actually play fine even though they aren't in the RD Cloud anymore.

**Comment by Tikipeter** [comment]
Nope, Fen will show both like it is currently doing.
