### ISSUE TITLE
Fen Trakt Personal List Not Loading

### ISSUE THREAD

**Issue by rogermae** [Tikipeter/repository.tikipeter#456]
Unable to retrieve Trakt My Movies list in Fen or Venom unless it is sorted by title. I can retrieve my other personal lists however. I have my movie list sorted by release date and have no problem retrieving the list in Seren, TheOath or Shadow. I have revoked and reauthorized Trakt in My Accounts. Uninstalled and reinstalled My Accounts as well. Have cleared caches in both addons. Closed Kodi each time. Eventually got an error log for Fen regarding this: Http://paste.ubuntu.com/p/r3VYrcvthD

**Comment by Tikipeter** [comment]
Is `My Movies` just another personal list, or is it your Trakt Movies Collection?

**Comment by Tikipeter** [comment]
[plugin.video.fen-1.8.48.test1.zip](https://github.com/Tikipeter/repository.tikipeter/files/6468476/plugin.video.fen-1.8.48.test1.zip)

You can install this test zip which should show a proper error in the log as to why this is happening.

After you get an error, upload the log here, then go into the tikipeter repository and re-install Fen from there. DO NOT keep using this test zip, as there is no caching of Trakt lists in this version.
