### ISSUE TITLE
"Next episodes>Include first episode in progress" not working

### ISSUE THREAD

**Issue by ReaLx3m** [Tikipeter/repository.tikipeter#459]
1 or 2 updates back, the few "first episodes in progress" that i had in next episodes, dissapeared from the list, but didnt pay much attention as it was something that i would never finish watching either way. Today when i got to a middle of a first episode of a tv show i noticed it never appeared in next episodes, it did have the in progress indicator shown meaning that progress was detected correctly, and could resume it if run from within its season folder.

Out of topic. At one point you mentioned using your own skin with kodi... Is it something publicly available, would you care to share it? Curious what youve sculptured there :).

**Comment by Tikipeter** [comment]
This will be fixed for next update. I'm just having trouble remembering the exact function this was meant to do, so let me know if it's not behaving properly.

**Comment by ReaLx3m** [comment]
Awesome.

Btw great last update on easynews being able to choose languages for dubs. Youre making it better and better every day :).

A suggestion for making it perfect would be you add fallback if possible. As i think its safely to assume most of users would want english files. But then there are some great shows/movies here and there in other original languages that wouldnt display results when you run into them. 
So maybe its possible adding to easynews language filter something similar to the "ignore all filters when no results available" option in quality/size results?

**Comment by Tikipeter** [comment]
I'll have a think on it. Some things are harder than they sound.

I forgot to address your skin question from earlier... Trust me, it's about 7 years old at this point and is way behind anything being offered these days. I just patch it up each major Kodi release to keep it working because I've used it for so long and it's very fast. Definitely not something worth sharing though. It's functionality over looks, which doesn't make any sense for a skin but it works for me. :)

**Comment by ReaLx3m** [comment]
Thats what a programmer does i suppose, functionality over looks. This is the way :)

As for easynews, not sure how viable this would be, but just thinking out loudly, its what i wanted to suggest before you beat me to it and already implemented the language choice.
Maybe it would be possible to make fen crosscheck with tmdb what is the original language of the Movie/Show and then if option is selected just display results with that flag, or if unchecked show all flags.
Again, not sure how doable this is, just brainstorming.

**Comment by ReaLx3m** [comment]
It came to my attention from a friend, as i do not use subtitle often and when i do its english ones, that subtitles through fen dont display some non english characters, and i know it used to be ok before, not sure when it got broken. Checked and confirmed myself for the issue. 
Characters in question are from Croatian alphabet (Čč, Đđ, Šš, Žž), it just removes them from the subtitle. When going through opensubtitles addon with the same subtitle, the characters are displayed correctly. Croatian uses Central European encoding, so could be other languages with same encoding are affected too.

**Comment by Tikipeter** [comment]
Can you recommend a movie/episode that definitely has Croatian subs so I can test this?

**Comment by ReaLx3m** [comment]
I tested on "Game of Thrones s01e03" with the subtitle thats selected on teh screen below. Not teh right sub for the file but does the job for testing.
![2021-05-18 (3)](https://user-images.githubusercontent.com/22484793/118680774-4e1d0400-b7ff-11eb-845f-e555e61c590a.png)

This is how it looks through fen
![2021-05-18 (4)](https://user-images.githubusercontent.com/22484793/118680832-5e34e380-b7ff-11eb-8f1c-615881f8c672.png)

And this is through opensubtitles addon, and how it should look. 2 of the charcters mentioned are in this example, "ž" and "č".
![2021-05-18 (5)](https://user-images.githubusercontent.com/22484793/118681061-90464580-b7ff-11eb-894a-819a9dc8b6ee.png)

**Comment by ReaLx3m** [comment]
OOT, is "Check before full search" in easynews provider settings recommended to be on or off? And what does it actually do?

**Comment by Tikipeter** [comment]
It will run a "Pre-scrape" of Easynews before the external scrapers are loaded and run.
![screenshot00000](https://user-images.githubusercontent.com/28930002/118691670-a6c6be00-b84c-11eb-9e96-baf3b7b8c249.png)


Use it if you would prefer playing an Easynews result over a RD/PM/AD/Furk/etc result. If Easynews has results, they will display.
![screenshot00001](https://user-images.githubusercontent.com/28930002/118691745-b7773400-b84c-11eb-9903-beff3af7af83.png)


Then you can play a result, or select to run a full search utilizing all enabled scrapers.
![screenshot00002](https://user-images.githubusercontent.com/28930002/118691838-cfe74e80-b84c-11eb-9487-f5919fcbece5.png)
![screenshot00003](https://user-images.githubusercontent.com/28930002/118692317-3ff5d480-b84d-11eb-8a55-eb7e53671671.png)


Works on autoplay also. Any "Internal" Fen scraper can be set to be checked before a full scrape (Easynews, Furk, 3xDebrid Clouds and Local Folders).

**Comment by ReaLx3m** [comment]
All clear, thanks for the info.

**Comment by ReaLx3m** [comment]
Just noticed that using the search function started giving less results. As example when i search for tv shows, stopped giving result for "game of thrones"
![image](https://user-images.githubusercontent.com/22484793/118796547-000a0e00-b89c-11eb-898b-fd852aad68e2.png)

And when searching for spartacus now it gives 2 instead of 3 results it used to previously.
 
![image](https://user-images.githubusercontent.com/22484793/118796420-e36dd600-b89b-11eb-819d-eee1d0fc55ff.png)

I remember there was fenomscrapers update yesterday, maybe related to that?

I suppose youre never closing this issue if i continue with the same tempo, are you? :)

**Comment by ReaLx3m** [comment]
Searching for "Domina" also doesnt give the correct result, just some similarly named ones, and it also inserts "He-man" which i did search for previously(might be related).
![image](https://user-images.githubusercontent.com/22484793/118798129-968aff00-b89d-11eb-9aca-688a0d161b02.png)

**Comment by Tikipeter** [comment]
Hide Watched enabled in your skin?

**Comment by ReaLx3m** [comment]
omg , such a noob mistake :), indeed it was enabled, probably forgot to return it back as it was after messing with the settings. Thanks.
Didnt think of checking for that as "Domina" didnt show in the results and it has only 2 episodes watched of that show, but for some reason it was also marked as whole show watched at the parent(while entering season having just those 2 episodes marked). Any idea why that happened?

**Comment by Tikipeter** [comment]
>...i changed "Shows in progress" to show only Unwatched, and it reflected on search results also. Didnt know those were connected.

Any setting like that for the skin (except views) will be throughout the skin (except maybe widgets).

>...whole show watched at the parent(while entering season having just those 2 episodes marked). Any idea why that happened?

No, but since the permanent move away from tvdb and only using tmdb there are occasionally issues like this. The data returned from tmdb for the TV Show can be different to the data returned for a season's episodes. At the TV Show/Season level, data is used from the TV Show data. When a season is selected to browse into and show the episodes, a second call is made to tmdb for that season's episode data.

At the "episodes" level, we can see how many episodes have aired and how many have not yet aired, but at the "TV Show" level tmdb only reports total episodes, which is the number of episodes it has information on. It has information quite often on unaired upcoming episodes, so that causes big problems. You likely have wrong data from tmdb for the "TV Show" level data, so Fen has falsely assumed the show is watched based on that. If you were to refresh the metadata on that TV Show, it would likely fix it (Context Menu->Options->Re-cache TV Shows Info).

Solutions are in place to help fix these issues. They are not foolproof unfortunately, but work most of the time.

**Comment by ReaLx3m** [comment]
Have a question regarding easynews results flagged as encrypted. I know you decided to not display them in the results, but is there any specific reason why that im not aware of? 
As when i go through potplayer, every file marked as encrypted that i tried(around 20-30) played just fine. 
Im asking this as just recently came to a show(final space) that i was in the middle of, and noticed that half of first season got removed and only files that were left are encrypted ones, which do play fine through potplayer.
So is there any limitation to the video player kodi uses or the way fen works that would make them unplayable?
If not, maybe it would be possible to include them in the search results? Or if there are any possible implications that might show up unpredictably, have an option to include them if user prefers it that way.
