### ISSUE TITLE
Easynews Playback on Kodi 19.1 Troubles Update.......

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/repository.tikipeter#460]
"3 heads are better than one" is often a good way to solve problematic issues.

Thankfully, over the last couple of days, myself and a couple of wise heads have been able to narrow down the issue with Easynews playback in Kodi 19.1 (mainly the couple of other wise heads to be honest).

I need to do some changes to Fen, and some testing to make sure everything is OK after that, but barring any serious issues I'll try and have an update out within the next 2 days that should fix the freezing and very slow playback of Easynews links.

Unfortunately my time is limited today, otherwise I could get on it and have an update likely tomorrow. But it will have to wait an extra day at least.

Big thanks to my often partner in crime, and Venom dev, **123Venom**. Also big thanks to an unnamed person whose diligence, persistence, and embarrassingly large brain were of immense help. Even though this person doesn't even use Easynews. Massive thanks to them both, and if I can get my act together with Fen and get it sorted, it should soon be a non-issue.

**Comment by ReaLx3m** [comment]
Out of curiosity, what was the culprit and how did you solve it?
Does it by any chance have to do with how fen authenticates with EZN, like did it need to do the authentication every time you start a file and it took longer to start it because of the additional step, thus the timeouts in kodi 19.1?

**Comment by Tikipeter** [comment]
Not that, no. I thought it might be something to do with that, in so far as we include the authorization info in the url we give Kodi to use for playback. But that wasn't the issue thankfully, as I didn't want to have to start using cookies for Easynews.

The issue was how we are invoking the Kodi player for playback. For at least the 2 years Fen has been around, I've always called the Kodi player a certain way, but there has always been a more "preferred" way to call the player, using `xbmcplugin.setResolvedUrl`. In the past the resistence to using this (in more addons than just Fen) has been because we don't invoke playback from the movie/episode directory (there's another directory where results are shown first), we needed to account for directory/dialog or auto playback etc. It was much easier to get that all working by calling Kodi's player directly with the resolved url.

Something broke that in Kodi 19.1 (we still don't know the change that caused the break), so now we **have** to use the preferred method for playback.

Using `xbmcplugin.setResolvedUrl` does raise some issues though with how Fen is currently coded, so there needs to be adjustments to the code to hopefully get it working correctly. Fingers crossed.

**Comment by ReaLx3m** [comment]
Thank you for the explanation.
Hopefully everything goes without a hitch with the code adjustments, gl.

**Comment by Tikipeter** [comment]
Troubles with this solution.
Update with a fix for this issue has been temporarily postponed.

**Comment by Tikipeter** [comment]
Unfortunately, there are still prevalent playback issues when dealing with Kodi 19.1 that using `xbmcplugin.setResolvedUrl` does not fix. Windows systems are affected with a freeze and crash of playback after around 10 seconds for certain streams (not related to Easynews but another problem that would need to be solved).

Unfortunately, there is no other option at the moment than to stay with Kodi 19.0 if you are an Easynews user and don't want the long delay/freeze before playing back every video. I would suggest ALL users stay on Kodi 19.0 to be honest. 19.1 looks like a flawed update, at least with regards to the Kodi player.
