### ISSUE TITLE
When starting kodi FEN shows "my accounts error" 

### ISSUE THREAD

**Issue by nived0999** [Tikipeter/repository.tikipeter#462]
When kodi starts FEN shows this "my account error" and i don't understand why..the log file is below

https://paste.kodi.tv/fihisexafo

This error appear only sometimes..if i am correct if my VPN is on then l don't see this error popping up..can u please help..

**Comment by Tikipeter** [comment]
You have "Account Expiry Notification" enabled for RD in My Accounts' settings, and the error is to do with My Accounts not being able to get correct data for your account status. Are you even able to use RD when not using your VPN?

You can either:
* Find out why RD is not connecting properly without your VPN on, and ask them to fix it (good luck).
* Only start Kodi with your VPN on already.
* Turn OFF "Account Expiry Notification" in My Accounts' settings.

Any of the above will stop the error appearing.

**Comment by nived0999** [comment]
No sometimes i am not able to use RD without VPN...☹️..i will try contacting RD support..thanks for the help..🙂

**Comment by Tikipeter** [comment]
It likely means you had the VPN on when you signed up/paid for RD.

If you have no luck resolving the issue with RD (very possible, they are not known for their customer support), then just turn off that setting I quoted above from My Accounts and that will stop the error.

**Comment by nived0999** [comment]
Ohh..okay ..but if that error showed up.Then I won't be getting any RD links...so i need to use the VPN all the time..but if i use my mobile data...then everything is normal without VPN also...i think RD is blocked my broadband ISP..

**Comment by Tikipeter** [comment]
>...i think RD is blocked my broadband ISP..

Possibly, although you may have signed up/paid using your mobile data at the time.

>Then I won't be getting any RD links...

Quite possible. Or you may get the links but they won't play. Your best bet is to fix the issue with RD. But don't mention Kodi when you interact with them. Just state the problem in general terms. They will not help you if you mention Kodi most of the time.

**Comment by nived0999** [comment]
Okay..👍..

I also have a doubt...in discover section in FEN is it possible to exclude unreleased tv shows and movies..when i put the end year as 2021 to see latest shows and movies it also shows unreleased contents..is there a way to hide the unreleased ones to only see the latest released

In autoplay next episode..can you make an option to choose an cached pack at first and autoplay the same pack in the coming episode

Is it possible to change the sorting order of a trakt list to released date order in FEN?


Also FEN is the best addon i ever used...FEN scrapping speed is awesome....well done sir.. great addon🙌

**Comment by derrgoo** [comment]
This happened to me before with ExpressVPN became a provider on their preferred list. I actually called them and support signed up with them a few weeks later. If the vpn you signed up on is on this list you should be fine because they whitelist all IP. [](https://real-debrid.com/vpn)

If your vpn is not listed than they do block ip coming from those vpn. However,using RD is quite safe because they use HTTPS but not as protected as a vpn.
