### ISSUE TITLE
Error on scrape

### ISSUE THREAD

**Issue by esra8877** [Tikipeter/repository.tikipeter#463]
when i click a film to play it gives me "Fen Error Check the log for more information" error.When i check the log a pop up message comes with the header "changelog 1.8.50 (v.18.50)".I am using fen on apple tv 4K kodi version 19.1..
Log file url:https://paste.kodi.tv/opixiseron

thanks in advance

**Comment by basalona** [comment]
I am facing the same issue in my new Apple TV 4K

**Comment by Tikipeter** [comment]
Ill check this out when i get home.

**Comment by Tikipeter** [comment]
Fixed with 1.8.50a.

**Comment by esra8877** [comment]
Sorry i am a total newbie.I tried to find this 1.8.50a update but it doesnt show on addon update section??
