### ISSUE TITLE
[Question] How do I cancel an upload ?

### ISSUE THREAD

**Issue by DaisyF8** [Tikipeter/repository.tikipeter#464]
I download remuxes 60GB. Sometimes I want to cancel.

Is there a menu-item to use for this ?

Atm I'm exiting Kodi to stop the dl. I used to delete the file that was downloading but my router shows the dl still continuing.

**Comment by Tikipeter** [comment]
Exiting Kodi is the only way.

**Comment by DaisyF8** [comment]
Okay thx 🙂
