### ISSUE TITLE
Trakt resume point

### ISSUE THREAD

**Issue by deyooluv** [Tikipeter/repository.tikipeter#467]
Hi,
I am wondering if there is Trakt resume point on Fen?. I keep hitting a dead end on every attempt to get Trakt resume point working on the add-on. I have several systems in my household and I am trying to be able to resume a movie or TV shows from where I left off.
Thank you

**Comment by nived0999** [comment]
I am able to resume any movies or tv shows using track as "watched status provider"

I just authorised my Trakt account from the FEN settings and i don't use any Trakt addon..

**Comment by deyooluv** [comment]
@nived0999  I can resume on the same device but not on my other device in a different room

**Comment by Tikipeter** [comment]
Trakt resume isn't supported in Fen. Fen uses a local database.

Support might/will be added one day, but not at this time.
