### ISSUE TITLE
Easynews Encrypted Results Question

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/repository.tikipeter#468]
https://github.com/Tikipeter/repository.tikipeter/issues/459#issuecomment-844700226

via @ReaLx3m:

> Have a question regarding easynews results flagged as encrypted. I know you decided to not display them in the results, but is there any specific reason why that im not aware of?
> As when i go through potplayer, every file marked as encrypted that i tried(around 20-30) played just fine.
> Im asking this as just recently came to a show(final space) that i was in the middle of, and noticed that half of first season got removed and only files that were left are encrypted ones, which do play fine through potplayer.
> So is there any limitation to the video player kodi uses or the way fen works that would make them unplayable?
> If not, maybe it would be possible to include them in the search results? Or if there are any possible implications that might show up unpredictably, have an option to include them if user prefers it that way.

**Comment by Tikipeter** [comment]
I was more not including results that have a password as determined by Easynews.

I will look into this more though. If there's more valid results to get then that's a good thing.

**Comment by ReaLx3m** [comment]
> I was more not including results that have a password as determined by Easynews.
Thats what i meant by encrypted, labeled by easynews as "password encrypted" (key and exclamation mark icon). So far every file like that i have run into, worked just fine through potplayer.

**Comment by Tikipeter** [comment]
I'm as sure as I can be that I'm getting results that have been previously filtered because of a `password` to play when I disable that filter in the code. So that looks like it might be doable.

I don't want to have any more settings options for EN if I can help it, so I'd rather remove this filter altogether if it's going to play successfully all the time.

**Comment by ReaLx3m** [comment]
Im sure were talking about the same thing just using different terms. As an example you can take Final Space s01e07, the only one available is marked as "password encrypted" on ezn website, and im sure it will show for you when you remove the password fiter.

I proposed to have the option as a safeguard in case unexpectedly turns out there are some unplayable ones, i did try a lot, but still not all of them :). Though still better to have most playable and a rare password protected one not playable, than not have them avilable at all.
And i agree with you that it makes sense to keep it as simple as possible, by not having crap-load of options if unnecessary.

**Comment by Tikipeter** [comment]
I think I'll remove the `password` check for next update. If there's troubles then I can put it back if needed, or see what else can be done.

At the moment I'm having the same results as you, they all seem to play just fine. Don't know where the password is coming from, or if it's just EN reporting incorrectly that it's needed.

**Comment by ReaLx3m** [comment]
> Don't know where the password is coming from, or if it's just EN reporting incorrectly that it's needed.

I dont think its FEN reporting wrongly, its how its marked on ezn website. To illustrate heres a screenshot of what im talking about.
![2021-05-26](https://user-images.githubusercontent.com/22484793/119577160-60c4a980-bdba-11eb-9b98-097da14ca39d.png)

**Comment by Tikipeter** [comment]
Fun fact (not): That's what the EN in FEN stands for (Easynews). The F is for Furk.
That's all the addon used to support in the good old days. No external scrapers.
It's still true you can get pretty much anything you want to watch with just those 2, but RD/PM/AD have improved a lot in the last year/two years. You can almost get everything you want to watch through them as well now.

**Comment by Tikipeter** [comment]
I thought I'd test that Final Space S01E07 because you posted a picture of it above, and was wondering why I only got the 1 result for the password file. I realized the other one is a sample file and get's filtered of course. The password protected one played fine just like all the others so far.

**Comment by ReaLx3m** [comment]
History lessons are important, now it all makes sense :).
As for the debrid services... I still find them bit worse than easynews, though RD and PM are pretty close to it. RD/PM was arguably better than EZN up untill recent if used exclusively in kodi, but then you went and did the search results changes so EZN gets the crown now in my experience.
AD being the worst of the bunch(though good enough if one is after new stuff or popular older). Cant comment on Furk as i never used it.
