### ISSUE TITLE
Sync foreign subtitles

### ISSUE THREAD

**Issue by 1nf5um** [Tikipeter/repository.tikipeter#47]
Hello,

I really love using your addon, so I would like to ask something.
There is a problem/possibility that auto-downloaded subtitles will not be available for certain movies/shows or they will be out of sync.

I did not really find it a problem for English subs, as they were always present (for source materials with English audio, of course).

Would not it be a better solution than the original, if we'd do the following?

- Set the desired subtitle language in the settings
- Get the corresponding subtitle for the language of the stream. So in other words, get the English sub for an English one, Spanish for a Spanish one and so on. It does not seem hard, since Fen provides the full filenames.
- Then get a subtitle of the desired language. For instance Hungarian.
- Get the timings out of the original language's subtitle (English/Spanish/...)
- Paste it into the desired language's subtitle. (Hungarian)

I don't think it would be a perfect solution, but it is something that's worth considering, IMO. :)

**Comment by Tikipeter** [comment]
Are you sure you are in the correct github account? You're mentioning Umbrella, not Fen.

**Comment by Tikipeter** [comment]
No worries.

Now to your post:

>Set the desired subtitle language in the settings

This happens already

>Get the corresponding subtitle for the language of the stream. So in other words, get the English sub for an English one, Spanish for a Spanish one and so on. It does not seem hard, since Fen provides the full filenames.

This is possible.

>Then get a subtitle of the desired language. For instance Hungarian.

This happens now of course.

>Get the timings out of the original language's subtitle (English/Spanish/...)

Here's where we hit an issue. How would this be done?

>Paste it into the desired language's subtitle. (Hungarian)

Also with this. How would this be done?

In the end really, it doesn't matter. Subtitle support within Fen will need to be removed in the coming year, as Opensubtitles are moving to a new API with a subscription based model. Free users will only be allowed 10 subtitle downloads per day, and only 5 if you aren't even a free user (i.e. not registered on their forum).

This will mean the end of subtitle support from within Fen. Users (including myself who always uses subtitles) will need to install an external subtitle addon and use that instead. It's not something I'm looking forward to, but unfortunately that is the way it is going to be.
