### ISSUE TITLE
Fen and trakt not getting along well

### ISSUE THREAD

**Issue by bubba107** [Tikipeter/repository.tikipeter#47]
When trying to access trakt collection in fen ,  the process hangs,and didn't bring up collection, any thoughts on why it is getting stuck?

**Comment by Tikipeter** [comment]
This is almost certainly down to fanart.tv's API being (mostly) down at the moment. There will be an update soon which will limit the fanart.tv requests to 10 seconds, and pop up a notification suggesting to turn off fanart.tv until their API is working again if there are problems. This will stop the endless hanging waiting for a response.

It is still on you, the user, to turn off extra fanart in tikimeta's settings when this issue arises, otherwise browsing will be slow because Fen will keep trying the fanart.tv API each time movies are loaded. Wait a day and turn it back on to see if it's responding again.

**Comment by bubba107** [comment]
Thanks for the information, now I didn't mention that this has been since I installed fen  about 6weeks ago  .I've never been able to use it with trakt. I'd really like to get this app working as my main add-on as I have a easynews sub and would like to utilize it.

**Comment by Tinuz97** [comment]
@Tikipeter, the timeout message kicks in realy fast (but everything with art is working, cleaned meta also).

But the message kicks in regularly (api fanart not down at the moment, working fine), is it possible to give kodi more time to load? (set the limit for the message a little higher? >

**Comment by Tikipeter** [comment]
Yeah, I need to do something about the message. I'm on it.

**Comment by Tikipeter** [comment]
Message should be fixed with tikimeta v.1.1.19a and Fen v.1.5.64a.

**Comment by Tikipeter** [comment]
@bubba107 

I'd really like to fix your issue.

A few questions..

* Do the normal, built in Movie/TV Show menus work for you i.e. Trending, Popular etc?

* If they do work, do you get the correct watched mark status from Trakt?

* Does any function from trakt work correctly (i.e. Next Episodes, Calendar). Is it only your trakt Collection that won't load?

**Comment by bubba107** [comment]
I'm at work right now, when I get home,I will try and attach a log file and
answer your questions about the other trakt features

**Comment by bubba107** [comment]
So fen' features work fine. (trending etc) load quick.it seems anything
trakt related spins the  wheel constantly. As for uploading error pages I
can't seem to get it to do anything

**Comment by bubba107** [comment]
No ,no special characters, letters and numbers,  and yes any other add-on
has worked well with trakt. I'm finding "the crew"hangs a bit after
clearing cache , but after it does load it's  all good

**Comment by bubba107** [comment]
Ok  cleared cache, set tract to 20 /page, made sure indicates are set to
trakt, went to watched movies, 10 min of spinning wheel .went to
collections another 10 min of spinning wheel. Now I figured after 10 min
without loading was long enough to test .

**Comment by Tikipeter** [comment]
You will only need to let it load for about a minute tops to see if it's going to work. If it hasn't worked after 1 minute, it's probably not going to work at all. Just press back to stop it loading.

A couple more changes...

* Go to Settings-->General-->Use Threading for Main Menu Items and turn it OFF.

* Go to Settings-->Indicators-->Watched Status Provider and select 'Fen'.

Then try a Trakt list again and let me know if it works.

 If these don't change the result (I suspect they likely won't), then you will need to supply me with a log file (at least one). I can talk you through that if needed. I'll understand if at that point you feel it's not worth your time messing around, and you use another add-on, but it's the only way I can continue to try and fix the problem. :)

**Comment by bubba107** [comment]
Ok so kudos to you sir! I do believe you've done it ! Everything right now
is loading in a few seconds! This  should be  posted to addons4kodi on
Reddit as I had started a post on it and others had same problem   thank
you very much for all your hard work and a great app

**Comment by Tikipeter** [comment]
Great you have it working. :) :)

Was it the Use Threading setting causing the problem?

Because if it was the Indicators setting, then Fen is still not much use to you as you need your watched indicators coming from Trakt to get full use.

**Comment by bubba107** [comment]
Hi ,,so I haven't changed any settings only updated  regularly, now I seem
to be having the same problem with trakt, only this time  page one loads
quickly but page 2etc are taking very long if loading at all, any idea?

**Comment by bubba107** [comment]
My bad sorry, trakt isn't loading with any other add-on either, ever since
I got fen working I haven't  used anything else.
