### ISSUE TITLE
Next Episodes Enhancements

### ISSUE THREAD

**Issue by ReaLx3m** [Tikipeter/repository.tikipeter#470]
1. When new episode gets released and shown in "Next Episodes" theyre not available to watch straight away.So i think adding an option to delay the display of the episodes would be great. 
Depending on what youre watching, availability times can differ, so ideally it would be user configurable value in hours. Or if its complicated to do that maybe have few options(3, 6, 9, 12, 15, 18, 21, 24 hours etc.). Or if too complicated to do this way maybe just do delay by 1 day as some other addons ive seen have, though i think user configurable way would be preffered and more to liking to different users and one up over the "competition".
Since as mentioned, availability depends on the popularity of the show, to take it one step further,  it would be perfect after setting the master option, to have ability to set an offset from master for individual shows in case some shows availability differs greatly from most of what youre watching. Though even just first one would be good enough if this additional suggestion is too complicated to implement. Or maybe do just the first one, and then enhance in future when you have time and no more pressing changes/fixes in queue.

2. Increase visibility of new episodes by adding label "Week" that would be on episodes released in last 7 days, besides the already available "Today" and "Yesterday".  Makes it easier to spot new releases if you havent started kodi for last 2 days.

3. I noticed "Sort Episodes Airing Today on Top" keeps the episode there untill it has the "Today" label, and then it gets back to the position dictated by the last watched date if you dont watch an episode it in the meantime. This seems bit short period, as sometimes you wont turn on kodi for few days and will miss it. 
It would be great to have an option to choose how long to keep it on top, like while it has label "Today",  "Today"/"Yesterday" or "Today"/"Yesterday"/"Week".  Or maybe have an suboption sort of like "If Left Unwatched Keep on Top For" and user configurable value presented in days. Or if this is too complicated to implement, to simplify, just make it stick there for a week by default. I think this will cover most scenarios and users schedules.
This way much lower possibility that youll miss it, and if you still dont watch it say after a week it will go to the position where it belongs, on the bottom with the rest of the rejects :).

**Comment by travisg100** [comment]
I personally would love the option to delay the display of episodes until a couple hours after they’ve aired. It seems like right now Fen just looks at date rather than time, so all new shows for the day show up at midnight. Now I know I’m not alone!

**Comment by Tikipeter** [comment]
>...It seems like right now Fen just looks at date rather than time...

That is exactly what it does.

Have you set your utc time in settings?

**Comment by travisg100** [comment]
> Have you set your utc time in settings?

Yeah I’ve got that set, doesn’t seem to make a difference unfortunately

**Comment by Tikipeter** [comment]
Oh well, that's about all you can do.

I generally just don't try to play an episode that hasn't aired yet. But it seems like that is not the general behavior of users.

**Comment by Tikipeter** [comment]
I think I did `3).` last update.
The rest are not going to be done I'm afraid.
