### ISSUE TITLE
Fen not searching easynews

### ISSUE THREAD

**Issue by wholesoul** [Tikipeter/repository.tikipeter#471]
I installed Fen on Kodi 19.1 and it worked perfectly fine for few hours (I must mention that I am news to Kodi, Fen and this addon world) but after that I am not sure what settings I changed or may be some update happened and Fen although was giving results but was playing the videos after like 5 minutes once I opened a link (earlier it was instantaneous).

I tried to find what was going on and then I read a note on Fen that Kodi 19.1 update has some bug which is resulting in huge lag in Fan and the advice that I should downgrade to Kodi 19.

I downgraded to 19 but post that it even stopped searching easynews, now there are no results from easynews and I don't know what I am doing wrong and how can I rectify it??

I even tried to go back to 19.1 but now even in 19.1 the search shows no results.

I have already spent my 1 day on this trying various settings, unistalling ,installing, clearing cache of addon and kodi , updating addon etc etc but nothing works.

It just says "no results". I am running Fen 1.8.51 currently and using version 2.0 in easynews website. Please help.

If you can help me on this it would be really nice. Thanks.

**Comment by Tikipeter** [comment]
Firstly, you definitely need to be on Kodi 19.0 for Easynews to play back properly. So no good updating to 19.1.

It's impossible for me to tell you the issue is, as although you've written a lot, you've said very little.

Most likely you need to either re-enter your Easynews credentials in My Accounts, or you need to re-sync those credentials into Fen.

Also you need to make sure Easynews is enabled in Provider Accounts.

Apart from the Easynews website itself being down, they should be the only 2 reasons why Fen would not display results.

**Comment by ReaLx3m** [comment]
> It just says "no results". I am running Fen 1.8.51 currently and using version 2.0 in easynews website. Please help.

Maybe try switching easynews website to v3. I remember when there was an option in FEN to choose between v2 or v3 , i didnt have any results with v2 while web was at v3(didnt try would it work if i switched web to v2).

**Comment by wholesoul** [comment]
Hey Brother/s,
First of all many thanks for replying back so promptly.
Secondly yes you are right on this "you've written a lot, you've said very little" 😂😂

Actually I am a total rookie at Kodi and addon world, installed Kodi for the first time and Fen was my first addon, so ya I didn't know what I was doing for first few hours on Kodi and so I did not know what to mention to you, because I was trying random things to make it work.

But I have tried following:
1. Uninstalled and reinstalled Fen
2. Cleared cache for both Fen and Kodi and tried
2. Reinputted my Username password for easynews
3. Tried to make it work on Kodi 19 but it was having similar issue
4. When Fen worked perfectly for first few hours on easynews (I watched a full movies on it) I was at that time also using easynews 2.0
5. Yes I have checked Easynews is enabled in provider account
6. Easynews site I have checked multiple times it is working perfectly fine
Besides, I must also mention that on Kodi 19.1 also it was able to search on easynews but was playing with lot of lag. This issue of search happened only when I installed Kodi 19, but my be I messed up something over there.

I don't want to change easynews to 3.0 as on that version I am unable to play the video directly on the website which I often do for many videos which becomes as issue particularly on mobile, as the moment you click on the link it starts downloading on 3.0

But I must also mention that in between which researching a lot on this on google to find a solution I stumbled upon an addon called TheCrew. It also has an option of easynews and it was able to search easynews under my current setup (i Just did it) but it is playing the video with a 2-3 min lag at the start (which you have mentioned is due to Kodi 19.1.

So what I would do is that I would reinstall Kodi 19 tomorrow and update you after that.

Thanks for all your help.

**Comment by wholesoul** [comment]
Sorry for the late update as I got busy with certain things in life.
Nevertheless, let me update you on what happened.

I did not get time to install Kodi 19 again because it also involved me installing all the addons again and as I told you I am new to Kodi.

But all I did was to change the username and password of easynews to a different one in Fen and it started searching again. Viola! I don't really know what rectified it because before sending you the earlier messages I had already tried deleting and reinputting the same username password but that did not work. But this when I changed the username and password from what was there before it started searching. Besides, I must also tell you that it plays the videos as well after an initial lag of around 1 minute (I am still using Kodi 19.1).

Hope that is useful information. 
One more thing I would like to inform, somehow IMDB watchlist doesn't work for me in Fen, I have checked the username and it is correct and the Trakt works just fine but IMDB shows blank page on opening.
But it is not something which concerns me majorly and I hope it starts working in later updates, so no worries.

But, thanks a lot for all your help, the way you promptly respond is simply amazing, you are a great guy. Keep up the great work that you are doing, it is really awesome.

**Comment by wholesoul** [comment]
Thanks, i tried but it didn't install unfortunately. FYI I am using Sony Android OLED TV for this, don't know if that is what is preventing it.

**Comment by ReaLx3m** [comment]
Oh, i assumed youre using it on windows, not sure how it goes on android. I know playstore wont have the earlier version, but you could get the apk from a website like [apkpure](https://apkpure.com/kodi/org.xbmc.kodi/variant/19.0-APK). Though not sure how install over the new one would go on android TV as havent done it, should be possible with no problems.  Allways fun to try, isnt it?  :). 
You can do a backup as a safeguard with "Backup" from kodi repository , or "OpenWizard".
Worst that can happen you spend half an hour to re-set everything again, increasing your skill level in the process :)
