### ISSUE TITLE
an advice and a problem

### ISSUE THREAD

**Issue by muzikherif** [Tikipeter/repository.tikipeter#472]
Firstly, problem is at the jump to page option, choosing option 'page' working like alphabet, choosing 'alphabet' working like page.
And secondly my advice is, at the sorting results if you can add 'seeders' option too, it would be better.Like quality then seeders then etc..

**Comment by muzikherif** [comment]
Here is my log
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/6578470/kodi.log)

**Comment by Tikipeter** [comment]
1. `Jump To...` - I'll look into this.
2. `Seeders` - Why do you want this?

**Comment by Tikipeter** [comment]
Yep, Jump To is doing the opposite at the moment. Will be fixed for next update.

**Comment by muzikherif** [comment]
i am not sure about it but i guess high seeders mean more popular, and my experiences it is easier to find sync subtitles for those videos in my language
