### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by derrgoo** [Tikipeter/repository.tikipeter#474]
Thank you for the recent updates. All working great. 

I was wondering if there is a way to limit the amount of movies or tv shows when trakt widget is being used like watchlist. 

It appears in settings and trakt it has a selection for max items. When I pull my trakt watchlist on a widget it extends way beyond the max items set. For example I set 10 and I get the full list.

**Comment by Tikipeter** [comment]
Turn on Paginate Lists and set the limit you want.

Then refresh the widgets or restart Kodi.

**Comment by derrgoo** [comment]
Perfect 👌 exactly what I needed. Thank you
