### ISSUE TITLE
Canceled showing when continuing torrent transfer

### ISSUE THREAD

**Issue by muzikherif** [Tikipeter/repository.tikipeter#475]
after adding uncached links to cloud, if we close the pop up it asks transfer will be continue background then when i choose 'yes' it says cancelled but it continues, it should show up after choosing no.
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/6602650/kodi.log)

**Comment by Tikipeter** [comment]
I'll fix this for next update.
