### ISSUE TITLE
A request 

### ISSUE THREAD

**Issue by rishisss23** [Tikipeter/repository.tikipeter#477]
Hi Tikipeter;

Long time user of fen and an ardent fan;
Is it possible to add an extra option for 'episodes still watching check' under playback episodes to autoplay episode if nothing selected and cancel fen if option selected(i.e opposite of present) 

The present function is 'fen gets cancelled' if nothing selected and autoplays if we select option to continue. 

Not sure whether it will be useful for others;but I would be grateful if this function added.. Thank you

[
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/6635508/kodi.log)
](url)

**Comment by Tikipeter** [comment]
Not at this time.
I'll add it as an option in a coming update.
