### ISSUE TITLE
Trakt not marking anything as watched

### ISSUE THREAD

**Issue by KalAvroniev** [Tikipeter/repository.tikipeter#479]
I'm not sure if this is an issue or not but I have noticed that Trakt stopped logging watched,
~~That goes for resume as well.~~ - Correction resume still works
Before I could also see what I'm watching and progress bar when I loggin to trakt.tv, no longer the case.

Any update or suggestion on what to do to reset this is welcocme.

I already tried revoking and authorising, no luck.

Manually marking anything as watched works.

**Comment by Tikipeter** [comment]
Are you sure you are using Fen? Fen does not set trakt resume points.

**Comment by KalAvroniev** [comment]
I am sure that I'm using Fen. 
But I'm not sure what the Fen integration with Trakt is and if it is supposed to do any of the things mentioned in my original post.

**Comment by Tikipeter** [comment]
Sounds like you have the Trakt addon installed. Do you?

**Comment by KalAvroniev** [comment]
I do have that.
What is Trakt integration on Fen, so I know not to disturb if any further issues?

**Comment by Tikipeter** [comment]
The trakt addon is predominantly for users who have a library based setup in Kodi.

If you have the trakt addon, and have not set it to ignore playback from streaming addons, then Fen will not mark as watched because the Trakt addon does it. That would lead to items being marked twice otherwise.

Your options are to stop using the trakt addon or set it to ignore playback from addons.

**Comment by xyzfre** [comment]
How do you set it up to ￼

**Comment by xyzfre** [comment]
> The trakt addon is predominantly for users who have a library based setup in Kodi.
> 
> 
> 
> If you have the trakt addon, and have not set it to ignore playback from streaming addons, then Fen will not mark as watched because the Trakt addon does it. That would lead to items being marked twice otherwise.
> 
> 
> 
> Your options are to stop using the trakt addon or set it to ignore playback from addons.

Trakt addon,How do you set it up to ignore playback from other addons didn't even know you could do that￼￼

**Comment by Tikipeter** [comment]
I'm afraid I can't help with the settings name. It's been years since I've had the trakt addon installed.

Just have a careful browse of the settings and you should see one to ignore http links and another to ignore addons.

**Comment by KalAvroniev** [comment]
So, can we confirm that if we only have Fen installed with Trakt integration we'd be able to sync Watchlists, Next Episodes, In Progress, Watched and flag as watched automatically?
But we would not be able to have resume point unless we have the trackt addon itself?

**Comment by Tikipeter** [comment]
That's right.

**Comment by KalAvroniev** [comment]
So, if we want resume to work on multiple machines we need to keep the old Trakt add-on?

Sorry about all the questions, just want to make sure I do not have add-ons I do not need.

**Comment by Tikipeter** [comment]
You'll need to look in the Trakt addon's settings to see if you can isolate marking as watched and marking the resume point. I don't think you can.

If you can't, you would be much better off using a different addon that supports resume point syncing with Trakt. Venom does this for instance. Venom also shares the same My Accounts and FenomScrapers modules as Fen, so Venom will already have all your account type settings after you install it. It also will use the same scrapers for results.

**Comment by KalAvroniev** [comment]
Thanks
