### ISSUE TITLE
Thank You: Fen

### ISSUE THREAD

**Issue by ronfrankhill** [Tikipeter/repository.tikipeter#480]
I have to say this but I am enjoying Fen a lot 😊. Plus the amount of work that went into it to make it run perfectly for users to benefit from. I am constantly learning something every time in order to use it with RD to get the full benefit of it. Keep up the great work. I apologize if this not the right place to post any compliments for the use of your Fen etc.

**Comment by Tikipeter** [comment]
Much appreciated. Thanks for the kind words.

I suppose some might be getting a little worried as there hasn't been an update in a few weeks. But I'm plugging along with the next update.
