### ISSUE TITLE
Not an issue, just possible enhancement

### ISSUE THREAD

**Issue by adamosborne83** [Tikipeter/repository.tikipeter#481]
Good Morning,
I trust you're well.

I think firstly you need to be recognised for the amazing work you do and to reply to all issues is credit too.

I was wondering........
Is there a way to increase page limit on movies on trending and other categories?

In regards to the Genre category I'm guessing that it is linked to trending.... is it at all possible to change this to most popular? Reason being I like multiple widgets and most the films are quite repetitive. 

Finally, when scrapping is it possible to have this done in the background at all, as I like a very clean loom.

Please do not think I am ungrateful because that is not the case.

Thank you.

**Comment by Tikipeter** [comment]
>Is there a way to increase page limit on movies on trending and other categories?

Unfortunately not within the general categories. Many of them come from TMDb, which has a default of 20 items returned per page. Some categories come from Trakt, which does allow for increasing per page numbers, but there's no use doing this when TMDb doesn't support it as well. Many lists would still be stuck at 20 items.

>In regards to the Genre category I'm guessing that it is linked to trending.... is it at all possible to change this to most popular?

It is already based on `popularity`.

>Finally, when scrapping[sic] is it possible to have this done in the background at all, as I like a very clean loom.

I used to have this as an option, and removed it a while ago. Unfortunately anything removed during that great purge of features won't be coming back.
