### ISSUE TITLE
Dolby Vision Results Filter Removing All 4K Results

### ISSUE THREAD

**Issue by jkaw** [Tikipeter/repository.tikipeter#485]
When I uncheck the include Dolby Vision results checkbox I no longer get any 4K results.

**Comment by Tikipeter** [comment]
Are all the 4K results Dolby Vision?

**Comment by jkaw** [comment]
No, there were regular 4K HDR results... I will say this was on Wednesday, but didn’t think about submitting an issue until today. I made the switch from Seren due to its many issues and I’ve been enjoying it better so far. 

I think you might’ve made a release since then that may have fixed that issue, however, today I am still getting some D/Vision results when scraping with it unchecked. This is the result with Luca and Dolby Vision unchecked for example. 
![EB561562-44F5-4CF7-AD03-D05DE6C943B7](https://user-images.githubusercontent.com/11337897/123496643-ea47e100-d5dd-11eb-9e56-000c6ac0767c.jpeg)

**Comment by Tikipeter** [comment]
I changed the label for Dolby Vision a few updates ago and forgot to change what the filter looks for.
I'll fix this for next update.
