### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by derrgoo** [Tikipeter/repository.tikipeter#486]
Just want to say thanks for all the updates and continued work.👍

**Comment by Tikipeter** [comment]
No problem. Thanks for the kind words. :)

**Comment by xyzfre** [comment]
You definitely have done an amazing job with Fen ,to me it's the best addon out there right now￼￼, always looking forward for a new update the features you add lately are GREAT ,love The new pop-up when browsing movies and TV shows￼￼￼ for the extra media info this is something definitely unique ,,thank you for all the hard work￼ you put into Fen✊🏼￼￼
