### ISSUE TITLE
Clear Cache Error - Any Option

### ISSUE THREAD

**Issue by supafyn** [Tikipeter/repository.tikipeter#487]
I am getting an error when trying to utilize any of the clear cache options under Tools. For the attached log I tried Clear Trakt Cache and Clear All Cache.

The errors only started after updating to the version 2.x branch.

If there is anything else I can provide besides the attached log file, please let me know.

[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/6720567/kodi.log)

**Comment by Tikipeter** [comment]
Can't check error log yet, but make sure you have latest vrrsion of script.tikiskins. Version 1.1.10

If not, download and install from here.

**Comment by supafyn** [comment]
Downloading script.tikiskins 1.1.10 and manually installing it did fix my issue and I no longer get the error. Thanks!
