### ISSUE TITLE
Thank you & qq

### ISSUE THREAD

**Issue by onlytanmoy** [Tikipeter/repository.tikipeter#488]
First things first, many thanks for this awesome add-on.
Just one qq- can I make request to add a torrent source site to fenomscrapers?

**Comment by Tikipeter** [comment]
You'll have to see Mr Kodi at this repo for fenomscrapers. :)
https://github.com/Mr-Kodi

**Comment by onlytanmoy** [comment]
Thanks mate, I will create an issue there and link this one :)
