### ISSUE TITLE
Feature request - Play  random episode

### ISSUE THREAD

**Issue by Fatal-Errol** [Tikipeter/repository.tikipeter#489]
It would be nice to have this option on the context menu both in the addon and the global context menu. This is similar to Seren's random play where when you highlight a show, it will give you an option to play 1 random episode from that show. I primarily use this for comedy series and some documentaries that I already completed where each episode is standalone. Thank you very much!

**Comment by Tikipeter** [comment]
This was a feature that was removed in a feature purge many updates ago, and slated to never return. However, that removed feature included more useability i.e. autoplaying of continual random episodes, without repeating already watched episodes in that session.

I'll think about including a more simple episode playback of a single random episode. That would get around the rule that this feature is not to be returned. Let me think on it some more.

**Comment by Tikipeter** [comment]
Done for next update.
