### ISSUE TITLE
Feature Request info dialog

### ISSUE THREAD

**Issue by IG2022** [Tikipeter/repository.tikipeter#490]
Hi, Thanks alot for all the work you are doing on the I really appreciate all the work you have been putting in. 

I really like the new info dialog that pops up and gives more information about the movie or tv show its such a great feature, I was wondering if it would be possible to bring this popup up upon clicking select or enter ie rather than just playing the movie when selected it would bring up the extra information. I don't know how difficult this would be but I just wanted to ask!

Thanks again for all your work on the addon!

Log attached below.

http://paste.ubuntu.com/p/mHC4gNH3S7/

**Comment by Tikipeter** [comment]
I won't have the little pop-up come up by default on selection of a movie/episode, but I am thinking of an option to have the full window `Extras...` come up on selection of a movie/episode. From there it can be played as well.

**Comment by IG2022** [comment]
> I won't have the little pop-up come up by default on selection of a movie/tvshow, but I am thinking of an option to have the full window `Extras...` come up on selection of a movie/tvshow. From there it can be played as well.

Come to think of it that would actually be better I didn't realize it was possible to play the title through the "Extras" full window (I just checked and saw that it is). This would be a great feature! I hope you are able to implement it.

**Comment by derrgoo** [comment]
Sounds like a great idea

**Comment by Tikipeter** [comment]
Done for next update.

**Comment by IG2022** [comment]
> Done for next update.

Thanks! I appreciate it.
