### ISSUE TITLE
Extra info

### ISSUE THREAD

**Issue by derrgoo** [Tikipeter/repository.tikipeter#491]
Hi,

Is there a way to make extra info show up as default when you click on context menu information? I really like what you have done. 

Currently, information only pulls the default skin which is not as nice. 👍

![image](https://user-images.githubusercontent.com/63697905/123604262-e22db280-d824-11eb-9dcb-1e3010a0c537.jpeg)

Okay now I see! It shows automatic. That is cool. 

![image](https://user-images.githubusercontent.com/63697905/123605619-3b4a1600-d826-11eb-9835-4ff81f9af288.jpeg)

**Comment by Tikipeter** [comment]
There's two different infos here. The bottom picture is the little popup that you can set to appear after being focused on a movie/tvshow for a certain period of time (found in settings->General->Info Popup).

The top is a full window "Extra Info". You can select that from the context menu currently using `Extras...`. Unfortunately there is no way I can override Kodi and have it show when selecting context menu information. That is a default Kodi action.

I am thinking (as per another request) about making it the default action when you select a movie or episode for playback. Still thinking on that one.

**Comment by derrgoo** [comment]
Thanks for explaining that.  Great feature. 

One more thing I noticed. At the end of series as normal it asks still watching? (I have mine set to 1? I like to ask every one) pop up It says Are you still watching ? The choice is OK or CANCEL. If I hit ok it stops but if I hit cancel it plays next. Maybe those are mixed up?

**Comment by Tikipeter** [comment]
Should be fixed in the most recent update.
