### ISSUE TITLE
next episode not playing after 1st iteration

### ISSUE THREAD

**Issue by jigoop1** [Tikipeter/repository.tikipeter#492]
@Tikipeter 
thanks for all hard work
next episode not playing after 1st iteration of 'fen_total_autoplays' when press OK on confirm_dialog since line no 293 is
"if confirm_dialog(text=ls(32802) % meta['title']):"
instead of
"if not confirm_dialog(text=ls(32802) % meta['title']):"
would you please update addon this change
thanks

**Comment by Tikipeter** [comment]
Done for next update. Thanks @jigoop1  👍
