### ISSUE TITLE
Real Debrid 

### ISSUE THREAD

**Issue by FloridaJC** [Tikipeter/repository.tikipeter#495]
Hi, 
Hope you are well. I use FEN with RD on two devices, Firestick 4k and 2019 Nvidia Shield. All are up to date and have valid RD subscription through Nov., 2021. A couple of days ago I noticed an issue on my Firestick 4k while using FEN. I would pick a TV show off my IMDB watchlist. RD would then just scan all the links and then display results. Once I click on first link it just goes through all of them on the list, never stopping til the end.  Then nothing plays.

Here is the link to my debug file: https://paste.kodi.tv/iwolidugam
Thank you in advance for looking at this.

**Comment by Tikipeter** [comment]
Whilst I can't see what's happening with playback, you do have a corrupted Fen metadata database that's not good to have, and possibly there's also something wrong with your Fen settings file.

If you know how to navigate into the addon_data folder, I would go in there, delete the plugin.video.fen folder and restart Kodi. Then make sure your settings are synced by My Accounts and then try an RD link again.

If you can't do that, then the next easiest way to get that result would be to uninstall Fen, and select YES when it asks you to also remove Fen's settings. Then re-install, make sure the sync with My Accounts has taken place, and try an RD link again.

**Comment by FloridaJC** [comment]
Thanks! Will try that and report back.

**Comment by FloridaJC** [comment]
Tikipeter,
Tried both. Reinstall and re-synching did the trick. Thanks for your expertise!!
