### ISSUE TITLE
Still Watching Dialogue

### ISSUE THREAD

**Issue by IG2022** [Tikipeter/repository.tikipeter#497]
Hi, thanks for the recent update Fen is working great for me!  

I just had a quick question about the still watching dialogue. There are times when this pops up but there are no next episodes to watch. Would it be possible to have the dialogue only pop up if there is another episode up next?

Thanks again for everything you are doing I really appreciate it. 

Log attached below.

http://paste.ubuntu.com/p/G7MJyzm57D/

**Comment by IG2022** [comment]
Log attached below. (Sorry forgot!)

http://paste.ubuntu.com/p/G7MJyzm57D/

**Comment by Tikipeter** [comment]
Should be done for next update.

**Comment by IG2022** [comment]
Thanks alot! I appreciate it!
