### ISSUE TITLE
Watchlist button

### ISSUE THREAD

**Issue by djdirty60** [Tikipeter/repository.tikipeter#498]
Good day,

Could there possibly be a Watchlist button in the fen extra new display?

 thanks in advance

**Comment by Tikipeter** [comment]
No, but I can add a `Trakt` button which will open the trakt manager and allow you to add/remove things from your watchlist.
The problem is I'll have to replace one of the buttons with this, otherwise there will be one extra button on it's own in a new row which won't look very good.

**Comment by Tikipeter** [comment]
Done for next update.
