### ISSUE TITLE
Autoplay next episode lag

### ISSUE THREAD

**Issue by IG2022** [Tikipeter/repository.tikipeter#50]
Hi, 

I have been experiencing a lag on autoplay next episode for some time. I thought it may have been a skin issue however I have tired other skins and I experience the issue with those skins aswell.  Strangely enough I don't have the issue on the default estuary skin there is no lag but with the other skins I have tried I have faced the same issue. This issue also only happens on my Android device, when using my MacBook I do not experience this lag on any skin. 

At the moment I am using Arctic Horizon 2 but I have tried arctic zephyr 2 arctic zephyr reloaded and estuary mod v2 all have the lag. 

The behavior:
When an episode gets towards the end the on deck episode pop-up initiates when I click play or let the timer count down to the end the next episode tries to play, after a few seconds of the busy loading spinner everything freezes and just locks up with the bust spinner stuck. I hear the audio from the next episode playing in the background for 10-20 seconds and then the picture comes in and tries to catch up to the audio. 

Not entirely sure if this is a fen issue but I just wanted to check in and see what you think. 

I've attached my log below for you to take a look.

Log: https://paste.kodi.tv/pivubalexi

Thanks!

**Comment by IG2022** [comment]
Hi again, I just wanted to let you know the latest update has significantly helped with this issue. The lag happens but alot less infrequently and when it happens it's literally for a couple of seconds not the 10-20 I mentioned before.

**Comment by IG2022** [comment]
This issue is no longer present after restarting Kodi with the latest update. I'll close this.

**Comment by Tikipeter** [comment]
I was checking your issue first to make sure the fix worked for you, and I see I never sent the comment I wrote out about it yesterday. :)

Anyway, glad it's working. There'll be a nice full screen"About to Play" type window for next update that will look a bit better. Still not as good as using Kodi's playlist like most other addons do, but better than it's been up until this point.

**Comment by IG2022** [comment]
> I was checking your issue first to make sure the fix worked for you, and I see I never sent the comment I wrote out about it yesterday. :)
> 
> Anyway, glad it's working. There'll be a nice full screen"About to Play" type window for next update that will look a bit better. Still not as good as using Kodi's playlist like most other addons do, but better than it's been up until this point.

No worries, thanks for sorting it out so quickly, I appreciate it. 

Looking forward to seeing that new window. :) I'm used to how fen handles playing the next episode since I've been using it for such a long time but any improvements are always welcome! 

Thanks again.
