### ISSUE TITLE
Episode not marked as watched when using autoplay next episode

### ISSUE THREAD

**Issue by IG2022** [Tikipeter/repository.tikipeter#500]
Hi again,

I've noticed a bug over the last couple of days with autoplay next episode. When I finish an episode and have it set the auto play the next episode it does not mark the previous episode as watched. 

This only happens when I use the autoplay next episode function, when I do not use the auto play next episode the episode is marked as watched after playback ends. 

Also if I click "cancel" in the still watching dialogue and auto play is cancelled the the previous episode is marked as watched.

For example I could watch episode 1 have it autoplay episode 2 and then cancel after episode 2, episode 2 will be marked as watched but episode 1 will not and I have to manually mark it as watched. 

 Im not sure if this has something to do with my settings or if it's a bug with the autoplay next episode function. Any advice would be greatly appreciated. 

My log is attached below. 

http://paste.ubuntu.com/p/6XRxJmKVm6/

**Comment by Tikipeter** [comment]
Have you backed out of and back into the episode list to ensure it hasn't been marked watched and rather the container hasn't refreshed to reflect that?

**Comment by jigoop1** [comment]
@Tikipeter 
hi 
i also have noticed since last 2 updates it's not mark watched,
yeah i have  backed out of the episode list to ensure it hasn't been marked watched and rather the container hasn't refreshed to reflect that?

**Comment by Tikipeter** [comment]
Playback through Fen directly or through a third party addon i.e TMDbHelper?

**Comment by jigoop1** [comment]
Fen directly i do not use TMDbHelper

**Comment by IG2022** [comment]
> Have you backed out of and back into the episode list to ensure it hasn't been marked watched and rather the container hasn't refreshed to reflect that?

I have backed out and back into the episode list after playback and also confirmed on the trakt website that the episode is not marked as watched. At first I just thought it needed some time to refresh so I waited 10 minutes but there was no change on fen or on the trakt website. Just to confirm this only happens during autoplay next episode when I disable autoplay next episode the episode is marked as watched after playback.

**Comment by Tikipeter** [comment]
I was finally able to replicate this issue, so there's a hopeful fix in the next update. Please check if it works after that.

**Comment by IG2022** [comment]
> I was finally able to replicate this issue, so there's a hopeful fix in the next update. Please check if it works after that.

Thanks alot! I'll let you know if it's working correctly after the next update.

**Comment by derrgoo** [comment]
Great. I actually noticed this also today. 👌

**Comment by Tikipeter** [comment]
New update includes fix.

**Comment by IG2022** [comment]
> New update includes fix.

Previously watched episode is now being marked as watched after playback using autoplay. Thank you for fixing this.
