### ISSUE TITLE
Request for "Networks" list for movies

### ISSUE THREAD

**Issue by ShibajiCh** [Tikipeter/repository.tikipeter#501]
Hi @Tikipeter,

First of all many thanks for the awesome "Fen" addon!

I'd like to make a request, that is, if you could add a "Networks" list for movies similar to the one that is already present in the TV Shows section in the Fen addon for Kodi 19.1

Is this possible? Kindly advise.

Thanks and Regards,
ShibajiCh.

**Comment by Tikipeter** [comment]
Unfortunately not. There's thousands of them.

**Comment by ShibajiCh** [comment]
OK fine. Thanks for your prompt response!
Keep up the good work!
