### ISSUE TITLE
Fen Extras and Pop-up Error

### ISSUE THREAD

**Issue by servet** [Tikipeter/repository.tikipeter#504]
Hi,

First of all thank you for this great addon.

After last Fen update I'm getting an error on extras menus and some pop-up menus.
For example, when I open the fen extras menu by long pressing for any content, it gives an error. Second example is it gives an error when I want to open any pop-up in the settings menu like video quality selection.

Log File
[https://paste.kodi.tv/gevepudoza](https://paste.kodi.tv/gevepudoza)

**Comment by Tikipeter** [comment]
Firstly, you will need to delete Fen's metadata database. It is corrupted. Delete the `metacache3.db` file found at `Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.fen`. Then restart Kodi.

Next, you do not have the latest versions of `script.tikiart` and `script.tikiskins` installed. Get them from this github and install them from zip file. If you don't know how to do that, then uninstall Fen and then reinstall it and that should install the correct versions of these 2 dependencies.

**Comment by servet** [comment]
Thanks. I reinstalled Fen without wipe data. Now it's working like rock :)

Thanks again for great work.
