### ISSUE TITLE
Still Watching Check

### ISSUE THREAD

**Issue by derrgoo** [Tikipeter/repository.tikipeter#505]
I reported this as an FYI the other day. I think I am able to recreate it and maybe you can test also. Set still watching check to 1. After the episode is done I click ok to continue and popup keeps coming back until cancel then it does play as it should. I set still watching to 2 and seems to cure the problem.

**Comment by Tikipeter** [comment]
Hopefully fixed with latest update.
The mechanism in place to keep track of played episodes and when to display the confirmation dialog is not ideal at the moment. It will need to be re-written when I have some time to dedicate to it.

**Comment by derrgoo** [comment]
Working great. Have had no issues so far 👍 thank you.
