### ISSUE TITLE
Trakt when watch from download

### ISSUE THREAD

**Issue by uk-julian** [Tikipeter/repository.tikipeter#506]
I’ve been watching episodes from a series which I downloaded to my real debrid account. Presume equally applies to my Premerize account. 

After watching each episode the Trakt account isn’t being updated nor is the scrobbing value pop up appearing. I’m manually updating on the web my watched status etc , but thought may be something you care to look at.

thanks for excellent add on 

regards

julian

**Comment by Tikipeter** [comment]
How would Fen know what tv show you're watching?

I'm not sure why you're not utilizing Fen's cloud scrapers to play back your content in your cloud.

You can even tell Fen to check the cloud(s) before performing a full search.

That way everything will perform like normal, including the interaction with Trakt.

**Comment by uk-julian** [comment]
Morning

Thanks for your response

Obviously from your comments I’m doing something wrong but having looked at tool settings , I’m none the wiser. My downloads are going into the premium cloud storage accounts presently, and I’m pressing play from there. Is this wrong, should I obtain that download differently?

How do I enable settings to utilise Fens cloud scrappers to play back content in the cloud, check cloud before search, which will then in turn interact normally with trakt?

Sorry if this basic to you, but appreciate your advise as it’s a great adding and want to use to it’s potential, or as much as I’m able.

Best regards






Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Tikipeter** [comment]
>.... and I’m pressing play from there. Is this wrong, should I obtain that download differently?

That's the issue. If you play your cloud items back through My Services directly, then of course Fen doesn't know what you are playing (without parsing the filename and then looking that up for metadata which is not going to happen). If you add things to your cloud, you can then still navigate through the addon to the movie/show, and search for sources. The same way you would if you didn't have the item in your cloud. That way, Fen has the metadata needed to mark the movie/episode as watched once you have finished etc.

>How do I enable settings to utilise Fens cloud scrappers to play back content in the cloud...

Settings->Provider Accounts->[YOUR DEBRID ACCOUNT]->Search [RD/PM/AD] Cloud. If you also want Fen to check the cloud before performing a full search, you can also enable "Check Before Full Search".

**Comment by uk-julian** [comment]
Thank you very much.

Once I’ve got system back up will utilise, but presently universal url resolver has gone or won’t load for a number of addons, don’t know why and becoming a nightmare puzzle for this 59 year old. Fen is fine but need to sort this out.

Again thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
