### ISSUE TITLE
UTC Time Offset

### ISSUE THREAD

**Issue by KalAvroniev** [Tikipeter/repository.tikipeter#507]
Hi,
Sorry to be a bother but I'm not sure how the UTC Time Offset is supposed to work.

I'm in Sudney UTC+10. I have trackt configured to show me times in my time zone.
When I look at a show, for example Lupin 1x06 it shows aired  as 11 June 2021 17:00 on Netflix
On Fen with UTC Time Offset I get different dates:
- UTC-14 it shows as 11-06-2021
- UTC-10 it shows as 11-06-2021
- UTC-0 it shows as 12-06-2021
- UTC+10 it shows as 12-06-2021
- UTC+15 it shows as 12-06-2021

I'm not sure how to configure this properly. Caan you please advsce?

**Comment by Tikipeter** [comment]
A few things..

Fen does not use Trakt for ANY metadata at all. Not airtimes, nor any other info for movies/ tv shows. So it matters not what trakt is telling tou.
Fen does get ALL it's metadata info from TMDb, which only provides airdates, not airtimes. So there is no way to always accurately represent the correct airdates after adjusting for utc times. Many shows will be accurate, some will not.

I don't know how trakt are giving a 5pm airtime on a show that's premiering on a streaming service. How do you put an airtime on a VOD service?

Anyway, set your utc to +10, try and enjoy your current lockdown, and ignore the shows that give a wrong airing date. Problem solved. ☺
