### ISSUE TITLE
Mapping extras to remote controller button

### ISSUE THREAD

**Issue by ReaLx3m** [Tikipeter/repository.tikipeter#508]
At the moment i have "info" mapped to a remote button through "Keymap Editor" addon. But i do like fen extras much more, but dont need it set as a default action. 
Could you advise a way to map it to remote button through keymap editor, or maybe some alternate way if not possible through it? I cant seem to figure it out by myself.

**Comment by Tikipeter** [comment]
Kodi is very finicky when running scripts in this way, and despite my best efforts and trying several different methods, I do not think this is possible. Even though it should very much be possible, it never works. As in, I know exactly how to make this work, it just WON'T work the way it should.

**Comment by ReaLx3m** [comment]
Well hopefully Kodi comes to its senses in the near future. I guess its an additional click for the time being :). Thanks for the reply
