### ISSUE TITLE
Resume and AutoResume not working

### ISSUE THREAD

**Issue by pgpold** [Tikipeter/repository.tikipeter#509]
Resume and AutoResume do not work even with AutoResume enabled.  All files will play from the beginning only and not from the resume point.

**Comment by Tikipeter** [comment]
Works for me.
Wish to include any other information?

**Comment by pgpold** [comment]
Automatically Resume Playback is set to "Always" but it's not resuming
playback either when selecting a file to play or playing from auto-resume
and restarts the file from the beginning.  Tried setting it to "Auto play
only" but it still will only restart

**Comment by Tikipeter** [comment]
I don't know what to tell you. I've tested all the different combinations and they all work like they should.

* Are you changing/testing the correct setting (there are separate settings for movies and episodes)?
* Are you playing the media back through a third party addon i.e. TMDbHelper?
* Does the movie/episode display a "resume" icon/flag before playback starts? Signifying the resume point is being saved in the first place?

**Comment by pgpold** [comment]
- Are you changing/testing the correct setting (there are separate
   settings for movies and episodes)?  *Yes*
   - Are you playing the media back through a third party addon i.e.
   TMDbHelper?  *No, directly through Fen*
   - Does the movie/episode display a "resume" icon/flag before playback
   starts? Signifying the resume point is being saved in the first place?
   *No*

**Comment by Tikipeter** [comment]
Then the third item above is the issue. If there's no resume point registered for the movie/episode, how can Fen resume?

This might be a case of you expecting Fen to use Trakt resume points. It doesn't.

**Comment by pgpold** [comment]
Thanks.   How are resume points set in Fen?

**Comment by Tikipeter** [comment]
They are set using a local database. You only have resume info for the movie/episode on the machine where the resume point is set. There is no interaction with Trakt for this.

**Comment by pgpold** [comment]
Are the resume points set automatically without user input?

**Comment by Tikipeter** [comment]
Yes.

**Comment by pgpold** [comment]
On my end it doesn't seem to be setting those points for some reason.  I
tried to test now again and turned off my TV and streaming device in the
middle of an episode.   When I restarted it auto resumed but from the
beginning of the episode.

**Comment by Tikipeter** [comment]
Why did you turn off? The video needs to be STOPPED, not the whole device turned off.
