### ISSUE TITLE
request for feature: rescrape & select from source. 

### ISSUE THREAD

**Issue by rrosajp** [Tikipeter/repository.tikipeter#51]
hi @Tikipeter 
if you can add context menu item for rescrape and select from source @ episode level ,so when play fail or like to change source while play user can do so.
btw your addon is great .
thnaks

**Comment by Tikipeter** [comment]
Hi rrosajp.

That should be doable. :)

**Comment by Tikipeter** [comment]
Done for next update.

**Comment by rrosajp** [comment]
thanks a lot.
