### ISSUE TITLE
Results page enhancement suggestions

### ISSUE THREAD

**Issue by odroider** [Tikipeter/repository.tikipeter#511]
Thank you for sharing such an exceptional addon.

I have a couple of enhancement requests/suggestions pertaining to filters on the Results page as follows:

1. A filter for 10 bit sources.

2. Sort cloud files to the top of the results list. This is on the basis that a file that has been manually downloaded to the cloud is likely to be the first and preferred choice, e.g. for auto play. This is not a big issue for manual select as cloud files are of course listed in a different, definable color. 

As an aside, and just something to consider, it would be very useful to have a user defined field where the user could input custom defined filters, possibly as a string with a delimiter, e.g.: 10 bit; 7.1; Xvid;

Thank you for considering the foregoing, and for your great work.

**Comment by Tikipeter** [comment]
>2. Sort cloud files to the top of the results list.

This used to be a feature, but was removed in a large purge of features many updates ago, which means it is not allowed to come back. If you want the cloud item to be played first in autoplay, you can select in settings for that cloud source to be checked before a full scrape. If something is found, then that will autoplay, if not a full search of providers is initiated.

>1. A filter for 10 bit sources.

As you have this and then mention at the end of your comment an ability for a user edited filters list, you should check out Fenomscrapers settings, which has that already: (Fenomscraper)Settings->Torrents->Remove Undesirables->Define Extra Undesirables. There you can add strings you wish Fenomscrapers to consider when filtering results before handing them to Fen.

**Comment by odroider** [comment]
Thanks for clarifying the cloud result question - the removal must have pre-dated my use of Fen.

Adding a10bit exclusion in the Fenomscrapers torrent section did indeed work - thanks for that. My main interest in the 10bit filter is that many older, notably non-4K/HDR, TVs don't support 10bit color depth - sort of goes hand in hand with HDR - which is not generally a feature of older 1080p TV's which are only 8bit color depth.

Thanks again.
