### ISSUE TITLE
Episodes that haven't aired yet

### ISSUE THREAD

**Issue by djdirty60** [Tikipeter/repository.tikipeter#514]
Good day, it might be possible to map the unaired episodes from the seasons of a series, now the episodes that have yet to be broadcast are listed....

 thanks in advance

**Comment by Tikipeter** [comment]
There's a slight language issue here djdirty.

Are you requesting a setting to stop unaired episodes from showing? I think that's what you're asking.

**Comment by djdirty60** [comment]
Yes

**Comment by Tikipeter** [comment]
Can you please give a translation for "Hide Unaired Episodes".

**Comment by djdirty60** [comment]
Niet uitgezonden afleveringen verbergen

**Comment by Tikipeter** [comment]
Done for next update. Sorry, djdirty60, I went with a string I already had in the translation files. I deleted my message probably just as you were replying. :)
