### ISSUE TITLE
Fen Autoplay Episodes  and Next Episodes  Not Working 

### ISSUE THREAD

**Issue by rogermae** [Tikipeter/repository.tikipeter#516]
Fen has stop autoplaying episodes since the 2.0.07 update. I have autoplay episodss and autoplay next episodes enabled. Have uninstalled and reinstalled Fen several times to no avail.
http://paste.ubuntu.com/p/37FF4kCc2B

**Comment by Tikipeter** [comment]
Both are working fine.
Are you running a build?

**Comment by rogermae** [comment]
Yes

**Comment by Liquidrag** [comment]
> Both are working fine.
> Are you running a build?

Are enabling autoplay episodes and next episodes the only thing need to get this feature working? I also have activate next episode search set to the default 90. I have fen installed from your repo on my personal build and have tested on a fresh install of kodi with only fen and it still does not play the next episode. There is no error log.

**Comment by Tikipeter** [comment]
That is all you need to set to get it working, yes.

**Comment by Liquidrag** [comment]
> That is all you need to set to get it working, yes.

Thank you, I will try again.

**Comment by rogermae** [comment]
Liquidrag Were you able to get it to work

**Comment by Tikipeter** [comment]
Fen is not supported when installed as part of a build. At all.
