### ISSUE TITLE
Fen Extras

### ISSUE THREAD

**Issue by djdirty60** [Tikipeter/repository.tikipeter#518]
Hello,

In fen Extras the button play trailer does not work.  

thanks in advance

**Comment by Tikipeter** [comment]
It should work, but I didn't have anything coded for when there are no trailers in the metadata. It just failed without showing a reason for the user. I will add an OK dialog stating there are no Trailers when that happens for next update.

To make sure for yourself that the button does indeed work, pick a popular new american movie, and try to play the trailer. It should either play a trailer, or present a list of videos that can be chosen.

**Comment by djdirty60** [comment]
https://youtube.com/shorts/bj2RKpyOTeg?feature=share

**Comment by Tikipeter** [comment]
No idea why it's not working for you.

Perhaps a log would help, but possibly not.

**Comment by djdirty60** [comment]
And where can I find that?

**Comment by Tikipeter** [comment]
Leave it for a bit.

I've got an idea it might be language related, as I know you use Dutch.

Hopefully TMDb still includes trailer info in their metadata when another language is selected. I'll have a look.

**Comment by Tikipeter** [comment]
Damn, looks like TMDb don't include videos (including trailers) when you request metadata in a different language. Or at least will only include videos IN that language.

I'll look into a fix..

**Comment by djdirty60** [comment]
Okay will have to wait and see, hope it can be solved like that if tmdb sends the Metadata

**Comment by djdirty60** [comment]
Aaaa that sucks, it's a smaller effort for them I guess than for you

**Comment by Tikipeter** [comment]
For the new movie Black Widow (2021):

Videos when using Dutch language (0 videos):
`'videos': {'results': []}`

Videos when using English language (35 videos):
`'videos': {'results': [{'id': '5de6d4fc11386c001653ee95', 'iso_639_1': 'en', 'iso_3166_1': 'US', 'key': 'RxAtuMu_ph4', 'name': 'Official Teaser Trailer', 'site': 'YouTube', 'size': 1080, 'type': 'Trailer'}, {'id': '5e1d4bab95c0af001511783f', 'iso_639_1': 'en', 'iso_3166_1': 'US', 'key': '_1eykFE1fSA', 'name': 'Special Look', 'site': 'YouTube', 'size': 1080, 'type': 'Teaser'}, {'id': '5e376eeb98f1f1001405caa6', 'iso_639_1': 'en', 'iso_3166_1': 'US', 'key': 'lTL3OZkVMHQ', 'name': 'Big Game Spot', 'site': 'YouTube', 'size': 1080, 'type': 'Teaser'}, {'id': '5e663e90151c5c0017017d01', 'iso_639_1': 'en', 'iso_3166_1': 'US', 'key': 'ybji16u608U', 'name': 'Final Trailer', 'site': 'YouTube', 'size': 1080, 'type': 'Trailer'}, {'id': '606897779ca759005781c348', 'iso_639_1': 'en', 'iso_3166_1': 'US', 'key': 'Fp9pNPdNwjI', 'name': 'New Trailer', 'site': 'YouTube', 'size': 1080, 'type': 'Trailer'}, {'id': '60a1e090162bc30078bac4f1', 'iso_639_1': 'en', 'iso_3166_1': 'US', 'key': '65CzisMJpJ0', 'name': '"You Got A Plan?" Clip', 'site': 'YouTube', 'size': 1080, 'type': 'Clip'}, {'id': '60a1e0b4b1f68d00572d8f19', 'iso_639_1': 'en', 'iso_3166_1': 'US', 'key': 'OBYfrOG83Wc', 'name': 'Legacy Featurette', 'site': 'YouTube', 'size': 1080, 'type': 'Featurette'}, {'id': '60b9272ba066450058e160fe', 'iso_639_1': 'en', 'iso_3166_1': 'US', 'key': 'gKnOm7IWJL8', 'name': 'Playmaker', 'site': 'YouTube', 'size': 1080, 'type': 'Teaser'}, {'id': '60c3a58d5cc11d002a778341', 'iso_639_1': 'en', 'iso_3166_1': 'US', 'key': '3Qh3_Xpi7LM', 'name': '“In Pursuit” Clip', 'site': 'YouTube', 'size': 1080, 'type': 'Clip'}, {'id': '60c3a5c2dc1cb40040f44d28', 'iso_639_1': 'en', 'iso_3166_1': 'US', 'key': '81irXSo-GBA', 'name': 'Ready Set Action Featurette', 'site': 'YouTube', 'size': 1080, 'type': 'Featurette'}, {'id': '60c3a67c992fe60077a9fdeb', 'iso_639_1': 'en', 'iso_3166_1': 'US', 'key': 'aA0uHRPRmdY', 'name': 'Let’s Go', 'site': 'YouTube', 'size': 1080, 'type': 'Teaser'}, {'id': '60d748aeaa78980073f273e1', 'iso_639_1': 'en', 'iso_3166_1': 'US', 'key': 'ck1OR_qoBqg', 'name': 'Control', 'site': 'YouTube', 'size': 1080, 'type': 'Teaser'}, {'id': '60d748e9880551005d62bfcc', 'iso_639_1': 'en', 'iso_3166_1': 'US', 'key': 'tKoebpbJZY0', 'name': 'Spy', 'site': 'YouTube', 'size': 1080, 'type': 'Teaser'}, {'id': '60d749e8ef9d72005da1cf99', 'iso_639_1': 'en', 'iso_3166_1': 'US', 'key': 'E9kjSww45Wg', 'name': 'Dad Jokes Featurette', 'site': 'YouTube', 'size': 1080, 'type': 'Featurette'}, {'id': '60dd802c5690b5002e3d991e', 'iso_639_1': 'en', 'iso_3166_1': 'US', 'key': 'CERIM_K29sM', 'name': 'Got This', 'site': 'YouTube', 'size': 1080, 'type': 'Teaser'}, {'id': '60dd80885690b5007faa9745', 'iso_639_1': 'en', 'iso_3166_1': 'US', 'key': 'e0m5H_OXI9s', 'name': 'Launch', 'site': 'YouTube', 'size': 1080, 'type': 'Teaser'}, {'id': '60dd82a6ef9d72007e08c5c2', 'iso_639_1': 'en', 'iso_3166_1': 'US', 'key': 'GdUVXgyjGfI', 'name': 'Fight', 'site': 'YouTube', 'size': 1080, 'type': 'Teaser'}, {'id': '60dd82cca128560046a0c2ec', 'iso_639_1': 'en', 'iso_3166_1': 'US', 'key': 'LwtYFmu-NyU', 'name': 'Chance', 'site': 'YouTube', 'size': 1080, 'type': 'Teaser'}, {'id': '60e4177407faa200485faded', 'iso_639_1': 'en', 'iso_3166_1': 'US', 'key': '-YbfvsLyL_Y', 'name': '“Prison Break” Official Clip', 'site': 'YouTube', 'size': 1080, 'type': 'Clip'}, {'id': '60e4180c07faa200301710bc', 'iso_639_1': 'en', 'iso_3166_1': 'US', 'key': 'vw-UwLfufao', 'name': 'Taskmaster Breakdown Featurette', 'site': 'YouTube', 'size': 1080, 'type': 'Featurette'}, {'id': '60e4183d26dac10045596680', 'iso_639_1': 'en', 'iso_3166_1': 'US', 'key': 'nbf_1ufgCEw', 'name': 'Hero’s Speech', 'site': 'YouTube', 'size': 1080, 'type': 'Teaser'}, {'id': '60e4185e8805510074e0b4d6', 'iso_639_1': 'en', 'iso_3166_1': 'US', 'key': 'WaIM63s5ylU', 'name': 'Event', 'site': 'YouTube', 'size': 1080, 'type': 'Teaser'}, {'id': '60e418838805510045d0b6d6', 'iso_639_1': 'en', 'iso_3166_1': 'US', 'key': 'G_OV4pPC5Jg', 'name': 'Her Story', 'site': 'YouTube', 'size': 1080, 'type': 'Teaser'}, {'id': '60e72555b7d3520075baff14', 'iso_639_1': 'en', 'iso_3166_1': 'US', 'key': '5twCWC1_3kk', 'name': 'Family Reunion Featurette', 'site': 'YouTube', 'size': 1080, 'type': 'Featurette'}, {'id': '60e7256c4ca676004627c191', 'iso_639_1': 'en', 'iso_3166_1': 'US', 'key': 'EECgbmiQvDg', 'name': 'Future Featurette', 'site': 'YouTube', 'size': 1080, 'type': 'Featurette'}, {'id': '60e725c1caaca2007e513899', 'iso_639_1': 'en', 'iso_3166_1': 'US', 'key': 'IBPKZ5Ra9C4', 'name': 'Jump', 'site': 'YouTube', 'size': 1080, 'type': 'Teaser'}, {'id': '60e7262dcd2046005c619844', 'iso_639_1': 'en', 'iso_3166_1': 'US', 'key': '2du82cvSSXA', 'name': 'Comeback', 'site': 'YouTube', 'size': 1080, 'type': 'Teaser'}, {'id': '60e93753b7d352005e21c8f4', 'iso_639_1': 'en', 'iso_3166_1': 'US', 'key': '9x5NbzoC8Tc', 'name': '2 Truths and a Lie Featurette', 'site': 'YouTube', 'size': 1080, 'type': 'Featurette'}, {'id': '60e9377bec8a43005da0e4af', 'iso_639_1': 'en', 'iso_3166_1': 'US', 'key': 'EnntB6cafpw', 'name': 'Ready', 'site': 'YouTube', 'size': 1080, 'type': 'Teaser'}, {'id': '60e9d68d22e48000300ab7d2', 'iso_639_1': 'en', 'iso_3166_1': 'US', 'key': '3uuOreh_UsQ', 'name': 'Run', 'site': 'YouTube', 'size': 1080, 'type': 'Teaser'}, {'id': '60eba4b4903c5200461d6ce7', 'iso_639_1': 'en', 'iso_3166_1': 'US', 'key': '90PYxX16pG8', 'name': 'Choose', 'site': 'YouTube', 'size': 1080, 'type': 'Teaser'}, {'id': '60ed27d4ab1bc7005e35de05', 'iso_639_1': 'en', 'iso_3166_1': 'US', 'key': 'irsjYO7wa4o', 'name': 'Back', 'site': 'YouTube', 'size': 1080, 'type': 'Teaser'}, {'id': '60ef71fab7abb5005e045978', 'iso_639_1': 'en', 'iso_3166_1': 'US', 'key': '8vzPn0Zmg5M', 'name': 'Exciting', 'site': 'YouTube', 'size': 1080, 'type': 'Teaser'}, {'id': '60f0a34868b1ea0026488315', 'iso_639_1': 'en', 'iso_3166_1': 'US', 'key': 'pWLzEDJEJ6k', 'name': 'Sister Sister Featurette', 'site': 'YouTube', 'size': 1080, 'type': 'Featurette'}, {'id': '60f3ad5133a5330075402a54', 'iso_639_1': 'en', 'iso_3166_1': 'US', 'key': 'mAz8iHJA2aQ', 'name': 'New Team', 'site': 'YouTube', 'size': 1080, 'type': 'Teaser'}]}`

**Comment by Tikipeter** [comment]
I should be able to come up with a fallback to get the ENG videos when not using ENG language and you hit the "Play Trailer" button.

**Comment by djdirty60** [comment]
If it works, I'd love to, but if it's too much work, and you have to adjust too much, don't worry.  Don't want too much work done

**Comment by Tikipeter** [comment]
Should be working next update.

**Comment by djdirty60** [comment]
Thnx for your great work
