### ISSUE TITLE
Kodi 18.9 crashing (if I leave it open overnight)

### ISSUE THREAD

**Issue by wasssu** [Tikipeter/repository.tikipeter#519]
Hi,

If I leave Kodi 18.9 opened overnight (on nvidia shield) the next day I found it crashed. The last 3 lines in the log looks like this:
INFO: CPythonInvoker(210, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.fen/resources/lib/service.py): script successfully run
DEBUG: onExecutionDone(210, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.fen/resources/lib/service.py)
 ERROR: CPythonInvoker(210, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.fen/resources/lib/service.py): script didn't stop in 5 seconds - let's kill it

Latest version of Fen installed.

Thanks

**Comment by Tikipeter** [comment]
Those last 3 lines have no significance on the reason Kodi is crashing for you. For any chance of seeing what the issue might be you need to provide the full log, not pick and choose what you think is relevant.

Has this happened only once, or is it an ongoing issue?
