### ISSUE TITLE
REQ: Fen Trakt Feature

### ISSUE THREAD

**Issue by mystik1** [Tikipeter/repository.tikipeter#520]
Hopefully it's okay to post requests here.  I am not familiar with GitHub etiquette (first time posting in it). I want to switch from using Gia to using Fen exclusively, but there is one thing that prevents it. In Gia, when you go into Favorites and Trakt, there is a Calendar option. This is what I need in Fen. I go in there each day to watch what comes on that day. It is different from Next Episodes because that lists shows you stopped watching and such that it's more difficult to weed through (and they don't show right away also). It's also different from Airing Today, which shows a ton of foreign language shows rather than just shows you watch.  Thanks much in advance for consideration.

**Comment by Tikipeter** [comment]
My Lists->TRAKT: Lists->Trakt Calendar.

A couple of settings can be changed for the calendar in Settings->Trakt.

You can also add the calendar to any main menu by bringing up Context Menu->Add to a Menu. Choose the name and the menu you want to add it to (Root, Movies or TV Shows).

Also, when in Next Episodes, you can bring up Context Menu->Next Episode Manager->Manage In Progress Shows and hide shows you don't want to have appear. This would make your Next Episode list easier to manage.

**Comment by mystik1** [comment]
Oh, awesome.  Thanks a ton.  I am heading to look at it now!  😄

**Comment by mystik1** [comment]
I am so impressed, in the capability and how quickly you replied for me with the great info.  Thanks again.
