### ISSUE TITLE
Crashing To Shield TV After Show

### ISSUE THREAD

**Issue by Baubascat** [Tikipeter/repository.tikipeter#522]
After I watch a show I get sent back to the Shield TV home page.

[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/6871574/kodi.log)

**Comment by Tikipeter** [comment]
Try turning OFF Tools->Set Language Invoker.

**Comment by Baubascat** [comment]
Set Language Invoker set to False. Still crashing to Shield home screen. It is only shows, not movies.

**Comment by Tikipeter** [comment]
That's the only idea I had.
