### ISSUE TITLE
not an issue, question about library integration

### ISSUE THREAD

**Issue by thefrench1** [Tikipeter/repository.tikipeter#523]
Hi, I have used fen in the past when you had a library integration feature how would I do this now as I don't see an option to scan to the library in this version?

thank you in advance

**Comment by Tikipeter** [comment]
If you must, you can use TMDbHelper to make your library. Although support for Fen from TMDbHelper is not handled by me, and continued support of TMDbHelper by Fen is certainly not guaranteed.

Fen is no longer a good option if you insist on using library integration.

**Comment by thefrench1** [comment]
Thank you for the reply will have a look at that. Shame it no longer has the integration option as for me it's a feature I use daily for TV shows. Keep up the great work with fen.On 24 Jul 2021 01:31, Tikipeter ***@***.***> wrote:
If you must, you can use TMDbHelper to make your library. Although support for Fen from TMDbHelper is not handled by me, and continued support of TMDbHelper by Fen is certainly not guaranteed.
Fen is no longer a good option if you insist on using library integration.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

On 24 Jul 2021 01:31, Tikipeter ***@***.***> wrote:
If you must, you can use TMDbHelper to make your library. Although support for Fen from TMDbHelper is not handled by me, and continued support of TMDbHelper by Fen is certainly not guaranteed.
Fen is no longer a good option if you insist on using library integration.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

On 24 Jul 2021 01:31, Tikipeter ***@***.***> wrote:
If you must, you can use TMDbHelper to make your library. Although support for Fen from TMDbHelper is not handled by me, and continued support of TMDbHelper by Fen is certainly not guaranteed.
Fen is no longer a good option if you insist on using library integration.
