### ISSUE TITLE
Has `Autoplay Next Episode` stopped working?

### ISSUE THREAD

**Issue by KalAvroniev** [Tikipeter/repository.tikipeter#525]
For the past 2 weeks to a month, I've noticed that **Autoplay Next Episode** has stopped playing the next episode. 
Currently, I've been watching "Masters of the Universe: Revelation 2021". The show released 5 episodes on the first day July 23rd but it only plays a single episode and then stops. 
I also do not see the notification about the next episode anymore.

I have checked the playback settings and I can see that it is on in there, My Episodes settings are:
- Auto Play = on
- Limit Auto Play Quality = SD, 720p, 1080p
- Autoplay Next Episode = on
- Episodes Watched Before Still Watching Check = 0(off)
- Automatically Resume Playback = Never

**Comment by Tikipeter** [comment]
Change your still watching check to something other than 0. There's likely something wrong to do with that.

**Comment by KalAvroniev** [comment]
I changed the Episodes Watched Before Still Watching Check setting to 10 and it seems to be working now. Would be good to review why 0 does not work, at some point.
