### ISSUE TITLE
Play Next Dialogue

### ISSUE THREAD

**Issue by derrgoo** [Tikipeter/repository.tikipeter#527]
Works well, I was wondering if it was possible to be able to adjust how long the dialogue will stay open to answer. I find it very fast and miss getting my remote to make a selection. ![image](https://user-images.githubusercontent.com/63697905/126967664-7dffc6a4-9b96-485d-b8df-ea5bd1c853ac.jpeg)

**Comment by Tikipeter** [comment]
I'll change it to 20 seconds.

**Comment by derrgoo** [comment]
Sounds great. Thank you
