### ISSUE TITLE
Not an issue just a bit of a thank you 

### ISSUE THREAD

**Issue by IG2022** [Tikipeter/repository.tikipeter#529]
Not sure if this is the place for this but just wanted to give you a big thank you for keeping up with this project and constantly making it better month in and month out. I myself have just started to learn how to code with python and I realize how much time and effort goes into everything that you are doing for the community so I just wanted to say thanks for everything you are doing and keep it up. 

Ps: I especially like the new update with the new autoplay and still watching xml dialogue they look great and work really well. Thanks again and just know we all appreciate all you are doing for us.

**Comment by Tikipeter** [comment]
Thanks for the kind words. I appreciate it. 👍
