### ISSUE TITLE
Dolby vision filtering doesn't work 

### ISSUE THREAD

**Issue by adilaloum** [Tikipeter/repository.tikipeter#53]
hey
dollby vision filtering doesn't work properly 
getting dv links 

ring of power 
si hulk 
and more saws 
not only hybrid links are pulled 
olso dv links 
please help

**Comment by Tikipeter** [comment]
Provide a screen shot of the links that are dolby vision.

Also, a screenshot of your setting for the dolby vision filter.

And a log. <--- This one is required to receive support.

**Comment by adilaloum** [comment]
what's a log ?

![Screenshot_20221009_133120](https://user-images.githubusercontent.com/115411201/194813848-408ca045-fbf8-4ebc-8ab2-73f173cc1f63.jpg)
![Screenshot_20221009_133012](https://user-
images.githubusercontent.com/115411201/194813862-54a621d3-18e6-401a-b707-8dd54aa92c04.jpg)


![Screenshot_20221009_133120](https://user-images.githubusercontent.com/115411201/194813973-e6703d37-766e-49f3-8d59-f7d8ff43f3a5.jpg)
![Screenshot_20221009_133012](https://user-images.githubusercontent.com/115411201/194813978-d9dede27-b2f2-4aca-b7c3-915c4ed5c67b.jpg)
![Screenshot_20221009_132930](https://user-images.githubusercontent.com/115411201/194813982-9c215f41-37b3-46d2-b402-bb0651474c6c.jpg)
![Screenshot_20221009-132659_Kodi](https://user-images.githubusercontent.com/115411201/194813984-15d8dacd-2ff0-49bc-8bfe-89bec810e5d5.jpg)
![Screenshot_20221009-132100_Kodi](https://user-images.githubusercontent.com/115411201/194813986-d269e9cc-f63e-4803-af5d-ffc86026585d.jpg)
![Screenshot_20221005-144813_Kodi](https://user-images.githubusercontent.com/115411201/194814133-0f948a42-abf9-4f1d-bc7a-a33ebd8f4136.jpg)

**Comment by adilaloum** [comment]
try to add DV
dv is not DV
it is case sensitive!!!

**Comment by adilaloum** [comment]
add 
DOLLBY VISION 
Dovi

**Comment by adilaloum** [comment]
add
Dv

**Comment by adilaloum** [comment]
Dovi
dovi
DOVI
dollby vision 
DOLLBY VISION 
Dollby Vision

this are all the options

**Comment by Tikipeter** [comment]
It's not case sensitive.

**Comment by adilaloum** [comment]
i don't know
what a log
but i now it is case sensitive 
because i did the filter in weyd app
and it works really good
just add DV to the code and it will work for sure

**Comment by Tikipeter** [comment]
What does weyd app have to do with fen?

It is not case sensitive.

Provide a log with your next reply.

**Comment by adilaloum** [comment]
okay sorry for the dumb question how can i get the log your asking for?

**Comment by adilaloum** [comment]
yes my matadata is Hebrew
is there a way to keeb the Hebrew matadata and filter DV?

בתאריך יום ג׳, 11 באוק׳ 2022, 11:14, מאת valleycake ‏<
***@***.***>:

**Comment by adilaloum** [comment]
hey i saw you closed the issue
and also tag a label that i can't follow rules
sorry a bout the log i didn't send
i don't know how to send it

anyway thanks for all your good work
you have a great addon


if you can solve dv filtering white datamata on Hebrew it will be great

בתאריך יום ג׳, 11 באוק׳ 2022, 13:36, מאת Tikipeter ‏<
***@***.***>:

**Comment by adilaloum** [comment]
i tried datamata language on English
still getting DV links

בתאריך יום ג׳, 11 באוק׳ 2022, 14:37, מאת adi laloum ***@***.***>:
