### ISSUE TITLE
Autonext xml dialogue size 

### ISSUE THREAD

**Issue by IG2022** [Tikipeter/repository.tikipeter#533]
Hi, 

Just wanted to find out if it would be possible to increase the size of the autonext xml dialogue or decrease the font or include less information about the next episode eg. just the season and episode number. Currently if the next episodes title is more than one word it tries to create a new line in the dialogue which gets cut off by the buttons. (Play now, cancel and close). Not a huge problem but just wanted to find out if there would be way to fix this. 

Thanks! 

http://paste.ubuntu.com/p/nffdZ3V34G/

**Comment by Tikipeter** [comment]
I'll look into this, but it shouldn't be doing what you're describing.

Let me know what skin you're using so i can test.

**Comment by IG2022** [comment]
> 

> > I'll look into this, but it shouldn't be doing what you're describing.

> 
> Let me know what skin you're using so i can test.

I'm using arctic zephyr reloaded. It's quite possible it could be the skin I'm using that's causing the problem. There is a picture of the dialogue with a longer episode title below. If you are able to test and confirm this I can live with it. It's not the biggest deal in the world. 

![PXL_20210730_150538911 MP](https://user-images.githubusercontent.com/78256798/127673370-dafde861-0ec7-4f72-afcb-dfcd4bb0c244.jpg)

**Comment by Tikipeter** [comment]
Yeah there's an issue with the font size. The font for the buttons are too big as well.
The issue addon devs have is we cannot control the fonts available to us to use. Whatever fonts the skin has is what will be shown.

If i code those labels to use `font12`, and the skin doesn't have a font assigned font12, then it will display a different sized font.

Jurial likes to be difficult with his font names. I would assume other fen xmls don't look right either.

I'll see if i can use a different fontbamethat is compatible with his skins.

**Comment by IG2022** [comment]
> Yeah there's an issue with the font size. The font for the buttons are too big as well.
> The issue addon devs have is we cannot control the fonts available to us to use. Whatever fonts the skin has is what will be shown.
> 
> If i code those labels to use `font12`, and the skin doesn't have a font assigned font12, then it will display a different sized font.
> 
> Jurial likes to be difficult with his font names. I would assume other fen xmls don't look right either.
> 
> I'll see if i can use a different fontbamethat is compatible with his skins.

I see, that's a bit of a dilemma! Honestly the other xml dialogues haven't really had an issue when I've seen them at least not for me. The only issue I had as with the auto next dialogue when there is a longer title. Although I don't really use the still watching dialogue often so it is possible that one has the same problem with this skin.

Thanks for taking the time to look for a compatible font I appreciate it. If you are unable to find one then it shouldn't be that big of a deal the function is still there and that's what's most important to me.

**Comment by Tikipeter** [comment]
If I can't get a compatible font type for the size I need (which is likely), then I'll increase the window size so it at least accommodates the larger font that is defaulting in your pic above.

**Comment by Tikipeter** [comment]
Well, I've never seen a font.xml file like this skin has. They are definitely not Jurial's names for fonts.
The only "generic" name that this skin has is `font13`. Every other name is specific for this skin.
I'll have to increase the window size to accommodate the largish font. I won't be able to code in names like `Button`, `Mini`, `TinyBold`, `lyrics9` etc. Bummer really.

I'll have this sorted as best as possible for next update.

**Comment by IG2022** [comment]
> Well, I've never seen a font.xml file like this skin has. They are definitely not Jurial's names for fonts.
> The only "generic" name that this skin has is `font13`. Every other name is specific for this skin.
> I'll have to increase the window size to accommodate the largish font. I won't be able to code in names like `Button`, `Mini`, `TinyBold`, `lyrics9` etc. Bummer really.
> 
> I'll have this sorted as best as possible for next update.

Yeah I think the developer for this skin took Jurials base and changed alot of things including the font I guess. It's no big deal. Thanks for looking into it for me! I'm sure the increase in the dialogues size will be fix enough for me. 

Thanks again!

**Comment by IG2022** [comment]
I can also switch skins if this change  will affect how you intended the xml dialogue to look? There are plenty of skins out there.

**Comment by Tikipeter** [comment]
No, no, I've coded it to at least fit properly with that bigger dialog.
The progress bar looks wonky as well, but there's naught I can do for that.
It'll look a lot better next update.
It's actually a really nice skin. A bit of old AZ and a bit of new AZ. He's done a good job. Just wish he'd kept his font names more generic. And his font.xml file is 5500 lines. Crazy!

**Comment by IG2022** [comment]
> No, no, I've coded it to at least fit properly with that bigger dialog.
> The progress bar looks wonky as well, but there's naught I can do for that.
> It'll look a lot better next update.
> It's actually a really nice skin. A bit of old AZ and a bit of new AZ. He's done a good job. Just wish he'd kept his font names more generic. And his font.xml file is 5500 lines. Crazy!

Ahh okay perfect, thanks for that! Yeah it's a great skin I actually just found it recently, I was using arctic horizon for the longest time and decided to switch it up. Yeah that is crazy! I guess what's what happens when you have developers working independently of each other things dont always line up perfectly.
