### ISSUE TITLE
Loonatics Empire.  Swift. TvNSports .

### ISSUE THREAD

**Issue by Greg0580** [Tikipeter/repository.tikipeter#534]
Swift  is not working.  You  get error messages  to check  log.  TvNSports. Viprow there is no content   in any of the categories.  And streamline.to a lot of channels are not working and or get error message to check log.

**Comment by Tikipeter** [comment]
What do you suppose I should do about this?
Please advise....

**Comment by Greg0580** [comment]
Thank you for fixing swift . You have a great addon.  I use it as main addon throughout

**Comment by Tikipeter** [comment]
I am not the author/maintainer of ANY of the addons you have listed.

I did not fix Switch.

To be honest I have absolutely no idea what any of the addons you've listed are.
