### ISSUE TITLE
Trailer crashing

### ISSUE THREAD

**Issue by djdirty60** [Tikipeter/repository.tikipeter#535]
When I press play trailer in the fen extra, Kodi shuts itself down (crashes).

 Can you maybe look at this

**Comment by derrgoo** [comment]
He probably needs a log. Difficult to diagnose a crash.

**Comment by trkselim** [comment]
Same here Arctic: Zephyr - Reloaded skin

**Comment by Tikipeter** [comment]
Make sure you have `script.tikiskins` version `1.1.22`.

**Comment by IG2022** [comment]
This issue seems to only happen when a title is accessed through widgets and when the default select action is to open extras. if extras is accessed through the context menu on widgets I am not having this issue the trailer plays fine. 

Here's a log. 

http://paste.ubuntu.com/p/h2sRgw977F/

**Comment by derrgoo** [comment]
Yes- I also tested this and I think your correct. Pull manually from fen extras and has no issues.

**Comment by Tikipeter** [comment]
I've got no idea how to fix this.

**Comment by IG2022** [comment]
We can just access extras through the context menu since thats working.

**Comment by derrgoo** [comment]
Looks like latest update fixed it. Great job 👍
