### ISSUE TITLE
Fen Next Episodes not opening after latest update

### ISSUE THREAD

**Issue by ShibajiCh** [Tikipeter/repository.tikipeter#537]
Hi @Tikipeter,

Hope you are doing well.

After today's latest Fen update version 2.0.18 the Next Episodes section under TV Shows is not opening anymore. It's throwing Fen Error. Could you please check what's the issue?

Here is my Kodi log:

https://paste.kodi.tv/vazakadaju.kodi

These are the errors I found in the log:

2021-08-09 23:38:46.758 T:13128   ERROR <general>: GetDirectory - Error getting plugin://plugin.video.fen/?iconImage=next_episodes.png&mode=build_next_episode&name=32483
2021-08-09 23:38:46.792 T:12332   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.fen/?iconImage=next_episodes.png&mode=build_next_episode&name=32483) failed

Kindly advise.

Thanks and Regards,
ShibajiCh.

**Comment by Tikipeter** [comment]
Working for me.

There's nothing in that log that shows why it's not working.

To test....
* Make sure you've restarted your device to test.
* Make sure you are accessing the Next Episodes menu through Fen (not a widget).
* Make sure Trakt is not having any issues.
* Explain to me EXACTLY what is happening. Does Fen load an empty list? Does Kodi throw an error that can be seen on the screen notification?

You might need to install a test version so I can get some logging and see what is happening.

**Comment by ShibajiCh** [comment]
Hi @Tikipeter,

I have restarted my Nvidia Shield TV Pro.

I am accessing the Next Episodes menu through Fen (also tried through a widget). In both cases same error.

Trakt might be having an issue. I had tweeted them regarding such a similar issue few months earlier and they provided a fix. Today also I tweeted them to enquire if there is any issue with the Trakt Api. Let's see what they respond. Last time when I faced such an issue it was happening on multiple addons. This time it's only on Fen.
I revoked Trakt authentication on Fen and also cleared all caches. Still the same error is occuring. The error started happening after the latest Fen update today.

Fen is not opening the list at all and Kodi is throwing an error called Fen Error which in my log shows up as:

2021-08-09 23:38:46.758 T:13128 ERROR : GetDirectory - Error getting plugin://plugin.video.fen/?iconImage=next_episodes.png&mode=build_next_episode&name=32483
2021-08-09 23:38:46.792 T:12332 ERROR : CGUIMediaWindow::GetDirectory(plugin://plugin.video.fen/?iconImage=next_episodes.png&mode=build_next_episode&name=32483) failed

Please advise.

Thanks and Regards,
ShibajiCh.

**Comment by ShibajiCh** [comment]
Hi @Tikipeter,

I guess there was some issue with the latest Fen update when it over-wrote the previous version. I've now uninstalled Fen and reinstalled the latest version which has resolved the next episodes list issue.

Thanks for all your help! You may close this ticket.

Thanks and Regards,
ShibajiCh.

**Comment by apothegm** [comment]
Had the same exact issue. With same errors in kodi.log that ShibajiCh mentioned.

I did everything mentioned here except reinstalling Fen.

I started renaming (by adding "_backup" to) various .db files under 'userdata\addon_data\plugin.video.fen' and narrowed it down to watched_status.db. Once it recreated that file, Next Episodes started working for me again!
