### ISSUE TITLE
FEN leaking incomplete season packs on all episodes after the one that is actually cached

### ISSUE THREAD

**Issue by Nuklear92** [Tikipeter/repository.tikipeter#538]
As the title says, FEN is leaking incomplete season pack on each episode regardless of the one that's actually cached. As you'll see in the clip below regardless of doing a **Clear Scrapers Cache** and **Rescrape & Select Source** you still pull the incomplete Season Pack making you think all of the sudden that the whole season from that particular Season Pack is cached. This is something that I have already re-tried by even doing a complete FEN reinstall, R.D re-auth, **Clear Debrid Cache**, etc. It seems to be a bug, because when I try to click on it on an episode that doesn't have a cached link from that season pack but the URL link appears in the SS window. I get prompted with a FEN error log or simply it skips resolving link since there's nothing to resolve basically.

### Here's the log: 
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/6957804/kodi.txt)

### Here's a video clip showing the issue:
https://streamable.com/6ur7gs

**Comment by Tikipeter** [comment]
That isn't a bug. The 2 results you compared in your video were quite obviously different torrents. There is no "leaking" going on. I don't even know what that means to be honest.

I am unable to dictate what files are added by a person to their RD cloud. If they decide to only upload 1 file from a torrent, that torrent will still be reported as cached by RD when a check is made by Fen.

The only way to know if RD truly has a cached version of a specific EPISODE within that cached torrent is to attempt to play it (or "browse" it as you do in the video). This can't be done for each result before showing the results, as it's something like 3 API calls to do this for EACH result. So instead this is done when the cached torrent is chosen for playback. If it can't access the episode needed, it moves to the next result, which is what you say it is doing in this instance.

There's nothing to fix here.

**Comment by Tikipeter** [comment]
BTW, there's no need to clear the cache before hitting rescrape and select source. That's what "rescrape" means.

**Comment by 123Venom** [comment]
@Nuklear92 Sometimes those incomplete pack files ere uploaded like that and the person caching it only saw it as a season pack file and assumed it was complete.  It's rather common seeing this and we try filter out known offending groups that do this in FenomScrapers, when they can be identified in the torrent name.  Sometimes we have nothing to identify the pack file is incomplete.

**Comment by Nuklear92** [comment]
Thanks for the clarification, yeah been noticing on a few titles that sometimes people upload a season pack to R.D but filter out all the episodes but the one it wishes to see; example S01E01 from season pack and then the same pack leaks on all episodes from that season as the url link is called "unknown.S01.1080p.webdl" just for saying S01 scraper thinks is part of all eps regardless of that pack carrying each episode or not. I tried checking this on Seren which uses a4kscrapers and to my surprise it filter out the season pack from all the episodes that doesn't have a link in it. Perhaps this has to do on the way a4kscrapers filter items. Maybe it has a string that checks inside season packs and if there's no episodes in it that matches the one you're scraping from that season it completely filters out that pack on that particular episode.

**Comment by 123Venom** [comment]
I stand corrected.  I neglected to move down to another episode that I know does not exist in that RD incomplete pack file.  Seren is indeed not showing the pack file when I moved to S01E02.  I know ak4scrapers is not doing that but Seren must be looking inside the returned source for the episode and removing it if it does not contain it.  That's got to be adding overhead to do that.

**Comment by 123Venom** [comment]
The more I peak at Seren now I'm not so sure he's looking inside packs at all because not only did it drop that RD incomplete pack but the PM pack file, that is valid, is gone as well.  If it is looking inside pack files looks a bit like it's also removing valid packs to as I compare results of S01E01 vs. S01E02 and notice a few packs are gone on S01E02 and seems off.

**Comment by Nuklear92** [comment]
Oh, interesting thanks for the insight. I only checked the pack that it's incomplete but didn't dug around more about that other issue of Seren filtering out other season packs. 🤔
