### ISSUE TITLE
Wall View no longer available in Root:set views

### ISSUE THREAD

**Issue by james-nduka** [Tikipeter/repository.tikipeter#539]
It looks like the newer version of FEN does not allow the set views:ROOT to be changed to “Wall” which was the best view…

![E25B8AD2-8CB4-4B97-A737-F3EC222874D6](https://user-images.githubusercontent.com/62253912/128848449-21cab460-3e56-4ce8-b65c-6463327312ad.jpeg)

**Comment by Tikipeter** [comment]
The content type for main content (menus like this) is no longer set by Fen. This is so the skin can provide a more accurate representation of what the actual content is.

This will also mean some skins will provide more views to choose from, some will provide less and some will provide different views.

Your screenshot looks like Estuary which should provide some kind of Wall view for the menu content still...
