### ISSUE TITLE
Plea to bring back play next ep when no action is used.

### ISSUE THREAD

**Issue by Liquidrag** [Tikipeter/repository.tikipeter#54]
Hi Tikipeter, I love fen and so glad you're back. but here/s my plea. Please bring back the function to disable the next up popup because visually it blocks the screen. Also please allow for no action to play next ep, I'm disabled and have little to no hand dexterity so getting to the remote is difficult each time the ep ends. Possibly you could add a "are you still watching" popup after x amount of eps? Loved the way it was functioning before the latest 3.0.16 update.

**Comment by Tikipeter** [comment]
Not likely, because I got rid of the are you still watching check due to another user not liking it being 2 different windows.

**Comment by Liquidrag** [comment]
I had the setting that showed no windows and it just played on to the next so idk what 2 separate windows they were speaking ok. Thank you for the reply though, I'll just revert back to 3.0.15 and disable updates.
