### ISSUE TITLE
Search path not found by arctic zephyr 2

### ISSUE THREAD

**Issue by ruizitu** [Tikipeter/repository.tikipeter#540]
Hi Tikipeter,

I'm trying to add the search pop-up window to arctic zephyr but it doesn't find that option when I choose item for menu, it only finds search for "movies history", "tv shows history" and "people history". 
Could you please advise, I would really like to use fen's search path window, instead of having to use tmdb for example.

Apologies, I'm no expert, I've tried to find a way to solve this myself by looking into the log and trying to add the custom path manually, but I still couldn't manage to get that pop-up window. I've attached a log, hopefully will help.

[Log](https://paste.kodi.tv/kevidivubi) 

Kind regards

**Comment by Tikipeter** [comment]
Not possible I'm afraid.
The best you can do is make an item that falls on the main search page, and press "Search Movies" from there.
