### ISSUE TITLE
Latest release v2.0.18 broke Next Episodes

### ISSUE THREAD

**Issue by KalAvroniev** [Tikipeter/repository.tikipeter#541]
See attached logs
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/6975676/kodi.log)

**Comment by Tikipeter** [comment]
Log says nothing......so I know nothing about this issue.
You have provided absolutely zero information.

**Comment by apothegm** [comment]
@KalAvroniev 

Had the same issue. 

Fix it by renaming (or deleting) watched_status.db under '...userdata\addon_data\plugin.video.fen'.
