### ISSUE TITLE
Not per se an issue.

### ISSUE THREAD

**Issue by jigoop1** [Tikipeter/repository.tikipeter#542]
@Tikipeter
i was watching tv show from TV Show > Popular > Loki 
then watch 2 episodes of that series then try to choose other show Broker
that were the busy dialog show and it do not let display  episode list but then i back out from the list and then try again it work. same thing happen with other show.  
so i was wondering did any one experience this behavior?
i know u need log but there is no error so i did not attach the one. 
btw all latest vers of fen/tikiskin 
on kodi 19 OS win10 and fire stick 4k i experience same behavior.
i thinks it has some thing to do with 
`xbmcplugin.endOfDirectory(__handle__, cacheToDisc=True)`
since it list from cache or mem and do not displaying.
but u may have batter understanding of problem.
thanks for all your hard work.

**Comment by Tikipeter** [comment]
I fairly certain it's to do with Kodi's language invoker. If you turned that off in Fen's Tools section, this will likely never happen. But you will lose the increased speed that having the invoker on provides. I have this happen occasionally. I just wait the amount of time it should take to open, and if it hasn't I hit back to clear the busy dialog and hit it again.

Maybe once every few days on my LibreELEC install this happens.

**Comment by KalAvroniev** [comment]
Currently the Language Invocer is set to TRUE. When I go to Next Episodes I get an error notification a few seconds later. I have waited for hours and nothing happenes, the screen does not load.

**Comment by jigoop1** [comment]
@Tikipeter 
thanks for yr help i will do the same
