### ISSUE TITLE
Timing of the Next Up window

### ISSUE THREAD

**Issue by mddfe** [Tikipeter/repository.tikipeter#544]
First off, I love the add-on. I know you're not interested in bringing back features/usability that has been changed/removed, but my suggestion is a bit different than the previous options that were available.

The relatively new Next Up window is awesome. It's the only thing that I cared about that Fen was really missing compared to some of the other popular add-ons. One issue I have with it, however, is that it typically pops up too early for my liking. In the dramatic final minutes of an episode, you've got this distracting box that pops up. In the previous versions, I could mitigate this issue by changing the the 'Activate Next Episode Search (%)' to something high, like 95-98%. I know you've removed that option and won't be bringing it back, but it was never ideal to begin with. My suggestion is to base the next episode search on the amount of time remaining in the video, rather than a %. The credit sequence to an hour long show usually isn't much different to that of a 30 minute show. Or actually, the next episode search could be done at any time, as long as the Next Up window doesn't appear until later. I figure that's more technically challenging though.

I am aware that you've added the option to remove the Next Up window, which I currently have enabled, but I hate seeing that awesome Next Up window go to waste.

Thank you for your time

**Comment by Tikipeter** [comment]
When I took away the setting last update, I changed it to 95% before it pops up.
I'll have a look at changing it to a specific amount of time. I'd need to separate the mechanics of scraping for sources and displaying the notification.

>My suggestion is to base the next episode search on the amount of time remaining in the video

What amount of time do you think? 30secs? 20 secs?

**Comment by mddfe** [comment]
> What amount of time do you think? 30secs? 20 secs?
Well, if you're separating the mechanics of scraping and displaying, I think I'd go with 20 seconds. In my opinion, it's better to have it pop up slightly into the credits rather than showing up during a dramatic reveal. Different people will have different opinions on that though, and different shows will have different length credit sequences. I think it's best left as an option that the user can change, but I understand the desire to remove clutter from the settings page.

**Comment by Tikipeter** [comment]
>I think it's best left as an option that the user can change

I think you're right. I'll make a new setting using amount of seconds rather than percentage. I'll default it to 20 seconds.

**Comment by Tikipeter** [comment]
This will be done for next update. I've re-written the auto next episode code (again) so please keep an eye out for any errors and let me know.
