### ISSUE TITLE
New Settings

### ISSUE THREAD

**Issue by ronfrankhill** [Tikipeter/repository.tikipeter#546]
I am enjoying the new features in Fen settings. Thanks. This will make things simple. Dumb question on my part. If my internet speed is 100 Mbps should l adjust the settings from default 20 Mbps to 100 Mbps? Just curious. Not getting any issues on the default 20 Mbps.

**Comment by Tikipeter** [comment]
Yes. You set it to whatever you like. If your speed is 100, but you want to set it to 80 to leave some room for other devices in the house, or you only get 80 from the servers you're streaming FROM, that's fine too. Whatever you like you can set it to basically.

**Comment by ronfrankhill** [comment]
Okay. Thanks. I will do that.
