### ISSUE TITLE
Is nextep.airdate_colour being honored in new version?

### ISSUE THREAD

**Issue by meesterexx** [Tikipeter/repository.tikipeter#547]
I see the setting for next episode airdate color has been removed from the GUI, but in the userdata settings.xml I still see 
setting id="nextep.airdate_colour". Changing the color here manually doesn't seem to have any effect and I seem to be stuck on a magenta type color for the airdate. This is not a big issue, but I would like it to better match the highlight colors I'm using in my current skin for the homescreen next episodes widget.
Thank you.

**Comment by Tikipeter** [comment]
It does not honor any now non-existing settings, including the one you mention.
As soon as you run a "Clean All Settings" those will be removed. They aren't being used anymore.

**Comment by meesterexx** [comment]
Thank you. I ran "Clean All Settings" as you recommended to remove the unused settings.
