### ISSUE TITLE
Cant add source to kodi

### ISSUE THREAD

**Issue by patel-jeel92** [Tikipeter/repository.tikipeter#548]
Cant install the source to install repository in Kodi. Using https://tikipeter.github.io/ and it returns a 404

**Comment by Tikipeter** [comment]
Download the repository zip from here-
https://github.com/Tikipeter/repository.tikipeter/tree/master/zip/repository.tikipeter
and install the Tikipeter repository using that.

The github.io source to install from has been removed.
