### ISSUE TITLE
"The Midnight Club" 

### ISSUE THREAD

**Issue by JFG1000** [Tikipeter/repository.tikipeter#55]
Hey, selecting "The Midnight Club" TV show causes Kodi to crash every time

**Comment by Liquidrag** [comment]
searched and played fine on my end.

**Comment by JFG1000** [comment]
> searched and played fine on my end.

What device?

**Comment by Tikipeter** [comment]
Better post a log, because there's no issue with it on my end. Plus it's a requirement for support posts and all. :)
