### ISSUE TITLE
Add to Kodi library?

### ISSUE THREAD

**Issue by JayDee696969** [Tikipeter/repository.tikipeter#55]
Any plans to add Kodi library support to this addon? Im not seeing a way to add shows or movies to library with FEN?

**Comment by Tinuz97** [comment]
That would be awesome,so i can load my TV Show Trakt collection list to library (faster with loading,and if some website goes down,it is already cached).

+1 from me, would be nice 👍

**Comment by Tikipeter** [comment]
Fen already has Library Integration (Subscriptions). Go to Subscriptions->Directories in settings to set your Movie and TV Show folders (or leave the default path). Then you have a couple of ways to implement Subscriptions:

* Add individual Movies/Shows by bringing up Context Menu->Add/Remove->Add To...->Add to Fen Subscriptions. Do this for any number of Movies/TV Shows.

* Or you can go to Settings->Subscriptions->Trakt Lists and enable 'Use Trakt Lists for Subscriptions'. Then assign a Trakt list for Movie Subscriptions and/or TV Show Subscriptions. Follow the process Fen will guide you through, and at the end that Trakt list will be monitored by Fen. When a Subscription update is triggered, either automatically or by going to Tools->Update Subscriptions, Fen will remove from your Subscriptions any Movies/Shows that have been removed from the Trakt List, and add any new Movies/Shows that have been added to that Trakt List. Trakt Lists available to use for Fen Subscriptions are the 'Collections' lists, 'Watchlist' lists, any Personal List or any Liked List.

With either method Fen will add any new episodes from subscribed TV Shows into your Kodi library.

If you choose to use a Trakt list/s for Subscriptions, then the option to add media individually will not appear in the Add/Remove menu.

Monitor what you have in your Subscriptions by navigating to 'Subscriptions' in the root menu, or each of the Movies and TV Shows menus.

Any issues let me know.

**Comment by Tinuz97** [comment]
Thx for the tip (works great for me with Trakt). 👌

**Comment by rizreflects** [comment]
Just out of curiousity, has this feature since been removed? I've been trying to integrate my library but I've not found the subscriptions tab. Any help would be appreciated.
