### ISSUE TITLE
Fails to install master zip

### ISSUE THREAD

**Issue by Arthur1967** [Tikipeter/repository.tikipeter#551]
When I try to install it from a zip file it says it fails but it doesn't really give me a reason why￼

**Comment by Tikipeter** [comment]
Use this link and try again:
https://github.com/Tikipeter/repository.tikipeter/raw/master/zip/repository.tikipeter/repository.tikipeter-0.0.6.zip

**Comment by Tikipeter** [comment]
Otherwise, post a log after trying to install. It always says why.

**Comment by Arthur1967** [comment]
OK I will I just have to figure out how I can take a screenshot of it but I
can’t post it hereThank you for your help

**Comment by Arthur1967** [comment]
It installed perfectly that one you sent I really like your ad on that's why it was so important to me to get thank you￼
