### ISSUE TITLE
Watched Indicators - Set watched in Kodi library when watched in Fen

### ISSUE THREAD

**Issue by ShibajiCh** [Tikipeter/repository.tikipeter#558]
Hi @Tikipeter,

Hope you are doing well.
I just noticed that in the latest Fen version you have removed some settings for Trakt watched Indicators like, "Set watched in Kodi library when watched in Fen" . Could you please bring back this feature as I'm using a hybrid Kodi setup where I watch both local and Fen (Debrid) content, so this feature was really useful to me. Now after removal of this feature I have to manually sync my local library with Trakt everytime I watch anything on Fen so it's really a bit troublesome. In the past you've brought back many features on request by Fen users. So if you do the same for me then I'll be really grateful to you. Thanks in advance! Keep up the great work! 🙂

Thanks and Regards,
ShibajiCh.

**Comment by Tikipeter** [comment]
OK.
Done for next update.

**Comment by ShibajiCh** [comment]
> OK.
> Done for next update.

Thanks a lot @Tikipeter! 🙂 👍
