### ISSUE TITLE
no icon tp go return page

### ISSUE THREAD

**Issue by vinay821007** [Tikipeter/repository.tikipeter#559]
hi, ai just installed FEN because of so many good reviews and was disappointed. The only return is when I m browsing there is no icon to go to the previous page.

**Comment by Tikipeter** [comment]
I'm having a similar experience.

I've been waiting a long time for you to use Fen, and now that you finally have, I am disappointed.

You don't seem to know what the back button does.

**Comment by vinay821007** [comment]
I am really sorry mistyped was not disappointed.  Everything seems perfect figured out everything.
