### ISSUE TITLE
New next up feature

### ISSUE THREAD

**Issue by thefrench1** [Tikipeter/repository.tikipeter#56]
I see in the latest update the next up option is on for TV series. When a TV show comes to an end the next up option appears for TV shows. If I do not click  anything it's canceling the next episode from playing. Is they a way this can be amended so we don't have to click continue each time. Thank you in advance.

**Comment by Tikipeter** [comment]
Not likely, because I got rid of the are you still watching check due to another user not liking it being 2 different windows.

**Comment by thefrench1** [comment]
Hi thank you for the reply. The way you had it set up originally worked great for me. I would turn the window off in ypur settings and it auto played the next episode with no problems. I never used the next up option within Kodi itself.  Now sadly I have to keep clicking on continue when each episode comes to an end in a series I'm watching

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Liquidrag** [comment]
I had the same settings as you did @thefrench1 and it was perfect.

**Comment by Tikipeter** [comment]
Argh.

Let me look at it again. I'll try and re-add the basic notification with no check as to whether still watching. Is that how it used to be for the both of you? Episodes just continued to load one after the other until you manually stopped an episode?

**Comment by thefrench1** [comment]
Hi that would be  great if you can. Yeap I just turned it of so it didn't show the pop up and the episodes just kept playing. Or you could set it  to ask after so many episodes. Just makes binge watching easier when your are watching them one after another.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Tikipeter** [comment]
I'll put it in the next update.

**Comment by thefrench1** [comment]
Sweet thank you so much and thanks for the best add-on out there.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Liquidrag** [comment]
Yes that is the way I have it set, no popup and just plays on for easy binging. Thank you for reconsidering. Here's a screenshot of how the setting used to be. 
<img width="1262" alt="Screen Shot 2022-10-09 at 5 04 39 PM" src="https://user-images.githubusercontent.com/43726430/194781615-3864aced-c159-481c-910c-c6afb52ff7e4.png">

**Comment by Tikipeter** [comment]
From next update, set "Next Episode Alert Method" to "Notification" to regain the functionality you want.

![screenshot00000](https://user-images.githubusercontent.com/28930002/194788225-c295094f-e564-493f-9e7b-be34e0476f03.png)

**Comment by pyro12** [comment]
If I could make a suggestion...

At some point in the past, and I apologize that I can't give credit where credit is due - i simply don't recall, but I used an app that had a 'binge mode' where when that was 'ticked' episodes would play continuously until either the series ended or a user interrupted it.  If 'binge mode' wasn't ticked then the app would stream the selected episode and stop.

Perhaps this could make almost everyone happy and also be relatively simple to implement?

Ahhh, nevermind.  I came to my PC all excited to offer what I thought was a good suggestion and I now see that Tikipeter has beaten me to it and resolved the issue.

Thank you for all of your work.  I use your app daily and I appreciate the effort it takes to keep refining it.

**Comment by Tikipeter** [comment]
>relatively simple to implement?

LOL That's certainly debatable. :) But yeah, this is a feature that's been in Fen for a long time. Just last update I took this out, in favour of only having a window alert appear at the end of each episode. In the past you could choose to have that window, or a simple notification and auto continue watching.

**Comment by Tikipeter** [comment]
Good to hear.

**Comment by thefrench1** [comment]
Thank you so much for adding this back quickly it really is appreciated.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
