### ISSUE TITLE
Sources

### ISSUE THREAD

**Issue by jan1mal** [Tikipeter/repository.tikipeter#56]
Hi I just started trying to use your FEN addon using the External scrapers.  I notice an issue I can't seem to find any setting which controls it. 

When selecting a movie to watch, Dora & the lost city of gold for example, the popup scraping progress dialog lists a total of say 40 sources (35 SD) but when it is finished & lists the sources it only lists 7 only two of which are SD and in my case non of the 7 sources work.  Why doesn't it display the full list of scraped sources? Is there a setting somewhere?

**Comment by Tikipeter** [comment]
It is probably the removing of duplicate links. You can turn that off in Settings->Scrapers->External->Remove Duplicate Links. It won't give you any more USEABLE links, though. Also (and probably as much a reason for the discrepancy) Fen now removes Openload and Streamango free links before showing results, as they have been shut down. Also, if you are going to be searching for Movies that are still in the Theaters (I know Dora has been released), you should also enable Settings->Results->Sorting & Filtering->Include Pre-Release Results. This will stop Fen removing any CAM etc results it identifies (although that is not as much an issue with the External Scrapers).

**Comment by jan1mal** [comment]
OK I see. Thanks for the quick response.  I managed to watch several other movies without issue - I guess Dora's not very well sourced.  Thanks for your efforts.
