### ISSUE TITLE
Kodi started crashing after I updated to the latest version 2.0.24

### ISSUE THREAD

**Issue by KalAvroniev** [Tikipeter/repository.tikipeter#560]
Have not had this before but started happening a lot after the latest update. 
Not 100% sure if it is the addon or not but that is the only addon I have installed.
Video plays for a bit and then once it reaches the end of the preloaded/buffered content is stops. And when I try and stop the video Kodi becomes non responsive for a very long time
[kodi.old.log](https://github.com/Tikipeter/repository.tikipeter/files/7072265/kodi.old.log)

**Comment by KalAvroniev** [comment]
I tried with the 2.0.23 same issue. Attached degub log
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/7072450/kodi.log)

I also found this wich is exactly the same, so maybe not Fen related - https://forum.kodi.tv/showthread.php?tid=364140

**Comment by Tikipeter** [comment]
Almost never an addon issue when there are problems with playback.

**Comment by KalAvroniev** [comment]
Any advise what I can look at?

**Comment by Tikipeter** [comment]
Afraid not, except for the fact that the Kodi forum thread you posted above looks to be the issue you are having. You have that same error present in your log.

Keep an eye on that thread and see if the devs have a solution.

**Comment by KalAvroniev** [comment]
Reply does not seem like they would be doing much:
> Not sure if this issue is related to others in this thread, but it appears the log provided contains add-ons and repositories that are in contravention to our Official:Forum rules/Banned add-ons (wiki) policy and as such we can offer no support. I suggest it's quite unusual to have Kodi stop playing mid stream as reported in these forums, and the suspect 3rd party scripts and add-ons are in play. Perhaps Plex forums can cast some light.

**Comment by KalAvroniev** [comment]
Just a heads up. I was able to reproduce the issue on MacOS, Windows 10 and FireTV stick.

**Comment by Tikipeter** [comment]
Yes that is quite possibly the reason.

**Comment by Tikipeter** [comment]
I would try switching your CDN in the real-debrid settings. Try another location and see if that helps.
