### ISSUE TITLE
Playing Easynews links, the page gets stuck

### ISSUE THREAD

**Issue by isaikrishnatej** [Tikipeter/repository.tikipeter#561]
![image](https://user-images.githubusercontent.com/61765468/131451894-f3b13504-83bd-40ca-ade7-0a04b8dd71b2.jpg)

this happens on my Chromecast and Mac 

also this is working with Venom.

**Comment by Tikipeter** [comment]
If you're using Kodi 19.1 (I assume you are), then Easynews is problematic on Fen. It is a Kodi bug that will be fixed likely on Kodi 19.2 when it is released.

This has been written in red writing at the top of the Fen changelog for over 8 weeks now so users are informed of the issue.

Either roll back to Kodi 19.0 or don't use Fen for Easynews until Kodi 19.2 is released.

Certainly nothing wrong with using the wonderful Venom addon.

**Comment by isaikrishnatej** [comment]
I’m sorry Tiki, I was unaware if this.
Thanks for clarifying.
