### ISSUE TITLE
Fanart.tv default for artwork

### ISSUE THREAD

**Issue by ivarbrandt** [Tikipeter/repository.tikipeter#562]
Can you please add the option to enable the preferred artwork provider to be fanart.tv? I've noticed that when using posters the artwork comes from TMDB but when using landscape, the artwork comes from fanart.tv.

I can't really say that this would have any functional use, I just really like fanart.tv over TMDB for artwork.

BTW I never got a chance to thank you for implementing the choice between percentage and time based for the next episode pop up window. It's been working flawlessly so thank you!

**Comment by Tikipeter** [comment]
I'm still thinking on this......

**Comment by Tikipeter** [comment]
Done for next update. Settings->Metadata->Enable Extra Art->Use as Default Provider for Posters & Fanart (Slow).

If you want to use this, then you will need to clear your metadata (Tools->Clear Databases and Clean Settings Files->Clear Meta Cache). YOU ONLY NEED TO CLEAR YOUR METADATA THIS FIRST TIME OF TURNING IT ON. If in the future you wish to enable/disable the setting, you can do it without clearing metadata. Users who do not wish to utilize the setting will not need to clear metadata.

**Comment by ivarbrandt** [comment]
> Done for next update. Settings->Metadata->Enable Extra Art->Use as Default Provider for Posters & Fanart (Slow).
> 
> If you want to use this, then you will need to clear your metadata (Tools->Clear Databases and Clean Settings Files->Clear Meta Cache). YOU ONLY NEED TO CLEAR YOUR METADATA THIS FIRST TIME OF TURNING IT ON. If in the future you wish to enable/disable the setting, you can do it without clearing metadata. Users who do not wish to utilize the setting will not need to clear metadata.

AWESOME!!! Thanks so much! I look forward to testing it out :)

**Comment by Tikipeter** [comment]
>Will this also include the clearlogo from fanart.tv?

Yes, but this is currently also the case. So there's no change there.

**Comment by ivarbrandt** [comment]
> >Will this also include the clearlogo from fanart.tv?
> 
> 
> 
> Yes, but this is currently also the case. So there's no change there.

Right on! Thanks again!

**Comment by Tikipeter** [comment]
As I knew already, fanart.tv are very slow in serving their images. This will have a very noticeable effect when the images are called for the first time. They are of course cached by Kodi after that initial download and are served immediately.

I have no idea of the reasons for your preference for fanart.tv artwork, but if it is because the TMDb artwork is not of high enough resolution, that can be changed in the settings to `Original` and will provide much clearer artwork from TMDb than the default setting provides. You would need to clear the meta when changing that setting though. Just something I thought I'd mention in case that was the main reason for wanting fanart.tv posters and fanart.

**Comment by ivarbrandt** [comment]
> As I knew already, fanart.tv are very slow in serving their images. This will have a very noticeable effect when the images are called for the first time. They are of course cached by Kodi after that initial download and are served immediately.
> 
> I have no idea of the reasons for your preference for fanart.tv artwork, but if it is because the TMDb artwork is not of high enough resolution, that can be changed in the settings to `Original` and will provide much clearer artwork from TMDb than the default setting provides. You would need to clear the meta when changing that setting though. Just something I thought I'd mention in case that was the main reason for wanting fanart.tv posters and fanart.

I'm totally ok with waiting a little longer for the images to load as the images are absolutely beautiful. 

Thanks for the tip, I appreciate it. However, it's not about the resolution since I already set the resolution to HIGH and the resolution provided from the resulting images is more than sufficient for my use. I just prefer fanart.tv's images because they're more artistic compared to TMDb's images. I feel like the best way I can explain the difference is that fanart.tv's images are actual art compared to TMDB's images. Fanart.tv's images have sharper contrast, deeper colors, and more saturated hues. This makes them really pop on the screen. They also evoke a sense of beauty that TMDb's images don't.

So as you can see, I have deeply personal reasons for my preferences.

I'm very grateful to you for implementing this awesome feature.

**Comment by Tikipeter** [comment]
No worries. You are right, it's quite often much more artistic images. And once they're cached, they're cached.

**Comment by ivarbrandt** [comment]
> No worries. You are right, it's quite often much more artistic images. And once they're cached, they're cached.

I just updated Fen and duuuuude the new artwork is sickkk! Thanks sooo much!
