### ISSUE TITLE
Play next popup 0-120 seconds

### ISSUE THREAD

**Issue by tundrablasen** [Tikipeter/repository.tikipeter#563]
Currently, it looks like you can set the time period for the Play Next pop up between 0-60 seconds in the settings.

Would it be possible to extend this period to 0-120 seconds? Default settings can continue to be 20 seconds, but I notice that most series have a 90-120 second end.

So I'd rather see the Play next popup a little longer instead of having to fast forward every time for the pop up to appear at all.

Thanks a lot For considering

**Comment by Tikipeter** [comment]
Done for next update.
