### ISSUE TITLE
Cannot connect to repo server

### ISSUE THREAD

**Issue by textroynado** [Tikipeter/repository.tikipeter#564]
I've been using Fen for a very long time and it is hands down the best add-on avialable to kodi in my humble opinion.  I normally run it on Linux desktop but am having an issue with one of my machines.  Tonight I installed Kodi on a Windows10 pc (which I've never done before) and when adding the repo to file manager as https://tikipeter.github.io/  it keeps telling me it cannot connect to server.  I've never had any issues with this on my Linux machines.  Any ideas? Or is the repo temporarily down by chance?
I do have internet connection and am able to download and install other add-ons such as subtitles, TMDB, Trakt, etc.

**Comment by omaramiromo** [comment]
Yup. U need download the repo zip from the repo and install by zip file

**Comment by Tikipeter** [comment]
That's correct. You need to download the zip file from here and install manually. The github.io http link has been closed.
