### ISSUE TITLE
Resume watching from library across multiple devices

### ISSUE THREAD

**Issue by queensryche6** [Tikipeter/repository.tikipeter#565]
Hi Tikipeter,
First of all I want to thank you and congratulate you on all the hard work you have put on your addon!

This is not a bug but an enchancement by bringing back an old feature.

I am using Fen with library integration with the tmdbh addon. When I was using the 1.8.44a version of your addon I was able to  resume an episode or movie on another device. A popup asking me to resume appeared as if I was watching a library item. Then fen would start the video from the current resume position. Upon update to the latest version this is no longer possible. I don't know how difficult or possible is to bring back that feature, but it would be fantastic for me!!

Again thanks for all the hard work!

**Comment by Tikipeter** [comment]
Not unless you've got a copy of 1.8.44a you could post here.

The code for that is long gone I'm afraid, and I'm not prepared to re-write it.
I MAY put it back in if you can give me the old version, depending how disruptive the code is.

But, moving forward, there is no support for either TMDbHelper or library playback in general, so it may be the case that Fen is not the addon that best suits your needs anymore.

**Comment by queensryche6** [comment]
I do have it. Do you want me to zip the addon folder and upload it somehow?

**Comment by Tikipeter** [comment]
Yes please. You should be able to drag the zip into the comment window here and it will upload.

**Comment by queensryche6** [comment]
[plugin.video.fen.zip](https://github.com/Tikipeter/repository.tikipeter/files/7106389/plugin.video.fen.zip)

Hope you can implement it again. Even if you don't thanks for your effort!!

**Comment by Tikipeter** [comment]
I've implemented what's needed in theory get this running again, but when looking at the current player files for tmdbhelper, they don't have a `library=True` param, which is needed for the 1.8.44a code to work correctly.

It's possible you have older player files for tmdbhelper, or you have modified files that have the `library=True` param in them.

Anyway, I've done what I can do for this, and it will be in the next update. Hopefully it works for you.
