### ISSUE TITLE
Scraping error and next episode list not showed

### ISSUE THREAD

**Issue by omaramiromo** [Tikipeter/repository.tikipeter#567]
As per title, after update to v2.0.26, all movie and tv episode failed to scraped and show an error msg

Kodi log as per below

https://pastebin.ubuntu.com/p/gCmFHytxpP/

**Comment by Tikipeter** [comment]
I can't view that log without "logging in" to the paste site, so as a guess I would say make sure you have the latest version of script.tikiskins installed. If not, uninstall Fen and script.tikiskins and then reinstall from the repository.

**Comment by omaramiromo** [comment]
OK. Sorry for the trouble. Issue solve with your suggestion
