### ISSUE TITLE
Next episodes not updating newly released episodes 

### ISSUE THREAD

**Issue by IG2022** [Tikipeter/repository.tikipeter#569]
The next episode section is not updating newly released episodes for Tv shows. The episodes are showing in the next up section on the trakt website but not in the next episode section in fen. This seems to only happen when it is a newly released episode if for example you start a show that already has episodes that have aired they show up in the next episode section but for newly released episodes they do not. I have also navigated to the the show outside of the next episode section and it indicates that it has aired and has not been watched yet. I have uninstalled and reinstalled fen aswell as reauthorized trakt and cleared the setting and cache and I am not seeing any change. 

I thought this could just be a trakt issue but I used the addon venom to see what the next episodes section looked like and it included all the newly aired shows that are missing in fen. Also some of the newly aired shows that were in my next episodes section yesterday before the update have since disappeared even though they have not been watched. 

I also checked the next episode manager and none of the shows are hidden. 

I have uploaded a log below for you to take a look. Let me know if you need anything else from me.

[Log](https://pastebin.ubuntu.com/p/KZGnJgzYTf/)

**Comment by Tikipeter** [comment]
That log is not accessible to me unless I "Log In" to the paste site.

**Comment by IG2022** [comment]
Sorry about that, I think the website must have changed the view options for non users. 

Herr is another one. I hope you are able to view this one. 

https://paste.kodi.tv/utokepusas

**Comment by Tikipeter** [comment]
Perfect. Thanks. 👍

**Comment by Tikipeter** [comment]
Nothing in the log.
Pick one show where this is happening, tell me the last episode you have watched in it and the episode you should expect in the Next Episodes that is not there.

I'll have some questions apart form this, but let me see myself first.

**Comment by IG2022** [comment]
> Nothing in the log.
> Pick one show where this is happening, tell me the last episode you have watched in it and the episode you should expect in the Next Episodes that is not there.
> 
> I'll have some questions apart form this, but let me see myself first.

There are a couple... But one would be Titans, I last watched season 3 episode 5 last week and  season 3 episode 6  aired on the 2nd of September but is not showing in the next episode list.

**Comment by Tikipeter** [comment]
Found the issue.
Fix will be in next update, which I'll try and push now if I can.

**Comment by xyzfre** [comment]
On my end One example is Supergirl also airs on September 2￼￼nd

**Comment by IG2022** [comment]
> Found the issue.
> Fix will be in next update, which I'll try and push now if I can.

That was quick! Thanks for looking into that for me I appreciate it.

**Comment by Tikipeter** [comment]
Was to do with one of the "structural changes" I made last update. I'm surprised really that this is the only issue currently, seeing as I moved some very widely used functions around. The search program I'm using must be doing a pretty good job. But it missed this one. :)

**Comment by rishisss23** [comment]
Hi Tikipeter
I have noticed episodes not getting resume point marked if i close a tv show more than 1 time. 1st time it is getting marked. Is it because of this issue. Didn't matter much so didn't open an issue. 
If you need I can open an issue with log. Thanks

**Comment by IG2022** [comment]
> Was to do with one of the "structural changes" I made last update. I'm surprised really that this is the only issue currently, seeing as I moved some very widely used functions around. The search program I'm using must be doing a pretty good job. But it missed this one. :)

Perfect. Everything else seems to be working fine. There was another error I noticed when trying to use the "clean settings cache" function but that's a separate issue if it persists after the next update I'll open another issue.

**Comment by Tikipeter** [comment]
@rishisss23 working fine here. Open a new issue if you want, and I'll see what might be happening for you.

@IG2022 I've tested that too and it is working OK on my end. Might have been a nice Kodi "glitch".  I'll keep an eye on it.

**Comment by IG2022** [comment]
Issue resolved with the update. Thanks alot!

**Comment by xyzfre** [comment]
Same here working great again thank you Tikipeter ,the new scraping window ￼looks AMAZING
