### ISSUE TITLE
A doubt

### ISSUE THREAD

**Issue by rishisss23** [Tikipeter/repository.tikipeter#57]
Hi

I have a doubt..After playing an episode or movie;fen does 2 refreshes;one soon after stopping the video and next in 5 to 7 seconds. 
One user has already asked this i think;please don't get angry.. Are these both refreshes needed?? 
Please close this if it is a foolish question.. 
Thanks..

**Comment by Tikipeter** [comment]
Are you referring to within Fen, or widgets on the home window?

**Comment by rishisss23** [comment]
Within fen:in next episodes;tv shows; movies everywhere.. Attaching a screen shot from mobile;but on my shield the time for second refresh is like more seconds after the first refresh

**Comment by rishisss23** [comment]
![Screenshot_2022-10-10-22-03-01-879_org videolan vlc](https://user-images.githubusercontent.com/76693986/194913691-844d91be-04ef-411f-ae7f-3e0141597f0b.jpg)
Within fen:in next episodes;tv shows; movies everywhere.. Attaching a screen shot from mobile;but on my shield the time for second refresh is like more seconds after the first refresh

**Comment by Tikipeter** [comment]
That's one refresh. The container has to load after playback ends. Then there is a refresh to set the new resume point on that first episode there.

**Comment by rishisss23** [comment]
Okk.. Thanks
