### ISSUE TITLE
Crashing on Subscription Update

### ISSUE THREAD

**Issue by dm2912** [Tikipeter/repository.tikipeter#57]
Having an issue where anytime I try to do a subscription update its crashing.

My subscription folders are currently set to a folder on local network via SMB (which maybe is the issue). Have tried with both pointing Fen to the smb folders, and pointing to local folders with advanced settings used to do a path substitution to the lan. 

The original export is fine, its any subsequent updates are the problem

Log when trying to do full sync from tools menu https://paste.kodi.tv/osinewejat (its at the end)

Log when trying to add single movie to subscription https://paste.kodi.tv/gedahohofe (again, at the end of the logfile)

**Comment by dm2912** [comment]
and full debug log.. booted, sync subscriptions, log

https://paste.kodi.tv/ifamupexaz

**Comment by dm2912** [comment]
I might have fixed it.

Uninstalled, cleared data, reinstalled

Left the subscription folders as default and used path substitution and it seems to be doing it without errors...

**Comment by Tikipeter** [comment]
Let me look into this dm2912. Subscriptions need to work over smb, if that is the problem. I'll do some testing. Thanks for the logs and info. :)

**Comment by dm2912** [comment]
I have it working after a reinstall and setting up from scrath

but Ive left the directories as default (as opposed to pointing them to smb) and set it to smb with pathsubstitution in advanced settings instead and its playing ball nicely.

**Comment by Tikipeter** [comment]
OK then. I tried to replicate this issue, but I could not. It never crashed for me. Mind you, I wasn't able to test on Android OS.

I'll close this for now since you are satisfied with your fix and I have other issues to sort out, but I would still like to get this fixed eventually.

Thanks again for the report dm2912. :) :)

**Comment by dm2912** [comment]
Its  returned again, not updating subs today. 

Gonna revert it to default directories with no path substitution and try that for a few days and see if the smb and path sub causing it, or if its some other trakt/android issue. 



(add on is great btw, love that it can scan local collection/download folder before scraping.. makes life so much easier - i have netflix account which does library export in kodi so from within fen it recognises the netflix stuff and plays from there which is ace :D)

**Comment by Tikipeter** [comment]
I've made some changes to Subscriptions for the next update (v.1.5.71). It may help with this issue.

**Comment by dm2912** [comment]
At the moment (touch wood) all seems to be going fine. Im using path subs to move it to smb and Ive had no subscription issues since the bump to 1.5.71
