### ISSUE TITLE
Resume point not marked if closing the episode more than 1 time before ending

### ISSUE THREAD

**Issue by rishisss23** [Tikipeter/repository.tikipeter#570]
Hi Tikipeter

My fen resume points not marked if closing the episode more than 1 time before ending. I usually watch only tv shows;this started after 2.0.18 update. So I used to fast forward and watch. I am facing this in my Android mobile windows laptop and shield tv. Since it is localized to me I think some of my setting conflict. 

I again re installed kodi actually many times to change all setting and see;but didn't help. So creating an issue for you to have a look. 

If i play a video after closing for second time it resumes from my 1st resume point. For example if i close a video at 3 minutes next time play from 3 minutes but again if I close at 6 minutes next time plays from 3 minutes only and next episode window dont pop up and marked as watch also wont work after that;but if i clear the progress after that 2nd time everything back to normal. Hope you understood what I am trying to say.. Thanks for your hardwork.. Always appreciated

[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/7109149/kodi.log)

**Comment by Tikipeter** [comment]
Test this without autoplay enabled and see if it stops happening.

What are your Autoplay Next Episode settings?
* Show Next Episode Window (Enabled/Disabled)?
* Show Window Based On (Percentage Played/Time Remaining)?
* Show Window Before End?
* Episodes Watched Before Still Watching Check?

and then also:
* Automatically Resume Playback (Never/Always/Autoplay Only)?

**Comment by rishisss23** [comment]
> Test this without autoplay enabled and see if it stops happening. Still happening same
> 
> What are your Autoplay Next Episode settings? On
> 
> * Show Next Episode Window (Enabled/Disabled)? Enabled
> * Show Window Based On (Percentage Played/Time Remaining)? Time remaining actually tried both
> * Show Window Before End? 30s
> * Episodes Watched Before Still Watching Check? Tried with 0;1;3
> 
> and then also:
> 
> * Automatically Resume Playback (Never/Always/Autoplay Only)? Always

**Comment by rishisss23** [comment]
This happened actually from the update 2.0.18 when you changed "Show Next Episode Window " from percentage based to time remaining. Hope I am helpful

**Comment by Tikipeter** [comment]
I'll have some extra logging in the next update which will hopefully reveal what is happening.

**Comment by rishisss23** [comment]
Okk thanks.. Actually i tried with all settings in all scenarios;but since it wasn't much of a problem i didn't mind actually.. Thank you so much for your time

**Comment by ivarbrandt** [comment]
I'm having the same issue. It also doesn't mark the episode as watched after resuming an episode from the previous resume point.

My settings are:

    Show Next Episode Window (Enabled)
    Show Window Based On (Percentage Played)
    Episodes Watched Before Still Watching Check (3)
    Automatically Resume Playback (Never)

**Comment by rishisss23** [comment]
Hi Tikipeter
I had fen v2.0.17 on my laptop so I tried installing that zip as update and resume worked fine after downgrading. Resuming correctly with the same settings.

**Comment by Tikipeter** [comment]
Please test with 2.0.28 and post  log of something going wrong.

**Comment by rishisss23** [comment]
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/7113000/kodi.log)
Hi
Thanks for your time and support. This is the log with new update;after trying with 2 videos and same problem. 
Can you please have a look.

**Comment by rishisss23** [comment]
[kodi_2.log](https://github.com/Tikipeter/repository.tikipeter/files/7113073/kodi_2.log)
Tried again;attaching 1 more log. I don't know to read log but I think some error is showing in this log.

**Comment by Tikipeter** [comment]
This gives me something to go on. Good job.

**Comment by Tikipeter** [comment]
Check if things are working with 2.0.29.
If not, I'll need another log.
Hopefully it's fixed though.

**Comment by rishisss23** [comment]
Yes... Fixed... Wonderful!!! 

Thank you Tikipeter.. Good job as always.

**Comment by rishisss23** [comment]
May I ask why only me faced the problem?

**Comment by xyzfre** [comment]
Working again 👍🏼Thank you for all your hard work Tikipeter

**Comment by Tikipeter** [comment]
Thanks for reporting back. 👍
