### ISSUE TITLE
Backgroud Scraping Progress

### ISSUE THREAD

**Issue by omaramiromo** [Tikipeter/repository.tikipeter#572]
Just a request if possible. Can u add a background scraping progress? I am sorry if this one already discussed, but i can't find any from past closed issue. Thank you

**Comment by Tikipeter** [comment]
I was planning on doing this after coding the custom scrape progress window (which has just been added last couple of updates), but I've changed my mind on it. I simply don't see the use of it.

What is your reasoning for wanting it? Perhaps you will change my mind.

**Comment by omaramiromo** [comment]
It just my personal request actually, i am just really keep thing hidden since the scraping process is just showing the no cached file available. Its not demand from me just asking. What undoing now is more that perfect

**Comment by Tikipeter** [comment]
I'm not willing to have "nothing" when Fen is doing a scrape, but I'll likely add something small in the top right corner to let the user know a scrape is happening.

**Comment by omaramiromo** [comment]
> I'm not willing to have "nothing" when Fen is doing a scrape, but I'll likely add something small in the top right corner to let the user know a scrape is happening.

That is what i mean. Sorry for my english and trouble.

**Comment by Tikipeter** [comment]
I've decided against this for now.
