### ISSUE TITLE
Boxset

### ISSUE THREAD

**Issue by djdirty60** [Tikipeter/repository.tikipeter#573]
Hello, 

Is it perhaps possible with your own film collections, that the films that have a box set are also in a box set, such as Harry Potter, lord of the rings, etc etc. 

Thank you in advance

**Comment by Tikipeter** [comment]
From your Trakt Collection do you mean?

I'll have a look but I'm almost 100% sure that Kodi would not allow me to do that. We'll see....

Good idea though. :)

**Comment by djdirty60** [comment]
Yes I mean, treats collection, Yes, it's so irritating when you have so many films, half of which are almost all successors, that they are all standalone instead of looking good in box sets.  Like you have a library in kodi.  Will be great if you can.  I think it will also make a difference in loading for most people.

 thanks in advance

**Comment by Tikipeter** [comment]
I've had a good look, and unfortunately this is not possible. :(

**Comment by djdirty60** [comment]
Don't care, unfortunately nothing can be done, thanks for watching
