### ISSUE TITLE
Fen Error - Rescrape & Select Source

### ISSUE THREAD

**Issue by ShibajiCh** [Tikipeter/repository.tikipeter#574]
Hi @Tikipeter ,

Hope you are doing well.
After today's latest update of Fen version 2.0.28 I noticed that if I'm selecting "Rescrape & Select Source" option from the Fen context menu then a "Fen Error" is appearing and the rescrape process is failing. I tried it on both my Nvidia Shield TV Pro and also on my Windows 10 PC. The error occurred in both the instances. So the issue is not device specific.

Here are my logs:

Nvidia Shield TV Pro Log: https://paste.kodi.tv/ucivugekuk.kodi

Windows 10 PC log: https://paste.kodi.tv/udasegoqat.kodi

Could you please look into the issue and try to provide a fix?

Thanks & Regards,
ShibajiCh.

**Comment by JFG1000** [comment]
I also noticed this and was about to post. Thankyou

**Comment by xyzfre** [comment]
I'm also having the same exact issue I was going to post as well so thank you for sharing￼

**Comment by Tikipeter** [comment]
This is fixed in the next update. I'll try and push it today.

**Comment by ShibajiCh** [comment]
> This is fixed in the next update. I'll try and push it today.

Thank a lot @Tikipeter!

By the way, the new Fen scraping progress window looks awesome! 🙂

Thanks and Regards,
ShibajiCh.
