### ISSUE TITLE
Fen addon stopped working

### ISSUE THREAD

**Issue by guryoram** [Tikipeter/repository.tikipeter#576]
Whenever I click on a movie or TV show title I get "Fen Erroe" and nothing happens.
I am using Kodi 19.1 version on Windows10.
The addon has worked fime for me at least on last 6 months. It was my favorite Kodi addon.
The relevant log file can be browsed in this site: https://paste.kodi.tv/ubegufeluy

Thank you,
YB

**Comment by Tikipeter** [comment]
You are 2 versions behind on Fen, and about 20 versions behind on Tikiskins. It's surprising anything works at all.

Uninstall Fen and Tikiskins and then reinstall Gen from the repository.

I'd also consider a cleanup of your installed repos. There's a lot there, some of which are considered potentially untrustworthy. Every aspect of your interactions with Kodi would be improved if you were just running the things you need and use on your install.

**Comment by guryoram** [comment]
Thank you.
It was helpful. The problem has been solved.

YB
