### ISSUE TITLE
Download Directory Settings Broken in 1.5.70

### ISSUE THREAD

**Issue by dm2912** [Tikipeter/repository.tikipeter#58]
After upgrade to 1.5.70 directory settings for downloads are missing in Android (tested on two devices.)

![Screenshot_20191119-044950](https://user-images.githubusercontent.com/25871666/69117767-b400c200-0a88-11ea-8742-5b6a799c8f61.png)

Reverting to 1.5.69 fixes it

![Screenshot_20191119-045055](https://user-images.githubusercontent.com/25871666/69117766-b3682b80-0a88-11ea-94a9-2cce7068cd28.png)

**Comment by Tikipeter** [comment]
Oops! Thanks dm2912. I'll push a quick fix for this.
