### ISSUE TITLE
Error on opening Fen settings 

### ISSUE THREAD

**Issue by inky-pits** [Tikipeter/repository.tikipeter#58]
I wanted to find the option to have episode thumbnails rather than poster for my next up list of episodes, but unfortunately trying to open Fen settings brings up the following error

https://paste.kodi.tv/vipopuwiyi

Nvidia Shield TV Pro, Kodi Maven Nexus 11/19/2023, Fen v3.0.18

Edit: I've realized on reading change log the settings menu item needs to be manually removed as it has been merged into the tools menu. Apologies for the unnecessary post. I just need to find the option for episode thumbnails now.

**Comment by Tikipeter** [comment]
>I've realized on reading change log the settings menu item needs to be manually removed as it has been merged into the tools menu

Correct.

>I just need to find the option for episode thumbnails now.

No such option in Fen. Fen provides the skin with ALL available artwork, and the skin decides what to show. Sounds like you need to change "views" within the skin to get episode thumbs instead of posters.

**Comment by inky-pits** [comment]
Hi,

Thank you for your reply. I'm a long time user of the default Estuary skin with TV seasons and episodes set to wide list. Today is the first time next episodes has displayed posters instead of thumbnails. I've just tried switching Estuary skin views, but the three available all shows posters. I shall check elsewhere in the skin settings.

**Comment by Tikipeter** [comment]
Screen capture please.

**Comment by Tikipeter** [comment]
![screenshot00000](https://user-images.githubusercontent.com/28930002/195161839-2adbd1d7-7a85-4f7c-8e18-26976f766619.png)

Here's mine, showing thumbnails like it should.

**Comment by inky-pits** [comment]
![PXL_20221011_174103996](https://user-images.githubusercontent.com/78259034/195162482-2116333a-53fd-4f6d-a591-0c38f542f6e7.jpg)
That's interesting, mine is still showing poster, it started happening yesterday I believe.

**Comment by Tikipeter** [comment]
It is interesting.

What about through normal episode lists? i.e. go to the TV Show, navigate through the season container into the episodes container. Are they showing posters too?

**Comment by inky-pits** [comment]
Fen is the only video add-on I have installed with Wako as a backup on my phone. It is Kodi, but modified by Maven to be compatible with Dolby Vision
https://www.kodinerds.net/index.php/Thread/69428-Maven-s-Kodi-Builds-f%C3%BCr-Android/?pageNo=54&s=c957514469e0545ea489b49ca2cb1ac07a82f33a

You reminded me I updated my Kodi Nexus by Maven the other day. It used to be his Matrix, but that was not saving audio settings. Perhaps I need to roll back my Kodi version

**Comment by Tikipeter** [comment]
The Nexus build might have a change in Estuary that is causing this.

Let me check my Nexus install before doing any uninstalling yourself. I don't have the Maven build, but vanilla Kodi should be the same in regard to thumbnails.

**Comment by Tikipeter** [comment]
![screenshot00001](https://user-images.githubusercontent.com/28930002/195187465-208c593e-288a-4d62-b2c6-82f2f472bc43.png)

Still showing correctly on Kodi 20 Nexus Alpha 3.
I'm stumped....

**Comment by inky-pits** [comment]
Okay, I'll roll back my Kodi Nexus Maven in a bit to the first Oct version which was okay and let you know.  Thank you for taking the time to check.

**Comment by inky-pits** [comment]
I tried clearing Fen cache, Kodi cache, and rolling Nexus Maven back to Oct 1st, which is the earliest available from the downloader, but the same time happened. It's a strange one, Nexus had been stable, but you never know since vanilla Kodi was fine. Maven has been handy for Dolby Vision.

**Comment by Tikipeter** [comment]
I'd install another addon and see what artwork Estuary displays for it.

**Comment by inky-pits** [comment]
Late last night I installed the latest version of Kodi Maven Matrix to compare. After copying the .kodi folder across, episode thumbnails worked as expected in this version. I had originally switched from vanilla Kodi to Maven Matrix for Dolby Vision, but an audio bug regularly caused audio to be output as stereo. This issue didn't happen in the Maven Nexus version, but I guess being alpha it has its quirks. All being well the audio issue will not return with Maven Matrix.
