### ISSUE TITLE
Remove duplicate results

### ISSUE THREAD

**Issue by ShibajiCh** [Tikipeter/repository.tikipeter#580]
Hi @Tikipeter,

Hope you are doing well.
I'm on Fen latest version 2.0.30. I guess there was a setting to remove duplicate results while scraping earlier in Fen. Have you removed it? If so then could you please restore it again as lots of duplicate results are appearing after scraping? It will be really helpful.

Thanks and Regards,
ShibajiCh.

**Comment by Tikipeter** [comment]
Fen removes duplicates automatically.
Please post a screen shot of duplicates.

**Comment by ShibajiCh** [comment]
> Fen removes duplicates automatically.
> Please post a screen shot of duplicates.

Hi @Tikipeter,

Oh, that's weird then. I don't know why so many duplicate results are appearing recently. Please see below attached images which shows the duplicate results:

![IMG20210911113947](https://user-images.githubusercontent.com/65297828/132938386-beee6ea7-73df-46a8-a9b6-87a5144396a8.jpg)

![IMG20210911114023](https://user-images.githubusercontent.com/65297828/132938393-4af2b98e-f742-4dea-942d-2ee63f42cfec.jpg)

Kindly check and do the needful.

Thanks and Regards,
ShibajiCh.

**Comment by Tikipeter** [comment]
Unfortunately you're going to find all those results are not duplicates. I know it looks like some of them are, but they're likely not.

Fen checks both the URL and (for torrents) the HASH of the result. Any duplicates are removed using those 2 variables.

For torrents, the easiest way to see if 2 results are duplicates is to press Information button on a result. You will get an Info window that will show the HASH value among other things. If the HASH values are different, they are not duplicate results.

Really the answer to your question of why you're getting duplicate results recently is that they are being released that way onto the torrent sites.

Take those Titans results you posted above:
* The first 2 results and the 4th result all share the same name, but each have different HASHES, so they are unique torrents.
* The 3rd result you can see already has a different filename with `[TGX]` added to the end of the name, and of course it also has a different HASH value.

If the URL is unique and the HASH is unique, then that is a unique result and it won't be filtered.

**Comment by ShibajiCh** [comment]
Hi @Tikipeter,

Thanks for the detailed explanation! 🙂 
It's quite clear to me now. You may close this ticket.

Thanks and Regards,
ShibajiCh.
