### ISSUE TITLE
Fen error - Kodi 19.1

### ISSUE THREAD

**Issue by dashzombie** [Tikipeter/repository.tikipeter#581]
Hello,

I am using a Chromecast w/ Google TV device and I am on Kodi 19.1. 

There is a 'Fen error' when trying to startup a movie or show. Not sure what happened. I recently noticed I was on an older version, so I updated and it worked for a minute,  but now it doesn't. Also have tried uninstalling and reinstalling several times since. Also reauthorized Trakt and Real-Debrid.

https://paste.kodi.tv/opamadurag.kodi

**Comment by Tikipeter** [comment]
You are on version `1.1.08` of `script.tikiskins`. The latest version is `1.1.29`. The error stems from this.

Uninstall Fen (keep settings), uninstall tikiskins and then re-install Fen from the Tikipeter repository. That should bring everything up to date and provide Kodi the required repo linkage to keep updating correctly in the future.

**Comment by dashzombie** [comment]
Awesome! That worked. Not sure how that happened, maybe cause I wasn't updating from the repo for a time.

**Comment by Tikipeter** [comment]
That will be enough for this to happen on Kodi 19. It now links an addon to a repository, so if you don't install from the repo, or you even once don't update from the repo, then that link with the repo will be lost and it won't update from it at all anymore.
