### ISSUE TITLE
Progress dialog unresponsive and Trakt not updating

### ISSUE THREAD

**Issue by MrCeez** [Tikipeter/repository.tikipeter#582]
1. I have this issue when scraping. Sometimes the progress dialog just freezes.
https://bin.disroot.org/?eec691ebe914b1e7#CLT22DmDiqQ1eJaeathPbji1bum7f6FBNGUBcK4bN2Yp

2. Watched shows are not updating even when marked as watched. 
3. Resuming not working either.

Hope the log is of help. Thanks for all your hard work.

**Comment by Tikipeter** [comment]
Nope. Log is no help. I can't open it. The link doesn't lead anywhere.

**Comment by Tikipeter** [comment]
Are you running a "build"?

**Comment by MrCeez** [comment]
No.

**Comment by Tikipeter** [comment]
Just curious.

There's no problem with the code with regard to the scraper progress. It looks like your hardware can't make the dialog in time before a command is sent to it, so right from the start it's shitting itself.

I'll add a try/except for next update. But before then, you'd best use another addon or you'll be stuck with that dialog window with no way to get rid of it.

**Comment by MrCeez** [comment]
Yeah I've had to force close it a few times. I don't know if it's because I changed the default views, but that's the last thing I remember doing before the error. Don't know if that shows in the log as well. 

Any news on the trakt issues?

**Comment by Tikipeter** [comment]
How long have the Trakt issues been happening? Over 24 hours?

**Comment by Tikipeter** [comment]
* Are you getting any error notification to do with Trakt?
* Please list any troubleshooting steps you have completed to attempt to rectify this problem.
* Post me a log that includes trying to mark an item as watched through Trakt.

**Comment by MrCeez** [comment]
- No error when selecting season folder to mark as watched. There is an error when selecting a single a show to mark as watched.

- I have cleared all caches and databases to see if that would rectify the error. Only thing left is to clear everything and start afresh which I am avoiding. My shield which is on 19.1 has the same unmarked issue as well.

- https://bin.disroot.org/?7cf0727c41209fb6#HDAMW6ReAqbBjLMa2z6ryknw72PUuZv3uBu1DRZxWcsv

**Comment by Tikipeter** [comment]
The log shows Trakt is not being connected to successfully. I would try revoking your Trakt auth in My Accounts, and then re-authing it and see if that solves the issue.

Unfortunately from a coding standpoint it looks like there's nothing I can do. Why Trakt is not connecting for these calls I have no idea.

**Comment by MrCeez** [comment]
Just tried revoking but still the same. It seems it's unable to pull the watched status from trakt but I have no idea. I'm grateful that you even looked at the problem. It doesn't affect the awesomeness of Fen.
Thank you for all your efforts🙏🏿

**Comment by Tikipeter** [comment]
>It doesn't affect the awesomeness of Fen

I'm pretty sure it would!
Can you use Trakt on other addons?
It might be time to go the ridiculous route and try something like the old restarting your modem etc. There's something going on.

**Comment by MrCeez** [comment]
😀
Yeah trakt working fine on the other addons like venom & seren. They're able to pull and push watched status

**Comment by Tikipeter** [comment]
Give me one show as an example. Everything I try works fine.

Can you do other trakt related things, like browse your lists and collections?

**Comment by MrCeez** [comment]
Fen
![Screenshot_20210912-021334_Kodi](https://user-images.githubusercontent.com/16075377/132967436-1e1923d4-c2e8-4f48-ad00-4dfe30f6ffa7.jpg)
[](url)

Venom
![Screenshot_20210912-021005_Kodi](https://user-images.githubusercontent.com/16075377/132967452-74acd0e8-711a-48c7-a6a8-f7d98af0deb2.jpg)

**Comment by DaisyF8** [comment]
I was just now in the middle of putting in an efford and also posting a log and describing my Trakt-problems of the last few days. But after multiple reboots and playing a source to procuce a log with consistent Trakt faillure it all started working perfectly again. This fifteen minutes after revoking, syncing, and enabling again and syncing Trakt Auth...

I hope @MrCeez things got solved for you also.  I'm  going to keep an eye on this.
