### ISSUE TITLE
Request for the custom search path for "TRAKT: Search Lists"

### ISSUE THREAD

**Issue by ShibajiCh** [Tikipeter/repository.tikipeter#584]
Hi @Tikipeter,

This is not an issue but a request. Could you please provide the custom search path for "TRAKT: Search Lists" similar to below? 

plugin://plugin.video.fen/?mode=people_search.search&actor_name=

I want to implement it in the Arctic Horizon skin's default search in Kodi.

Thanks and Regards,
ShibajiCh.

**Comment by Tikipeter** [comment]
Not possible right now to do this, but I'll add code next update to support it.

For next update onwards, the path will be:
`plugin://plugin.video.fen/?mode=trakt.list.search_trakt_lists&search_title=`

**Comment by Tikipeter** [comment]
Re-looking at the code, it may well support that path right now in the current Fen version. Give it a try and see.

**Comment by ShibajiCh** [comment]
> Re-looking at the code, it may well support that path right now in the current Fen version. Give it a try and see.

Hi @Tikipeter,

Yes, the above custom search path is working perfectly with Arctic Horizon skin. Thanks a lot! 🙂

You may close this issue.

Thanks and Regards,
ShibajiCh.
