### ISSUE TITLE
Excellent

### ISSUE THREAD

**Issue by derrgoo** [Tikipeter/repository.tikipeter#585]
Hi Tikipeter,

When I think you can't do anymore, your updates keep blowing me away. Thanks for your on going service to the best add on 👍. For me everything working great.

**Comment by xyzfre** [comment]
Absolutely agree much respect for your work Tikipeter ✊🏼 Amazing addon THANK YOU for all your hard work

**Comment by Tikipeter** [comment]
Many thanks for the kind words. It is always appreciated. 🥇
