### ISSUE TITLE
[Feature Request] Prioritize HDR

### ISSUE THREAD

**Issue by rizreflects** [Tikipeter/repository.tikipeter#586]
Would you consider adding an option that lets you prioritize HDR links above everything else? Let's say for example there is a 20gb movie that is HDR, and there is another movie that is 25gb but SDR, Fen will go with the SDR one because it's a larger file size. Do you think you could make it so if HDR is present, then those links will be prioritized above the SDR ones regardless of file size?

Imo this would make autoplay perfect.. as searching for HDR links is the only reason I use source select.

**Comment by derrgoo** [comment]
In the playback section why not just choose only 4K?  Uncheck the rest.

**Comment by rizreflects** [comment]
> In the playback section why not just choose only 4K?  Uncheck the rest. 

Even if 4k is enabled, if a 4K SDR link has a higher file size than a HDR one it will always be chosen first. I'm my case, since I have a HDR TV, I'd like auto select to prioritize HDR links above SDR ones.. if this were the case I'd really have no reason to use source select anymore, as the only reason I use it is to choose HDR.

**Comment by derrgoo** [comment]
Okay, got your point. I have hdr also but really what links Fen pulls on auto are always very good quality. But I guess I am not that picky. Clear picture, no buffering is best for me.

**Comment by Tikipeter** [comment]
@rizreflects 
Check out the setting for the HEVC Files Filter. I could make the HDR filter behave the same way. Include/Exclude/Prefer (Autoplay). The Prefer brings them to the top of the list for autoplay. The caveat is it brings ALL matches to the top of the list (independent of quality i.e. 4K, 1080p etc).

**Comment by rizreflects** [comment]
> @rizreflects 
> Check out the setting for the HEVC Files Filter. I could make the HDR filter behave the same way. Include/Exclude/Prefer (Autoplay). The Prefer brings them to the top of the list for autoplay. The caveat is it brings ALL matches to the top of the list (independent of quality i.e. 4K, 1080p etc).

Would it still be in order of file size though? Because if so, quality isn't too important.. 4k links are always larger than 1080p ones anyway so as long as it's still filtered by size I see no issues whatsoever. Thank you for considering this request, I really appreciate it.

**Comment by Tikipeter** [comment]
They'll still be sorted by size.

**Comment by mddfe** [comment]
This is a bit off-topic, but it's kinda related and I don't think it deserves its own thread.

@Tikipeter I assume the idea behind sorting by size is that the higher size files will have a higher bitrate. Have you considered weighting the different compression types? I think x265 video files are roughly 30% smaller than an equivalent x264 file. Suppose you have two files to pick from:

A) 10.0gb x264 file
B) 9.0gb x265 file

In terms of video quality, option B should be superior despite being smaller.

For movies I always manually select a source, and it's trivial to do some quick mental math to decide between two competing compression types, but it might help other people or people who automatically select a source.

Just a thought. Thanks again for all of the work you have done to make this great plugin!

**Comment by ShibajiCh** [comment]
> @rizreflects
> Check out the setting for the HEVC Files Filter. I could make the HDR filter behave the same way. Include/Exclude/Prefer (Autoplay). The Prefer brings them to the top of the list for autoplay. The caveat is it brings ALL matches to the top of the list (independent of quality i.e. 4K, 1080p etc).

Prioritizing HDR will be a really great feature!

@Tikipeter: Can't wait to see it implemented in Fen soon. Thank you so much! 🙂

Thanks and Regards,
ShibajiCh.

**Comment by Tikipeter** [comment]
@mddfe
Whilst that is a cool idea, I can't really foresee a way in which it could be implemented with enough consistency so as to be useful or accurate. Different encodes within the same compression method would need to be entirely consistent to do this successfully. That is just not the case. One 720p HEVC file may be 1.4GB, whilst another 720p HEVC file might be 0.8GB. You quickly find you would end with an infinite number of comparisons to make.

**Comment by mddfe** [comment]
> @mddfe
> Different encodes within the same compression method would need to be entirely consistent to do this successfully. That is just not the case. One 720p HEVC file may be 1.4GB, whilst another 720p HEVC file might be 0.8GB. You quickly find you would end with an infinite number of comparisons to make.

@Tikipeter 
In your example of comparing two HEVC files, the larger file is likely the better option, assuming your goal is maximum output quality. Fen already picks the largest file size, so if all of the scraping results were HEVC, there is no issue. If all of your scraping results are x264, then picking the largest file size is also a good way to go.

The issue is when you're comparing HEVC to x264. Maybe I'm ignorant here, but are there plausible scenarios where a 10% smaller HEVC file is inferior to the x264 counterpart?

I don't really understand the infinite number of comparisons comment. You could just value the size when ranking HEVC files as size*1.1 or some other value other than 10%. I believe equivalent quality output with HEVC compression is typically 10-30% smaller than x264, so a 10% 'bonus' to the ranking is a conservative one. A conservative value like 10% would probably be relatively easy to implement, and accurate enough that you won't be automatically selecting an HEVC file of inferior quality.

Maybe it's not a super clean solution though, and so it's not something you'd want to include. Either way, it was just a thought. Thanks again.

**Comment by Tikipeter** [comment]
Using "infinite" was silly of me, but from a code standpoint even a potential 20 point difference in comparisons (10-30% smaller) is a huge number.

The original stated goal of HEVC was to achieve as close as possible a 50% reduction in size for comparable picture quality. It certainly isn't 10%. It's more than that. That's part of the issue. What should that figure be? Choose the wrong figure and the feature is useless. Less than useless really, as it would not be in any way accurate to what it's trying to achieve.

Does the file contain 5.1 or better audio, or 2.0 audio? That affects file size quite a lot as well (particularly with HEVC files, where the percentage of the audio track/s to the overall size is greater). Are we including the audio in the weighting of "quality", or just the video?

It would have to be a blanket re-valuing of HEVC file sizes to be practical, like you say. Not taking any variables into consideration. And that number would need to be somewhere between 1.25-1.5. The question is how accurately would doing that represent the overall quality of the files being compared? It's worth thinking on some more for sure. My main point was I wasn't convinced weighting the HEVC file sizes would correctly represent the difference in video quality between H264 and HEVC. There are a lot of variables, but certainly not an infinite amount. :)

Let's not even get started on XVID files, which are still being encoded by some release groups.

This could be done, but I'd only want it for Autoplay mode. It could be a setting like "Use Weighted Filesizes".
I'll think on it some more...

**Comment by Tikipeter** [comment]
Oh, I forgot, prioritize HDR done for next update.

**Comment by ShibajiCh** [comment]
> Oh, I forgot, prioritize HDR done for next update.

Hi @Tikipeter,

Thanks a lot for adding this feature! 🙂

Thanks and Regards,
ShibajiCh.

**Comment by JC253** [comment]
> Oh, I forgot, prioritize HDR done for next update.

Thank you for this! 

I'm assuming this will also effect Dolby Vision links? Or would it be possible to add a 'Prioritize Dolby Vision' as well as the 'Prioritize HDR' feature? Anyway they could both be implemented?

**Comment by rizreflects** [comment]
Hey there tikipeter, I just checked your new update and can see you've added the HDR feature.. thanks a lot for that.. however I also noticed you removed the option to hide Dolby vision links. If it's not too much to ask, would you consider bringing that option back? The reason I'm asking is because I run Kodi on CoreELEC which isn't compatible with Dolby vision.. so I relied quite heavily on the option to hide those links.

**Comment by rizreflects** [comment]
![IMG_20210916_040400.jpg](https://user-images.githubusercontent.com/76912707/133542682-92bb5944-1757-4075-9236-3e26f8a05ea3.jpg)

If you see here for example, Dolby vision has been placed above HDR due to its larger file size.. so I'm basically in the same position as I was in before.. I'll have to source select in order to make sure Dolby vision doesn't play.. and of course that means I can't use the next up feature which requires autoplay.

**Comment by derrgoo** [comment]
If your running Dolby surround sound and having an hdr tv through regular kodi the update is awesome. Great enhancement.

**Comment by rizreflects** [comment]
Update: I woke up today and saw the problem was fixed. Just wanted to say thank you. I really appreciate it.
