### ISSUE TITLE
Lists request (TMDB) and a big thank you!

### ISSUE THREAD

**Issue by ShibajiCh** [Tikipeter/repository.tikipeter#588]
Hi @Tikipeter,

Hope you are doing well.

Firstly, I noticed that the Fen Trending and Popular lists for both Movies and TV Shows are fetched from TMDB "Weekly" Trending and Popular lists. Is it possible to change these lists to the TMDB "Today" Trending and Popular lists? That way the lists will be more updated and new movies and tv shows that are released everyday will show up. If this is not possible then could you create 2 separate lists for both movies and tv shows like "Trending Today" and "Trending This Week"? I know that these type of lists are already available in the TMDB Helper addon, but I prefer Fen as it's much faster than the TMDB Helper addon.

Secondly, could you create 2 separate "Because you watched" lists for movies and tv shows which will fetch the content randomly, so that the lists can be displayed as widgets?

Also, as a side note, are there any plans to create random mixed lists for movies and tv shows combined, like Random Mixed "Trending" and "Popular" lists? That will be a really great addition to an already great addon.

Fen is an excellent addon that you've created. It's one of the best addons available for Kodi at present. I can understand the huge amount of work that you've put into it. You're really awesome! Hats off to you! Thank you so much! 🙂 

Thanks and Regards,
ShibajiCh.

**Comment by Tikipeter** [comment]
>Firstly, I noticed that the Fen Trending and Popular lists for both Movies and TV Shows are fetched from TMDB "Weekly" Trending and Popular lists.

Where did you notice that? Not true I'm afraid. Trending comes from Trakt.

>Secondly, could you create 2 separate "Because you watched" lists for movies and tv shows which will fetch the content randomly, so that the lists can be displayed as widgets?

You need to explain what you mean by this. What content do you want fetched randomly? At the moment ALL of your watched is returned. I can't randomize a list where everything is already included.

>Also, as a side note, are there any plans to create random mixed lists for movies and tv shows combined, like Random Mixed "Trending" and "Popular" lists? That will be a really great addition to an already great addon.

No plans.

**Comment by ShibajiCh** [comment]
Hi @Tikipeter,

Thanks for the detailed explanation! No problem. I'll adjust with a combination of Fen and the TMDB Helper addons as I'm doing currently. Fen is already a great addon and it'll remain great without these enhancements. Thanks again for this awesome addon! 🙂 You may close this ticket.

Thanks and Regards,
ShibajiCh.
