### ISSUE TITLE
Fen player won’t play TMDB Helper movie saved into favorites

### ISSUE THREAD

**Issue by jaimsitecom** [Tikipeter/repository.tikipeter#589]
Log:
https://mega.nz/file/pYYSHZJZ#p0r4kFFSu4vQH5c0lpP970NUgllxOHMyu8a8bTp0t1g

Hi Tikipeter!

The latest update wont let TMDB Helper movies saved into Favorites play via FEN player. Then I tested saving a TMDB Helper movie in favorites using Venom as player and it works. I just noticed this after the latest update. 

But the TDMB Helper movies saved into kodi movies library still works when played via FEN player. It’s just the movies saved into Favorites that won’t play. It will go thru the usual source search process and once the chosen source is ready, it will just stop and won’t play the movie. 

Is there a new setting i need to enable to use this function again?

thanks in advance!

**Comment by Tikipeter** [comment]
TMDbHelper is not supported by Fen.
Any functionality between Fen and TMDbHelper is entirely coincidental.

**Comment by jaimsitecom** [comment]
Ok. Thanks anyways Tikipeter.
