### ISSUE TITLE
Trakt Movie Watchlist only shows 5 entries

### ISSUE THREAD

**Issue by burntovenmit** [Tikipeter/repository.tikipeter#59]
I have about 30 shows on my personal watch list. However, the widget for watchlist and the menu of it only shows 5 movies. I unauthorized trakt and tried again. Also cleared list cash and Trakt cache but that didn't work.

Anyone else have this issue?

**Comment by Tikipeter** [comment]
You need to post a log to open a support based issue.

**Comment by burntovenmit** [comment]
Any way I can attach them without them being seen publicly by everyone? @Tikipeter

**Comment by Tikipeter** [comment]
I don't think so.
