### ISSUE TITLE
[Question] Regarding widget updates

### ISSUE THREAD

**Issue by rizreflects** [Tikipeter/repository.tikipeter#590]
I've noticed my widgets have not been updating. I have fen set as follows:

Fen > settings > trakt > trakt cache duration: one hour. Refresh on each Kodi startup is set to off. 

I'm assuming the lists are supposed to update every hour set up this way, but I've waited 24 hours and my trending widget has not changed at all.. neither has my latest releases list (this is a liked list from trakt). Am I doing something wrong here or missing a particular setting? Refreshing on Kodi startup works, but it isn't an option as I'm running CoreELEC which is set to 'suspend' when not in use.. I'm trying to get it to update without the need for me to restart my device. I'm not sure if this is a bug or whether i need to enable another setting somewhere. Any help would be appreciated.

**Comment by Tikipeter** [comment]
>I'm assuming the lists are supposed to update every hour set up this way.....

Why would you assume that? What does the trakt cache have to do with widgets? In fact, what does the trakt cache have to do with any of the generic lists that Fen offers? You are making assumptions that are entirely incorrect. The Trakt cache is for your personal information from Trakt i.e. your watched history, collections, personal lists etc.

The skin (generally) is in charge of when widgets are refreshed. Usually after playback ends, a library update etc. Fen doesn't control when a skin's widgets are refreshed.

If you want to manually refresh the widgets, then make sure you have the Fen Context Menu addon installed, and simply select "Fen Refresh Widgets". But fair warning, all those generic lists are cached by Fen for 2 days. So every 2 days expect a difference in the lists contents.

Alternately, you could look into AutoWidget which apparently can look after widget refreshes along with other things including merging different lists into a single widget. That might be well worth a look.

**Comment by rizreflects** [comment]
> >I'm assuming the lists are supposed to update every hour set up this way.....
> 
> Why would you assume that? What does the trakt cache have to do with widgets? In fact, what does the trakt cache have to do with any of the generic lists that Fen offers? You are making assumptions that are entirely incorrect. The Trakt cache is for your personal information from Trakt i.e. your watched history, collections, personal lists etc.
> 

I made the assumption because when 'refresh on each Kodi startup' is enabled,  the widgets refresh properly (on startup).. therefore I figured disabling that option and setting the duration to 'one hour' would do the same thing but on an hourly basis. Obviously I wasn't too sure which I why I decided to ask you. Thanks for clearing it up for me though, I'll look into adding those lists through autowidget.
