### ISSUE TITLE
Kind request to clear my doubt

### ISSUE THREAD

**Issue by ShibajiCh** [Tikipeter/repository.tikipeter#598]
Hi @Tikipeter,

Hope you are doing well. I can understand that you're very busy but if you could clear a small doubt of mine then I shall be really grateful to you. 

I reported an issue via ticket #594. 
Since you've mentioned in that ticket that this is not a bug, so does that mean the HDR filter won't work for Debrid Cloud Files? Please advise.

My Kodi log:
https://paste.kodi.tv/eyasomitif.kodi

Thanks and Regards,
ShibajiCh.

**Comment by Tikipeter** [comment]
Cloud Files (if set to appear at top of results) will be sorted after any other sorts, meaning they will appear at the top in any order. Something has to be sorted last, and these are what are sorted last.

To sort the main list by HEVC/HDR/DOLBY VISION and then sort the cloud results to the top, and then expect the cloud results to also be sorted by HEVC/HDR/DOLBY VISION, I would have to do yet another sort on the cloud files AFTER bringing them to the top. All of this after already sorting the list by SIZE/QUALITY/PROVIDER.

At that point it is getting ridiculous. I'm afraid it's as good as it's going to get.

**Comment by Tikipeter** [comment]
I forgot. `Not a Bug` means the expected behavior is what is being observed.

**Comment by 123Venom** [comment]
If one does not want HDR files to appear from your cloud why not just keep ONLY HDR sources there?  Rid the undesired sources from your online account and they won't appear anymore.

**Comment by ShibajiCh** [comment]
Hi @Tikipeter,

Thank you for the detailed explanation! I'm very happy with the HDR filter feature. It's very useful. No problem if it doesn't work on cloud files. Thanks again! 🙂

@123Venom: Thanks for your suggestion! I'm already doing that what you suggested above.

By the way, both Fen and Venom are excellent addons for Kodi. Thanks for all the hard work that you both are doing! 🙂

Thanks and Regards,
ShibajiCh.
