### ISSUE TITLE
 WARNING <CAddonSettings[plugin.video.fen]>: failed to load value "false" for setting ignore_results_filter

### ISSUE THREAD

**Issue by freaktabnl** [Tikipeter/repository.tikipeter#6]
After last update today FEN crahes

 WARNING <CAddonSettings[plugin.video.fen]>: failed to load value "false" for setting ignore_results_filter

**Comment by freaktabnl** [comment]
Updates to latest version and after starting Kodi it crahes

**Comment by xyzfre** [comment]
Same here Crashes on start up

**Comment by ShibajiCh** [comment]
Hi @freaktabnl and @xyzfre,

I resolved the crashing issue by quickly moving into the addons page and disabling the Kodi Menu Caching option under Fen's General Settings. However, you've to be real quick to disable it.

Thanks and Regards,
ShibajiCh.

**Comment by xyzfre** [comment]
> Hi @freaktabnl and @xyzfre,
> 
> I resolved the crashing issue by quickly moving into the addons page and disabling the Kodi Menu Caching option under Fen's General Settings. However, you've to be real quick to disable it.
> 
> Thanks and Regards, ShibajiCh.

I always keep that setting disabled did this update enabled it by default?

**Comment by ShibajiCh** [comment]
> > Hi @freaktabnl and @xyzfre,
> > I resolved the crashing issue by quickly moving into the addons page and disabling the Kodi Menu Caching option under Fen's General Settings. However, you've to be real quick to disable it.
> > Thanks and Regards, ShibajiCh.
> 
> I always keep that setting disabled did this update enabled it by default?

@xyzfre Not sure about that.

**Comment by LITUATUI** [comment]
Mine was also disabled, but enabling and then disabling it made Fen work again.

Thanks for the suggestion @ShibajiCh

**Comment by ShibajiCh** [comment]
> Mine was also disabled, but enabling and then disabling it made Fen work again.
> 
> Thanks for the suggestion @ShibajiCh

@LITUATUI You're welcome! 🙂👍🏻
