### ISSUE TITLE
Tv show American dad not finding correct season and episode?

### ISSUE THREAD

**Issue by vinkop** [Tikipeter/repository.tikipeter#6]
hello, i noticed that for tv show american dad we do not get correct season and episode...for example if i click on american dad s16e01 i got files from seasons 12,14, 06 etc....for test i try in seren and gaia and there are files correct as i choose....

**Comment by Tikipeter** [comment]
I'm sure this would be due to having "!" in the title. Often in search syntax that means "ignore". So it would be searching for "American Dad" and ignoring what comes after it, hence the random episodes.

I'll hopefully have a fix next update. Please remind me here if I forget to do it.

**Comment by Tikipeter** [comment]
Should be fixed in 1.5.25
