### ISSUE TITLE
[Feature Request] Sorting - Filtering for Keywords/Key Phrases

### ISSUE THREAD

**Issue by tundrablasen** [Tikipeter/repository.tikipeter#60]
Hi Tiki, Hi Umbrella,

I want to propose an additional "Sorting/Filtering" category. 
Currently we have Quality, Provider, Size. - I propose a new category **Keyword**.
It would be great if i could set keywords (each for TV and Movies seperately), which can be then be taken into account during Results Sorting.

This feature is basically taken from the Sonarr/Radarr setting, of prioritizing the grabbing on releases due to keywords.

**Example TV Shows:**
I prefer Amazon Web-DLs. These are labeled within the file name with "_AMZN_". I will set a keyword "_AMZN_" and this will be taken into account during Results Sorting. Results with "_AMZN_" will be taken to the top, when i choose that in the "Results sorting" Menu (Keyword, Quality, Provider, Size)

**Example Movies**
Premiumize CDNs are often slow. and Premiumize have nearly everytime cached the encodes from rarbg (E.g. Uncharted.2022.1080p.BluRay.x265-RARBG).
I will set the keyphrase "_BluRay.x265-RARBG_" and "_WEBRip.x265-RARBG_" and this will be taken into account during Results Sorting. Results with "_BluRay.x265-RARBG_" and "_WEBRip.x265-RARBG_" will be taken to the top, when i choose that in the "Results sorting" Menu (Keyword, Quality, Provider, Size).

I hope it gets clear what i propose. Basically take a idea from the sonarr/radarr playbook to make the autoplay feature even more accurate and streamlined.

i will link this issue to Umbrellas Github, since i think this is a great feature also for this addon. and it might be smart to collaborate on that, to save resources and time. hope thats ok.

Thanks for your hard work @Tikipeter and @Umbrella

**Comment by tundrablasen** [comment]
Also what I am just thinking. Sonarr and radarr combine the keywords with a (optional) point system for each keyword. 

For for example.

you can set for tv shows n-amount of keywords

„AMZN“ +100
„NTb“ + 80


Therefore releases with AMZN would get 100 points. A release with NTb 80. and a release with AMZN and NTb would get 180. therefore it would be on top of the results. 

I guess that’s also needed, whenever 2+ keywords are set up. Or else there is no way for doing a results sorting right?

**Comment by Tikipeter** [comment]
https://github.com/umbrellaplug/umbrellaplug.github.io/issues/102#issuecomment-1278390079

**Comment by Tikipeter** [comment]
To save resources and time:

https://github.com/umbrellaplug/umbrellaplug.github.io/issues/102#issuecomment-1278390079
