### ISSUE TITLE
2 Issues

### ISSUE THREAD

**Issue by cabban** [Tikipeter/repository.tikipeter#60]
Hello. 
I have problem with colors not changing for quality.  though I fix that also fetching takes very long time I tested exodus and took 0-1 sec . Fen takes 5-7 . Kind regardp

**Comment by Tikipeter** [comment]
What device are you using cabban?

Fen does an extra round of sorting and other things that can slow it down, especially on slower devices.

Also, check the result numbers if comparing two displays of results (80 results will show a lot quicker than 500 results).

To test more, go to Settings->Results->Display and change 'Results Display' to 'Dialog' and see how much faster that shows...

**Comment by Tikipeter** [comment]
It shouldn't take that long on a windows machine.

Let me know if switching to 'Dialog' makes it faster, and we can go from there.
