### ISSUE TITLE
Issue with 'Networks' items.

### ISSUE THREAD

**Issue by JC253** [Tikipeter/repository.tikipeter#601]
Hello Tikipeter. Loving the recent update, thanks again.
I just noticed a bug while browsing the 'Networks' section. Each network I choose, example: Amazon, Apple TV, HBO Max, the page is blank. I can click on the "Next Page" item twice, and items for each network will show up then. I've attached a couple pics for reference.
![Screenshot (183)](https://user-images.githubusercontent.com/79684237/133908229-f84e74a5-1c18-43d0-95dd-e9fb5b1c03f7.png)

![Screenshot (184)](https://user-images.githubusercontent.com/79684237/133908231-160c6784-f437-445f-8112-a6c1d821bb13.png)

**Comment by JC253** [comment]
After digging around some more, it seems like the channels work fine, but the Networks that are streaming services are the ones that have the issue.

**Comment by Tikipeter** [comment]
A log is always required.

There's no issue with Networks currently.

It's not normally a troubleshooting step for this type of thing, but I'd load the default skin and see if they work then.

There's an external reason the directory isn't loading, and some skins these days use some tricky things to work the way they do. Worth trying with Estuary.

**Comment by JC253** [comment]
Sorry. Here is the log. Hopefully I did it right.
Also, switched to Estuary, back to FEN->Tv Shows->Networks and have same
issue.

https://pastebin.ubuntu.com/p/8VjX9MJXcD/plain/

**Comment by JC253** [comment]
![image](https://user-images.githubusercontent.com/79684237/133909503-d9ac5224-e147-4e8f-a722-6cda63963f06.png)

**Comment by JC253** [comment]
It's definitely something on my end, sorry to bother ya. Just loaded up another setup of mine and it's working fine. I'll try to figure it out. Thanks!
