### ISSUE TITLE
Install Repository help

### ISSUE THREAD

**Issue by esra8877** [Tikipeter/repository.tikipeter#602]
repository.tikipeter/repository.tikipeter-0.0.6.zip .I am trying rhis link to add a source on my apple tv4k.But it keeps saying "unable to connect-couldnt retrieve directory information" Can you help me please?

**Comment by Tikipeter** [comment]
You need to download the repo zip from here and install the repo from the zip.

That is now the only way to install the repo.

**Comment by Tikipeter** [comment]
Follow this:
https://github.com/Tikipeter/repository.tikipeter/issues/548#issuecomment-902320450

**Comment by Tikipeter** [comment]
You select install from zip file in kodi and select that zip file.

**Comment by sarmado88** [comment]
@Tikipeter I can't seem to install even from zip file either. It says 'the dependency script.module.requests couldn't be satisfied'.
