### ISSUE TITLE
[Question] liked trakt lists slower than built in lists under "Movies" and "TV Shows"

### ISSUE THREAD

**Issue by tundrablasen** [Tikipeter/repository.tikipeter#603]
So that is rather a question, than a bug report. i hope its still ok.

so i use FEN with arctic horizon skin on Kodi 19.1. works like a charm. (nvidia shield tv)

But my question is, if the lists entries under movies and tv shows (Trending, Popular, top rated etc) are loading faster as widgets, than if i use entries from liked lists on trakt (which are located under My Lists -> trakt, etc.)

thats just my feeling, but can this be true?

**Comment by Tikipeter** [comment]
Yes that can be true. The most likely factor would be the amount of items in the lists. More items equal a longer loading time.

**Comment by tundrablasen** [comment]
> Yes that can be true. The most likely factor would be the amount of items in the lists. More items equal a longer loading time.

Could I counter that, with activating the paginate lists when possible in the fen settings, or isn’t that helping for widgets?

I have already for all Widgets a limit of 25 within the widgets/menu settings

**Comment by Tikipeter** [comment]
A skin widget item limit setting won't really help here with regards to load times.

Setting a paginate limit in Fen will work to limit the number of items and improve load times. It doesn't matter whether it's a widget or not.

How many items are in the list?

**Comment by tundrablasen** [comment]
> A skin widget item limit setting won't really help here with regards to load times.
> 
> Setting a paginate limit in Fen will work to limit the number of items and improve load times. It doesn't matter whether it's a widget or not.
> 
> How many items are in the list?

<img width="414" alt="PNG-Bild" src="https://user-images.githubusercontent.com/46343142/135057728-d0c6fbfd-c5ba-4c2b-ac08-5aab9c5f5dd9.png">

**Comment by Tikipeter** [comment]
Yeah they'll take a while on an Android device if not paginated.
