### ISSUE TITLE
Trakt - Marking Watched

### ISSUE THREAD

**Issue by mystik1** [Tikipeter/repository.tikipeter#604]
Hate to bother you with this.  I am wondering if there is a trick or workaround.  I constantly get errors when trying to mark as watched, either automatically after watching or manually.  Sadly, I can't attach a log, but I am hoping this is enough for you to know what I mean.  

Am I perhaps hitting some limit on the number of accesses that upgrading to their Pro or whatever it's called plan would fix?   Not that I am anxious to do that  but just checking....

Thanks much in advance as always.  Terrific work on the addon.  It's awesome and very much valued/appreciated.

**Comment by Tikipeter** [comment]
There are a couple of reports of this sort of isuue in the past few months.

There is not really any advice I can give except for revoking your trakt auth in my accounts. Then making sure to hit ok when exiting the settings. Then making sure those settings are synced with Fen. Then going back in and reauthing trakt.

**Comment by mystik1** [comment]
Thank you.  I will give it a shot.  :)
