### ISSUE TITLE
A little guidance 

### ISSUE THREAD

**Issue by sgtser** [Tikipeter/repository.tikipeter#606]
Hi 
Sorry to post here but cannot find a solution to my problem 
I am a elderly citizen and my wife is even older than me LOL . We both have been using Kodi for years and have been stuck on you Fen add on for a long time with my Nvidia Shield. My wife’s birthday the 1st of this month I bought her own Nvidia Shield because she is stuck mainly to bedroom until the COVID restrictions ease as she is on a waiting list for a operation. ( sorry to bore you with that ) . 
She wants the FEN add on on her shield simply because it does what we tell to do with auto play and subtitles cause she doesn’t hear well . Your add on has always work with one click auto play through RD links and subtitles come up perfectly without issues and even next episodes launch on time . We even are able to understand some of the updates through the channel log most of time. 
My problem is I have tried all types of versions from all 18 versions to 19 versions but cannot get your repository to load on any of them , we even have it memorized LOL . I have been trying to get other add ons to the same but they just do not perform well at all so can you tell if you are gone from Kodi or is there a different link. Please let me know I am in the dog house for spending that much money and not delivering on the set up. I just need to know why I cannot get it to download and install. It still works on the other shield but it’s on 18.9 version and will update but not the new installations . 
I have always downloaded Kodi fresh and added my add ons myself and I always change the skin too Confluence because that is what we like . We tried the builds but they just make our TV’s look like a 2years olds comic book so we stay with simple as it works longer and we don’t have to change but every 6 months or longer if we keep updating the add ons . 
let me know YouTube hasn’t been any help this time with this issue and that’s where we look for updates!  Sorry so long , I delete this afterwards!

if you are done with Kodi , we would like to thank you for so much reliability for long you add on has been awesome!

sgt

**Comment by Tikipeter** [comment]
Follow what I replied here:
https://github.com/Tikipeter/repository.tikipeter/issues/548#issuecomment-902320450
That is the only way to install Fen now

**Comment by sgtser** [comment]
Ok 
Thanks I have tried that link as I found it online but it doesn’t open up and I haven’t had success accessing it through the Kodi app or getting to it with a remote functions inside the limited browsers available on the shield . I will keep trying! 
thanks for your help and sorry to bother you so late !

**Comment by Tikipeter** [comment]
You need a way to either transfer it onto the shield, or access it from the shield over your network if it's on another computer.
Then you use it to install from zip just like in the past with the old github.io address. But instead of selecting that address source, you select the zip you have downloaded.

**Comment by sgtser** [comment]
Ok 
I tried it but would not let inside the shield because of it’s issue . I understand what you are saying and I do from a friends computer tomorrow. 
thanks for letting me know and being so kind 
Keep up the good work , we love your app !!

**Comment by sgtser** [comment]
I closed now and  try to delete
