### ISSUE TITLE
Error after Updating to 2.0.41

### ISSUE THREAD

**Issue by dazazbab** [Tikipeter/repository.tikipeter#608]
I've been getting errors every time I try to play anything on FEN since I updated to 2.0.41. I'm running Kodi 19.1 on Windows 10 and has been using FEN 2.014 with no issues until I decided to update. I checked the log but not sure what the problem is. I saw a these lines:

2021-09-30 09:43:54.459 T:6552    ERROR <general>: EXCEPTION: XML File for Window is missing
2021-09-30 09:43:54.459 T:6552     INFO <general>: ###error in open_window###: XML File for Window is missing

right after I selected a movie. Not sure if that's the issue. Please see the debug log attached. Any assistance is appreciated.

[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/7260107/kodi.log)

**Comment by Arthur1967** [comment]
Go into the tips and tricks section and it tells you exactly everything you
need to know to use it

**Comment by dazazbab** [comment]
> Go into the tips and tricks section and it tells you exactly everything you need to know to use it

Could you be more specific? I had Fen set up before and made no changes other than the update. Any particular section on the tips that could help me?

**Comment by Arthur1967** [comment]
I’m not tikipeter Did you supply hin the log view because it’s hard to say
what’s going on without seeing that so I really don’t know what the issue
is but he might know but I know he wants a log all your answers are in tips
and drinks I know that and it does say fen is  for experienced kodi users
 So provide him a log and he might be able to help you without that he won’t

**Comment by Arthur1967** [comment]
I don’t use the add-on but I have I will install it now and see if it works
for me I wasn’t trying to be rude but when you say it wasn’t working
anymore that could be any number of things without providing a log it is
very hard to tell

**Comment by pigskins65** [comment]
Not for nothing but he did provide a log. It's in plain view. And you don't even use the add-on?

**Comment by Arthur1967** [comment]
Like I said I just installed it now in a matter of minutes and it’s giving
me everything I watch so I really don’t know what to say other than wait
for tikipeter

**Comment by Tikipeter** [comment]
You are many versions behind for the tikiskins module and a version behind for the tikiart module.

* Uninstall Fen (don't clear settings).
* Uninstall Tikiskins and Tikiart dependencies.
* Re-install Fen from the repository.

That should bring all the modules up to date and also link them correctly with the Tikipeter repository.

**Comment by dazazbab** [comment]
> You are many versions behind for the tikiskins module and a version behind for the tikiart module.
> 
> * Uninstall Fen (don't clear settings).
> * Uninstall Tikiskins and Tikiart dependencies.
> * Re-install Fen from the repository.
> 
> That should bring all the modules up to date and also link them correctly with the Tikipeter repository.

That did it!! Thanks for the help!!
