### ISSUE TITLE
Unable to add https://tikipeter.github.io

### ISSUE THREAD

**Issue by Zack9f6** [Tikipeter/repository.tikipeter#609]
Unable to add https://tikipeter.github.io

inside Kodi (newest version) in File Manger as a source

 gives an error that it cant connect

**Comment by Tikipeter** [comment]
Follow this:
https://github.com/Tikipeter/repository.tikipeter/issues/548#issuecomment-902320450

**Comment by Zack9f6** [comment]
Thanks, wish there was not so many guides saying to install it via the github.io  I thought I was going bonkers and typing it in wrong.  Thanks
