### ISSUE TITLE
Easynews scraper in Fen

### ISSUE THREAD

**Issue by les017** [Tikipeter/repository.tikipeter#61]
Hi, I noticed that on several shows Fen will not find anything whereas another add-on does find an Easynews source.

Is this something you could/would want to address?
It's only an issue with a few specific shows but it's consistent with those shows 

Thanks for your attention.

**Comment by Tikipeter** [comment]
>Is this something you could/would want to address?

Only if you post a log file (required in the rules for all error related Issues) and tell me the names of some of the TV Shows so I can test....

**Comment by umbrellaplug** [comment]
@les017 Can you please post the requested information? Your report effects multiple add-ons but is so vague there's not a way for us to troubleshoot or fix anything.

**Comment by les017** [comment]
Yes I will do so. Unfortunately I had to travel for business. I will post
log when I return, hopefully tomorrow.


Thanks,
Evan
