### ISSUE TITLE
Source results all show as SD (Even though they are 4k, 1080 results)

### ISSUE THREAD

**Issue by nigelwarning** [Tikipeter/repository.tikipeter#610]
So,

I just installed Kodi again. And I use Fen a lot, but now when I search for something, everything show up as SD even when they are higher quality sources. Is this a bug in the new version or is my Kodi tripping?

Thanks for the good work!

![Screenshot_20211003_130403](https://user-images.githubusercontent.com/51288761/135750884-1ef488c6-f5fb-443e-b264-1bae91d380c7.png)

**Comment by ReaLx3m** [comment]
Have the same issue, but this is on linux only. And by looks of OP's taskbar hes also using Linux.
If i recall correctly, at first start after setting everything fresh i think i had results displayed correctly, but after changing some unrelated setting it started doing this. Though dont quote me on this, havent tried another fresh kodi install to confirm the behaviour.
Im using Manjaro, but also tested on Fedora and same behaviour is exibited.
No problem with Venom.

Will provide some logs later when i get home in case they help.

**Comment by ReaLx3m** [comment]
Heres the log
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/7296151/kodi.log)

Oh and also it sometimes does display 1080p only(my max setting), havent seen 720p displayed so far. That free guy example should be in the log.
![Kodi](https://user-images.githubusercontent.com/22484793/136257338-cf3184ec-328c-43c6-b7ae-a5e2b337c782.png)

**Comment by ReaLx3m** [comment]
Just installed ubuntu on a VM out of curiosity, and same behaviour.
With no setting touched it ofcourse shows lot more sources, and within those besides 1080p there are 4K and 720p. This might have given me the impression that its working if no setting is touched, but scrolling down i see theres still whole lot of SD marked ones that are not SD. 8 marked correctly and 40+ incorectly for "Free Guy".
Also you probably noticed it doesnt detect extra info for those files like HEVC.

**Comment by ReaLx3m** [comment]
Checked few Movies/TV Shows, and it looks like its ok now. Thanks

**Comment by pigskins65** [comment]
I saw confirmation on Reddit that the Kodi 19.1 issue that caused the
Easynews delay has been fixed in Kodi 19.2.
