### ISSUE TITLE
Link

### ISSUE THREAD

**Issue by MKLaRue** [Tikipeter/repository.tikipeter#611]
Not able to find repository to add to Kodi. When putting in the add source link it states not able to find it. I am using: https://tikipeter.github.io

**Comment by ReaLx3m** [comment]
Download from [here](https://github.com/Tikipeter/repository.tikipeter/blob/master/zip/repository.tikipeter/repository.tikipeter-0.0.6.zip) and install zip. Old way wont work anymore

**Comment by ReaLx3m** [comment]
Settings>Addons>Install from zip file

**Comment by Tikipeter** [comment]
builds are not supported.
you will have to use a different addon.
