### ISSUE TITLE
Options - rescrape & Select Source 

### ISSUE THREAD

**Issue by derrgoo** [Tikipeter/repository.tikipeter#613]
Since update of 2.0.42 I have not been able to use context menus options rescrape and select source. It will list all links but when I goto play it doesn't do anything.

I have deleted and reinstalled a few times same thing. No error comes up, just nothing happens.

Update- I went back to last version and it still works fine.

--- Tested again today and I was able to play if I browse tv pack and select a single episode then it would work. Kodi 19.2 

[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/7319595/kodi.log)

![image](https://user-images.githubusercontent.com/63697905/136734743-c92e015f-f4e3-47a3-b98b-99ed275e0a4c.jpeg)

![image](https://user-images.githubusercontent.com/63697905/136734767-3badf60e-3035-4744-97f6-7918ab888824.jpeg)

![image](https://user-images.githubusercontent.com/63697905/136734785-e239399b-a4c6-4622-a16f-fd93a138b702.jpeg)

**Comment by derrgoo** [comment]
Understand, thank you for checking and all let you know on next update.

**Comment by JFG1000** [comment]
For me if I click rescrape and select source, I click any link and nothing happens, I then have to bring back the cached results, click that same link again for it to play

**Comment by JFG1000** [comment]
UPDATE: I cleared all addon cache and it's working again, apologies

**Comment by Tikipeter** [comment]
That's really strange. I have no idea what was causing it to happen.
With `cleared all addon cache`, do you mean in Fen's settings or your device settings (i.e. Android)?

**Comment by JFG1000** [comment]
UPDATE : the bug appears to be back

**Comment by derrgoo** [comment]
> @derrgoo  you should try what JFG1000 has done and go to Tools->Clear Databases and Clean Settings Files->CLEAR ALL CACHE and see if it works for you as well.

I tried this but still have to browse pack and pick to get it to play. But not that big of an issue.

**Comment by derrgoo** [comment]
Didn't crash but didn't have any affect to it working. Fingers crossed for the update.

**Comment by JFG1000** [comment]
![Screenshot_20211103-223953_Reddit](https://user-images.githubusercontent.com/76907836/140213805-0ce6074a-809d-4127-aa3c-de5b75da1acd.jpg)

Just keeping you updated, I've just seen this on reddit which I believe is the same bug we are experiencing

**Comment by TrillaG** [comment]
I've had this issue as well, where the links are found in the cloud but fail to resolve and nothing happens. Happened for me with Dragonball Z (1989) series. I couldn't get Fen to play that show at all, with any amount of scrapers, despite it populating a list like the original post and finding the torrent file that I had uploaded to my RD cloud.

**Comment by Tikipeter** [comment]
@TrillaG  The issue others are describing is one where "Rescrape & Select Source" is being used, and isn't working properly. You haven't mentioned that in your post above. You've simply mentioned that a certain source wouldn't play.

Is your issue related to using the "Rescrape & Select Source" or not?

**Comment by TrillaG** [comment]
My issue is both. Fen can't resolve cached torrent from my RD cloud, so
when I try to click 'rescrape and select source', it shows me that I have
cached files but I click them and they won't play.

**Comment by derrgoo** [comment]
Just to report on the latest update. This is now working again 👍👍

**Comment by Tikipeter** [comment]
Really?! I didn't think anything I did would fix it yet. I was more hoping to get more log info.
Are you sure it's fixed? Have you tried it a bunch of times?

**Comment by derrgoo** [comment]
I tried several times but will do more testing tonight just to make sure.

**Comment by derrgoo** [comment]
I tested another 10 different series in my tv show widget. Everyone worked. Maybe others can test as well.

**Comment by Tikipeter** [comment]
10 should be plenty good enough. :)
Good job.
