### ISSUE TITLE
Error when trying to access RD cloud storage

### ISSUE THREAD

**Issue by Projectal374** [Tikipeter/repository.tikipeter#62]
Hi, I am unable to access some folders in Real debrid cloud storage when accessing them through the my services section of FEN. It also appears they are not being scraped by the addon.
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/9832265/kodi.log)

**Comment by Tikipeter** [comment]
The log is indicating there are no playable files within those folders.

Please check the Real Debrid website and make sure there are still links available for those cached folders. And that they are playable (video) links.

**Comment by Projectal374** [comment]
I checked the website and playable items according to the unrestricted links they provided.

![Realdebrid](https://user-images.githubusercontent.com/116296903/197062365-a65ea368-9722-485b-9c8b-3c3b159d2174.png)

**Comment by Tikipeter** [comment]
Have you got a link to one of these so I can add them to my cloud and see what's going on?

**Comment by Projectal374** [comment]
Here are 2 torrents I used. I made sure I deselected the sample file that's included.

magnet:?xt=urn:btih:cdb81ddc2ba0f7e5982ab1103fb0ff43b40ded48&dn=The.Lord.of.the.Rings.The.Two.Towers.2002.DISC1.EXTENDED.2160p.BluRay.x265.10bit.SDR.DTS-HD.MA.TrueHD.7.1.Atmos-SWTYBLZ&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2910&tr=udp%3A%2F%2F9.rarbg.to%3A2950

magnet:?xt=urn:btih:4eb63c61de28a375d18755a9cf2fc64d74a437f2&dn=The.Lord.of.the.Rings.The.Return.of.the.King.2003.DISC2.EXTENDED.2160p.BluRay.x265.10bit.SDR.DTS-HD.MA.TrueHD.7.1.Atmos-SWTYBLZ&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2940&tr=udp%3A%2F%2F9.rarbg.to%3A2900

**Comment by ivarbrandt** [comment]
I'm also having this exact same issue.

**Comment by Tikipeter** [comment]
Good job.

I haven't looked at RD's output from these endpoints for a while, but it looks like they've changed something that has broken this feature of Fen.

I'll have a fix for next update, but that might be a bit of time away as I'm quite busy with work at the moment.

Tomorrow I'll upload here a couple of files that you can replace if you feel comfortable doing that. They should fix the cloud browser and the cloud scraper.

**Comment by Projectal374** [comment]
It's good you were able to replicate the error and address it. I'll give the files a try when available.

**Comment by Tikipeter** [comment]
[plugin.video.fen-3.0.18a.zip](https://github.com/Tikipeter/repository.tikipeter/files/9843140/plugin.video.fen-3.0.18a.zip)

I can't upload py files here in Issues, so here's the last released version of Fen with the changes needed.

Keep in mind if you install from zip, Kodi will lose the link between Fen and my repository. So you will need to manually update Fen the next time that's needed by navigating into the repository and selecting to install Fen from there again.

Might not be worth the hassle, but it's there if you want to use it. :)

**Comment by Tikipeter** [comment]
There's a potentially troublesome are of code in the next update which is making me hold off on releasing it soon enough to address this RD issue in a timely fashion. I'll likely need a few people on android systems to test it first.

That's why I've applied the couple of changes to the last released version above.

**Comment by Projectal374** [comment]
Well I didn't want to lose the link between Fen and your repo so I copied these 2 .py files: real_debrid.py & rd_cloud.py to their respective folders and that seem to do the trick. 
Unfortunately they "display" as SD quality instead of 4K because of the the titles missing the necessary info I guess.

![image](https://user-images.githubusercontent.com/116296903/197323609-9766018f-a050-4b24-b442-317fdfff1e24.png)

**Comment by ivarbrandt** [comment]
I'm on a NVIDIA Shield TV Pro and I updated to the version attached above.

Accessing torrents directly through the My Services menu works without any issues. I can watch directly from there. 

However when scraping, the torrent isn't found. I also tried linking the torrent and the show together and it still didn't work.

Let me know if a log would be helpful.

**Comment by Tikipeter** [comment]
A screenshot of the filenames of the files inside the torrent would be handy. If the scraper is failing (even when linked to a show) then it would usually be due to poor `SxxExx` naming.

**Comment by jigoop1** [comment]
> There's a potentially troublesome area of code in the next update which is making me hold off on releasing it soon enough to address this RD issue in a timely fashion. I'll likely need a few people on android systems to test it first.
> 
> That's why I've applied the couple of changes to the last released version above.

@Tikipeter 
i can test on Android if you need me to.

**Comment by ivarbrandt** [comment]
What about shows that only have one season?

![Screenshot_20221022-113634](https://user-images.githubusercontent.com/54084201/197355068-864b3f1d-bc36-4352-a2dc-d4d09b8a64de.png)

**Comment by Tikipeter** [comment]
Yeah, no way to match that.

Well there is, but not without matching a whole bunch of other stuff as well.

**Comment by Tikipeter** [comment]
> > There's a potentially troublesome area of code in the next update which is making me hold off on releasing it soon enough to address this RD issue in a timely fashion. I'll likely need a few people on android systems to test it first.
> > That's why I've applied the couple of changes to the last released version above.
> 
> @Tikipeter i can test on Android if you need me to.

Appreciate it. I should have a test build ready in a couple of days.

**Comment by ivarbrandt** [comment]
> Yeah, no way to match that.
> 
> Well there is, but not without matching a whole bunch of other stuff as well.

I understand. I'll just watch those ones directly from the premium services section.

**Comment by Projectal374** [comment]
Hi, I noticed I can only access 50 folder items when viewing my cloud storage files. I am using RD and this seems to be their "page [1]" on the website. Is this a limitation with RD because I definitely have more than fifty folders in my cloud with playable files. Now when I scrape for shows/movies that would be on their "page 2" they can't be found.

**Comment by Tikipeter** [comment]
@Projectal374 
There's a `limit` parameter that I currently don't have set, which defaults to 50. Maximum is supposed to be 2500, but it seems RD's API doesn't like that figure. I've set the limit for 500 for next update.
