### ISSUE TITLE
Error: <class 'TypeError'> 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by meesterexx** [Tikipeter/repository.tikipeter#622]
Updated my existing Fen and immediately got the error message. Navigating to any menu option in Fen also throws the error message. So I installed new on a clean Kodi and get the same error on opening addon / navigating menu options in addon.

Log attached:
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/7486667/kodi.log)

**Comment by GarciaGroupie** [comment]
I have the same errors.

**Comment by xyzfre** [comment]
I'm Having the same issue as well any section I click on Fen I get a error pop up￼￼ my apologies did not get a chance to grab a log but I took some quick screenshots of the errors that show on the wizard log￼￼ ,,using Nvidia Shield 2019 model K19.3 ,,AuraMod Skin

**Comment by xyzfre** [comment]
![image](https://user-images.githubusercontent.com/49699869/140551192-cf05c8d0-fbf5-4ebc-a1ba-9d2f2e80ca8f.jpeg)

**Comment by xyzfre** [comment]
![image](https://user-images.githubusercontent.com/49699869/140551295-24246414-c0de-4b07-a1a6-8ba73a0e09d5.jpeg)

**Comment by xyzfre** [comment]
![image](https://user-images.githubusercontent.com/49699869/140551397-50fc4bf5-ae8b-47b8-80e2-775f900e7a19.jpeg)

**Comment by xyzfre** [comment]
![image](https://user-images.githubusercontent.com/49699869/140551525-215d03c7-f008-45a0-8a9d-e1eac3abe149.jpeg)

**Comment by yam4me** [comment]
also the same errors in coreelec (kodi 19)

**Comment by ShibajiCh** [comment]
Hi @Tikipeter,

After the latest Fen update I'm also getting the same errors like the others above. Also, majority of the Trakt lists are not opening anymore. For example, my Trakt Liked Lists are not working anymore. I'm using Kodi v19.3 on Nvidia Shield TV Pro 2019.

Here's my Kodi log:

https://paste.kodi.tv/icubekujex.kodi

Could you please look into the issue?

Thanks and Regards,
ShibajiCh.

**Comment by Tikipeter** [comment]
Fixed in 2.5.02

**Comment by ShibajiCh** [comment]
> Fixed in 2.5.02

Hi @Tikipeter,

Thanks for the prompt response!
All the issues seem to be fixed now.
Thank you so much! 🙂

Thanks and Regards,
ShibajiCh.

**Comment by meesterexx** [comment]
That fixed it for me, thank you. Also, I like the new dark gray color of the addon background, looks better in dark theme builds than the blue.
Thanks again!

**Comment by yam4me** [comment]
Fixed for me. Many thanks for your work!

**Comment by xyzfre** [comment]
Also fixed on my end working flawlessly thank you for your amazing work with Fen￼✊🏼 🙌🏼

**Comment by SirRickie** [comment]
![PXL_20211105_231432797](https://user-images.githubusercontent.com/60318531/140588458-5962fd94-49c4-4a5b-8b78-2ef6a999866d.jpg)
Kodi 18.9, going into tools, then changelog : cannot open this. Gives an error each time.

**Comment by xyzfre** [comment]
> Fixed in 2.5.02

Been doing some testing with this New update on my end I see a very big speed improvement on everything thanks again for this great work and really appreciate everything you do to make Fen better✊🏼🙌🏼🙌🏼￼￼￼￼

**Comment by Tikipeter** [comment]
No worries @xyzfre . I knew there'd be a couple of hiccups with this release. Unfortunately it was a function that EVERY menu uses that was the issue. Didn't happen in testing because I always have a view set for the root menus. But apparently plenty don't. :) :)

**Comment by Tikipeter** [comment]
@SirRickie I'll get that sorted soon. Doing some work with Venom dev at the moment.

**Comment by derrgoo** [comment]
Great update 👍 as always

**Comment by Tikipeter** [comment]
Good job with the feedback everyone. 👍 🥇
