### ISSUE TITLE
Next episode window doesn't pop up at the end of a episode 

### ISSUE THREAD

**Issue by IG2022** [Tikipeter/repository.tikipeter#623]
Hi, thanks for the new update I like the new fen logo, looks good. Just an issue I noticed, after the latest update the next episode window is not Popping up at the end of episodes. Just noticed this issue when I updated and watched a couple of shows today. I've tried both settings with percentage played aswell as time remaining and it seems to fail on both scenarios. 

Any help would be greatly appreciated. Thanks! 

Here is my Log.  [Log](paste.kodi.tv/qukojodedu)

**Comment by Tikipeter** [comment]
I'll look into it. :)

**Comment by Tikipeter** [comment]
Bloody thing breaks even when I don't go near the code. :)

**Comment by Tikipeter** [comment]
I actually don't think it's anything wrong with the code. There's an old Kodi python bug that's been around for years and I had something in place to counteract it, but I think with all the code changes I made I've left it in the wrong spot, if that makes any sense.

The next window/function works fine on my Windows machine, but doesn't on my LibreELEC machines, and obviously not your Android machine, leading me to believe it must be this specific Kodi python bug.

Hopefully fixed for next update, which won't be too far away.

**Comment by Tikipeter** [comment]
Looks like it is fixed with a minor addition.

**Comment by derrgoo** [comment]
I had same issue which I tested several series. On android box. FYI.

**Comment by derrgoo** [comment]
Fixed with most recent update 👍

**Comment by IG2022** [comment]
> Looks like it is fixed with a minor addition.

Thank you for fixing this it's working perfectly with the recent update! I appreciate it.
