### ISSUE TITLE
download directory series cannot change to home NAS server 

### ISSUE THREAD

**Issue by jeepeevdw** [Tikipeter/repository.tikipeter#624]
Changing the download directory for series to home NAS still not working Now it is not possible to go to  **://nfs** it stops at **special://profile 
I send attached photographs for clarifying the path .
![IMG_20211106_092940314](https://user-images.githubusercontent.com/93767662/140603616-81564f98-0df5-41ea-aa83-922485e47608.jpg)
![IMG_20211106_092823970](https://user-images.githubusercontent.com/93767662/140603617-d44c4f35-1638-4104-b113-31f47a71bb3c.jpg)

**Comment by Tikipeter** [comment]
Press "Back" when you are at that level in the directory tree.

**Comment by jeepeevdw** [comment]
This works Thanks

**Comment by Tikipeter** [comment]
Let me know if downloading over the network is working again...
