### ISSUE TITLE
Trakt Calendar Down

### ISSUE THREAD

**Issue by mystik1** [Tikipeter/repository.tikipeter#625]
Just got the new version last night.  I saw in the release notes that there's supposed to be some new Trakt settings.  But  they are not showing on this side.  Also (and more serious), Trakt Calendar is not working.  Errors out.  Strangely, Next Episodes does work!

**Comment by Tikipeter** [comment]
It's not possible to not have settings that are included with the addons settings file.

If you don't have v2.5.04 installed then you are not on the latest version, and could be the reason for trakt calendar not working, because it's working for me.

**Comment by mystik1** [comment]
Ah, I see the options now.  It does still crash, though.  Here's the log:


Https://paste.kodi.tv/UPUHOMAXEK

**Comment by mystik1** [comment]
Hm.  When I click the link, it doesn't open the log for me.  In case it doesn't for you too, maybe this will help.
![20211106_205249](https://user-images.githubusercontent.com/1531767/140628461-8e40d602-2856-4efa-acb2-76c69700dffc.jpg)

**Comment by mystik1** [comment]
Thank you.  I figured it out.  A recent change with the Trakt improvements must have broken the menu item I had added to a menu.  It works using the route from My Lists.  I will re-create the menu item.  I suspect that will fix it.

**Comment by Tikipeter** [comment]
My fault really. I mentioned that widget paths may be broken but forgot to mention that the same would be true for custom menu entries.

**Comment by mystik1** [comment]
No worries.  All good now.  Really great work on it.  It is very much valued and appreciated.
