### ISSUE TITLE
Fen 2.5.04 not working 

### ISSUE THREAD

**Issue by pmcgrath1** [Tikipeter/repository.tikipeter#626]
Everytime I try play an episode I get 'no results'. My debrid and trakt accounts are authorised and logged in. Despite that I still don't see any ticks beside my watched content. I'm on the latest version of Fen 2.5.04

I get an error whenever I try click the logviewer on settings too. I've tried uninstalling and reinstalling the add on.

**Comment by Tikipeter** [comment]
Provide a log. Or at least tell me what version of Kodi you are running.
There's nothing useful in what you've written above otherwise.

**Comment by pmcgrath1** [comment]
Whenever I try view the log it gives me an error. The version of Kodi is 18.9

**Comment by Tikipeter** [comment]
Not view the log. Post the log here so I can view it.

**Comment by pmcgrath1** [comment]
I've actually just upgraded to Kodi 19.3, the issues I was having aren't happening on 19.3.
