### ISSUE TITLE
Question..url for updates?

### ISSUE THREAD

**Issue by FloridaJC** [Tikipeter/repository.tikipeter#628]
Hi, Had url set in kodi file manager to https://github.com/Tikipeter/repository.tikipeter/,  stuck now at version 2.0.41. What should I use to insure updates? On Kodi 19.3, Android version. Have other Android devices, same url, and updates are current. Update: Downloaded repository zip file and use it to update FEN for now.

**Comment by Tikipeter** [comment]
That URL in File Manager has nothing to do with managing updates. That's not how Kodi repositories work.
That URL is only ever to originally INSTALL the repository.

If you have the Tikipeter repository installed, and have ONLY installed Fen from that repository, then you will receive updates.

**Comment by FloridaJC** [comment]
Didn't know that. Good to know. Thank you very much!!

**Comment by Tikipeter** [comment]
No worries. Be sure to ensure that Fen is installed from the Tikipeter repository only. This is a new security "feature" in Kodi 19. If you were to , say, update Fen using a Fen zip file, then the "link" with the Tikipeter repository would be lost, and you would not receive updates anymore. It's something I have to deal with constantly as I install Fen using zips so as to test future updates.

To make sure Fen is linked correctly to the Tikipeter repository, navigate to the repository, and make sure "Enabled" is next to the Fen menu item within it. If not, Kodi does not have the link set between Fen and Tikipeter Repo. If that's the case, simply uninstall Fen (keep settings when Kodi asks), and then re-install it from the repo. That will re-set the "link" between the two, and ensure Fen updates correctly in the future.

**Comment by FloridaJC** [comment]
Got it. Thanks again.
