### ISSUE TITLE
Trakt Calendar Error

### ISSUE THREAD

**Issue by FloridaJC** [Tikipeter/repository.tikipeter#629]
Hi, When clicking on Trakt Calendar get message to check error log. See log file. Thank you.

https://paste.kodi.tv/ucorilatav

**Comment by Tikipeter** [comment]
Is that being accessed from "My Lists->TRAKT: Lists->TRAKT: Trakt Calendar", or is it being accessed from a custom shortcut you made to this item. If the latter, you will need to delete it from the menu you placed it in and then make it again.
Some plugin endpoints were changed in the 2.5 update.

**Comment by FloridaJC** [comment]
Yep, custom short cut. Will redo. Thanks.

**Comment by Tikipeter** [comment]
I mentioned in the changelog for 2.5.01 that widgets pointing to certain endpoints would need to be re-set, but neglected to mention that was also true for custom list items. I never thought of it, even though I have custom items myself.
