### ISSUE TITLE
Dolby-Vision on top

### ISSUE THREAD

**Issue by djdirty60** [Tikipeter/repository.tikipeter#63]
Good day Peter, are you okay?

Question, is it possible that DV takes precedence over HDR.  So that first all DV is on and then HDR etc etc.

Thank you for all the beautiful work

**Comment by Tikipeter** [comment]
Unfortunately I can't implement sorting such as this with the current code being used. It needs to be re-written.

This type of sorting will be a feature then, but it might be a bit of time until I can get to it.

**Comment by djdirty60** [comment]
Good day,

Is it perhaps already possible to have dolby vision/HDR sorted at the top?

Thanks in advance for the top addon
