### ISSUE TITLE
Feature Suggestion: Netflix (addon) Integration

### ISSUE THREAD

**Issue by dm2912** [Tikipeter/repository.tikipeter#63]
First up, great job on this, what I love is the effective RD Cloud, and Local Download integration. Solved a problem that so many library building add-ons have with being able to use local files if they are present. 

Which brings me onto a feature suggestion that I feel might be fairly straightforward to implementation and that is integration with the Netflix add-on (and in time the Amazon Prime addon) https://github.com/CastagnaIT/plugin.video.netflix/issues (Think it is in the official repo's now as well).

Netflix (And Amazon) add-ons like most can automatically export your watchlists to library locations, but where Netflix causes problems is they are forever adding things, removing things, changing what is available, which makes maintaining a library in conjunction with other add ons that also maintain libraries a total pain to keep up to date. 

With the netflix add on its fairly straightforward library export.. show name with episodes and seasons then as .strm files

![241119b(001)](https://user-images.githubusercontent.com/25871666/69498885-9b5b3680-0ee4-11ea-9d56-76ada4c0ba8c.png)

What would be great is if Fen could recognise the Netflix directories in the same way it does with Download directories, as an additional source. So when searching for a show, if that show was available on Netflix then it would auto play the netflix source. 

Something like........

![netflix](https://user-images.githubusercontent.com/25871666/69498899-c04fa980-0ee4-11ea-9cde-60fefe555de8.jpg)

In theory the same process could be applied to any add on that generates strm based library folders.

(Obviously its possible to add netflix to my kodi library and set fen to "dont create duplicate content", but netflix constant adding and removing content causes headaches)

The same principle could be used with Amazon Prime. So basically in Fen I could click on a show and it would search Torrents, RD Cloud, Netflix, Amazon etc

**Comment by Tikipeter** [comment]
I like the idea of having, say, 3 or 4 generic "Folder Scrapers" that you can assign to any folders with content in them. You could then name the scrapers whatever you liked. So you could name yours 'Netflix' and 'Amazon'. Another user with different uses for the scrapers could name them accordingly.

I'm going to adjust the 'Downloads' scraper to only see video files (i.e. not .strm files), as that is an oversight with the code as it is. The library scraper doesn't pick up .strm files either.

I would do this new feature first so a user case like yours would be able to continue having Fen pick up .strm files.

Unfortunately, a few good ideas have come in just recently right when I am much busier at work. But that should end soon and I can start adding these things. Just be patient. :) :)

**Comment by dm2912** [comment]
>I'm going to adjust the 'Downloads' scraper to only see video files (i.e. not .strm files), as that is an oversight with the code as it is. The library scraper doesn't pick up .strm files either.

^ it doesnt pick up strm files at the moment. I did consider that and tried it, and was going to be clever with folder grouping so like 

-Downloads
-- Actual downloads
-- Netflix

But it doesnt currently pick up strm, you dont need to fix that :D

But, Yeh, it could be really useful for a host of things. 

With generic folder scrapers that look for strm files it could be applied to things like Netflix, Amazon, that support library export and potentially other addons that support library export (Im thinking like legal catch up tv addons that support library export)

**Comment by Tikipeter** [comment]
OK. The next update (v.1.5.74), has 3 scrapers called 'Source1, Source2, Source3'. You can set a Movie and TV Show folder for each. Try them out and see if they work.

I am not fully confident the strm files will play. Please test and let me know.....
