### ISSUE TITLE
“5.1” not included in the source title anymore?

### ISSUE THREAD

**Issue by james-nduka** [Tikipeter/repository.tikipeter#631]
By default, it looks like I can’t see if a movie/show will support surround sound in the new update.

Has this feature been removed? Or is it a setting I can turn on?

**Comment by Tikipeter** [comment]
I'm about to push an update to fix a couple of things like this.

**Comment by james-nduka** [comment]
Awesome thanks

**Comment by Tikipeter** [comment]
2.5.06 should fix this. Although the terminology has changed slightly (6CH, 5CH, 8CH etc).
