### ISSUE TITLE
No results

### ISSUE THREAD

**Issue by mrXoo** [Tikipeter/repository.tikipeter#632]
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/7508668/kodi.log)
Hi There,

Getting no results for most movies. Have deleted scrapers cache and pretty much all plugin.video.fen data except settings. Still the same. Updated to lasted version although I like the older version because I really need autoplay and to be able to select movies over 4 GB so that i dont get any cams. Any way you could add this setting?

Cheers

**Comment by Tikipeter** [comment]
>Getting no results for most movies.

No idea why. Nothing in the log. At which point does the scraping process fail and return no sources? Do you see the dialog running through the scrapers and displaying results? Do you then see the dialog of Fen checking with your debrid service/s for cached torrents?

>Any way you could add this setting?

Why not turn OFF "Include Pre-Release Results (CAM/SCR/TELE)"? Doesn't that do what you want (no CAM results)?

**Comment by mrXoo** [comment]
It flashes up the dialogue box for a second then says no results on almost every movie. turned off autoplay and occasionaly get some results in purple

Still get CAM versions with the switch turned on, always have. Like Shang Chi for example. Keep on getting that cam version of 1.89 GB

**Comment by Tikipeter** [comment]
I'd delete the `providerscache.db` file in the Fen userdata folder, restart Kodi and try again. It's working fine here.

**Comment by mrXoo** [comment]
I tried that now the dialogue box doesnt even come up just says no results

**Comment by mrXoo** [comment]
Okay so I just deleted script.module.fenomscrapers and now im getting links

**Comment by mrXoo** [comment]
seems to be working now. ill keep an eye on the CAM versions.

Thanks for the help

**Comment by mrXoo** [comment]
My issue of no results is back gain. Im using the latest version in Matrix.
If I have played it from my cloud it will appear in the results in purple. If Its not in my cloud then I get no results immediately. 
Seems to me that external scrapers are not being searched at all.
External scrapers are enabled
