### ISSUE TITLE
Hey folks support is gone for 18

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/repository.tikipeter#633]
The next update of Fen will be Python 3/Kodi 19 compatible only.

**Comment by AT5Pin** [comment]
Thank you for all you do for us. Your work is truly appreciated. I remember when you first made mention of Fen in the sub a couple 3 years ago me thinks. You've come a long way and Fen is the best!

**Comment by james-s-nduka** [comment]
Is it possible to prevent devices with an older version from receiving the update please? Even with auto-update on.

**Comment by iCanuck** [comment]
Thanks for all your work Tikipeter, just a suggestion but if you are migrating to python 3 for new versions of Fen could you please add a dependency for python 3 or xbmc gui v5.15.0 so people still running K18 don't receive the update to Fen v2.5.07. Thanks!

**Comment by mrXoo** [comment]
Hi there,
This is not related to the workings of your addon but I was wondering how, when im playing a video I can invoke your downloader to come up? The skin im using allows to runscript or I can create a little addon for that function.
Do you have a line of code to bring up the download dialogue box?
Cheers
