### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by Sourcedine** [Tikipeter/repository.tikipeter#636]
Hello,

First I want to thank you for all your work!

I translated for my personal use the addon in French, I would like to share my work with other users.

Here is the strings.po file to insert in the resource.language.fr_fr folder :)

[strings.po.zip](https://github.com/Tikipeter/repository.tikipeter/files/7514958/strings.po.zip)

**Comment by Tikipeter** [comment]
Good work @Sourcedine 🥇 💯 
That's a lot of work to get that done. Thanks for taking the time to do it.
I will add it for the next update.
There will be new strings periodically. Let me know in these Issues if you ever update the strings.po and I'll include it for the next update.

**Comment by Grarem** [comment]
Okay, I would post the file here whenever I update it :)

**Comment by Sourcedine** [comment]
Okay, I would post the file here whenever I update it :)
