### ISSUE TITLE
CAM versions being played

### ISSUE THREAD

**Issue by mrXoo** [Tikipeter/repository.tikipeter#638]
Hi There,

I started a new thread for the CAMS coming in search results.

The new venom came up, not sure what your search criteria are but this was the link

EDIT: I've removed this URL for your sake. URL's given to you by RD are for your consumption only. They are individual to your account with RD. Not a good idea to post them on the net. If you want me to check out items that are getting through the CAM check, you will need to post the filename of the torrent/file.

**Comment by mrXoo** [comment]
I see there may be a problem because the ones that are coming up are categorized HD1080 or BRRIP or something similar.

I added br2020 and mp4 to this line 24 in the sources+utils.py to test and it removes them

CAM = ('.cam.', 'camrip', 'hdcam', '.hd.cam', 'cam.rip', 'dvdcam', 'bd2020', 'mp4')

**Comment by mrXoo** [comment]
I wonder if there was an option to remove .avi streams that would help.

**Comment by Sourcedine** [comment]
You can manage undesirables torrents with keywords directly in _FenomScrapers Module > Torrents > Remove Undesirables > Define Extra Undesirables_

**Comment by Tikipeter** [comment]
What @Sourcedine said.
There are strings that are searched for to weed out CAMS/TELE/SCR. But if the uploader of the content doesn't tag that content appropriately, they will be missed and the result will get through. The best way to stop this from happening is to of course not attempt to watch movies that have not been released yet on the web or physical media.
