### ISSUE TITLE
2.5.08 Update Broken

### ISSUE THREAD

**Issue by KTBoxer1** [Tikipeter/repository.tikipeter#639]
The update seems to have broke FEN on all of my devices.  Error log is blank...?  Anyone else or is this currently just limited to 
![Log](https://user-images.githubusercontent.com/94191332/141509353-5270a6be-0165-4faf-bde9-2061c9b54aac.jpg)
me

**Comment by KTBoxer1** [comment]
I understand post without error log will be deleted. I'm checking my other devices to see if they also have a blank error log..

**Comment by Tikipeter** [comment]
It's impossible for the error log to be empty. If you see it as empty, then you are looking at the wrong thing.

You can post a pic like above if you want, but I need a bit more of the info than what you captured. The few lines underneath what your picture shows will likely give the answer.

**Comment by Tikipeter** [comment]
Scratch that. Looks like you're using Kodi 18 which isn't supported anymore.

**Comment by KTBoxer1** [comment]
Ahh,,  Well. That would do it!  Thank you for the quick response.  Guess it's time to update.

**Comment by Tikipeter** [comment]
You won't regret it.
