### ISSUE TITLE
[BUG] Fen Not Displaying In Progress Episodes Sorted By LastPlayed Timestamp

### ISSUE THREAD

**Issue by rtuRgALp** [Tikipeter/repository.tikipeter#64]
It appears that the Trakt sorting for in progress content is not updating properly. I have this set to recently watched.

https://paste.kodi.tv/pohoxugice

This was working flawlessly before. I figured it is not a Trakt API issue since this is functioning correctly with another add-on (Umbrella). 

Trakt scrobbles are picked up fine and the content resumes normally. The resume point is then saved back to Trakt properly after stopping playback as well. It just doesn't move up in the list to first place and stays in its preexisting place instead.

This is happening on all my devices: MacBook Air and Apple TV 4K.

**Comment by xyzfre** [comment]
In settings don’t recall exactly what it’s called not in front of my device but there is a setting that you can disable new episodes to the top of the list ,, that might be your issue

**Comment by rtuRgALp** [comment]
No, that’s not it.

**Comment by xyzfre** [comment]
My apologies I thought you were referring to the next episodes but it's in progress TV shows which you are correct because on my end it's working properly ,when I finish an episode my in progress TV shows also refreshes and puts that show on top of the list I'm using Nvidia Shield 2019 pro K19.4, could be something with Apple good luck

**Comment by rtuRgALp** [comment]
It used to work properly for me; but, it isn’t any longer. 

The issue started after I experimented with this custom skin called FENtastic: https://github.com/Tikipeter/repository.tikipeter/issues/49#issuecomment-1272165465

I’m not sure if that had anything to do with it, but now my it’s not working properly.

**Comment by xyzfre** [comment]
I remember this comment I myself got tempted to try out the skin I downloaded the zip but haven't got a chance to check it out been stuck on AH2 which is amazing so far

**Comment by xyzfre** [comment]
Hope you don't mind just trying to help got some free time this morning when you did the fresh install did you make sure you deleted everything you know sometimes Kodi tends to leave some files behind I usually use a file explorer to make sure nothing was left behind from the old installed

**Comment by rtuRgALp** [comment]
I regret trying that skin. I love AH2. Everything was working flawlessly. I think that skin may have corrupted my Trakt account or something. But, I find that hard to believe because it’s just hard-coded XML shortcuts. 

What’s weird is that this issue started on my other devices where I didn’t install that skin. So, I’m not sure what’s going on. 

When I re-installed, I made sure to delete everything. Thanks for your help!

**Comment by xyzfre** [comment]
This is gonna be a long post lol but I managed to get AH2 to work pretty fast even on start up I got it from 28 seconds to 12 seconds and that’s pretty good when using android devices I only use Fen and TMDb H because it’s a dependency for the skin ,with Trakt what I’ve done is delete any old TV show that has been canceled or no new seasons for a while and also movies that I have watch a long time ago which on my end was thousands for both this has improved my speed performance a lot,,, Trakt even though a TV show has been canceled in the background it still check for new episodes and also checks for all those movies you have watched ,on my end it doesn’t bother me to delete half of that don’t need to be reminded lol but we all have preferences and I respect that, just wanted to share some feedback on speeding things up

**Comment by Tikipeter** [comment]
It's nothing to do with the skin. So you can rest easy about that.

There's a known issue that I've had in Fen for a long time where if you continue playback of an episode that already has a resume point set, and then stop before marking as watched, thus setting a new resume point, then the trakt sync doesn't reflect the updated watch time for the new resume point.

That sounds like what's happening here. Is that the case?

**Comment by rtuRgALp** [comment]
Hey Tiki,
Yeah, that’s what is happening here. The new resume point is set properly but the last played time stamp isn’t sent back, therefore the list order doesn’t update.

**Comment by Tikipeter** [comment]
I can't fix that I'm afraid. I've already tried a couple of months ago.

**Comment by rtuRgALp** [comment]
But I can’t wrap my head around why it was previously working?

**Comment by Tikipeter** [comment]
I've never seen it work with the particular scenario I'm talking about above (new resume point being set replacing an already present resume point). I don't get an updated watch time from Trakt in that instance.

I'm sure I know why it happens, but it's a decently large re-write of the code to get it working. And there's just not too many times multiple resume points are set for media. Not enough to warrant the work I'd have to put in to get it fixed.

If there's issues with episode progress ordering outside of the particular scenario I've outlined above, then that is something that I should be able to fix. But in my testing all of that works fine.

**Comment by rtuRgALp** [comment]
I respect your decision not to prioritize it. 

I do however still observe this bug with content I haven’t watched before. Even with the official Trakt add on scrobbling alongside Fen, it still doesn’t sort properly.

**Comment by Tikipeter** [comment]
Fen won't scrobble if the official Trakt addon is scrobbling. It needs to be one or the other. Never both.

>I do however still observe this bug with content I haven’t watched before.

If you give me an example I can try to replicate it. If it's independent of the scenario I referred to above, then it's something I can hopefully fix. Is there an episode right now in your list, that hasn't had 2 or more resume points set, that is not sorting properly?

**Comment by rtuRgALp** [comment]
Nevermind - it sorts properly if there's only one resume point. But once you add a second one, it stays in place. Guess I'll just have to live with this. I don't know how I didn't notice this before. I often pause content more than once to come back to it later (especially with episodic content that last an hour or more). This is a slight inconvenience; but, I appreciate you taking the time to reply to my issue report.
