### ISSUE TITLE
HDR filter not showing under results

### ISSUE THREAD

**Issue by rizreflects** [Tikipeter/repository.tikipeter#640]
Hey there, just a quick question. I recently booted up Kodi, updated fen and noticed the HDR filter was removed. 

![IMG_20211112_184930.jpg](https://user-images.githubusercontent.com/76912707/141519640-0aae4569-96bd-4bb9-b355-1d179e1a3d26.jpg)

Is this just on my end or did you remove the option? If it's the latter, any chance you could bring that option back? I utilize it a lot.

**Comment by Tikipeter** [comment]
Looks like somethings gone wrong with that language string. That setting should still be to toggle the HDR setting. It should still work.

**Comment by Tikipeter** [comment]
I'm home from work and it's what I thought. Fixed for next update.
