### ISSUE TITLE
Real Debrid no results

### ISSUE THREAD

**Issue by extremeaudio** [Tikipeter/repository.tikipeter#641]
I'm using Coreelec on Amlogic S912 so I cannot use Kodi Matrix. I am thus using fen 2.0.44 which I believe must be compatible with kodi leia. My build has been working perfectly fine for over a year but not working now. The search ends very fast and displays "no results".

Log - https://paste.kodi.tv/vuzecufeda.kodi

**Comment by Tikipeter** [comment]
Use these versions for Kodi 18 and turn off auto update for ALL of them..
[plugin.video.fen-2.5.07.zip](https://github.com/Tikipeter/repository.tikipeter/files/7534598/plugin.video.fen-2.5.07.zip)
[script.module.fenomscrapers-1.6.0.zip](https://github.com/Tikipeter/repository.tikipeter/files/7534599/script.module.fenomscrapers-1.6.0.zip)
[script.module.myaccounts-1.1.4.zip](https://github.com/Tikipeter/repository.tikipeter/files/7534600/script.module.myaccounts-1.1.4.zip)

I'm not 100% sure these are all the right versions for Kodi 18, so let me know if you still can't get it to work. Keep these somewhere so you can use them again if needed.

**Comment by extremeaudio** [comment]
Switched off auto updates.

Updated (downdated) fenomscrapers and myaccounts to 1.6.0 and 1.1.4 respectively. 

Updated fen to 2.5.07 and tried, the addon wouldnt open at all.  So I used 2.0.44 from here - https://repoil.club/plugin.video.fen/

This made the addon to open. But the same error as before.

Finally I found some older versions of fenomscrapers (1.4.2) and myaccounts (1.1.1)

That got it back up again. Thanks for the help.

**Comment by heferdl** [comment]
Hi 
I'm using RPI3 so I'm facing the same issue :(
Can you please add links to the files that enabled you to run FEN on KODI Leia:
fenomscrapers (1.4.2) and myaccounts (1.1.1)

Thanks

**Comment by Tikipeter** [comment]
https://github.com/Mr-Kodi/repository.fenomscrapers/raw/master/zips/script.module.fenomscrapers/script.module.fenomscrapers-1.4.2.zip

https://github.com/Mr-Kodi/repository.myaccounts/raw/master/zips/script.module.myaccounts/script.module.myaccounts-1.1.1.zip

**Comment by heferdl** [comment]
Thanks 
Now is working again :)
