### ISSUE TITLE
Jump To feature suddenly not working

### ISSUE THREAD

**Issue by ivarbrandt** [Tikipeter/repository.tikipeter#643]
For some reason the Jump To feature isn't working anymore. I tried with my collection, watchlist, and other lists. All of them load a blank list. I've attached my log.

[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/7581736/kodi.log)

**Comment by muzikherif** [comment]
Same here, jump to function with alphabet not bringing page, shows just empty.

**Comment by Tikipeter** [comment]
Fixed for next update.
In the meantime, "Page" still works for the Jump To setting if you need it.
