### ISSUE TITLE
Phyton 3.0

### ISSUE THREAD

**Issue by Hmeeberg** [Tikipeter/repository.tikipeter#644]
Hello,

I am using coreelec 9.0.3 and fen worked great.
A few Day ago i got the message:

The dependency on xbmc.python version 3.0.0 could not be satisfied.

Also the FenomScrapers module will not update. To version 2.0.3

I have removed Fen, but when i try   to reinstall, it says Add-on not compatibel with this version of Kodi. It always worked with this version.

Please can you help me.

**Comment by Tikipeter** [comment]
Fen and it's dependencies are no longer compatible with Kodi 18. You will need to install an older version of Fen and Fenom Scrapers if you wish to keep using it with Kodi 18. Best bet if you can't update Kodi would be to use another addon.

**Comment by Hmeeberg** [comment]
I am using Coreelec 19.3 Matrix. So that must be an other problem.

**Comment by Tikipeter** [comment]
>The dependency on xbmc.python version 3.0.0 could not be satisfied

That is not ambiguous at all. Either you aren't running Kodi 19, or you did not do a completely clean install when updating from Kodi 18. I can't see what else you think the problem might be?

**Comment by Tikipeter** [comment]
Or your whole install is messed up in some way. I suppose it could be that as well.

**Comment by Hmeeberg** [comment]
Why did it work before. It workt fine on Coreelec 19.3 Matrix. I didnot update or did something else to messup the Coreelec.

**Comment by Tikipeter** [comment]
Absolutely no idea outside of what I've already written above. I don't have access to your install to see. Post a log and I'll have a look.

**Comment by Tikipeter** [comment]
Can you use other addons that are Kodi 19 only?

**Comment by Hmeeberg** [comment]
Yes, no problemen there i think. I use Sereen and The Oath. Dont know if
they are 19 only.

Op ma 22 nov. 2021 20:26 schreef Tikipeter ***@***.***>:

**Comment by Hmeeberg** [comment]
Yes, no problemen there i think. I use Sereen and The Oath. Dont know if
they are 19 only.

**Comment by Tikipeter** [comment]
Neither of those are Kodi 19 only.
Please post a log.

**Comment by Hmeeberg** [comment]
No idea how that works. Posting a log.
Name an 19 only addon will try to install that one

**Comment by Tikipeter** [comment]
Venom. Try that.

If you do not post a log with your next reply I am going to have to close this issue. I am using my free time here to try and help you, but you are unwilling to do what I have said I need you to do to achieve that help. The rules clearly state you need to post a log, but you are unwilling to do it.

**Comment by Hmeeberg** [comment]
I am not unwilling. I am not a specialist. So i have no idea how to post a
log, sorry.

I appreciat you donig this for me.

Op ma 22 nov. 2021 20:48 schreef Tikipeter ***@***.***>:

**Comment by Hmeeberg** [comment]
Hello,

When installing Venom, i get the same faultmessage.
So i think, my setup is somehow gotten corruptet.

You were right.

Will do an new install of Coreelec.

Thanks for youre help.

Op ma 22 nov. 2021 20:48 schreef Tikipeter ***@***.***>:

**Comment by Tikipeter** [comment]
Alright. Easier (and quicker) to learn how to post a Kodi log than to reinstall a whole operating system. But that is your choice to make, so I can't speak on that.

But I do encourage you to take just a couple of minutes and educate yourself on how to retrieve and post a Kodi log. Use an internet search engine to look up how to do it. It's very easy usually.

**Comment by Hmeeberg** [comment]
Hello  sorry that it took so long. I had to learn this first
![20211126_151456](https://user-images.githubusercontent.com/94850471/143594081-484371dd-91af-4904-a080-e99400555e60.jpg)

Https://paste.kodi.tv/0jur0wab0s

I hope this is ok this wat.
.

**Comment by Tikipeter** [comment]
Good job with the log. I had to change the link (it was `o` not `0`) but I got it.

Now for the bad news... The first line of the log:
```
Starting Kodi (18.9 (18.9.0) Git:00ff7594e42e9539912c9bd12c5a6a9d1b9d8d78). Platform: Linux ARM 32-bit
```
You are running Kodi 18.9 like I thought. :)
Sorry to be the bearer of bad news. Fen doesn't work on Kodi 18 anymore.

**Comment by Hmeeberg** [comment]
Thanks for your help.

I need to update, but i have no idea how to put the tar file in the update
folder.

I have downloaden it on an usbstick. But no idea how to copy and paste it.

Tia.

Op vr 26 nov. 2021 23:06 schreef Tikipeter ***@***.***>:

**Comment by Tikipeter** [comment]
I've not used Coreelec, but I do use LibreELEC and they are likely the same with regards to updating. You can use Kodi's File Manager to put the tar file where it needs to be once you've connected the USB stick to your device.

There will be an `.update` folder inside the CoreELEC folders. You need to navigate into that folder, and then on the other window of the Kodi File Manager you need to navigate to your usb stick. Then select the tar file, and select "Move" or "Copy" and then it will move/copy that tar file into the .update folder.

Then restart CoreELEC, and during the restart it should detect a file in that update folder and attempt to install the update.

As always, anything could go wrong, so don't have anything on that device that you are unwilling to lose, and cross your fingers during the process.

Also, this is a MAJOR update for Kodi, so you will need to wipe all your data (settings, currently installed addons etc) from the device after update and restart fresh. Usually this would not be the case, but the change from python 2 to python 3 necessitates this, otherwise you will more than likely have many problems.

**Comment by Hmeeberg** [comment]
Thanks for your help.

Youre right they work the same.

I will try and let you know if i got it werking.

Greetings.

Op vr 26 nov. 2021 23:32 schreef Tikipeter ***@***.***>:

**Comment by Tikipeter** [comment]
Good luck.

**Comment by odroider** [comment]
You can use the CoreELEC addon to update to 19.3 - Matrix directly.

I use CoreELEC Matrix 19.3 and the latest FEN works fine.

**Comment by Hmeeberg** [comment]
I have triest that, but the update stays empty. I see nothing when i select
1.

Plz help.

Tia

Op za 27 nov. 2021 11:04 schreef odroider ***@***.***>:

**Comment by Tikipeter** [comment]
I don't think I'm capable of helping you more. Try to explain what you did and where it went wrong for you.

**Comment by odroider** [comment]
Hmeeberg: You don't say what hardware you are using with CoreELEC, but I would add that with ColreELEC 19 - Matrix, support for older Amlogic SoC's such as the S905 was discontinued. As it will not update it might be you are using an older Amlogic SoC in which case it will not be updateable.

**Comment by Hmeeberg** [comment]
Hello,

I am using an MS8 pro L S912.
Is this one still supported?

Greetings.

Op ma 29 nov. 2021 17:02 schreef odroider ***@***.***>:

**Comment by Hmeeberg** [comment]
I get to this and then i am stuck
![Uploading 20211129_172822.jpg…]()
.

**Comment by Tikipeter** [comment]
That image doesn't show for me...

I really think you need to go to the CoreELEC forums at this point and let them help you with the install.
