### ISSUE TITLE
Immediate No results

### ISSUE THREAD

**Issue by easyjim** [Tikipeter/repository.tikipeter#646]
I've had this issue in the past and not been able to fix it but it normally resolves itself if I leave it a day but I can't get Fen working again this time.
Coincidental maybe but a few times this has happened has been when I've selected something to scrape and immediately changed my mind and pressed back, Fen will then show no results for everything.

I've cleaned caches on Fen and Kodi, I've resynced my accounts, disabled scrapers and enabled but no luck, pretty sure everything is up to date.

Log>>> https://paste.kodi.tv/bowibisilu

**Comment by Tikipeter** [comment]
You're on Fen version `2.5.08`. The latest is `2.5.09`.

"...pretty sure everything is up to date" - Let me know how you checked this so I can see what the problem is with getting accurate info of what the most recent release of Fen is.

**Comment by easyjim** [comment]
Ah ok, everything is set to auto update > any repository, there is no "available updates" section in add-ons, when I click the fen add-on through there it does not display an "update available" message, manually clicking update does nothing. In add-ons I click check for updates and nothing is found.

The only way I could update was clicking options, versions and selecting 2.5.09

Probably something screwy at my end

**Comment by Tikipeter** [comment]
Does it work now on 2.5.09?

**Comment by easyjim** [comment]
Yes it does, thank you

**Comment by scalpmonkey** [comment]
I had this issue with the latest 2.5.11 build on Android TV.
The problem was the dependencies weren't installing/updating. If someone have this issue you will need to manually go to FEN in addons, click Versions -> FEN 2.5.11 and install/update dependencies one by one. 
After that it worked as intended.
Thanks for it btw.

**Comment by DaisyF8** [comment]
I'm having to go through Versions as wel. Noticed a week ago I was five updates behind on Fen.
