### ISSUE TITLE
[Clues] Updating Fen through Versions

### ISSUE THREAD

**Issue by DaisyF8** [Tikipeter/repository.tikipeter#648]
I generated this Issue just to give @Tikipeter some info... I don't expect a solution right away since I think this behaviour is tricky.

Maybe this only happens to some users, but for me/us Fen updates don't show up.  In another issue I saw others also needing to go to Versions to update Fen.

I was messing around in the dependencies and I saw this :   (all screenshots are in sequence).

![screenshot00000](https://user-images.githubusercontent.com/10348988/143249153-590aab34-caaa-4dff-a803-d5254641f427.png)
I updated to 2.5.10 (latest version before update to 2.5.11 some hours ago - didn't do that one yet) yesterday, but in Dependencies it says I need to update My Accounts to 2.0.0

![screenshot00003](https://user-images.githubusercontent.com/10348988/143249874-ce4f10f7-f2e3-4a6b-bfc1-1233d264aed9.png)
But if I look at the installed version, it allready is 2.0.0

![screenshot00004](https://user-images.githubusercontent.com/10348988/143250102-ef67cd1e-8ec2-47b6-a668-bc88b9444e9b.png)
When I update...

![screenshot00007](https://user-images.githubusercontent.com/10348988/143250421-d31404b4-ea5d-4e09-8c59-9e9aa9bc002a.png)
In Dependencies the installed version is correct.

I have both Fen and Venom installed.

Also, after that one update orphaning Tiki Skins Module I could have sworn I uninstalled it but ...

![screenshot00006](https://user-images.githubusercontent.com/10348988/143250732-77e08bc1-5bfc-4342-9551-e8a678c8ed3f.png)
... it's still there ? Am I misremembering or did it reinstall ?

**Comment by DaisyF8** [comment]
And Fen 2.5.11 did show up just now in Available Updates.  But sometimes it doesn't and that's when I start skipping updates until I go to Versions and update manually.

**Comment by Tikipeter** [comment]
Firstly, you must have misremembered removing the tikiskins module. There is nothing in the repo to be donwloaded. It doesn't exist anymore, so could not have been re-downloaded.

 To get to the bottom of what's happening here, you need to investigate which repo these modules and addons are currently linked to by Kodi. Unfortunately it is a new Kodi "feature" that you can only receive updates from the repository that the module/addon was initially installed from. So if you installed Venom before Fen, then you will receive your My Accounts and Fenom Scrapers updates through the Venom repo. That shouldn't be an issue of course, as both 123Venom and myself link the same source for the repo updates.

On the other hand, if you were to have installed Fen through the Venom repo before he removed it, then there is no link with Fen and the tikipeter repo. So you won't receive updates.

Navigate to the tikipeter repository, and check that "Installed" is listed next to Fen. If not, the Fen install you have is not linked to the repository, and you won't receive updates. Also check which repository My Accounts and Fenom Scrapers are linked. It could be Tikipeter or it could be 123Venom.

Another thing to remember is if at any stage you manually install an update to any of these modules/addons i.e. install from zip, then the link to the correct repository will be lost by Kodi, and you will need to reinstall from the correct repository to regain that link.

Just some things to think about if you are troubleshooting this.

**Comment by DaisyF8** [comment]
Thx for your tips. I think I did what you said about a manual install. I did that (was a previous issue I registered here) to solve a problem, succeeded, but didn't link to the original repo afterwards.

I'll keep an eye out for the checks you mention that I can do.

**Comment by Tikipeter** [comment]
I understand Kodi devs introducing this "feature" so rogue repositories cannot hijack an addon and update it with nefarious code, but it does introduce this problem that needs to be looked out for. I would say now that you know about it it likely won't catch you again. It is possible that it isn't the root of your problem, but more likely than not it is.

**Comment by DaisyF8** [comment]
The last bit what you say yeah... this addon (and another popular addon I use also) sometimes just seems to lose track of updates.  It's a bit weird really.

**Comment by FlaParrotHead** [comment]
A simple question.. what is the correct repository we should have in our builds?  I originally had to d/l the zip directly due to repository issues.
