### ISSUE TITLE
[Playback] Autoplay Next Episode + Source Select

### ISSUE THREAD

**Issue by tundrablasen** [Tikipeter/repository.tikipeter#649]
Hi tikipeter

I have a feature request you might want to consider.

currently as I understand it, you can only choose if you want to autoplay a tv show and then auto play a next episode. Therefore manual source select is not available.

but I really like to choose my own source from the list. But then I am missing the autoplay next episode feature because you can just turn that on when choosing “autoplay” for tv shows.

could you please make “autoplay next episode“ able to toggle on when not choosing autoplay for tv shows.
this would result that we still get the next episode screen when reaching the end of the episode. And automatically the source select screen comes up for the next episode. One click choosing the perfect sourcefile and the fun continues. Currently it’s much more clicks and waiting times because of the end of an episode it loads the Menü screen again etc.

Seren has this feature but FEN is much cleaner and faster and I love the easynews support which supports my PM.

**Comment by Tikipeter** [comment]
>Currently it’s much more clicks

One more?

I'm afraid that is a feature that will never be implemented in Fen. It has been discussed at length before. You are not autoplaying something if you are choosing the link, so it makes no sense to me. It's whole purpose seems to be saving the user one click when you want to watch the next episode.

**Comment by tundrablasen** [comment]
Yes agree. It’s not that much more clicks. 

But it’s more time. Waiting for the Menu  to load. Scrape again etc. 

Compared to pre scrape in the background and getting instantly the source select.

But as I mentioned it was just a suggestion 👍

**Comment by Tikipeter** [comment]
I understand it has some utility. It is just unfortunate this is what you have requested as I have a history with this particular request which means I'm not willing to entertain adding it to Fen.

Anything else.....sure. Just not this one.

**Comment by tundrablasen** [comment]
Roger that. Not a big deal. To be honest I also should have read the closed issues and see if that was already addressed. So it’s my fault. 

What I noticed anyway is with the auto play next episode pop up at the end of the episode:

when using vanilla Kodi with the vanilla estuary skin, then you can barely see if you are currently navigating on the „play“, „cancel“ and „close“ button.

It would be great if there would be better visibility of that (maybe another Color of the button when navigating on it). Something with more contrast.

i would assume most users use the standard Kodi skin. 


thanks tikipeter for this amazing addon!

**Comment by Tikipeter** [comment]
>To be honest I also should have read the closed issues and see if that was already addressed

That certainly wasn't expected by me. There are nearly 650 closed issues! But I appreciate the sentiment.

The button contrast issue is due to me using the python PIL module to choose those buttons' highlight color. It gives me a color to use based on the poster color. Sometimes this works great, sometimes it definitely doesn't.

I think I will remove this from the buttons I currently use it for (it is used also for the highlight color when navigating in the Extras window). It would be much more consistent to simply have  a decently contrasted highlight color instead.

**Comment by Tikipeter** [comment]
Button highlight color fixed for next update.
