### ISSUE TITLE
Enhancement 

### ISSUE THREAD

**Issue by JayDee696969** [Tikipeter/repository.tikipeter#65]
Loving the addon. Was just wondering if possible to add an option to open Extended Info mod when selection Movie or show. I really like the OpenInfo GUI. I know you can open the context menu and choose Extended info to get there, but was wondering if an option could be added to set as default to open Extended Info when selecting a Movie/Show. Thanks! I also Know you can set the Kodi settings to open Info when hitting Play, but I only want it for FEN.

**Comment by Tikipeter** [comment]
Hi JayDee696969.

How would you then proceed to play back the Movie/Episode?

**Comment by JayDee696969** [comment]
> Hi JayDee696969.
> 
> How would you then proceed to play back the Movie/Episode?

You would hit the Play button in OpenInfoMod, Like this:  https://vimeo.com/376341149

**Comment by Tikipeter** [comment]
I see. Use Openmeta's players.

I should be able to get this done. I'm still busy with work atm, so give me a few days...

**Comment by JayDee696969** [comment]
> I see. Use Openmeta's players.
> 
> I should be able to get this done. I'm still busy with work atm, so give me a few days...

Thanks, no rush. Just thought it would be a cool way to use FEN.

**Comment by JayDee696969** [comment]
Oh, and while your here,I couldnt see a clear answer to this. What exactly is the Real Debrid authentication in the addon for? Is it just for RD Cloud service?  I am assuming I still need to authenticate RD using ResolveURL to use Tiki Scrapers correct? I have RD, just not exactly sure what RD Cloud is used for, lol.

**Comment by dm2912** [comment]
I think its for stuff thats in your personal cloud. Its particularly useful for hard to find series or series that have trouble finding episodes. I just zap the season pack into my RD torrents, and once its there then it automatically finds it in Fen straight away.

**Comment by host505** [comment]
Correct, it's for the Rd cloud scraper, but Rd auth in Fen is also used for the check Fen does to determine if a torr is cached on Rd or not.

**Comment by Tikipeter** [comment]
Yep, everyone's correct. :)
It's for access to your RD cache, and to check for cached torrents.

PM is for the same reasons.

**Comment by Tikipeter** [comment]
Jay Dee696969, where would you want extended info opening for tv shows? At the show level, or episode level?

**Comment by JayDee696969** [comment]
> Jay Dee696969, where would you want extended info opening for tv shows? At the show level, or episode level?

Hmm, I guess the show level, because the seasons show right underneath in Openinfo along with trailers, etc.

**Comment by Tikipeter** [comment]
This will be in the next update. Movies and TV Shows will have separate settings.
