### ISSUE TITLE
No Results

### ISSUE THREAD

**Issue by mrXoo** [Tikipeter/repository.tikipeter#651]
Hi there,

Im having the same issueas before. Its as if the external scrapers are not getting searched at all. The only results I do get are in purple from my RD Cloud.
Ive tried everything to get it back to searching the external scrapers.

Log attached. Ive debugged the Fenom scrapers addon

The first time I tried No Time to Die and immediately no results. the next one I tried was Venom and that was in my RD cloud and it played just fine

[01_KODI.log](https://github.com/Tikipeter/repository.tikipeter/files/7673640/01_KODI.log)

**Comment by Tikipeter** [comment]
Your log says you have `plugin.video.fen v3.5.06` installed. The current version of Fen is `v2.5.12`.

How you got a version of Fen on your system that shouldn't exist I have no idea. But that will be your issue.

**Comment by mrXoo** [comment]
Hmm interesting, no idea other than i changed the version for my Leia box. Ill uninstall and reinstall and see if that fixes it.

Thanks for your help

**Comment by mrXoo** [comment]
Yes that fixed it lol
