### ISSUE TITLE
Pre-scrape extreamly slow (2.5.12 Ver)

### ISSUE THREAD

**Issue by fxreza** [Tikipeter/repository.tikipeter#652]
After updating to 2.5.12, pre-scrape ( I have only Real-Debrid and all others are disabled) takes 45 seconds and most of the time it won't find the links which already are in RD cloud. 
Even if find a link it won't play it right away, it starts external scraping and when finished, it will play the link. 

It was working well before and played RD cloud link pretty fast.

**Comment by Tikipeter** [comment]
Please post a log or this will be deleted as per the rules.
