### ISSUE TITLE
Progress/Scrobbling

### ISSUE THREAD

**Issue by derrgoo** [Tikipeter/repository.tikipeter#653]
Hi Peter,
Thanks for the update. It appears you added Scrobbling trakt? I was testing and seems to pick up where I left off in different android boxes. Great feature. 👌

**Comment by KalAvroniev** [comment]
I think the latest update stopped flagging videos as watched. I tried a few and none are marked as watched. Or do we still need the Trakt addon for that?

**Comment by derrgoo** [comment]
Mine are still showing. Depends on skin sometimes.

**Comment by KalAvroniev** [comment]
I checked direct on trakt an they are not marked as watched.

**Comment by derrgoo** [comment]
Yea not sure. Mine also marks trakt with my latest test.

**Comment by KalAvroniev** [comment]
Do you have the Trakt addon or just Fen? I disabled the Trakt addon and nothing gets marked as watched for me

**Comment by derrgoo** [comment]
I only ever use fen not the add on. I have updated version which is my main add on. Everything working as usual.

**Comment by KalAvroniev** [comment]
Very odd

**Comment by xyzfre** [comment]
> Very odd

Try deleting the Trakt addon and only use Fen having both can cause issues if you have Fen sync with Trakt you don't need the Trakt addon

**Comment by KalAvroniev** [comment]
I did that and it seems to work for Movies but does not seem to for TV Shows.

**Comment by derrgoo** [comment]
[request if possible]

I really find Scrobble trakt progress awesome. However, when I goto another box I usually end up pulling up context menu and clicking on fen refresh widgets, because widget seems to update at the end of loading kodi and just faster using your refresh.

Is it possible to have a setting that when you load kodi it will automatically refresh widgets? Or is this just a kodi issue waiting to do it once everything is loaded?
