### ISSUE TITLE
Enhancement Request - Search From Library

### ISSUE THREAD

**Issue by shoppedude** [Tikipeter/repository.tikipeter#654]
Scenario: My wife and I watched an episode of NCIS. I fell asleep on the couch, and missed 2/3 of the episode. At the end, she by default deleted the episode.

Current Solution: I enter Fen, search for NCIS, scroll to the current season, find the episode, and watch.

Enhanced Solution: Within my library, I hit the menu button and select "Search Fen for this Show". Fen opens and automatically searches for NCIS, saving both navigation and typing steps.

Thanks for the consideration!

**Comment by Tikipeter** [comment]
Library playback is not supported at all I'm afraid. Perhaps it's something that TMDbHelper dev might be able to integrate for you. Would be more of a generic solution.


From Posting Issues Rules....
`Issues related to playback through TMDbHelper will NOT be supported here.`

Perhaps it's something that TMDbHelper might be able to integrate for you. More of a generic

**Comment by shoppedude** [comment]
I don't use, nor do I wish to use, TMDBHelper. I'm also not looking for Library Playback, per se. I am more about a menu hook into the Fen search function.

I read the rules. If this was related to TMDBHelper, I wouldn't have posted the question.

**Comment by Tikipeter** [comment]
Then you need to explain yourself better, or adjust the terminology you are using.
i.e. You say:
`Within my library`
`default deleted the episode` - What does that mean?

You need to explain what you are saying more clearly.
