### ISSUE TITLE
Real Debrid not authorizing correctly resulting in no results 

### ISSUE THREAD

**Issue by KTBoxer1** [Tikipeter/repository.tikipeter#656]
Not having a problem with any other addons. When authorizing real debrid, there's a massive delay in the prompt coming up. 60+ seconds. After authorizing another 60-120 seconds pass before it says its authorized. When searching, it will show that its gathering results and then say "No Results".  

When I check to see if Real Debrid is authorized, it does show that it's connected. It's almost as if the ISP is blocking something with FEN.

Everything was working fine, I haven't made any changes on my end for months. This just started happening a few days ago. 

Appreciate any help.

Included log
https://pastebin.com/HkWbwJ1M

**Comment by Tikipeter** [comment]
Nothing sticks out in the log I'm afraid.

Maybe try a "Revoke" of the RD auth in My Accounts and then try and authorize again.

**Comment by od420** [comment]
So I'm having the same issue. Not getting any results. Trakt also is not synced at all on tv shows but everything is synced on movies. I've revoked both trakt and realdebrid and reauthorized with the same issue going on. I've also tried on another device with the same problem .

**Comment by sblair77** [comment]
Same. Trakt is fine for me but premiumize, real debrid and all debrid all return no results. I tried the all to see if one was down.

**Comment by Tikipeter** [comment]
Those are not the same issue as OP.
Wait for a FenomScrapers update to fix your issues, or go into Fenomscraper settings and turn OFF "Torrents->Remove Undesirables".

Start a new Issue with any Trakt problems.

**Comment by KTBoxer1** [comment]
Yup, now a bunch more are popping up tonight with other family members on different machines.. I have revoked, reauthorized. Nothing. ..

**Comment by KTBoxer1** [comment]
I'm going to try turning off undesirable and see what happens as soon as I get back.  Appreciate your help as always.

**Comment by tomtomclub** [comment]
Same here fen and venom after update

**Comment by mystik1** [comment]
@KTBoxer1 Show context menu, go into Options, and Rescrape.  I had the same issue (no results with Ptemiumize).  Came here to either post on it or see if there was something from another person.  Saw the workaround above, and it worked.

**Comment by tomtomclub** [comment]
> @KTBoxer1 Show context menu, go into Options, and Rescrape. I had the same issue (no results with Ptemiumize). Came here to either post on it or see if there was something from another person. Saw the workaround above, and it worked.

Nothing wrong with fan on Venom The Problem is Venom scrapers Don update scrapers

**Comment by KTBoxer1** [comment]
Awesome, let me give that a try shortly and I'll report back

**Comment by od420** [comment]
Everything is working normally now and I'm not experiencing any issues. All is right in the world! Thanks for all the hard work.

**Comment by Bea979** [comment]
Above fix  worked for me! Thanks 👍🏽
