### ISSUE TITLE
Season pack download broken? (Cached pack) 

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#658]
Is it just me @Tikipeter?
Downloading movies is working great (I noticed a new pop-up, so you can name the folder yourself), but at a cached package (for tv shows), I see that pop-up like 0,5 seconds, and gone (and not asking if i want to download the selected episodes that I all selected).

I'm on my bed now, so I am not able at the moment for a log, but, I can do that in a few hours If needed, but maybey you can reproduce it just easy.

Thx.

Edit:
I used 'Welcome to earth' show, from National Geografic.

**Comment by Tikipeter** [comment]
Yep, I likely broke something with it.
I'll get it sorted for next update.

**Comment by Tinuz97** [comment]
Thx 😀

**Comment by Tikipeter** [comment]
Silly error. Fixed for next update. :) :)
