### ISSUE TITLE
Furk api issue?

### ISSUE THREAD

**Issue by sasagr** [Tikipeter/repository.tikipeter#659]
Hi tiki. Hope everything is ok. I just discovered that furk is not getting any results and also in my service I cannot connect to it (going to account info for example). Here a log when trying to get the account info. I get message on screen saying ‘NoeType Object’ I’m not subscriptable. 
https://paste.kodi.tv/alifaloqum
I m using Kodi 20 alpha on Apple TV. I have not having issues with this build in recent times with Furk. Pls let me know if it is an issue it can be easily solved.

**Comment by tomtomclub** [comment]
> Hi tiki. Hope everything is ok. I just discovered that furk is not getting any results and also in my service I cannot connect to it (going to account info for example). Here a log when trying to get the account info. I get message on screen saying ‘NoeType Object’ I’m not subscriptable. https://paste.kodi.tv/alifaloqum I m using Kodi 20 alpha on Apple TV. I have not having issues with this build in recent times with Furk. Pls let me know if it is an issue it can be easily solved.

Nothing wrong with fan on Venom The Problem is fenom scrapers go to programs fenom scrapers module. Configuration. Clean settings file punches and uses it venom en Fen works for 
Mi .Maby it work for you

**Comment by 123Venom** [comment]
Furk's been down for last 24hrs and this has nothing to do with the above response.  Until Furk comes back online there's nothing we can do here.

**Comment by sasagr** [comment]
My bad I did not check their website before posting the issue. Maybe to leave it open till furk works again so another one will not issue the same :)

**Comment by Tikipeter** [comment]
Good to see you sasagr. :) Hope you're well also.

123Venom's right of course. Furk's having issues. We just have to wait it out. Maybe they've shut up shop. I've not seen a time where you can't even land on an error page before.
