### ISSUE TITLE
Tiki scrapers cfscrape.py (update needed I think) 

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#66]
It looks that the cfscrape.py needs to be updated, sources that are using the CloudFare bot page (like the rlsbb scraper as 1 example), are not giving any links back.

Could you maybey take a look at this, not sure if it has a fix, but updated like 19 hours ago. 

https://github.com/VeNoMouS/cloudscraper

**Comment by Tikipeter** [comment]
I tried (and failed) to convert that for use with Kodi. I'm afraid I'll have to wait for someone more skilled than myself to put out a new cfscrape.py.

Keep an eye out Tinuz97, and let me know if anyone updates their cfscrape.py. I'll take a good look at the differences with regard to the updated cloudscraper file, and hopefully learn how to implement an update myself next time, instead of waiting for someone else to do the work..

**Comment by Tinuz97** [comment]
@Tikipeter, did not test it, but can you take a look at this?
Updated a hour ago (openscrapers). 


https://github.com/a4k-openproject/script.module.openscrapers/commit/1212085170b76a1390f92ad16d01c4346392a971

**Comment by Tinuz97** [comment]
![Screenshot_20191202-003358](https://user-images.githubusercontent.com/47715606/69922301-7f830200-149b-11ea-91c3-1201269d3ba4.jpg)
Tested with Venom (using openscrapers), working (rlsbb links are back). 

Maybey you can convert it if needed, to work with tiki scrapers.

**Comment by Tinuz97** [comment]
I also see a cfscrape_solver.py (cfscrape.py also available)

**Comment by Tikipeter** [comment]
Thanks a lot Tinuz97. It's a different format to the one I was using in tikiscrapers, but like you say it works with cfscraper_solver. I'll push an update for tikiscrapers.

**Comment by Tinuz97** [comment]
🍻

**Comment by Tinuz97** [comment]
I did the update few minutes ago (fen and tiki scrapers).

Cleaned all cache, I even remove tiki scrapers (closing kodi, remove in userdata and in addons, in Fen dependencies, reinstall tiki scrapers). 

As soon I wants to scrape, it trows a error pop-up (oneplus 5 phone, android 9).

Log:


   - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named user_agents
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.fen/resources/lib/fen.py", line 88, in <module>
                                                literal_eval(params.get('library', 'False')), params.get('background'), literal_eval(params.get('autoplay', 'None')))
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.fen/resources/lib/modules/sources.py", line 75, in playback_prep
                                                self.get_sources()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.fen/resources/lib/modules/sources.py", line 82, in get_sources
                                                results = self.collect_results()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.fen/resources/lib/modules/sources.py", line 125, in collect_results
                                                self.providers.append(('external', ExternalSource()))
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.fen/resources/lib/scrapers/external.py", line 29, in __init__
                                                self.getConstants()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.fen/resources/lib/scrapers/external.py", line 726, in getConstants
                                                self.sourceDict = sources()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.tikiscrapers/lib/tikiscrapers/__init__.py", line 23, in sources
                                                module = loader.find_module(module_name).load_module(module_name)
                                              File "/home/jenkins/workspace/Android-ARM64-Leia/tools/depends/xbmc-depends/aarch64-linux-android-21-release/lib/python2.7/pkgutil.py", line 243, in load_module
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.tikiscrapers/lib/tikiscrapers/sources_tikiscrapers/en/0123putlocker.py", line 5, in <module>
                                                from tikiscrapers.modules import cleantitle,client,proxy,cfscrape
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.tikiscrapers/lib/tikiscrapers/modules/cfscrape.py", line 21, in <module>

**Comment by Tinuz97** [comment]
@Tikipeter, 1.1.2.4a fixed it (the scraping error, does scrape fine now).

But still not returning rlsbb (as a example of a CloudFare scraper) links, is it just me?

**Comment by Tikipeter** [comment]
Not just you. It doesn't seem to be performing well. I will have a look at it and see if there are errors.

**Comment by Tinuz97** [comment]
Also look, compare scrapers (I think), looks that need to change also, I did see something new like
self.scraper = cfscrape.create_scraper()

**Comment by Tinuz97** [comment]
(Compare with openscrapers, I see the self.scraper = cfscrape.create_scraper() in it, never did see that before)

**Comment by Tikipeter** [comment]
I'm going to push a new version in a minute. See if it improves result numbers (I had rlsbb results in one search, not another. So it did show at least once). But it returns a lot more hoster results for me now...

**Comment by Tinuz97** [comment]
This one shows rlsbb allot like before, and other hosters indeed, nice. Thx.

**Comment by Tinuz97** [comment]
@Tikipeter, can't find my other message, so I just post it in here.

Tested the latest version, if api set to Dutch, the downloader respects the filename now also, working 100%

Realy nice 🥰

**Comment by Tinuz97** [comment]
I remember that you did say you don't do python that long, but this is realy one of the best Addons in development.
Fen is my daily driver now, Seren as backup, and that was my favorite one before Fen. 

Good job sir.

**Comment by Tinuz97** [comment]
@Tikipeter  ,i don't want to spam with opening a new 'ticket'. but i noticed in trakt_api.py this (last line)

        from Wmodules.nav_utils import notification
        notification('Error getting Trakt Watched Info', time=3500)
        pass


Is Wmodules.nav_utils OK? Does it need to be modules.nav_utils ?

**Comment by Tikipeter** [comment]
That definitely shouldn't be Wmodules! Thanks Tinuz97.

**Comment by Tinuz97** [comment]
Is it just me, or is 'preparing sources' and calculate/display the links much (seconds) slower after the latest update? (  before the autoplay fix version was much faster, could be me, no idea).

Tested on Oneplus 5 Android phone (snapdragon 835 cpu, 8GB ram), nvidia shield tv pro 2017 (Modded with SSD inside, so faster as stock pro 2017).

**Comment by Tinuz97** [comment]
Like 48 seconds, I think before it was like 20-25 seconds. 

The screen that pops up for scraping does take longer, preparing is longer, calculate and display the links also. 

Never had it  before (fast al versions before), I am wondering if this is just me. 
Wiped all cache, tryed Realdebrid account only, removed credentials Realdebrid, did auth premiumize (to see if one of them did slow it down), but i keep the 'issue',on my phone and my shield (my phone specs are faster as the shield). 

Do you have any idea how I can troubleshoot this? (it started with 1.5.76, and meta module 1.1.26)

Performance video (phone) 

https://tinuz97.stackstorage.com/s/QVQz0vqYiMiwYfs

**Comment by Tinuz97** [comment]
![Screenshot_20191204-001510__01](https://user-images.githubusercontent.com/47715606/70098097-5ee9b200-162b-11ea-8e65-415d21f6f2f9.jpg)

Hzm, seeing more messages pop-up, weird. (did wipe his name for privacy)

**Comment by Tikipeter** [comment]
There was a problem with 1.1.76, that I then tried to fix with 1.1.76a. Both were causing a slowdown for not only Fen, but Kodi in general. I've pushed 1.1.76b to fix the issue, so the Repository needs to be refreshed.

**Comment by Tinuz97** [comment]
1.5.76b fixed it indeed.
Fast again on my phone and nvidia shield tv 😎
