### ISSUE TITLE
“And Just like That” Scraping Issue (Internal + External)

### ISSUE THREAD

**Issue by tundrablasen** [Tikipeter/repository.tikipeter#660]
full disclosure: I opened the same issue in [fenomscrapers GitHub](https://github.com/Mr-Kodi/repository.fenomscrapers/issues/27) since I do not know if the issue is related to FEN or FENOMSCRAPERS 

So it seems there is a scraping issue with the new HBO Max Show “And Just like That…”

http://www.themoviedb.org/tv/116450-and-just-like-that

It’s the new sex and the city spin off and obviously often female viewers want to see that show.

anyway FEN does not find any torrent sources for this show. Not externally not internally. Even though many many torrents are cached in Premiumize and also I have added manually torrents from rarbg to my PM Cloud. Both doesn’t get detected.

it is NOT related with the undesirables issue from previous fenomscrapers versions. (At least I think that). Because I have 2.0.7 and everything else up to date and other shows/movies scrape just fine.

i checked other kodi addons which does not utilise fenomscrapers and they detect cached sources for this show just fine.

Initial,y I thought it has something to do with the “…” in the show name which no source has in their file name.

**Comment by tundrablasen** [comment]
Seems to be really FEN related. Venom and Seren work fine. 123Venom confirmed in fenomscraper repo.

reinstalling FEN does not fix the issue. Same as cleaning settings.

**Comment by Tikipeter** [comment]
It's going to be the `...`'s at the end that are the issue.
If you like, you can bring up the context menu, select "Options" and then "Scrape With Custom Values" to do a custom search and remove those trailing `.`s.

**Comment by tundrablasen** [comment]
> It's going to be the `...`'s at the end that are the issue.
> If you like, you can bring up the context menu, select "Options" and then "Scrape With Custom Values" to do a custom search and remove those trailing `.`s.

I don’t think that’s that the issue. I added the „…“ manually in the filename (and folder) of the PM cloud and it still wasn’t found. 

Also Venom and Seren finding the show and results. 

My context menu for options does not have any entry for search for custom values

**Comment by Tikipeter** [comment]
>My context menu for options does not have any entry for search for custom values

Sure it does. When highlighting an episode/movie in Fen - Context Menu->Options...->SCRAPE WITH CUSTOM VALUES.

>I don’t think that’s the issue.

It is. The `…` in the show title is not actually 3 x periods, it is a `Horizontal Ellipsis`. So adding 3 dots to those titles will not make it work, but it is still the cause of the issue. I've switched to using a different (i.e. correct) unicode normalization method for the next update, which will convert this horizontal ellipsis into 3 x dots like it should be. Then everything will work like it should.

>Also Venom and Seren finding the show and results.

Venom's the bomb! Use Venom. It's much better than Fen.

Anyway, fix in next update.

**Comment by tundrablasen** [comment]
Thanks for your reply. I will make tomorrow some screenshots of my context menu. Already turned off the TV. Maybe I am just blind. Im sure it is there. But I normally use the options context menu when I want to manually rescrape and select source and I didn’t see it there. Nevermind. 

Also thanks for the detailed technical explanation and for the fix. 

I did not mention the other addons to tease, rather to help pin point down the issue. 

Glad you found so fast a solution and pushed it in the next update. 

Thanks tiki for your addon.

**Comment by Tikipeter** [comment]
>I did not mention the other addons to tease, rather to help pin point down the issue.

I know. I was just having a joke. :) It is, of course, a great addon though.
Venom dev helped me track down the issue.
