### ISSUE TITLE
I started getting issues playing videos and kodi crashes

### ISSUE THREAD

**Issue by KalAvroniev** [Tikipeter/repository.tikipeter#662]
Lately I've not been able to play lots of videos. Keep getting an error "One or more items failed to play. Check the log for more information about this message." 
Sometimes no error at all, it tries to play and then fails. 
Other times if the video is xVid it crashes Kodi all together

Not sure if it is add on related or Real-Debrid but I could see some Fen errors so thought, I might as well check with you.

Attached is an export of my log - [https://paste.kodi.tv/tolizazobi](https://paste.kodi.tv/tolizazobi)

**Comment by Tikipeter** [comment]
There's a 503 error on the RD link Kodi tried to play.

**Comment by KalAvroniev** [comment]
OK must be RD.
