### ISSUE TITLE
Trakt lists no longer populating

### ISSUE THREAD

**Issue by JFG1000** [Tikipeter/repository.tikipeter#663]
Hi there I've been monitoring this for a short while now but it appears trakt lists no longer seem to be populating, I use latest releases by giladg and I'm having to clear trakt cache for new titles to appear, they don't refresh on kodi start up either, is there any setting I may need to adjust now? I haven't messed about with anything

Kind regards

**Comment by Tikipeter** [comment]
I'll look into this. The new code to handle Trakt info looks to need a bit of tweaking in this regard.

**Comment by Tikipeter** [comment]
Fixed for next update.

**Comment by JFG1000** [comment]
Thankyou so much

**Comment by JFG1000** [comment]
@Tikipeter this issue appears to still be persistent.
