### ISSUE TITLE
Pulling only hosters, not torrents, must be me.

### ISSUE THREAD

**Issue by Mike-FL** [Tikipeter/repository.tikipeter#664]
I hesitate to post this and take up your time, but I am unable to get any answers elsewhere and I'm frustrated having literally spent hours on this. 
Multiple installations with either 4k sticks or cube and Real Debrid. I have gone through all the settings repeatedly; the definition of insanity now over and over and get numerous links, but only hosters, no torrents. Have uninstalled and reinstalled the addon with the same results. I appear to match the same fenomscrapers settings as those on Venom and pull plenty of torrents on Venom.
Assuming this is "me", can you point me in the right direction to correct this? 
Many thanks for your time.

**Comment by Tikipeter** [comment]
I'll need a log of an unsuccessful scrape I'm afraid. Otherwise I couldn't even begin to diagnose.

**Comment by Mike-FL** [comment]
Needless to say, thanks for the quick response. The unsuccessful scrape does not show up in the Kodi log viewer. Seemingly it does not 'think' it's an error producing all those hoster links. I'm baffled, but I'll just have to struggle on further and sort it out somehow. Thanks again.

**Comment by Tikipeter** [comment]
The Kodi log viewer is useless.
Post me the log here and I'll be able to help you.

**Comment by Tikipeter** [comment]
If you're not willing to post a log:

* Does the hoster results play?
* Have you turned OFF the hoster scrapers in FS, and tried a scrape ONLY with torrent scrapers? Did it still not work?
* Are you sure your My Accounts settings are properly synced in Fen (they should be)? If not, perform a sync.
* What's your Kodi version, Fen version, FenomScrapers version and My Accounts version?

**Comment by Mike-FL** [comment]
Hoster results play
I turned off all hoster scrapers in FS, did a sync with my accounts, confirmed, so presumably, it was then scraping only torrents scraped select source and oddly the results were again all hosters. I'm at a loss.

Kodi 19.3
Fen 2.5.15
Fenomscrapers 2.0.9
My Accounts 2.0.0

**Comment by Tikipeter** [comment]
Clear the results cache then retry.
`Tools->Clear Database & Clean Settings Files->Clear External Scrapers Cache`

**Comment by Mike-FL** [comment]
I have previously done that. Did it again with the same results I'm afraid. Here's a log prior to clearing the external scrapers cache:
[(https://paste.kodi.tv/idoqanikux)](url)

**Comment by Tikipeter** [comment]
I need the Kodi log, not the FS log.

**Comment by Mike-FL** [comment]
I'm afraid I don't know how to grab that to a paste, and the menu indicating view errors: none found.
Sorry. I'll just try uninstalling Fen again and see if I can deal with it. Thanks for your time. I really appreciate it. 
Odd thing. As there is some at least limited relationship with Venom which has been stellar for me all along I figured I could handle any issue with Fen. I guess not. Again, thank you.
