### ISSUE TITLE
Show Percentage Watched on items

### ISSUE THREAD

**Issue by unkn0wn234** [Tikipeter/repository.tikipeter#665]
Hey Tiki hope you're doing well. This is more just a request based on a visual thing rather than practicality but hope you will entertain the thought anyway.
I was just wondering if you could make it so Fen could show the %watched of in progress items from Trakt inside the addon when viewing them. I do know it is possible as it was in Seren though they took it out for a bit. I'm not sure if that code can be transferred over and I do doubt it is, I don't mean to disrespect by bringing up another addon I truly love Fen and would just really like this feature; though I understand if you wouldn't want to as it doesn't really do much.
[kodi.old.log](https://github.com/Tikipeter/repository.tikipeter/files/7774825/kodi.old.log)

**Comment by Tikipeter** [comment]
Likely not as I don't like adding any extra checks when making listiems, and I couldn't do this for people not using Trakt.
