### ISSUE TITLE
Error marking shows as watched/unwatched

### ISSUE THREAD

**Issue by ivarbrandt** [Tikipeter/repository.tikipeter#667]
Fen throws an error when marking a whole show as watched or unwatched. It will mark it after if I leave that page and then go back in but it throws an error when initially trying to mark it. Here is my log.

Thank you and happy holidays!

[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/7776323/kodi.log)

**Comment by Tikipeter** [comment]
Fixed for next update.
