### ISSUE TITLE
Filter Results by Name Issue

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/repository.tikipeter#668]
Reported by @ReaLx3m

>Also noticed there is some regression in seach results with easynews. ' symbol is a problem again.
Namely no results displayed for "Don't Look Up" if "Filter Results by name" is checked.
Not sure when it started being a problem again, but i had 2.0.44 laying around, and going back to it works ok and displays results for the movie in question and also other affected items, like Schitt's Creek or It's Always Sunny in Philadelphia

>I found some online archive with older fen versions and tried all from 2.5.16 and down. Newest correctly working version is 2.5.07, after that one all have problem with ' symbol

**Comment by Tikipeter** [comment]
I've done a quick fix for this for next update (just removing the `'` from the title).
With things like this, though, there could be unintended consequences that I'm not up to looking into just at the moment. Hopefully it will be OK.

**Comment by ReaLx3m** [comment]
Dont think it will be a problem, at least personally havent noticed any apparent issue with ' removed, it did work that way for pretty long time. Havent had updated FEN for some time, but did notice almost straight away when i updated to the latest version that has it removed.
Good to hear well have it back as it was, will definitely let you know if i run into any related issue, though like i said havent noticed any so far. 
Thanks again.
