### ISSUE TITLE
Bug: Show Trailer video missing. 

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#67]
Option enabled in the settings , but missing since last update (press and hold the OK button on let's say a movie), did give the option to play a trailer, but missing in the extra menu that pops up after pressing and holding the OK button.

Can you verify this? (no idea how to log this one unfortunately).

**Comment by Tikipeter** [comment]
Hi Tinuz97.
What does the context menu item say for the trailer. Does it say 'Trailer' or 'Choose Trailer'?

If it says 'Trailer', go into Settings->General->Appearance and activate 'Show Choice for all Trailer Videos'. That should fix it, as it's working for me..

**Comment by Tinuz97** [comment]
This is weird, yesterday I tryed several times, did not see the trailer option (enabled in settings), and now it is magically there 😅

**Comment by Tikipeter** [comment]
Hi Tinuz97.
Ha! I was just finished writing out a reply! Glad it's sorted for you.

**Comment by Tikipeter** [comment]
Whilst I was looking into this before replying, I did notice, when set to a language other than ENG, TMDb provides much less data for Trailers. Many of the Movies I tried on the first page of Trending didn't have trailers when metadata was set to DUTCH, but did have trailers when set to ENGLISH. I'm going to look into this, but I doubt there is anything I can do about it. Obviously TMDb often has less info when querying for a different language. Very unfortunate. :(

**Comment by Tinuz97** [comment]
Ah yes, that is the issue, I forgot that I switched as a test to English, that is why it is indeed working now.

**Comment by Tikipeter** [comment]
Yeah, whilst it's nice for TMDb to try and supply language specific trailers, they should include the default ENG ones as well, so there's always something there to watch, even if not in preferred language. :( :(

**Comment by Tinuz97** [comment]
I noticed something else, the downloader (download option) does not respect the filename if api is set to Dutch.

As a example IT chapter two. 
If the api is set to Dutch, the filename is IT chapter two (2019) or something like that. 

If changed back to English, it does respect the filename (same link), and it does IT.CHAPTER.TWO.2019.1080P.WED-DL.H264.AC3-EVO as a example.

**Comment by Tikipeter** [comment]
Makes sense, I suppose. Hopefully I can fix this for next update (not the one I'm about to push, the next one).

**Comment by Tinuz97** [comment]
Ah ,found the lost message ,lol.
Working 100% in the latest update (api on Dutch), Thx!
