### ISSUE TITLE
Reg. "Scrape With Custom Values" option while using Autoplay

### ISSUE THREAD

**Issue by ShibajiCh** [Tikipeter/repository.tikipeter#671]
Hi @Tikipeter,

Greetings and wish you an advance Happy New Year 2022!

Recently I noticed that for some TV shows like "Marvel's Ultimate Spider-man" the name is correct in TMDB but in the torrent name it's mentioned as only "Ultimate Spider-man" which results in zero results while scraping with Fen.
The "Scrape With Custom Values" option was helpful in this case as I could remove the "Marvel's" part from the name and get the results.
However, there's a small problem that this option only becomes available if I don't use Autoplay. So it's my kind request if you could add this option while using Autoplay as well?

If this is not possible then could you please suggest any alternative solution for scraping such problematic torrent files?

Here's my Kodi log:

https://paste.kodi.tv/epeqohadis.kodi

Thanks,
ShibajiCh.

**Comment by ReaLx3m** [comment]
Option works in 2.5.07, maybe some newer ones but havent tried.
Since older versions arent available on the git, i could upload them somewhere for you if you cant find them online 

Otherwise, unless it was removed due to some technical reason, i know id also like to see that feature back since i also prefer autoplay on.

**Comment by ShibajiCh** [comment]
> Option works in 2.5.07, maybe some newer ones but havent tried. Since older versions arent available on the git, i could upload them somewhere for you if you cant find them online
> 
> Otherwise, unless it was removed due to some technical reason, i know id also like to see that feature back since i also prefer autoplay on.

Thanks @ReaLx3m!

However, I think I found an alternative solution. We can turn off autoplay by going into Fen options from context menu and it immediately displays the "Scrape with custom values" option, which we can then use. I think @Tikipeter implemented it in this way after a lot of R&D as even if we keep autoplay on with custom values it won't play the next episode automatically since we need to enter the custom values for the next episode manually as well.

@Tikipeter, please correct me if I'm wrong and kindly advise regarding the same.

Thanks,
ShibajiCh.

**Comment by Tikipeter** [comment]
Lucky for you, you are wrong. :) :)

I really can't remember why I put a visibility condition on showing this in the Options Menu. I should be able to make this, and "Scrape With All External Scrapers" honor the autoplay settings you have no toruble.

So if you choose "Scrape With Custom Values" or "Scrape With All External Scrapers" then the Movie/Episode will autoplay at the end of the scrape. "Rescrape And Select Source" will of course still temporarily disable the autoplay setting, as that is it's purpose.

**Comment by ShibajiCh** [comment]
> Lucky for you, you are wrong. :) :)
> 
> I really can't remember why I put a visibility condition on showing this in the Options Menu. I should be able to make this, and "Scrape With All External Scrapers" honor the autoplay settings you have no trouble.
> 
> So if you choose "Scrape With Custom Values" or "Scrape With All External Scrapers" then the Movie/Episode will autoplay at the end of the scrape if that is your current setting. "Rescrape And Select Source" will of course still temporarily disable the autoplay setting, as that is it's purpose.
> 
> You are right about the autoplay next episode likely not working in this scenario though. I'll have to look into that more, but I should be able to use the custom value entered on the previous episode.

Hi @Tikipeter,

Thank you! That'll be great. I shall wait for your further update on this.

Thanks,
ShibajiCh.
