### ISSUE TITLE
Reg. "In Progress" Movies and TV Shows Issues

### ISSUE THREAD

**Issue by ShibajiCh** [Tikipeter/repository.tikipeter#672]
Hi @Tikipeter,

Greetings!

I noticed the below 2 issues:

1) The Movies and TV Shows under "In Progress" menu are in reverse order, i.e. the most recently watched Movie/TV Show appears at the end and the oldest one appears at the beginning. Could you please fix this to arrange them in the correct order?

2) Also, if I use "Clear Progress" under the "In Progress" menu then even though the video gets cleared from Trakt but it then starts replaying the video again. I used the "Trakt Playback Progress Manager" (https://sharkykh.github.io/tppm/) to track this. Please see screenshot below:

![image](https://user-images.githubusercontent.com/65297828/147812860-74262b45-50e4-4441-a160-c63f2f1581b7.png)

I cleared progress for the video called "Femme Fatales...". However, it started replaying again after it got cleared from Trakt playback history. This happens for all Movies and TV Shows. Could you please look into this issue?

Here's my Kodi log:

https://paste.kodi.tv/nevofawoqi.kodi

Thanks,
ShibajiCh.

**Comment by Tikipeter** [comment]
1. Unfortunately, things will have to stay this way. For Movies and Episode, I didn't set up the database with titles or time watched so I can't do anything about it with the current database I'm using. TV Shows Progress are sorted alphabetically at the moment, and will also need to stay that way as well.
2. I don't understand what you've written here. What do you mean by "started replaying again"? Do you mean it resumed in Fen after you had cleared the resume point on the Trakt website?

**Comment by ShibajiCh** [comment]
> 1. Unfortunately, things will have to stay this way. For Movies and Episode, I didn't set up the database with titles or time watched so I can't do anything about it with the current database I'm using. TV Shows Progress are sorted alphabetically at the moment, and will also need to stay that way as well.
> 2. I don't understand what you've written here. What do you mean by "started replaying again"? Do you mean it resumed in Fen after you had cleared the resume point on the Trakt website?

Hi @Tikipeter,

1) That's fine. I can live with it. It's not such a big issue. Thank you for letting me know!

2) By "started replaying again" I meant that once I cleared progress in Fen the progress for the Movie/TV Show Episode got cleared on the Trakt website which I checked on the "Trakt Playback Progress Manager" tool. Upto this stage it worked fine. However, after the progress got cleared then it started scrobbling again on the Trakt website as you can see from the above screenshot I provided. If I let it continue scrobbling entirely then the Movie/TV Show Episode will get marked as watched in Trakt even though I only cleared its progress and didn't complete watching it. Hope I could explain the issue. Please advise.

Thanks,
ShibajiCh.

**Comment by Tikipeter** [comment]
Is there anything that's triggering it to start scrobbling again?

**Comment by ShibajiCh** [comment]
> Is there anything that's triggering it to start scrobbling again?

Hi @Tikipeter,

I'm not very sure about what's triggering it, but like I said this only happens if I click on the "Clear Progress" option in the context menu of the Movie/TV Show Episode located under "In Progress" menu in Fen. You can check for yourself by doing the same and try to replicate the issue at your end. Maybe that way you can find out what might be the cause of this issue.

Thanks,
ShibajiCh.
