### ISSUE TITLE
A Big Thank You and a small contribution regarding Dolby Vision videos

### ISSUE THREAD

**Issue by ShibajiCh** [Tikipeter/repository.tikipeter#673]
Hi @Tikipeter,

First of all a Big Thank You for making the already great Kodi addon Fen even greater by adding Trakt Progress syncing to it!
It was really very helpful for people like us who use Trakt everyday.

Secondly, I wanted to contribute a small code which I wrote by modifying some other versions I found on the web.
I know it's nothing much but I just wanted to show my gratitude.
Since Kodi doesn't support Dolby Vision Video Playback properly so I wrote this code which contains almost all possibilities of Dolby Vision in a torrent filename and plays such videos in an external player: "Just Video Player", which needs to be installed separately from the Google Play Store.

Here's my code:

https://paste.kodi.tv/livenoquyu

The above script needs to be added as "playercorefactory.xml" filename in the below location:

/Android/data/org.xbmc.kodi/files/.kodi/userdata/

This code along with Fen has made Kodi the perfect media player for me since I've a TV supporting Dolby Vision HDR.
Please correct me if I wrote anything incorrect in the code.
Also, please suggest if there's any better solution to play Dolby Vision video files from within Fen other than using an external player.

Thanks again for the great work that you're doing!

Here's my Kodi log:

https://paste.kodi.tv/nevofawoqi.kodi

Thanks,
ShibajiCh.

**Comment by Tikipeter** [comment]
Looks good. Good job on it. I've never created a `playercorefactory.xml` as I've never had a need to. I assume as long as your `rule filename` has an exhaustive enough set of rules it should be good, which it looks like yours has.

As to a better way to play DV HDR, I'm afraid that's entirely between your device and Kodi. If you can't play it natively in Kodi, then I don't think you have another choice than to use an external player. Usually if it's possible it will be implemented within Kodi, but I think they are severely short on Android developers. So it might just never happen.

I'll direct anybody who asks about this sort of thing to this post in the future.

**Comment by ShibajiCh** [comment]
Hi @Tikipeter,

Thank you so much for your kind words! :)

Regards,
ShibajiCh.
