### ISSUE TITLE
Viewed Indicators

### ISSUE THREAD

**Issue by djdirty60** [Tikipeter/repository.tikipeter#674]
Good day,

The Viewed Indicators function in the general section does not work, I have authorized trakt but I do not see the function that normally becomes visible.  Is there an error in that?

 I like to hear it

**Comment by Tikipeter** [comment]
![screenshot00000](https://user-images.githubusercontent.com/28930002/147890488-99558241-01e3-4c83-bf0e-3def48887c2d.png)

Working fine here. Make sure your Trakt username is visible in the Meta Accounts section. Resync with My Accounts if it isn't.
Is trakt working apart from that? Do you get the correct watched indicators in Fen anyway?

A screen shot might help me see what's going on.

**Comment by Tikipeter** [comment]
Also, make sure the Trakt Username in My Accounts is the same name as in Fen.

If all of that is correct, then I would Revoke Trakt Auth in My Accounts, then click OK to save the setting, then make sure Fen has resynced the now revoked setting, then go back in and re-auth Trakt in My Accounts, then click OK and then make sure Fen has resynced again.

**Comment by djdirty60** [comment]
![1641160903445359291086132035283](https://user-images.githubusercontent.com/13561831/147890558-d70341fe-72c7-4862-b169-32de6241bf9f.jpg)

![16411609488238550496298381572764](https://user-images.githubusercontent.com/13561831/147890564-7fb981af-210c-4836-be89-5aa60d8da548.jpg)

**Comment by Tikipeter** [comment]
>Also, make sure the Trakt Username in My Accounts is the same name as in Fen.
If all of that is correct, then I would Revoke Trakt Auth in My Accounts, then click OK to save the setting, then make sure Fen has resynced the now revoked setting, then go back in and re-auth Trakt in My Accounts, then click OK and then make sure Fen has resynced again.

**Comment by djdirty60** [comment]
> > Also, make sure the Trakt Username in My Accounts is the same name as in Fen.
> > If all of that is correct, then I would Revoke Trakt Auth in My Accounts, then click OK to save the setting, then make sure Fen has resynced the now revoked setting, then go back in and re-auth Trakt in My Accounts, then click OK and then make sure Fen has resynced again.

Its working, thnx

**Comment by Tikipeter** [comment]
That was quick.
