### ISSUE TITLE
Trakt lists no longer populating

### ISSUE THREAD

**Issue by JFG1000** [Tikipeter/repository.tikipeter#675]
Hey there I thought address this again, as it seems the prior fix didn't fix it, trakt lists are no longer populating until a trakt cache clear is performed or a clear all cache, upon my testing I cleared all cache and over 10 new items appeared, used latest releases gilag as the example, many thanks

**Comment by Tikipeter** [comment]
I'm going to go out on a limb here and say this is not a "liked" list. Is that correct? Because it looks like I fixed the list caching for "liked" lists, but not just lists that are from another user but not liked.

**Comment by Tikipeter** [comment]
Fixed for next update. They will be cleared on each Kodi start.

**Comment by JFG1000** [comment]
Yes mate it's a liked list from trakt, this one

https://trakt.tv/users/giladg/lists/latest-releases?sort=added,asc

Many thanks.

**Comment by Tikipeter** [comment]
Damn. If it's a liked list of yours it should already be getting cleared on EVERY trakt data refresh. Are you accessing it from the TRAKT: Liked Lists menu in Fen?

**Comment by JFG1000** [comment]
Usually from homescreen widgets, but I did a few tests a the other week and it wasn't populating via the fen menus either, this has only been a recent issue it hasn't been happening for long

**Comment by Tikipeter** [comment]
Lists accessed through the Liked lists menu should be getting cleared each trakt data refresh.
Lists accessed through either "Trending User Lists" or "Popular User Lists" will have not been getting cleared each refresh. If the list was added to a widget or accessed through Fen by these 2 menus, then they will have been missing out on the data refresh.. It's an oversight from when I changed to using a Trakt refresh data method a few updates ago.

Best to wait until next update (very soon) and see if the changes I've made have fixed this issue or not.

**Comment by JFG1000** [comment]
I understand, I updated to the most recent update, new items populated on the trakt list within the addon, but not on the homescreen widgets, even after a skin reload, I had to clear all cache for them to appear, so could this be a skin issue? It's such a shame been using the skin with no issues up til now

**Comment by Tikipeter** [comment]
Doubtful it's a skin issue.

* Tell me what skin and I'll test it.
* Tell me the Fen menu the offending widget is pointing to.
* Is it the same Fen menu that refreshed successfully?

**Comment by Tikipeter** [comment]
As a side note, I would remake that widget item now that Fen has been updated and see if that makes a difference. There might be a new param added to the list since last update.

**Comment by JFG1000** [comment]
The skin is Auramod for matrix

https://github.com/SerpentDrago/skin.auramod/tree/Matrix

I created a widget that points to my lists, liked lists, then this list

https://trakt.tv/users/giladg/lists/latest-releases?sort=added,asc

I didn't think about re creating the widget so I could try that tomorrow evening after work.

Many thanks

**Comment by JFG1000** [comment]
Just to update, I've re created the widget so will continue to test, a friend of mine who uses Venom and Tmdb has said his widgets are refreshing to populate to items as normal though so I'm not sure what's going on, the issue still seems persistent though it's definitely an odd one.

**Comment by JFG1000** [comment]
Just to let you know, the recreating of the widget appears to have fixed this issue. Many thanks for all your hard work. Fingers crossed in the future we hopefully see a return of the addon

**Comment by Tikipeter** [comment]
Really good news. Thanks for reporting back @JFG1000
