### ISSUE TITLE
Issues with auto play

### ISSUE THREAD

**Issue by jaycassini** [Tikipeter/repository.tikipeter#68]
Been trying to use the autoplay function yet all it is doing is going through the different links but not actually playing. But when choose what link to play it works fine using real debrid and all debrid not sure what the issue is will post the error log if I can get one

**Comment by Tikipeter** [comment]
This does look like an issue. Let me look into it jaycassini.

I have a couple of other things I need to look at first, so best to not use autoplay for now.

**Comment by jaycassini** [comment]
Will do just wanted to give a heads up loved your work and appreciate
everything you have done

**Comment by Tikipeter** [comment]
This should be fixed for next update (v.1.5.76). Let me know of any troubles after that.
