### ISSUE TITLE
Closing of Repository...

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/repository.tikipeter#680]
Hi all. Over the next day or so this repository will be cleared of its zip files.

Anyone wanting to keep access to Fen should download the fen and tikiart zip files now, while they're still available.

As long as the Venom repo is alive, you can get FenomScrapers and My Accounts from there.

This github needs to stay in my ownership so it isn't hijacked, so it will not be deleted.

**Comment by tomtomclub** [comment]
Please let stay for 7 day so everyone can download the zip file 
And thanks for the addon I enjoy it every day

**Comment by JFG1000** [comment]
Will Fen continue to work if Fenomscrapers is maintained?

**Comment by Tikipeter** [comment]
Yes.

**Comment by FloridaJC** [comment]
Sorry to hear this is happening.  Could you please tell me exactly where I go to save the zips you mentioned? I am long time user. Does this mean FEN is going away, no more updates?  Thanks for all your work!!

**Comment by Tikipeter** [comment]
In the zip folder of this repository that you are in now.

**Comment by Tikipeter** [comment]
Yes, no more updates. Fen is done. For now at least.

**Comment by FloridaJC** [comment]
I don't know what to say. Best add-on, and a very strategic and unique approach to providing its feature set. Hope you come back... and if not in the cards, thanks again for your work.

**Comment by ReaLx3m** [comment]
Very sad to hear this, as since i discovered FEN i never looked back. Easy the best kodi addon in my opinion.
You have brought to joy to many people with your work, whether they expressed it here or havent because they never learned about github and the existence of this git.
So thank you in case im overdue saying it once again :) , and good luck with whatever you decide to do in the future whether its fen related or not.

Wish you all the best.

**Comment by Hotkodimax** [comment]
This just stopped working for me today when I added the source to my kodi program it showed "couldn't connect to network server". I'm so disappointed. This is by far the BEST and only program I have used for a very long time. I'm desperately trying to understand the zip files... I need a https link to add the source to my Kodi program. I honestly don't know the added sources link anymore. This sucks. WE LOVE FEN!

**Comment by chrisnikol** [comment]
I am verry sorry to hear this. FEN it was my main addon for the last 2 years.
Thank you for all your hard work and this amazing addon.

I really hope to change your mind but if you dont, i wish you all the best.

**Comment by toothmaniac** [comment]
dude this is one of the best of best, really sad to hear , but it is your life your decision , you can improve it and make it available only for paid users just suggestion , thanks

**Comment by Tinuz97** [comment]
My favorite addon 🤕
Thx for all the effort you put into the project, and give me the ability to translate to Dutch language.

Best wishes also, and hopefully see you in the future.

**Comment by Hmeeberg** [comment]
Very sad to hear this. It was my favorit addon.
Hope you come back soon. 
Thanks forval your work and help.

Dat is balen  was mijn favoriete addon
Hopelijk kom je snel weer terug. 

Bedankt voor al werk en hulp.

**Comment by tomtomclub** [comment]
> Yes, no more updates. Fen is done. For now at least.

Just take it more easy 1 every 4 week update is oke not necessary  delays  I see lat of de developer's  gowing mad  . Just take your time .
Is hard and complex work

**Comment by tundrablasen** [comment]
I would also hope for continuing of maintaining of FEN.

i think the current state is perfect. I don’t see any major bugs or missing features. 

Maybe you keep the addon and repository just as it is and just become active when something breaks. 

however you decide: thanks for the great work. And good luck for future endeavours

**Comment by Tikipeter** [comment]
I am not closing the repository because I am burnt out. So it's really not a matter of having a rest to recharge etc.

**Comment by toothmaniac** [comment]
can you just open it to premium, for those only who are ready to pay like
me?

**Comment by Tikipeter** [comment]
It's definitely 100 percent not about money.

**Comment by Logs22** [comment]
Thanks for all the work you did boss! You will be missed :)

**Comment by AnotherUniqueName** [comment]
Thank you. I've enjoyed and followed your work. Third party Kodi will miss your commitment and innovation. I hope you reconsider, if not I wish you good luck with whatever you choose do with all that spare time. Thanks again.

**Comment by Aguzy** [comment]
Thanks for everything you've done @Tikipeter. If this is the end it's been a great ride and hopefully the add-on will continue to work for a good while yet. I totally understand that sometimes the spark just goes and something isn't enjoyable anymore and feels like a chore, when that happens you have to take a step back and decide what is best for you. All the best in whatever you choose to do in the future my friend and thanks again for the best Kodi addon over the last few years

**Comment by Sea-Wolfe** [comment]
FEN is fantastic!  

Thank you for all the work you have put into this, for as long as you have.  Best to you!

**Comment by FlaParrotHead** [comment]
Good luck to you Sir.  FEN truly is one of the best add_ons and I do hope it'll continue to run without maintenance.  Regardless .. Thank You!
