### ISSUE TITLE
Sigh..... Fen Lives on to Fight Another Day.

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/repository.tikipeter#681]
Well, pulling the trigger is never easy.

I'll need to hold off for now.

Fen lives on to fight another day.

But you great users who come here on to github, make sure you've got a backup addon you are comfortable with. My reasons for wanting/needing to close the repo have not changed, but things are usually more complicated than simply shutting up shop and riding into the sunset.

This is my 2nd attempt in 3 years to shut this thing down. Knowing the way us dev's brains work, it likely won't be the last. I suppose it's like a parent trying to give away their child. It's not easy.

Possibly next time I'll stick the landing, but for now let's continue. I'll do some new code and break shit, you come on and let me know what I've broken. And sometimes I'll come on here in a bad mood and make a cranky ass of myself just for your amusement.

**Comment by pigskins65** [comment]
Don't ever change!

**Comment by Sea-Wolfe** [comment]
Not that I have a say, one way or the other.  But for my own selfish reasons, I love this news! :)

**Comment by Tikipeter** [comment]
@Sea-Wolfe 

Glad you're happy. :)
But... please remove the link to this github in your a4K post you just made. It's not good for me to have a link to here from reddit. If an a4k mod sees it they'll delete your whole post, so best to just remove the github link.
Thanks. :)

**Comment by Sea-Wolfe** [comment]
> @Sea-Wolfe 
> 
> 
> 
> Glad you're happy. :)
> 
> But... please remove the link to this github in your a4K post you just made. It's not good for me to have a link to here from reddit. If an a4k mod sees it they'll delete your whole post, so best to just remove the github link.
> 
> Thanks. :)

Sorry about that.  It looks like the post was already removed (by a mod).

**Comment by Tikipeter** [comment]
They were too quick for you! No worries.

**Comment by Liquidrag** [comment]
@Tikipeter glad to hear fen is here for a bit longer. I see how often you update and it’s because you like to tinker and add things. As of right now, I think fen is pretty damn perfect. It’s fast as hell, has trakt scrobbling that you recently added and I can’t see much else you can do. Thank you again for the addon and I’ll save the updates in case you do finally pull the plug.

**Comment by AT5Pin** [comment]
LOL, yeaaa it ain't easy walking away from something we love. Glad to read your positive comment for sure. I'll ride on this bus until the wheels fall off. Thanks again for doing your do for us!

**Comment by MrC001** [comment]
That was a good read ... It's tough to give up on something you are passionate about.  I personally had a heart attack and two minor strokes when you said you were tossing in the towel.  Just got back from the hospital.  By far, without doubt, the best app out there.  If it takes some beer money to keep you happy, I am in......I always have mine set to not auto update and come look to see if you broke something before I update lol.....  We love you man......

**Comment by cgcgcgcgcg** [comment]
A lot of peeps I know appreciate the fact Fen is again available.
Thank you @Tikipeter.

**Comment by ShibajiCh** [comment]
Hi @Tikipeter,

Wow! That's a great relief! Thank you for the good news! We Kodi users just can't live without such an awesome addon like Fen. Thanks again for changing your decision for now! Please keep up the great work that you're doing. We Fen users are always there to support you. 🙂 

Regards,
ShibajiCh.

**Comment by rishisss23** [comment]
Hi Tikipeter;
Glad to hear this wonderful news.. 

If I am not overstepping;please share your reason for quitting the addon;since once shared it lessens your burden;and if it is a fault of users like me;we can rectify it. 
Anyway Thanks for your review in decision.. Always the best addon and dev in my mind..

**Comment by tomtomclub** [comment]
Thanks for the good news🥂. But remember take it slowly you don't neet to run ever day if something 
is  broking ,

**Comment by odroider** [comment]
Excellent news indeed which many FEN users will be very happy about. FEN is surely the greatest addon of its type ever developed and deserves to live on.

We know you develop FEN in your spare time and is a passion and a hobby. As such, first and foremost it should be FUN. If it ever becomes a chore or an obligation, or you feel pressured, it is time to stop.  I hope you take it easy now and push updates at your own pace and convenience whether a day, week or month. Providing FEN stays alive and you enjoy developing FEN you are making numerous people happy, and that means a lot.

Thanks again for such an exceptional addon that you most freely and generously share.

**Comment by Meese77** [comment]
Thank you for all your hard work and dedication. I'm glad you're staying in the game man!

**Comment by derrgoo** [comment]
Glad to hear!

**Comment by mrgsi** [comment]
I have a semi-private build and play around with forking add-ons. I tend to spend more time doing that, then working on my business which is really, really bad, but it's so damn addictive. It's hard to walk away from it. Being a "creative type" I think it satisfies a need that creates a void when you aren't doing it. It's cleaner than painting and requires less tools than making birdhouses. lol

**Comment by textroynado** [comment]
FEN is the only add-on I use anymore. Simply the best. So I hate to hear any talk of it going away. That said, I understand the headache as well. Just know there are plenty of us out here that really appreciate all you do.

**Comment by FlaParrotHead** [comment]
Bring on your cranky ass mood and if we can, we'll try to make your smile.  If you are a diver ... message me and you'll have a personal tropical invite.

**Comment by ReaLx3m** [comment]
Great to hear man, hopefully FEN will live long and prosper :)
