### ISSUE TITLE
Playback issue

### ISSUE THREAD

**Issue by curtyman11** [Tikipeter/repository.tikipeter#683]
I am having trouble playing a video since the newest Fenomscrapers update. The addon brings up a list of sources but when I try to play one it will simply attempt to play every source in the list and then return me to the menu. I have tried reauthorizing my real-debrid but it didn’t work.

**Comment by Tikipeter** [comment]
It won't be an issue with Fenomscrapers as that has nothing to do with playback.
Post a log showing Fen failing playback and it will likely tell me what is going on.

**Comment by curtyman11** [comment]
How do I post a log?

**Comment by Tikipeter** [comment]
https://kodi.wiki/view/Log_file/Easy

**Comment by curtyman11** [comment]
https://paste.kodi.tv/cobabahuba

hopefully I did it right.

**Comment by Tikipeter** [comment]
I would turn off Orion and try again.

**Comment by curtyman11** [comment]
I removed Orion from fen and then cleared addon cache and kodi cache but the issue persists. Would you recommend a fresh install at this point?

**Comment by curtyman11** [comment]
I did a fresh install without Orion and it seems to be working now. Thanks for your advice.

**Comment by Tikipeter** [comment]
That's good news. I would give that exact log to the Orion devs to let them know there's an issue. They have other issues in that log as well.

Some advice to think about..... Orion inserts code into addons when it auto "integrates" with them. Whilst it's certainly not terrible to do this, it does change the function of Fen/Venom/Seren. Whatever you integrate it with. It makes it more difficult for you to know what's happening when something goes wrong. And I (and I know other devs) haven't bothered to look at what exactly is being changed to integrate itself (I have an idea though).

Basically what I'm leading up to is make sure you really need Orion, as it changes code in the addons you have installed, making it harder to troubleshoot when things go wrong. It's likely the reason you had to do a fresh install, to get rid of the inserted code, before Fen would work again.

Orion's method of inserting code will normally be OK, but with an addon like Fen, where I am often changing things (and made many changes to the sources code in last couple of updates), Orion will often break and leave the addon useless as it does.

I don't want this to sound like I'm trying to dissuade you from using it, but it is something to think about. I'm sure when you give them that log they will sort out the issue.
