### ISSUE TITLE
Trakt Progress Error

### ISSUE THREAD

**Issue by muzikherif** [Tikipeter/repository.tikipeter#684]
Firstly i am happy to hear that you still keep continuing, thanks for all your effort.
And secondly issue is actually not a big deal, it exist for long time.Kodi crashes when browsing local subtitles...There is an alternative addon for it but i m just want to say if you can easily fix that issue it would be good, because sometimes i m opening by mistaken and crashes annoying.And also here is my log if you need it
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/7842147/kodi.log)

**Comment by textroynado** [comment]
Just jumping in here. I use subtitles a lot. And I've experienced what you're describing with the subtitles. That said, I don't believe that is an issue with the FEN add-on as it does it with any add-on. It's a KODI function. You just have to be careful to choose Download subtitle rather than "browse" for subtitle. It's been happening that way for as long as I can remember. It seems to be worse if you have a large library.
Hope this helps.

**Comment by muzikherif** [comment]
sorry i do not know it was a kodi issue, not a problem, thanks for the explanation

**Comment by Tikipeter** [comment]
Yep, texttroynado is correct muzikherif. I recall someone bringing this to my attention a long, long time ago. The alternative addon was the only solution that I could find.

**Comment by muzikherif** [comment]
Ok thanks, but bad news i have encountered a new problem, which is completely different with mentioned issue.

When i continue an episode from in progress episodes, at the end of it, giving an error at the top right corner "Trakt error, 409 client error, conflict for url : https://api.tr" then marks as watched at the trakt but it still keeps episode in the 'in progress episodes' folder.I tried to manually clear progress but giving same error again.I thought it might be temporary trakt error but i have experienced the same thing a few times at last days

**Comment by muzikherif** [comment]
Here is my log
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/7842715/kodi.log)

**Comment by Tikipeter** [comment]
I changed the call to trakt from `scrobble/pause` to `scrobble/stop` to fix another issue with trakt progress, and this has now raised it's head. I think I'll have to go back to `scrobble/pause` to solve this.

**Comment by muzikherif** [comment]
hi, i m really appreciate for all your interest, i do not want bother you and steal your time but after last update real debrid results with all movies-series showing uncached

**Comment by xyzfre** [comment]
> hi, i m really appreciate for all your interest, i do not want bother you and steal your time but after last update real debrid results with all movies-series showing uncached

Please open a new issue as the rules state do not post a new issue on a different issue ,, please try to follow the rules we want to keep Tikipeter happy ,,we have to be super grateful he decided to stay with us

**Comment by muzikherif** [comment]
sorry i did not know rule you said, after now i will be careful

**Comment by muzikherif** [comment]
> hi, i m really appreciate for all your interest, i do not want bother you and steal your time but after last update real debrid results with all movies-series showing uncached

now i made a clear installation and it fixed this issue
