### ISSUE TITLE
[Bug] Wrong clearlogo

### ISSUE THREAD

**Issue by Bequiet19** [Tikipeter/repository.tikipeter#686]
In the meantime, I discovered another bug. The movie Black box (2021) shows the Russian logo instead of the English one. It is probably not set in Fen to download the first image in the language that kodi uses but takes the first one available. For this movie there is only Russian clerlogo. This is just my guess, maybe I'm wrong.

**Comment by Tikipeter** [comment]
If fanart.tv doesn't have any art in the preferred language then Fen will choose the atrwork with the most `likes`.

**Comment by Bequiet19** [comment]
In my opinion, this is not good. If it is not in the selected language, it should not show clearlogo, most skins have the ability to display text. It doesn't make much sense if I use English language to throwing out Russian logo.
Or to insert a function like in tmdb helper to display logo from the tmdb site, I think there is an api for clearlogo. They are not quality as a fanart logo but as a fallback it is ok.

**Comment by Tikipeter** [comment]
Noted.
