### ISSUE TITLE
"One or more items failed to play."

### ISSUE THREAD

**Issue by cgcgcgcgcg** [Tikipeter/repository.tikipeter#69]
This is what I sometimes get as a pop up after watching an episode of a series.
Nothing is written in the log.

Is there anything I can do?

Thanks for Fen, a superb addon that set the bar really high for all the rest.
![fen](https://user-images.githubusercontent.com/38960370/69992255-f67ad200-1551-11ea-9d97-c93f41008f10.jpg)

**Comment by Tikipeter** [comment]
Hi cgcgcgcgcg.

Let me assume you are playing from a library item.

I've grapled with this for a long time. At the moment, this is the best I can do with regard to this dialog showing up (after playback ends). The much worse situation I had to try and fix for a long time was it turning up after playback started, and as soon as you hit OK, it would end playback and return you to your previous menu.

I know this has something to do with playlists in Kodi, but I need to revisit it to try and find a better fix.
I have a couple of other things to do and then I will have another look at this problem. Just be thankful for now that it no longer shows up a minute into watching your video! ;)

**Comment by cgcgcgcgcg** [comment]
> Hi cgcgcgcgcg.
> 
> Let me assume you are playing from a library item.
> 
> I've grapled with this for a long time. At the moment, this is the best I can do with regard to this dialog showing up (after playback ends). The much worse situation I had to try and fix for a long time was it turning up after playback started, and as soon as you hit OK, it would end playback and return you to your previous menu.
> 
> I know this has something to do with playlists in Kodi, but I need to revisit it to try and find a better fix.
> I have a couple of other things to do and then I will have another look at this problem. Just be thankful for now that it no longer shows up a minute into watching your video! ;)

OK, thanks for the quick reply, and thanks again for this amazing addon.

I'll let this issue open for others to be aware of it until a final fix is ready.

**Comment by cgcgcgcgcg** [comment]
A solution that worked better than Kodi's library for me was to delete the whole Kodi library and it's shortcuts on the Library section in the build I use, and use Fen's TV Shows and Movies folders.
I added "Resync Fen Watched to Trakt Watched" on Fen's TV Shows menu, disabled Trakt addon completely (of course Trakt is still authorized in Fen) and now I have an ultra fast Library, that I can just click on Resync to update in seconds.
Since I have other stuff in that Library section in the build I use, I added Fen shortcuts and it works better than Kodi's library.

**Comment by Tikipeter** [comment]
That's a good plan cgcgcgcgcg, but I don't think "Resync Fen Watched to Trakt Watched" does what you think it does. It resyncs you watched history from Trakt to Fen's internal database of watched entries. It's mainly useful if Trakt goes down, you can still browse Fen by switching Watched Indicators to "Fen" in the settings. Then you will have your watched statuses from Trakt whilst Trakt is down.

I think what you are trying to do is force a resync of Trakt Collection info. If that is so, instead add "Clear Trakt Cache" item to your menu/s of choice. This wil clear Fen's trakt cache and when you navigate into any Trakt list it will grab fresh info from Trakt.

"Clear Trakt Cache" is found in Tools->Clear List and Data Info. You can rename it to something else like "Trakt Resync" if you want when adding it to your menu/s. The name doesn't matter.

**Comment by cgcgcgcgcg** [comment]
> That's a good plan cgcgcgcgcg, but I don't think "Resync Fen Watched to Trakt Watched" does what you think it does. It resyncs you watched history from Trakt to Fen's internal database of watched entries. It's mainly useful if Trakt goes down, you can still browse Fen by switching Watched Indicators to "Fen" in the settings. Then you will have your watched statuses from Trakt whilst Trakt is down.
> 
> I think what you are trying to do is force a resync of Trakt Collection info. If that is so, instead add "Clear Trakt Cache" item to your menu/s of choice. This wil clear Fen's trakt cache and when you navigate into any Trakt list it will grab fresh info from Trakt.
> 
> "Clear Trakt Cache" is found in Tools->Clear List and Data Info. You can rename it to something else like "Trakt Resync" if you want when adding it to your menu/s. The name doesn't matter.

Thanks for the clarification.

**Comment by dm2912** [comment]
I dont know if this is related, but im finding the library in kodi is not marking things at watched after watching them via fen.

like the OP i get the "one or more items failed to play" after watching a show (just after the trakt rating prompt" but im then having to manually mark everything as watched because Kodi isnt picking up that ive watched it.

**Comment by cgcgcgcgcg** [comment]
> I dont know if this is related, but im finding the library in kodi is not marking things at watched after watching them via fen.
> 
> like the OP i get the "one or more items failed to play" after watching a show (just after the trakt rating prompt" but im then having to manually mark everything as watched because Kodi isnt picking up that ive watched it.

I disabled rating myself after my first post in Trakt addon, and authorized Trakt in both Fen and Trakt addon.
This error never came up again for me.

**Comment by Tikipeter** [comment]
Could you check you have the setting "Set Resume/Watched in Kodi Library When Watched in Fen" activated. It is found in Settings->Playback->Indicators.

Does this happen for both movies and episodes?

Also, let me know your settings for the Trakt add-on. Do you have it set to mark as watched when viewing media from an add-on?

**Comment by cgcgcgcgcg** [comment]
> Could you check you have the setting "Set Resume/Watched in Kodi Library When Watched in Fen" activated. It is found in Settings->Playback->Indicators.
> 
> Does this happen for both movies and episodes?
> 
> Also, let me know your settings for the Trakt add-on. Do you have it set to mark as watched when viewing media from an add-on?

1. Yes.
2. Yes.
Lately (this is irrelevant with this issue), Fen's sync timeouts but right-clicking on a Fen's library episode and selecting Options / Clear Trakt Cache fixes it.

Also, using RD or similar (I use Premiumize) sometimes this happens:
While scanning several 1080p or higher sources show up, but on the final table of sources only a few 720p sources exist.
This can be solved by logging in to RD site and going to https://real-debrid.com/devices and deleting all authorizations, then authorize RD again via Kodi.
I checked all my current episodes a while ago and this only happened with one (using Premiumize), clearing all cache from Fen's options fixed that episode.

![ksnip_20191221-094750](https://user-images.githubusercontent.com/38960370/71305079-33aae500-23d7-11ea-849d-f7b9aab1585d.jpg)
![ksnip_20191221-094917](https://user-images.githubusercontent.com/38960370/71305080-34437b80-23d7-11ea-9c90-c2cee8c285cf.jpg)

**Comment by Tikipeter** [comment]
I'm closing this issue which was originally "One or more items failed to play". Please start new "Issues" for any new issues.
