### ISSUE TITLE
Improvement suggestion: Display Uncached Torrents Behaviour

### ISSUE THREAD

**Issue by ReaLx3m** [Tikipeter/repository.tikipeter#690]
With the current way the things are, if you use "Filter Results by Size" and also have "Display Uncached Torrents" Enabled, you can run into situation that the Movie/TV show is available at a bit larger size but because of the uncached torrents it doesnt ignore the filters if you have the option on to show the cached results. Which i would assume would be much more preferable to most instead of getting just uncached torrents in results.

So maybe the "Display Uncached Torrents" could be swapped around and be "Disable Uncached Torrents", so when its checked if one runs into a situation where no results with set size are available, both the larger cached results(if any available) and uncached torrents be displayed when it triggers the "Ignore filters" setting.

**Comment by Tikipeter** [comment]
I'll look in to that behavior in the coming days...
