### ISSUE TITLE
Have you ever thought about adding support for XDCC?

### ISSUE THREAD

**Issue by TheGuyWhoo** [Tikipeter/repository.tikipeter#691]
That would be extremely useful to me personally, it's probably the best and safest way to get your hands on content for free.

**Comment by Tikipeter** [comment]
That's some old school tech!
I'll have a look around, but I doubt I have the skills to add it, so I wouldn't get your hopes up.

**Comment by Tikipeter** [comment]
I can't see how the infrastructure could possibly support streaming, so I'm afraid it's a no for XDCC. It was fun to load up an IRC chat program again though.

**Comment by TheGuyWhoo** [comment]
https://github.com/Backflipz/plugin.video.excubed

Check this out. It claims to be able to do it, though the developer still uses DSplayer, so it only works in Krypton.
