### ISSUE TITLE
INFO: Next update will reset Main Menus....

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/repository.tikipeter#692]
Hi all.
The next update for Fen (v.2.5.22) will unfortunately reset all Fen main menus (Root, Movies & TV Shows) to their default.

This will likely not affect most users, who do not change the default configuration of these menus, but for those that do, unfortunately they will be lost. There is not even the option of backing up the `navigator.db` file, as that cannot be used in the new update.

In even worse news, anyone using the "Shortcut Folders" feature will also lose their shortcut folders for the same reason.

Unfortunately there is no way around this happening after the re-write. I also lost my custom menus and Shortcut Folders.

**Comment by derrgoo** [comment]
Thanks for the update 👍
