### ISSUE TITLE
Error TypeError: sources() got an unexpected keyword argument 'ret_all'

### ISSUE THREAD

**Issue by ramondunker** [Tikipeter/repository.tikipeter#694]
Hi there,

I would like to use Fen as it seems really promising and it comes preinstalled with Reloaded build. I tried to upload my full log file but it doesn't contain the actual error. The addon doesn't work for me and it gives the following error:

![IMG_2772](https://user-images.githubusercontent.com/6952890/154864020-06160523-577d-463f-96c8-72de806e28ec.jpg)

I'm running Kodi 19.3 on an Apple TV 4K on tvOS 14, Fen version 2.5.21.

Am I doing something wrong? I've already tried resetting Real-Debrid connection and clearing caches, but that didn't work.
Thanks in advance :)

**Comment by xyzfre** [comment]
You should try deleting and doing a fresh install the dev from Fen usually doesn't deal with issues when the add-on comes preinstalled on a build I would think it's best for you to do a fresh install and tweak the settings to your liking

**Comment by ramondunker** [comment]
Hi @xyzfre ,

Thanks for your reply. I did a fresh install, but it didn't work unfortunately. I got the same error message.

**Comment by Tikipeter** [comment]
You need to update FenomScrapers to the latest version.

**Comment by ramondunker** [comment]
Hi @Tikipeter ,

Thanks for your reply, got it working. I mostly use builds as a starting point, instead of setting everything up manually. Can you tell me what's wrong with builds in your opinion?

**Comment by xyzfre** [comment]
Personally on my end I like creating my own personal build to my personal preference but one of the main reasons you never know where the build got the addon from and it's always good to make sure it comes from its original Repo source,, that's my opinion but the dev knows BEST Fen is an amazing add-on you just have to tweak the settings to your liking just play with them a little till you get them right lol

**Comment by Tikipeter** [comment]
What repository is Fenomscrapers linked to?

**Comment by ramondunker** [comment]
To the original one where Fen is also hosted on. I checked most plugins and all are from original repos.

Thanks for the quick and useful help :)

Op 21 feb. 2022 om 00:32 heeft Tikipeter ***@***.***> het volgende geschreven:

﻿

What repository is Fenomscrapers linked to?

—
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTikipeter%2Frepository.tikipeter%2Fissues%2F694%23issuecomment-1046346348&data=04%7C01%7Cr.dunker%40st.hanze.nl%7C543c64252fa848efc23d08d9f4c938c8%7Ca3b390147adc48faa11437c2434dbd69%7C0%7C0%7C637809967354810351%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8n5bzv%2Fmsou2teKPkLMXIofXCJWodd2tQQ71SKN0eZ8%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABVBPOU6MQTMDLR6NBRLJI3U4F2XXANCNFSM5O445VSA&data=04%7C01%7Cr.dunker%40st.hanze.nl%7C543c64252fa848efc23d08d9f4c938c8%7Ca3b390147adc48faa11437c2434dbd69%7C0%7C0%7C637809967354810351%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=JzPOvsXLBORQYAc4bMlYxDpa46LJVuRpR4d7uwhKg4c%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cr.dunker%40st.hanze.nl%7C543c64252fa848efc23d08d9f4c938c8%7Ca3b390147adc48faa11437c2434dbd69%7C0%7C0%7C637809967354967025%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=rdkjLU6n3MWqnMaGR75SmEVWOn8ZusowUTuITEDAqaY%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cr.dunker%40st.hanze.nl%7C543c64252fa848efc23d08d9f4c938c8%7Ca3b390147adc48faa11437c2434dbd69%7C0%7C0%7C637809967354967025%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=xPzrEqQSw4sSIf4mZKMm5vM7rdgy2Atdwuxn2Iwjks8%3D&reserved=0>.

**Comment by 123Venom** [comment]
I agree with @Tikipeter and @xyzfre to NOT use builds.  They're usually over-bloated and can bog out devices.  You are best to create your on setup with 2-3 addons and save as a backup for other devices and quick setup.
