### ISSUE TITLE
Foreign fan art

### ISSUE THREAD

**Issue by JFG1000** [Tikipeter/repository.tikipeter#696]
Hi I was wondering if you know why the fan art for the show "Power book 2 : Force" is displaying as a foreign logo? 

Many thanks
![Screenshot_20220227-133534_Gallery](https://user-images.githubusercontent.com/76907836/155884634-d79aa323-a77b-4b51-9a79-947d79c04d1d.jpg)

**Comment by Tikipeter** [comment]
The current default behavior (if there's no art in the chosen language) is to then grab the most voted for art from the remaining. This has been changed for the next release a while back. So until I release the next version, that is the reason you see that foreign language.

**Comment by JFG1000** [comment]
Ok mate awesome thanks for the response

**Comment by Tikipeter** [comment]
Should be fixed on v.2.6.01

**Comment by JFG1000** [comment]
Cheers mate look forward to the update
