### ISSUE TITLE
Fen showing every single watched show in "In progress TV Shows"

### ISSUE THREAD

**Issue by rexiscodin** [Tikipeter/repository.tikipeter#698]
Hello, I just did a clean install of Kodi and installed fen. But, no matter what I do in "In Progress TV Shows", every single show I've watched shows up with a tick mark. Have tried re-installing kodi and fen.

Windows 10, tried both 19.3 and 19.4 with the latest Fen.

**Comment by Tikipeter** [comment]
Are they all still airing?

**Comment by rexiscodin** [comment]
> Are they all still airing?

nope. all of them are finished and this didn't happen until I re-installed fen.

**Comment by Tikipeter** [comment]
Can you post a screen capture here?

**Comment by Tikipeter** [comment]
Version of Fen too please.

**Comment by rexiscodin** [comment]
> Can you post a screen capture here?

Sure. As you can see, all of them are tick marked and showing up in the in progress section, except Daredevil which I'm currently watching and it isn't tick marked. If you would like a recording of this I can also provide that. 
![watched](https://user-images.githubusercontent.com/65942753/157305574-d348721c-8c46-418e-a8e2-89009bc37a54.png)
![unwatched](https://user-images.githubusercontent.com/65942753/157305589-af335285-476b-446d-8fc8-47eda5fef3a9.png)

**Comment by Tikipeter** [comment]
Are you using Trakt to maintain your watched status?

**Comment by rexiscodin** [comment]
> Are you using Trakt to maintain your watched status?

Yes. I am, and it shows up correctly on the trakt website.

**Comment by Tikipeter** [comment]
> > Are they all still airing?
> 
> nope. all of them are finished and this didn't happen until I re-installed fen.

What I meant by that is are they all "ended". i.e. the show no longer airs because it has ended/been canceled.

If the show has a full watched history, but the show is still being made/airing episodes, then it will show up in your In Progress section.

Unless there's any shows in that list that have are no longer being produced and you have watched all the episodes for that show, then In Progress is working correctly.

**Comment by rexiscodin** [comment]
> > > Are they all still airing?
> > 
> > 
> > nope. all of them are finished and this didn't happen until I re-installed fen.
> 
> What I meant by that is are they all "ended". i.e. the show no longer airs because it has ended/been canceled.
> 
> If the show has a full watched history, but the show is still being made/airing episodes, then it will show up in your In Progress section.
> 
> Unless there's any shows in that list that have are no longer being produced and you have watched all the episodes for that show, then In Progress is working correctly.

Most of the shows in that list are no longer being produced and I have watched all the episodes. For example - euphoria still shows up after I have watched both the seasons, and it shows that on the trakt website too.

![trakt](https://user-images.githubusercontent.com/65942753/157307402-0b3eac19-1ca7-4baa-815d-da1d72aabad4.png)
![euphoria tick](https://user-images.githubusercontent.com/65942753/157307280-b12185fd-e651-4286-8fe0-ade475bf8199.png)
![euphoria watched](https://user-images.githubusercontent.com/65942753/157307305-63712174-4dbb-4534-8e22-1ddd217f755a.png)

**Comment by Tikipeter** [comment]
Euphoria is a `Returning Series`. Meaning it is still being produced.

**Comment by rexiscodin** [comment]
> Euphoria is a `Returning Series`. Meaning it is still being produced.

Oh. I just tried to mark another series that has ended as completely watched and it disappeared from the menu. But, before this update it only showed me the shows that I was in the middle of watching and not those which were in production. so is there any way to get that functionality back?

**Comment by Tikipeter** [comment]
I might add a setting for excluding shows still airing but currently fully watched.

**Comment by rexiscodin** [comment]
> I might add a setting for excluding shows still airing but currently fully watched.

Alright, until then thank you very much for all the hard work you do for us. Have a great day!

**Comment by Tikipeter** [comment]
I've decided to add a setting for this next update. And the setting will default to NOT show the currently fully watched but still airing shows.

If you think you can handle changing one line of code, you could disable this behavior before then.

In the Fen addon folder, navigate to resources/lib/modules and open `watched_status.py` in a text editor.
Add a `#` to the front of this line (line 151):
`elif watched_status[0] == 1 and meta['status'] not in ('', 'Ended', 'Canceled'): append(item)`

So it will look like this:
`#elif watched_status[0] == 1 and meta['status'] not in ('', 'Ended', 'Canceled'): append(item)`
Save the change and close the file.

Navigate out of Fen into another addon, and then navigate back to Fen and you should see the behavior you want (Or restart Kodi after the changes).

**Comment by rexiscodin** [comment]
> I've decided to add a setting for this next update. And the setting will default to NOT show the currently fully watched but still airing shows.
> 
> If you think you can handle changing one line of code, you could disable this behavior before then.
> 
> In the Fen addon folder, navigate to resources/lib/modules and open `watched_status.py` in a text editor. Add a `#` to the front of this line (line 151): `elif watched_status[0] == 1 and meta['status'] not in ('', 'Ended', 'Canceled'): append(item)`
> 
> So it will look like this: `#elif watched_status[0] == 1 and meta['status'] not in ('', 'Ended', 'Canceled'): append(item)` Save the change and close the file.
> 
> Navigate out of Fen into another addon, and then navigate back to Fen and you should see the behavior you want (Or restart Kodi after the changes).

Just did it, and it's working exactly how I'd like. Thanks so much!

**Comment by Tikipeter** [comment]
No worries. Good job.

**Comment by Tikipeter** [comment]
I've changed my mind again. I'm just going to revert the behavior to how it was before this latest update. Likely I'm the only one who wants to see the fully watched still airing shows in the progress. :)
