### ISSUE TITLE
Fanart: API Key

### ISSUE THREAD

**Issue by ronfrankhill** [Tikipeter/repository.tikipeter#70]
Is it possible for you to add in the account setting a section for users to add their personal Fanart API key in the Fen add-on. Possible an option to add TheTVDB user key.

**Comment by Tikipeter** [comment]
Hi ronfrankhill.

The setting for adding an API key for Fanart is in tikimeta settings. Get there through Fen by navigating Settings->EXTERNAL: Tikimeta Settings.

I'll think about adding an API key entry for TVDb.

**Comment by ronfrankhill** [comment]
Thanks. I don't know if you can benefit from this but here goes. https://github.com/KyranRana/cloudflare-bypass

**Comment by Tikipeter** [comment]
Thanks ronfrankhill. I'll have a look through them >)

**Comment by Tikipeter** [comment]
TVDb API setting added to tikimeta for v.1.1.26.

Enter your own TVDb API (version 2 API only) in settings if desired. You must then clear TVDb token in settings for tikimeta to start using your API key immediately.

**Comment by ronfrankhill** [comment]
Thanks. I appreciate it a lot.

**Comment by ronfrankhill** [comment]
I can't remember if there's a play progress option for background or foreground in Fen add-on.
