### ISSUE TITLE
Auto play Replaying

### ISSUE THREAD

**Issue by luckylukz02** [Tikipeter/repository.tikipeter#70]
Kodi Nexus

Playing something with Auto play, if I stop the video it scrapes links again and plays the video again.

Once it plays for a second time if I close the video this time it doesn't attempt to Auto play.

**Comment by luckylukz02** [comment]
Can this be opened again?

[https://paste.kodi.tv/ivekocexid.kodi](kodi.log)

**Comment by Tikipeter** [comment]
How is the video being played? From a widget or from within Fen? From a TMDbHelper player?

If widget, where is the widget coming from? Directly from Fen or via Auto Widgets?

Does this happen when playing a file from directly within Fen?

Does this happen on the currently supported Kodi version, instead of a pre-release Kodi version?

**Comment by Tikipeter** [comment]
Tried in Kodi 20 Alpha 3 and I can't reproduce this.

**Comment by luckylukz02** [comment]
I am using a new devices, Khadas Vim4

![1667926196458356252529341955373](https://user-images.githubusercontent.com/80491975/200626052-2842d078-41aa-4125-8211-a9588a3ce2e2.jpg)

Playing video from File, YouTube addon and IPTV all seem to stop correctly.

**Comment by luckylukz02** [comment]
Also I thought it maybe my remote but I have the same problem when using my Bluetooth remote, IR keyboard and the UI stop button.

**Comment by luckylukz02** [comment]
Hi, i have tested this behaviour with other skins such as Arctic Horizon, AppTV, Amber and Estuary. This issue isnt present in these skins and is only limited to Arctic Horizon 2. Currently i have the latest version of the skin installed but have also tried reverting to 0.6.5 which i intially had no problems with.

Thanks

**Comment by luckylukz02** [comment]
Started skin from stratch. Seems to have been issue with write permission on skin.
