### ISSUE TITLE
Check year before search

### ISSUE THREAD

**Issue by JesseNtaylor** [Tikipeter/repository.tikipeter#701]
Possible bug?

Just updated to fen 2.6.01. started getting zero torrent and holster results when scraping since update

Kodi 19.4 on Ubuntu 20.04.4LTS

Found possible bug..... when activating the tick in fen settings, RESULTS, "check year before search" will then ONLY return results from cloud and you get zero results from hosters or torrents..

Unticking box returns all results as normal..  

Log here of search when ticked

https://paste.kodi.tv/izahategib

**Comment by Tikipeter** [comment]
I'll check it out....

**Comment by JesseNtaylor** [comment]
From what I can see in the log I think you're searching for an integer rather than a string?

**Comment by Tikipeter** [comment]
Yep. Fixed for next update. I'll push it out today my time most likely. As you say, turn off year check until then.
Changed to dealing with the year as a `str` in last update, but forgot about the imdb check for year, which returns an `int`. Don't use year check myself. :)

**Comment by JesseNtaylor** [comment]
Many thanks...
