### ISSUE TITLE
No Debrid links with Fen 2.06.01

### ISSUE THREAD

**Issue by chrisnikol** [Tikipeter/repository.tikipeter#702]
First off all i want to thank you for all your hard work and this amazing addon called Fen.

After i update Fen at 2.06.01 i noticed that Fen no longer returning any debrid sources.

I tested at windows 11 64 bit OS and android 10, in both cases the version of kodi was the 19.4

You can read the log file:

https://pastebin.com/jBXYynsx 

but i am not sure how helpfull would be, since i am not receiving any error msg.

Its normal log. If you think a debug log would actually help you please let me know and i will provide as soon as possible.

To understand what i am talking about i am including a video. The first part is with Fen and second part for the same movie with venom.

https://youtu.be/HrgNTk-yXjc

I have Real-Debrid account, All-Debrid account as backup and Easynews account. After the last update the Fen is returning links only from EasyNews.

My debrid accounts are not expired and i tried to re-authendicate both my Real-Debrid and All-Debrid account but the results was the same.

**Comment by JesseNtaylor** [comment]
Have you tried unchecking the "check year before search" in the results section of fen settings?

**Comment by chrisnikol** [comment]
> Have you tried unchecking the "check year before search" in the results section of fen settings?

I just saw your report and yes by unchecking the "check year before search" the Fen is returning debrid sources. So actually this is the same issue with the one that you reported.

Thanks for your help.

**Comment by Tikipeter** [comment]
Good job. I'll close this issue and use the other Issue for this problem.
