### ISSUE TITLE
Error when playing with TMDBHelper

### ISSUE THREAD

**Issue by Liquidrag** [Tikipeter/repository.tikipeter#704]
Thank you for the updates and continued support.

I have the 2.6.02 update and it seems to have broken the player for TMDBHelper. can you update the player?

here's my log https://paste.kodi.tv/cocicoteyi.kodi

**Comment by Tikipeter** [comment]
>can you update the player?

I cannot. I do not support TMDbHelper, so I'm not willing to update the player.

If some other kind soul wants to do it, then they need to change the instances of `vid_type` to `media_type` within the playback urls.

**Comment by Liquidrag** [comment]
Thank you I was able to do that. I attached the files if anyone else needs them.
[fenplayers.zip](https://github.com/Tikipeter/repository.tikipeter/files/8211175/fenplayers.zip)

**Comment by ShibajiCh** [comment]
Thank you @Tikipeter and @Liquidrag for the above! This resolved the player issues for me in TMDB Helper. 🙂 👍

Thanks and Regards,
ShibajiCh.
