### ISSUE TITLE
[Request] Force View Types?

### ISSUE THREAD

**Issue by unkn0wn234** [Tikipeter/repository.tikipeter#705]
I'm using Embuary on v19 and if i set a viewtype for the movies or shows it doesn't transfer over to other movie paths within fan or even when i click next page within that path. I think it's an embuary problem but just posting this in case you'd be interested in adding a force view types option in Fen.

Cheers
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/8212704/kodi.log)

**Comment by Tikipeter** [comment]
Are you setting the viewtype correctly through Tools-->Set Views?

**Comment by Tikipeter** [comment]
I installed Embuary and can't even see where to change viewtypes.

**Comment by unkn0wn234** [comment]
> I installed Embuary and can't even see where to change viewtypes.

It's in the top right but I think he may have made it so you can't use custom view types on addons so I edited the xmls slightly to allow it. I'm pretty sure it was always allowed on movies and shows tho I had to enable it manually for episodes.

**Comment by Tikipeter** [comment]
Thanks mate, I found it. The set views are working for me, when I set them correctly. Which leads back to this question:
>Are you setting the viewtype correctly through Tools-->Set Views?

**Comment by unkn0wn234** [comment]
Im really sorry I cant seem to find Tools - Set Views? Is it in the Fen context menu cause I dont see it. This must be a stupid question

**Comment by unkn0wn234** [comment]
Nvm im an idiot

**Comment by Tikipeter** [comment]
Did you get it working OK?

**Comment by Tikipeter** [comment]
Always try and set the views through the addon you're using if there's the ability to do it. Some skins offer a "view lock" type thing, but it's always better for the addon to handle it if it can.

The way Kodi handles views is not geared at all for addons unfortunately. So the addon sets it each page instead.

**Comment by unkn0wn234** [comment]
Yep I got it working I just felt dumb for having used fen for so long and not knowing where tools were. Plus I made a feature request for something that was already in the addon :p thanks again for the help I know it can get frustrating when people ask for features or things that are in the addons and they haven't checked first
