### ISSUE TITLE
Request for the custom search path for "SEARCH: Movies Collection (TMDB)"

### ISSUE THREAD

**Issue by ShibajiCh** [Tikipeter/repository.tikipeter#707]
Hi @Tikipeter,

This is not an issue but a request. Could you please provide the custom search path for "SEARCH: Movies Collection (TMDB)" similar to below?

plugin://plugin.video.fen/?mode=people_search.search&actor_name=

I want to implement it in the Arctic Horizon skin's default search in Kodi.

Thanks and Regards,
ShibajiCh.

**Comment by Tikipeter** [comment]
`plugin://plugin.video.fen/?mode=build_movie_list&action=tmdb_movies_search_collections&query=`
