### ISSUE TITLE
Request to bring back "Mosts" feature in Movies and TV shows Menu

### ISSUE THREAD

**Issue by ShibajiCh** [Tikipeter/repository.tikipeter#708]
Hi @Tikipeter,

I was a big fan of your "Mosts" feature under Movies and TV Shows menu and am really sad to see that it has been removed in the latest update. Could you please bring back that feature, especially Most Watched This Week as I used it to determine the Top 10 Movies and TV Shows of the week?

Thanks and Regards,
ShibajiCh.

**Comment by Tikipeter** [comment]
I'll add `Most Watched This Week` to Movies and TV Shows menus.

**Comment by Tikipeter** [comment]
Done for next update.

If you haven't edit the menu structures in Fen, then just navigate into the Movies and TV Shows menus, bring up the context menu on any item, and select Edit Menu-->Restore Menu to Default. This will reload the default menu items and the new one will appear.

If you have edited the menus and want to keep those edits, then navigate into the Movies and TV Shows menus, bring up the context menu on any item, and select Edit Menu-->Check if Menu Has New Menu Items. It will then tell you there is a new menu item. You can then choose where to put it in the menu list.

**Comment by ShibajiCh** [comment]
Hi @Tikipeter,

Thank you for providing the above details!
I'll surely check them out. Eagerly waiting for the next update.

Thanks and Regards,
ShibajiCh.
