### ISSUE TITLE
auto update library subscription

### ISSUE THREAD

**Issue by ricinga666** [Tikipeter/repository.tikipeter#71]
I have an issue with the auto-update of subscriptions. 

I have tried on Kodi 18.5 and 18.2 on both fresh instal and existing setup and on android and windows 10.

I have set up my subscription folders as Trakt lists. and these scan into the library fine on first loading, I set my update schedule to 1 hour (i have also tried 2 and 12 hours).  In the tools section, this then shows me the next update time.   

At this time the update does not happen and stays at the time which is now in the past.  this now will not change unless I click the update button in tools or if I restart Kodi. at which time a new update is done and a new time for the next update set,  this then repeats the whole process.  

For info I have around 50 shows in both my tv and movie subscription lists.

**Comment by ricinga666** [comment]
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/3916859/kodi.log)

**Comment by Tikipeter** [comment]
Hi ricinga666.

Should be fixed in next update (v.1.5.76). Fen should re-do a subscription update at the desired scheduled interval now.

One issue I cannot control (or fix) is if you change the update schedule in settings, you will have to restart Kodi for Fen's subscription service to register the change (to do with service.py behavior). (This is despite the Tools' Menu item showing the correct new update time.)

But Fen should update now on schedule, without having to restart Kodi. :)

**Comment by ricinga666** [comment]
That's great news.    No worries about that once it's sorted there should be no need to change the update time.  

Is there any way you could set the update to go off at a set time (ie the middle of the night).  

I have used library auto-update (from the official Kodi repo) in the past and that uses cron expression to set the update to go off at 4 am.  meaning I don't see the library updates/cleaning

**Comment by Tikipeter** [comment]
Firstly, I've been able to fix it so that it will honor a new schedule setting without reloading Kodi.

As for your new question, let me think about it some more. It probably won't be in the next update, but I might be able to do it.

**Comment by ricinga666** [comment]
great news.

No rush on it, it was just a thought I had.  I saw you advised previously about telling people to turn library clean off 
if it was taking too long and thought this might be a viable solution for people.

**Comment by ricinga666** [comment]
to confirm the library update works as expected again.  Although I did have to clear my addon settings and set it up again as it was giving me continuous library updates.

**Comment by Tikipeter** [comment]
Troubling that you had to clear settings, but I'm glad it's working now.

I'll close this, as it will stay in my head to implement the set time feature you suggested as I like the idea of it.
