### ISSUE TITLE
TMDB Helper players for Fen no longer working

### ISSUE THREAD

**Issue by ShibajiCh** [Tikipeter/repository.tikipeter#710]
Hi @Tikipeter,

TMDB Helper players for Fen are no longer working after the latest update. Could you please check?

Here's my Kodi log:
https://paste.kodi.tv/ulukesolif

Thanks,
ShibajiCh.

**Comment by Tikipeter** [comment]
Fen doesn't support TMDbHelper.

There is, however, a closed issue on this github where a user made a new set of Fen players for TMDbHelper. Find that and use those new players instead.

**Comment by ShibajiCh** [comment]
Thank you @Tikipeter! I found that closed issue and the players are working fine now.

Thanks and Regards,
ShibajiCh.

**Comment by thefrench1** [comment]
Hi. Do having the same issue if possible can you pm or send me the correct link to follow as not sure how to do this or the correct thread. Thank u in advance

**Comment by ShibajiCh** [comment]
Hi @thefrench1,

Please check the following issue link. It has the updated players:

https://github.com/Tikipeter/repository.tikipeter/issues/704

Regards,
ShibajiCh.

**Comment by ShibajiCh** [comment]
Hi @thefrench1,

Please follow the below process.

Go your user folder, then addons, then tmdb Helper folder and then both players and reconfigured players. Delete all the players related to Fen. Then open Kodi, go to TMDB Helper settings and re-download the players from the usual tmdb helper players url. Now close Kodi and go to the folders again and replace only the 2 players within players folder under your user directory. After this you can again open Kodi and reconfigure the players in TMDB Helper settings as per your need. You need to select playmedia under set resolved settings for the Fen player and then save the settings.

Hope this helps.

Regards,
ShibajiCh.

**Comment by thefrench1** [comment]
Hi @ShibajiCh. Thank you for the guide above that solved the issue. Again many thanks.

**Comment by ShibajiCh** [comment]
> Hi @ShibajiCh. Thank you for the guide above that solved the issue. Again many thanks.

Hi @thefrench1,

You're welcome! 🙂 👍

Regards,
ShibajiCh.
