### ISSUE TITLE
Playing links from Easynews 

### ISSUE THREAD

**Issue by IG2022** [Tikipeter/repository.tikipeter#713]
I've just got an Easynews account and linked it to fen I'm having trouble with consistency of  links playing. (Sometimes they play sometimes they try and fail) 

I know that Kodi 19.1 had some issues and you had mentioned this before in the change log a while back  but I just wanted to check in and see if its something that is still a problem with Kodi or if it's possibly my setup that's having issues. I am having the same problem on Android and Mac OS. 

Here's my log. 

https://paste.kodi.tv/daxudutuje

**Comment by Tikipeter** [comment]
An Easynews problem unfortunately. Sometimes the video doesn't start within the required time frame. I think Kodi gives 28 seconds timeout for video start.

**Comment by IG2022** [comment]
Ahh okay got it. Thanks for letting me know. Would you suggest I just try another link when this happens?

**Comment by Tikipeter** [comment]
Not really. It appears random. You're just as likely to get the previous link to play again when you retry.

There is some utility to changing the location of server within the Easynews settings page, but unfortunately I've forgotten where that setting is. If you want to have a look around the settings page you might find it..

**Comment by IG2022** [comment]
I'll take a look and see if I can sort it out. Thanks for the advice!
