### ISSUE TITLE
Fen - Kodi crash

### ISSUE THREAD

**Issue by JFG1000** [Tikipeter/repository.tikipeter#714]
Hi I've noticed since the latest update something with Fen is causing my kodi to crash to nvidia shield homescreen, I can cause this most times on a skin reload using auramod, this also happens when exiting playback quite often, I would get a debug but I'm not sure how to capture the log if kodi crashes, I've deleted all the widgets that relate to fen to test, And when there's no widgets i get no crashes.

Kodi 19.4

**Comment by Tikipeter** [comment]
Sounds like it's fucked.

**Comment by JFG1000** [comment]
Is there anything I can do to help?

**Comment by Tikipeter** [comment]
I'm completely lost as to why it's happening to be honest. True Fen and all addons run different code, but when it comes to making a Kodi directory of listitems there's really only one way to do it in the end. So it's not like I'm running some fundamentally different code to every other addon out there. But this seems to only happen with Fen.

If I had a clue at least I'd know where to start. I thought it might be something in the code for after a video finishes, but you're saying you can run a skin refresh and it happens then as well.

I'll install AuraMOD and see if I can get any idea as to what's happening.

You definitely have the Invoker OFF?

**Comment by Tikipeter** [comment]
@JFG1000 

I reopened another Issue that you commented on where a crash at end of playback was being observed because I think they might be related.

I tested a change using Arctic Horizon (I can't install AuraMOD at the moment so went with that skin instead) and the crash no longer happens.

**Comment by JFG1000** [comment]
I'm on Keybase if you can message mate
