### ISSUE TITLE
Movie files in kodi library won’t play anymore after FEN 2.5.21

### ISSUE THREAD

**Issue by jaimsitecom** [Tikipeter/repository.tikipeter#715]
I had to go back to ver 2.5.21 so i can play TMDB HELPER movies to play via FEN from the kodi library. The next 3 versions up to the latest gave errors and won’t play anymore…so i had to downgrade back to 2.5.21. 

Log:
https://mega.nz/file/AYxnCAwL#KKs8GUnChNP-ofdgKGpXAnTwiK4_oEuQEr0uAwW66eM

**Comment by Tikipeter** [comment]
Update your players.

**Comment by jaimsitecom** [comment]
I reinstalled ver 2.6.05. Check. 
I went to tmdb helper setting and updated the players. Check. 
I restarted kodi. Check. 

Played a movie. But still no joy. Gets error. 

Log:
https://mega.nz/file/dJohCaoS#u8Az8ONP5wwWRNKaF7pKwOjqcogjAgvPphpwtH3ADp4

**Comment by Tikipeter** [comment]
Try reconfiguring the Fen players in the settings.

I don't use TMDbHelper, and there is no implied support for Fen. Apparently the players have been updated to work with the latest Fen. But apart from that I know nothing about the situation.

**Comment by jaimsitecom** [comment]
I’ll tinker with the player then. If i couldn’t make it work, i can always just stick with what’s working now (2.5.21). 

Thanks Tikipeter!

**Comment by Tikipeter** [comment]
Never a good idea.

It's a TMDbHelper bug. It doesn't replace "reconfigured" players when players are updated. It continues to use the old reconfigured players.

**Comment by jaimsitecom** [comment]
Ok. I’ll head over to TMDB Helper now. Will let them know their FEN player is out of date. 

Thanks again.

**Comment by jaimsitecom** [comment]
You are right. I uninstalled TMDB Helper, reinstalled it again. Started all settings from scratch, and re downloaded all players in default settings, then set it it up the way i liked it. Presto! Works again!

thanks Tikipeter! Whew!
