### ISSUE TITLE
Fen 2.6.05 "rescrape & select source"

### ISSUE THREAD

**Issue by zambux** [Tikipeter/repository.tikipeter#716]
Dont now if just whith me , but options-rescrape & select source dont work, it auto plays insted of select source, in version Fen 2.6.04 it is working ok

**Comment by Tikipeter** [comment]
Yeah it's a bit broken.

**Comment by MehBlorg** [comment]
+1. Came here to report this. If autoplay is enabled for episodes, the rescrape and select source doesn't present a list. It just plays. You have to disable autoplay for episodes in order for that to work.

**Comment by Tikipeter** [comment]
I know.

**Comment by MehBlorg** [comment]
👍

**Comment by Tikipeter** [comment]
Fixed for next update.
