### ISSUE TITLE
Trakt TV Collection Add/Remove

### ISSUE THREAD

**Issue by Cloudman999** [Tikipeter/repository.tikipeter#717]
I don't seem to be able to add to or remove TV shows from Fen, using the context menu. Fen returns the error message to 'check the log file for more information'.

I have reauthorized Trakt, re-synced with Fen and cleared the caches several times, but still unable to get it to work.

This has been happening for past few days and since latest Fen update.

Kodi 19.3 Fen 2.6.05

Any help would be appreciated. Thank you Tikipeter.

**Comment by Tikipeter** [comment]
I just checked and it's not working.

**Comment by Tikipeter** [comment]
Fixed for next update.

**Comment by Cloudman999** [comment]
Thank you very much for fixing the problem @Tikipeter . Looking fwd to the next update.
