### ISSUE TITLE
Nothing Loads

### ISSUE THREAD

**Issue by Jrdnkasparek** [Tikipeter/repository.tikipeter#719]
Idk what’s happening but nothing will load in Fen
-Anything in Movies or TV sections
-Trakt lists 

evey section jast returns blank 🤷🏼‍♂️

Latest update of Fen and Kodi 19.4
Was happening before 19.4 as well

**Comment by Tikipeter** [comment]
I'll need a log.

**Comment by Tikipeter** [comment]
Scratch that. I'll post a fix now....

**Comment by JesseNtaylor** [comment]
Latest update...  Only trakt list I can now see is my watchlist/next episodes. 

Any other trakt list e.g. trending movies, trakt personal lists, movies watchlist etc just returns an empty widget and empty list.. 

Log here... https://paste.kodi.tv/kenuqacaxu

**Comment by Tikipeter** [comment]
Refresh repo until you see version `2.6.07` I just uploaded. It will have the fix needed.

**Comment by JesseNtaylor** [comment]
Thanks... fiix tested and issue resolved

**Comment by oidarwazeh** [comment]
> Refresh repo until you see version `2.6.07` I just uploaded. It will have the fix needed.

Literally just came here to resolve the issue. Updated, working perfectly. Thanks!

**Comment by Jrdnkasparek** [comment]
Thank for the fix!
