### ISSUE TITLE
Trakt movies watchlist doesn't show

### ISSUE THREAD

**Issue by ANHBOB** [Tikipeter/repository.tikipeter#72]
After the update to 1.5.76b when I go to... My Trakt Lists....Watchlists....Movies  it is blank. Doesn't show anything at all, but if I use another addon like The Crew it shows my movies. 

In FEN under My Trakt Lists...Collections....TV Shows...that works as expected. I have all my TV shows there.

I appreciate all the work you do. I think FEN is one of the best addons I've used. Thank you.

**Comment by Tikipeter** [comment]
Fixed for next update.

**Comment by xyzfre** [comment]
After yesterday‘s update on my end my Trakt watchlist for TV shows ,,shows up blank but for collections etc.. They work and my shows are all there ,, thank you for all your hard work Fen is definitely the best hope you can sort it out

**Comment by Tikipeter** [comment]
> 
> 
> Fixed for next update.
