### ISSUE TITLE
Fen- Trakt errors on wake

### ISSUE THREAD

**Issue by tundrablasen** [Tikipeter/repository.tikipeter#725]
Nvidia Shield TV, Kodi 19.3

 when I wake the Shield into Kodi there’s lots of error pop ups for Fen. They go by quickly but the Fen errors mention connection pool host api.trakt.tv, although all Trakt lists load and content gets marked as watched by Trakt.
Issue just comes when kodi is in the background and you open it again. If it normally starts no error

It gets lots of error pop ups, it can last a a couple of seconds/minutes before they finally stop. 

The issue is:  HTTPSConnectionpool(host=‘api.trakt.tv’ , port=443)

Full install or reauth Trakt does not fix the issue.

I again double checked with venom. It does Not have this issue. Seren has. 

So i think @123venom fixed this in one of his last updates, maybe you could ask him and he points in the right direction

**Comment by Tikipeter** [comment]
Log of the errors please.

**Comment by tundrablasen** [comment]
I will try to provide a log today. Please Have a bit patience. Thanks

**Comment by tundrablasen** [comment]
> Log of the errors please.

https://paste.kodi.tv/hoyixapexo

**Comment by Tikipeter** [comment]
Just found a way to check if device is in sleep state, so this should be fixed for next update.
