### ISSUE TITLE
No trakt progress results

### ISSUE THREAD

**Issue by ananias47** [Tikipeter/repository.tikipeter#727]
Hi i have a strange problem on trakt progress. I have two  trakt accounts The first account give me results on progress .The second account give me no results(blank) with no error. in other addons works great so there is no an account problem

ps: i use coreelec

**Comment by Tikipeter** [comment]
I'll be pushing an update soon with some trakt changes. So best to wait for that and see if it sorts out this problem you're having.

**Comment by ananias47** [comment]
ok my friend

**Comment by ananias47** [comment]
hi my friend i tested it again with the latest update but steel i have the same problem
