### ISSUE TITLE
Possible Bug: Scrapping box with image pops up few minutes before the video playback ends

### ISSUE THREAD

**Issue by ShibajiCh** [Tikipeter/repository.tikipeter#729]
Hi @Tikipeter,

Since the last update of Fen to version 2.6.08, I've been noticing that around 2-3 minutes before a video playback ends the scrapping box with image pops up for a fraction of second on the screen and then disappears instantly. It happens so fast that I can't even take a screenshot to share here. However, I guess this only happens when the autoplay next episode/movie setting is on. I think that instead of the scrapping for the next episode happening in the background, the pop up somehow appears on the foreground just after the video is marked as watched in Trakt. You can try and check for yourself if you're noticing the same issue like I do. Though it's not a very big issue, however it just causes a minor distraction while watching the video.

Here's my Kodi log:
https://paste.kodi.tv/egukakamuj

Thanks and Regards,
ShibajiCh.

**Comment by Tikipeter** [comment]
I'll have a look before I push the next update.

**Comment by Tikipeter** [comment]
Fixed for next update.

**Comment by ShibajiCh** [comment]
Hi @Tikipeter,

Thank you so much! 🙂 👍

Thanks and Regards,
ShibajiCh.
