### ISSUE TITLE
Fen Showing Incorrect Episode Count

### ISSUE THREAD

**Issue by rogermae** [Tikipeter/repository.tikipeter#730]
As of the current update v.2.6.09, Fen is showing the entire episode count for each show in my Trakt Watchlist and My Shows lists has been for a week now. All of my other addons show the correct episode count of unwatched episodes. I've revoked and reauthorized Trakt several times, closed and cached Kodi as well. Here is the log...
paste.kodi.tv/obelesoruh

**Comment by Tikipeter** [comment]
What skin?
