### ISSUE TITLE
[Request] Date arrangement on watched list

### ISSUE THREAD

**Issue by Skoukoubagia** [Tikipeter/repository.tikipeter#731]
Hello, first of all thank you, Fen is awesome and with nice search features, however I find it very difficult to rewatch an episode I have finished because if I go to Watched it shows everything in alphabetical sorting which makes me search something really long time😛 I don't know how hard could an option in the settings be. If it's very time consuming forget it, thank you.

**Comment by Tikipeter** [comment]
I'll have a think about it....

**Comment by Tikipeter** [comment]
Will be default next update. No setting.

**Comment by Skoukoubagia** [comment]
Thank you very much. It had been the only thing missing from my view🙂 thank you for keeping it up also since I got the chance to talk to you. Should I close this?

**Comment by Tikipeter** [comment]
>Should I close this?

It's OK. I'll leave it up until I push the update.
