### ISSUE TITLE
[Request]Add "browse season" along with the existing "browse" context option

### ISSUE THREAD

**Issue by Liquidrag** [Tikipeter/repository.tikipeter#732]
Request to add "browse season" along with the existing "browse" context option so that it pulls you directly into the season instead of the whole series then I have to go into the correct season. It would save from loading the other seasons when it doesn't have to.

**Comment by JFG1000** [comment]
This would be a great edition to be honest

**Comment by Tikipeter** [comment]
Done for next update.
