### ISSUE TITLE
Fen issue with Trakt Sorting 

### ISSUE THREAD

**Issue by luckylukz02** [Tikipeter/repository.tikipeter#733]
When I add a widget on my skin Arctic Horizon through Fen I select the sort method as dateadded (see pic). 

![16481621677656768086544097615827](https://user-images.githubusercontent.com/80491975/160022703-ef6fa04b-4dd7-4963-baf3-c1061f4cc142.jpg)

This does not seem to do anything and shows the results in alphabetical order.

This is the case particularly for my Trakt watch list as I want to see the most recently added to show first. 

Is there any way to fix this. In the past I have used TMDB Helper which seems to have a deeper integration with Trakt which allows you to pick the sort order from Trakt. 

![16481622500205648013479277415804](https://user-images.githubusercontent.com/80491975/160022876-0ad208cf-e147-42c7-82a0-4decd7fb02d6.jpg)

**Comment by Tikipeter** [comment]
That sort method has nothing to do with Trakt, and is an internal sort method of Kodi.

No good using that for widgets made through an addon.

I'll make the trakt watchlist be sorted by recently added next update.

**Comment by luckylukz02** [comment]
That's great thanks. Look forward to it.
