### ISSUE TITLE
Issues with In Progress Movies list

### ISSUE THREAD

**Issue by ShibajiCh** [Tikipeter/repository.tikipeter#734]
Hi @Tikipeter,

After today's latest Fen update I noticed the following 2 issues with the In Progress Movies list:

1) The sort order is showing incorrectly, i.e. instead of the last watched in progress movie appearing at first the oldest watched in progress movie is appearing at first and so on...

2) Any in progress movie which was completely watched and is at 0% progress in Trakt is also showing up on the In Progress Movies list, which never happened earlier (see screenshots below).

![IMG20220325130538](https://user-images.githubusercontent.com/65297828/160078878-66d749e7-73ce-49fd-b239-df92cb3966b2.jpg)

![IMG20220325130515](https://user-images.githubusercontent.com/65297828/160078911-f1657f4f-6d96-4a1d-9203-83dbc15239c9.jpg)

Edit: I found a 3rd issue which is as follows:

3) After playing any movie from the In Progress list it's getting removed from the In Progress list in Fen, even though the movie is still present in the Trakt In Progress list. Also, any new movie played is not getting added to the Fen In Progress list even though it's getting added to Trakt In Progress list. The Fen In Progress list only gets updated with the newly played movies if I restart Kodi. I tried enabling and disabling the Kodi Menu Caching setting in Fen, but the issue still happens in both cases.

Here's my 1st Kodi log:
https://paste.kodi.tv/hejatefami

Here's my 2nd Kodi log which I generated after I noticed the 3rd issue:
https://paste.kodi.tv/ujuhobebuz

Here's my 3rd Kodi log which I generated after disabling Kodi Menu Caching setting in Fen:
https://paste.kodi.tv/omufoxulun

Kindly look into these issues.

Thanks and Regards,
ShibajiCh.

**Comment by xyzfre** [comment]
For the in progress movies the ones that show up  completely watch if you bring up the context menu click on clear progress they disappear from that section and they still maintain the checkmark for completely watched

**Comment by ShibajiCh** [comment]
@xyzfre,

If I clear my progress from Fen then they get marked as 0% progress under Trakt progress. Prior to the latest Fen update movies/tv shows with 0% progress were not displayed under In Progress list. The only solution at present is to go to Trakt In Progress and delete the entries from there.

Thanks and Regards,
ShibajiCh.

**Comment by Tikipeter** [comment]
Unfortunately I'm going to have to re-write a decent amount of the progress/watched code for next update. I was hoping a quick re-write would do for the time being, but there are issues that need to be addressed immediately.

After next update hopefully all these issues will be resolved.

**Comment by ShibajiCh** [comment]
Thank you @Tikipeter! 🙂 👍
