### ISSUE TITLE
Request: Option to select sort order type for Trakt Watchlists

### ISSUE THREAD

**Issue by ShibajiCh** [Tikipeter/repository.tikipeter#735]
Hi @Tikipeter,

I noticed that as per request from someone you've changed the sort order type for both Trakt Watchlists (Movies and TV Shows) to last added instead of Alphabetical like it was earlier. However, I really liked the Alphabetical sort order as it was earlier. I guess majority of Fen users will agree with me as Alphabetical sort order is very helpful while searching for Movies/TV Shows in large Trakt Watchlists. Therefore, it's my kind request that if you could add an option in the Fen settings to enable choosing of Trakt Watchlist Sort Order Type so that it can be either changed to Last Added or Alphabetical? In that way everyone can select their own choice.

Here's my Kodi log:
https://paste.kodi.tv/hejatefami

Thanks and Regards,
ShibajiCh.

**Comment by Tikipeter** [comment]
Trakt Collection and Watchlist will have new settings next update to sort by Recently Added or Title.

**Comment by ShibajiCh** [comment]
Thank you @Tikipeter! 🙂 👍
