### ISSUE TITLE
Error at because you watced function at tv-shows section

### ISSUE THREAD

**Issue by chrisnikol** [Tikipeter/repository.tikipeter#738]
First of all thank you for this amazing addon.

When i am trying to use the because you watced function at tv-shows section the addon though an error msg.
At Novies section is working withouth any issue.

Here is the full debug log: https://we.tl/t-i2AeQTUkA0

And a request if i may. Is it posible at because you watched list to have the full metadata like poster etc like when we are browsing the movies or tv-shows catalogue?

Thank you

**Comment by Tikipeter** [comment]
There's some re-working of watched//progress code needed for next update. Hopefully that will fix this issue, as I'm not experiencing a problem here myself.
