### ISSUE TITLE
Settings bug?

### ISSUE THREAD

**Issue by jaycassini** [Tikipeter/repository.tikipeter#74]
Trying to get into the settings menu and every time I load it up I get 
![20191204_104425](https://user-images.githubusercontent.com/29668042/70157278-4dcc8f80-1683-11ea-8ef9-e462e3421771.jpg) tried a reset of my device cleared kodi cache and still is doing it

**Comment by Tikipeter** [comment]
Hi jaycassini.
Please tell me the version of Kodi you are using.

**Comment by jaycassini** [comment]
18.5 i ended up getting it fixed by reinstalling
