### ISSUE TITLE
[Feature request] Exclude filter by resolution/codec combinations?

### ISSUE THREAD

**Issue by ASmanaTH** [Tikipeter/repository.tikipeter#742]
This would help us RPi users. The RPi isn't able to decode 4k with AVC (x264/h264) codec in HW, 4K with HEVC (x265/h265) is decoded fine. SW decoding is obviously too slow to be usable. Unfortunately there are many sources that use this bad combination. Being able to exclude by resolution **and** codec would be very useful, especially when using autoplay. Currently one is forced to exclude HEVC and/or 4k altogether. Or maybe a checkbox saying "Exclude 4k-AVC combination (for RPi users)" or something like that? What do you think?

**Comment by Tikipeter** [comment]
Has been asked for before and is a road I don't want to head down.
