### ISSUE TITLE
In progress tv shows

### ISSUE THREAD

**Issue by derrgoo** [Tikipeter/repository.tikipeter#743]
Maybe this is my issue but I have noticed nothing comes up since last few updates when I choose In a progress tv shows. Was it taken off? Everything else works great. Thanks

**Comment by Tikipeter** [comment]
Wait until next update when hopefully all the watched/in progress issues will be sorted.

**Comment by derrgoo** [comment]
Hi Peter,

Was wondering what it meant 'enable kodi menu caching' which I do use a jurialmunkey skin. Should I turn on or off? 👍
