### ISSUE TITLE
Cant open fen

### ISSUE THREAD

**Issue by Liquidrag** [Tikipeter/repository.tikipeter#745]
fen crashes when I try to open it. I have done a fresh install of kodi then fen but now it crashes. I can access settings but that's about it. 

https://paste.kodi.tv/gareyopose.kodi

**Comment by Tikipeter** [comment]
Delete the navigator.db and restart kodi.

**Comment by Liquidrag** [comment]
I cant find a navigator.db where should it be located?

**Comment by Liquidrag** [comment]
I've tried to delete navigator.py but it still doesn't work
