### ISSUE TITLE
Issue with In Progress Movies/TV Shows Resume option

### ISSUE THREAD

**Issue by ShibajiCh** [Tikipeter/repository.tikipeter#746]
Hi @Tikipeter,

After today's latest Fen update to v2.6.11 majority of the issues with In Progress Movies/TV Shows have been resolved. However, I noticed a minor issue that if I Resume an existing Movie/TV Show from the In Progress Movies/TV Shows list then that particular Movie/TV Show doesn't get moved to the Top of the In Progress list, even though my In Progress Sort Type is set as Recently Watched in Fen settings. Nevertheless, if I Start over the same Movie/TV Show instead of Resuming it then it gets moved to the Top of the In Progress list correctly.

Here's my Kodi log:
https://paste.kodi.tv/vujudenihu

Kindly check and advise.

Thanks and Regards,
ShibajiCh.

**Comment by Tikipeter** [comment]
Don't think much can be done for this. That is the information Trakt returns after setting the resume point.

**Comment by ShibajiCh** [comment]
Hi @Tikipeter,

Oh, is it so? Actually I thought that in a Fen update or two earlier I noticed that the Resume feature was working fine, i.e. the Movie/TV Show was moving to the top of the In Progress list after Resuming and stopping the playback. However, I might be wrong. In any case this is not such a major issue and will not hamper the great experience of Fen anyway. Thanks for the amazing addon!

Thanks and Regards,
ShibajiCh.
