### ISSUE TITLE
Hide unreleased movies in watchlist

### ISSUE THREAD

**Issue by Aezriel82** [Tikipeter/repository.tikipeter#747]
Hey I just moved over to Fen as my main widget source. is there is any way to hide unreleased content. I've got many movies in my trakt watchlist that aren't even close to being out Eg avatar 2, 3 etc but appear in my watchlist obviously with no sources. It can get quiet confusing especially on near release movies.
Is there an option I'm missing to fix this or Any chance U can add this as an option somehow. As a reference Seren seems to do it quiet well.

**Comment by Tikipeter** [comment]
Nope.

**Comment by xyzfre** [comment]
> Hey I just moved over to Fen as my main widget source. is there is any way to hide unreleased content. I've got many movies in my trakt watchlist that aren't even close to being out Eg avatar 2, 3 etc but appear in my watchlist obviously with no sources. It can get quiet confusing especially on near release movies.
> 
> Is there an option I'm missing to fix this or Any chance U can add this as an option somehow. As a reference Seren seems to do it quiet well. 

What I usually do is make a personal Trakt list for movies that haven't aired yet or are going to air in a couple years from now lol and I add those there and give it a name like upcoming movies to watch ,, and the list looks pretty cool , hope it helps

**Comment by xyzfre** [comment]
https://user-images.githubusercontent.com/49699869/161394213-e0fe9675-c47a-48f3-82bb-ae5d923c09b4.MOV

**Comment by xyzfre** [comment]
Just a small one as an example sorry that's on my phone but looks lovely on the big screen and I keep my watchlist with Movies that are ready or at least a couple days away from airing, but I understand it's all preference just trying to help👍🏼
