### ISSUE TITLE
Fen returning no results

### ISSUE THREAD

**Issue by Guacan0le** [Tikipeter/repository.tikipeter#748]
I was in the middle of watching a show last night when ‘Next Up’ returned no results. I’ve tried everything I can think of to get it working including reauthorizing my accounts. 

https://paste.kodi.tv/ipowebiyif

**Comment by Guacan0le** [comment]
Forgot to mention anytime I try and watch anything no it returns no results.

**Comment by Guacan0le** [comment]
Update: Fen is no longer working at all. I get the following error just trying to open the addon. I have Fen version 2.6.11 installed and Kodi version 19.4. 
![5CA06EA2-3E4C-4B8A-9DA1-1137A928BF2A](https://user-images.githubusercontent.com/102869797/161399787-7edf72aa-6c33-477a-9d4a-f0388f939f03.jpeg)
![4ADD5DE9-778B-400F-A85E-8A7914F7F9B2](https://user-images.githubusercontent.com/102869797/161399792-4efe1a5a-13b3-409d-9099-457999726b63.jpeg)

**Comment by Tikipeter** [comment]
Should be working with 2.6.12.

**Comment by Guacan0le** [comment]
Works like a dream. Thank you so much.
