### ISSUE TITLE
No issues just wanted to say thank you

### ISSUE THREAD

**Issue by xyzfre** [Tikipeter/repository.tikipeter#749]
With this latest update on my end everything is working flawlessly (PERFECT 👌🏼) with Fen no issues at all thank you for all the hard work you put into Fen ,, not quite sure why some people are having issues I tested almost every issue open lately and everything works GREAT,, using Nvidia shield pro 2019 ,AuraMOD 1.1.7, K19.4

**Comment by Tikipeter** [comment]
I appreciate the kind words.
