### ISSUE TITLE
Orion Integration

### ISSUE THREAD

**Issue by jjred1977** [Tikipeter/repository.tikipeter#75]
Morning Tiki,

The link caching service Orion is having trouble keeping a working integration with the FEN addon.  Whenever you have an update it seems their integration breaks because of a indentation error, One of the  two logs below should show you. Orion has created a beta zip asking me to try it to see if it solves the problem. The problem is when Orion is integrated with FEN, FEN will not scrape it just errors out.  If I remove Orion's integration then FEN works.

I know you aren't part of Orion but out of all the addons that I use that have Orion integrated within them FEN is the only one that keeps breaking after there is an update to the addon itself.

Any suggestions for them as I'm sort of a tester of their updates?

https://paste.ubuntu.com/p/trxH69zCSp/

https://paste.ubuntu.com/p/YhZKSzVw5J/

**Comment by Tikipeter** [comment]
Tell them they just need to add an extra indent to this code..

``
if module_name == 'orionoid': module_name = 'orion'
``

..in the 'sources' function within the init.py file. Where they are inserting that is wrapped in a try/except, and they are currently outside of that try/except after they insert that code. It needs to be 5 indents to match the code (20 spaces).

**Comment by Tikipeter** [comment]
Also, the other code they insert in that init file for the 'scraperNames' function, only needs 4 indents (16 spaces). This one is currently correctly inserted.

So, 5 indents for 'sources', 4 indents for 'scraperNames'.

**Comment by jjred1977** [comment]
Here is Orion's response:  I've decided to rewrite the integration code and make it
more generic. Orion will now check the code after integration to see if
there are any errors, and if so, try different indentations until it
works. This should reduce the integration errors for all addons in the
future.

Feel free to close the ticket. Thanks for your input!
