### ISSUE TITLE
Fen 2.6.11 error

### ISSUE THREAD

**Issue by GhostCod3** [Tikipeter/repository.tikipeter#750]
Hi, after update fen to 2.6.11 I keep getting error when I try to open it, I downgrade to 2.6.10 and everything works.

Android tv 10
Kodi 19.4 apk

**Comment by Liquidrag** [comment]
Seems like something is missing in 2.6.11.  I did a fresh install on a new kodi and couldn't open fen either, but if you downgrade to 10 then upgrade, you can open fen. I tried to do the fix @Tikipeter suggested from my post but it didnt work. #745
