### ISSUE TITLE
Error with Because you watched... TV Shows

### ISSUE THREAD

**Issue by Cloudman999** [Tikipeter/repository.tikipeter#751]
Hi @Tikipeter

I know someone reported having problems with 'Because you watched...' Trakt (for TV shows) in a previous issue #738

I am still getting this error message.

It seems to be working with 'Because you watched...' with Trakt Movies.

OS: Android TV OS 10 Fen: v.2.6.11

Kodi log: https://paste.kodi.tv/uxepakelez

Thank you for taking a look.
Cloudman999

**Comment by Tikipeter** [comment]
Does both the "Watched" and "In Progress TV Shows" menus work for you?

**Comment by xyzfre** [comment]
Hope this helps this is the error I get when going into (TV Shows) Because You Watched

**Comment by xyzfre** [comment]
![image](https://user-images.githubusercontent.com/49699869/161435432-d4afff78-e597-4040-9661-aad7fd7f4898.jpeg)

**Comment by xyzfre** [comment]
> Does both the "Watched" and "In Progress TV Shows" menus work for you?

On my end the (Watched) works fine but, (In Progress TV Shows) no error shows up blank

**Comment by xyzfre** [comment]
In Progress TV Shows ![image](https://user-images.githubusercontent.com/49699869/161435997-cbf77e47-e8a2-42c6-a209-dba02bce26be.jpeg)

**Comment by Tikipeter** [comment]
If someone could post here their `traktcache3.db` that might shed some light on what is happening here.

Maybe before doing that, delete the `traktcache3.db` and restart Kodi and see if that has any effect.

**Comment by Cloudman999** [comment]
> 

Hi @Tikipeter 


> Does both the "Watched" and "In Progress TV Shows" menus work for you?

The "Watched" Shows menu works, but the "In Progress TV Shows" menu returns no entries.

Regards Cloudman999

**Comment by Cloudman999** [comment]
> 



> If someone could post here their `traktcache3.db` that might shed some light on what is happening here.
> 
> Maybe before doing that, delete the `traktcache3.db` and restart Kodi and see if that has any effect.

I deleted the traktcache3.db and restarted Kodi.
The "Watched" TV Shows works but the "In Progress TV Shows" returns no entries.

Sorry can't post my 'traktcach3.db' file, as I am writing this reply on my phone, and the .db file is on my other system

Regards Cloudman999

**Comment by Tikipeter** [comment]
I need someone with the "Because You Watched"/"In Progress TV Shows" bug to please install this build below. Then:

1. Go into Tools->Clear Databases & Clean Settings Files->Clear Trakt Cache.
2. Navigate into TV Shows->Because You Watched...
3. Navigate into TV Shows->In Progress TV Shows.
4. Go to Tools->Changelog & Log Utils->Upload Kodi Log to Pastebin.
5. Paste here the link given in the kodi dialog.
6. Cross fingers this sheds some light on the situation, as at the moment I have no idea why it isn't working for some...


[plugin.video.fen-2.6.12a.zip](https://github.com/Tikipeter/repository.tikipeter/files/8406884/plugin.video.fen-2.6.12a.zip)

**Comment by Cloudman999** [comment]
> 



> I need someone with the "Because You Watched"/"In Progress TV Shows" bug to please install this build below. Then:
> 
> 1. Go into Tools->Clear Databases & Clean Settings Files->Clear Trakt Cache.
> 2. Navigate into TV Shows->Because You Watched...
> 3. Navigate into TV Shows->In Progress TV Shows.
> 4. Go to Tools->Changelog & Log Utils->Upload Kodi Log to Pastebin.
> 5. Paste here the link given in the kodi dialog.
> 6. Cross fingers this sheds some light on the situation, as at the moment I have no idea why it isn't working for some...
> 
> [plugin.video.fen-2.6.12a.zip](https://github.com/Tikipeter/repository.tikipeter/files/8406884/plugin.video.fen-2.6.12a.zip)

Hi @Tikipeter 

Followed all your steps above.

Navigated into TV Shows->Because You Watched...

and that returned results!


Navigated into TV Shows->In Progress TV Shows.

came up with the fen error again.

Here is the link in the dialog box...

https://paste.kodi.tv/gonususini

Cheers Cloudman999

**Comment by Tikipeter** [comment]
Good job @Cloudman999 .

This will likely be a big help for me to see what is happening.

**Comment by Tikipeter** [comment]
Please install the following build and re-do the following 3 steps:
1. Go into Tools->Clear Databases & Clean Settings Files->Clear Trakt Cache.
2. Navigate into TV Shows->Because You Watched...
3. Navigate into TV Shows->In Progress TV Shows.

Let me know if both menus are working now...
Hopefully no need for a log this time.

[plugin.video.fen-2.6.12b.zip](https://github.com/Tikipeter/repository.tikipeter/files/8413849/plugin.video.fen-2.6.12b.zip)

**Comment by Cloudman999** [comment]
> Please install the following build and re-do the following 3 steps:
> 
> 1. Go into Tools->Clear Databases & Clean Settings Files->Clear Trakt Cache.
> 2. Navigate into TV Shows->Because You Watched...
> 3. Navigate into TV Shows->In Progress TV Shows.
> 
> Let me know if both menus are working now... Hopefully no need for a log this time.
> 
> [plugin.video.fen-2.6.12b.zip](https://github.com/Tikipeter/repository.tikipeter/files/8413849/plugin.video.fen-2.6.12b.zip)

Sorry @Tikipeter 
I am not at home just now, but will try out the steps when I get back, ok?

Cheers Cloudman999

**Comment by Cloudman999** [comment]
> Please install the following build and re-do the following 3 steps:
> 
> 1. Go into Tools->Clear Databases & Clean Settings Files->Clear Trakt Cache.
> 2. Navigate into TV Shows->Because You Watched...
> 3. Navigate into TV Shows->In Progress TV Shows.
> 
> Let me know if both menus are working now... Hopefully no need for a log this time.
> 
> [plugin.video.fen-2.6.12b.zip](https://github.com/Tikipeter/repository.tikipeter/files/8413849/plugin.video.fen-2.6.12b.zip)

Hi @Tikipeter 

Great news!
I installed your latest version of Fen.
 Followed your steps after installing.

Navigated into TV Shows->Because You Watched...

Working! 😀👍

Navigated into TV Shows->In Progress TV Shows...

Working! 😀👍👍👍

Well done @Tikipeter 👏👏👏

Thank you so much for fixing these issues!

Kind regards Cloudman999

**Comment by Tikipeter** [comment]
I appreciate you taking the time to install the test builds and supply the log when needed.
Unfortunately because you have done this (installed from zip), Kodi has discarded the "link" Fen had with my repo, meaning when the new version comes out you will not get the update automatically. So when the update comes out, I will let you know here, and then you just need to go into the Tikipeter repository and re-install Fen from there. That will re-establish the "link" with the repo.

**Comment by Tikipeter** [comment]
@Cloudman999 
Fen version `2.6.13` was just released.
Navigate to the Tikipeter repository and re-install Fen from there and that should then re-link Fen to the Tikipeter repo so as to ensure you get future updates correctly.

**Comment by Cloudman999** [comment]
> I appreciate you taking the time to install the test builds and supply the log when needed. Unfortunately because you have done this (installed from zip), Kodi has discarded the "link" Fen had with my repo, meaning when the new version comes out you will not get the update automatically. So when the update comes out, I will let you know here, and then you just need to go into the Tikipeter repository and re-install Fen from there. That will re-establish the "link" with the repo.

Thanks for the explanation @Tikipeter 
Appreciate your update.

Cheers Cloudman999

**Comment by Cloudman999** [comment]
> @Cloudman999 Fen version `2.6.13` was just released. Navigate to the Tikipeter repository and re-install Fen from there and that should then re-link Fen to the Tikipeter repo so as to ensure you get future updates correctly.

Thank you @Tikipeter . I cannot update to the latest Fen version tonight, as I am not able to access the system from home.

Will need to update in the morning.

Many thanks for fixing up the issues.

Kind regards Cloudman999

**Comment by xyzfre** [comment]
Thank you Tikipeter for fixing this issue gave it a test run this morning both sections are working great again (Fen is the BEST)🙌🏼
