### ISSUE TITLE
old issue with trakt progress

### ISSUE THREAD

**Issue by ananias47** [Tikipeter/repository.tikipeter#752]
sorry my friend i dont know how to reopen an old issue i have the latest version of fen

Hi i have a strange problem on trakt progress. I have two trakt accounts The first account give me results on progress .The second account give me no results(blank) with no error. in other addons works great so there is no an account problem

**Comment by Tikipeter** [comment]
I would say you would have to completely revoke your trakt credentials in My Accounts, save those revoked settings in both My Accounts and Fen, and then re-auth Trakt in My Accounts and make sure it saves in both my accounts and Fen and then Clear Trakt cache in Fen.

If that doesn't work I'd just use one of the addons you say is working for you.
