### ISSUE TITLE
another old issue

### ISSUE THREAD

**Issue by muzikherif** [Tikipeter/repository.tikipeter#753]
After the last update the issue which i was mentioned before => https://github.com/Tikipeter/repository.tikipeter/issues/726 started again, interestingly seems like no one getting this error except me.I got this error at different series watched until now not for one episode or serie.I dont know what should i do or what i m doing wrong.Please help me.Here is the log may you need again.
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/8405651/kodi.log)

**Comment by Tikipeter** [comment]
I would revoke Trakt auth in My Accounts, making sure to hit OK after done.
Then resync My Accounts settings with Fen.
Then go into My Accounts settings and re-auth Trakt, making sure to hit OK after done.
Then resync My Accounts settings with Fen again.

**Comment by muzikherif** [comment]
Strangely i m awared that when i connect with a vpn to the another country connection aborted error is gone.Without vpn it comes back.I m connecting from Turkey and it is so ridiculous i can access in every way to the trakt but just toward to the end of videos i m getting this trakt error.Is it could be something about fen? There was no such thing until recent updates

**Comment by Tikipeter** [comment]
No. Not likely Fen related.
