### ISSUE TITLE
Watched Problem

### ISSUE THREAD

**Issue by Skoukoubagia** [Tikipeter/repository.tikipeter#754]
First, I really feel like an asshole for reporting things to a wonderful free piece... But still I hope you want to hear it.

So since the first implementation of date watched something is going wrong, my trakt watch history
![Screenshot_20220405-033614](https://user-images.githubusercontent.com/88809070/161655735-14a0e868-6248-4042-85f1-c5f8959fc079.jpg)

And my watched on Fen.
![Screenshot_20220405-033643](https://user-images.githubusercontent.com/88809070/161655762-e7cace6b-8ba3-41c9-bf4a-5b7ea38756e4.jpg)

**Comment by Tikipeter** [comment]
What's the question/Issue?

**Comment by Skoukoubagia** [comment]
Oh sorry, they are not the same. Last I watched two broke girls and from, and Fen thinks last is halo and moon knight, same goes for further behind

**Comment by Tikipeter** [comment]
The "Watched" menu in Fen is for shows that are fully watched (all episodes watched).
There is also the "In Progress TV Shows" which will show TV Shows that are being watched but not all episodes are watched.

Unless you have watched all episodes of Two Broke Girls, then it won't show in the "Watched" menu.

**Comment by Skoukoubagia** [comment]
Oo ok sorry I thought it was last episode watched. Thank you for the explanation and your time🙂
