### ISSUE TITLE
Enable kodi menu caching

### ISSUE THREAD

**Issue by derrgoo** [Tikipeter/repository.tikipeter#755]
Can you explain this setting because I do use jurialmunkey skins. Confused if I should turn on or off? Thanks

**Comment by xyzfre** [comment]
This is a really good feature Tikipeter I use AuraMod 1.1.7 Nvidia shield pro 2019 K19.4 and ever since you added this feature on my end I keep it disabled and the crashes have completely stopped thank you so much for all your hard work Tikipeter 👏🏼👏🏼

**Comment by Tikipeter** [comment]
Good to hear @xyzfre 

I wish it wasn't necessary, but Kodi is a strange creature in a lot of ways.

**Comment by derrgoo** [comment]
Thank you for the answer.
