### ISSUE TITLE
Trakt Next Episodes/In Progress bug

### ISSUE THREAD

**Issue by Liquidrag** [Tikipeter/repository.tikipeter#757]
Fresh install of kodi 19.4 and fen 2.6.13

I use "Next Episodes" religiously but the list does not populate as it should. I have the settings set to "recently watched" and "descending" with "Include Trakt Watchlist" enabled. Every time I click on Next Episodes" a different list shows up every time and it is definitely not what the list should be. 

I'm not sure if it is related but "watched" "In Progress TV Shows" and "In Progress Episodes" all come up blank in the "TV Shows" section. 

There is no error message that pops up so IDK if a log would help.

**Comment by xyzfre** [comment]
Have you tried ,Going into Tools->Clear Databases & Clean Settings Files->Clear Trakt Cache. Sometimes that helps

**Comment by Tikipeter** [comment]
I just don't care about anything to do with Trakt anymore.

Time to use another addon.
