### ISSUE TITLE
(Request) - Autoplay Cloud Source Only/Re-scarpe & Select Source Option in Context Menu

### ISSUE THREAD

**Issue by AshDroidG** [Tikipeter/repository.tikipeter#76]
Hi TikiPeter,
First thank you for making FEN so awesome and the time you spend developing the addon. I just had a request/suggestion.

1. Is it possible to setup an option in autoplay to Autoplay Cloud Sources only. I know I can set FEN to terminate scraping when cloud sources are found but what I am suggesting is that FEN autoplay only IF cloud sources are found. Let me explain where I am coming from. I love the autoplay option cause it eliminates unnecessary clicks however I prefer certain encode types and for that first scrape I always need to Re-Scrape and select Source first and then after selecting the source I want the next time it's in the Cloud Sources and works from there. Having an Autoplay From Cloud Sources only would Scrape the cloud sources and if nothing is found it would pull a list of all sources to select from. This would help the user select the exact source they want the first time and next time it would just play from the cloud scarping.

2. If the above is too tedious and needs a huge amount of work would it be possible to include Re-Scarpe & Select Source in the context menu. Right now the steps taken are Context Menu->FEN: Options->Playback Option->Rescrape & Select Source. Bringing Rescrape & Select Source out into the context menu would certainly work well for users who want the play a specific source and still use Autoplay.

Once again the addon is amazing, love your work and thank you.

**Comment by Tikipeter** [comment]
I can't see myself implementing either of those suggestions unfortunately.

**Comment by AshDroidG** [comment]
> I can't see myself implementing either of those suggestions unfortunately.

Ok. No problem. Thankyou for the quick response.
