### ISSUE TITLE
Fanart API time out 

### ISSUE THREAD

**Issue by xyzfre** [Tikipeter/repository.tikipeter#77]
Not sure if this is related to Yesterdays update but right after the update keep getting fanart API time out

**Comment by Tikipeter** [comment]
Hi xyzfre.

Turn extra fanart off in tikimeta settings like the notification suggests. Fanart.tv are having issues.

**Comment by xyzfre** [comment]
Thank you for this info wasn’t to sure if it was the update or I thought maybe I needed a new fanart API key ,, Much appreciate it and thank you for all your hard work

**Comment by Tikipeter** [comment]
It kind of was the update. I knew fanart.tv was having issues and that tikimeta should have been displaying that notification but it wasn't.

The update was to fix the fanart.tv notification error.
