### ISSUE TITLE
Crashing upon start up

### ISSUE THREAD

**Issue by JFG1000** [Tikipeter/repository.tikipeter#77]
Hi mate it's Gaddinator on Keybase, recently I've been getting several crashes upon kodi start up and sometimes a skin refresh of auramod, how do i go about getting a log from a kodi crash so i can post it to you? This has been happening for the past couple of updates now, reach out on Keybase if you would like as I know we quite often talk on there

Kind regards

**Comment by Tikipeter** [comment]
If Kodi crashes then upload the `kodi.old.log`. But there will likely be nothing in the log pertaining to this issue. It's a Kodi/Python bug that they need to fix. The only way to stop it happening is to turn off reuse language invoker in Fen.

**Comment by JFG1000** [comment]
Ok I'll upload it when it happens again where would i find the old log? Language invoker is already off, does enable kodi menu cache help?

**Comment by borygo77** [comment]
Same here. I was trying many things but never seen language invoker settings. Gonna try it now :) Thank you!

**Comment by JFG1000** [comment]
Closing this now as it seems to be running ok now
