### ISSUE TITLE
Request - Next Episode

### ISSUE THREAD

**Issue by JFG1000** [Tikipeter/repository.tikipeter#78]
Hey Tiki loving the next episode feature it's brilliant, is it possible to have an option to disable the "No next Episode" notification?

Thanks for all your hard work

**Comment by Tikipeter** [comment]
Done.

**Comment by JFG1000** [comment]
Thanks mate

**Comment by JFG1000** [comment]
Thanks @Tikipeter could you please check your Keybase when you get a second I've got something I want to run by you if I may
