### ISSUE TITLE
Years not working (movies) 

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#78]
Section years is broken, does not load, checked other addons (the Crew as a example), and it shows movies.
I think it got broken after the last update, just fyi.

**Comment by Tikipeter** [comment]
Thanks Tinuz97.
Fixed for next update.

**Comment by Tinuz97** [comment]
For the update, cleaned all cache, still empty.
Is it just me? Version 1.5.80, and Tiki meta version 1.1.28

**Comment by Tinuz97** [comment]
This is weird, cleaned all cache with openwizard (the new aftermath wizard from drinfernoo), and now years are working.
So that makes me wonder if clean all cache in Fen does work correct, no idea how in an log that, could you check it maybey? (clean all option in Fen)

**Comment by Tikipeter** [comment]
There was no need to clear cache to get years working again. I was rearranging code and accidently deleted a line of the years code. It should have begun working immediately upon update.
Nevertheless, I will make sure clear all cache is working. :)
