### ISSUE TITLE
Trakt progress not being recorded if stopped in middle [Log provided and followed all rules]

### ISSUE THREAD

**Issue by ShibajiCh** [Tikipeter/repository.tikipeter#8]
Hi @Tikipeter,

First of all I'm really glad that you're back with the amazing Fen addon in a more improved way.

I noticed a small issue that if I stop any movie or TV show in the middle then its progress is not recorded in Trakt. Instead it gets completely removed from Trakt. However, if I complete watching the movie or TV show then it gets marked as watched in Trakt properly. In the earlier versions this issue was not there. Could you please check and try to resolve the issue?

Here's my Kodi log:

https://paste.kodi.tv/cozalenana

Thanks and Regards,
ShibajiCh.

**Comment by Tikipeter** [comment]
>Instead it gets completely removed from Trakt.

What does this mean?

How are you checking whether the progress is being recorded? Through Kodi? Through the Trakt website? Through a third party Trakt application?

If you then press play on the movie/show, does it indeed offer a resume point?

**Comment by ShibajiCh** [comment]
> > Instead it gets completely removed from Trakt.
> 
> What does this mean?
> 
> How are you checking whether the progress is being recorded? Through Kodi? Through the Trakt website? Through a third party Trakt application?
> 
> If you then press play on the movie/show, does it indeed offer a resume point?

Hi @Tikipeter,

I check my Trakt progress by using this web based tool:

https://sharkykh.github.io/tppm/

The movie or TV show also gets removed from the In Progress list in Fen.

And, no, pressing play on the same movie or TV show later on doesn't provide a resume point.

Thanks and Regards,
ShibajiCh.

**Comment by AltFreq07** [comment]
I had a similar issue
Changing FEN -> Playback -> Movies/Episodes -> Automatically Resume Playback to "Always" fixed my problem and it now tracks the progress (locally I assume as FEN doesnt scrobble to Trackt)

**Comment by Tikipeter** [comment]
Fen does scrobble to Trakt. Has done for a long while.

**Comment by xyzfre** [comment]
Resume points and Trakt are working fine on my end using an Nvidia shield  most of the time  it’s on Trakt’s end

**Comment by ShibajiCh** [comment]
> Resume points and Trakt are working fine on my end using an Nvidia shield most of the time it’s on Trakt’s end

Hi @xyzfre,

I'm using an Nvidia Shield TV Pro too and the Trakt progress feature is not working if the video is stopped in the middle. Even changing the Automatically Resume Playback setting to Always like @AltFreq07 suggested, didn't work for me. However, if I watch a movie or TV show completely then it is getting marked as watched correctly. Also, no, it's not a Trakt issue as all other video addons are working perfectly with Trakt.

Thanks and Regards,
ShibajiCh.

**Comment by xyzfre** [comment]
Have you tried revoking Trakt and right after that clear settings and database , Trakt cache exit Kodi and then re-authorize sometimes this helps

**Comment by Tikipeter** [comment]
Not much more I can tell you at this point.

I'll include some logging in the next update to see if the code is failing somewhere. That is about all I can do now as the code works perfectly well for me. Setting Trakt resume points for both movies and episodes.

See if something shows in the log after the next update.

**Comment by ShibajiCh** [comment]
> Not much more I can tell you at this point.
> 
> I'll include some logging in the next update to see if the code is failing somewhere. That is about all I can do now as the code works perfectly well for me. Setting Trakt resume points for both movies and episodes.
> 
> See if something shows in the log after the next update.

Hi @Tikipeter,

I figured out the issue and resolved it by checking the log thoroughly. Actually the Kodi Trakt addon was installed long back in my setup, but I had kept it disabled and forgot about it. However, even though it was disabled it was interrupting with Fen's Trakt progress somehow. I'm not sure why. The solution was to either enable it and Exclude HTTP sources under its settings or completely uninstall it. I did the latter and Fen's Trakt progress started working perfectly. Apologies for missing this minor thing. Now everything works fine. You can close this ticket. Thanks a lot to you and @xyzfre for helping me figuring out the issue!

Thanks and Regards,
ShibajiCh.

**Comment by Tikipeter** [comment]
Good to hear it's working better now.
I'll add a check for whether the Trakt plugin is installed but disabled. Might save the next person a headache trying to sort out what's happening with their setup.

**Comment by xyzfre** [comment]
@ShibajiCh you're welcome and this is also great info for future issues to ask a person if they have it installed and disabled and wouldn't think of what you did ,good catch on your end a learning experience for all 👍🏼, by the way did you end up uninstalling it or changing the settings in the Trakt addon,, I haven't used it in years

**Comment by ShibajiCh** [comment]
> Good to hear it's working better now. I'll add a check for whether the Trakt plugin is installed but disabled. Might save the next person a headache trying to sort out what's happening with their setup.

Fine @Tikipeter. Thank you so much!

**Comment by ShibajiCh** [comment]
> @ShibajiCh you're welcome and this is also great info for future issues to ask a person if they have it installed disabled and wouldn't think of what you did ,good catch on your end a learning experience for all 👍🏼, by the way did you end up uninstalling it or changing the settings in the Trakt addon,, I haven't used it in years

Hi @xyzfre,

I checked by changing the settings as well as by completely uninstalling it. It worked both ways. However, finally I kept it uninstalled as I didn't need that Trakt addon anymore as I'm not using any local content at present.

Thanks and Regards,
ShibajiCh.
