### ISSUE TITLE
3 scrapers called 'Source1, Source2, Source3'

### ISSUE THREAD

**Issue by jjred1977** [Tikipeter/repository.tikipeter#80]
What are these for and how do I set them up?

**Comment by Tikipeter** [comment]
Hi jjred1977.

There are 5 of these scrapers now, so I'll add 'Source4, Source5' to your question (if you don't see these extra 2 scrapers, then you need to update Fen. Current version on github is 1.5.79).

These are scrapers that can each be assigned a file path local to your network for Movies or TV Shows. If you have a bunch of movies in a folder on your network, you can assign one of these scrapers to scrape that folder and present the results for playback in Fen.

If you don't have any downloaded media in folders you wish to scrape, just disable these scrapers or leave them blank.

For more info on these, navigate in Fen to Tools->Tips for Fen Use->NEW!!! Folder Scrapers.

**Comment by jjred1977** [comment]
Thank you for clarifying this.
