### ISSUE TITLE
Request for thumbcache.cleaner

### ISSUE THREAD

**Issue by xyzfre** [Tikipeter/repository.tikipeter#81]
First of all thank you for all your amazing work with Fen it’s been working perfect ,,Small request if it’s not too much to ask for would it be possible to bring back this program [thumbcache.cleaner] it was a very useful tool

**Comment by Tikipeter** [comment]
You want it in the repo, or just a zip of it here?

**Comment by xyzfre** [comment]
It would be good to have it back in the repo but I’ll settle for whatever makes it easier for you

**Comment by Tikipeter** [comment]
In the repo now. You may need to refresh the repo and also maybe wait a while for it to show.

**Comment by xyzfre** [comment]
Thank you @Tikipeter really appreciate it 💯
