### ISSUE TITLE
Fen not recognising all seasons of a particular show

### ISSUE THREAD

**Issue by dm2912** [Tikipeter/repository.tikipeter#81]
Ok, this is a weird one.

The show Terrace House 2019-20, its now into its 3rd part (season)

Trakt link> https://trakt.tv/shows/terrace-house-tokyo-2019-2020
TVDB Link> https://www.thetvdb.com/series/terrace-house-tokyo-2019

But Fen is only finding one season. (the first part), the first 12 episodes. 

weird.....

**Comment by Tikipeter** [comment]
Im getting 3 'Parts' for a total of 25 episodes for that show.

Highlight the show, bring up the context menu and select Add/Remove-->Remove-->Remove from Cache. Fen will recache info for the show, and hopefully it will display the correct info for you.

**Comment by dm2912** [comment]
aha
