### ISSUE TITLE
Request Thumbnail Cleaner

### ISSUE THREAD

**Issue by Cloudman999** [Tikipeter/repository.tikipeter#82]
Hi @Tikipeter 
I am using the Beta 1 of Kodi 20. I installed your Thumbnail Cleaner, but unfortunately, it doesn't seem to work with Kodi 20.

System: Chromecast with Google TV (Android TV OS 12)
Kodi: 20 Beta 1

Are you planning to update it so it works with Kodi 20?

I'd be ever so grateful
Kind regards
@Cloudman999

**Comment by Tikipeter** [comment]
Should work with `1.0.04` just uploaded to repo.

**Comment by Cloudman999** [comment]
Thank you @Tikipeter 
I uninstalled Kodi 20 Beta 1 yesterday and went back to Kodi 19.4, so will reinstall Kodi 20 again and try it.

May be tomorrow until I can do this though.

Kind regards
@Cloudman999

**Comment by Cloudman999** [comment]
Hi again @Tikipeter 
I am pleased to report that your updated version of Thumbnail Cleaner works great with Kodi 20 Beta 1.

Many thanks for your great Fen add-on and support here on Github!

Kind regards
@Cloudman999
