### ISSUE TITLE
Additional ways to search for content other than trakt lists

### ISSUE THREAD

**Issue by jjred1977** [Tikipeter/repository.tikipeter#83]
I was wondering if there was a way to search by year and by genre of movies in an addon for example, Horror movies from 1980?  If not, is that something very hard to code into an addon?

**Comment by Tikipeter** [comment]
Hi jjred1977.

"Discover", on the Fen Main Menu, will do what you are after here, along with many other filters to get lists you want.
Read about Discover in the "Help" Section of Discover, or in Fen Tips from the Tools menu.

Briefly, from your question above, you would go to DISCOVER: Movies and enter the following:

* Year Start: 1980
* Year End: 1980
* Include Genres: Horror

(Set Year End to 1989 to include Movies from the whole decade of the '80s.)

Then scroll to the bottom and select "Save & Browse Results For:" to browse the list Fen will make, or select "Export Search" to save that list to Fen's Main (Root) Menu, Movie Menu or TV Show Menu. You can rename the list before you finish exporting it.

Let me know if you have any questions.
