### ISSUE TITLE
Results Display Format - Question

### ISSUE THREAD

**Issue by JFG1000** [Tikipeter/repository.tikipeter#83]
Hi there thankyou for your most recent update, would it be atall possible to have the white highlight removed as default when selecting a link and have it like it used to be before when we could have a contrast option as its so much easier on the eyes on the second image, I've attached 2 images to try show you what I mean. Kind regards

![20221205_221246](https://user-images.githubusercontent.com/76907836/205756087-f5cbf2a9-7bed-4f4d-9154-fcdb636c8f16.jpg)

![172e059d43fe1a43](https://user-images.githubusercontent.com/76907836/205756109-75b54ea9-7ef9-484b-b31e-54cce730735d.jpg)

**Comment by ivarbrandt** [comment]
Tools > Settings > Results tab > under Display section > Results Display Style > click List

**Comment by JFG1000** [comment]
I have this is how it looks by default now

**Comment by JFG1000** [comment]
On the most recent update its completely changed it now looks like this when selecting "list"

**Comment by ivarbrandt** [comment]
Oh ok. I haven't updated yet so I haven't run into this.

**Comment by Tikipeter** [comment]
Get better eyes.

**Comment by Tikipeter** [comment]
.... or try `3.0.26` if you're stuck with the eyeballs God gave you.

**Comment by ivarbrandt** [comment]
I shouldn't have laughed but I definitely laughed lmao

**Comment by JFG1000** [comment]
@Tikipeter "user has shitty eyeballs" 🤣🤣👌🏻 I speak to you through Keybase quite often so I do get your banter it's all good 🤣 thanks for the update setting its really appreciate it, P.S I do actually have shitty eyeballs at the moment, I'm currently fighting an eye infection as coincidental as that may seem 🤣
