### ISSUE TITLE
NEW FEATURE: Sub Clean for subtitles

### ISSUE THREAD

**Issue by sasagr** [Tikipeter/repository.tikipeter#84]
Hi Tikipeter! Very happy to see you around again. I hope all is good at your end.
Since you provide a subtitles feature in Fen, I was wondering if you could be interested to add a cleaning feature, for those that they dont have a subtitles premium account, and want to remove the ads.
I know a couple of projects that probably could be used/added to the addon. Not sure which one could easier to implement.
https://github.com/brianspilner01/media-server-scripts/blob/master/sub-clean.sh
https://pypi.org/project/subclean/
Cheers

**Comment by sasagr** [comment]
Can you use their api with user login so vip users can take advantage of the premium?

**Comment by tundrablasen** [comment]
Would be the a4ksubtitles code any help? Instead of the opensubtitles api.
