### ISSUE TITLE
Trakt Error response timeout 

### ISSUE THREAD

**Issue by xyzfre** [Tikipeter/repository.tikipeter#85]
Just started happening a little while ago and I have the same set up for a while now ,I use widgets from Trakt Collections ,Watchlist etc.. from Fen ,, but just started getting a Notification that says error Trakt response and some sections of my home skin widgets won’t load but if I go in the addon to those Trakt sections they open up with no problem ,, Everything was fine to a couple hours ago,, Thank you for your help really appreciate it

**Comment by dm2912** [comment]
This happened to me earlier, but then sorted itself out.

I think trakt has gone to pot tonight though because nothings playing in Fen at all, Seren cant load any trakt lists, and ive just had hundreds of library items unwatch themselves.

**Comment by Tikipeter** [comment]
Yep, nothing I can do about Trakt timeouts. We just have to wait for their server to stabilize.

**Comment by xyzfre** [comment]
Weird thing is it’s only happening with TV Shows Trakt collections on home screen widgets but for example I try with Seren and the error Trakt timeout doesn’t happen ,sorry to bother for any inconvenience I love Fen

**Comment by Tikipeter** [comment]
OK. Let me know the skin you are using and approx. how many items you have in your Trakt TV Show Collection and I will see if I can make it happen. It happened once for me over the last couple of days with a trakt widget, but hasn't happened since.

Also, let me know your Trakt settings for the following in 'Settings->Trakt->Trakt Cache':

* Trakt Cache Duration?
* Refresh Trakt Cache on Each Kodi Startup?

Also:
Does the widget reload successfully after you watch something through Kodi?
Does the widget reload successfully if you reload the skin?

**Comment by xyzfre** [comment]
OK so Earlier I had change the home screen  widgets from Trakt Collection to pull from Seren to see if the same error would occur  and it didn’t,, Now I added them back when you responded to pull from Fen so I can check ,,and now everything is fine the error  stop showing up ,, So far I have exited Kodi 3 times and all good no timeout error🤞🏼 Removing the widgets and adding them back sorted it out        (AuraMod)                               Trakt cache duration (1 hr).                                    Refresh Trakt Cache on each Kodi startup (off).                                                                       Max Trakt List Items (40).                                    (42 TV shows but I had more in the past LOL)

**Comment by xyzfre** [comment]
Once again thank you for your Time and your amazing work with Fen

**Comment by dm2912** [comment]
Trakt has been having major issues. A lot of people had problems with Seren/Trakt on reddit last night. Ive had a nightmare with trakt, both seren and fen last night refused to do things. At one point last evening Kodi randomly removed about 500 play counts from various things. 

im not sure its solely trakts fault though, everything has been messed up by tvdb who have created countless knock on issues.

that said, exporting to library and using library to populate widgets is a much better solution in the grand scheme of things as its not then dependant on a trakt/tvdb etc connection. Or use something like TMDBHelper to pull widgets (which is mega fast with track) and install player files for fen.
