### ISSUE TITLE
IMDB Lists are empty

### ISSUE THREAD

**Issue by pwhiteheadonline** [Tikipeter/repository.tikipeter#85]
I can open IMDB Lists and see all the Lists but when I click on a list it comes empty. This is for every list on my IMDB account.
Doing the same in Ezra shows the list. Happened recently. Thankyou for working hard!

**Comment by Tikipeter** [comment]
This issue has been seen and will be addressed in the next update.

But it needed to be closed as there was no log posted, as per the rules.

**Comment by pwhiteheadonline** [comment]
THANK YOU SO MUCH! I should have read the log post, I'm sorry.
I'm so happy it will be resolved, your addon is the best bar none! the speed is just out of this world!
Will wait patiently. Thanks Tikipeter
