### ISSUE TITLE
Add on name not displayed

### ISSUE THREAD

**Issue by sasagr** [Tikipeter/repository.tikipeter#86]
Hi. I just installed Fen on kodi 20 rc1 on my Apple TV and all seems working fine except the name of the addon not showing. Please let me know if you need a full log. 
Sorry the attached photo did not go through 
There is a message instead of the name
$PARAM[single_label]

**Comment by sasagr** [comment]
Here the log
https://paste.kodi.tv/lideqaqilu

**Comment by Tikipeter** [comment]
Interesting. I'll download RC1 and have a look.

**Comment by sasagr** [comment]
The issue is solved with the RC2 and Fen v. 3.0.32

**Comment by Tikipeter** [comment]
I wonder what it was? I could never get it to happen in testing.

**Comment by sasagr** [comment]
I don’t know but I had it in both my two Apple TV. Today I updated both to RC2 and it disappeared. Maybe it was only related to the Apple TV build.

**Comment by Tikipeter** [comment]
>Maybe it was only related to the Apple TV build.

I think that might be the case. There's been a couple of issues so far with Nexus 20 that have been Apple TV specific.
