### ISSUE TITLE
Internal scraper not hidden anymore 

### ISSUE THREAD

**Issue by edb64** [Tikipeter/repository.tikipeter#86]
I remember a while back when you added a feature to hide internal scraper from scraping progress dialog when a Furk or EasyNews account was not present or used. It used to only show external scraper progress for me since I only added RD & PM accounts. Recently I have noticed that it is no longer hiding the Internal scraper progress and I can't find a setting to change that. It's not really a problem so much as a question really. Thanks in advance for any info you can give me about this 👍

**Comment by Tikipeter** [comment]
Hi edb64.

You probably have one of the Internal Scrapers active. If any of the following are activated, you will see the 'Internal' Progress:

* Furk
* Easynews
* PM-Cloud
* RD-Cloud
* Local Library
* Downloads
* Sources 1-5

I tested just now, and with all of the above scrapers off, I didn't see the Internal Ptogress.

Let me know if you have ALL of these disabled and still see the Internal Progress.

**Comment by edb64** [comment]
OK, I had RD & PM cloud enabled. Thanks for the quick reply!
