### ISSUE TITLE
Disable content look up 

### ISSUE THREAD

**Issue by IG2022** [Tikipeter/repository.tikipeter#87]
Hey, I just wanted to find out what the option in playback settings for "disable content look up before playback" does? I've enabled it and it feels like scraping is slightly faster when searching my real debrid cloud. (I have my settings to search internal before external.) Anyway just wanted to find out what it's for. 

Thanks!

**Comment by Tikipeter** [comment]
If enabled (meaning content lookup is disabled) then Kodi won't send a HEAD request before playback to get the MIME TYPE (type of file) of the video file. It was included as a setting by me mainly to try and improve Easynews playback.

It won't affect scraping speed, as it is used after you select a file for playback.

**Comment by IG2022** [comment]
> If enabled (meaning content lookup is disabled) then Kodi won't send a HEAD request before playback to get the MIME TYPE (type of file) of the video file. It was included as a setting by me mainly to try and improve Easynews playback.
> 
> It won't affect scraping speed, as it is used after you select a file for playback.

Thanks for answering this for me! I appreciate it.
