### ISSUE TITLE
Real Debrid & Premiumize cloud enhancement request.

### ISSUE THREAD

**Issue by Sovilor** [Tikipeter/repository.tikipeter#87]
Hello, for now Fen (Cloud Storage) shows all the files in Real Debrid cloud (downloaded, still downloading, failed, dead). 
If it's possible please change it to show the working downloaded files only.

One more thing, a year ago, about adding support for Alldebrid you said it's not possible because of some api request limit issue, will you please have a look again, it looks like something changed because Seren is supporting it now.

Thank you

**Comment by Tikipeter** [comment]
Hi Sovilor.

I saw Seren had added Alldebrid, I plan to take a look at it soon.

Let me look into the Cloud Storage issue and see what's possible. :)

**Comment by Tikipeter** [comment]
The RD Cloud will be fixed to show only live downloaded files for next update.

I've looked at the Alldebrid API documentation, and they do now offer an endpoint to test multiple hashes at once, so I should be able to add Alldebrid to Fen. I'm not great at these things so you'll need to give me a little time to get it up and working.

**Comment by Sovilor** [comment]
@Tikipeter thank you very much,
That will make Fen perfect

**Comment by Tikipeter** [comment]
Done for next update. Report any issues by starting a new 'Issue'.
