### ISSUE TITLE
request:

### ISSUE THREAD

**Issue by rrosajp** [Tikipeter/repository.tikipeter#88]
hi,Tikipeter
    can u pl incorporate notification when player Not Start playing video; i observed when playing episode some time link not start plying and all dialog box closed but not playing video and focus back to the episode list . i hope ,i explain the issue right.
i really appreciate yr work.
thanks.

**Comment by Tikipeter** [comment]
Hi rrosajp.

Whilst this sounds like an easy thing to do, I don't think it would be because of how Kodi works in this area. Let me see if it's possible..

**Comment by Tikipeter** [comment]
Unfortunately, I cannot find a practical way to implement this.
