### ISSUE TITLE
Sorting and filtering not working in Fen 3.0.29

### ISSUE THREAD

**Issue by LITUATUI** [Tikipeter/repository.tikipeter#89]
Updated Fen and now sorting and filtering is not working in Fen 3.0.29.

I noticed this because I have Fen setup to prioritize HDR, AV1 and HEVC, but now Fen auto plays x264 (AVC) videos even when AV1 and HEVC sources are available.

**Comment by Tikipeter** [comment]
If you have them all set to prefer then the results will likely end up being sorted AV1, then DV, then HDR, then DV, then HEVC.

Does the AVC x264 file that plays have any of the other infos present?

**Comment by Tikipeter** [comment]
I've spotted an error in the code logic that will hopefully fix this.

I'll include it next update (shouldn't be too long away).

**Comment by Tikipeter** [comment]
Keep in mind though that the sort order I wrote above still applies, so it's not perfect.

I need to re-write the sorting code, but it makes my head hurt a bit and I'm not sure I can pull it off well enough.

But it should be better with the fix coming.

**Comment by LITUATUI** [comment]
Yeah, I noticed that the sorting wasn't perfect before.

Example of three file options:

4K HEVC
1080p AV1
1080p AVC

Fen will choose the 1080p AV1 file because of the better codec. However, I think that in this case the 4K HEVC file is the best option available and that AV1 should only be prioritized against other codecs, not against resolution or HDR type.

I think that higher resolution should always be the first priority, then HDR type, codec and finally size.

If the priority order could be customized by the user it would be great. I would configured like this:

1. Resolution (4K, 1080p, 720p)
2. HDR type (DV, HDR, None)
3. Codec (AV1, HEVC, AVC)
4. Size (Higher to lower)

**Comment by Tikipeter** [comment]
>...it makes my head hurt a bit and I'm not sure I can pull it off well enough.

**Comment by LITUATUI** [comment]
It would be a 4-pass search.

First, short files by resolution
Second, for each resolution short files by HDR type
Third, for each resolution and HDR type short files by codec
Fourth, for each resolution, HDR type and codec short files by size

If it's too much work, maybe it's a good idea to copy the shorting method of Umbrella. It's not exactly like this, but it's good nonetheless.

**Comment by Tikipeter** [comment]
I very much doubt Umbrella has any shorting code. I don't even know wtf shorting is.

And I didn't say it was too much work.

**Comment by LITUATUI** [comment]
Typo sorry, I meant sorting.
