### ISSUE TITLE
Kodi Crashing with Recent Update

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/repository.tikipeter#9]
It looks like update `3.0.5` is causing Kodi to crash on multiple devices.

The code that is causing this crash is a change in the `type` of a specific setting in Fen: `ignore_results_filter`.

Settings are changed like this by addon dev's fairly frequently, without this issue arising. As such, I have absolutely no idea why this would suddenly start happening. I also did not have this happen on the 4 installs of Kodi I put this update on before releasing. They include Windows and LibreELEC installs.

There are hopefully a few ways to fix this issue.

* Hope a Fen update that has been posted gets through on your system. This has renamed the problematic setting, and that will hopefully stop Kodi freaking out about it.
* Quickly go in to Fen's settings and change the setting `Ignore All Filters When No Results Available` to something else. Then restart Kodi. Thanks ivarbrandt.
* If it's quicker for you, do the above but **Disable** Fen first, so you have more time to change the setting.
* The PARTIAL NUKE option. As above, but navigate into the `plugin.video.fen` folder and only delete the `settings.xml` file. You will still need to re-enter all settings.
* The NUKE option. Navigate to your user userdata/addon_data folder and delete the `plugin.video.fen` folder. This will delete your settings and cache objects from Fen. Restart Kodi and all SHOULD work again. You will need to re-enter all settings.

These are quite possibly the only options available.

My apologies for this happening, but there's no actual issue in the Fen code that is causing this. The code is fine. The issue is I have no idea why Kodi has decided to behave this way simply because a setting's `type` has been changed.

**Comment by ivarbrandt** [comment]
Something that fixed it for me is disabling Fen, go into the Fen's settings and change "Ignore All Filters When No Results Available" to anything other than the default, hit OK, enable Fen, restart Kodi. I think it worked because this rewrites the settings.xml file.

**Comment by Tikipeter** [comment]
That's true ivarbrandt. That's a good way to do it if Kodi stays open long enough to do that.

**Comment by xyzfre** [comment]
This also worked for me🤞🏼🤞🏼 had to be quick with it I set it to prompt,, my question is now can I go back and set the setting to off or will it cause it to start crashing again

**Comment by Tikipeter** [comment]
Once the setting has been changed, it should be fine to set it to whatever you want from there.

**Comment by Tikipeter** [comment]
Anyone NOT have this happen on their install?
I tested 4 installs and none of them had this issue. I wasn't however able to test an Android system.
Was it an Android install for everyone that this happened to?
I KNOW I will need to do this in the future (change a setting's `type`). So it would be very beneficial to find out what OS was being used when this Kodi bug was triggered by my settings change.

**Comment by ivarbrandt** [comment]
> That's true ivarbrandt. That's a good way to do it if Kodi stays open long enough to do that.

Can confirm. Had to haul ass to disable it after start-up.

**Comment by xyzfre** [comment]
On my end I use a Nvidia shield 2019 Pro so definitely android

**Comment by ivarbrandt** [comment]
I use a NVIDIA Shield TV Pro too so Android as well

**Comment by Tikipeter** [comment]
If it's quicker to disable Fen, and then have more time to change that setting, then that's another option. Some have had success with that as well.

**Comment by xyzfre** [comment]
My apologies for asking this on this post because I know it's off topic ,,but I noticed Maximum Active Threads by default it's 60 do you recommend a different number when using android for this  settings

**Comment by chibidaru** [comment]
> Anyone NOT have this happen on their install? I tested 4 installs and none of them had this issue. I wasn't however able to test an Android system. Was it an Android install for everyone that this happened to?

For me it happened on my Windows 11 install but NOT on my Android install. Just FYI

**Comment by Tikipeter** [comment]
> My apologies for asking this on this post because I know it's off topic ,,but I noticed Maximum Active Threads by default it's 60 do you recommend a different number when using android for this settings

Not really. Before this setting, if you had 200 items in a list, Fen would fire off the 200 calls for info all at the same time (most addons do this). This is just a way to cap how many requests for info are being sent at one time. It will get to 60 and then stay at 60 as requests come and go.

So to answer your question, 60 is a pretty low number as it is compared to the previous unlimited number.

**Comment by Tikipeter** [comment]
> For me it happened on my Windows 11 install but NOT on my Android install. Just FYI

I was afraid of that lol.

**Comment by Tikipeter** [comment]
I'm hoping 3.0.7 fixes it (released). Otherwise best to try one of the options above.

**Comment by xyzfre** [comment]
> > My apologies for asking this on this post because I know it's off topic ,,but I noticed Maximum Active Threads by default it's 60 do you recommend a different number when using android for this settings
> 
> 
> 
> Not really. Before this setting, if you had 200 items in a list, Fen would fire off the 200 calls for info all at the same time (most addons do this). This is just a way to cap how many requests for info are being sent at one time. It will get to 60 and then stay at 60 as requests come and go.
> 
> 
> 
> So to answer your question, 60 is a pretty low number as it is compared to the previous unlimited number.

Thank you for the GREAT info on this setting I've gotten some mix feedback but the way you explained it makes a lot of sense

**Comment by ivarbrandt** [comment]
> > > My apologies for asking this on this post because I know it's off topic ,,but I noticed Maximum Active Threads by default it's 60 do you recommend a different number when using android for this settings
> > 
> > 
> > Not really. Before this setting, if you had 200 items in a list, Fen would fire off the 200 calls for info all at the same time (most addons do this). This is just a way to cap how many requests for info are being sent at one time. It will get to 60 and then stay at 60 as requests come and go.
> > So to answer your question, 60 is a pretty low number as it is compared to the previous unlimited number.
> 
> Thank you for the GREAT info on this setting I've gotten some mix feedback but the way you explained it makes a lot of sense

Agreed. I thought it was related to scraping performance. So I turned it off completely. I'm gonna set it to 60 and see if that helps with my Trakt issues.

**Comment by xyzfre** [comment]
> Something that fixed it for me is disabling Fen, go into the Fen's settings and change "Ignore All Filters When No Results Available" to anything other than the default, hit OK, enable Fen, restart Kodi. I think it worked because this rewrites the settings.xml file.

This method right here works like a charm even with Fen enabled I had enough time to change the setting ,keep in mind if you're using A Skin don't even wait to the widgets load just go straight to video add-ons and you're good to go👍🏼

**Comment by Tikipeter** [comment]
> This method right here works like a charm even with Fen enabled I had enough time to change the setting ,keep in mind if you're using A Skin don't even wait to the widgets load just go straight to video add-ons and you're good to go👍🏼

Good info. Thanks for that. 🥇

**Comment by Skates1616** [comment]
3.0.7 did not fix, I actually waited to update to this version and it still crashed.  Worked after I did the Ignore fix listed above.

This was on a Fire Stick 4K Max.

**Comment by ReaLx3m** [comment]
Trying to update from 3.0.04 to 3.0.07 made FEN dissapears from Video Addons. After going to the repo and trying to install from there, it says installation failed now.

Deleting settings.xml still crashing. When deleting the addon folder, and then installing fen through the repo it crashes the moment addon is installed. Cant make it in time to try the third solution.  

Maybe it has some conflict with a Skin used? Using Aeon Nox Silvo here.

**Comment by xyzfre** [comment]
After a crash did you try deleting the (userdata)/addon_data folder plugi.video.fen and then restarting Kodi that should also do the trick

**Comment by ReaLx3m** [comment]
Yep, i mentioned that in the post above. Not doing the trick, crashing the moment fen is installed

**Comment by xyzfre** [comment]
My apologies I missed understood when you said (When deleting the addon folder, and then installing fen through the repo) because the user/data folder is only the settings/auth./API etc..so you shouldn't have to reinstall Fen

**Comment by ReaLx3m** [comment]
> My apologies I missed understood when you said

No need to apologize, i updated the original post. It was my bad, deleting wrong folder , 2 am not the brightest of times, thanks for making me question myself and get to the right location :).

**Comment by Tikipeter** [comment]
So no more crashes @ReaLx3m after deleting the Fen userdata folder?

**Comment by ReaLx3m** [comment]
> So no more crashes @ReaLx3m after deleting the Fen userdata folder?

Yep, just finished setting it up. Looks good so far.

**Comment by ReaLx3m** [comment]
@Tikipeter Oh and welcome back wayward son :)

**Comment by xyzfre** [comment]
> Yep, i mentioned that in the post above. Not doing the trick, crashing the moment fen is installed again.
> 
> 
> 
> Edit: No wait, i lied. didnt do that one looks like. Will give it a shot now.
> 
> 
> 
> Edit2: Silly me, was deleting the folder from Kodi\addons. Looks like its fixed, no crash so far. Gotta set it up now and see.
> 
> Thanks for pointing it out.

You're welcome glad I was able to help out enjoy it's working GREAT 🥇 thank you @Tikipeter for this amazing addon

**Comment by Tikipeter** [comment]
In the only good news, I am 100% confident once you stop the crashes they will not start again. It's just having the time to race in and change that setting or disable Fen so you can change that setting.

`3.0.07` includes about the only other thing I could do to stop this from my side, so people unfortunately are just going to have to try each of the solutions from least disruptive to most disruptive until one works.

**Comment by 43v3rLoCo** [comment]
> Anyone NOT have this happen on their install? I tested 4 installs and none of them had this issue. I wasn't however able to test an Android system. Was it an Android install for everyone that this happened to? I KNOW I will need to do this in the future (change a setting's `type`). So it would be very beneficial to find out what OS was being used when this Kodi bug was triggered by my settings change.

This happened on my windows 11 laptop. After I read what was happening, I didn't chance it and disabled auto update on my android TV's before the .05 update took. Just went ahead and forced 1 of my android 11 TVs to update directly to .07 from .04 and it still crashed after trying to restart kodi. Had to do the method ivarbrandt mentioned and that worked. It did freeze up while I disabled fen at first so I had to force shut down kodi, but luckily the disabling took and then went in and changed the setting when I restarted again.

**Comment by ReaLx3m** [comment]
After going through deleting addon data folder for 3.0.07 to make it work, it started crashing again after updating to 3.0.08.

**Comment by ReaLx3m** [comment]
Am i in the minority here with the issue returning, or people still havent gotten around to updating from 07 to 08?

**Comment by xyzfre** [comment]
I updated as soon as it came out but luckily no crashing issues Came back on my end

**Comment by ReaLx3m** [comment]
Thanks for the input. Had to delete addon data folder again to make 08 work, guess will have to wait and see if it happens again to me when 09 is out.

**Comment by screen-power** [comment]
No solutions works for me on ATV4K with Kodi 19.4. Any help please ?

**Comment by ReaLx3m** [comment]
> No solutions works for me on ATV4K with Kodi 19.4. Any help please ?

If you cant make it work in any way(even reinstalling), then maybe try going back to 04. Since its not available anymore on the repo i uploaded it for you in case you dont have it saved - https://1drv.ms/u/s!AnmxUFF1zODFgb4ogSqyaqEnxCHOaA?e=iT2LQg

**Comment by screen-power** [comment]
> > No solutions works for me on ATV4K with Kodi 19.4. Any help please ?
> 
> If you cant make it work in any way(even reinstalling), then maybe try going back to 04. Since its not available anymore on the repo i uploaded it for you in case you dont have it saved - https://1drv.ms/u/s!AnmxUFF1zODFgb4ogSqyaqEnxCHOaA?e=iT2LQg

Great thank you that worked

**Comment by screen-power** [comment]
Was this fixed with 0.9 ? 

Thanks
