### ISSUE TITLE
Enhancement ( Disc Art )

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#9]
Thx again for this amazing addon.

Tested the Multi Line option several times now, and it works  100% perfect for Aeon Nox Skin.

I have a new request / enhancement:

Disc Art, Aeon Nox also supports it, the Cleart Art from Fen is working in it also.
If Disc Art is possible, that would be very nice ( just a idea )

Greetings.

**Comment by Tikipeter** [comment]
I should be able to get Disc Art from fanart.tv, but only for movies. I'll include in next update.

**Comment by Tinuz97** [comment]
Nice, thx 👌

**Comment by Tikipeter** [comment]
DiscArt added for next update to tikimeta and Fen. Checked in Aeon Nox and it works when disc  art is available from fanart.tv.

You will need to go to Tools->Clear List and Data Info->Clear Meta Cache to start seeing the disc art.

Any problems let me know.

**Comment by Tinuz97** [comment]
Tested, working 100%,looks great in aeon nox.

Thank you 👌
