### ISSUE TITLE
Enhancement : File size filter ( Fake Xvid links)

### ISSUE THREAD

**Issue by JayDee696969** [Tikipeter/repository.tikipeter#91]
So as you may know, theres a lot of these Xvid fake torrents out there that give you the white Xvid screen when playing a link. Now all these files are a dead giveaway because the file size is always under 1GB. Do you think putting a minimum file size option might weed these fake links out??

https://ibb.co/K2PCRJP

**Comment by Tikipeter** [comment]
Hi JayDee696969.

With the way the external scrapers are set up, it is not practical to introduce a filter based on filesize. It xould be done for Fen's internal scrapers, but I don't think that's what you are after.
