### ISSUE TITLE
ANNOUNCEMENT - Open Scrapers

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/repository.tikipeter#92]
I thought I would post an announcement here for anyone who cares about such things, that FEN will be switching to use the Openscrapers module from the OpenProject in a future update.

I have resisted this in the past, as I'm not a huge fan of the settings configurations for Open Scrapers, but the resource is there and available to use, so FEN may as well utilize it.

The results I see when using Open Scrapers is comparable to Tiki Scrapers, so there should not be a noticeable issue for most users.

The main reasons for switching are...
* Tikiscrapers was always meant to be a temporary module, with the plan always to switch to Openscrapers in the future.
* Whilst the Tikiscrapers module was maintained by me, I VERY rarely was the person fixing/making new scrapers. I was grabbing scrapers from many other projects, and combining them into Tikiscrapers. Whilst I acknowledged this at the top of the Tikiscrapers changelog, it never sat well with me, and I was always eager to stop using tikiscrapers as soon as possible.
* I'd much prefer to not have a scraper module included in my repository if possible, for various reasons. Some of which I'm sure you can appreciate.

Changes to FEN as a result of switching to Open Scrapers...
* Fen will no longer be able to import and use multiple different scraper modules. This was a Tikiscrapers feature that will not be brought over with the change.
* There should be no other changes/issues with using FEN... hopefully.

IMPORTANT NOTE FOR FURK USERS:
Open Scrapers includes a Furk scraper, which is normally activated when you enter your username/password in Openscrapers settings. Since Fen scrapes Furk with it's own internal scraper, the Furk scraper from Openscrapers will be removed by Fen before a search is performed, so as Furk will not be called twice for results. So leave FEN's Internal Furk scraper ON if you want Furk results. I'm hoping to write an Easynews scraper for Openscrapers in the future, and the same advice will apply in that case as well.

Any questions regarding this change, please leave a message below.

**Comment by Tinuz97** [comment]
Thx for the announcement, I always read this kind of information 👍

**Comment by jjred1977** [comment]
Is there a way to leave the import ability in the addon but remove tikiscrapers?

**Comment by acf150** [comment]
When will this update to Fen be coming? Does the end user have to do anything on their side for the switch over to open scrapers? Or will the update do everything needed? Will the Tiki scrapers module disappear and change to open scrapers on it's own or will we need to uninstall it? Can you please explain more on what will happen with this update and what we as Fen users need to do anything on our end? Thank you for such a great addon! Happy new years! 👍

**Comment by Tikipeter** [comment]
To jjred1977:
There is a way to re-code the import ability into Fen directly, but I won't be doing it. Maybe in a later update I will add it back, but not for now. Openscrapers is due a big update to v2, and I don't know what it will involve. I may just have to remove the feature again when that happens. So it's a watch and wait situation at the moment.

To acf150:
Update will PROBABLY be a few hours after me writing this.

I updated the tikipeter Repo a few days ago so it now includes a link to the OpenProject Repository. This should mean when the new version of Fen is uploaded, Kodi will see the new dependency on Openscrapers, and install it from the Tikipeter Repository.

Unfortunately, in the past Kodi sometimes does not do what it's supposed to do, and the update fails. I cannot test this properly as I would need to upload the new Fen version to the repository to test it, which then makes it live for everybody. It's basically a case of me doing what needs to be done beforehand, and then uploading the update and hoping for the best.

As a user, the LEAST you will need to do, if everything goes correctly, is accept the update for Fen when it is available. If you have automatic updates enabled, Kodi will do that itself and will require no interaction from you. After that, if you wish to do so, so as to keep a clean running Kodi, you can go in and remove the Tikiscrapers module. It will now show as "Orphaned" and Fen will not have it as a dependency anymore.

I will write another announcement when I upload he update, outlining what needs to be done should something go wrong with the update. But with a worst case scenario, it will basically involve the update failing. The version of Fen you are currently using will still work whilst the failed update is fixed. You shouldn't be left with Fen not working due to the update. :)

**Comment by brentonv** [comment]
Are TikiScrapers remaining for the time being or is there a way to uninstall it from the add-on database? It no longer shows as a dependency so I'm not sure how to remove it.

**Comment by Tikipeter** [comment]
Just remove it as you would any other Orphaned dependency.

**Comment by Tinuz97** [comment]
Let's hope openscrapers 2.0 will be better, because i already miss tikiscrapers, much faster and better results for me scraper wise.

**Comment by Tikipeter** [comment]
Tikiscrapers has been removed from the repository. I'll close this announcement.

**Comment by brentonv** [comment]
> Just remove it as you would any other Orphaned dependency.

Sorry but I'm not aware how to do this if it has been removed from the add-on dependencies which is why I asked.

**Comment by southpaw99** [comment]
Thank you for the announcement  appreciate your hard work

**Comment by southpaw99** [comment]
Thank you for the announcement and your hard work keeping your addon up to date and for keeping everyone in the loop so thank you
