### ISSUE TITLE
Exclude “Audio Description” Audio Tracks

### ISSUE THREAD

**Issue by barronen1** [Tikipeter/repository.tikipeter#93]
Hi 

I’m using Auto Play feature for movies/episodes (automatically selects the first link in results)

Is it possible to exclude in results Audio Description links? I choose English as defaults Audio language to select in Kodi, but sometimes I get Audio Description movies/episodes.

**Comment by Tikipeter** [comment]
No, unless they include information in the filename to let me discern when it's a file with "Audio Description".

Otherwise that can't be known until the file starts playback.
