### ISSUE TITLE
FEN working very slow

### ISSUE THREAD

**Issue by ANHBOB** [Tikipeter/repository.tikipeter#94]
First I want to say I appreciate everything you do with FEN. I hope you had a good holiday as well. Ever since the last 2 updates FEN has been working very slow. When I go to my trakt list...watchlist for movies..after the sync trakt to FEN takes place...before it only took about 25-30 seconds to display my watchlist. Now it's taking around 8-10 minutes...and some of the movies that I have in my watchlist do not show up. I have checked on the Trakt website and it still shows the movies I've chosen in my watchlist but not in FEN? Also it shows I've watched the movie 2 times on the Trakt web site but I've only watched it once.

**Comment by Tikipeter** [comment]
Hi ANHBOB.

Firstly, there are a couple of settings you can check are set a certain way and retry your Watchlist:
* In Settings->General->Navigation set "Use Threading for Menu Items" to OFF.
* In Settings->Trakt->Trakt Navigation set "Choose Max Trakt List items" to 20.
* Go to Tikimeta Settings (from within Fen, navigate to Settings and select "Tikimeta Settings") and turn off "Include Extra Art" (fanart.tv has been having API issues again lately).

Check your Watchlist after setting those settings (also, don't wait 8-10mins for your Watchlist to load. If it is not loading in roughly the same time as it used to, hit the back button to cancel the loading. I'd say if it hasn't worked after 1 min, then it isn't going to work).

If your issue is solved with the settings above, let me know.

Otherwise some questions:
* How many items in your Movie Watchlist?
* Do your other Trakt lists work as expected (Collection, Liked Lists etc)?
* Do other Movie lists in Fen work as expected (Trending, Popular etc)?
* Do you have a Watchlist for TV Shows, and if so does it work as expected?

**Comment by ANHBOB** [comment]
My settings> Use threading for Menu IS OFF
Settings>Trakt Navigation> Choose Max list WAS set to 40, now I've changed it to 20
In Tikimeta Settings> Include Extra Art IS OFF
After changing the settings it did NOT resolve the problem.  Last night I also deleted Real Debrid and Trakt authorizations then added them back to see if it would help but didn't.
I only have about 40 Movies in my Watchlist. 
My TV show collection is working slow...the same as the Movie Watchlist
I only have 1 Watchlist for Movies and 1 Collection list for TV shows.
I don't know why but it started after the update 2 updates ago.  Also it's back to showing watching 2 of the same movie.

**Comment by Tikipeter** [comment]
I forgot to ask what device you are running Kodi and Fen on ANHBOB?

**Comment by ANHBOB** [comment]
I'm using the 4K Firestick. I've had it for over 9 months without any problems.
Yes the regular FEN menus load normally.

**Comment by Tikipeter** [comment]
Firstly...
* In Settings->Playback->Indicators set "Sync Fen Watched Info with Trakt Watched Info" to OFF.
* In Settings->Trakt->Trakt Navigation set "Choose Max Trakt List items" to 10.
* In Settings->Trakt->Trakt Cache make sure "Refresh Trakt Cache On Each Kodi Startup" is set to OFF.

Please do one of the following:
* If you are comfortable and know how to navigate using Kodi's File Manager, go into "File Manager->Profile directory->addon_data->script.module.tikimeta" and delete the "metacache3.db" file. If there are any other numbered metacache.db files, delete them as well. Then go to "plugin.video.fen" and delete the "fen_trakt" file. RESTART KODI (important) and see if there is an improvement opening your Watchlist.
* Alternately, navigate to Tools->Clear List and Data Info and select "Clear Meta Cache" and then "Clear Trakt Cache". RESTART KODI and see if there is an improvement opening your Watchlist.

If none of this works, you will have to send through a log file after trying to enter your Watchlist. There may be nothing for me to see in the log, in which case I would have to make you a special build with extra logging to get to what the trouble is.

**Comment by ANHBOB** [comment]
Well I've changed everything you mentioned and still hasn't helped.

I'm unable to do this: f you are comfortable and know how to navigate using Kodi's File Manager, go into "File Manager->Profile directory->addon_data->script.module.tikimeta" and delete the "metacache3.db" file. If there are any other numbered metacache.db files, delete them as well. Then go to "plugin.video.fen" and delete the "fen_trakt" file. RESTART KODI (important) and see if there is an improvement opening your Watchlist....unless you know of a program I can use with the Firestick so I can access the file manager?

The only addons I have installed are: FEN, The Crew, You Tube, f4m Tester, OpenWizard, Tiki Scrapers Module, Tiki Meta Module, F4mProxy, Trakt, and python module InputStream Helper.
Everything is up to date with the latest versions. I am NOT using any builds.
Many times when there is an update for FEN or anything related to FEN, there seems to also be an update for The Crew related addon.  Maybe that's what happened when there was an update for FEN at the same time as The Crew something clashed in the updates which is causing this?

**Comment by Tikipeter** [comment]
The File Manager is built in to Kodi. If you are using the default skin (Estuary) then you get to it by selecting the small 'cog' like icon (Settings) at the top of the main home menu. The File Manager is the first item on the settings page.

If you still can't use the File Manager successfully, don't worry, just do the other suggestion I made (Clearing the Caches from within Fen). I don't think it's going to help, though. There is something wrong with your setup.

If clearing the caches or deleting them through the File Manager doesn't xhange anything, you will have to restart Kodi, navigate into your Watchlist, and then grab the logfile and upload it and share the link here.

**Comment by Tikipeter** [comment]
I have uploaded a couple of test builds for you to try ANHBOB.

If you installed my repository the way most guides tell you to, you should have added a 'source' with my repo address to Kodi's File Manager. Navigate to there now, and you will see a test version of both Fen (plugin.video.fen-1.5.83b_test_build.zip) and Tikimeta (script.module.tikimeta-1.1.29a_test_build.zip). Go to Addons then Install from zip file, and install both these test versions. With the test versions, hopefully you will get a proper error somewhere within the line of tring to get Watchlist items to display, and then you can send me that error log and I'll hopefully be able to fix your issue.

**Comment by ANHBOB** [comment]
I'll have to try that when I get home...I'm working now so it won't be til later.
I did try it this morning and the watchlist loaded faster...about 30 seconds.  Then I went to Tools..delete settings and also delete all cache.  After doing that and restarting Kodi, it took about 4-5 minutes to show me my watchlist instead of almost 10 minutes, BUT in the past when I've cleared all cache the watchlist would still load in less than 1 minute.

**Comment by Tikipeter** [comment]
Yeah, 4-5mins is not acceptable either. It sounds like something to do with the metadata.

**Comment by ANHBOB** [comment]
Sorry I haven't responded in  a couple of days but with work and the holiday I've been busy.  FEN seems to be working a lot better now so you can delete the test files from your repo. I followed your instructions and now it's working the way it used to.

If you are comfortable and know how to navigate using Kodi's File Manager, go into "File Manager->Profile directory->addon_data->script.module.tikimeta" and delete the "metacache3.db" file. If there are any other numbered metacache.db files, delete them as well. Then go to "plugin.video.fen" and delete the "fen_trakt" file. RESTART KODI (important) and see if there is an improvement opening your Watchlist.

I deleted the metacache3.db file, and I also had a metacache2.db file which I deleted. And I deleted the fen_trakt file.

I never knew they were there because I never looked into that folder. Others had said before about needing a program like es file explorer to get to those files because I'm using a Firestick.  Then other people said not to use es file explorer so I uninstalled it.

Thank you for taking your time to help me resolve the issue. I appreciate it.

**Comment by Tikipeter** [comment]
That's good to hear ANHBOB. I'll close this for now. :)
