### ISSUE TITLE
Context menu homescreen options

### ISSUE THREAD

**Issue by JFG1000** [Tikipeter/repository.tikipeter#94]
![20221221_115337](https://user-images.githubusercontent.com/76907836/208899454-6680532c-ca3f-480b-9a5b-50aa23cec0d4.jpg)

Hi mate just put out of curiosity was Mark was watched trakt and clear progress removed from the homescreen context menu options? Noticed it this morning as I used them quite often and not can't acess them unless I go into the addon directly, many thanks

**Comment by Tikipeter** [comment]
I'll fix it for next update.

If you want it sorted out before then, you can go into Fen's `addon.xml` and change the 3 instances of `fen_widget` to `fen.widget` and restart Kodi and they will appear again.

**Comment by JFG1000** [comment]
Thanks mate, it's ok no worries I'm happy to wait, many thanks

**Comment by barronen1** [comment]
@JFG1000 How you've made Fen to look like this?

**Comment by JFG1000** [comment]
My own personal created build

**Comment by barronen1** [comment]
Are you able to share it? I’ve liked it

**Comment by JFG1000** [comment]
Apologies but no, it's not public
