### ISSUE TITLE
Hidden spoiler

### ISSUE THREAD

**Issue by sasagr** [Tikipeter/repository.tikipeter#95]
I have on kodi settings to hide spoiler plot and poster on the tv shows but somehow Fen override this setting and it shows the plot when I play from results and if I m not mistaken also in the results page. Could it be possible for fen to follow general kodi settings on this or eventually to have a separate setting within the addon to hide spoiler?
Cheers

**Comment by Tikipeter** [comment]
I can do a setting within Fen.

Can I instead show the TV Show overview instead of the Episode plot when the setting is ON?

**Comment by sasagr** [comment]
Yes. Good idea!

**Comment by Tikipeter** [comment]
Added for next update. :)

Settings->Navigation->Content->"Suppress Episode Plot in Fen Custom Windows".

Will show tvshow overview if available, else `* Hidden to Prevent Spoilers *` like Kodi does.

**Comment by Tikipeter** [comment]
Changed for the results window and also the resolve window, like you mentioned in OP.

I looked and I think that's the only 2 windows that show episode plot that are custom Fen windows.

Open a new Issue if you find any more. :)
