### ISSUE TITLE
Openscrapers (latest update) 

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#96]
All information is gone (for me) in the links, like blu-ray, HDTV, WEB-DL, is it is x264, or x265 etc.
I only see info like this:

EXT |1080P|PM CACHED|1337x |TORRENT (first line, I use multi line in aeon nox silvo mod).
Seconde line only the file size, before I got also if it it blu-ray, HDTV, WEB-DL etc etc.
Is this just me?
I realy miss this information.

**Comment by Tikipeter** [comment]
Thanks Tinuz97.
I'll push a quick fix for this now. :)

**Comment by Tinuz97** [comment]
Thx 🤟

**Comment by Tinuz97** [comment]
Working 100% with quick fix, thx 🍻
