### ISSUE TITLE
Filtering Real Debrid results by Language audio

### ISSUE THREAD

**Issue by barronen1** [Tikipeter/repository.tikipeter#98]
Hi,

I know it is possible to configure in Kodi settings the preferred audio stream language (for example English will be selected between ENG and ITA).

Is it possible in Fen settings to configure to search only links with specific Language audio stream specified?
And it not, is it possible to add this feature?

And another question,
I've uploaded an example movie to Real Debrid (The Lion King movie - hebrew langauge dubbed)
But can't find it in Fen search results, what is required for Fen to find it? the files does exist in Real Debrid.
Real Debrid Link:  XXXXXX
Real Debrid Download Link: XXXXXX

Thank you

**Comment by Tikipeter** [comment]
For Fen to find the copy of the movie in your RD Cloud, Turn on Settings->Provider Accounts->Real Debrid->Search RD Cloud.

As for filtering out specific languages during results gathering, it is not possible.

**Comment by barronen1** [comment]
I see, thank you. 

But it will only search in my private RD cloud of my account right?

If so, do you know how can I make my uploaded movie public to search results of Fen/any other Real Debrid addon?

**Comment by Tikipeter** [comment]
>If so, do you know how can I make my uploaded movie public to search results of Fen/any other Real Debrid addon?

To guarantee that happening, you would need to add a torrent file to your cloud from a torrent site that is also scraped by the addon.

Addons sends the hashes of the torrent files it gets in results to the debrid providers. They then return information as to whether they currently have a torrent upload with a matching torrent file on their servers.

If you did that and the movie is not showing, and also you have that scraper enabled, then you likely need to do a fresh scrape for new results.

**Comment by barronen1** [comment]
What I’ve did is to copy a magnet link of movin torrent from RARBG site, and pasted the magnet link to RD, and he downloaded the file and gave me link. 

What do you think?

**Comment by Tikipeter** [comment]
The TorrentAPI scraper gets results from RARBG.

**Comment by barronen1** [comment]
That’s what I thought, but still can’t find my uploaded link (he’s different because he have HEB audio track), that’s why maybe the option to search/filter by audio language tracks would help

But there are too many links for the movie, will Fen show every torrent it’s finds? or with a limit?

**Comment by Tikipeter** [comment]
Every torrent it finds that is within the filters you have set.

You could go into Tools->Clear Databases & Clean Settings Files and select to "Clear External Scrapers Cache". Then re-scrape the movie and see if it appears.

If that doesn't work, then we're getting into a scraper issue which I will not be able to help with, as I do not maintain the external scrapers.

**Comment by barronen1** [comment]
Thank you, I’ll try it. 

In addition, I think maybe some data need to be configured in the torrent/movie file metadata for the scrapers to find it easier (like name, quality, year, langauge, etc). And my movie file name in the torrent is named:
“toy story hebrew dubbed 1995”

do you know anything about it?

**Comment by Tikipeter** [comment]
No, I don't know anything about it.
