### ISSUE TITLE
Next Up Episode 

### ISSUE THREAD

**Issue by xyzfre** [Tikipeter/repository.tikipeter#98]
Noticed yesterday next Up episode wasn’t working and After watching a TV show it will not mark as watched so I tried with a different addon to check and it worked ,after finishing a show it Mark as watched and then the next episode showed up as well using a different addon Just wanted to report it don’t know if it’s a bug or something on my end appreciate all your hard work with Fen and love the open scrapers you add it Great work

**Comment by xyzfre** [comment]
I cleared all cache within Fen and reauthorize Trakt as well ,,it’s almost like it’s not communicating with Fen ,, Also notice after watching something You always get the pop-up to give it a rating through Trakt and that doesn’t show up either ,,sorry to bother just trying to sort this out

**Comment by Tikipeter** [comment]
Let me know the name of the show and i will test it out.

**Comment by xyzfre** [comment]
Tom Clancy’s Jack Ryan

**Comment by xyzfre** [comment]
> Let me know the name of the show and i will test it out.

I guess it has something to do with that TV show just tested it with a different TV show which I should’ve done first ,,sorry ,,,and everything works fine next up worked and the pop up for Trakt Ratings showed up as well ,, First time I see this happen with a show weird,, Glad it wasn’t nothing on my end thank you for your response and all your hard work ,,Fen is the best I use Nvidia shield pro with AuraMod skin and Fen for all my widgets pretty much for everything and works flawlessly

**Comment by xyzfre** [comment]
The only weird thing is using a different addon for this show does mark it as watched

**Comment by Tikipeter** [comment]
Yep, I'm going to have a look at it when I get a chance. Could be one of a couple of things.

**Comment by Tikipeter** [comment]
Well, the show worked the way it should for me with marking watched and next episodes, so I don't know what was happening?! It was neither of the couple of things I thought it might be.
